- examples/login.rs
- src/async_client.rs
- src/base_client.rs
- src/crypto/machine.rs
- src/crypto/memory_stores.rs
- src/crypto/olm.rs
- src/crypto/store/memorystore.rs
- src/crypto/store/mod.rs
- src/crypto/store/sqlite.rs
- src/event_emitter/mod.rs
- src/models/mod.rs
- src/models/room.rs
- src/models/room_member.rs
- tests/async_client_tests.rs
Resolves #7 
Resolves #8 
Signed-off-by: Devin Ragotzy devin.ragotzy@gmail.com
I hope it's ok for me to work on this as much as I am, I am enjoying working with you?
> use RoomId and UserId over string, use setter method names in Room

- Cargo.toml
- src/async_client.rs
- src/base_client.rs
- src/error.rs
- src/models/room.rs
Not sure how to handle the error, what is there is an associated type on the `Endpoint` trait (so a big type mess). We don't want to panic for this right?
> async_client/error: dont swallow response error in `AsyncClient::send`

- src/base_client.rs
- src/event_emitter/mod.rs
- src/models/room.rs
- src/request_builder.rs
- src/test_builder.rs
- tests/data/events/aliases.json
- tests/data/events/name.json
- tests/data/sync_with_summary.json
I hope this is focused enough, if not I can separate them into 2 PRs.
> Add tombstone event handling/emitting, fix panic in calculate name

- matrix_sdk/src/async_client.rs
- matrix_sdk/src/base_client.rs
- matrix_sdk/src/state/mod.rs
- matrix_sdk/src/state/state_store.rs
- matrix_sdk/src/test_builder.rs
I think the `store_client_state` taking a `Session` works perfectly thanks for helping me along! Here is everything that was reviewed on the last PR.
By the way the workspaces look good!
> state_store: load_client takes a sessions obj, docs, copyright, ect.

- matrix_sdk/src/async_client.rs
add endpoints for typing notifications and read receipts, ban user and forget room.
> More endpoints for AsyncClient

- matrix_sdk/examples/command_bot.rs
- matrix_sdk/examples/login.rs
- matrix_sdk/src/client.rs
- matrix_sdk/src/lib.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/event_emitter/mod.rs
- matrix_sdk_base/src/lib.rs
- matrix_sdk_base/src/models/message.rs
- matrix_sdk_base/src/state/mod.rs
- matrix_sdk_base/src/state/state_store.rs
This is the only thing I had in a `rumatui` branch, I got everything working it wasn't too bad!
> client: add store_room_state method

- matrix_sdk/Cargo.toml
- matrix_sdk_base/Cargo.toml
- matrix_sdk_base/src/models/message.rs
Would something like this be a good workaround, since because of workspaces you can't run the tests with any features not enabled by default?
> add the `messages` feature to dev-deps so the tests are run

- matrix_sdk/src/client.rs
- matrix_sdk/src/error.rs
- matrix_sdk/src/lib.rs
- matrix_sdk/src/request_builder.rs
- test_data/registration_response_error.json
Not sure how you feel about the `Client::send_uiaa` method, I wasn't able to factor out any of the "shared" code?
> add `register_user` method to `Client`

- matrix_sdk_base/src/client.rs
Also some FIXMEs about future restructuring.
> Fix and test hoisting of `prev_content` for timeline events.

- matrix_sdk/Cargo.toml
- matrix_sdk/examples/autojoin.rs
- matrix_sdk_base/Cargo.toml
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/models/room.rs
- matrix_sdk_base/src/models/room_member.rs
- matrix_sdk_common/Cargo.toml
- matrix_sdk_crypto/Cargo.toml
- matrix_sdk_crypto/src/machine.rs
Originally I wanted to upgrade the ruma dependency but it seems that that might actually be a bit more involved with the `EventEmitter` and checking whether an event affects room state.
> Remove unused dependencies, some refactoring

- matrix_sdk/src/client.rs
- matrix_sdk/src/request_builder.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/event_emitter/mod.rs
- matrix_sdk_base/src/models/room.rs
- matrix_sdk_base/src/models/room_member.rs
- matrix_sdk_base/src/session.rs
- matrix_sdk_base/src/state/json_store.rs
- matrix_sdk_common/Cargo.toml
- matrix_sdk_crypto/src/device.rs
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/store/sqlite.rs
Not sure what to do with the event emitter error.
CC @DevinR528
> Upgrade ruma

- matrix_sdk/src/client.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_common/Cargo.toml
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/olm/group_sessions.rs
If you don't mind, I will start doing these (semi-)regularily :)
> Upgrade ruma #2

- matrix_sdk_base/src/models/message.rs
Also add a few missing apostrophes.
> Expose `sender` in `PossiblyRedactedExt`.

- matrix_sdk/examples/get_profiles.rs
- matrix_sdk/src/client.rs
- matrix_sdk/src/error.rs
- matrix_sdk/src/lib.rs
- matrix_sdk/src/request_builder.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/event_emitter/mod.rs
- matrix_sdk_base/src/lib.rs
- matrix_sdk_base/src/models/message.rs
- matrix_sdk_base/src/models/room.rs
- matrix_sdk_base/src/models/room_member.rs
- matrix_sdk_base/src/session.rs
- matrix_sdk_base/src/state/json_store.rs
- matrix_sdk_base/src/state/mod.rs
- matrix_sdk_common/src/lib.rs
- matrix_sdk_crypto/src/device.rs
- matrix_sdk_crypto/src/lib.rs
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/memory_stores.rs
- matrix_sdk_crypto/src/olm/account.rs
- matrix_sdk_crypto/src/olm/group_sessions.rs
- matrix_sdk_crypto/src/olm/mod.rs
- matrix_sdk_crypto/src/olm/session.rs
- matrix_sdk_crypto/src/store/memorystore.rs
- matrix_sdk_crypto/src/store/mod.rs
- matrix_sdk_crypto/src/store/sqlite.rs
- matrix_sdk_test/src/lib.rs
I did this by adding a `rustfmt.toml` with `merge-imports = true` maybe we could add that file in this PR?
Do we want to use `crate` or the name of the actual mod i.e. `crate::identifiers` -> `matrix_sdk_common::identifiers`? I can do that in this PR also.
> Merge import declarations

- matrix_sdk/src/client.rs
- matrix_sdk/src/http_client.rs
- matrix_sdk/src/request_builder.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/event_emitter/mod.rs
- matrix_sdk_base/src/models/message.rs
- matrix_sdk_base/src/models/room.rs
- matrix_sdk_base/src/models/room_member.rs
- matrix_sdk_base/src/state/json_store.rs
- matrix_sdk_base/src/state/mod.rs
- matrix_sdk_common/Cargo.toml
- matrix_sdk_common/src/lib.rs
- matrix_sdk_crypto/src/device.rs
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/memory_stores.rs
- matrix_sdk_crypto/src/olm/mod.rs
- matrix_sdk_crypto/src/store/memorystore.rs
- matrix_sdk_crypto/src/store/sqlite.rs
- matrix_sdk_test/src/lib.rs
Part of the evaluation of ruma/ruma#178, can potentially be rolled up into the other active update PR (#82).
> Update Ruma once again

- matrix_sdk/Cargo.toml
- matrix_sdk/src/http_client.rs
I fully broke authentication in #83, here is the fix.
I'm sorry for yet again submitting a PR that conflicts with yours @DevinR528, but this should probably be merged first, making #84 smaller in diff too.
> Fix handling of headers in HttpClient

- matrix_sdk/Cargo.toml
- matrix_sdk/src/client.rs
- matrix_sdk/src/http_client.rs
- matrix_sdk/src/http_send.rs
- matrix_sdk/src/lib.rs
- matrix_sdk_common_macros/Cargo.toml
> matrix_sdk: Create trait and default type for sending http requests

- matrix_sdk/src/client.rs
Add direct request authentication data to registration example
> doc: Add UIAA auth data to registration example

- matrix_sdk/examples/autojoin.rs
Fixes #105 
I am sure, there is some better way to handle retries. Retrying after 2 seconds was enough every time I tested it. I am open to suggestions how to handle the case better.
I switched from printing the room display_name to room_id, since the display name was always empty for my test case (DMs).
> matrix-sdk: example: retry autojoin

- matrix_sdk_base/src/client.rs
> Implement BaseClient::get_session to retrieve the login session.

- matrix_sdk/src/client.rs
I tried to make the code fit the style of the rest of the library as well as possible. Let me know if there is feedback to address.
> Add methods for getting and setting display name

- matrix_sdk_common/Cargo.toml
We need the new version to get the fix for https://github.com/ruma/ruma/issues/380
> Update ruma to rev d6aa37c848b7f682a98c25b346899e284ffc6df7

- matrix_sdk/examples/autojoin.rs
- matrix_sdk/examples/command_bot.rs
- matrix_sdk/examples/image_bot.rs
- matrix_sdk/examples/login.rs
- matrix_sdk/src/client.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/event_emitter/mod.rs
> Rename `add_event_emitter` to `set_event_emitter`

- matrix_sdk_crypto/benches/crypto_bench.rs
This adds a benchmark for the room key sharing logic, cleans up the benchmark titles a bit and adds benchmarks to check the throughput while using the sled store.
> More benchmarks

- matrix_sdk/src/client.rs
Implement `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}`
Resolves part of https://github.com/matrix-org/matrix-rust-sdk/issues/14
> client: PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}

- matrix_sdk/src/client.rs
- matrix_sdk/src/lib.rs
- matrix_sdk/src/room/common.rs
- matrix_sdk/src/room_member.rs
This will allow use to move all the member specific request to this struct.
> matrix-sdk: Add RoomMember

- .github/workflows/ci.yml
Follow-up for #201 which aims to make sure that features work as intended
(CI fails because #201 isn't merged yet)
> ci: test features

- matrix_sdk/src/client.rs
- matrix_sdk_crypto/src/file_encryption/key_export.rs
- matrix_sdk_crypto/src/key_request.rs
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/olm/mod.rs
This PR contains a progress listener for key imports, it's needed for Element Android, though the usefulness of this is debatable so it's not exposed in the `Client` yet.
> Progress listener

- matrix_sdk/Cargo.toml
- matrix_sdk/src/http_client.rs
- matrix_sdk/src/lib.rs
As [proposed by @jplatte](https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$soYvm1OsKOknC6DdNOmRi8mo914VfKNCXJjCeMgurXs?via=matrix.org&via=gnome.org&via=queersin.space)
> matrix-sdk!: send_request returns Bytes

- matrix_sdk_test/src/lib.rs
> test: Add a method to build a sync response as a JsonValue

- matrix_sdk/src/room/common.rs
Another member method was forgotten to be overridden, returning the wrong `RoomMember`. We also add back the ability to manage the member list synchronization yourself using separate `_no_sync()` versions of the methods.
> More member methods

- matrix_sdk/src/client.rs
> client: Require a proper Url to create a client

- matrix_sdk_common/Cargo.toml
- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/olm/account.rs
- matrix_sdk_crypto/src/olm/group_sessions/inbound.rs
- matrix_sdk_crypto/src/olm/group_sessions/outbound.rs
- matrix_sdk_crypto/src/olm/session.rs
Need new type for the room tag names. Seeing as there are a few changes for encrypted events, I separated it from my work.
> bump ruma to 24154195a00390a33542603b968e94022487587c

- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/rooms/normal.rs
- matrix_sdk_base/src/store/memory_store.rs
- matrix_sdk_base/src/store/mod.rs
- matrix_sdk_base/src/store/sled_store/mod.rs
Stores them and keeps them updated. Allows to retrieve them from a room.
> base: Add support for read receipts

- matrix_sdk/src/client.rs
- matrix_sdk_appservice/examples/appservice_autojoin.rs
- matrix_sdk_appservice/src/lib.rs
- matrix_sdk_appservice/src/webserver/actix.rs
- matrix_sdk_appservice/src/webserver/warp.rs
- matrix_sdk_appservice/tests/tests.rs
context: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$X6127Eh48J6c1ZgIBrP1owH945ixAU_RwMcAkr0xCVE?via=matrix.org&via=kde.org&via=nordgedanken.dev
Part of #228
> appservice: Rename Appservice to AppService

- matrix_sdk/src/room/common.rs
> Respect room visibility while making automatic requests to fetch members

- matrix_sdk_crypto/src/verification/sas/sas_state.rs
… instead of SasV1ContentInit.
> crypto: Store key::verification::start::SasV1Content

- matrix_sdk_crypto/src/machine.rs
- matrix_sdk_crypto/src/olm/account.rs
There is no reason to use different logic when updating one-time key counts coming from an upload response vs when coming from a sync response.
Switch to an AtomicU64 for the count as well, the i64 is probably a remnant of the SQLite based crypto store.
> crypto: Streamline how we update one-time key counts

- matrix_sdk/src/event_handler/mod.rs
- matrix_sdk_base/src/client.rs
- matrix_sdk_base/src/lib.rs
Fixes #292 
Signed-Off-By: Sorunome <mail@sorunome.de>
> use hoist_and_deserialize for state events

- matrix_sdk/src/client.rs
- matrix_sdk/src/room/joined.rs
- matrix_sdk_crypto/src/verification/machine.rs
- matrix_sdk_crypto/src/verification/mod.rs
- matrix_sdk_crypto/src/verification/requests.rs
clippy got smarter, so we can improve the code, yay
> Fix clippy warnings

- matrix_sdk/src/room/joined.rs
Fixes #250.
Adds helper functions for creating, updating and removing room tags.
> matrix-sdk: Add helpers for room tags

- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/store/caches.rs
- crates/matrix-sdk-crypto/src/store/memorystore.rs
- crates/matrix-sdk-crypto/src/store/sled.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/joined.rs
This simplifies the event sending examples and fixes a small issue with the
verification requesting.
> Two small fixes

- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/README.md
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/room/joined.rs
This PR improves our docs for the sync methods, adds a method to sync as an async
stream and fixes some usability issues with logging in.
This PR closes: #245.
> Clean up and improve the Client docs

- crates/matrix-sdk-appservice/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/README.md
- crates/matrix-sdk/src/event_handler.rs
Fixes #324
Fixes #347
Supersedes #348
> Fix the anyhow feature

- crates/matrix-sdk/src/encryption/verification/requests.rs
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/367
> encryption: Expose FlowId on VerificationRequest

- crates/matrix-sdk/src/encryption/verification/requests.rs
- crates/matrix-sdk/src/error.rs
We need to tell the other side that we scanned there Qr Code.
> matrix-sdk: Send reciprocate to other side when calling VerificationRequest::scan_qr_code()

- crates/matrix-sdk-crypto/src/lib.rs
- crates/matrix-sdk-crypto/src/verification/mod.rs
- crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
- crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
- crates/matrix-sdk/src/encryption/verification/mod.rs
- crates/matrix-sdk/src/encryption/verification/sas.rs
> Use an struct for the emoji/description pairs.

- crates/matrix-qrcode/src/error.rs
- crates/matrix-qrcode/src/lib.rs
- crates/matrix-qrcode/src/types.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/error.rs
- crates/matrix-sdk-base/src/lib.rs
- crates/matrix-sdk-crypto/src/lib.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/verification/cache.rs
- crates/matrix-sdk-crypto/src/verification/mod.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-test/src/appservice.rs
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/config/request.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/encryption/verification/mod.rs
- crates/matrix-sdk/src/encryption/verification/requests.rs
- crates/matrix-sdk/src/error.rs
- crates/matrix-sdk/src/lib.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/joined.rs
> docs: Remove the now unneeded doc cfg attributes

- crates/matrix-sdk-appservice/examples/appservice_autojoin.rs
- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk-appservice/tests/tests.rs
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/event_handler.rs
> Custom event handler context

- crates/matrix-sdk-base/src/media.rs
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/room/joined.rs
See #406 for details.
I've also added a commit which refactors `Joined::send_attachment` to use `*MessageEventContent::encrypted` instead of manually modifying the struct (and simplifies the implementation overall in my opinion). As the implementation of `encrypted` in ruma does not set the url this would also avoid problems for other clients which exhibit the same (incorrect) behavior as the sdk did until this PR. I can also drop this commit if you don't like it, though.
> Correctly handle MediaType of encrypted files that also include a url to the encrypted blob

- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-base/src/session.rs
On a recent [live stream](https://diode.zone/w/uSPoZBCu6zs2fNmsotHRiK?start=38m15s) I spent ages trying to create a `matrix_sdk::Session`.
I think I worked out the right way to make one, but if I did it wrong, please let me know and I'll update the PR.
> Document how to create a Session

- crates/matrix-sdk-crypto/src/identities/manager.rs
Users of the crypto crate should mark all members that are part of an E2EE room for tracking, this will of course mark your own user for tracking.
If the crypto crate user doesn't have any E2EE rooms he may not add any members to be tracked. The user might still want to inspect their own E2EE devices and identities. This patch makes sure that our member is tracked.
> Automatically track your own user if the caller doesn't do so

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
> Degrade some logs that show user ids to the debug log level

- crates/matrix-sdk-appservice/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-base/examples/state_inspector.rs
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/file_encryption/key_export.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/http_client.rs
Dashmap was skipped because of: https://github.com/xacrimon/dashmap/issues/167
Image was skipped because rqrr needs a new release: https://github.com/WanzenBug/rqrr/pull/12
This closes #469.
> chore: Upgrade our deps

- .github/workflows/docs.yml
Regression introduced in f12f03b8daec4f198b48261564d6f142c553ce67.
> fix(doc): Build nightly docs with correct features

- crates/matrix-sdk/src/client.rs
Useful to know if we can change the user password, among other things.
> feat(sdk): Add method to get homeserver capabilities

- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/lib.rs
Move account-related methods on `Client` to the new `Account` struct and add new methods.
I cloned the whole client instead of the `HttpClient`, like discussed in the matrix room, to be able to use methods like `upload` or `get_media_content`.
> Create Account struct

- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-base/examples/state_inspector.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
- crates/matrix-sdk/src/config/client.rs
- crates/matrix-sdk/src/http_client.rs
- crates/matrix-sdk/src/lib.rs
- Documenting how to use a custom http client via `reqwest::ClientBuilder`
- use `user_aget`-API to make the code more consisce.
> Minor improvements on ClientConfig

- labs/README.md
This adds a `labs` folder for experimental crates, code, and other misc items.
> Add `labs/` folder

- crates/matrix-sdk/src/client.rs
This allows to get a specific SSO-URL for a provider (E.g. https://matrix.org/_matrix/client/v3/login/sso/redirect/oidc-apple?redirectUrl=example.com for Apple), instead of just a generic URL. (Like https://matrix.org/_matrix/client/v3/login/sso/redirect?redirectUrl=example.com)
> Add methods for authenticating with a SSO-Provider

- crates/matrix-crypto-ffi/Cargo.toml
- crates/matrix-crypto-ffi/README.md
- crates/matrix-crypto-ffi/build.rs
- crates/matrix-crypto-ffi/src/backup_recovery_key.rs
- crates/matrix-crypto-ffi/src/device.rs
- crates/matrix-crypto-ffi/src/error.rs
- crates/matrix-crypto-ffi/src/lib.rs
- crates/matrix-crypto-ffi/src/logger.rs
- crates/matrix-crypto-ffi/src/machine.rs
- crates/matrix-crypto-ffi/src/olm.udl
- crates/matrix-crypto-ffi/src/responses.rs
- crates/matrix-crypto-ffi/src/users.rs
- crates/matrix-crypto-ffi/src/verification.rs
This imports the bindings of the crypto crate from https://github.com/vector-im/element-android/pull/3209/ into the repo.
The CI hasn't been yet hooked up, the idea is to eventually let CI build the bindings as well. @ganfra intends to work on the Element Android packaging setup and the CI setup to do this.
> feat: Import the Uniffi based matrix-sdk-crypto bindings

- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk-appservice/tests/tests.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-crypto/benches/crypto_bench.rs
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/requests.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-indexeddb/src/lib.rs
- crates/matrix-sdk-sled/src/lib.rs
- crates/matrix-sdk/examples/autojoin.rs
- crates/matrix-sdk/examples/command_bot.rs
- crates/matrix-sdk/src/client.rs
- crates/matrix-sdk/src/config/client.rs
- crates/matrix-sdk/src/store.rs
> Builder / constructor function cleanup

- crates/matrix-sdk/src/client/builder.rs
> Detect invalid .well-known endpoint response

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
> Make room invitations for previously-left rooms work

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-indexeddb/src/safe_encode.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-sled/src/cryptostore.rs
- crates/matrix-sdk-sled/src/encode_key.rs
- crates/matrix-sdk-sled/src/lib.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
Lots of small cleanup changes and a few select edge case behavior changes. Mostly based on what I noticed when upgrading Ruma.
> Post Ruma upgrade cleanup

- crates/matrix-sdk-base/src/rooms/mod.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/state_store.rs
- labs/sled-state-inspector/src/main.rs
> chore(base): Make fields of RoomInfo and BaseRoomInfo private

- .github/workflows/wasm.yml
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/examples/wasm_command_bot/Cargo.toml
- crates/matrix-sdk/examples/wasm_command_bot/package.json
- crates/matrix-sdk/examples/wasm_command_bot/src/lib.rs
- crates/matrix-sdk/examples/wasm_command_bot/webpack.config.js
- crates/matrix-sdk/src/sync.rs
- xtask/src/ci.rs
> Fix the WASM example

- crates/matrix-sdk-indexeddb/src/safe_encode.rs
- crates/matrix-sdk-sled/src/state_store.rs
> fix(state-store): ensure counter consistency

- crates/matrix-crypto-ffi/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
New typos release immediately found more instances of the typos from #563 😄
> chore: Fix typos

- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/error.rs
> feat(sdk): Merge HttpError::{Api, ClientApi}

- crates/matrix-sdk-indexeddb/src/cryptostore.rs
- crates/matrix-sdk-indexeddb/src/lib.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/cryptostore.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/src/store.rs
> fix(sled): Don't derive a StoreCipher twice if we're reusing the db

- crates/matrix-sdk/src/error.rs
- crates/matrix-sdk/src/lib.rs
Otherwise the type is not public.
> fix(sdk): Export RumaApiError

- crates/matrix-crypto-ffi/src/machine.rs
- crates/matrix-crypto-ffi/src/olm.udl
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-crypto/src/machine.rs
> Handle unencrypted verification events

- benchmarks/Cargo.toml
- crates/matrix-crypto-ffi/Cargo.toml
- crates/matrix-crypto-ffi/src/logger.rs
- crates/matrix-qrcode/Cargo.toml
- crates/matrix-sdk-appservice/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/file_encryption/attachments.rs
- crates/matrix-sdk-crypto/src/file_encryption/key_export.rs
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-store-encryption/Cargo.toml
- crates/matrix-sdk-test-macros/Cargo.toml
- crates/matrix-sdk-test/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- labs/sled-state-inspector/Cargo.toml
- xtask/Cargo.toml
The notable exceptions are:
1. Zeroize - Blocked on vodozemac
2. xshell - Requires code changes
3. image - Blocked on [qrcode-rust](https://github.com/kennytm/qrcode-rust)
4. rqrr - Same as image
> chore: Bump most of our deps

- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-sled/src/cryptostore.rs
- crates/matrix-sdk-test/Cargo.toml
- crates/matrix-sdk-test/src/test_json/events.rs
- crates/matrix-sdk-test/src/test_json/members.rs
- crates/matrix-sdk-test/src/test_json/mod.rs
- crates/matrix-sdk-test/src/test_json/sync.rs
- crates/matrix-sdk/Cargo.toml
fix #576 
Signed-off-by: cutecutecat <starkind1997@gmail.com>
> replace lazy_static with once_cell

- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
Document `OlmDecryptionInfo` and fix some errors.
> Document `OlmDecryptionInfo` and make it `pub(crate)`.

- .github/workflows/benchmarks.yml
- benchmarks/benches/crypto_bench.rs
- crates/matrix-sdk-crypto/src/store/integration_tests.rs
- crates/matrix-sdk-indexeddb/src/cryptostore.rs
- crates/matrix-sdk-sled/src/cryptostore.rs
> Fixing benchmarking

- crates/matrix-crypto-ffi/src/machine.rs
- crates/matrix-crypto-ffi/src/olm.udl
- crates/matrix-crypto-ffi/src/responses.rs
> [crypto-ffi] Add RoomMessage in RequestType

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/store/ambiguity_map.rs
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/store/caches.rs
- crates/matrix-sdk-crypto/src/store/memorystore.rs
- crates/matrix-sdk-crypto/src/verification/cache.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk-test/src/lib.rs
First commit was originally in #627, then I noticed some other things and created a new PR so it's easier to review.
> Some refactorings

- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-sled/src/state_store.rs
> feat(sled): Add state store db schema version support

- crates/matrix-crypto-ffi/README.md
Well, I need to start somewhere.
> docs(crypto-ffi) Fix a typo in the `README.md`

- Cargo.toml
Align with ruma: https://github.com/ruma/ruma/commit/a5c3af4a9af3c4fd59c4f8eec8be3810f0258c55
> chore: Use resolver2 for workspace

- crates/matrix-sdk-indexeddb/src/cryptostore.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/cryptostore.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk-store-encryption/src/lib.rs
- crates/matrix-sdk/src/client/mod.rs
… to make the code a bit more readable.
> Use convenience API bits from serde & anyhow

- crates/matrix-sdk-ffi/src/backward_stream.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/examples/cross_signing_bootstrap.rs
- crates/matrix-sdk/examples/emoji_verification.rs
- crates/matrix-sdk/examples/get_profiles.rs
- crates/matrix-sdk/examples/image_bot.rs
- crates/matrix-sdk/examples/login.rs
- crates/matrix-sdk/examples/timeline.rs
- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/attachment.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/joined.rs
… extra anyhow::Result usage in examples might also make less people ask about more `From<_>` impls for `matrix_sdk::Error` 😉
> Some more QOL improvements

- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
- crates/matrix-sdk-crypto/src/olm/utility.rs
This patch collects our json signing logic into a single place.
> refactor(crypto): Introduce a SignJson trait

- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
- crates/matrix-sdk-crypto/src/olm/utility.rs
> Simplify the signature verification logic

- crates/matrix-sdk-appservice/src/lib.rs
This PR adds support for appservice logins[^1] in matrix-sdk and matrix-appservice-sdk, which are currently needed for end-to-end-encrypted application services.
matrix-appservice-sdk can now take a persisted device id for virtual users. If e2ee is enabled, it will automatically perform an appservice login to create the session for the virtual user.
[^1]: https://spec.matrix.org/v1.2/client-server-api/#appservice-login
> Add support for appservice login

- Cargo.toml
Let's see whether this also improves macOS CI times.
> chore: Optimize quote even in debug mode

- crates/matrix-sdk-crypto-ffi/src/machine.rs
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/types/backup.rs
- crates/matrix-sdk-crypto/src/types/mod.rs
- crates/matrix-sdk-crypto/src/types/one_time_keys.rs
This is the first step for #709. The FFI side is not yet modified, will come in a separate PR. Depends on #724.
> Improve the backup verification API

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/store/integration_tests.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-indexeddb/src/lib.rs
- crates/matrix-sdk-sled/src/lib.rs
- crates/matrix-sdk/examples/autojoin.rs
- crates/matrix-sdk/examples/command_bot.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/http_client.rs
- labs/sled-state-inspector/src/main.rs
cc @Anderas, this should make it possible to implement the same builder API in the bindings, should be helpful for #739. I can also take care of implementing that though, if you prefer.
> Some builder improvements

- bindings/matrix-sdk-crypto-nodejs/package.json
As @turt2live suggested, it should be good to have a scoped package name. Here we are :-).
> feat(crypto-js): Change the package name

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/room/common.rs
Adds a method to get the `alt_aliases` too, that was needed by this method.
> feat(sdk): Add method to get a room permalink

- crates/matrix-sdk-test/src/event_builder/bulk.rs
- crates/matrix-sdk-test/src/event_builder/invited_room.rs
- crates/matrix-sdk-test/src/event_builder/joined_room.rs
- crates/matrix-sdk-test/src/event_builder/left_room.rs
- crates/matrix-sdk-test/src/event_builder/mod.rs
- crates/matrix-sdk-test/src/lib.rs
- crates/matrix-sdk/tests/integration/room/common.rs
Adds the possibility to add and create test events in bulk to the test crate.
> test(sdk): Split tests for permalinks

- benchmarks/Cargo.toml
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-nodejs/Cargo.toml
- crates/matrix-sdk-appservice/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-qrcode/Cargo.toml
- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-test/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/room/common.rs
- labs/sled-state-inspector/Cargo.toml
> sdk: Make `from` in `MessageOptions` optional

- bindings/apple/debug_build_xcframework.sh
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
This PR exposes a simple mechanism for enabling tracing and logs for clients using the FFI layer.
> Tracing configuration through FFI

- crates/matrix-sdk/src/sync.rs
I don't know why we didn't do this before...
> fix(sdk): Call to-device handlers

- crates/matrix-sdk/src/room/common.rs
… to match the latest changes in Ruma.
cc @johannescpk
> refactor(sdk)!: Update MessageOptions API once again

- .github/workflows/bindings_ci.yml
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-js/cliff.toml
- bindings/matrix-sdk-crypto-js/package.json
- bindings/matrix-sdk-crypto-js/tests/encryption.test.js
- bindings/matrix-sdk-crypto-js/tests/events.test.js
- bindings/matrix-sdk-crypto-js/tests/identifiers.test.js
- bindings/matrix-sdk-crypto-js/tests/machine.test.js
- bindings/matrix-sdk-crypto-js/tests/requests.test.js
- bindings/matrix-sdk-crypto-js/tests/sync_events.test.js
- bindings/matrix-sdk-crypto-js/tests/tracing.test.js
- bindings/matrix-sdk-crypto-js/tsconfig.json
- bindings/matrix-sdk-crypto-nodejs/cliff.toml
Chore PR to prepare `matrix-sdk-crypto-js` for publishing, and to update `git-cliff` configurations.
> chore: Update or add `git-cliff` config' & prepare `crypto-js` for publishing

- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/store/ambiguity_map.rs
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/verification/mod.rs
- crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
- crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/src/client/login_builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/sync.rs
* Use fields more
* Adjust some wording
> refactor: Improve tracing events

- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
This fixes a bug where we would lose already generated to-device requests carrying an m.room_key when the client gets restarted.
This only happens if the request was generated after the initial share of the room key. Such requests get generated if a new device or member join the group.
> fix(crypto): Store intermediate changes to the outbound group session

- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
This PR depends on #884. Shouldn't be too controversial either, the real change is 1-2 lines while the rest is comments explaining what's going on and unit test for the changed method.
> fix(crypto): Rotate the outbound group session if the algorithm changes 

- Cargo.toml
Let's see whether this shows up in CI times..
> Disable debug-info for the dev profile

- crates/matrix-sdk-appservice/examples/appservice_autojoin.rs
- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk/README.md
- crates/matrix-sdk/examples/autojoin.rs
- crates/matrix-sdk/examples/command_bot.rs
- crates/matrix-sdk/examples/image_bot.rs
- crates/matrix-sdk/examples/login.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/event_handler.rs
> Rename {register => add}_event_handler and add back the register_ methods with previous signatures

- .github/workflows/documentation.yml
> ci(js) add npm docs of bindings to pages

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/event_handler.rs
> Add support for room-specific event handlers

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/room/common.rs
Implements the API suggested in https://github.com/matrix-org/matrix-rust-sdk/issues/177#issuecomment-1093081915.
Follow-up to #899.
Closes #177.
> feat(sdk): Add room::Common::add_event_handler

- crates/matrix-sdk-crypto/src/gossiping/machine.rs
No changes in the logic, just removing a bit of code duplication in the tests and splitting out some methods.
> Refactor the key forwarding logic and tests

- crates/matrix-sdk-common/src/timeout.rs
… as well as simpler, and faster.
> chore(common): Make timeout tests deterministic

- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-nodejs/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
- crates/matrix-sdk-qrcode/Cargo.toml
This patch delegates the decision making if a session is better to vodozemac. Vodozemac has better insights if a group session can be considered to be better.
> refactor(crypto): Use the vodozemac method to decide if a session is better

- .github/workflows/bindings_ci.yml
- Cargo.lock
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/lib.rs
Not very impressive, I know 😅
Currently on hold, timeline API is more important.
> Use the latest git version of UniFFI

- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
> Improve the logic that determines if an event is trusted

- Cargo.lock
- examples/create_rooms/Cargo.toml
- examples/create_rooms/src/main.rs
> feat(examples): Add an example that lets you create rooms

- crates/matrix-sdk-crypto/src/identities/device.rs
> doc(crypto): Fix typos in the documentation

- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-ffi/src/session_verification.rs
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk/src/docs/encryption.md
- crates/matrix-sdk/src/encryption/identities/devices.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/room/common.rs
- examples/emoji_verification/src/main.rs
Just a small renaming to match the rest of the code.
> feat(crypto): Rename `verified` and `deleted` to `is_*`

- bindings/matrix-sdk-ffi/src/authentication_service.rs
- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/attachment.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/room/joined.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
- examples/image_bot/src/main.rs
Just opening this to hear whether I should continue removing `Read` everywhere or it should be kept in `matrix-sdk-crypto`.
> Change upload to take &[u8]

- bindings/matrix-sdk-ffi/Cargo.toml
… or do we want to make it optional there too?
> feat(bindings): Enable socks proxy support in matrix-sdk-ffi

- Cargo.lock
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/members.rs
- crates/matrix-sdk-base/src/store/integration_tests.rs
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/event_handler/mod.rs
- crates/matrix-sdk/src/room/common.rs
- testing/matrix-sdk-integration-testing/Cargo.toml
- testing/matrix-sdk-integration-testing/assets/ci-start.sh
- testing/matrix-sdk-integration-testing/src/tests.rs
- testing/matrix-sdk-integration-testing/src/tests/invitations.rs
- testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
- testing/matrix-sdk-test/src/test_json/sync.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/978 , potentially related to #505 ?
I would like to ask whether this could break something?
Also there might be additional changes needed for stripped states vs. states in the stores?
I added some cleaning up that I had laying around as well, I hope this is fine.
> Fix rooms being in stripped and non-stripped stores

- bindings/matrix-sdk-crypto-nodejs/src/machine.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/encryption/mod.rs
This replaces #961.
It's just removing some dead code and making fmt/clippy happy.
> Make create_dm_room public

- Cargo.lock
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/config/sync.rs
- crates/matrix-sdk/src/lib.rs
- testing/matrix-sdk-integration-testing/Cargo.toml
- testing/matrix-sdk-integration-testing/src/tests.rs
The last commit changes logs like
```
2022-09-08T08:50:39.404260Z  INFO sync_once{sync_settings=SyncSettings { filter: None, timeout: Some(30s), token: None, full_state: false }}: matrix_sdk_base::store::memory_store: Saved changes in 820.453132ms
```
to
```
2022-09-08T08:51:06.946237Z  INFO sync_once{sync_settings=SyncSettings { timeout: 30s, full_state: false }}: matrix_sdk_base::store::memory_store: Saved changes in 842.238766ms
```
> Improve logging

- .github/workflows/bindings_ci.yml
- Cargo.lock
- bindings/apple/build_xcframework.sh
- bindings/apple/debug_build_xcframework.sh
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/messages.rs
No cargo build errors, soo maybe it works? 😍
> Upgrade UniFFI

- Cargo.lock
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-nodejs/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-qrcode/Cargo.toml
> Bump some deps

- examples/emoji_verification/src/main.rs
Haven't tested this, would appreciate instructions for how best to do that 😅
> refactor: Use event handlers in emoji_verification example

- crates/matrix-sdk/src/sliding_sync.rs
Curious why CI didn't catch these.
> chore: Fix clippy lints

- labs/jack-in/src/components/label.rs
- labs/jack-in/src/components/rooms.rs
I'll create an issue about clippy not checking everything..
> refactor: Replace str::to_string with to_owned

- tarpaulin.toml
Let's see what this does to coverage numbers 😅
> Tarpaulin config improvements

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
This PR will allow FFI clients to fetch media thumbnails by providing the MediaSource and required size
> Expose FFI layer function for fetching media thumbnails

- .rustfmt.toml
- crates/matrix-sdk-appservice/examples/appservice_autojoin.rs
- crates/matrix-sdk-appservice/src/lib.rs
Refactors the AppService struct to use a builder pattern to allow for further configuration.
> refactor(appservice)!: Use builder pattern

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/event_handler/mod.rs
> feat(sdk): Make EventHandlerDropGuard public

- bindings/apple/Tests/MatrixRustSDKTests/ClientTests.swift
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client_builder.rs
> feat: Allow clients using matrix-sdk-ffi to set the user agent

- bindings/apple/README.md
This ports the documentation improvements from #1080 over to @pixlwave's branch for #1023.
> Explain how to run the unit tests

- labs/jack-in/src/app/model.rs
> refactor: Use Box::default

- bindings/matrix-sdk-ffi/src/client.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/error.rs
- crates/matrix-sdk/tests/integration/client.rs
- crates/matrix-sdk/tests/integration/refresh_token.rs
- examples/appservice_autojoin/src/main.rs
First commit follows up on #604. The other two are for convenience (see matrix-rust-sdk room for some context).
> Some error improvements

- crates/matrix-sdk/README.md
- crates/matrix-sdk/src/client/mod.rs
Supposed to close https://github.com/matrix-org/matrix-rust-sdk/issues/733 .
> docs: Improve documentation for custom event handler context

- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/room.rs
While uniffi does catch those panics and transforms them into errors we should still treat them accordingly.
> chore(bindings): Replace various expectations with anyhow contexts

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
As suggested in review of #940.
> refactor(sdk): Move timeline event handling fns to TimelineInner

- .github/workflows/bindings_ci.yml
- xtask/Cargo.toml
- xtask/src/ci.rs
I want to add some optimizations, but also have the test run once before that.
> Add bindings generation CI job

- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
For debugging some timeline item duplication Ștefan has been seeing.
> feat(bindings): Add TimelineItem::fmt_debug

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
For debugging some timeline item duplication Ștefan has been seeing.
> Improve logging in the timeline API

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/authentication_service.rs
- bindings/matrix-sdk-ffi/src/client.rs
- crates/matrix-sdk-appservice/src/virtual_user.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/docs/encryption.md
- crates/matrix-sdk/src/test_utils.rs
- crates/matrix-sdk/tests/integration/main.rs
- crates/matrix-sdk/tests/integration/refresh_token.rs
- labs/jack-in/src/main.rs
As suggested in #1176 and discussed on Matrix.
> Rename restore_login to restore_session

- crates/matrix-sdk-appservice/src/error.rs
- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/error.rs
- crates/matrix-sdk/src/http_client.rs
- crates/matrix-sdk/tests/integration/client.rs
- examples/cross_signing_bootstrap/src/main.rs
- testing/matrix-sdk-integration-testing/src/helpers.rs
… and a lot of HTTP error improvements.
> Use server-supplied retry time when available

- crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
- crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs
- crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This closes #603.
Tested using the emoji example with the latest Element desktop release.
> Implement MSC3783

- Cargo.lock
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/platform.rs
And introduce the concept of platform-specific implementations via a `platforms.rs` mod. Probably to be moved into a subfolder once this becomes too much...
> feat(ffi): logging support for android

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/error.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/invited.rs
- crates/matrix-sdk/src/room/joined.rs
- crates/matrix-sdk/src/room/left.rs
- crates/matrix-sdk/tests/integration/client.rs
- crates/matrix-sdk/tests/integration/main.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
- crates/matrix-sdk/tests/integration/room/left.rs
- crates/matrix-sdk/tests/integration/room/timeline.rs
- testing/matrix-sdk-integration-testing/src/helpers.rs
- testing/matrix-sdk-integration-testing/src/tests.rs
- testing/matrix-sdk-integration-testing/src/tests/invitations.rs
- testing/matrix-sdk-integration-testing/src/tests/redaction.rs
- testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
- testing/matrix-sdk-test/src/test_json/sync_events.rs
Follow-up of #1022 .
Unfortunately I had to merge main into the branch instead of rebasing, because it was done before once and rebasing was made pretty much impossible by that :(
> Don't require sync_events interaction for room creation / joining / leaving

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-crypto-ffi/src/olm.udl
- crates/matrix-sdk-crypto/src/backups/mod.rs
> feat!(bindings): Expose the improved result of the verify_backup method

- crates/matrix-sdk/src/event_handler/mod.rs
- crates/matrix-sdk/src/sync.rs
Adds some debug aids.
Closes #1102.
> Event handler tracing

- Cargo.lock
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-js/src/verification.rs
- bindings/matrix-sdk-ffi/src/client.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-indexeddb/src/crypto_store.rs
- crates/matrix-sdk-indexeddb/src/lib.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk/src/sliding_sync.rs
It removes the fork we have introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/1068 (all our patches have been merged and are part of this 0.3.0 release).
> feat(indexeddb): Update to `indexed_db_futures` 0.3.0

- .gitignore
Follow up on the https://github.com/matrix-org/matrix-rust-sdk/pull/1239 PR
To ignore the generated files
Signed-off-by: valeref@matrix.org
> Git Ignore generated files from kotlin bindings

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
- crates/matrix-sdk/src/room/timeline/tests.rs
- labs/jack-in/src/components/details.rs
> feat(sdk): Add support for stickers in the timeline

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/deserialized_responses.rs
- crates/matrix-sdk-base/src/store/integration_tests.rs
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-common/src/deserialized_responses.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/src/events.rs
- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/tests.rs
Some bugfixes happened recently and I want to make sure we don't introduce new cases of serializing full events.
> chore: Upgrade Ruma

- bindings/matrix-sdk-ffi/src/timeline.rs
Kévin recently added support for day dividers to the timeline API in the main crate and less recently did the same thing for (one's own) read marker. This makes both available in the generated bindings.
> feat(bindings): Add virtual timeline items to matrix-sdk-ffi

- bindings/matrix-sdk-ffi/src/room.rs
… as a debugging aid for the current UTD issues in ElementX.
> feat(bindings): Add decryption retrying to matrix-sdk-ffi

- crates/matrix-sdk/src/sliding_sync.rs
> style(sliding-sync): explain why we limit the timeline items in freeze

- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
- crates/matrix-sdk/src/room/timeline/to_device.rs
This will hopefully help figuring out what's wrong with ElementX not retrying decryption correctly.
> Improve timeline event decryption retries

- crates/matrix-sdk/src/room/timeline/mod.rs
More efficient, more than halves the `mem::size_of::<Timeline>()`. Follow-up to #1297.
> refactor(sdk): Store timeline event handler handles in a Vec

- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/sliding_sync.rs
Mostly code style, but also some logging improvements and small optimizations.
> Some sliding sync refactoring

- crates/matrix-sdk/src/room/timeline/tests.rs
This wasn't previously covered in our test cases.
> test(sdk): Add a test for TimelineInner::add_initial_events

- crates/matrix-sdk-common/src/timeout.rs
It's broken and doesn't seem to be used, so remove it.
> Simplify wasm timeout implementation

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/session_verification.rs
Expose support for manually starting sas verifications and accepting remotely started ones
Enables https://github.com/vector-im/element-x-ios/pull/408
> FFI verification manual SaS start support

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
> feat(uniffi): Add support to set list filters on sliding sync view builders

- crates/matrix-sdk-base/src/sliding_sync.rs
The sliding sync proxy seems to have started to omit the e2ee extension completely if no changes happened to the one-time key counts.
Our sync response processing assumed that, if there are some to-device events that need to be passed to the OlmMachine, then we'll have some data in the e2ee extension of the response as  well. In other words, it wouldn't pass in the to-device events to the OlmMachine if the e2ee field of the sync response is `None`.
Since the assumption isn't true, we're going to pass in default values for the one-time key counts when the e2ee extension field of the response is `None`.
Thanks for @gnunicorn for spotting the exact place where to-device events would vanish :ghost:.
> fix(sdk): Pass in to-device events to the OlmMachine unconditionally

- crates/matrix-sdk-crypto/src/machine.rs
This adds the receiving side of #1266
> Log to-device message ids if we receive them

- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
This are fixes that were made as part of #1349. But auto-merge was enabled on that PR before the review phase was done.
> Message id support continuation

- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
- crates/matrix-sdk/src/room/timeline/tests.rs
- crates/matrix-sdk/tests/integration/room/timeline.rs
- labs/jack-in/src/components/details.rs
- testing/matrix-sdk-test/src/test_json/messages.rs
> feat(sdk): Add support for state events in the timeline

- bindings/matrix-sdk-ffi/src/timeline.rs
> fix(bindings): Add user_id to RoomMembership

- bindings/matrix-sdk-ffi/src/client_builder.rs
To allow clients to skip the extra round trip.
Example usage on iOS client:
```diff
diff --git a/ElementX/Sources/Services/UserSession/UserSessionStore.swift b/ElementX/Sources/Services/UserSession/UserSessionStore.swift
index ccc01e7..30f3e80 100644
--- a/ElementX/Sources/Services/UserSession/UserSessionStore.swift
+++ b/ElementX/Sources/Services/UserSession/UserSessionStore.swift
@@ -105,6 +105,7 @@ class UserSessionStore: UserSessionStoreProtocol {
private func restorePreviousLogin(_ credentials: KeychainCredentials) async -> Result<ClientProxyProtocol, UserSessionStoreError> {
let builder = ClientBuilder()
.basePath(path: baseDirectory.path)
+            .serverVersions(versions: ["v1.0", "v1.1", "v1.2", "v1.3", "v1.4", "v1.5"])
.username(username: credentials.userID) …
```
> feat(ffi): expose server_versions on ClientBuilder

- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-crypto-js/src/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
I had no idea what a tracked user was, so I've attempted to clarify this
somewhat for future readers.
> doc: Improve the documentation of "tracked users"

- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- crates/matrix-sdk/src/sliding_sync.rs
It didn't push the updates through FFI anymore because of a bug I refactored into the code in my last PR: https://github.com/matrix-org/matrix-rust-sdk/pull/1372/files#diff-b2b7a31b871584d3c41cf8033e97c694724088898ae74ab5c16ada7939389817L494 .
Also adds some minor more debug aggregated info for easier tracking of incoming requests.
> Fixing sliding sync diff loop

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/tests.rs
Small PR.
Trying to address https://github.com/matrix-org/matrix-rust-sdk/issues/1363, and noticed tests that can be improved + documentation.
> test(sdk): Improve `m.fully_read` test coverage and documentation

- crates/matrix-sdk/src/room/timeline/event_handler.rs
… rather than prepended, or added at a specific point as replacement for an existing timeline item.
Previously, we would log lots of useless tracing events when retrying to decrypt UTD items.
> fix(sdk): Only look for local echoes for events appended to the timeline

- crates/matrix-sdk/src/room/timeline/inner.rs
Ivan found that these didn't make sense. Should be better now.
> fix(sdk): Update add_event_id logs to make more sense

- crates/matrix-sdk/src/account.rs
> doc(sdk): Simplify `if let` into `let`

- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
- crates/matrix-sdk/src/sliding_sync.rs
- labs/jack-in/src/app/model.rs
- labs/jack-in/src/client/mod.rs
- labs/jack-in/src/components/statusbar.rs
- labs/jack-in/src/main.rs
- testing/sliding-sync-integration-test/src/lib.rs
… to avoid gaps in the timeline in such cases.
> Clear the timeline when sliding-sync loop is reset

- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk/src/room/timeline/event_item.rs
> feat(sdk): Add `EventTimelineItem::unique_identifier`

- Cargo.toml
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/lib.rs
- crates/matrix-sdk/src/sliding_sync.rs
- crates/matrix-sdk/src/test_utils.rs
- testing/sliding-sync-integration-test/Cargo.toml
- testing/sliding-sync-integration-test/src/lib.rs
tests and fixes on top of #1399 :
> Sliding Sync Fixes

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/store/memory_store.rs
- crates/matrix-sdk-indexeddb/src/state_store.rs
- crates/matrix-sdk-sled/src/state_store.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
… but do log relevant parts to allow debugging.
> fix: Don't log raw events that fail deserialization

- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-crypto/src/store/traits.rs
A few independent improvements that I noticed could be made while trying to refactor our store traits.
> Small matrix-sdk-crypto refactoring

- Cargo.lock
- bindings/matrix-sdk-crypto-ffi/src/error.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-crypto-ffi/src/olm.udl
- crates/matrix-sdk-sqlite/Cargo.toml
- crates/matrix-sdk-sqlite/migrations/002_reset_olm_hash.sql
- crates/matrix-sdk-sqlite/src/crypto_store.rs
- crates/matrix-sdk-sqlite/src/error.rs
- crates/matrix-sdk-sqlite/src/lib.rs
- crates/matrix-sdk-sqlite/src/utils.rs
… and replace the last bits of JSON encoding with MessagePack.
> Clean up matrix-sdk-sqlite error handling

- crates/matrix-sdk-sled/src/crypto_store.rs
- testing/sliding-sync-integration-test/src/lib.rs
This clippy lint was constantly showing up in my editor 😅
> A little bit of cleanup

- bindings/matrix-sdk-crypto-js/tests/device.test.js
- crates/matrix-sdk-crypto/src/machine.rs
> fix(crypto): Always mark your own device as verified

- crates/matrix-sdk/src/room/timeline/mod.rs
> test(sdk): Add timeline items accessor

- testing/matrix-sdk-integration-testing/assets/Dockerfile
- testing/sliding-sync-integration-test/assets/Dockerfile
- testing/sliding-sync-integration-test/assets/docker-compose.yml
Please confirm the new config still works in whatever version of `docker-compose` you have!
> Some Docker improvements

- crates/matrix-sdk/src/room/timeline/tests/basic.rs
- crates/matrix-sdk/src/room/timeline/tests/mod.rs
- crates/matrix-sdk/src/room/timeline/tests/virt.rs
- crates/matrix-sdk/tests/integration/room/timeline.rs
Add some new functionality to TestTimeline to simplify the test cases themselves.
> TestTimeline improvements

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
This should help us create unit tests for a given real-world flow.
> chore(sdk): Add more spans and trace events to the timeline

- .github/workflows/ci.yml
Fix CI for the sliding sync integration test. Example: https://github.com/matrix-org/matrix-rust-sdk/actions/runs/4186062440/jobs/7254039749#step:8:1
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1377
> Update sliding sync integration tests CI

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/room.rs
Added a new function in the ffi Room implementation, to expose the usage of the report_content_v3 API to clients.
> feat: Report Content exposed to clients

- Cargo.lock
- crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
- crates/matrix-sdk/src/room/timeline/tests/basic.rs
- crates/matrix-sdk/src/sliding_sync.rs
- testing/sliding-sync-integration-test/src/lib.rs
> chore: Run `cargo update`

- crates/matrix-sdk/src/client/mod.rs
Allows me to rename a device.
Signed-off-by:
> feat(sdk): Allow changing a device's display name

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
Because it is what it is.
#NamingIsHard
> chore(ffi) Rename `StoppableSpawn` to `TaskHandle`

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-crypto-ffi/src/olm.udl
This branch was still lying around, I think I didn't open a PR because something in UniFFI was broken. I'm pretty sure it will work now :)
> Use UniFFI proc-macros for CrossSigningStatus

- crates/matrix-sdk/src/room/timeline/mod.rs
> feat(sdk): Add conversion from EventTimelineItem and VirtualTimelineItem to TimelineItem

- crates/matrix-sdk/src/sliding_sync/builder.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
- crates/matrix-sdk/src/sliding_sync/room.rs
I suggest to read this patch commit by commit, as it's a set of small local changes.
> chore(sdk): Many clean ups in `SlidingSync`

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk-crypto/src/verification/qrcode.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- labs/jack-in/src/app/model.rs
- labs/jack-in/src/client/mod.rs
- labs/jack-in/src/client/state.rs
- labs/jack-in/src/components/details.rs
… but not in sliding sync yet, where some planned refactorings might conflict with this.
> refactor: Upgrade eyeball and use SharedObservable

- crates/matrix-sdk-crypto/src/file_encryption/attachments.rs
> docs(crypto): fix typo

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-crypto-js/src/lib.rs
- bindings/matrix-sdk-ffi/src/lib.rs
https://github.com/matrix-org/matrix-rust-sdk/issues/1489#issuecomment-1445582815
> chore: Remove workaround for clippy bug that was fixed

- bindings/matrix-sdk-ffi/src/sliding_sync.rs
Last one (I lie).
That's a small clean up PR.
> chore(bindings): Clean up and code simplification on `matrix_sdk_ffi::sliding_sync`

- .github/workflows/bindings_ci.yml
- .github/workflows/ci.yml
Looks like #1604 broke the build :(
> Reinstate protoc for a couple of GHA jobs

- Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-sqlite/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/room/timeline/builder.rs
- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/tests/mod.rs
- xtask/src/ci.rs
… and update CI to test for some of it.
> Fix some things not compiling without encryption

- crates/matrix-sdk-base/src/store/traits.rs
- crates/matrix-sdk-indexeddb/src/crypto_store.rs
- crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
- crates/matrix-sdk-indexeddb/src/state_store/mod.rs
- crates/matrix-sdk-sled/src/state_store/migrations.rs
- crates/matrix-sdk-sled/src/state_store/mod.rs
A few refactorings to make the code easier to understand
cc @zecakeh
> Clean up state store API a bit

- bindings/matrix-sdk-ffi/src/sliding_sync.rs
With https://github.com/matrix-org/matrix-rust-sdk/pull/1601, `TaskHandle::with_callback` is no longer necessary.
This patch updates `TaskHandle` as follows:
1. Before, the `handle` and `callback` fields were not mutually exclusive! Indeed, the `callback` field was used as an abort mechanism, but _also_ as a finalizer, i.e. a code that runs _after_ the cancellation of `handle`. Now that the callback-based solution is no longer used, we can keep one usage for this field and rename it `finalizer`.
2. The `handle` field is no longer optional, as it will always be set.
3. The `with_callback` method is renamed `new` as it's now the only constructor.
4. The `set_callback` method is renamed `set_finalizer`.
Tadaaa.
> feat(ffi): Rethink `TaskHandle`

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/room.rs
Added two new functions to the room.rs file of FFI
> feat(bindings): exposed `leave` and `reject_invitation` functions to FFI

- crates/matrix-sdk/src/sliding_sync/mod.rs
The #1386 issue is closed. Yepee.
> doc(sdk): Remove a `FIXME` that is actually fixed

- crates/matrix-sdk-base/Changelog.md
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/lib.rs
- crates/matrix-sdk-base/src/rooms/mod.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-base/src/store/integration_tests.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/lib.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/invited.rs
- crates/matrix-sdk/src/room/joined.rs
- crates/matrix-sdk/src/room/left.rs
- crates/matrix-sdk/src/room/mod.rs
- testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
> Rename RoomType to RoomState and make it retrievable from RoomInfo

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-common/src/deserialized_responses.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/tests/mod.rs
- crates/matrix-sdk/src/sliding_sync/room.rs
Follow-up to #1648, cc @zecakeh
> Some timeline refactoring

- crates/matrix-sdk-base/src/rooms/normal.rs
> Undo room_type => room_state rename in serialized form of RoomInfo

- Cargo.lock
- bindings/matrix-sdk-ffi/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk/Cargo.toml
- xtask/src/ci.rs
> Allow room key forwarding to be enabled and disabled

- Cargo.lock
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
> Use UniFFI macros more

- crates/matrix-sdk/src/sliding_sync/mod.rs
This patch adds more logs around `SlidingSync` to ease debugging sessions.
I'm not totally sure those logs will be helpful, but at least it will help to detect when a request and a response are sent as expected.
> feat(sdk): Add more Sliding Sync logs

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
… to restore the default values of some fields.
> ffi: Put CreateRoomParameters back into the UDL file

- crates/matrix-sdk-indexeddb/src/crypto_store.rs
Follow up to #1614.
Like with the state store, the bindings expose the version as an f64 while the web API expects an unsigned integer.
This merges two migrations because both would be triggered anyway before the upgrade to version 2.
> indexeddb: Use u32 to represent version of crypto store

- crates/matrix-sdk-common/src/deserialized_responses.rs
This way it's okay to log them / derive `Debug` for structures that contain these types.
> Remove event contents from (Sync)TimelineEvent Debug impls

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/encryption/mod.rs
> DM creation cleanup

- testing/sliding-sync-integration-test/src/lib.rs
Strongly recommended to disable whitespace changes when viewing the diff 😉
> Feature-gate everything in sliding-sync-integration-test

- crates/matrix-sdk/src/sliding_sync/list/builder.rs
- crates/matrix-sdk/src/sliding_sync/list/mod.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
- crates/matrix-sdk/src/sliding_sync/room.rs
- testing/sliding-sync-integration-test/src/lib.rs
This PR should be reviewed commit by commit. It adds tests and fixes bugs inside `SlidingSyncList`.
A larger PR to merge the request generator inside the list is coming. It will fix a larger design issue in Sliding Sync itself.
> test(sdk): Write test suites for `SlidingSyncList` and siblings

- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/src/room/timeline/tests/encryption.rs
- crates/matrix-sdk/src/room/timeline/tests/mod.rs
- crates/matrix-sdk/tests/integration/room/common.rs
Follow-up to (and final part of) : #1648, #1656.
> sdk: Get push actions of decrypted events 

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- crates/matrix-sdk/src/sliding_sync/error.rs
- crates/matrix-sdk/src/sliding_sync/list/builder.rs
- crates/matrix-sdk/src/sliding_sync/list/frozen.rs
- crates/matrix-sdk/src/sliding_sync/list/mod.rs
This PR should be reviewed commit by commit.
> test(sdk): Continue to fix, test and clean up `SlidingSyncList`

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/client.rs
Resolve https://github.com/matrix-org/matrix-rust-sdk/issues/1698
> Make "name" optional when creating a room

- Cargo.lock
- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/Cargo.toml
- bindings/matrix-sdk-crypto-js/src/machine.rs
- bindings/matrix-sdk-crypto-js/src/olm.rs
- bindings/matrix-sdk-crypto-js/src/store.rs
- bindings/matrix-sdk-crypto-js/tests/machine.test.js
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
Fixes #1584. Adds a Stream which can be used to listen for updates, and a wrapper in the js binding. (I haven't updated the other bindings.)
It might be easier to review this commit-by-commit.
> API to notify apps when a megolm key is received

- bindings/matrix-sdk-crypto-js/package.json
> matrix-sdk-crypto-js v0.1.0-alpha.6

- bindings/matrix-sdk-ffi/src/client.rs
- crates/matrix-sdk/src/client/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1700
> Add get_profile to UniFFI

- xtask/src/swift.rs
Replace all "Generate" by "Generating" to fit the overall wording style of messages.
Signed-off-by: innocent fish <126611049+fInnOcentsh@users.noreply.github.com>
> chore: fix wording in scripts

- .github/workflows/release_crypto_js.yml
- bindings/matrix-sdk-crypto-js/RELEASING.md
The tags are supposed *not* to contain `v`, for consistency with the other
crates.
> Fixes and documentation for crypto-js releases

- bindings/matrix-sdk-ffi/src/room.rs
This allows us to know who has invited us to rooms
> feat: expose inviter to ffi

- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- crates/matrix-sdk/src/sliding_sync/cache.rs
- crates/matrix-sdk/src/sliding_sync/list/mod.rs
I don't know why CI doesn't show them, but locally I get them and they're annoying.
> Fix clippy lints

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/room.rs
Fix https://github.com/matrix-org/matrix-rust-sdk/issues/1653
> Expose accept_invitation to UniFFI

- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/src/room/invited.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1676
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1770
> Improve account data logics for Invites

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/src/machine.rs
Wait for up to a second for any in-flight device list updates to complete.
> crypto-js: wait for device updates in `getUserDevices`

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/tracing.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/login_builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/room/joined.rs
- crates/matrix-sdk/src/room/timeline/mod.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
- crates/matrix-sdk/src/sliding_sync/room.rs
Let's see if any of this works 🤞🏼
> Add tracing to matrix-sdk-ffi

- .github/workflows/ci.yml
Not sure why I did this in such a complicated way before. I think I even tried doing sth. like this, but thought it wouldn't work without trying. Or maybe it didn't work and I'll rediscover that here 😅
> ci: Simplify test-all-crates job

- bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs
- bindings/matrix-sdk-crypto-ffi/src/device.rs
- bindings/matrix-sdk-crypto-ffi/src/error.rs
- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-crypto-ffi/src/logger.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-crypto-ffi/src/olm.udl
- bindings/matrix-sdk-crypto-ffi/src/responses.rs
- bindings/matrix-sdk-crypto-ffi/src/users.rs
- bindings/matrix-sdk-crypto-ffi/src/verification.rs
Same as #1804, but for the crypto crate.
> Use UniFFI proc-macros as much as currently possible for the crypto-ffi crate

- .github/workflows/prep-crypto-nodejs-release.yml
- .github/workflows/release-crypto-nodejs.yml
Reverts matrix-org/matrix-rust-sdk#1779
> Revert "Install musl-gcc for linux-musl nodejs releases"

- bindings/matrix-sdk-ffi/src/room.rs
Re-sent this PR as a new one, for simplicity's sake (PR was so small, so instead of having to rebase and what not, just pulled in latest main and re-did it).
> Exposts fetch_event_details to FFI consumer

- crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
- crates/matrix-sdk-indexeddb/src/state_store/mod.rs
As discussed in https://github.com/matrix-org/matrix-rust-sdk/pull/1794#discussion_r1175476310.
cc @jplatte 
> indexeddb: Avoid unnecessary clones when deserializing events

- crates/matrix-sdk/src/room/timeline/event_handler.rs
`m.new_content` is the replacing content according to the spec. In general `content` has an extra `*` for fallback support.
> sdk: Use `new_content` of edits instead of `content`

- .github/workflows/bindings_ci.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/release-crypto-nodejs.yml
- .github/workflows/release_crypto_js.yml
We're constantly over the cache size limit with caches from a single day. This should help a little bit.
> Small CI cache improvements

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk/src/sliding_sync/builder.rs
- crates/matrix-sdk/src/sliding_sync/cache.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
- crates/matrix-sdk/src/sliding_sync/room.rs
> chore: Update Ruma

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
Improves logging, removes a redundant clone and a redundant scope.
> Minor sync response handling improvements

- bindings/matrix-sdk-crypto-js/package.json
New release of the JS bindings.
> matrix-sdk-crypto-js v0.1.0-alpha.8

- crates/matrix-sdk-base/Changelog.md
- crates/matrix-sdk-base/src/rooms/members.rs
Expose https://github.com/ruma/ruma/pull/1536 in the SDK.
> sdk: Add more convenient power level action checks to RoomMember

- crates/matrix-sdk/src/sliding_sync/list/mod.rs
Does what it says on the tin. I'd expect that re-providing builder arguments from an existing list shouldn't be too complicated, and this wasn't exposed to the FFI layers. In case we need it, we could add it back later.
> sdk: Remove unused `SlidingSyncList::new_builder`

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item/content.rs
- crates/matrix-sdk/src/room/timeline/tests/basic.rs
- crates/matrix-sdk/tests/integration/room/timeline/mod.rs
> sdk: Fill in replied-to event from timeline items when available

- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk/src/http_client.rs
A first few manual future size optimizations. The clippy lint `large_futures` was very helpful in evaluating these changes, but it is unfortunately no use for CI, since you have to configure it to warn on relatively small futures to find worthwhile spots for manual optimization, which also gets you hundrets of errors in places where it makes little sense to change anything.
> Optimize future sizes, round 1

- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
As discussed on Matrix yesterday.
> crypto: Reduce stack size of Store, OlmMachine

- crates/matrix-sdk/src/client/mod.rs
> sdk: Document when a created room is set as direct

- crates/matrix-sdk/src/encryption/identities/devices.rs
I'm guessing that for now this is simpler than removing local trust.
I copied the cross-signing verification part of `is_verified` for the docs.
cc @poljar.
> sdk: Add method to check if device is verified with cross-signing

- .github/workflows/ci.yml
- Cargo.lock
- benchmarks/Cargo.toml
- benchmarks/benches/crypto_bench.rs
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/client_builder.rs
- codecov.yaml
- crates/matrix-sdk-appservice/Cargo.toml
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-sled/Cargo.toml
- crates/matrix-sdk-sqlite/src/error.rs
- crates/matrix-sdk-sqlite/src/lib.rs
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/README.md
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/docs/encryption.md
- examples/persist_session/src/main.rs
- examples/timeline/Cargo.toml
- testing/matrix-sdk-integration-testing/src/helpers.rs
- testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
- testing/sliding-sync-integration-test/src/lib.rs
- xtask/src/ci.rs
> sdk: Replace Sled with SQLite as default store

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/session.rs
- crates/matrix-sdk-crypto/src/requests.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-crypto/src/verification/cache.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk-crypto/src/verification/qrcode.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/config/sync.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/sync.rs
The last round for now. This is no fun at all, we really need better tools here. I'm also getting the impression the compiler is missing *loads* of optimization opportunities.
I've tried hard to only make sensible and understandable changes, but ultimately had to introduce quite arbitrary `Box::pin`s to segment large future stacks into somewhat reasonable chunks.
> Optimize future stack sizes, round 2

- crates/matrix-sdk/src/sliding_sync/mod.rs
Hope this makes sense. I think it's very helpful to have the `pos` value when logging the sync response, and I didn't want to use `Span::current()` in a function that doesn't necessarily has its own span (as was the case before).
> sdk: Clean up spans for sliding sync_once

- crates/matrix-sdk/src/room/timeline/event_handler.rs
- crates/matrix-sdk/src/room/timeline/event_item/mod.rs
- crates/matrix-sdk/src/room/timeline/inner.rs
- crates/matrix-sdk/tests/integration/room/timeline/mod.rs
Short-circuit when we already have the in-reply-to details.
> sdk: Add more logging and a new branch to fetch_in_reply_to_details

- crates/matrix-sdk-base/src/debug.rs
- crates/matrix-sdk-base/src/lib.rs
- crates/matrix-sdk-base/src/sync.rs
- crates/matrix-sdk-common/src/debug.rs
- crates/matrix-sdk-common/src/deserialized_responses.rs
- crates/matrix-sdk-common/src/lib.rs
- crates/matrix-sdk/src/sync.rs
> Fix remaining sync response Debug event content leaks

- crates/matrix-sdk/src/sliding_sync/list/mod.rs
A `SlidingSyncList` has a state, which can be either `NotLoaded`, `Preloaded`, `PartiallyLoaded`, or `FullyLoaded`.
A `SlidingSyncList` can be reset, either manually when `SlidingSyncList::reset` is called, or when a range is updated for example.
Resetting a list is modifying its state. Prior to this patch, the state was set to `NotLoaded`. However, it's not entirely true. This patch updates this behavior to the following rules:
* When the state is `NotLoaded`, it's kept at this state as nothing has happened yet,
* When the state is `Preloaded`, the list is restored from the cache, but nothing has happened yet too, so it's kept at this state,
* When the state is `PartiallyLoaded` or `FullyLoaded`, it means some (or all) updates have been done, so the new state is `PartiallyLoaded` after …
> feat(sdk): Rethink the `SlidingSyncList::state` after a reset

- Cargo.lock
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/build.rs
- bindings/matrix-sdk-ffi/src/lib.rs
Edit by @Hywan: Fix https://github.com/matrix-org/matrix-rust-sdk/pull/1909.
> feat(ffi): add method for getting the build time git short sha value

- bindings/matrix-sdk-ffi/src/room.rs
Allow for retrieving a single room member by their ID.
> feat(bindings): expose getting member by id

- crates/matrix-sdk/src/sliding_sync/mod.rs
We didn't previously log any details about which sliding-sync response is being handled. This should fix that.
> sdk: Instrument sliding response handling task

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/src/requests.rs
> crypto-js: expose a constructor for `SigningKeysUploadRequest`

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/package.json
Cut a new release, to include recent fixes
> matrix-sdk-crypto-js v0.1.0-alpha.9

- Cargo.lock
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk-ui/test/integration/main.rs
- crates/matrix-sdk-ui/tests/integration/main.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
- crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
The directory had the wrong name, so it wasn't detected by Cargo.
> Restore timeline integration tests

- Cargo.lock
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-crypto-ffi/build.rs
- bindings/matrix-sdk-crypto-ffi/src/lib.rs
Closes: https://github.com/matrix-org/matrix-rust-sdk/issues/1907 for real.
> Expose the git description and commit hash in the crypto-ffi bindings

- crates/matrix-sdk-crypto/src/file_encryption/key_export.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/attachment.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/identities/devices.rs
- crates/matrix-sdk/src/encryption/identities/mod.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/encryption/verification/sas.rs
- crates/matrix-sdk/src/media.rs
- crates/matrix-sdk/src/room/common.rs
- crates/matrix-sdk/src/room/joined.rs
- crates/matrix-sdk/src/room/member.rs
- crates/matrix-sdk/src/sliding_sync/README.md
… and clean up formatting around the affected ones.
> Don't use block_on in no_run doctests

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/session_verification.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
> Start using UniFFI async support

- crates/matrix-sdk/src/sliding_sync/list/frozen.rs
This patch replaces a panic (`Option::expect`) by a `tracing::error` log.
Imagine the Sliding Sync proxy responds with the following payload:
```json
{
"pos": …,
"lists": {
…: {
"count": …,
"ops": [
{
"op": "INSERT",
"index": 0,
"room_id": !foo:bar.org",
}
]
}
},
"rooms": []
}
```
It's an invalid response, as it will update the room list entry (because it's present in `lists.$list.ops`), but the room won't be created (it's absent in the `rooms`).
This situation creates a panic in the patched code. We don't want to crash if the server replies with invalid data.
Ultimately, we should check that the sync operations are valid regarding the rooms' updates.
> fix(sdk): Replace a panic by a log in Sliding Sync

- crates/matrix-sdk-indexeddb/src/state_store/mod.rs
Allows rustfmt to do its thing.
> indexeddb: Use parentheses for the impl_state_store macro

- Cargo.lock
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/tests/integration/main.rs
- crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
- crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
- crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
Fixes https://github.com/vector-im/element-x-ios/issues/939, as much as it can be fixed client-side.
> Deduplicate local and remote echo by event ID when it comes in late 

- Cargo.lock
- Cargo.toml
This was a temporary replacement I've made, waiting for a PR of mine to be merged, and it's been merged since then. Oh well.
> fix: import Ruma from upstream repository

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/src/identities.rs
- bindings/matrix-sdk-crypto-js/tests/machine.test.js
> Bindings JS: Add missing keys to `UserIdentity` and `OwnUserIdentity`

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/package.json
> Bindings JS: New release `matrix-sdk-crypto-js v0.1.0-alpha.10`

- crates/matrix-sdk-sqlite/src/crypto_store.rs
- crates/matrix-sdk-sqlite/src/error.rs
- crates/matrix-sdk-sqlite/src/state_store.rs
- crates/matrix-sdk-sqlite/src/utils.rs
Instead of just logging the error.
> sqlite: Return an error when DB version is invalid or missing

- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/authentication_service.rs
- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/client_builder.rs
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/room_list.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
- bindings/matrix-sdk-ffi/src/task_handle.rs
- crates/matrix-sdk-ui/src/room_list/mod.rs
- crates/matrix-sdk-ui/tests/integration/room_list.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
Address https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
This patch implements the `RoomList` API inside `matrix-sdk-ffi`. It uses UniFFI and relies on the recent async UniFFI support for some methods.
This patch can be reviewed commit-by-commit.
> feat(ffi): Implement `RoomList` API

- crates/matrix-sdk-crypto/src/gossiping/machine.rs
This helps removing *a few* Arcs within the `GossipMachine`, but we still need one because `users_for_key_claim` is shared with another data structure (at the call site).
> chore: group GossipMachine fields inside an `Arc`-struct

- crates/matrix-sdk-common/src/executor.rs
… and simplify wasm spawn implementation.
This reduces the differences on wasm vs. non-wasm. Of course it's still possible to rely on details of the different error types, but at least both implement a few common traits: `Debug`, `Display`, `Error`.
> common: Add executor::JoinHandle

- bindings/matrix-sdk-crypto-js/src/device.rs
- bindings/matrix-sdk-crypto-js/src/machine.rs
- bindings/matrix-sdk-crypto-js/src/verification.rs
... mostly, writing down what things actually return.
> crypto-js: improvements to the documentation

- crates/matrix-sdk-ui/src/timeline/mod.rs
… in Timeline::paginate_backwards.
> ui: Add loading indicator before waiting for prev_batch token

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
Fix https://github.com/matrix-org/matrix-rust-sdk/issues/2004.
> fix(ui): `SlidingSync::subscribe_to_room` marks room as having missing members

- crates/matrix-sdk/src/sliding_sync/builder.rs
Address #1911.
Please see https://github.com/matrix-org/matrix-rust-sdk/issues/2037.
> fix(sdk): Disable the `receipts` extension temporarily

- crates/matrix-sdk-ui/src/room_list/mod.rs
> fix(ui): Enable SS caching on `RoomList`

- crates/matrix-sdk-ui/src/room_list/mod.rs
- crates/matrix-sdk-ui/tests/integration/room_list.rs
Address #1911.
This patch configures the `bump_event_types` paramter for the `all_rooms` list in `RoomList`.
> feat(ui): Add `bump_event_types` for `all_rooms` in `RoomList`

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-ui/src/room_list/mod.rs
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/2085
I suggest reviewing in separate commits. (I mean, I _always_ suggest that ;-)
> Cache display name in room info

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
> Revert parts of #2111 because name is already cached in RoomInfo

- bindings/matrix-sdk-crypto-nodejs/README.md
- ~Public API changes documented in changelogs (optional)~ N/A
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Add docs on how to use tracing for local Node dev

- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/queue.rs
- crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
> Add a queue to serialize message sending requests

- bindings/matrix-sdk-ffi/src/authentication_service.rs
Element X is using ClientBuilder.user_agent when restoring sessions but doesn't get this for new sessions through the authentication service. This PR fixes that and closes #2156.
> feat(bindings): Add user_agent parameter to authentication_service.

- crates/matrix-sdk-ui/src/timeline/event_item/content.rs
- crates/matrix-sdk-ui/src/timeline/tests/basic.rs
… for now, until we add proper support for threads.
Closes https://github.com/vector-im/element-x-ios/issues/477.
> ui: Treat thread fallback the same as a regular reply

- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/to_device.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/room/joined/mod.rs
Reverts matrix-org/matrix-rust-sdk#2164 (due to https://github.com/matrix-org/matrix-rust-sdk/pull/2164#issuecomment-1611065441).
> Revert "Expand room_key_received stream and use it for Timeline"

- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/room_list.rs
- bindings/matrix-sdk-ffi/src/sliding_sync.rs
Another attempt at allowing upload cancellation.
> ffi: Add SendAttachmentJoinHandle

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/src/verification.rs
- bindings/matrix-sdk-crypto-js/tests/device.test.js
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/verification/requests.rs
Element-web gives a countdown, so we need to know the remaining time.
> Add accessor for remaining time to `VerificationRequest`.

- bindings/matrix-sdk-ffi/src/room.rs
Address #1911.
This patch does the following:
1. changes `add_timeline_listener` to be async, thus removing one `RUNTIME.block_on`.
2. simplifies the logic by adopting a more classical pattern we use elsewhere:
* removes one `spawn_blocking`,
* let's move the `listener` into the task as a `Box` instead of cloning it as an `Arc`.
> fix(ffi): Simplify `Room::add_timeline_listener`

- crates/matrix-sdk-ui/src/room_list/mod.rs
> chore(ui): Remove unecessary qualification

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/package.json
Let's declare ourselves out of alpha!
> matrix-sdk-crypto-js v0.1.0

- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
Fixes a bug where toggling a reaction 3 or more times (with the right timing) can trigger multiple simultaneous requests to the homeserver.
Note this is difficult to reproduce manually, but this is done in the new unit test.
- Toggle a reaction on
- _Send request is triggered_
- Toggle the same reaction
- _Redact request is **not** triggered_
- _Send request returns_
- _Redact request is triggered_
- Toggle the same reaction
- _Send request is triggered (**bug - redact request has not yet responded**)_
To prevent multiple simultaneous requests to the homeserver for a particular reaction, `TimelineInner` keeps track of any ongoing request; on receiving a fresh reaction toggle input, it saves the request to it's state and returns the action to be performed. When it receives a new reaction …
> ui: Fix reaction response resolution

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
This PR the following fields of the [MSC3488](https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/location/proposals/3488-location.md):
- Description
- Asset
- Zoom level
> Map MSC3488 fields for UniFFI

- Cargo.lock
- benchmarks/Cargo.toml
pprof 0.12 is finally out and we can get rid of a few duplicate dependencies!
> Upgrade criterion, pprof

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- .github/workflows/release-crypto-nodejs.yml
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/read_receipts.rs
- examples/login/src/main.rs
- xtask/src/ci.rs
> Bump nightly, auto-format let-else

- bindings/matrix-sdk-ffi/src/notification.rs
Also did a small refactor to separate the Senderinfo from the RoomInfo
> feat(bindings): Room joined members is now in the notification

- crates/matrix-sdk-crypto/src/verification/machine.rs
… instead of nesting DashMaps.
The previous type was tracking mutability at very fine-grained level for no clear reason.
~~Also this is required for another refactoring~~
> crypto: Use HashMap inside DashMap

- Cargo.lock
- Cargo.toml
- codecov.yaml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-ui/Cargo.toml
Don't mind me, just doing maintenance.
> Upgrade dependencies

- .github/workflows/ci.yml
- .typos.toml
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content.rs
It had a purpose originally, but it no longer makes sense now that it only has a single field.
> ui: Remove NewEventTimelineItem

- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/virtual_item.rs
- crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
… with a BackPaginationState observable.
> ui: Replace loading indicator and timeline start virtual timeline items

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/package.json
> BindingsJS: Release `v0.1.1`

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk/src/client/mod.rs
> chore: remove a few useless async

- bindings/matrix-sdk-crypto-js/src/verification.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/verification/qrcode.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2237
Also a couple of other cleanups while I'm in the area. Suggest review commit-by-commit.
> Fix handling of SAS start events once we have shown a QR code

- crates/matrix-sdk-ui/src/events.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
- crates/matrix-sdk-ui/src/timeline/tests/mod.rs
- crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
- crates/matrix-sdk-ui/src/timeline/traits.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
To avoid to deal with events we are not interested in in the stream.
cc @jplatte
> ui: Allow to filter events added to the Timeline

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/src/verification.rs
- bindings/matrix-sdk-crypto-js/tests/device.test.js
Again, suggest review commit-by-commit
> crypto-js: Add Qr.state()

- bindings/matrix-sdk-crypto-js/CHANGELOG.md
- bindings/matrix-sdk-crypto-js/package.json
Prepare a new release of crypto-js
> matrix-sdk-crypto-js v0.1.2

- bindings/matrix-sdk-crypto-js/tests/device.test.js
Because https://github.com/jestjs/jest/issues/4156 is closed
> Disable debug logging for tests

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-ui/tests/integration/notification_client.rs
- crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
- crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
- crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/event_handler/mod.rs
- crates/matrix-sdk/tests/integration/room/common.rs
- testing/matrix-sdk-test/src/appservice.rs
- testing/matrix-sdk-test/src/event_builder/mod.rs
- testing/matrix-sdk-test/src/lib.rs
> test: Rename EventBuilder to SyncResponseBuilder

- crates/matrix-sdk-common/src/lib.rs
- crates/matrix-sdk-crypto/src/lib.rs
- crates/matrix-sdk/src/lib.rs
… a small bit for convenience of the bindings.
> Extend crate re-exports

- .github/workflows/bindings_ci.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
Documentation: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> ci: Fix git ref comparison

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-crypto-ffi/src/logger.rs
- bindings/matrix-sdk-crypto-ffi/src/olm.udl
- bindings/matrix-sdk-crypto-ffi/src/verification.rs
> crypto-ffi: Use proc-macro definition of callback interfaces

- UPGRADING-0.5-to-0.6.md
- crates/matrix-sdk-appservice/src/lib.rs
- crates/matrix-sdk-crypto/src/backups/keys/recovery.rs
- crates/matrix-sdk-ui/src/events.rs
- crates/matrix-sdk-ui/src/room_list_service/mod.rs
- crates/matrix-sdk-ui/src/room_list_service/room.rs
- crates/matrix-sdk/src/sliding_sync/list/mod.rs
- crates/matrix-sdk/src/sliding_sync/list/request_generator.rs
Fixes a few typos in several files. No functional changes intended.
> Fix some typos

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/tests/basic.rs
- crates/matrix-sdk-ui/src/timeline/tests/mod.rs
> ui: Reuse IDs when removing and re-inserting an item

- crates/matrix-sdk/src/sliding_sync/mod.rs
The `limited` flag computation was a bit too eager, in case the server responded with no new events on an `initial` response (e.g. after re-subscribing to a room that's already in the room list service's cache) it would make the response as limited. It's not really limited in that case, it's just that there was no new events to compare IDs against. This PR fixes that, and also adds another fix: whenever the server already includes `limited: true`, we can skip the emulation as the server has more context.
> fix: Don't mark a room as limited if the SS response doesn't contain any events

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/reactions.rs
`TimelineInnerState` is becoming less comprehensible, this should help a tiny bit.
> ui: Group timeline reaction metadata into a new struct

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
- crates/matrix-sdk-ui/src/timeline/traits.rs
We're facing a deadlock in ElementX-Android, need more debug info.
> Add more tracing

- bindings/matrix-sdk-ffi/src/room.rs
Since it might take a while and the UI might not be interested anymore after a short while (leaving a room that member fetching was initiated for).
cc @ganfra
> ffi: Make fetch_members cancellable

- bindings/matrix-sdk-crypto-ffi/src/responses.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/backups/mod.rs
instead of the more generic OutgoingRequest
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Return keys backup type

- bindings/matrix-sdk-ffi/src/room.rs
… to hopefully work around current issues.
> ffi: Remove async from a few functions

- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner.rs
… we should not be fetching the profile if it's already set.
> ui: Reduce work for updating sender profiles

- crates/matrix-sdk/src/sliding_sync/mod.rs
Tiny commit extracted from #2323. The `UpdateSummary` only contains the to-device token for the caller to store it somewhere else; no one else uses that, and it should be an internal implementation detail as far as I know.
> chore: slim down `UpdateSummary`

- bindings/matrix-sdk-ffi/src/notification.rs
- crates/matrix-sdk-ui/src/notification_client.rs
- crates/matrix-sdk-ui/tests/integration/notification_client.rs
- crates/matrix-sdk/src/room/mod.rs
Parts of #2330. Just missing integration tests, which will likely come in another PR.
> feat(sliding sync): make the notification client more robust

- bindings/matrix-sdk-ffi/src/notification.rs
The full timeline event contains both the timestamp (requested in #2361) and the sender id; now the sender id for the invite can also be contained in there, minimizing the amount of copying we're doing in the FFI code.
Fixes #2361.
@jmartinesp Can you test it please?
> ffi(notifications): include full timeline event again in the `NotificationEvent`

- crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
This should help us debug issues with false negatives.
> chore(sliding sync): add logs for the limited flag computation

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/tests/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
> ui: Add Timeline::subscribe_batched

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/src/notification_settings.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/room_list.rs
- bindings/matrix-sdk-ffi/src/session_verification.rs
Upstream PR: https://github.com/mozilla/uniffi-rs/pull/1684
> Use UniFFI fork with future cancellation support

- crates/matrix-sdk/src/sliding_sync/mod.rs
Small PR to fix a log (and an arithmetic overflow in it).
> Fix an arithmetic overflow

- crates/matrix-sdk-indexeddb/src/crypto_store.rs
> Fix rust doc on IndexedDBStore

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk/src/client/mod.rs
I found something nice in tokio's changelog ^^
> Upgrade tokio

- crates/matrix-sdk/src/http_client/native.rs
> sdk: Set content-length header when streaming HTTP request body

- bindings/matrix-sdk-ffi/src/tracing.rs
… at the expense of some performance.
This should allow everything to "just work" on Android where we don't always have accurate callsite information.
> ffi: Make tracing more flexible

- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/room_info.rs
- bindings/matrix-sdk-ffi/src/room_list.rs
- bindings/matrix-sdk-ffi/src/room_member.rs
… so the foreign code doesn't have to call a bunch of individual getters, which are bad for performance.
> Add RoomInfo type to FFI

- Cargo.lock
- Cargo.toml
> chore(cargo) Update `ruma`

- crates/matrix-sdk-base/src/client.rs
This patch first off renames `BaseClient::ignore_user_list_changes_tx` to `::ignore_user_list_changes`.
This patch then changes the type from `Arc<SharedObservable<_>>` to simply `SharedObservable<_>` as this type implement `Clone`. We basically have a double-`Arc` here.
Finally, this patch adds documentation for this field.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/2284.
> fix(base): `BaseClient::ignore_user_list_changes` is no longer behind an `Arc`

- Cargo.lock
- bindings/matrix-sdk-ffi/src/tracing.rs
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-common/src/lib.rs
- crates/matrix-sdk-common/src/tracing_timer.rs
- crates/matrix-sdk/src/sliding_sync/builder.rs
- crates/matrix-sdk/src/sliding_sync/cache.rs
- crates/matrix-sdk/src/sliding_sync/list/builder.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
See commit messages for details.
> feat: add log-based timers facilities + use them to measure how long it takes restore sliding sync lists

- bindings/matrix-sdk-ffi/src/room_info.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/tests/integration/room/mod.rs
- crates/matrix-sdk/tests/integration/room/notification_mode.rs
- testing/matrix-sdk-test/src/test_json/sync_events.rs
This PR adds the notification mode in `room_info` required by https://github.com/vector-im/element-x-ios/issues/1035
> feat(ffi): Add a notification_mode property to room_info

- bindings/matrix-sdk-ffi/src/room.rs
Fix https://github.com/matrix-org/matrix-rust-sdk/issues/2471
Fix https://github.com/matrix-org/matrix-rust-sdk/issues/2470
> Add send "poll response" and send "poll end" to UniFFI

- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk/src/widget/filter.rs
- crates/matrix-sdk/src/widget/mod.rs
- crates/matrix-sdk/src/widget/permissions.rs
… and some other small improvements.
> Add widget::EventFilter matching

- crates/matrix-sdk-ui/src/room_list_service/mod.rs
- crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This does what it says on the tin. cc @stefanceriu
> feat(room list service): enable read receipts for subscribed rooms

- .cargo/config.toml
- .github/workflows/bindings_ci.yml
- .github/workflows/coverage.yml
- tarpaulin.toml
- xtask/src/swift.rs
WIP, do not review. Not a draft because I need CI to run.
> Attempt to improve caching for matrix-rust-components-swift CI job

- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/2467.
The `Timeline` batches its updates to its subscribers (e.g. a client app, like Element X). A batch is built every time the inner state lock of the `Timeline` is released. On the paper, it's nice; in practise, even a read operation on the `Timeline` leads to building a new batch. This is inefficient and consumes resources (like CPU cycles, FFI boundary crossings, memory allocations etc.) even if there is no update to put in the batch: this will just batch empty updates.
To avoid that, one needs to make the difference between read or write operations onto the inner state. Only the write operations will fire a batch.
This patch splits the `TimelineInnerStateLock::lock` method into `::read` and `::write`. The idea is that …
> feat(ui): `TimelineInnerStateLock::lock` is replaced by `::read` and `::write`

- crates/matrix-sdk-base/src/store/memory_store.rs
What it says on the tin. 100% iso-functional, so no new tests.
> chore: derive `Default` for the state `MemoryStore`

- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content.rs
> Add is_threaded method to timeline Message types (Rust, FFI)

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-ui/src/room_list_service/mod.rs
> Some documentation cleanup

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/read_receipts.rs
Best reviewed commit by commit. Last one might be better off squashed. Not happy with how large the diff still is after attempting to make it smaller, but I don't have any further ideas for how to simplify things.
> Use ObservableVectorTransaction for timeline

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/tests/echo.rs
- testing/matrix-sdk-integration-testing/src/tests/reactions.rs
Fixes https://github.com/vector-im/element-x-ios/issues/1336.
Manually verified that the test *didn't* pass before the logic change.
> ui: Fix day divider logic

- benchmarks/benches/store_bench.rs
- bindings/matrix-sdk-ffi/src/authentication_service.rs
- bindings/matrix-sdk-ffi/src/client.rs
- crates/matrix-sdk-ui/src/room_list_service/mod.rs
- crates/matrix-sdk-ui/tests/integration/main.rs
- crates/matrix-sdk/src/authentication.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/matrix_auth/mod.rs
- crates/matrix-sdk/src/oidc/cross_process.rs
- crates/matrix-sdk/src/oidc/data_serde.rs
- crates/matrix-sdk/src/oidc/mod.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/src/test_utils.rs
- crates/matrix-sdk/tests/integration/main.rs
- crates/matrix-sdk/tests/integration/matrix_auth.rs
- crates/matrix-sdk/tests/integration/refresh_token.rs
- examples/oidc_cli/src/main.rs
- examples/persist_session/src/main.rs
Some simple refactorings on OIDC, can be reviewed commit by commit.
> OIDC refactorings

- .github/workflows/coverage.yml
It's better huh?
It should fix the CI.
> fix(ci): Change tarpaulin output format from `Xml` to `xml`

- crates/matrix-sdk/src/room/mod.rs
- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
This also fixes the test, by removing the initial sync that Bob's doing, as noted in the TODO.
Also don't send an empty key request query, to avoid spurious network roundtripping.
> fix(e2ee): query keys for untracked users even if we didn't explicitly sync members ourselves

- crates/matrix-sdk-ui/src/room_list_service/mod.rs
> feat(ui): Improve the `InputCannotBeApplied` displaying

- crates/matrix-sdk-ui/src/room_list_service/room_list.rs
- crates/matrix-sdk-ui/tests/integration/room_list_service.rs
It's best to review this PR commit-by-commit.
> feat(ui): `RoomList` dynamic entries simplifications

- bindings/matrix-sdk-ffi/src/notification_settings.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/session_verification.rs
- bindings/matrix-sdk-ffi/src/sync_service.rs
To work around Kotlin bugs in UniFFI.
> ffi: Add _blocking versions of async methods

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/latest_event.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content.rs
Also renames `PossibleLatestEvent::YesMessageLike` to `PossibleLatestEvent::YesRoomMessage` for consistency.
> Show polls as last_message in the room list

- bindings/matrix-sdk-ffi/src/room.rs
The timeline checks this already. The network request made for this was wasteful and unnecessary.
Fixes one half of #2582.
> ffi: Don't check original sender of message when editing

- bindings/matrix-sdk-ffi/src/room_list.rs
Because it creates a bug on iOS when using `RUNTIME.block_on` here.
This patch also adds `full_room_blocking` temporarily for Kotlin.
> fix(ffi): `RoomListItem::full_room` is now `async`

- bindings/matrix-sdk-ffi/src/error.rs
- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
This patch should be reviewed commit-by-commit.
---
* Fix https://github.com/matrix-org/matrix-rust-sdk/issues/1658
> feat(ffi): `Room::upload_avatar` now has an `Option<ImageInfo>`

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-ui/tests/integration/room_list_service.rs
So we get stats about waking through our logs.
> Enable eyeball's tracing feature

- crates/matrix-sdk/src/sliding_sync/mod.rs
Turns out that `tracing` will happily accumulate several values for the same key, if we `record()` in a loop. This patch reverts to logging the room_id in the individual statements instead.
> logs(sliding sync): don't accumulate room ids when computing `limited`

- bindings/matrix-sdk-ffi/src/room.rs
- bindings/matrix-sdk-ffi/src/timeline.rs
- crates/matrix-sdk-ui/src/timeline/error.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content.rs
- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/tests/basic.rs
- crates/matrix-sdk-ui/src/timeline/tests/echo.rs
- crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
… and use it in the FFI crate.
Fixes #2582.
cc @stefanceriu @zecakeh
> Add highlevel API for replying

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
> Timeline event handler cleanup

- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk-ui/src/timeline/error.rs
- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
> Add highlevel API for editing

- crates/matrix-sdk-indexeddb/src/crypto_store.rs
Fix a bug which caused `get_outgoing_secret_requests` to return no data.
This is exposed as a public function, and when called that way it does *not* expect the key to be escaped and encrypted.
There are tests for this, but they are not currently being run due to matrix-org/matrix-rust-sdk#661 :(
> Fix `IndexeddbCryptoStore::get_outgoing_secret_requests`

- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk/src/widget/mod.rs
… and make the FFI API cover everything the Rust API does.
> Rewrite public widget API

- crates/matrix-sdk/src/account.rs
The comment in the code explains why we need this. Some other client might still mess things up, but there's not much we can do about that.
> Ensure that we can't try to mark two rooms as a DM at the same time

- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/dehydrated_devices.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
> Small improvements to `StaticAccountData`

- .github/workflows/ci.yml
> ci: Upgrade crate-ci/typos

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/sync.rs
They were a stop-gap solution for detecting limited responses and have been obsolete since the introduction of room update handlers.
> sdk: Remove sync gap broadcast channels

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-crypto/src/backups/keys/backup.rs
> Upgrade Ruma to latest crates.io release

- crates/matrix-sdk-ui/src/timeline/builder.rs
… but record the relationship between them using follows_from.
I noticed that all `room_update_handler` spans in logs are reported to have a `build` span as their parent, that's not really the right relationship.
> Remove build as parent span of room_update_handler

- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/pagination.rs
… to help debugging timeline gap problems.
> Add more tracing to pagination

- crates/matrix-sdk-ui/src/timeline/pagination.rs
… if wait_for_token flag is set for backwards-pagination.
> ui: Wait for pagination token across multiple sync response notifs

- crates/matrix-sdk-qrcode/src/types.rs
I spent a while trying to figure out how all of this works.
> Improve documentation on `QrVerificationData`

- crates/matrix-sdk/src/oidc/cross_process.rs
Adds a test that covers the two interesting cases where a token refresh might happen while another `Client`'s doing things (another refresh, or restoring a session). The third case is less interesting and only emits a warning: it's a mismatch just after login succeeded, but a new login should be a sign that the `Client` doing the login has the final word anyways.
Part of #2602.
> oidc: add a cross-process lock test

- Cargo.lock
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
- crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
https://github.com/vector-im/element-x-ios/issues/1883
> ui: Fix missing thread relation when sending reply to threaded message

- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk/src/widget/settings/mod.rs
- crates/matrix-sdk/src/widget/settings/url_params.rs
Just a few small changes I noticed while looking over things and comparing with the POC branch.
> Widget cleanup

- crates/matrix-sdk-crypto/src/ciphers.rs
- crates/matrix-sdk-crypto/src/secret_storage.rs
My compiler is complaining about lack of explicit lifetimes on these consts
> Add static lifetimes to some constants

- crates/matrix-sdk-ui/src/timeline/pagination.rs
… since it can cause rather annoying problems with the SS proxy if it happens.
> ui: Raise log level for prev_batch wait timeout

- crates/matrix-sdk/src/widget/machine/mod.rs
- crates/matrix-sdk/src/widget/machine/tests/capabilities.rs
I wouldn't say I like much that we have access to the machine from all over the place (i.e. anyone could possibly modify the permissions), so we ideally probably need to change it at some point :)
> widget: Complete `ContentLoaded` implementation

- crates/matrix-sdk/src/widget/machine/tests/capabilities.rs
- crates/matrix-sdk/src/widget/machine/tests/openid.rs
This adds 2 unit tests for the cases when the matrix requests fail:
- For the OpenID case - if we don't get a successful response from the Matrix driver, we must notify the widget with the "blocked" state (now covered with a test).
- For the capabilities case - if we don't get capabilities granted (the request fails), we just send empty capabilities (no capabilities were granted) to the widget (covered with a test).
> widget: Add missing unit tests for error cases

- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2662
> Fix spurious "unknown secret request" warning

- crates/matrix-sdk-crypto/src/secret_storage.rs
This should now complete the test coverage for the secret storage support in the
crypto crate.
> Add more tests for the secret storage support in the crypto crate

- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/tests/integration/client.rs
> Some misc helpers around the E2EE support

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk/tests/integration/widget.rs
> widget: Add a test for receiving live events

- crates/matrix-sdk-ui/src/timeline/pagination.rs
> ui: Test next_event_limit for different pagination strategies

- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/tests/integration/encryption.rs
- crates/matrix-sdk/tests/integration/encryption/verification.rs
- crates/matrix-sdk/tests/integration/main.rs
> tests: add tests for verification

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk/src/encryption/verification/mod.rs
- crates/matrix-sdk/tests/integration/encryption/verification.rs
- testing/matrix-sdk-integration-testing/src/helpers.rs
- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
- testing/matrix-sdk-integration-testing/src/tests/invitations.rs
- testing/matrix-sdk-integration-testing/src/tests/reactions.rs
- testing/matrix-sdk-integration-testing/src/tests/redaction.rs
- testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
- testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
> Add test for mutual verification

- crates/matrix-sdk/tests/integration/encryption/verification.rs
Code-motion + commenting around only. No changes in functionality; this is really a small refactoring so as to make reuse of the keys endpoints mocking simpler in the future, as requested by @poljar in a previous PR.
> test: move the mocked endpoints into their own functions

- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
Bonus points for #2602, so we have a bit more leeway.
> Test some verification getters in the heavyweight verification integration test

- crates/matrix-sdk/src/widget/machine/driver_req.rs
- crates/matrix-sdk/src/widget/machine/mod.rs
- crates/matrix-sdk/src/widget/machine/pending.rs
- crates/matrix-sdk/src/widget/machine/tests/api_versions.rs
- crates/matrix-sdk/src/widget/machine/tests/capabilities.rs
- crates/matrix-sdk/src/widget/machine/tests/error.rs
- crates/matrix-sdk/src/widget/machine/tests/openid.rs
- crates/matrix-sdk/src/widget/machine/to_widget.rs
- crates/matrix-sdk/src/widget/mod.rs
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/2753.
> widget: Implement limits for requests

- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
- crates/matrix-sdk-crypto/src/olm/mod.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/src/lib.rs
- crates/matrix-sdk/src/room/futures.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/src/utils.rs
- crates/matrix-sdk/src/widget/machine/driver_req.rs
- crates/matrix-sdk/src/widget/machine/mod.rs
- crates/matrix-sdk/src/widget/matrix.rs
- testing/matrix-sdk-test/src/lib.rs
> Improve send-event API, part 2

- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
Found a few logging issues while digging into timeline problems on Tuesday.
> Some logging cleanup

- crates/matrix-sdk/src/http_client/mod.rs
- Log URI instead of separate homeserver, path
- Always log query parameters (not just for sliding sync)
- Only log request size for requests that could have a body based on the HTTP verb
Before:
`
2023-11-08T08:08:09.135164Z DEBUG send{homeserver="http://127.0.0.1:43201/" server_versions=[V1_0] config=RequestConfig { timeout: 30s, retry_limit: 0 } request_id="REQ-0" request_size="0 B" method=GET path="/_matrix/client/r0/login"}: matrix_sdk::http_client: Sending request
`
After:
`
2023-11-08T08:08:50.835238Z DEBUG send{server_versions=[V1_0] config=RequestConfig { timeout: 30s, retry_limit: 0 } request_id="REQ-0" method=GET uri="http://127.0.0.1:35149/_matrix/client/r0/login"}: matrix_sdk::http_client: Sending request
`
> sdk: Clean up http_client logging

- crates/matrix-sdk/src/http_client/mod.rs
Unfortunately there are a few requests like `check_registration_token_validity` that include secrets in the query parameters.
I don't think it's important to restore the logging of sliding sync query parameter that we had before since we're now recording the relevant ones in tracing spans higher up the tree.
> sdk: Exclude query parameters from logging

- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/file_encryption/key_export.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
Tiny refactorings while studying for merging the `GroupSessionCache` into the `StoreCache`.
Part of #2624.
> crypto: Preparatory refactorings for group sessions

- crates/matrix-sdk-crypto/CHANGELOG.md
- Add an entry which I forgot for #2805
- Reorder a few other items that have been added since https://github.com/matrix-org/matrix-rust-sdk/pull/2591.
> Update changelog for matrix-sdk-crypto

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/gossiping/mod.rs
- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/olm/session.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/types/cross_signing/common.rs
- crates/matrix-sdk-crypto/src/types/device_keys.rs
- crates/matrix-sdk-crypto/src/types/one_time_keys.rs
- crates/matrix-sdk-crypto/src/verification/cache.rs
- crates/matrix-sdk-crypto/src/verification/mod.rs
- crates/matrix-sdk-crypto/src/verification/qrcode.rs
- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk-crypto/src/verification/sas/mod.rs
- crates/matrix-sdk-store-encryption/src/lib.rs
- crates/matrix-sdk/src/encryption/identities/devices.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
- crates/matrix-sdk/src/room/futures.rs
> crypto: Small refactoring

- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/machine.rs
> doc: update doc comment for `OlmMachine::receive_sync_changes` and mention it in the changelog

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-crypto/src/backups/keys/mod.rs
- crates/matrix-sdk-crypto/src/gossiping/machine.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
- crates/matrix-sdk-crypto/src/verification/machine.rs
- crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
- crates/matrix-sdk-ui/src/timeline/tests/polls.rs
- crates/matrix-sdk-ui/src/timeline/tests/reaction_group.rs
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/widget/machine/tests/openid.rs
Some local compiler warnings (that we'd also see on CI on the next nightly version bump), and a follow-up to #2860.
> Cleanup (mostly crypto, tests)

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
... mostly in an attempt to figure out where all the `wait_if_user_key_query_pending` calls are coming from.
> Add `instrument` annotations to various methods

- crates/matrix-sdk/src/notification_settings/mod.rs
The mocks in some notification tests mock any PUT/DELETE request without the request to hit a certain path. These mocks then might respond to unintended new requests the client might make.
The tests also assert a bunch of things manually instead of using expectations when building the mock and calling server.verify().
> Make the mocks in some notification tests a bit more specific

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- crates/matrix-sdk/tests/integration/room/spaces.rs
- xtask/src/ci.rs
- xtask/src/fixup.rs
- xtask/src/main.rs
… to avoid issues with buggy toolchains.
> Use the same nightly toolchain for all xtask commands

- crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
Probably from a bad copy-pasta with a poll event.
> Tweak debug message wording for a timeline event

- crates/matrix-sdk-crypto/src/identities/device.rs
- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/session_manager/sessions.rs
A few different changes to reduce the number of lines that get logged during an encryption operation.
> Reduce logspam during encryption

- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/futures.rs
- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
It's been a while that I created a PR like this! Currently investigating an issue around disappearing local echoes, though not all of the commits are related to that.
> Improve tracing for the timeline

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-ui/src/timeline/builder.rs
- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
- crates/matrix-sdk-ui/src/timeline/read_receipts.rs
- crates/matrix-sdk-ui/src/timeline/tests/mod.rs
- crates/matrix-sdk-ui/src/timeline/traits.rs
- crates/matrix-sdk/src/room/mod.rs
A few read receipts refactorings. Nothing too fancy. Can be reviewed commit by commit.
> Some read receipts refactorings

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/verification/mod.rs
- crates/matrix-sdk/src/sliding_sync/README.md
Credit goes to @bmarty, thanks.
> Fix typos in doc

- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
`can_ban` and `can_kick` already exist and from what I can tell unbanning is covered by the `ban` power level.
> ffi: Support banning, unbanning and kicking users.

- xtask/src/ci.rs
- xtask/src/swift.rs
This reverts commit 0d24bcf6e5a803a6b375a8dd8d89ced3b75312e9.
git now translates nested "Revert X" commit messages to "Reapply X", how fancy is that?? 🤯
> Reapply "bindings: Use new uniffi-bindgen build mode"

- bindings/matrix-sdk-ffi/src/client.rs
This patch removes `RUNTIME.block_on` inside `Client::get_media_file`, `::upload_media`, `::get_media_content` and `::get_media_thumbnail`, and makes those methods async.
> feat(ffi): `Client::*media*` are now async

- crates/matrix-sdk-crypto/src/verification/qrcode.rs
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/src/encryption/verification/mod.rs
- crates/matrix-sdk/src/encryption/verification/qrcode.rs
- crates/matrix-sdk/src/encryption/verification/requests.rs
- crates/matrix-sdk/src/encryption/verification/sas.rs
- examples/emoji_verification/src/main.rs
- testing/matrix-sdk-integration-testing/Cargo.toml
- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
Allows to have a similar API as `SasVerification`.
> verification: Expose the `QrVerificationState` and the stream for its changes

- xtask/src/kotlin.rs
- xtask/src/swift.rs
Needed for #2240, this PR makes 2 changes:
- Handle multiple `.h`/`.modulemap` files in the Swift xtask for both the library and XCFramework outputs.
- Update Kotlin xtask to use Uniffi's library mode like Swift did in #2918. This has been tested with EXA by the Android team.
> Fix Swift/Kotlin Uniffi multi crate support.

- Cargo.toml
- benchmarks/Cargo.toml
- bindings/matrix-sdk-crypto-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-sqlite/Cargo.toml
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- examples/oidc_cli/Cargo.toml
- testing/matrix-sdk-integration-testing/Cargo.toml
Doing a release gets a bit easier with fewer dependency specifications scattered throughout the codebase :)
> Some release preparations

- crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
I was trying to figure out what was taking so long, so added some logging.
Signed-off-by:
> indexeddb: logging for open sequence

- Cargo.lock
- bindings/matrix-sdk-ffi/Cargo.toml
- bindings/matrix-sdk-ffi/src/api.udl
- bindings/matrix-sdk-ffi/src/lib.rs
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk-ui/src/lib.rs
- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/pagination.rs
> Move matrix_sdk_ui enum definitions out of UDL

- crates/matrix-sdk-ui/Cargo.toml
> Add a description for matrix-sdk-ui

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- crates/matrix-sdk/tests/integration/client.rs
And also comment that the timestamp is in seconds since the epoch.
Also silence a warning about unneeded qualifications.
> crypto ffi: use a u64 for timestamps instead of a String

- crates/matrix-sdk/src/lib.rs
> sdk: expose `SqliteStateStore` for symmetry with the crypto store export

- Cargo.lock
- crates/matrix-sdk/Cargo.toml
- Fix aquamarine dep, since 0.4.0 release has been withdrawn.
Signed-off-by: Sami J. Mäkinen <sjm@iki.fi>
> Fix aquamarine dep

- RELEASE.md
I think these were added accidentally
> RELEASE.md: remove spurious backticks

- crates/matrix-sdk/src/oidc/registrations.rs
I realized that having `Result<X, ()>` was equivalent to an `Option`, and then the simplifications just happened by themselves...
> oidc: cleanup `read_registration_data()` again

- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
- crates/matrix-sdk-ui/src/timeline/item.rs
- crates/matrix-sdk-ui/src/timeline/read_receipts.rs
- crates/matrix-sdk-ui/src/timeline/util.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/src/sync.rs
This can be reviewed commit by commit. These are small changes while I'm learning about the timeline's code.
> timeline: add comments and simplify code a bit

- testing/matrix-sdk-integration-testing/src/tests/reactions.rs
The room sync could be over, and then the timeline items would not contain the updated item yet, if the timeline didn't get a chance to finish its internal update. Fix this by:
1. limiting the sync time to 10 seconds
2. giving up to one second for the timeline to update internally, by watching its stream of events (we're ignoring stream updates just after this loop)
> integration test: fix racy behavior in the `test_toggling_reaction`

- examples/custom_events/src/main.rs
This closes: https://github.com/matrix-org/matrix-rust-sdk/issues/733
> Showcase how to use an event handler context in the custom events example

- xtask/src/swift.rs
Currently there are 3 separate code paths to build an xcframework depending on if you specify `--only-target`, nothing (all the targets) or `--sequentially` (all the targets one-by-one aka Stefan mode). This PR fixes that by defining all of the known targets and using the input to pick which ones should be included. This paves the way forward for us to include more supported platforms in the task (e.g. Mac Catalyst) whilst also being able to build for a certain subset of the targets.
> Improve the handling of targets in the Swift xtask.

- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk/src/account.rs
Just some tiny doc fixes I had lying around from elsewhere.
Signed-off-by: Denis Kasak <dkasak@termina.org.uk>
> Drive-by doc improvements

- labs/rrrepl/src/main.rs
I was trying to reproduce https://github.com/element-hq/element-x-ios/issues/1479 with rrrepl, with no luck. At least, this updates the CLI tool to use `Timeline::mark_as_read`, and adapt to other recent API changes.
> rrrepl: use `Timeline::mark_as_read` there too

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/deduplicating_handler.rs
- crates/matrix-sdk/src/room/mod.rs
While looking at a rageshake from EX apps, I've noticed that we can now get multiple requests to send the same read receipt (which is expected since I've asked EX devs to completely let us handle read receipts, to avoid stuck unreads). It's wasted work, and we already have a deduplicating handler somewhere in the code (which could be a separate crate useful in isolation, maybe?).
> sdk: deduplicate sending read receipts

- benchmarks/benches/crypto_bench.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/src/room/mod.rs
> Discard session API and bindings for `Room` 

- crates/matrix-sdk-common/src/executor.rs
- crates/matrix-sdk-common/src/ring_buffer.rs
- crates/matrix-sdk/src/event_cache/mod.rs
- testing/matrix-sdk-test-macros/src/lib.rs
This PR is a sequence of small refactoring. Please review it commit by commit. It contains a race condition fix.
> fix(sdk): Race condition, doc, and Wasm in `EventCache`

- crates/matrix-sdk-ui/src/notification_client.rs
A small change to keep the `RawNotificationsEvent` around after processing to allow any third party that isn't serializable into `AnyNotificationEvent` to still access the content, parse it themselves and display the notification.
Signed-off-by: Benjamin Kampmann <ben@acter.global>
> notification client: Keep the raw notification event around for further processing

- crates/matrix-sdk-crypto/src/backups/keys/decryption.rs
- crates/matrix-sdk/src/client/builder.rs
- crates/matrix-sdk/src/media.rs
- crates/matrix-sdk/src/room/power_levels.rs
Just a couple of warnings that were annoying.
> chore(sdk): Remove useless imports or fix unused code

- bindings/matrix-sdk-ffi/src/platform.rs
The built in hourly preset doesn't let us specify a max file count so files won't be tidied up. Additionally whilst I was here I added a `file_suffix` so that we can write to `.log` files on iOS (helps with previewing them).
> FFI: Allow logs to be pruned and written with a file extension.

- examples/getting_started/src/main.rs
> fix(examples): Fix typos in getting started example

- crates/matrix-sdk/src/client/mod.rs
Fixes: #3185
I also removed the `Visibility` use-declaration because it doesn't seem to be used in the example.
> chore: improve create_room documentation

- bindings/matrix-sdk-ffi/src/client.rs
exposed in ffi a way to join a room using a room id
> feat(bindings): added join room by id to ffi

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/src/ruma.rs
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/src/http_client/mod.rs
- crates/matrix-sdk/src/media.rs
Pull in https://github.com/ruma/ruma/pull/1747 and https://github.com/ruma/ruma/pull/1749 so that it works with wasm.
> Update Ruma to version that uses web-time crate

- crates/matrix-sdk-ui/src/timeline/inner/mod.rs
- crates/matrix-sdk-ui/src/timeline/inner/state.rs
What it says on the tin. I've seen this code, understood it once, then forgot, then wondered how the heck it was correct, so let's make it into a comment so I can just read that next time.
> timeline: add comments about insertion order to the front of the timeline

- labs/multiverse/src/main.rs
This is handy when running mitmproxy on multiverse.
(Skipping review, since this is multiverse.)
> multiverse: allow setting a proxy

- crates/matrix-sdk-crypto/src/qr_login/types.rs
Spelling fixes. For @poljar.
Signed-off-by:
> QR spelling fixes

- bindings/matrix-sdk-ffi/src/client.rs
- bindings/matrix-sdk-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/room_preview.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/lib.rs
- crates/matrix-sdk/src/room_preview.rs
- crates/matrix-sdk/tests/integration/client.rs
- testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
> sdk: give the ability to get a room's preview

- bindings/matrix-sdk-ffi/src/encryption.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3323
> ffi: Expose Encryption::wait_for_e2ee_initialization_tasks

- .github/workflows/audit.yml
- .github/workflows/benchmarks.yml
- .github/workflows/bindings_ci.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/xtask.yml
- .typos.toml
Should get rid of most warnings in CI.
I took the liberty to replace 2 unmaintained actions, these commits can be reverted if that's not wanted.
> ci: Upgrade most actions

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/types/device_keys.rs
See commit message for rationale.
> Docs and logging tweaks related to DeviceKeys

- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/olm/signing/mod.rs
- crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs
> chore(crypto): Refactor the PK signing subkey constructors

- bindings/matrix-sdk-ffi/src/client.rs
This PR makes the following changes:
- When resolving a room alias, also return the server names so they can be used later if needed.
- Expose `join_room_by_alias_or_id` which allows passing the server names from the via parameters in a permalink.
It doesn't help with getting the room preview which also needs to support the via parameters, but I haven't figured out how that one works yet.
> FFI: Support the use of via parameters when looking up and joining rooms.

- Cargo.lock
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/machine.rs
> Backport the fix for GHSA-9ggc-845v-gcgv and bump the crypto crate version

- crates/matrix-sdk/src/room/futures.rs
It is named filename before and after, and it is not a url.
It doesn't change anything, it just makes the code easier to follow, in my opinion.
> sdk: Rename SendAttachment's `url` field to `filename`

- crates/matrix-sdk/src/attachment.rs
- crates/matrix-sdk/src/room/futures.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
Particularly useful for captions
> sdk: Allow to send mentions with attachments

- crates/matrix-sdk-common/src/store_locks.rs
This should make it clearer why we can spawn the renew task twice in a row very quickly.
cc @kegsay
> cross-process lock: add a log line when aborting the previous renew task

- bindings/apple/MatrixSDKCrypto-Local.podspec
- bindings/apple/MatrixSDKCrypto.podspec
Updated the podspec files following the latest release of MatrixSDKCrypto to cocoapod.
Signed-off-by:
> Apple Bindings | Update SDKCrypto podspec files

- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/machine.rs
- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
> feat(crypto): If available, sign the new device keys using the cross-signing keys

- benchmarks/benches/crypto_bench.rs
- benchmarks/benches/room_bench.rs
- bindings/matrix-sdk-crypto-ffi/src/machine.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/backups/mod.rs
- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/account.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
> feat(crypto): Allow the creation of an OlmMachine using a custom Account

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/machine.rs
> feat(crypto): Allow the explicit upload of the device keys

- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/tests/integration/encryption/verification.rs
> sdk: Add method to request user identity from homeserver

- Cargo.lock
- bindings/matrix-sdk-ffi/Cargo.toml
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk/Cargo.toml
- examples/secret_storage/Cargo.toml
- labs/multiverse/Cargo.toml
> chore: remove unused dependencies

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- Cargo.toml
- crates/matrix-sdk-base/build.rs
- crates/matrix-sdk-common/build.rs
- crates/matrix-sdk-crypto/build.rs
- crates/matrix-sdk-indexeddb/build.rs
- crates/matrix-sdk-sqlite/build.rs
- crates/matrix-sdk-ui/build.rs
- crates/matrix-sdk/build.rs
- xtask/src/main.rs
See https://blog.rust-lang.org/2024/05/06/check-cfg.html#expecting-custom-cfgs for docs.
> Configure unexpected-cfgs via Cargo.toml instead of build scripts

- Cargo.lock
fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3467
Signed-off-by: Manmeet Singh <manmeetmann2003@gmail.com>
> fix: bump deadpool-sync

- crates/matrix-sdk/src/send_queue.rs
- crates/matrix-sdk/tests/integration/send_queue.rs
@ganfra reported that he got a "disabled" global status notification first, and that he couldn't cancel sending of the event at hand. In theory, one would need to be very lucky to be in that situation, but if the tokio runtime is very busy, it could be that the next `.await` at line 347 (before) is super slow. 
I couldn't trial this in a regression test, so I just introduced a test that mimics the steps to reproduce. It was passing before this PR, but probably would intermittently fail with a very low rate.
> send queue: try to avoid a race when disabling then aborting a send

- crates/matrix-sdk/src/sliding_sync/list/mod.rs
> doc(sdk): Fix a formatting typo

- crates/matrix-sdk/src/sliding_sync/list/mod.rs
This patch removes the useless `SlidingSyncList::get_room_id` method as I don't see how it can be useful for anybody. It's mostly dead public code, let's clean that up.
> chore(sdk): Remove the useless `SlidingSyncList::get_room_id` method

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/src/room.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
Ruma introduces a slightly different api to be compatible with the new default format for matrix_rtc events.
See: https://github.com/ruma/ruma/pull/1829
Signed-off-by:
> MatrixRTC: compatibility with new membership format (MSC4143) (ruma api changes)

- crates/matrix-sdk-ui/src/timeline/error.rs
- crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
- crates/matrix-sdk-ui/src/timeline/mod.rs
These are small refactorings I spotted during the review of #3553, and I didn't want to add more back-and-forth to that review.
> timeline: small refactorings after #3553

- examples/oidc_cli/src/main.rs
This adds support to input your recovery key to the OIDC example which will allow the OIDC example client to be verified and have access to all the secrets (cross-signing keys and the backup recovery key).
Not particularly useful right now, but once the OIDC example is able to log in other devices via a QR code it becomes necessary to have access to all the secrets.
> examples: Add a recovery command to the oidc-cli example

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk/Cargo.toml
- testing/matrix-sdk-integration-testing/Cargo.toml
- testing/matrix-sdk-integration-testing/src/helpers.rs
- testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
This also checks that secrets are gossiped from one device to the other and that the recovery and backup states are correctly updated.
>  test: Add a test to verify that interactive self-verification works

- crates/matrix-sdk-base/src/store/memory_store.rs
To help debug https://github.com/matrix-org/complement-crypto/issues/77
> base: Add trace logging to memory store

- labs/multiverse/src/main.rs
This allows seeing the events directly from the room event cache. I'm hoping this will give us some interesting insights about duplicates, among other things.
> multiverse: add Events view

- bindings/matrix-sdk-ffi/src/platform.rs
> ffi: add docs for `TracingFileConfiguration` and `TracingConfiguration`

- .cargo/config.toml
- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/olm/mod.rs
- crates/matrix-sdk-crypto/src/secret_storage.rs
- crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs
- crates/matrix-sdk-ui/src/room_list_service/filters/normalized_match_room_name.rs
- crates/matrix-sdk/src/authentication/qrcode/secure_channel.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/event_cache/paginator.rs
- crates/matrix-sdk/src/media.rs
- crates/matrix-sdk/src/oidc/mod.rs
- crates/matrix-sdk/src/oidc/tests.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
- crates/matrix-sdk/src/test_utils.rs
- crates/matrix-sdk/src/widget/machine/mod.rs
- crates/matrix-sdk/src/widget/machine/tests/openid.rs
- crates/matrix-sdk/src/widget/matrix.rs
- testing/matrix-sdk-integration-testing/src/tests/nse.rs
> clippy: Enforce the `redundant_clone` lint rule

- testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This patch rewrites the `test_delayed_decryption_latest_event` test a little bit. It does exactly the same things, but in a simpler way: it removes multiple `sleep` and remove 2 sliding sync loops.
First off, the `SyncService` already starts the `RoomListService` and the
`EncryptionSync` service. Both of them have their own sliding sync
loop. The test doesn't need other sliding sync loops in their own tasks, this is not necessary at all: it's just pretty confusing and doesn't reflect the reality, i.e. how these API are supposed to be used.
Second, it also tests the room for Bob is seen as encrypted.
Third, the `VectorDiff::Reset` is tested before the event from Bob is sent. It's not only for clarity: it makes the test more robust for future modifications.
Fourth, instead of waiting with a …
> test(sdk): Rewrite `test_delayed_decryption_latest_event`

- crates/matrix-sdk/src/oidc/mod.rs
> docs: Fix the OIDC QR code login example in the docs

- crates/matrix-sdk-crypto/src/identities/manager.rs
This reduces the work we do to calculate changed devices etc. when DEBUG logging is not enabled, but more importantly (to me) it makes clear that this code is only used for logging.
> logging: Extract debug log code into a separate function.

- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk/tests/integration/room/common.rs
See each commit's message for more information.
> sdk-base: Improvements to `Room::compute_display_name()`

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/machine.rs
Please note, that this is merging into the 0.7 release branch, all the patches here, except the changelog update are already part of main.
> Release prep for the matrix-sdk-crypto release 0.7.2

- Cargo.lock
> workspace: update dependencies

- crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
Remove `Result` where it is not needed, and switch to `CryptoStoreError` instead of `OlmError` where possible. Soon, this will allow us to call some of these methods from places that don't know about `OlmError`.
> crypto: Simplify error types in SenderDataFinder

- crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
- crates/matrix-sdk-crypto/src/olm/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3755
> crypto: Remove unused retry_details from SenderData

- crates/matrix-sdk-base/src/client.rs
- crates/matrix-sdk/tests/integration/room/common.rs
The code used to only add new targets to rooms but never remove the ones that are not in the event anymore.
> base-sdk: Properly update direct targets of rooms with m.direct event

- crates/matrix-sdk-crypto/src/machine.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3751
Before this PR: every time we decrypt a message we calculate the VerificationState of the sender (by calculating the SenderData and converting).
After this PR: while decrypting, we check whether there is already SenderData linked to the InboundGroupSession. If there is, and it's "fully trusted" i.e. we have already manually verified the sender, we just use it and don't calculate. If it's not fully trusted, we recalculate SenderData and, if it's more trusted, store it and return it.
When we are de we have already stored SenderData with an InboundGroupSession
> crypto: Use most-trusted SenderData available when decrypting

- crates/matrix-sdk-ui/src/room_list_service/mod.rs
This patch adds logs inside the `RoomListService::sync` method to know what are the current states.
> chore(ui): Add logs inside `RoomListService::sync`

- bindings/matrix-sdk-crypto-ffi/src/lib.rs
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/error.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3793
~~(currently based on https://github.com/matrix-org/matrix-rust-sdk/pull/3847)~~
> Crypto: return error when sharing keys with a user that was previously verified but is not any more

- crates/matrix-sdk-sqlite/src/crypto_store.rs
This is a small refactor that should not affect behaviour in any way.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3544
> crypto: Share more code when unpickling InboundGroupSessions in sqlite store

- bindings/matrix-sdk-ffi/src/event.rs
This was missing and was needed to be able to properly use the timeline item for custom logic in the clients, such as removing notifications for redacted events.
Closes #3859.
Signed-off-by:
> ffi: add missing info for `MessageLikeEventContent::RoomRedaction`

- bindings/matrix-sdk-ffi/CHANGELOG.md
- bindings/matrix-sdk-ffi/src/timeline/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3842
Part of https://github.com/element-hq/element-internal/issues/614
> ffi: expose new `SessionRecipientCollectionError`s to application

- Cargo.lock
- Cargo.toml
This revision includes renaming `focus_select` (wrong) to `focus_selection` (correct).
Signed-off-by:
> MatrixRTC: Update ruma revision for `focus_select` fix

- crates/matrix-sdk-sqlite/src/crypto_store.rs
- crates/matrix-sdk-sqlite/src/event_cache_store.rs
- crates/matrix-sdk-sqlite/src/state_store.rs
- crates/matrix-sdk-sqlite/src/utils.rs
See each commit description for details.
> sqlite: Cleanup

- crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
- crates/matrix-sdk/src/test_utils.rs
- testing/matrix-sdk-test/src/event_builder.rs
Tiny tiny refactorings, and introducing a helper that'll be useful for the future.
> testing: tiny refactorings, introduce `assert_let_timeout`

- crates/matrix-sdk-ui/tests/integration/room_list_service.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
When subscribing to an already subscribed room, the subscription state was reset, the subscription was resent by cancelling the in-flight request. All this is useless and can create a feeling of lag.
This patch checks if a room is subscribed first. If it is, nothing happens. If it is not, the room subscription is created, and the in-flight request is cancelled.
Tests are updated to reflect this new change.
Note: room subscription settings are not taken into account in this “presence” pattern. It means that if we subscribe to an already subscribed room but with different settings, nothing will happen. The server will ignore the new settings anyway for the moment. It's because room subscriptions are sticky. It's a normal behaviour here.
> fix(sdk): Don't subscribe to already subscribed rooms in Sliding Sync

- bindings/matrix-sdk-ffi/src/encryption.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/tests/integration/encryption/cross_signing.rs
> crypto: fix OIDC cross-signing reset flows after backend authorization failure response change

- CONTRIBUTING.md
This should clarify how things are working here, I don't think I added anything new or controversial but feel free to disagree.
> docs: Add PR review guidelines.

- crates/matrix-sdk-ui/src/timeline/controller/mod.rs
- crates/matrix-sdk-ui/src/timeline/controller/state.rs
- crates/matrix-sdk-ui/src/timeline/day_dividers.rs
- crates/matrix-sdk-ui/src/timeline/tests/echo.rs
- crates/matrix-sdk-ui/src/timeline/tests/virt.rs
> timeline: don't add a read marker after one's own events

- crates/matrix-sdk/src/sliding_sync/mod.rs
> chore(sdk): Improve a doc and format code

- crates/matrix-sdk-ui/src/timeline/controller/state.rs
And log an error in production builds if that's not the case.
> timeline: check that unique IDs are indeed unique

- crates/matrix-sdk/tests/integration/encryption/backups.rs
My theory is that the intermittent failure depends on the ordering of the requests, and if the /keys/upload request happened before the key backup request, then after failing the next key backup request wouldn't run.
This is likely a small typo that the key upload returns a 404 error instead of a 200, let's see if this improves the situation.
Should help with https://github.com/matrix-org/matrix-rust-sdk/issues/3719.
> tests: try to address intermittent failures of incremental backup tests

- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
After enabling encryption, previous code would wait for a sync, assuming (probably?) that the result of encrypting would come from the next sync result.
Unfortunately, this is not sufficient: it could be that the sync would only contain previous events that were unrelated to the enabling of encryption, or that there's no sync in the next 3 seconds. As a result, checking that the room was encrypted after calling `enable_encryption()` doesn't guarantee it always is, and since there's a cache preventing another direct lookup from the state event, it's even worse: the room would consider itself to be not encrypted, with absolute certainty (until the remote echo for the encryption state event came back from the sync). Sending a room message event, in that case, would assume the room is …
> room: mark encryption state as missing if a room thinks it's not encrypted after enabling it

- bindings/matrix-sdk-ffi/src/room.rs
This PR adds the `_and_resend` part of #3909 as it's own method so a user can re-verify on a different device that supports it, and then come back to the device using the FFI and send the message that failed to be sent.
> FFI: Expose RoomSendQueue::unwedge to allow resending.

- bindings/matrix-sdk-ffi/src/timeline/mod.rs
This is all Rust code, after all :)
> ffi: rename RustShieldState to SdkShieldState

- crates/matrix-sdk/src/sliding_sync/client.rs
This patch improves `Client::available_sliding_sync_versions` when trying to detect the sliding sync proxy. Previously, we were relying on the `Client::server` to send the `discover_homeserver::Request`. Sadly, this value is an `Option<_>`, meaning it's not always defined (it depends how the `Client` has been built with `HomeserverConfig`: sometimes the homeserver URL is passed directly, so the server cannot be known).
This patch tries to find to discover the homeserver by using `Client::server` if it exists, like before, but it also tries by using `Client::user_id`. Another problem arises then: the user ID indeed contains a server name, but we don't know whether it's behind HTTPS or HTTP. Thus, this patch tries both: it starts by testing with `https://` and then fallbacks to `http://`.
A …
> feat(sdk): Use the user ID to discover the sliding sync proxy

- labs/multiverse/src/main.rs
Small improvement to multiverse, to help debug DM issues.
> multiverse: highlight which rooms are DMs in the list

- bindings/matrix-sdk-ffi/src/client.rs
This PR exposes the discovered server URL to the FFI.
> ffi: Expose the server URL to the app too.

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/rooms/mod.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk/src/client/mod.rs
> chore: Update to `ruma/ruma`

- crates/matrix-sdk/tests/integration/account.rs
Introduced by https://github.com/matrix-org/matrix-rust-sdk/pull/4002.
> chore: Fix a clippy warning

- testing/matrix-sdk-integration-testing/README.md
- explain what these tests are
- mention that it's sometimes needed to rebuild the synapse image
> integration tests: update instructions

- crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
This test started to fail intermittently, so I rewrote it slightly:
- instead of assuming that sleeping for `delay/2 milliseconds will be sufficient (very flakey in the code cov scenario), wait for 2 seconds
- instead of delaying the responses for `delay` milliseconds, delay them for 60 seconds
That way, no response should get through the client, and 2 seconds should enough time to spawn all the requests to the mock endpoint, so the test should be more precise.
> tests: change strategy for `test_ensure_max_concurrency_is_observed`

- xtask/src/swift.rs
> ffi: default to reldbg when building iOS bindings

- crates/matrix-sdk/src/encryption/identities/users.rs
It doesn't serve any purpose and only confuses people since we have many similarly named types.
> refactor: Fold the private UserIdentities struct into UserIdentity

- crates/matrix-sdk/src/event_cache/mod.rs
This was because we used a `BTreeSet`, which doesn't make sense anymore since the data part of the key got mangled with some value unrelated to the key itself.
> event cache(refactoring): don't have related event rely on ordering

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
- crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
When a message B is a reply to message A, an edit to message A should be reflected in the replied-to part of message B.
Part of #3905.
> timeline: update replies when a message has been edited

- Cargo.lock
- crates/matrix-sdk/Cargo.toml
Finally get rid of proc-macro-error and syn 1!
Fixes #3955.
> sdk: Upgrade aquamarine

- bindings/matrix-sdk-ffi/src/client.rs
This allows clients to set custom join rules for a room, as would be needed for the knock-only rooms, or restricted rooms (those that can only be joined if the user is part of some other room or space).
The mapping from `CreateRoomParameters` to the `create_room::v3::Request` is now using a `TryFrom` since some parsing inside can fail and it seems better to explicitly make the action fail so it can be retried than creating a room with the wrong parameters.
Signed-off-by:
> feature(ffi): Add optional `CreateRoomParameters::join_rule_override`

- crates/matrix-sdk-crypto/src/identities/manager.rs
- crates/matrix-sdk-crypto/src/identities/user.rs
- crates/matrix-sdk/src/room/identity_status_changes.rs
- testing/matrix-sdk-test/src/test_json/keys_query.rs
- testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
- testing/matrix-sdk-test/src/test_json/mod.rs
A bit less repeating ourselves in this test data. Ulterior motive: if we ever want to add more users it will be easier now we can see exactly what information is needed to create a user.…ally
> Tidy the IdentityStatusChanges test data

- .deny.toml
- Cargo.lock
Some misc fixes cargo-deny told me about.
> Clean up our cargo-deny config

- Cargo.lock
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/test_utils/mocks.rs
- crates/matrix-sdk/tests/integration/send_queue.rs
- testing/matrix-sdk-test/src/sync_builder/invited_room.rs
- testing/matrix-sdk-test/src/sync_builder/joined_room.rs
- testing/matrix-sdk-test/src/sync_builder/knocked_room.rs
- testing/matrix-sdk-test/src/sync_builder/left_room.rs
This was promised to me :cry:.
> Add examples to the MatrixMockServer docs

- crates/matrix-sdk-crypto/src/machine/mod.rs
Signed-off-by: Tobias Fella <fella@posteo.de>
> doc(crypto): Fix typo

- crates/matrix-sdk/src/client/mod.rs
- crates/matrix-sdk/src/event_handler/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4297
> doc(sdk): Specify how the `Client::observe_events` works

- bindings/matrix-sdk-ffi/src/ruma.rs
Removed in https://github.com/matrix-org/matrix-rust-sdk/pull/4323 by mistake, they're still needed on Element X Android.
> chore: bring back `MediaSource` JSON serialization methods

- crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
This patch fixes the `test_echo` test. It was doing the following:
* client sends an event to the server,
* servers acknowledges with the ID `$wWgymRfo7ri1uQx0NXO40vLJ`,
* client syncs and the server returns one event with ID `$7at8sd:localhost`,
* the test expects those 2 events to be the same!, which is incorrect.
The test was working because the transaction IDs are the same, but that's an abuse of the existing code (the code will change soon, another patch is coming). Whatever the code does: the connection must be based on the event ID, not the transaction ID.
---
> test(ui): Fix the `test_echo` test

- crates/matrix-sdk-ui/src/timeline/event_handler.rs
A comment was duplicating (the first trace! that's removed here), and the second block comment only applied to new items, and was not as concise as it could be.
> doc(timeline): tweak comments when inserting a new item

- .github/workflows/bindings_ci.yml
- .github/workflows/xtask.yml
- crates/matrix-sdk-common/src/js_tracing.rs
Not sure if that'll help, but let's see if we get rid of the undefined `__chkstk_darwin` issue.
> Fix our CI after Rust got bumped to 1.83

- crates/matrix-sdk-common/src/linked_chunk/builder.rs
- crates/matrix-sdk-common/src/linked_chunk/mod.rs
- crates/matrix-sdk/src/event_cache/mod.rs
- crates/matrix-sdk/src/event_cache/room/events.rs
Thanks @Hywan for spotting the issue.
> fix(event cache): use a correcter heuristic to decide whether to add initial events or not

- crates/matrix-sdk-crypto/src/verification/requests.rs
- crates/matrix-sdk/src/room/mod.rs
Clippy is nice. Be nice with Clippy.
> chore: Make Clippy happy

- crates/matrix-sdk-crypto/CHANGELOG.md
Merging https://github.com/matrix-org/matrix-rust-sdk/pull/4433 into main
> doc(crypto): Add changelog entry for #4424

- testing/matrix-sdk-integration-testing/src/tests/timeline.rs
> test: Await the device creation in the notification client redecryption test

- crates/matrix-sdk-ui/src/sync_service.rs
- crates/matrix-sdk-ui/src/timeline/controller/mod.rs
- crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
- crates/matrix-sdk-ui/src/timeline/traits.rs
- crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
- crates/matrix-sdk/src/room/futures.rs
Previously: https://github.com/matrix-org/matrix-rust-sdk/pull/4491
I've got one more PR with a slightly larger diff coming, then it should compile!
> More small fixes for compiling the UI crate to WASM

- bindings/matrix-sdk-ffi/CHANGELOG.md
- bindings/matrix-sdk-ffi/src/encryption.rs
- crates/matrix-sdk/src/encryption/identities/users.rs
> task(bindings): Expose `withdraw_verification` in `UserIdentity`

- crates/matrix-sdk-ui/src/timeline/tests/mod.rs
- crates/matrix-sdk-ui/src/timeline/traits.rs
Based on #4497 (that one should be merged first).
I think this should be the last change required to make the UI crate compile on WASM. I'll make a separate PR to add that to CI afterwards.
> refactor(ui): Use RPITIT / AFIT for RoomDataProvider

- crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
- crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
- crates/matrix-sdk/tests/integration/main.rs
- crates/matrix-sdk/tests/integration/room/joined.rs
- crates/matrix-sdk/tests/integration/room/tags.rs
- testing/matrix-sdk-test/src/mocks.rs
`MatrixMockServer`, `MatrixMockServer` everywhere.
> test: get rid of the `mock_redaction` and `synced_client` helpers

- crates/matrix-sdk-ui/src/timeline/controller/state.rs
- crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
When the event cache receives a `RoomEventCacheUpdate::UpdateTimelineEvents` this will be broadcasted to every timeline, we needed a special case in the pinned event timeline to filter out any items loaded in these updates that aren't pinned.
Signed-off-by:
> fix(timeline): avoid adding non-pinned events when back paginating

- crates/matrix-sdk-crypto/src/dehydrated_devices.rs
We missed a call to `sign_device_keys`. Pull out a test helper to make it more obvious where this code is coming from.
> test: fix cross-signing in legacy dehydrated device test

- crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
- crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
This commit and PR elected GOAT.
> chore: update copyright years for files newly introduced

- bindings/matrix-sdk-crypto-ffi/src/verification.rs
- crates/matrix-sdk-sqlite/src/utils.rs
- crates/matrix-sdk/src/event_cache/pagination.rs
- crates/matrix-sdk/src/room/edit.rs
- crates/matrix-sdk/tests/integration/encryption/secret_storage.rs
A couple of Clippy lints being fixed. See individual patches to learn more.
> chore: Thanks Clippy!

- crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
The test ends up with checking that the redact endpoint has been hit once. It's actually the send queue doing the redaction as a dependent send request, and it doesn't provide any notification mechanism in this case, so we can't really know when it's done doing it.
One solution would be to not check the number of calls to the redact/ endpoint, but that means checking for fewer things. Instead, I made it so that when hit, the endpoint will signal it to the main task using a oneshot channel; then the main task waits with a long timeout for the receiving end to get the notification it's been sent, which should be sufficient.
Fixes #4633.
> test: wait for the redact endpoint to be hit in `test_abort_before_being_sent`

- bindings/matrix-sdk-ffi/src/session_verification.rs
Turns out we need the sender avatar too, might as well expose the whole profile.
> chore(ffi): expose the whole sender profile when receiving a verification request

- bindings/matrix-sdk-ffi/src/client.rs
This is used to decide if the alias is resolved or not.
Signed-off-by:
> fix(ffi): `Client::resolve_room_alias` was mapping the wrong error type

- Cargo.toml
- benchmarks/Cargo.toml
- benchmarks/README.md
- benchmarks/benches/timeline.rs
Also introduces a new `profiling` profile to be used in benchmarking or profiling contexts.
cc @Hywan
> bench: add a new benchmark to measure the time to fill a timeline with many events

- crates/matrix-sdk/src/event_cache/pagination.rs
- crates/matrix-sdk/src/event_cache/room/mod.rs
The code before this patch was doing this:
- look if there's any prev-batch token available right now, aka look if there's a gap in the in-memory linked chunk
- look at the first chunk; if it's a gap, return to the caller so it resolves it
The check is done twice at two different levels, which is confusing. Instead, this patch rewrites it so that the chunk is done only in `load_more_event_backwards()`.
Note this is also correct for the case storage is disabled; in this case, we early return and always try to resolve the gap anyways.
> refactor(event cache): simplify flow when deciding to resolve a gap

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
- crates/matrix-sdk-base/src/rooms/normal.rs
- crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
- crates/matrix-sdk/src/lib.rs
- xtask/src/main.rs
I was seeing some weird rustfmt issues in my local edition 2024 branch, pretty sure this fixes those.
> chore: Bump nightly

- .github/workflows/detect-unused-dependencies.yml
Should resolve the CI issues around cargo-machete.
See also: https://github.com/bnjbvr/cargo-machete/issues/156#issuecomment-2681308436
> ci: use an hardcoded version of cargo-machete in CI

- crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
- crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
- crates/matrix-sdk-common/src/linked_chunk/relational.rs
- crates/matrix-sdk/src/event_cache/room/mod.rs
> refactor(event cache): apply review comments of #4708

- crates/matrix-sdk/src/event_cache/pagination.rs
- crates/matrix-sdk/src/event_cache/paginator.rs
And don'y rely on the `Paginator`. This simplifies the code a bit, avoids a few methods on the `Paginator`, and makes it more straightforward the pagination happens.
> refactor(event cache): call /messages directly in the room pagination

- crates/matrix-sdk-sqlite/src/event_cache_store.rs
> test(sqlite): Improve a test to check the uniqueness constraint

- Cargo.lock
- labs/multiverse/Cargo.toml
- labs/multiverse/src/main.rs
We're mainly simplifying things by using the provided helpers by the tracing and ratatui crates, we're also switching to clap for command line parsing.
> Small multiverse cleanup

- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/src/widget/mod.rs
- crates/matrix-sdk/src/widget/settings/element_call.rs
- crates/matrix-sdk/src/widget/settings/mod.rs
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/4793
Signed-off-by:
> feat(widgets, element-call) Update the widget url generation

- benchmarks/benches/linked_chunk.rs
- crates/matrix-sdk-common/src/linked_chunk/mod.rs
What it says on the tin. Thanks to [Massive](https://valgrind.org/docs/manual/ms-manual.html) for helping pinpoint where the leak was.
I've written this benchmark as a preparation step for the rewrite of the event cache SQL schema, so we can measure the impact caused by using a different table to store the events' content.
Some statistics for nerdz.
<details>
```
reading/memory store/10
time:   [1.5470 µs 1.5493 µs 1.5527 µs]
thrpt:  [6.4404 Melem/s 6.4544 Melem/s 6.4643 Melem/s]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high severe
reading/sqlite store/10
time:   [99.251 µs 103.96 µs 111.36 µs]
thrpt:  [89.802 Kelem/s 96.192 Kelem/s 100.75 Kelem/s]
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high severe
reading/memory store/100
time:   [13.922 µs 14.062 µs …
```
> task(linked chunk): fix leak on drop + benchmark reading a linked chunk from a store

- crates/matrix-sdk-common/src/linked_chunk/mod.rs
As suggested in https://github.com/matrix-org/matrix-rust-sdk/pull/4840#pullrequestreview-2716444870 :)
> doc(linked chunk): tweak comments related to clearing/dropping a linked chunk

- bindings/matrix-sdk-ffi/src/room.rs
This patch updates `Room::report_content` and `Room::report_room` to call the same methods on `matrix_sdk` instead of re-implementing them.
---
* Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/4713
* Close https://github.com/matrix-org/matrix-rust-sdk/issues/4681
> refactor(ffi): Call methods on `Room` instead of redoing the same work

- Cargo.lock
- Cargo.toml
Newly released, as there is a release of the SDK planned for this week.
> Upgrade Ruma to version 0.12.2

- crates/matrix-sdk-ui/src/sync_service.rs
- crates/matrix-sdk/src/encryption/mod.rs
- crates/matrix-sdk/src/http_client/mod.rs
- crates/matrix-sdk/src/sliding_sync/mod.rs
A grab-bag of improvements to how we handle tracing spans, in an attempt to make debugging easier.
> Cleanups and extensions to tracing span logic

- RELEASING.md
Remove unbreakable spaces, and add indentations.
> doc(releasing): Fixing markdown

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/CHANGELOG.md
- bindings/matrix-sdk-ffi/Cargo.toml
- crates/matrix-sdk-base/CHANGELOG.md
- crates/matrix-sdk-base/Cargo.toml
- crates/matrix-sdk-common/CHANGELOG.md
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-indexeddb/CHANGELOG.md
- crates/matrix-sdk-indexeddb/Cargo.toml
- crates/matrix-sdk-qrcode/CHANGELOG.md
- crates/matrix-sdk-qrcode/Cargo.toml
- crates/matrix-sdk-sqlite/CHANGELOG.md
- crates/matrix-sdk-sqlite/Cargo.toml
- crates/matrix-sdk-store-encryption/CHANGELOG.md
- crates/matrix-sdk-store-encryption/Cargo.toml
- crates/matrix-sdk-ui/CHANGELOG.md
- crates/matrix-sdk-ui/Cargo.toml
- crates/matrix-sdk/CHANGELOG.md
- crates/matrix-sdk/Cargo.toml
- testing/matrix-sdk-test-macros/CHANGELOG.md
- testing/matrix-sdk-test-macros/Cargo.toml
- testing/matrix-sdk-test/CHANGELOG.md
- testing/matrix-sdk-test/Cargo.toml
> chore: Release matrix-sdk version 0.11.0

- Cargo.lock
- crates/matrix-sdk/src/room/mod.rs
- labs/multiverse/Cargo.toml
- labs/multiverse/src/main.rs
- labs/multiverse/src/widgets/room_view/invited_room.rs
- labs/multiverse/src/widgets/room_view/mod.rs
This is a bit bigger than intended because I've added mouse support to press the "Accept" button.
Rejecting the invite magnifies an issue we have. If a room we are viewing gets removed from the room list, it will still be shown in the room view despite another room being selected.
But I think that's a fix for another time.
> feat(multiverse): Add support to join rooms you've been invited to

- crates/matrix-sdk-common/src/tracing_timer.rs
"How long would it take to figure out how to use a macro? Less than 10 minutes, right? RIGHT?"
> docs(common): add a comment explaining how to use the `timer!` macro

- crates/matrix-sdk/tests/integration/notification.rs
Part of #3716
I think I covered almost all the information in the events that were replaced by using `EventFactory` instead, the only thing missing is the "mention" of a user in the first message. I had a look at `EventFactory` and didn't see anything that immediately jumped out as being able to handle this, and from the assertions in the test I thought that maybe the "mention" in the first message wasn't fundamental to what the test was checking, so I left out the "mention" for now.
Please feel free to let me know if that was an incorrect assumption, I'm happy to make changes accordingly, and the same for any other feedback :slightly_smiling_face: 
> Test: Replace `sync_timeline_event!` with `EventFactory` in notification integration test

- Cargo.lock
- Cargo.toml
- bindings/matrix-sdk-ffi/Cargo.toml
- crates/matrix-sdk/Cargo.toml
This will later be handled once the [account data observation PR](https://github.com/matrix-org/matrix-rust-sdk/pull/4994) is ready
> Update Ruma to support MSC4278

- crates/matrix-sdk-ui/src/room_list_service/filters/normalized_match_room_name.rs
Helping solve https://github.com/element-hq/element-x-ios/issues/3365#issuecomment-2868961046.
> task(ui): Log when the room name is empty when filtering the room list

- bindings/matrix-sdk-ffi/src/widget.rs
- crates/matrix-sdk-common/src/deserialized_responses.rs
- crates/matrix-sdk/src/room/mod.rs
- crates/matrix-sdk/src/widget/README.md
- crates/matrix-sdk/src/widget/capabilities.rs
- crates/matrix-sdk/src/widget/machine/driver_req.rs
- crates/matrix-sdk/src/widget/machine/from_widget.rs
- crates/matrix-sdk/src/widget/machine/incoming.rs
- crates/matrix-sdk/src/widget/machine/mod.rs
- crates/matrix-sdk/src/widget/machine/tests/capabilities.rs
- crates/matrix-sdk/src/widget/machine/to_widget.rs
- crates/matrix-sdk/src/widget/mod.rs
- crates/matrix-sdk/src/widget/settings/mod.rs
> docs(WidgetDriver): add initial module documentation

- crates/matrix-sdk-sqlite/src/state_store.rs
Under some very particular circumstances, the "database is locked" error can still happen, even in WAL mode, even if the database connection is not being upgraded from a read transaction to a write transaction.
We *think* this might be the reason behind errors like https://github.com/element-hq/element-x-ios/issues/3582, so we're enabling the sqlite busy_timeout, which will retry the operation after a short sleep, until the busy timeout is being hit.
See also https://github.com/element-hq/element-x-ios/issues/3582#issuecomment-2875836411
> feat(state store): enable the busy timeout to automatically retry operations on busy DBs

- crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
- crates/matrix-sdk-base/src/event_cache/store/media/integration_tests.rs
- crates/matrix-sdk-base/src/store/integration_tests.rs
> refactor: Use native async fn in traits for testing traits

- crates/matrix-sdk-crypto/CHANGELOG.md
Put one change in the right place in the changelog, and add missing PR links.
> crypto: changelog fixes

- Cargo.lock
- crates/matrix-sdk-base/src/event_cache/store/mod.rs
- crates/matrix-sdk-common/Cargo.toml
- crates/matrix-sdk-common/src/store_locks.rs
- crates/matrix-sdk-crypto/src/store/mod.rs
> refactor: Use native async fn in traits for BackingStore

- labs/multiverse/src/widgets/room_view/invited_room.rs
I tested this with two multiverse instances, seemed to work correctly.
This closes: https://github.com/matrix-org/matrix-rust-sdk/issues/5142
> fix(multiverse): Wait for the join task to finish before switching the view

- bindings/matrix-sdk-ffi/src/client.rs
Use `Client::room_info_notable_update_receiver` instead of `RoomUpdates`
This allows us to also react to local changes that would take several extra seconds to be received in a new sync response.
@ganfra found out this problem when testing this with unknown rooms he requested to join, the response using the previous implementation took way longer than it was needed. This new one behaves way better.
Signed-off-by:
> refactor(ffi): Improve `Client::subscribe_to_room_info`

- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/src/identities/manager.rs
This PR cherry-picks https://github.com/matrix-org/matrix-rust-sdk/pull/5191 into our `0.11` release branch.
> fix(crypto): Remove wildcard enum variant import

- crates/matrix-sdk/src/account.rs
- crates/matrix-sdk/src/error.rs
What it says on the tin. Fixes #5073.
> feat(sdk): forbid ignoring the current user

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-crypto/CHANGELOG.md
- crates/matrix-sdk-crypto/Cargo.toml
- crates/matrix-sdk-crypto/src/machine/mod.rs
- crates/matrix-sdk-crypto/src/machine/tests/decryption_verification_state.rs
- crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
- crates/matrix-sdk/src/room/mod.rs
This PR merges our release branch back into main, bringing in a fix for https://github.com/matrix-org/matrix-rust-sdk/security/advisories/GHSA-x958-rvg6-956w.
> Merge 0.11 back into main

- .config/nextest.toml
- .github/workflows/coverage.yml
- .github/workflows/upload_coverage.yml
- crates/matrix-sdk-ui/tests/integration/sync_service.rs
- xtask/src/ci.rs
A continuation of #5241, somehow caches got messed up with that PR and CI was completely borked.
Let's see if the suffering continues or we get somewhere with this.
>  Switch to llvm-cov for coverage reports

- bindings/matrix-sdk-ffi/src/timeline/mod.rs
Adjust some imports to use our shims to support Wasm.
> feat(wasm): Small fixes for imports in ffi timeline

- crates/matrix-sdk-crypto/src/machine/mod.rs
At this point in the code it is no longer raw.
Preparation for https://github.com/matrix-org/matrix-rust-sdk/issues/4147
> refactor(crypto): Rename raw_event to processed_event to reflect its changed state

- crates/matrix-sdk-base/src/sliding_sync.rs
- crates/matrix-sdk-common/src/linked_chunk/updates.rs
- crates/matrix-sdk-crypto/src/store/caches.rs
- crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
> Fix new lints in nightly

- labs/multiverse/Cargo.toml
- labs/multiverse/src/main.rs
- labs/multiverse/src/widgets/recovery/default.rs
- labs/multiverse/src/widgets/recovery/mod.rs
- labs/multiverse/src/widgets/recovery/recovering.rs
- labs/multiverse/src/widgets/room_list.rs
- labs/multiverse/src/widgets/room_view/details/read_receipts.rs
- labs/multiverse/src/widgets/room_view/invited_room.rs
- labs/multiverse/src/widgets/room_view/mod.rs
- labs/multiverse/src/widgets/room_view/timeline.rs
- labs/multiverse/src/widgets/status.rs
… and use let chains! 🙌🏼 
Signed-off-by: Jonas Platte
> chore(multiverse): Upgrade to Rust edition 2024

- examples/autojoin/Cargo.toml
- examples/autojoin/src/main.rs
- examples/backups/Cargo.toml
- examples/backups/src/main.rs
- examples/command_bot/Cargo.toml
- examples/command_bot/src/main.rs
- examples/cross_signing_bootstrap/Cargo.toml
- examples/cross_signing_bootstrap/src/main.rs
- examples/custom_events/Cargo.toml
- examples/custom_events/src/main.rs
- examples/emoji_verification/Cargo.toml
- examples/emoji_verification/src/main.rs
- examples/get_profiles/Cargo.toml
- examples/get_profiles/src/main.rs
- examples/getting_started/Cargo.toml
- examples/getting_started/src/main.rs
- examples/image_bot/Cargo.toml
- examples/image_bot/src/main.rs
- examples/login/Cargo.toml
- examples/login/src/main.rs
- examples/oauth_cli/Cargo.toml
- examples/oauth_cli/src/main.rs
- examples/persist_session/Cargo.toml
- examples/persist_session/src/main.rs
- examples/qr-login/Cargo.toml
- examples/qr-login/src/main.rs
- examples/secret_storage/Cargo.toml
- examples/secret_storage/src/main.rs
- examples/timeline/Cargo.toml
- examples/timeline/src/main.rs
> Upgrade examples to Rust edition 2024

- crates/matrix-sdk-ui/src/timeline/tests/polls.rs
When we upgrade Ruma, the `EventContent` bound on `EventBuilder` will be changed to `StaticEventContent`, which is not implemented by the `Any*EventContent` enums.
> refactor: Don't use `AnyMessageLikeEventContent` with the event factory

- crates/matrix-sdk-crypto/src/machine/mod.rs
As I try to unravel what the to-device handling code does, I tried to write a bit about what `handle_to_device_event` does, and I made the `match` statement enumerate all the possible types, to help us avoid missing something later if we add a new one.
I'd love it if someone who understands could read what I've written and check it makes sense. Thanks!
> doc(crypto): Attempt to explain what handle_to_device_event does and make all types explicit

- Cargo.lock
- crates/matrix-sdk-sqlite/Cargo.toml
Signed-off-by: Jade Ellis <jade@ellis.link>
> chore: Update rusqlite

- bindings/matrix-sdk-ffi/src/platform.rs
- crates/matrix-sdk-ui/src/notification_client.rs
What it says on the tin. Also makes the code in the notification client a bit more regular in terms of comments, naming, and logs.
> feat(ffi): add a new log pack for the notification client

- crates/matrix-sdk/src/event_cache/room/mod.rs
The metadata loading shouldn't cause an error to be displayed, when the linked chunk is empty; this can happen for new rooms we've never visited. This is harmless, because in this case the linked chunk would be reset on disk… which is a no-op since it was empty in the first place.
Spotted while investigating some failures in a rageshake; this would cause many lines with the following error:
> 311:2025-07-02T14:41:35.160589Z ERROR matrix_sdk::event_cache::room::private: error when loading a linked chunk's metadata from the store: the linked chunk metadata is invalid: no last chunk found | crates/matrix-sdk/src/event_cache/room/mod.rs:589 | spans: root > sync_once{conn_id="room-list" pos="abc"} > handle_response
> fix(event cache): don't return an error when a linked chunk is empty

- uniffi-bindgen/Cargo.toml
- xtask/Cargo.toml
- xtask/src/ci.rs
- xtask/src/fixup.rs
- xtask/src/kotlin.rs
- xtask/src/main.rs
- xtask/src/release.rs
- xtask/src/swift.rs
- xtask/src/workspace.rs
> Upgrade xtask and uniffi-bindgen to Rust edition 2024

- examples/getting_started/src/main.rs
> fix(examples): Remove a duplicate comment from the examples

- bindings/matrix-sdk-ffi/src/platform.rs
As described in #5375, this PR allows apps to update the directory used to write log files at runtime, so that logs could be segregated by e.g. user/homeserver etc.
Closes #5375
> FFI: Allow tracing's RollingFileAppender to be updated at runtime.

- crates/matrix-sdk-indexeddb/CHANGELOG.md
I would say that support for encrypted history is notable.
> indexeddb: Remove incorrect line from changelog

- crates/matrix-sdk/src/event_cache/mod.rs
This patch adds more logs inside `EventCache` around the `multiple_room_updates_lock` and around the `listen_task`, just to be sure if everything is listened and works as expected.
> feat(sdk): Add more logs in `EventCache`

- crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
- crates/matrix-sdk-base/src/response_processors/state_events.rs
- crates/matrix-sdk-base/src/response_processors/timeline.rs
- crates/matrix-sdk-base/src/room/members.rs
- crates/matrix-sdk-base/src/room/mod.rs
- crates/matrix-sdk-base/src/store/ambiguity_map.rs
- crates/matrix-sdk-base/src/store/mod.rs
- crates/matrix-sdk/src/room/mod.rs
This tries to reduce duplication for code that accesses the power levels of a room.
> base: Refactoring around room power levels

- benchmarks/Cargo.toml
- benchmarks/benches/crypto_bench.rs
- benchmarks/benches/linked_chunk.rs
- benchmarks/benches/room_bench.rs
- benchmarks/benches/store_bench.rs
- benchmarks/benches/timeline.rs
> chore: Upgrade benchmarks to Rust Edition 2024

- crates/matrix-sdk-store-encryption/Cargo.toml
- crates/matrix-sdk-store-encryption/src/lib.rs
> chore: Upgrade matrix-sdk-store-encryption to Rust Edition 2024

- .github/workflows/benchmarks.yml
- benchmarks/benches/crypto_bench.rs
- benchmarks/benches/event_cache.rs
- benchmarks/benches/linked_chunk.rs
- benchmarks/benches/room_bench.rs
- benchmarks/benches/store_bench.rs
- benchmarks/benches/timeline.rs
Let's see if we can get some more benchmarks running.
> ci: Enable more benchmarks

- crates/matrix-sdk-common/src/failures_cache.rs
Follow-up to #5490.
Signed-off-by: Jonas Platte
> refactor: Simplify some methods of FailuresCache

- crates/matrix-sdk-base/src/response_processors/notification.rs
- crates/matrix-sdk-ui/src/notification_client.rs
- crates/matrix-sdk-ui/tests/integration/notification_client.rs
Some simplifications extracted from #5461.
> refactor(notification client): misc simplifications

- crates/matrix-sdk/src/event_cache/room/mod.rs
This can happen because of an OS-level error, so let's try to handle it in a slightly cleaner way. At the moment, it will bubble up and only be logged, but we might try to find a better way to handle this at the top-level.
> refactor(event cache): don't panic when loading a linked chunk's latest event fails

- Cargo.lock
- Cargo.toml
- crates/matrix-sdk-base/src/room/call.rs
So as to get some backwards-compat changes for Element Call: https://github.com/ruma/ruma/pull/2176
> chore: bump Ruma

- crates/matrix-sdk-base/src/response_processors/account_data/room.rs
- crates/matrix-sdk-base/src/response_processors/room/msc4186/extensions.rs
- crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
- crates/matrix-sdk-base/src/room/tags.rs
- crates/matrix-sdk-base/src/sliding_sync.rs
:notes: what it says on the tin :notes:
> refactor(sdk): remove a few useless async

- Cargo.lock
- labs/multiverse/Cargo.toml
- labs/multiverse/src/main.rs
- labs/multiverse/src/widgets/create_room/mod.rs
- labs/multiverse/src/widgets/popup_input.rs
- labs/multiverse/src/widgets/search/mod.rs
This PR changes search in multiverse to show the sender and message in the results instead of just event id's.
Signed-off-by: Shrey Patel shreyp@element.io
> feat(multiverse): Show messages in search results.

- crates/matrix-sdk-search/src/index.rs
- crates/matrix-sdk/Cargo.toml
- crates/matrix-sdk/src/client/search.rs
- crates/matrix-sdk/src/room/mod.rs
- labs/multiverse/src/main.rs
Add a `pagination_offset` to allow paginated of search results.
Signed-off-by: Shrey Patel shreyp@element.io
> feat(search): Add paginated search

- .github/workflows/benchmarks.yml
> bench: Run the `room_list` benchmark in the CI
