matrix-org/matrix-rust-sdk

Cargo.lock, Cargo.toml
This patch switches UniFFI from
https://github.com/mozilla/uniffi-rs/pull/1684 to
https://github.com/mozilla/uniffi-rs/pull/1697.
Tested by @ganfra, and it works.
=> chore(uniffi): Update `uniffi` to another branch

Cargo.lock, Cargo.toml
See CI task failure in https://github.com/matrix-org/matrix-rust-sdk/pull/2404.
=> Revert upgrade to uniffi since it broke generation of swift bindings

bindings/matrix-sdk-ffi/src/room_info.rs
* remove `is_encrypted` from room info as it's not used and it might do network calls and slow down room list updates
* use the sliding sync avatar unstead of the room one as it has extra logic for DMs
=> RoomInfo: Remove is_encrypted use sliding sync room avatars

bindings/matrix-sdk-ffi/src/timeline.rs
Add FFI binding to create message events with custom HTML.
We currently have `message_event_content_from_markdown()` which can detect markdown and produce a message event containing formatted HTML content. However, markdown detection is limited and can lead to bugs such as vector-im/element-x-android#1070.
Hence the need for apps to create message events from a custom plain text body and formatted HTML body.
=> Add binding to create message events from HTML

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs, crates/matrix-sdk-ui/src/room_list_service/filters/normalized_match_room_name.rs
This patch adds a new filter for room list's entries. We had `all` and `fuzzy_match_room_name`, now this patch adds `normalized_match_room_name`. Both the pattern and the subject are normalized and lowercased, and then it's an exact match: `subject.contains(pattern)`.
=> feat(ui): Create a new `normalized_match_room_name` filter

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room_list.rs
While waiting on https://github.com/mozilla/uniffi-rs/pull/1714 to be merged, we can simply rename `RoomListState::Init` to `::Initial`, and the problem is solved on our side. That's what this patch does.
=> fix(ffi): Fix a keyword conflict with Swift

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
In the previous situation, we had two locks with similar responsibilities, the `response_handling_lock` and the `position` lock. The latter *almost* covered the former's critical zone, albeit for a single function call, which left room for a deadlock situation (latter taken, then former, then latter).
This removes the former, and extends the critical zone of the latter up to the end of the response handling, removing the possibility of the deadlock entirely.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2426.
=> feat(sliding sync): remove `response_handling_lock` and extend the position's lock responsibilities

.github/workflows/ci.yml, .github/workflows/coverage.yml
Until https://github.com/michaelkaye/setup-matrix-synapse/issues/95 is properly resolved.
=> fix: temporarily use the pip install method for the setup-matrix-synapse action

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs
The original JSON will just be removed entirely. There might be edge cases where this is unfortunate for debugging, but it fixes the immediate problem in a simple manner. Computing the redacted JSON locally seems error-prone, but if there are debugging needs, we could probably offer users to update the JSON by re-requesting the event after redaction.
Resolves #2417.
=> Fix original content of messages being retained in JSON form on redaction

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/assets/ci-start.sh, testing/matrix-sdk-integration-testing/assets/docker-compose.yml, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
When sending an encrypted message, we'll sync members of the room, if we never did that before. That means we might discover new accounts for which we don't have any encryption keys; in that case, we'd need to send the queries for missing users. This PR implements that.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2236
Fixes https://github.com/vector-im/element-x-ios/issues/1275
=> feat: query keys for newly sync'd members when sending encrypted message

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, bindings/matrix-sdk-ffi/src/error.rs, crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/data_serde.rs, crates/matrix-sdk/src/oidc/mod.rs
This PR builds on top of #1019 exposing OIDC to the bindings.
- The authentication service can be configured for OIDC (performing dynamic registration) and supports login via OIDC.
- The FFI client now converts `Session` to/from the OIDC Sessions when necessary.
- `UnknownToken` errors are now broadcast from the refresh logic depending on the errors encountered.
- `SessionChange`s are also broadcast to indicate that the app should update the session in whatever secure storage is being used.
Left todo in this PR:
=> feat(bindings): OIDC in AuthenticationService.

xtask/src/ci.rs, xtask/src/kotlin.rs, xtask/src/swift.rs, xtask/src/workspace.rs
… where we no longer need to specify the UDL file (its data is picked up automatically through the generated scaffolding).
=> Use uniffi-bindgen's new "library mode"

xtask/src/ci.rs, xtask/src/swift.rs
This reverts commit 329b6c4eb1f158e91c5c7295daafff9bd2dddcd4.
It caused weird issues with Swift, that we'll look into when we have time.
=> Revert "bindings: Use new uniffi-bindgen build mode"

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Usually, when the sliding sync session expires, it leads the state to
be `Error`, thus some actions (like refreshing the lists) are executed.
However, if the sync-loop has been stopped manually, the state is
`Terminated`, and when the session is forced to expire, the state
remains `Terminated`, thus the actions aren't executed as expected.
Consequently, this patch updates the state to `Error` manually.
=> fix(ui): Tweak `State` of `RoomListService` when session is forced to expire

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/polls.rs
- Creates `polls` module in `timeline` to hold all related logic.
- `PollState` holds ruma types directly to keep it simple and reuse ruma’s existing aggregation logic.
- `PollPendingEvents` acts as a cache for response/end events that are handled before their start event has been handled. 
- Handles ruma's `UnstablePoll{Start, Response, End}` events.
- When a start event arrives it computes the starting `PollState`.
- If there are responses/end events in the `PollPendingEvents` cache it will move them from the cache to the state.
- When a response event arrives it updates the `PollState`.
- Or it is added to the `PollPendingEvents` if no start event is found yet.
- When an end event arrives it updates the `PollState`
- Or it is added to the `PollPendingEvents` if no start event is found …
=> Show polls in timeline

crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs
… and make the `handle_redaction` on `BaseRoomInfo` private, so it's not called directly (bypassing `RoomInfo::handle_redaction`).
This is a first step towards figuring out https://github.com/vector-im/element-x-ios/issues/1441.
=> Add logging for `handle_redaction`

crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This PR can be reviewed commit-by-commit.
The first patch reduces the `batch_size` of `invites` from 100 to 20.
The second does the following.
Inside `RoomListService`, the `State` enum handles the transition from
one state to another. In case of some `State::Error`, the `all_rooms`
sliding sync was refreshed, i.e. its sync-mode was reset to its initial
value.
This patch also refreshes the `invites` sliding sync list! It adds
the `ResetInvitesListGrowingSyncMode` action, and attaches it to the
`refresh_lists` actions.
New constants are added to represent default `batch_size` values for the
growing sync-mode for various sliding sync list. It could be helpful for
further maintenance.
This patch finally adds and updates the tests accordingly.
---
* Fixes …
=> feat(ui): Reduce and refresh the `batch_size` growing sync-mode of `invites` in `RoomListService`

crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/timeline/event_handler.rs
… by swapping the branches around. Previously, invocations meant to match the found + not_found branch were actually hitting the other one prior to Rust 1.71, likely due to parser supporting type ascription (even though it was an unstable feature).
=> Make update_timeline_item macro compatible with Rust 1.70

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/widget.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/widget/mod.rs
`run_widget_api` (better name suggestions welcome) does not do anything right now, and the `WidgetComm` type doesn't have any methods yet, but having this makes sure the API is bridge-able (after a small change to use `async_channel` where both sender and receiver are clonable).
=> ffi: Add widget API skeleton

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/sliding_sync_ext.rs
Note to self: Probably should add a changelog entry.
=> Allow subscribing to `RoomInfo` updates

.cargo/config.toml, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
We have some types that are !Send and/or !Sync only on wasm, it would be slightly more efficient, but also pretty annoying, to wrap them in Rc where we would use Arc on other platforms.
=> Silence clippy lint `arc_with_non_send_sync` on wasm

crates/matrix-sdk/src/notification_settings/mod.rs
This PR limits the number of retries when updating the push rules.
=> fix(sdk): limit the number of retries when updating push rules.

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Allow using `RoomMessageEventContent` instead of strings in order to edit or reply to events.
Main use case: an app that uses an advanced composer such as Matrix Rich Text Editor, might need to provide HTML + Markdown instead of just Markdown. 
Also actually moves from using `RoomMessageEventContent` to `RoomMessageEventContentWithoutRelation` in order to avoid having to "downcast" when attaching a replacement.
=> ffi: use `RoomMessageEventContentWithoutRelation` for send / reply / edit

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
When a user has hundreds of rooms, `RoomListService` will fetch at worst one event per room, which can generate large responses. Let's use a `timeline_limit=0`.
=> feat(ui): Change `all_rooms` to `timeline_limit=0`

crates/matrix-sdk/src/sliding_sync/list/builder.rs
Prior to this patch, we have increased the
`SlidingSyncListInner::room_list` capacity, to avoid trigger `VectorDiff::Reset` as much as possible. Now that Element X is optimised to handle larger diff, we can discrease this number, yeeeee :-).
=> feat(sdk): Adjust `room_list` observable capacity

bindings/matrix-sdk-ffi/src/platform.rs
Example output:
```
2023-08-25T12:20:29.337610Z TRACE matrix_sdk_ui::timeline::event_handler: Handling event | crates/matrix-sdk-ui/src/timeline/event_handler.rs:284 | stack: handle_event{event_id="$FuRWqHfOu949TacuzF:dummy.server" position=Update(2)}
2023-08-25T12:20:29.337642Z TRACE matrix_sdk_ui::timeline::event_handler: Found timeline item to update | crates/matrix-sdk-ui/src/timeline/event_handler.rs:1205 | stack: handle_event{event_id="$FuRWqHfOu949TacuzF:dummy.server" position=Update(2)} > handle_room_message_edit{replacement_event_id="$QJ8GvVn5PDehujg61h:dummy.server"}
2023-08-25T12:20:29.337659Z TRACE matrix_sdk_ui::timeline::event_handler: Applying edit | crates/matrix-sdk-ui/src/timeline/event_handler.rs:443 | stack: handle_event{event_id="$FuRWqHfOu949TacuzF:dummy.server" …
```
=> ffi: Add custom tracing log formatter

crates/matrix-sdk/src/widget/client/handler/capabilities.rs, crates/matrix-sdk/src/widget/client/matrix.rs, crates/matrix-sdk/src/widget/filter.rs, crates/matrix-sdk/src/widget/permissions.rs
This does not include the FFI.
Changes to the FFI are required however to support the `All` scope.
@jplatte 
I changed the `EventDeHelperForFilter` -> `MatrixEventFilterInput` let me know if you want this to be reverted (Because we decided for EventDeHelperForFilter in our sync but now I very much prefer MatrixEventFilterInput but at the end its just a preference thing so I dont mind.)
I am not sure about the structure of the EventFilter there are two obvious solutions:
```rust
enum EventFilter{
AllState,
AllMessageLike,
State(StateFilterDescriptor),
MessageLike(MessageFilterDescriptor),
}
```
or
```rust
enum EventFilter{
State(FilterScope<StateFilterDescriptor>),
MessageLike(FilterScope<MessageFilterDescriptor>),
}
enum FilterScope<T>{
All,
Custom<T>
}
```
I decided for the second …
=> Add parsing for the Capabilities/Permissions.

bindings/matrix-sdk-ffi/src/authentication_service.rs
Part of https://github.com/vector-im/element-x-ios/issues/1547 this PR updates the `OidcConfiguration` to take a logo URL that will be displayed in the Consent prompt.
Whilst this property is optional in the request, without it MAS displays a big white square so I chose to not make it an optional property on the configuration.
=> feat(bindings): Add logo_uri to OidcConfiguration.

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This PR must be reviewed commit-by-commit. It tries to make `RoomListService` fast for gigantic accounts with various network speeds and stability. It's basically fine-tuning.
=> fix(ui): Try to make `RoomListService` fast for gigantic accounts with various network speeds

bindings/matrix-sdk-crypto-ffi/build.rs
Some time ago [we found an issue](https://github.com/matrix-org/matrix-rust-sdk/pull/1782) with x86-64 binaries generated from the Rust SDK using NDK 25 lacking some symbols and instantly crashing any apps that used the library in x86-64 devices. The Crypto SDK is also affected by this issue, as seen in https://github.com/vector-im/element-android/issues/8546.
In this PR I added the same workaround to the crypto SDK FFI crate.
=> Add the x86-64 Android workaround to the Crypto SDK too

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs
… and clean up a few unnecessary Arc's.
=> ffi: Only ever call ClientDelegate methods in a blocking task

Cargo.lock, Cargo.toml, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/sliding_sync/mod.rs
This is a hunch I had when reading some rageshakes, but my hunch was wrong. At least that makes for a new test that I don't think we had somewhere else in the code base: make sure that if we skip a stream iteration because of a change in list A, list B parameters don't get updated.
=> test(sliding sync): skipping b/o mode change doesn't change parameters in other lists

crates/matrix-sdk/src/authentication.rs, crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/oidc/mod.rs
To help track down why an `InvalidGrant` error is unexpectedly being thrown, this PR logs the OIDC refresh token (in hashed form) in the following instances:
- After a successful refresh.
- After a failed refresh.
As `InvalidGrant` is thrown when a token is reused, this will allow the ability to track in the logs whether the token isn't being updated properly by the app or whether the issue may be on the backend. First part of #2476.
=> chore(sdk): Log the OIDC refresh token (hashed).

bindings/matrix-sdk-ffi/src/platform.rs
The previous PR disabled colors in logs for the file logging, but not for the console logging that iOS is using. This PR disables it everywhere for the FFI; I'm not aware of any consumer that would make use of it anyways.
=> chore: disable colors for logging in FFI for logcat and stdout too

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This PR must be reviewed commit-by-commit.
This patch updates 2 things:
1. The `invites` sliding sync list is always present. Prior to this patch, it was installed only after the first sync.
However, during the first sync, its `range` is `0..=0` to fetch at least one invite. Next syncs, its `range` is `0..=19`. It's the same when recovering.
2. The `visible_rooms` sliding sync recovers with a `timeline_limit=0`.
The tests are taking a large part of the diff, but the modifications aren't that big.
=> feat(ui): Fine-tuning `RoomList` again

crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This introduces a new `SlidingSyncBuilder` method, `restore_pos_from_database()`, that when enabled, will save the `pos` values into the database, and restore them just before running another request.
This will show useful in contexts where multiple processes can spawn a sliding sync, and we'd like continuity over the range of `pos` values that are sent, given a fixed `conn_id`. In particular, this will prevent spurious session expirations, when alternating between the sliding sync running in one process or the other. An example of that is the iOS setup, where we have the main app running as its own process, and a separate process running to decrypt notifications.
This can be reviewed commit by commit; the latest commit includes extensive tests, including some for session expiration (as …
=> feat(sliding sync): optionally persist/restore the `pos` in/from DB, and use that for encryption sync

crates/matrix-sdk/src/sliding_sync/list/builder.rs
Resets were happening very frequently again.
=> sdk: Revert observable diff buffer capacity change

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification_settings.rs, crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/timeline/to_device.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_handler/mod.rs, crates/matrix-sdk/src/notification_settings/mod.rs, examples/image_bot/src/main.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
Technically a breaking change I think, but realistically event handler closures were always clonable.
=> sdk: Make use of clonable FnOnce in event handlers

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/oidc/mod.rs
Save the OIDC refresh token obtained from the response (that was removed in an attempt to debug further invalid grant issues), and add some logs to help with debugging in the future.
=> fix: save the OIDC refresh token from the response (!)

crates/matrix-sdk/src/oidc/mod.rs
=> OIDC: don't save `latest_id` upon access token refresh

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
Supersedes #2467. Different fix, basically same test code (slightly adjusted to account for implementation differences).
- Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2284
- Fixes https://github.com/vector-im/element-x-ios/issues/911
=> Reset the timeline when ignore user list changes

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
I want to write a test too, but please @stefanceriu can you check if this fixes the issue you see in EX?
=> Transfer reply details from old to new item when receiving dup event

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification.rs, bindings/matrix-sdk-ffi/src/sync_service.rs, crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/sync_service/mod.rs, crates/matrix-sdk-ui/tests/integration/encryption_sync.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs, crates/matrix-sdk-ui/tests/integration/sync_service.rs, testing/sliding-sync-integration-test/src/notification_client.rs
This introduces a new `EncryptionSyncPermit`, which is required to *run* (note: not *create*) an encryption sync. With this, we can ensure that there's at most one encryption sync running at any times, and solve #2491 in a more elegant way than what we've done: instead of asking the app to start the sync service themselves, we can take a permit and run the encryption sync a few times by ourselves, if needs be.
This aligns the behaviors of the iOS and Android apps, paving the way to always enable retrying decryption of encrypted events in notifications, for both apps.
Fixes #2491.
=> feat: add an `EncryptionSyncPermit` and use it in the notification client

crates/matrix-sdk-crypto/src/store/integration_tests.rs
Should help with the CI failures we've seen recently related to the key_request_saving store.
=> fix(tests): don't reuse the same store name in multiple tests

crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs
... so that `VerificationStore` and `StoreInner` can share the same `save_changes` impl which broadcasts updates to the broadcast channels.
=> Implement new `CryptoStoreWrapper`

crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-ui/src/notification_client.rs
This was previously accepted by the compiler but is being phased out; it will become a hard error in a future release! See https://github.com/ rust-lang/rust/issues/115010.
=> fix: `&` without an explicit lifetime name cannot be used here

crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-ui/src/timeline/event_item/content.rs
*Maybe* a fix for https://github.com/vector-im/element-x-ios/issues/1441, I'm really not sure 😅
We've always wanted to include redacted events AFAICT, it was likely just a misunderstanding that we might want to exclude them.
=> Allow redacted events as latest event

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk-ui/tests/integration/sliding_sync.rs
This patch implements a new method: `RoomListService::sync_indicator`.
It returns a `impl Stream<Item = SyncIndicator>` where `SyncIndicator`
is a new enum with 2 variants: `Show` and `Hide`.
`SyncIndicator` is the UI equivalent of a sync spinner/loader/toaster,
that the app might want to show to the user to indicate when a _first_
request is sent and might be slow, i.e. the first response is taking
a little bit of time to come. The term _first_ may be innapropriate as
it covers the actual first sync request, but also the recovering sync
request. It means that when a sync error happened, the sync indicator
will be shown too, which is a pretty useful information for the user.
It's not because a `SyncIndicator` should be shown that it must be send
immediately onto the `Stream`. In case of a …
=> feat(ui): Implement `RoomListService::sync_indicator`

Cargo.lock, Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk/src/encryption/identities/devices.rs, crates/matrix-sdk/src/encryption/identities/mod.rs, crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/encryption/mod.rs
This PR adds a way for users to listen for devices and user identities that were added or updated in our store.
This becomes useful if and when users try to implement a page which displays a list of devices a user has, or if they want to warn about newly added devices.
=> Add support to broadcast devices and user identities

crates/matrix-sdk-ui/tests/integration/room_list_service.rs
It does exactly what it says on the tin.
=> test(ui): Adjust `request_margin` to avoid a flaky test

.config/nextest.toml
This patch changes the backoff strategy from `fixed` to `exponential` when a flaky test is retried. The `count` value is also updated to 3. Finally, we try to avoid the thundering herd problems with `jitter = true`.
=> test(ci): Exponential backoff when retrying flaky tests

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/authentication.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs, examples/oidc_cli/src/main.rs
This fixes two things:
- for one, the authentication information was *duplicated* but not shared across a parent `Client` and its children. It means that any attempt to refresh an access token could happen in both the parent in the child, independently, leading in at least one of those failing. With OIDC the problem is much more frequent, since refreshes happen every 5 minutes at the moment.
- once we've fixed the above and shared that state, then when creating a child `Client`, we don't need to restore the full session, as it could overwrite the current session tokens (leading to some gnarly race conditions, observed during the implementation of #2440). Instead, we need to restore only the session metadata (user id and device id), which also recreates a fresh `OlmMachine`.
Includes also …
=> feat: Share the authentication data between a parent `Client` and all its children

Cargo.lock, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-common/src/store_locks.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/error.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-ui/src/encryption_sync_service.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs
And also add `CryptoStore::remove_custom_value`, as it's going to be used in the OIDC PR later (to remove stored data upon user logout).
Part of https://github.com/matrix-org/matrix-rust-sdk/pull/2440.
=> feat: generalize cross-process store locks

Cargo.lock, Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
This replaces our use of `batch_with` from `async-rx`, which was batching things reasonably most of the time, but not all of the time due to timing issues. There was a misunderstanding in why we needed to batch things in the first place (it was not just performance, but also correctness).
=> Use ObservableVectorTransaction from eyeball-im 0.3

bindings/matrix-sdk-ffi/src/authentication_service.rs
Part of https://github.com/vector-im/element-x-ios/issues/1653 and https://github.com/vector-im/element-x-android/issues/1250 this PR adds the contacts field which is optional for OIDC but will become mandatory for MAS deployments.
=> chore(bindings): Add missing contacts field on OidcConfiguration.

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/authentication_service.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/authentication/mod.rs, crates/matrix-sdk-ui/src/authentication/oidc.rs, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk/src/oidc/mod.rs
Currently when the AuthenticationService is given updated metadata, it is ignored if a dynamic registration has already been made for a selected issuer. This PR fixes that by storing the metadata's hash and resetting the store when there is a mis-match.
Additionally it moves `OidcRegistrations` out of the FFI into a new `authentication` module in the UI crate and adds some tests.
=> chore(bindings): Handle OIDC metadata changes.

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/store/mod.rs
An alternative to `user_identity_stream`, which does not hold a reference to the `CryptoStore` and hence is less prone to leaking references
=> Implement `Store::identity_stream_raw`

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/verification.rs, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/backups/keys/compat.rs, crates/matrix-sdk-crypto/src/backups/keys/decryption.rs, crates/matrix-sdk-crypto/src/file_encryption/attachments.rs, crates/matrix-sdk-crypto/src/file_encryption/key_export.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/utilities.rs
We have those same base64 decoding/encoding methods defined in multiple places and it's annoying to keep them in sync. Let's define them once and reuse them instead.
Closes: https://github.com/matrix-org/matrix-rust-sdk/issues/2531.
@BillCarsonFr if you have a unit test for the bindings feel free to push a commit or pass the commit to me over Matrix.
=> Reuse base64 encoding/decoding methods from vodozemac

crates/matrix-sdk/src/http_client/mod.rs, crates/matrix-sdk/src/http_client/native.rs
Extracted of https://github.com/matrix-org/matrix-rust-sdk/pull/2440.
Whenever there's an OIDC logout, our OIDC server (MAS) will log some information to Sentry to understand why a token has been rejected, and include some Sentry ID in the response, so we may correlate the Sentry log with our custom logs. This adds logging of that ID, if it's present in the request.
=> feat: log the x-sentry-event-id if we receive it from the server

crates/matrix-sdk/src/sliding_sync/mod.rs
When receiving a sliding sync room response for a room that had no local events in its timeline cache,
we'd mark the room as limited before, which is incorrect. It was made worse by the fact that later in
the code, we'd clear the local cache if a room was marked as limited, so this is a problem that would
repeat itself over time (assuming empty responses for that room).
This fixes it and unifies logs so there's only one log line per room, at most.
There's also a second commit that avoids doing the `limited` flag computation if we're not interested in the rooms part of the response, according to the configuration of that sliding sync.
Related: https://github.com/vector-im/element-x-android/issues/1281 (only fixed once SDK is released and integrated)
Fixes …
=> fix(sliding sync): don't mark a room limited if we don't have cached events for that room

crates/matrix-sdk/Cargo.toml
Some unit tests in the SDK use matrix-sdk-crypto functionality that's only available with `cfg(feature = "testing")`. Enable that feature (in sdk-base and implicitly sdk-crypto, though only sdk-crypto would have been possible too) for test builds of the sdk crate.
This allows `cargo test -p matrix-sdk` to work.
=> sdk: Fix unit tests not compiling without testing feature

crates/matrix-sdk-ui/tests/integration/room_list_service.rs
It's still compiled, but not run unless `--ignored` or `--include-ignored` is passed on the commandline.
=> ui: Ignore flaky test

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/oidc/mod.rs, examples/oidc_cli/src/main.rs
This PR adds the `action` and `device_id` account management URL parameters to OIDC and the FFI as detailed here:
https://github.com/sandhose/matrix-doc/blob/msc/sandhose/oidc-discovery/proposals/2965-oidc-discovery.md#account-management-url-parameters
Unsure if its possible to test these currently, I'm hoping @bnjbvr will add enough mocks to make that possible. For now I have checked they're all working against a server.
Part of https://github.com/vector-im/element-internal/issues/487
=> feat(sdk): Add an action parameter to the OIDC account URL.

bindings/matrix-sdk-ffi/src/event.rs, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
- Add reply info to the FFI API (only the event ID for now)
- Sanitize and strip reply fallbacks
Closes https://github.com/vector-im/element-x-ios/issues/1620.
=> Notification improvements

bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/notification_mode.rs
With this PR, the notification mode in `RoomInfo` now reflects the user-defined mode.
=> ffi: RoomInfo notification mode must reflect the user-defined mode

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/client.rs
When we modify the user's profile we can change the display name and the avatar, but there was no way to remove the current avatar without actually replacing it. These changes were needed:
- Added a `Client.remove_avatar` function to the FFI layer that calls `Client.account().set_avatar_url(None)`.
- Enabled [`compat-unset-avatar`](https://docs.ruma.io/ruma/api/client/profile/set_avatar_url/v3/struct.Request.html#structfield.avatar_url) feature to serialize this `None` to an empty string, otherwise we received an error saying the `avatar_url` parameter is missing from the request.
Signed-off-by:
=> ffi: Add `Client.remove_avatar` function

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/authentication.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/cross_process.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/tests/integration/refresh_token.rs
This should make it possible to use either the session change subscriber *or* the new synchronous callbacks for session changes, in both authentication schemes (Matrix Auth and OIDC). Also gets rid of the dependency to `anyhow` in OIDC, by using a wrapped dyn error type, as @jplatte suggested in the live review of the large OIDC PR.
=> feat(auth): make the session callbacks work for the matrix auth scheme too

crates/matrix-sdk/src/sliding_sync/mod.rs
Does what it says on the tin. We should not have removed this from the logs, as it helps identifying rooms in rageshakes related to `limited` computation errors.
=> chore(sliding sync): log the room id in the `limited` flag computation

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
For some room lists, the number of entries can be gigantic. For example,
some accounts have 800, 2500, or even 4000 rooms! It's not necessary for
the client/app to display all the 4000 rooms. First, it can create some
performance issues, second, nobody will scroll 4000 rooms to search for
a particular room :-). Such users are more likely to use a search bar or
something equivalent. The idea is that `RoomListService` will continue
to sync all the data, but only a _limited_ view of it will be shared
to the client/app.
This patch takes `RoomList::entries_with_dynamic_filter`, and improves
it to include this (dynamic) limit.
This patch renames `RoomList::entries_with_dynamic_filter`
to `::entries_with_dynamic_adapters`. It now returns a
`RoomListDynamicEntriesController`, which is a renaming …
=> feat(ui): Use a dynamic limit over the `RoomList` entries

bindings/matrix-sdk-ffi/src/chunk_iterator.rs, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/mod.rs
This PR contains several patches. It can be reviewed commit-by-commit.
The first set of patches makes `fetch_members`, `members` and `member` async. Why? Because some callers of the bindings would like to “cancel” `Room::fetch_members` or `Room::members` for example, which is easier to do when the methods are purely async.
THe second set of patches makes `members` to return a `RoomMembersIterator`, which “implements” `ChunkIterator`, a new type.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/1979
=> feat(ffi): Improve performances of `Room::members`

crates/matrix-sdk-ui/src/room_list_service/mod.rs
`RoomListService::new_internal` were creating the `invites` sliding sync list, with a cache. It is not a good idea. It should not be cached. Let's remove that :-).
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/2548.
=> fix(ui): The `invites` sliding sync is no longer cached

crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
In `RoomList::entries_with_dynamic_adapters`, we were using the `Limit::dynamic` constructor. It builds a `Limit` stream adapter where the limits come from a `Stream`. The immediate impact is that this constructor does only return a new `Stream`, but it cannot return the initial items of the vector. Thus, it wasn't possible to reset the final `Stream` with a `VectorDiff::Reset { values }`. Instead, we were emitting a `Clear` (from this code) then a `Append` (from the `Limit` stream). Sadly, for some client apps, like Element X iOS, these 2 diffs (`Clear` and `Append`) result in a “rendering blink”.
Hopefully for us, now there is new constructors for `Limit`! One of them is `Limit::dynamic_with_initial_limit`, which returns the initial items along with the new `Stream`. That's perfect, we …
=> feat(ui): Use an initial limit in room list dynamic entries

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/src/timeline/tests/polls.rs
From the changes in: https://github.com/ruma/ruma/pull/1638
Will allow polls edited from legacy Elements to be read rust-sdk based clients.
=> Polls: use new event replacement types

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
Prior to this patch, we were using 2 constants to define the sync indicator delays: `SYNC_INDICATOR_DELAY_BEFORE_SHOWING` and `SYNC_INDICATOR_DELAY_BEFORE_HIDING`. After some discussions with some users, it appears that it's desirable to make these values parameterizable.
Thus, this patch updates `RoomListService::sync_indicator` to accept 2 parameters: `delay_before_showing` and `delay_before_hiding`. The patch also updates the FFI bindings.
=> feat(ui): `RoomListService::sync_indicator` takes delays as parameters

crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/http_client/mod.rs, crates/matrix-sdk/tests/integration/client.rs
=> Add method to fetch account data and fetch the m.direct account data from the server when marking rooms as DMs

crates/matrix-sdk-sqlite/src/state_store.rs
This patch updates `chunk_large_query_over`. This function works great when it's required to chunk some data over a query. However, if the data don't need to be chunked, it is possible to get a quicker path that doesn't involve 2 `Vec` allocations, nor a `split_off` of one `Vec`, nor a `Vec::extend` (which move data in memory). The quicker path, which is also the most likely to be hit, simply does a single `Vec` allocation, and that's it.
=> feat(sqlite) `chunk_large_query_over` doesn't chunk if not necessary

Cargo.lock, Cargo.toml
Pulls in an important bug fix for the Limit adapter: https://github.com/jplatte/eyeball/pull/40
=> Upgrade eyeball, eyeball-im-util

examples/autojoin/src/main.rs
Stripped state events are only received for rooms in invite state.
=> examples: Remove nonsensical room state check

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/timeline.rs
This PR adds support for voice messages sent as `m.room.message`  (as implemented by Element Web)
=> feat(ffi): Add support for voice messages sent as `m.room.message`

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs, crates/matrix-sdk-ui/src/room_list_service/filters/none.rs, crates/matrix-sdk-ui/src/room_list_service/filters/normalized_match_room_name.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
A room list can be filtered by using filters. So far, we have:
* `all` that accepts `Filled` and `Invalidated` room list entries, and rejects `Empty` entries,
* `fuzzy_match_room_name` that runs a fuzzy matcher on the room name,
* `normalized_match_room_name` that runs a normalized matcher on the room name.
When the pattern is empty, both the last filters _accept_ the room list entry. That's a long-term well-known philosophical debate. I'm glad that the behavior is the same for both of the filters.
But that's a technical problem for us. There is no way to _empty_ the room list based on a filter. It becomes a technical challenge for the client app implementors:
* When a user searches for a pattern, before any input is received, the room list must be hidden,
* When a user starts providing a …
=> feat(ui): Add the `none` filter

crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
This patch removes `SlidingSyncList::room_list_filtered_stream. Of course, the only place where it was used,
`RoomList::entries_with_dynamic_adapters` now use `.filter` from `VectorSubscriberExt`. It's basically less code.
=> feat(sdk): Remove `SlidingSyncList::room_list_filtered_stream`

Cargo.toml, crates/matrix-sdk-base/Cargo.toml
Without this feature:
```sh
$ cargo check -p matrix-sdk --features experimental-sliding-sync
Checking matrix-sdk-base v0.6.1 (/Users/hwhost/Development/Element/matrix-rust-sdk/crates/matrix-sdk-base)
error[E0433]: failed to resolve: could not find `poll` in `events`
--> crates/matrix-sdk-base/src/latest_event.rs:7:5
|
7 |     poll::unstable_start::SyncUnstablePollStartEvent, room::message::SyncRoomMessageEvent,
|     ^^^^ could not find `poll` in `events`
error[E0599]: no variant or associated item named `UnstablePollStart` found for enum `AnySyncMessageLikeEvent` in the current scope
--> crates/matrix-sdk-base/src/latest_event.rs:40:68
|
40 |         AnySyncTimelineEvent::MessageLike(AnySyncMessageLikeEvent::UnstablePollStart(poll)) => {
| …
```
=> fix(cargo): Enable `unstable-msc3381` on `ruma`

bindings/matrix-sdk-ffi/src/timeline.rs
Adds a dummy field to `UnstableVoiceContent` otherwise uniffi will generate an empty Kotlin data class which breaks compilation (Kotlin data classes must have at least 1 prop). Upstream bug: https://github.com/mozilla/uniffi-rs/issues/1760
=> Workaround uniffi kotlin bug with empty structs

crates/matrix-sdk-base/src/rooms/normal.rs
Ruma used to handle this during deserialization when the field was an `Option` (prior to #2588).
Especially meaningful when computing the room name, where an empty string should mean that the name is not set.
=> base: Ensure room name is not empty

crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/reactions.rs
Move some things out of `timeline/event_item/content.rs` which was getting too big (still is pretty big) and add a test for membership change redaction because it's non-trivial.
=> Timeline test and module structure improvements

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, testing/matrix-sdk-integration-testing/src/tests/reactions.rs
There is no reason for it to be configurable in the high-level API, since the timeline manages local echoes automatically.
Supersedes #2610.
=> ui: Remove transaction ID parameter on Timeline methods

crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/types/cross_signing/common.rs, crates/matrix-sdk-crypto/src/types/mod.rs, crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk/src/encryption/verification/mod.rs, testing/sliding-sync-integration-test/src/notification_client.rs
Recently noticed a place where we could still benefit from `as_variant` and decided to go on another search for explicit construction of `None` that could be replaced by helpers like it (and `bool::then`).
=> Simplify construction of `Option`s

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/deduplicating_handler.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
This introduces a reusable way to run at most one request, given a key identifying what's the request for. It's used in place of our manual (and unfortunately buggy, as [this issue showed](https://github.com/vector-im/element-x-ios-rageshakes/issues/934)) implementation of similar de-duplication in the code base. This one is heavily commented and scrutinized, and it could be also tested in isolation. This will cause a few extra allocations, but nothing that should kill performance overall, since these requests are relatively infrequent.
This PR can be reviewed commit by commit; you can observe how I got to the final form :grin: 
Fixes https://github.com/vector-im/element-x-ios-rageshakes/issues/934.
=> `DeduplicatedRequestHandler` :sparkles: 

crates/matrix-sdk/src/widget/client.rs, crates/matrix-sdk/src/widget/mod.rs
@jplatte, this is an attempt to create a clean skeleton for the sans-io API for the widget API (based on our discussions on Friday). I went top-to-bottom (in terms of the APIs / implementation). I thought that the PR (instead of doing a change in the `widget-api-2` directly given that it's easier to follow) would be better due to a cleaner diff on top of a `main` branch, so by doing that we can iterate with smaller PRs that introduce fewer concepts at once and discuss/merge faster. This may be easier than doing all changes at once (I doubt we would create one huge PR at the end with the whole implementation 🙂, I feel like it would look similar to the rest of the things that we wrote in the `widget` module, i.e. smaller PRs that introduce concepts gradually).
This change would allow us to …
=> sdk(widget): add sans-io client api impl skeleton

Cargo.lock, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/js_tracing.rs, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-common/src/wasm_tracing.rs
Implement a `tracing_subsciber` `Layer` which sends output to the javascript console.
Obviously, this only works on the wasm32 target.
This is lifted from `matrix-rust-sdk-crypto-wasm`, so that we can use it in tests etc for other crates.
PR to follow to remove it from `matrix-rust-sdk-crypto-wasm`
=> `matrix-sdk-common`: add js console tracing layer

Cargo.lock, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-indexeddb/src/safe_encode.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs
Instead of using three separate object stores, use a single one with some  structured objects and indexes.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2605 (or at least, should make whatever is going wrong much more obvious).
Consists of a series of commits which should be reviewable on their own.
=> Change the way we store gossip requests in indexeddb

bindings/matrix-sdk-ffi/src/widget.rs
I'm not sure if this fixes any actual problems, but it can't really be worse than the previous solution either.
=> ffi: Use FFI's tokio runtime explicitly for acquire_permissions

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/mod.rs
Improvement on the signaling of identity changes.
Currently after a keys/query we signal changes (identity stream) even if the user identity is unchanged. This can create some side effects on some clients, see https://github.com/vector-im/element-web/issues/26194.
The API for idenity change is modified from (`new`, `changed`) to (`new`, `change`, `unchanged`).
In order to do so, I implemented PartialEq for UserIdentities; This implem will check for changes on signatures on the msk.
Signed-off-by:
=> Do not signal identity update if no change

crates/matrix-sdk-indexeddb/src/crypto_store.rs
For reasons I don't understand, these tests seem to work for me after my recent round of fixes, so let's re-enable them.
~~Based on https://github.com/matrix-org/matrix-rust-sdk/pull/2626.~~ Fixes matrix-org/matrix-rust-sdk#661
=> Enable the tests for encrypted indexeddb stores

Cargo.lock, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/widget/client.rs, crates/matrix-sdk/src/widget/matrix.rs, crates/matrix-sdk/src/widget/mod.rs, crates/matrix-sdk/src/widget/permissions.rs
Another small PR following the previous one rel. to the sans-io implementation 🙂 This one adds the I/O part to the widget API. Now, when the state machine is structurally decoupled from the i/o, the Matrix part looks tiny and elegant (as it should be).
=> sdk(widget): add matrix i/o part

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/src/store/mod.rs
This sets up the code so we have a dummy `StoreCache`, and I've moved what was previously cached in the `StoreInner` within that. It gives a pretty good idea of what the changes will look like:
- add field to the cache struct
- retrieve the cache using a new `async` fallible `cache()` function in the store (might be exposed to the whole crate later)
Considering the APIs that are making use of the cache, they can either 1. try to acquire the cache on their own, or 2. expect a cache to be provided as a function parameter. This PR shows both cases. It won't always be as simple to port things to the cache in the first place, because we might take some functions that are sync and make them `async`, or take infallible functions and make them fallible now.
Part of #2624.
=> Add a dummy crypto store cache

crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/utils.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/lib.rs
Due to a change in Ruma merged in #2588, the `name` field of `RoomNameEventContent` is now required. However, before, if the string was empty, Ruma would deserialize it to `None`, then re-serialize it to `null`. This fixes that.
In the process I removed the serde tweaks on `RoomInfo` to apply them during the migration.
Based on #2563 to also support the case where a client has already encountered a room using version 11.
Tested locally on Fractal.
=> base & stores: Migrate `RoomInfo` to new format

crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/helpers.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
This introduces a new data structure, `StaticAccountData` (we could just call it `StaticAccount`) that contains all the immutable fields from the `ReadOnlyAccount`. The `ReadOnlyAccount` is "cached" in one place, the `Store`; after #2625 lands, we can put the `ReadOnlyAccount` in the actual cache.
Then, all the structs storing `ReadOnlyAccount` are changed according to the following rules:
- if all uses were only of static data, store a `StaticAccountData`
- if there are uses of the actual inner-mutable `ReadOnlyAccount` fields, refer to the `Store`'s `ReadOnlyAccount`
The first step was supposed to be carried in small, incremental commits, but I've pulled a thread at some point, and it unraveled lots of uses that could be simplified at once.
This can be reviewed commit by commit. I've …
=> Introduce `StaticAccountData` for `ReadOnlyAccount` immutable fields

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/src/machine.rs
Adds a new crypto API to request missing secrets + the ffi bindings.
This API will look at the missing private secrets (usk, ssk, msk, megolm.backup), and if they are not present on the current session it will make requests for them.
The request are properly saved in "outgoing_request store" to ensure proper handling, it's also checking if there are no existing requests in fligh.
Signed-off-by:
=> Add new API to request missing secrets

crates/matrix-sdk-ui/src/notification_client.rs
This fixes two bugs identified by looking at logs from @bmarty (thanks!):
- first, the encryption sync could run without any locking, making it possible to accidentally possible to run multiple of them at the same time (I think only on iOS). This fixes that by introducing a mutex in the notification client, to guard against multiple calls to `retry_decryption`.
- second, decryption failing would unwind the whole Rust call stack, instead of repeating attempt to decrypt a bit later. This would result in notifications processing resulting in errors, instead of default notifications (because they're encrypted and we couldn't decrypt them).
Also improving logs to help with future debugging of notifications issues.
=> Few improvements for encrypted notifications

crates/matrix-sdk-ui/Cargo.toml
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2647.
=> chore(ui): Add `homepage` and `license` to `Cargo.toml`

bindings/matrix-sdk-ffi/src/timeline.rs
adds an emote param to `message_event_content_from_markdown` and `message_event_content_from_html` on the timeline API, so that clients can create `m.room.message` events with `msgtype` `m.emote`.
I've done it this way on the assumption that the `msgtype` returned in the `RoomMessageEventContentWithoutRelation` is immutable, and so can't be overridden by the client - thus needing this new param to specify it at creation time.
I've probably done this all wrong :D
=> support creating emotes

crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
See individual commit messages. This implements a few enhancements we've talked about with @poljar, notably one possible source of race conditions when writing changes to the crypto stores.
=> Make the crypto stores more robust when writing

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/matrix_auth/login_builder.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs, examples/oidc_cli/src/main.rs
The mutex used for the `homeserver` field is very short-lived, so use a std mutex instead, which makes a few methods sync instead of async.
=> chore: make `Client::homeserver` not async by changing the underlying mutex kind

bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/notification_settings.rs
This PR refines the ffi `NotificationSettingsError` to make it more client friendly.
=> ffi: refine NotificationSettingsError type

bindings/matrix-sdk-ffi/src/room.rs
While looking at rageshakes recently, I noticed that we would send lots of read receipts for the same event. That's because the FFI method invokes `Room::send_single_receipt`, which unconditionally sends a receipt; there's an equivalent method on the `Timeline` struct that sends it only if needed, so let's use that in the FFI layer.
=> ffi: use the `Timeline::send_single_receipt` method instead of that of `Room`

crates/matrix-sdk/src/media.rs
This PR fixes a problem where the disk size of the media file is 0 just after calling `get_media_file`.
=> Fix: wait for disk operations to finish before returning the media file in `get_media_file`.

Cargo.lock, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/gossiping/mod.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/machine.rs
There are a lot of small changes to how long the maps are locked, but I was conservative with changes, plus in some places where it seemed reasonable / useful to extend lock durations, it wasn't easily possible because there was a `.await` in the middle, so an async-aware lock would have been required.
Closes https://github.com/vector-im/element-web/issues/26301.
=> Remove dashmap crate usage from matrix-sdk-crypto

bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
This started as "oh it looks like I can avoid using `Account` here and there" until there was only a single meaningful use in `OlmMachine`. But what is an `Account`, other than a `ReadOnlyAccount` with extra capabilities and access to a store? By passing the store as a parameter to most `Account` methods, those methods could be moved to the `ReadOnlyAccount`, resulting in their merging \o/
Then I could rename `ReadOnlyAccount` to `Account`. The universe is a bit more in order.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/2624.
=> crypto: Fuse `ReadOnlyAccount` and `Account` :sparkles: 

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This patch wants to address https://github.com/matrix-org/matrix-rust-sdk/issues/2535.
The underlying idea behind this PR is to make `Timeline::latest_event` faster. How? By storing the member profile along with the `SyncTimelineEvent` which represents the latest event.
To achieve that, the `RoomList` configures the `all_rooms` sliding sync list to require `m.room.member: $LAZY`. That way, we hope that we receive the member information related to the events, so that we can create a “tiny” profile that skips any access to the storage.
If such a “tiny” profile cannot be generated, `EventTimelineItem::from_latest_event` will simply fallback to the “slow” path.
This PR must be reviewed commit-by-commit, otherwise it's going to be quite complex as it involves a little bit of refactoring (like …
=> feat: Make `latest_event` faster regarding member profile

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/util.rs
`TimelineInnerState::latest_user_read_receipt()` should be more accurate. This is also a preliminary step to have more accurate tracking of read receipts.
First split of #2646.
=> ui: Keep track of the order of all received events in the Timeline

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
Should avoid the same user appearing on two different events receipts in the timeline
2nd split of #2646.
=> ui: Do not add explicit receipts if implicit receipt is newer

crates/matrix-sdk-crypto/src/identities/manager.rs
This PR fixes a bug where in some cases the private cross-signing keys, while being correctly invalidated, the invalidated variant of them were not persisted to storage.
The first two commits add a regression test for this, the third one is the actual fix, while the last commit ensures that we don't spam the logs with info about our identity being marked as verified if it already was verified.
=> Bugfix for invalidated private cross signing keys not being persisted

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
- `content` is now of type `RoomMessageEventContentWithoutRelation`, the relation was previously always overwritten if set
- `add_mentions` is now inferred from `content.mentions`
Brings the Rust API and FFI API closer together.
=> ui: Update send_reply arguments

Cargo.lock, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/ciphers.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/secret_storage.rs
Initial support for secret storage in the matrix-sdk-crypto crate.
This is the crypto crate part of: https://github.com/matrix-org/matrix-rust-sdk/issues/402
The main crate PR is at https://github.com/matrix-org/matrix-rust-sdk/pull/2621.
=> Secret storage support

crates/matrix-sdk-base/src/latest_event.rs
#2587 introduced a breaking change in the serialized format of `RoomInfo`, changing the `event` field format in particular, without a migration. As a result, this lead to users state stores being invalidated for containing incorrect data, and thus being logged out.
This mitigates the issue by making sure that the LatestEvent type is either deserialized as its newer format (aka `SerializedLatestEvent`) or its older format (aka `SyncTimelineEvent`). This way, we maintain compatibility with the previous format. We always serialize to the new one, so we'd only run this migration once.
=> fix: live-migrate `LatestEvent` data from the former format to the newer

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
Not only the events in the Timeline. This increases the accuracy of read receipts.
The read receipts of discarded events are displayed on timeline event items.
3rd split of #2646.
=> ui: Keep track of read receipts on all events 

Cargo.lock, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/oidc/cross_process.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/src/oidc/tests.rs
This adds simple tests for OIDC, and removes some dead code (see code comments). Can be reviewed commit by commit.
Part of #2602.
=> oidc: add more simple tests

.github/workflows/coverage.yml, crates/matrix-sdk/src/widget/filter.rs, crates/matrix-sdk/src/widget/permissions.rs
I also renamed `requires_client` field to `can_open_in_separate_window` in our internal `Permissions` representation as the `requires_client` semantics sounded quite honestly a bit confusing (how is opening a widget in a separate window related to "requiring a client"?), but if you disagree, I could revert a change. I kept it `requires_client` in the FFI (in case anyone relies on this particular wording on the other side of the FFI).
This is a follow-up of a discussion here: https://github.com/matrix-org/matrix-rust-sdk/pull/2677#discussion_r1352547041
PS: Some unit tests would not harm, currently talking to @toger5 about expected inputs that we actually get when using it with Element Call.
=> widget: add serialize/deserialize for `Permissions`

crates/matrix-sdk-ui/src/timeline/pagination.rs
Otherwise `PaginationOptions` is not `Send`.
Gave a compilation error when trying to update the SDK in Fractal:
```
error[E0277]: `dyn Fn(PaginationOutcome) -> std::ops::ControlFlow<(), u16> + std::marker::Send` cannot be shared between threads safely
::: src/session/model/room/timeline/mod.rs:405:22
|
405 |           let handle = spawn_tokio!(async move {
|  ______________________-
406 | |             matrix_timeline
407 | |                 .paginate_backwards(PaginationOptions::until_num_items(
408 | |                     MAX_BATCH_SIZE,
...   |
411 | |                 .await
412 | |         });
| |__________- in this macro invocation
|
= help: the trait `std::marker::Sync` is not implemented for `dyn Fn(PaginationOutcome) -> std::ops::ControlFlow<(), u16> + std::marker::Send`
= note: …
```
=> ui: Require PaginationOptions strategy to be Sync

crates/matrix-sdk/src/notification_settings/mod.rs
This PR improve adds a logic that enables an underride push rule when actions are updated. This fixes inconsistency problems like [this](https://github.com/vector-im/element-x-ios/issues/1836) on the client.
=> feat: enable push rules when changing actions

Cargo.lock, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/attachment.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/media.rs
This PR adds a ffi binding for sending voice messages in the legacy format (before extensible events). It also makes minor changes in the `matrix-sdk` crate to accomodate this change.
=> feature: send voice message API

bindings/matrix-sdk-ffi/src/event.rs, bindings/matrix-sdk-ffi/src/timeline.rs
… allows the FFI type MessageLikeEventContent to hold custom msgtypes, which is useful for notification.
Also allows sending custom msgtypes, as long as no fields other than the msgtype itself and body are needed.
Fixes #2703.
=> ffi: Allow MessageType to contain arbitrary msgtype values, plus body

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/oidc/cross_process.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/tests/integration/refresh_token.rs
See commit messages.
A note: the first time it will run on an iOS device, since the hash algorithm has changed, and we store the tokens hash in the crypto database, this will result in a false-positive "some other process changed the tokens under my feet", but that's no biggie: in `Oidc::restore_session`, the app will retrieve the latest session tokens from the keychain and update them everywhere (in the app's memory and store), so that's all good.
=> oidc: tweak logging of tokens hashes

.github/workflows/documentation.yml
It contains a required job that only runs on non-draft PRs, but restarts don't trigger it.
=> ci: Run documentation CI workflow when un-drafting a PR

Cargo.lock, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/js_tracing.rs
Replace the old `tracing_subscriber::layer::Layer` (which I don't think anyone had gotten around to using) with a `MakeWriter` which can then be plugged into a `fmt::Subscriber`.
=> matrix-sdk-common: a tracing `MakeWriter` writing to a JS Logger

crates/matrix-sdk/src/widget/client/actions.rs, crates/matrix-sdk/src/widget/client/outgoing.rs, crates/matrix-sdk/src/widget/matrix.rs, crates/matrix-sdk/src/widget/mod.rs, crates/matrix-sdk/src/widget/settings/element_call.rs, crates/matrix-sdk/src/widget/settings/mod.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/widget.rs
For state events, widgets should only ever receive the latest state of any `event_type` / `state_key` combination. The previous implementation could return outdated ones as well.
This is a rewrite of <del>some of the changes from</del> #2717, should be a bit cleaner both in terms of code as well as commits.
=> widget: Separate reading of message and state events

crates/matrix-sdk-crypto/src/identities/manager.rs
These functions are a bit confusing, so I wrote some comments. I also factored out `get_user_signing_key_from_response`, to reduce duplication and (IMHO) improve clarity.
=> Documentation on `/keys/query` parsing functions

crates/matrix-sdk/src/widget/machine/from_widget.rs, crates/matrix-sdk/src/widget/machine/incoming.rs, crates/matrix-sdk/src/widget/machine/mod.rs, crates/matrix-sdk/src/widget/machine/to_widget.rs
Per-commit review is recommended as I moved some parts around for [arguable] readability (that produces a bigger diff than this PR probably requires 😃).
=> widget chores: move the common parsing part out of the to-widget specific structures

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Can be used to add mentions to the content of a message.
=> ffi: with_mentions method

bindings/matrix-sdk-ffi/src/notification_settings.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/session_verification.rs, bindings/matrix-sdk-ffi/src/sync_service.rs
Except for full_room_blocking, which is apparently noticably faster. They were only added as a workaround for a UniFFI bug that has now been fixed.
=> ffi: Remove _blocking functions

crates/matrix-sdk/src/widget/filter.rs, crates/matrix-sdk/src/widget/machine/driver_req.rs, crates/matrix-sdk/src/widget/machine/from_widget.rs, crates/matrix-sdk/src/widget/machine/mod.rs, crates/matrix-sdk/src/widget/machine/tests/capabilities.rs, crates/matrix-sdk/src/widget/machine/tests/error.rs, crates/matrix-sdk/src/widget/mod.rs, crates/matrix-sdk/tests/integration/widget.rs
Subset of #2743. Still needs tests, but it should not allow widgets to read more than what is negotiated through capabilities.
=> widget: Add support for read-state-event fromWidget requests

crates/matrix-sdk/src/widget/machine/driver_req.rs, crates/matrix-sdk/src/widget/machine/mod.rs, crates/matrix-sdk/src/widget/machine/tests/capabilities.rs, crates/matrix-sdk/src/widget/machine/to_widget.rs, crates/matrix-sdk/src/widget/matrix.rs
- ~~OpenID request handling + tests.~~ 
- ~~Error handling when an outgoing matrix request fails.~~
edit(jplatte): First parts merged in #2752.
- Basic `Subscribe` / `Unsubscribe` when the capabilities are negotiated.
=> widget: Subscribe and unsubscribe to matrix events

bindings/matrix-sdk-ffi/src/widget.rs, crates/matrix-sdk/src/widget/capabilities.rs, crates/matrix-sdk/src/widget/machine/incoming.rs, crates/matrix-sdk/src/widget/machine/mod.rs, crates/matrix-sdk/src/widget/machine/to_widget.rs, crates/matrix-sdk/tests/integration/widget.rs
… a few uppercase Permissions were missed last time.
=> widget: Rename remaining "permissions" to capabilities

bindings/matrix-sdk-crypto-ffi/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
The `Account` is lazily loaded in the cache, and transferred from the cache to `PendingChanges` in case of `StoreTransaction`. Later, `Account` is made not cloneable anymore, and inner mutable shared state is removed from there, so we can identify which interactions with the cache must be transactions (i.e. which Account function calls require write access), and which can just be reads from the cache (i.e. which Account function calls requires read-only access). Eventually, the cache is put behind a RwLock, so we can't read and write to the cache at the same time; this lock is taken in write access during transactions, and in read-only access during cache reads.
This can be reviewed commit by commit. 
Multiple parts of https://github.com/matrix-org/matrix-rust-sdk/issues/2624.
=> crypto: Remove inner mutable shared state from `Account`

crates/matrix-sdk-crypto/src/secret_storage.rs
These two commits are part of #2621, I'm pulling them out to get at least some parts of that PR merged.
=> Misc secret storage fixes

Cargo.toml
We thought we fixed all the dbg crashers but they're back now. While the reldbg profile helps us build the sdk faster, we cannot use it for debugging which is tremendously useful. 
This change takes the `opt-level = 3` "fix" from `reldbg` and applies it to `dbg` as well which, together with `debug = 2` seems to give us the best of both worlds. 
Not entirely sure what the downsides are, debug symbols seem to work just fine.. (-ish, they weren't great to being with)
L.E. Went with having `reldbg` inherit from `dev` instead
=> Prevent debug builds from crashing on iOS

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
Improves the compatibility with clients using threads. This should give us the same receipts as Element Web.
4th split of #2646.
=> ui: Handle read receipts in the main thread

crates/matrix-sdk-ui/src/timeline/read_receipts.rs
Tiny change spotted while reviewing #2701.
=> read receipts: avoid allocating an indexmap that's immediately consumed

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/matrix_auth/login_builder.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs, crates/matrix-sdk/tests/integration/refresh_token.rs
This adds support for automatically enabling the cross-signing bootstrapping, if the user so desires. This enables it for OIDC too, where [MSC3967](https://github.com/matrix-org/matrix-spec-proposals/pull/3967) ensures we don't need any UIAI for that.
Extracted from #2666.
=> feat: enable automatic cross-signing boostrapping

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/olm/account.rs
Debug output for the `Store` is extremely verbose, so we don't want to log it every time we touch this function.
=> Exclude `Store` from tracing

bindings/matrix-sdk-ffi/src/session_verification.rs
Fixes vector-im/element-x-ios/issues/1868 Incorrect `is_verified` flag after successfully running verification flow
- the inner user_identity isn't automatically updated when the flow finishes, needs to be fetched again from encryption
- also replaces `UserIdentity.is_verified` with `Device.is_cross_signed_by_owner`
=> Session verification fixes

bindings/matrix-sdk-crypto-ffi/src/responses.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/tests/integration/client.rs, crates/matrix-sdk/tests/integration/encryption/verification.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs
During bootstrapping of cross-signing, we first upload the cross-signing keys, then upload signatures for keys in general. The set of signatures may include a signature for a device key we haven't uploaded yet, in particular if we're creating the account and set it up for bootstrapping. This fixes it by having `bootstrap_cross_signing` return a key upload request, that must be executed after the cross-signing keys upload and the keys signatures upload (this is properly documented, fwiw).
This also updates the verification test that made us aware of this issue.
=> fix(crypto): Upload keys before signing

Cargo.lock, crates/matrix-sdk-common/src/tracing_timer.rs
Should fix the build with a more recent `tracing` version. Maybe we shouldn't rely on internal `tracing` APIs :eyes:
=> Bump tracing and update API usage

crates/matrix-sdk/src/widget/capabilities.rs, crates/matrix-sdk/src/widget/filter.rs, crates/matrix-sdk/src/widget/machine/mod.rs, crates/matrix-sdk/src/widget/machine/tests/capabilities.rs, crates/matrix-sdk/src/widget/machine/tests/error.rs, crates/matrix-sdk/tests/integration/widget.rs
**Summary:**
- Tests for fromWidget read and send event requests that are not allowed (I.e. negotiated, but negotiated capabilities did not allow the types of events that the widget requests).
- Implementation for reading message-like events, the integration test for that has already been written by @jplatte, I just 'activated' it and fixed one minor error there (the test expected 2 events to be returned by the machine, whereas actually 1 matches the filter).
NB: Now, after this implementation, the function that processes the read event contains some of the boilerplate. I have not refactored it yet (given that the rest of the tasks from https://github.com/matrix-org/matrix-rust-sdk/issues/2753 may touch it.
=> widget: Add missing stuff for read/send requests

crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Theoretically, it's possible to misuse the API of `StoreCache::account`:
- one can create a transaction with `Store::transaction()`
- then call `StoreTransaction::account()` on it, which returns a `&mut Account` (after stealing the `Account` from the `StoreCache`) 
- then call the `StoreTransaction::cache() -> StoreCache` method on it
- then call `StoreCache::account()`, which will reload the `Account` in the `StoreCache`
At this point, we have two live copies of the `Account`, which can be different if some changes have been done on the `&mut Account`.
This is bad, because that's duplicated state that can be inconsistent.
We still want to have access to a read-only `Account` when holding a `StoreCacheGuard` (obtained from `Store::cache()`), though.
Fortunately, it's relatively easy to …
=> crypto: Strengthen the API of `StoreCache::account`

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
The other methods give the event ID that the read receipt applies to, but it might not be an event that appears in the `Timeline`. This one always gives us the event ID where the read receipt would appear.
We use it in Fractal to know if there are unread messages after our own user's receipt, by checking if there are other messages after the receipt. It avoids to keep track of all events in our client too.
The first commit is a small bugfix.
=> ui: Add method to know the position in the timeline of a user read receipt

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/mod.rs
This removes some logic from the `Store` and `StoreCache`, and put it into a new structure called `KeyQueryManager` which is tightly coupled to the `StoreCache` itself. With this change, the `StoreCache` is now mostly pure data.
Also the public API of the `KeyQueryManager` makes it impossible to interact with pending key queries without syncing first with the database, potentially fixing a few issues introduced in recent refactorings around this.
A note to simplify review: the bodies of methods that were on the `Store` or `StoreCache` have **not** changed, except for data access (some data is now parameters, some data is now owned fields). The logic hasn't changed at all otherwise.
=> crypto(cleanup): introduce a `KeyQueryManager`

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs
This should fix a few logouts happening for users of the `poljar/recovery` branch.
=> recovery branch fix: don't send any request before OIDC is fully set up

bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-ui/src/timeline/futures.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/queue.rs, crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/futures.rs, crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/matrix_auth/login_builder.rs, crates/matrix-sdk/src/media.rs, crates/matrix-sdk/src/room/futures.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/widget/matrix.rs, crates/matrix-sdk/tests/integration/room/joined.rs, examples/command_bot/src/main.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
A bunch of improvements around sending events. I'll follow up with allowing the `_raw` methods to take different content types than `serde_json::Value` tomorrow.
=> Improve send-event API, part 1

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/client/tasks.rs, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs
This doesn't await for the startup tasks to finish, but it's not clear where it should do that.
=> crypto: put the enabling of backup and recovery in the background

Cargo.toml
In https://github.com/matrix-org/matrix-rust-sdk/commit/1f534821f6ec2287ec581435a7e6ae52195a3944, only the lock file was updated.
Cargo in projects that depend on this library will not be aware that tracing should be bumped when this crate is bumped though, causing compiling errors.
=> Bump tracing in cargo manifest

crates/matrix-sdk/CHANGELOG.md
=> sdk: Add changes to send-event API to changelog

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk/Cargo.toml, examples/oidc_cli/Cargo.toml, examples/persist_session/Cargo.toml, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
In the previous situation, running the tests with `cargo test` would sometimes fail because despite appending the number of milliseconds since the start of epoch to the user names, some user names would clash across different tests, leading to unexpected results. This fixes it by using an actual RNG in there, so the names don't ever clash.
With this, `cargo test` now seems to pass all tests with a bigger confidence rate.
=> integration tests: randomize user names better

Cargo.lock, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/mod.rs, examples/oidc_cli/Cargo.toml, examples/oidc_cli/src/main.rs
I decided to take another look at our use of async-std, and AFAICT we are not actually requiring any `Condvar`-specific functionality (I think the only case where it does more than tokio's `Notify` is when a specific piece of code wants to queue up to be "next in line" to operate on the mutex after the wait condition is fulfilled).
We also got a new use in an example, but that was even easier to remove.
Requesting rich's review in addition to one from the team because he added the use of `async-std`s `Condvar`.
=> Replace async-std with equivalent tokio functionality

bindings/matrix-sdk-ffi/src/widget.rs, crates/matrix-sdk/src/widget/mod.rs, crates/matrix-sdk/src/widget/settings/element_call.rs, crates/matrix-sdk/src/widget/settings/mod.rs
For e2ee to be enabled we need to allow the mobile clients to set a url flag. This PR adds the flag and creates the FFI for it.
Signed-off-by:
=> Add `perParticipantE2EE` to element call url.

crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs
Some non-functional refactoring in preparation for fixing https://github.com/matrix-org/matrix-rust-sdk/issues/281. Suggest review commit-by-commit. The salient changes are:
* `Account::create_outbound_session` no longer takes an entire list of keys; rather it takes a single key and it is up to the caller to pick a key out of the list. This in turn means that `SessionCreationError` loses one of its reason codes.
* `SessionManager::create_sessions` is factored out of `receive_keys_claim_response`. This is mostly helpful in tests, where our goal is to establish a session with a given device, rather than actually to test parsing of the entire `/keys/claim` response.
=> Groundwork for fixes to one-time-key fetching

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Fixes #2802, which was a performance regression, not a deadlock.
The lock was only useful to sync the database and the in-memory cache for the users awaiting a key query request, at the beginning of the `wait_if_user_key_query_pending`. So it's possible to slightly tweak the API by moving the method from `SyncedKeyQueryManager` to non-synced `KeyQueryManager`, and require a `StoreCacheGuard`, i.e. the owned lock, so we can manually drop it when we feel like so.
I've looked at all the other methods, and they do require the cache for writing into it and the store. At the limit we could also move `SyncedKeyQueryManager::users_for_key_query` into `KeyQueryManager`, but the lock in there is hold for a very short-time, so it shouldn't be an issue.
=> crypto(perf): don't hold the cache lock while waiting on a user key query

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/oidc/mod.rs
(by a few kilobytes for some functions)
This is not just segmenting the stack but also reducing the overall allocation size in some cases when it's not the code path with the highest stack requirement that is taken.
=> Reduce async fn stack size

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/file_encryption/key_export.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk/src/encryption/mod.rs
This PR adds source specific methods to import room keys instead of using a
boolean. The booelan could be easily forgotten and the structure of the room key
collection differs in a file export compared to when we download them from a
backup.
This makes it much easier to import room keys from a backup.
=> Add a backup specific method to import room keys

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification.rs
A detached task was spawned to react upon session changes, and that task captured a clone of the current `Client`. This caused a leak of the `Client`, because that task would never get aborted, and would not stop by itself. The fix here consists in having `Client::set_delegate` return a task handle that needs to be stashed by the FFI users, and cancelled when the Client gets out of scope. This fixes the leak, by removing the last reference onto the Client.
Then, when dropping the Client, we have to drop the Stores in it. These stores may be sqlite-based stores, which make use of deadpool. Deadpool has a sync wrapper that will call `block_on` in a `drop` method, and as such it requires to be in the scope of a tokio runtime to run properly. To avoid breaking all abstractions and giving …
=> fix(ffi): don't leak Client instances

bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/backups/keys/backup.rs
This type was added some time ago, but we didn't switch the backups support
towards it.
The serialized format remains the same, but we're offering some stronger typing
on the Rust side.
=> Use the better Signatures type in the MegolmV1BackupKey type

bindings/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/utility.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/types/cross_signing/master.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, xtask/src/ci.rs
This PR enables backups in the crypto crate by default and removes the
`backups_v1` feature, for better or worse.
=> Enable backups in the crypto crate by default

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/media.rs
So that client apps can keep their own cache avoiding re-requesting the same media from the SDK multiple times.
=> Expose NamedTempFile.persist() through MediaFileHandle

Cargo.lock, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/secret_storage/futures.rs, crates/matrix-sdk/src/encryption/secret_storage/mod.rs, crates/matrix-sdk/src/encryption/secret_storage/secret_store.rs, crates/matrix-sdk/tests/integration/encryption.rs, crates/matrix-sdk/tests/integration/encryption/secret_storage.rs, examples/secret_storage/Cargo.toml, examples/secret_storage/src/main.rs
This PR utilizes the cryptographic primitives for secret storage support introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/2591, and adds a convenient and easy to use API on top of it. As such, this PR depends on #2591.
We're now able to import the private cross-signing keys and verify our own device by entering the secret storage key or passphrase.
The PR should be reviewed commit by commit. An example, in case somebody wants to play around with this as part of the review, is provided as well.
=> Secret storage support in the main crate

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/backups/mod.rs
=> Add a higher level method to sign backup versions

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/backups/keys/compat.rs, crates/matrix-sdk-crypto/src/backups/keys/decryption.rs
Some more minor helpers and higher level methods for the backup support. A
unused error type was removed as well.
=> Add a higher level decryption method for the backed up room keys

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk/Cargo.toml
This pulls in https://github.com/matrix-org/matrix-authentication-service/pull/2047 and shrinks our dependency tree.
=> Upgrade mas-oidc-client, tracing-opentelemetry

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
Otherwise back-pagination goes in a loop because the token is never updated.
A Fractal user reported that they had the same message about an event failing to deserialize in a loop in the logs, and Fractal was using 30% CPU continuously. In their case, they received an empty chunk (which is valid according to the spec) which was causing the back-pagination to reset in a loop.
Added 2 tests that fail on `main` for the cases where that could happen.
=> ui: Update back-pagination token even if chunk is empty or event fails to deserialize

crates/matrix-sdk/src/oidc/cross_process.rs, crates/matrix-sdk/src/oidc/mod.rs
Changes the logging of the return value of the Sha2 types to use `LowerHex` logging, instead of `Debug`. Turns out that the type returned by the hashing was an array of bytes of some sort.
=> oidc: use hex logging for the hashed oidc tokens

crates/matrix-sdk/Cargo.toml
… so `ClientBuilder::indexeddb_store` is visible on docs.rs.
I think this wasn't initially possible because the `matrix-sdk-indexeddb` crate only compiled on wasm. It has long been compiling on non-wasm though (it will panic if one attempts to use it, but at least most documentation can be generated on non-wasm).
Fixes #1518.
=> sdk: Enable indexeddb in docsrs feature

bindings/matrix-sdk-ffi/src/notification.rs, crates/matrix-sdk-ui/src/notification_client.rs
fixes #2834
I could change the name of the variable to be: `is_highlighted` or `has_highlight` if that sounds more correct from a SDK point of view.
=> feat (bindings): `has_mention` in `NotificationItem`

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/utilities.rs
Keep a record of devices that were included in a `/keys/claim` request, and then, if they are missing in the response, register them as "failed".
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/281.
~~This PR is currently based on https://github.com/matrix-org/matrix-rust-sdk/pull/2803.~~
=> Handle missing devices in `/keys/claim` responses

testing/matrix-sdk-test/src/test_json/members.rs
It doesn't matter at the moment as the only test using `test_json::MEMBERS` does not rely on the event being valid, but it shows this error nonetheless:
```
2023-11-10T08:54:29.920782Z DEBUG receive_members{room_id="!hIMjEx205EXNyjVPCV:localhost"}: matrix_sdk_base::client: Failed to deserialize member event: missing field `room_id` at line 1 column 297 event_id="$151800140517rfvjc:localhost"
```
and https://spec.matrix.org/v1.8/client-server-api/#get_matrixclientv3roomsroomidmembers says it is a required key.
=> Add missing "room_id" to test_json::MEMBERS

bindings/matrix-sdk-ffi/src/notification_settings.rs
Added a function that returns true if the current homeserver has the msc 4028 push rule and is enabled.
Since I don't see Ruma having a specific push rule id for it yet, I am using an hardcoded string for now, is that okay?
=> ffi(bindings): check if MSC 4028 is enabled on the homeserver

Cargo.lock
Includes the following bugfixes:
- Fix the name of the fallback text field for extensible events in `RoomMessageEventContentWithoutRelation::make_reply_to_raw()`
- Allow to deserialize `(New)ConditionalPushRule` with a missing `conditions` field
- Fix deserialization of `claim_keys` responses without a `failures` field
The last fix is especially important, it caused at least one person (probably more) to be unable to send messages in encrypted rooms: https://github.com/vector-im/element-x-android-rageshakes/issues/1058
=> Upgrade ruma crates to pull in bugfixes

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs
Two sets of improvements to `get_missing_sessions` here:
* Currently, for any users who have an empty device list, we call `KeyQueryManager::wait_if_user_key_query_pending`, which waits up to 5 seconds for a `/keys/query` response. (Arguably, we should be waiting longer: it is not unusual for such a request to take a while.)
The problem is that that user's server may have been blacklisted, in which case we won't even be trying to do `/keys/query` resquests for that user, so we'll be waiting for something that never happens.
To fix this, let's check the failures list when deciding if we should wait for a user's devices.
* Separately, but closely related: for each user thus affected, we do the wait *in series*. This is a bit silly: there is no point waiting 50 times. We can parallelise the …
=> Improve performance of `get_missing_sessions`

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
Updates to the timeline happen via updates propagated to room subscribers. It appears that when a sliding sync response was received, ephemeral events in a room update defaulted to an empty set, resulting in read receipts not being handled live. This fixes it by manually copying read receipts received from the sliding sync response into the room update.
Fixes https://github.com/vector-im/element-x-ios/issues/2089.
=> sliding sync: include read receipts into room updates so they're handled live by the timeline

bindings/matrix-sdk-ffi/src/widget.rs, crates/matrix-sdk/src/widget/settings/element_call.rs
This is a deprecated flag for element call using livekit. It was used to enable/disable matrix signalling event encryption. This is not relevant for embedded mode at all since there the hosting client is taking care of encryption.
Signed-off-by:
=> element call: Remove `E2EEenabled` flag

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Encryption doesn't usually require access to the user identity, so we can skip loading that from the store.
Unfortunately that means a fair bit of refectoring, in the form of replacing `Device` with `ReadOnlyDevice`.
This reduces the time taken to encrypt a message in a large room from about 3 seconds to 1 second.
=> Improve performance of `share_room_key`

Cargo.lock, crates/matrix-sdk/src/sliding_sync/room.rs, room.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/mod.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
According to the sliding sync MSC, an `avatar` field in a room response set to `null` means it's been unset, and when it's not set (aka `undefined`), then it's not changed since the previous sync. The meaning of "null" and "undefined" were conflated by Ruma, previously, and both would deserialize to a Rust's `None` — which was ignored by sliding sync, interpreting it as "there's no update to the avatar".
This PR updates to the latest Ruma, which allows us to distinguish both cases, and the logic in sliding sync is tweaked to take that change into account, allowing us to see the effect of unsetting avatars with sliding sync.
=> sliding sync: correctly set/unset a group avatar

crates/matrix-sdk-crypto/src/olm/session.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk-crypto/src/types/events/room_key_withheld.rs
We don't need to distinguish null from an absent field in any of the places we used JsOption, so a regular Option is better.
=> crypto: Use Option instead of JsOption

crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/types/one_time_keys.rs
This is useful if we ever decide to switch to X3DH for the session establishment. It also refactors a bit the /keys/claim response handling method.
=> Prepare our /keys/claim response handling to handle multiple OTKs

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/src/timeline/tests/polls.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
This PR adds the API for editing a poll.
Furthermore refactors `create_poll` to reuse common code.
=> feat: edit poll API 

crates/matrix-sdk-crypto/src/identities/device.rs
Until https://github.com/matrix-org/matrix-rust-sdk/pull/2862, `GroupSessionManager::encrypt_session_for` called `Device::encrypt` (via `Device::maybe_encrypt_room_key`.
`Device::encrypt` is a thin wrapper for `ReadOnlyDevice::encrypt`, but it also has an `instrument` annotation.
https://github.com/matrix-org/matrix-rust-sdk/pull/2862 short-cuts `Device::encrypt` and calls `ReadOnlyDevice::encrypt` directly: that was functionally fine but of course means that we no longer benefit from the `instrument` annotation.
This PR rectifies the situation by pushing the annotation down to `ReadOnlyDevice::encrypt`. It also adds some documentation for that function, since we are using it in more places now.
(Longer-term, I think we should probably aim to get rid of `Device::encrypt` altogether, but …
=> Reinstate tracing instrumentation on `ReadOnlyDevice::encrypt`

benchmarks/benches/crypto_bench.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/responses.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs
Sometimes, we called this `keys query`, sometimes `/keys/query`, and sometimes, just for variety, `keys/query`. Generally in Matrix we talk about `/keys/query` so let's standardise on that.
=> Be consistent about endpoint names

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
This PR fixes the `EventTimelineItem.is_editable()` function for polls.
Before this changes it always returned false.
Now it consider poll's preconditions for editing:
- The poll has no votes yet
- The poll hasn't an end event
=> fix: is_editable() function for polls

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/filters/all_non_left.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs
This allows to get a list of all the rooms except for left ones, since they're still part of a sliding sync server response.
This mitigates https://github.com/vector-im/element-x-ios/issues/2005 until we get feedback about what the best behavior should be with respect to all the cases.
=> room list service: add a new filter to get all rooms but the left ones

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This adds a test documenting the current behavior of the proxy with respect to left rooms.
See also https://github.com/vector-im/element-x-ios/issues/2005
=> test: add an integration test for left rooms

crates/matrix-sdk-common/src/js_tracing.rs, crates/matrix-sdk-common/src/lib.rs
Somehow `fmt::pretty` manages to be both overcomplicated and not flexible enough.
The driver here is that I want to put the event "fields" on a separate line to the message.
=> Implement a custom event formatter for javascript logging

.typos.toml, Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/client/tasks.rs, crates/matrix-sdk/src/encryption/backups/futures.rs, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/backups/types.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/secret_storage/secret_store.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/src/utils.rs, crates/matrix-sdk/tests/integration/encryption.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs, crates/matrix-sdk/tests/integration/encryption/secret_storage.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs, examples/backups/Cargo.toml, examples/backups/src/main.rs, testing/matrix-sdk-integration-testing/src/helpers.rs
This PR adds support to download backups and start backing room keys up when:
1. The user imports secrets from secrets storage
2. The user performs an interactive verification and receives the backup key as a `m.secret.send` event.
Due to no 1, this PR depends on #2621.
The PR has also ballooned up to include a full API to:
1. Create a new backup.
2. Delete and disable an existing backup.
3. Expose the various methods to download room keys from the backup.
4. An example to play with the backup support
5. Comprehensive integration tests
=> Backup support in the main crate

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs
We had a very different API for FFI consumers than for Rust consumers for way too long. Now it required to first explicitly initialize a `Timeline` object before being able to call any methods that would require it.
Based on #2880.
=> Align FFI timeline API more with the Rust API

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/traits.rs
Allows to retrieve the Poll history of a Room.
The poll history is a Timeline instance that filters on poll events.
=> Timeline: add poll history API

bindings/matrix-sdk-ffi/src/client.rs
This allows to overwrite the power levels on room creation. So the app can set the Power level for m.call.member events to 0.
This is an alternative to: https://github.com/ruma/ruma/pull/1706
Signed-off-by:
=> Exposing power level overwrites on room creation to FFI

contrib/ide/vscode/settings.json
Since we need `cargo +nightly fmt` to pass ci `"rust-analyzer.rustfmt.extraArgs": ["+nightly"]` is very helpful.
`"rust-analyzer.checkOnSave.command": "clippy",` is copied from ruma since it also applies to the rust sdk if i am not mistaking.
This adds a file in `contrib/ide` that collects recommanded settings to copy over for vscode users. (The same concept that is used in ruma)
Signed-off-by:
=> Add vscode settings.json recommandation in contrib/ide

Cargo.lock, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
Currently, querying for inbound group sessions which need backing up is very
inefficient: we have to search through the whole list.
Here, we change the way they are stored so that we can maintain an index of the
ones that need a backup.
Fixes: https://github.com/vector-im/element-web/issues/26488
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/2877
=> indexeddb: Update storage for `inbound_group_sessions`

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/encryption.rs, bindings/matrix-sdk-ffi/src/lib.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/recovery/futures.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs, crates/matrix-sdk/src/encryption/recovery/types.rs, crates/matrix-sdk/tests/integration/encryption.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs, crates/matrix-sdk/tests/integration/encryption/recovery.rs, crates/matrix-sdk/tests/integration/encryption/secret_storage.rs
This PR implements a `Recovery` API. This API or subsystem attempts to unify the backup and secret storage support into a single and simplified API.
This `Recovery` API is also what Element X uses for their backup and secret storage support.
=> Recovery support: Or how to tame secret storage and backups

crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk/src/sliding_sync/error.rs
`itertools::format` is known to cause issues when its display implementation is being used multiple times, as it consumes the iterator it was given (and that can only happen once, unless caching it). This is bad, as our production apps may have multiple subscribers they will run into a panic.
The fix is to reify the debug string before it's logged, so the tracing consumer will only see a string, and not the display implementation that would panic on the second use.
=> fix: reify reformat of `missing_session_devices_by_user`

bindings/matrix-sdk-ffi/src/encryption.rs
The title is kind of self-explanatory. It fixes this issue:
```
> Task :sdk:sdk-android:compileDebugKotlin
e: file:///Users/jorge/Developer/Element/matrix-rust-components-kotlin/sdk/sdk-android/src/main/kotlin/org/matrix/rustcomponents/sdk/matrix_sdk_ffi.kt:14690:13 Conflicting declarations: public open val message: String, public final val message: String
e: file:///Users/jorge/Developer/Element/matrix-rust-components-kotlin/sdk/sdk-android/src/main/kotlin/org/matrix/rustcomponents/sdk/matrix_sdk_ffi.kt:14690:13 'message' hides member of supertype 'RecoveryException' and needs 'override' modifier
e: file:///Users/jorge/Developer/Element/matrix-rust-components-kotlin/sdk/sdk-android/src/main/kotlin/org/matrix/rustcomponents/sdk/matrix_sdk_ffi.kt:14692:22 Conflicting declarations: public …
```
=> Rename `message` since it clashes with Kotlin's `message` property in exceptions

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs
For Element Web, we want to be able to turn off outgoing room key requests without affecting whether we reply to incoming requests (https://github.com/vector-im/element-web/issues/26524).
Accordingly, we need a separate method to allow us to do that.
This PR also takes the opportunity to rename `toggle_room_key_forwarding` to `set_room_key_forwarding_enabled`, since it's not really a "toggle".
=> Crypto: add new methods for turning off room key requests

crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/client.rs
For most code paths, we'd use `Room::decrypt_event`, which may try to download a key backup if decryption failed. This code path wasn't taken during back-pagination of older events; this new PR makes use of it in that context. I've also checked other code paths. There's one in the base-client that makes direct use of `OlmMachine::decrypt_room_event`, and there we can't use `Room::decrypt_event` because the latter lives in the SDK crate. In this case it's fine, because that one use is the (core) handler of events received from sync, and we have an higher-level UTD event handler in the main crate that will notice the encrypted event, and try to download a room key.
It's a bit hard to test (must run a back-pagination request that resolves to UTDs), but I could add an integration test if we …
=> room: try restoring from a key backup during backpagination too

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
The read receipts code is relying on the `visible` boolean on an `EventMeta`, that's present for every event (even those that don't materialize into timeline events). This `visible` boolean was set accordingly to whether the event was filtered out or not, using the user-defined `event_filter` that's available on a timeline builder. Unfortunately, this is not the only thing that determines whether an event will be visible or not: according to its kind (message? poll? reaction? etc.), it may or may not be materialized into a `TimelineEventItem`. So we need to take that into account.
The default `event_filter` for a timeline is now defined as the set of events that can be materialized into a `TimelineEventItem`. Other events, that can't be made visible (edits, reactions and so on), are …
=> read receipts: don't put receipts on invisible timeline events

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs
`notifications` were stored in the `StateChanges` struct, which made me think that they're then persisted in the database. It's not the case, they were just stored there by convenience. This commit changes it to a parameter that's passed, as it's not too invasive and clearer that this is only transient data.
=> refactoring: make it clear that notifications aren't persisted in storage

crates/matrix-sdk/Cargo.toml
Otherwise `cargo test -p matrix-sdk` will fail with errors like:
```
error[E0599]: no method named `olm_machine_for_testing` found for struct `matrix_sdk::Client` in the current scope
--> crates/matrix-sdk/tests/integration/encryption/verification.rs:474:31
|
474 |         let alice_olm = alice.olm_machine_for_testing().await;
|                               ^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Client`
```
=> sdk: Make sure "testing" feature is enabled for integration tests

crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/tests/integration/refresh_token.rs
Otherwise the future will not run.
Changes the corresponding test to fail with the old behavior.
This was caught by `cargo check` with the nightly toolchain.
=> matrix auth: Await `save_session_callback`

crates/matrix-sdk-crypto/src/session_manager/sessions.rs
Noticed by @richvdh, thanks. This makes the formatting better by using the display implementations; we don't need to use `itertools::format` anymore, because the statement had to be guarded with an `if debug log level enabled` anyways.
=> dx: tweak debugging of user/device pairs missing a session

xtask/src/swift.rs
Small tweak to #2918 that will move all generated Swift files to the right location once we start using uniffi in more creates.
=> xtask: Move all the Swift files found.

crates/matrix-sdk-common/Cargo.toml
With the `inaccurate` feature, this polyfill uses `Date.now()` to emulate `Instant`, which is not monotonic, causing problems like https://github.com/element-hq/element-web/issues/26416. Without it, it uses `Performance.now()`, which *is* monotonic.
I'm not really sure why we were using `inaccurate` in the first place. It was added in https://github.com/matrix-org/matrix-rust-sdk/pull/414, but that doesn't seem to be giving any clues.
One other point of note: `instant` generally doesn't seem to be very well maintained (cf https://github.com/sebcrozet/instant/issues/52), and maybe we should use `web-time` as that issue suggests.
=> Configure `Instant` wasm polyfill to use monotonic time

bindings/matrix-sdk-ffi/src/timeline/mod.rs
This patch updates `Timeline::send_image` and `Timeline::send_video` so that `thumbnail_url` is now an `Option<String>`.
The idea is to allow sending an image or a video without a thumbnail.
---
* Closes https://github.com/matrix-org/matrix-rust-sdk/issues/2894
=> feat(ffi): `Timeline::send_image` and `send_video` takes an optional `thumbnail_url`

crates/matrix-sdk/src/notification_settings/command.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rule_commands.rs, crates/matrix-sdk/src/notification_settings/rules.rs
Adds a simple API to list, add or remove keywords that trigger notifications.
=> notification settings: Allow to manage keywords

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This contains several small refactoring commits before the "main" one, each can be reviewed separately:
1. Use private method to get poll start rule ID: A `From` implementation is part of the public API
and this conversion does not make sense outside of the module. Even in the module, when I encountered `one_to_one.into()` I was wondering what we were getting. Added a test for the private method.
2. Derive `Copy` for enum types: this a good practice for inexpensive types and avoids to have to call `.clone()` explicitly in the code. There is also one type where we derive `Eq` because `PartialEq` is already derived.
3. Rely more on Ruma methods: it simplifies the code / reduces boilerplate.
4. Use `NotificationSettingsError::RuleNotFound`'s rule ID in`Display` impl: otherwise its not …
=> notification settings: Don't error if poll start rule is not found

crates/matrix-sdk-sqlite/src/utils.rs
This is needed so we can use it inside `chunk_large_query_over`.
=> Provide a limit() method in sqlite to find limit values

crates/matrix-sdk-sqlite/src/state_store.rs
The old code accidentally used the enum value as the limit, but this code requests the value of the limit from the DB connection using the new `limit()` method.
To do this I needed to move `chunk_large_query_over` inside `SqliteObjectStateStoreExt` and add some more trait bounds to allow us to `await` before `do_query` was used.
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/2945
=> Use the `limit()` method to find the variable limit in `chunk_large_query_over`

crates/matrix-sdk-base/src/media.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-common/src/ring_buffer.rs, crates/matrix-sdk/src/media.rs, crates/matrix-sdk/tests/integration/client.rs
This PR should be reviewed commit-by-commit. All commits have a description message.
The idea is to re-implement media support inside `MemoryStore`. It's a quick and dirty implementation but it works. The PR also clean up a bit of code and improve testing.
---
* Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/1247/
=> Test Media caching, and re-implement it inside `MemoryStore`

crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2938
There might be other way to do that. On some other client there is signaling when a new key is imported to trigger that.
But doing it after the sync is probably reasonable.
Signed-off-by:
=> Maybe trigger backup at end of sync

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs
=> Small sliding sync refactorings

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk/src/encryption/mod.rs
Fixes https://github.com/element-hq/element-x-ios/issues/2243
When `regenerate_olm` is called, it creates a new olm machine with a new BackupMachine.
The problem is that the new `BackupMachine` is initialized with no `backup_key`:
`let backup_machine = BackupMachine::new(store.clone(), None);`
As a consequence `client1.encryption().backups().are_enabled()` will sudenly be false.
- My first solution was to  call again `setup_and_resume()` on the machine after `regenerate_olm`, but it's also re-adding a `add_event_handler`, and I don't think it's needed
- I udpated to modify `with_store` to get the cached key and pass it to the new helper
Signed-off-by:
=> Fix regenerate_olm_machine losing backup state

Cargo.lock, bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/sliding_sync_ext.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This adds support for processing the number of unread messages and mentions (highlights) client-side. This can be used to know whether a room has unread content or not (if any count > 0), or if there are mentions (highlights > 0) for the user in a given room. Or, it can also be used as a high-level approximation of the number of unread messages/mentions for recently visited rooms.
This implementation is not final, but attempts to be useful in the short-term. It's relatively simple. It is an improvement over the status quo, in that it can handle events from encrypted rooms, and it has a short-term memory to reconcile read receipts received at a different time than the events they relate to.
Some implementation notes:
- Historically, there's `UnreadNotificationCounts` which returns …
=> Process rooms' read status client-side

crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
Fixes https://github.com/element-hq/element-web/issues/26782
In migrate_data_for_v6, we incorrectly copied the keys in inbound_group_sessions verbatim into inbound_group_sessions2. What we should have done is re-encrypt them using the new table name, so we fix that up with a new migration here.
This caused the bug because we were looking for sessions to mark as backed up by calculating their key (from room_id and session_id) but that key did not exist, because the old sessions were stored under the incorrect keys. So no sessions were marked as backed up, and we repeatedly tried to re-mark them.
Depending on your taste you might like to review this commit by commit.
=> Migrate inbound_group_session2 to fix keys incorrectly copied from old store version

crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs
Can be reviewed commit by commit. It's nice that each test caused natural changes in the API shape too :smiling_face_with_three_hearts:
=> Add moar unit tests for read receipts

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/sliding_sync.rs
This fixes a TODO from #2953, by returning a boolean indicating whether a change happened in the `RoomReadReceipts` and they do need in fact to be saved.
=> read receipts: don't update a `RoomInfo` if the read receipts haven't changed

crates/matrix-sdk-base/src/sliding_sync.rs
This was modified and then removed from the PR, and forgot to put back the previous implementation.
=> Fix: revert notification count change from read receipts PR

crates/matrix-sdk-crypto/src/backups/mod.rs
`mark_request_as_sent` of the `BackupMachine` was doing a call to `store_inbound_group_session_count` just for tracing purpose.
On a test setup with 100k room keys, this call to count is taking 1955ms, in comparison `mark_inbound_group_sessions_as_backed_up` is taking `300ms`.
It's making mark as sent for backup take long for nothing
Signed-off-by:
=> Remove an expensive database call only used for tracing prupose

Cargo.lock, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
We should mostly not save `RoomInfo` by ourselves when we have a `StateChanges` data structure hanging around, otherwise we may save impartial state to the database, and notify subscribers which could then observe this incomplete state. This PR fixes that by adding a test failing on main first, then fixing it, then doing some small improvements in the neighborhood.
=> Avoid a spurious update when setting the room's latest event

bindings/matrix-sdk-crypto-ffi/Cargo.toml
`default-features = false` was already a no-op prior to workspace dependency change, as `matrix-sdk-crypto` has no default features.
=> Fix Cargo warning about default-features

crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs
Simply calls the endpoint. Added a test.
=> sdk: Add method to report an event

crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Small simplification spotted while working on #3000.
=> cleanup: move homeserver overriding to the `SendRequest` struct

crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
Now with a nice test :partying_face: 
Some sliding sync responses may include extension data that will cause an update to the room. For instance, whenever we receive a read receipt for that room, the content of the update lives in the extensions subpart of the response, and it may not involve an entry in the `rooms` or `lists` response fields. This could cause missed updates for rooms, since notifiers wouldn't be notified about those updates, until another response came that mentioned the room in one of the `rooms` or `lists` fields.
This fixes that, by making sure that we take into account room implicitly updated, as observed by the rooms returned in the base client's sync response. The test exhibits the issue (it doesn't pass on main).
=> sliding sync: Trigger a `RoomList` update when a room is updated b/o extensions

bindings/matrix-sdk-ffi/src/notification_settings.rs
Given the following comment:https://github.com/matrix-org/matrix-rust-sdk/pull/2840#issuecomment-1875587994 
The name and the documentation of the API might have been a bit misleading since we are not actively checking the supported state of the homeserver, but just the current state of the account data to verify if encrypted events are pushed to the client or not.
=> Improving documentation: Can push encrypted events to device 

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This started as a partial attempt to fix #1415, but the commit that was supposed to fix this has been removed from this PR, as it wasn't deemed useful: only refactorings remain, each explicited as an individual commit.
For history, the previous text for that PR stands below:
---
We're using application-level transactions to make sure that the account is properly synchronized in the cache vs in the database.
Before this commit, the transaction would be committed only when *all* the operations in it succeeded. This was based on the assumption that most encryption requests could be replayed, by re-sending them to the server. Unfortunately, this assumption doesn't hold for when generating one-time keys: it could be that one time-keys would be generated by the client, then the …
=> crypto: misc refactorings

bindings/matrix-sdk-ffi/src/notification.rs, crates/matrix-sdk-ui/src/notification_client.rs
Required to decide in El-X if names should display the user ID alongside the display name in notifications
=> ffi: Expose is_name_ambiguous for notification item

CONTRIBUTING.md, RELEASE.md
- The first commit introduces recommendations for commit messages and PR titles, that we intend to enforce with recurring contributors. These guidelines propose a consensus that's been reached with the core maintainers of the SDK at Element. We don't think they're controversial, and they shouldn't disrupt the flow of external or infrequent contributors.
- The second commit introduces a RELEASE.md file containing all the steps required to perform a release. I tried to compute the topological ordering with my monkey mind, but hopefully it's correct. @jplatte, can you confirm it contains all the steps please? Cheers!
=> docs: add new contribution guidelines + briefly explain release process

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
Before this, if an error occurred while making the request to the server, the error would be dropped and it wouldn't even be forwarded to the user of the method.
This makes sure:
- We forward server request errors as failures to the output of `Timeline::toggle_reaction`,
- We have logging in place everytime we return a `TimelineError::FailedToToggleReaction`.
=> ui: Improvements to toggle reaction failures

crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/encryption/mod.rs
The message of the first commit should explain the change well, so I'm pasting it inline:
> Specifically, this removes the following redundant types in the main
> crate:
> 
> - enum UserIdentities
> - struct OwnUserIdentity
> - struct OtherUserIdentity
> 
> This is possible because `OwnUserIdentity` and `OtherUserIdentity` are
> exactly the same as their crypto crate counterparts, except they also
> wrap a `Client`.
> 
> As a consequence, the main crate enum `UserIdentities` is isomorphic to
> a struct containing:
> 
> 1. the crypto crate `UserIdentities`
> 2. a `Client`
This then allows us to further simplify the construction of the main crate `UserIdentity` type, requiring only one constructor instead of three. The rest of changes are purely cosmetic, e.g. renaming of variables and …
=> Simplify main crate user identity types

crates/matrix-sdk-crypto/src/machine.rs
As I understand it, `Vec::retain` should do the same job as `into_iter().filter().collect()` but potentially more efficiently. This could help our problem with running out of memory during export ( https://github.com/matrix-org/matrix-rust-sdk/issues/2914 ).
=> crypto: Improve memory overhead of export_room_keys by using Vec::retain

crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/lib.rs, crates/matrix-sdk-sqlite/Cargo.toml, crates/matrix-sdk-sqlite/src/lib.rs, crates/matrix-sdk/src/client/builder.rs
Currently, `matrix-rust-sdk-crypto-wasm` builds `matrix-sdk-base` despite having no dependency on it. (None of the `matrix-sdk-base` is used when `matrix_sdk_indexeddb` is built without the `state-store` feature.)
I think this is because the dependency graph is *complicated*. The problem is `matrix-sdk-indexeddb`'s dependency on the `e2e-encryption` feature of `matrix-sdk-base`. That feature is only used in `matrix_sdk_indexeddb::make_store_config`. By moving that logic into `matrix-sdk`, we can remove the conditional dependency on ` matrix-sdk-indexeddb/e2e-encryption`.
Since I'm doing `matrix-sdk-indexeddb`, I thought I'd better do `matrix-sdk-sqlite` to keep it in step.
Should be reviewable commit-by-commit.
=> indexeddb, sqlite: Avoid dependency on `matrix-sdk-base`

bindings/matrix-sdk-ffi/src/room_list.rs
The Kotlin leaks have been fixed nowadays.
=> ffi: remove unused `RoomListItem::full_room_blocking()` function

crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/matrix_auth/login_builder.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs
Refactoring: 
In existing code the bootstraping is done in different places:
- in `bootstrap_cross_signing_if_needed` 
- or in `run_intialization_tasks`
And both are based on the same EncryptionSettings.
`bootstrap_cross_signing_if_needed` was done by `LoginBuilder` but `run_intialization_tasks` by `MatrixAuth`. 
I propose to move all that under `run_intialization_tasks` that has already support to do it in background, and to call it in one place only: `MatrixAuth`
Also Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2763
- Some tests have been updated to properly `wait_for_e2ee_initialization_tasks`
- `bootstrap_cross_signing_if_needed` might require re-authentication. Which I suppose was the original reason to have that in a seperate place. But given that the need to re-auth …
=> refactor(bootstrap): init cross-signing with other e2e initial task

crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
I saw crashes on export (like https://github.com/matrix-org/matrix-rust-sdk/issues/2914 ) in my local dev environment, but unlike the reporters of that problem, I did not see an out of memory error. I saw a crash inside the Indexed DB transaction, which only happened when the number of keys became quite large.
This PR keeps a single transaction, but batches the work we do within it into chunks, each using a separate cursor. I don't know why, but this fixes the problem in my local dev environment, and I think it is part of the work we will need to do to batch our export into genuine separate chunks to prevent memory exhaustion. So I think it's worth merging in its current form, even if it's only a partial step towards the right solution.
I spent some time trying to make the code …
=> indexeddb: Attempt to fix export crashes by batching DB operations in get_inbound_group_sessions

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-common/src/ring_buffer.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs
Read receipts rely on selecting what is the "most recent" read receipts. Beforehand, it was done by selecting *a* receipt for the current user, whenever we found one. And then, crossing our fingers real hard that the receipt we found was indeed the most recent one.
This wasn't sufficient:
- receipts can be received by the client *before* the event they're matching has reached us,
- ditto, with *after*
- a single receipt event can contain multiple receipts for the current user (any combination of (public, private) × (main thread, unthreaded)).
As a matter of fact, we need to take the sync ordering of the matched events into account, and consider "the most recent" is the one that is matching an event that is the most recent, according to the sync ordering. Fortunately, we do have an …
=> Read receipts: use sync order when computing client-side read receipts

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_member.rs, crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/debug.rs, crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/notification.rs, testing/matrix-sdk-test/src/lib.rs
Necessary for the `.m.rule.invite_for_me` rule that should only happen in invited rooms.
Requires to create a `Notification` type that accepts stripped state events. It is simpler than Ruma's type because it lacks fields with data that is made up or redundant.
Tested locally with Fractal.
Fixes #1912.
=> base-client: Support notifications in invited rooms 

crates/matrix-sdk-crypto/src/verification/requests.rs
Fixes a compiler warning:
```
warning: field `0` is never read
```
As far as I can tell, this has happened for ever. We *could* turn `Done` into a unit variant, but that's quite a lot of changes, would make `Done` asymmetric with the other variants, and would have to be undone if we ever needed that data.
=> crypto: Silence compiler warning

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
Without this, we wouldn't ever have the member information for the logged-in user, the first time they log in, if they don't happen to be the last user sending a message in a room (a case covered by `$LAZY`).
---
It's a very edge case, because we'd receive the current user's member information as soon as we subscribe to any room where the current user wrote a message, *or* we saw any room in `all_rooms` where the current user was the latest event's author, *or* the client received an invite. The member info for the current user is only returned the first time, and whenever it changes afterwards, so it won't make every single response heavier.
=> room list service: add `$ME` as a required state for the `all_rooms` sliding sync list

Cargo.lock, Cargo.toml, crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, labs/README.md, labs/rrrepl/Cargo.toml, labs/rrrepl/src/main.rs
This was quite handy during development of the client-side computation of read-receipts, to analyze some bugs.
It might be not useful to have it checked in for long, but I would love to make sure it keeps on compiling until we have a more stable handling of read receipts in general.
(One could also argue it's a general example of how to use the ui crate when it comes to sync.)
If you agree it should be checked in, please be gentle during review, this is throwaway code :-)
=> labs: introduce rrrrepl, a client specialized for showing and sending read receipts

Cargo.lock, crates/matrix-sdk/Cargo.toml
I've published the 0.7.1 tag and released matrix-sdk to crates.io, let's keep a correct version number in main.
=> Release 0.7.1

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
Let's see if the test correctly passes, now that all the racy behaviors should have been fixed with https://github.com/matrix-org/matrix-rust-sdk/pull/2978.
Fixes #2963.
=> test: reenable the unread count test in code coverage

Cargo.lock, Cargo.toml, crates/matrix-sdk-crypto/src/secret_storage.rs
This patch updates Ruma to the latest commit on its `main` branch.
This is useful for https://github.com/matrix-org/matrix-rust-sdk/issues/2932.
=> chore: Update Ruma to 684ffc

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/secret_storage.rs
A regression test for https://github.com/matrix-org/matrix-rust-sdk/issues/2932.
Also adds a changelog entry.
=> crypto: add test for 4S keys with no `mac` or `iv`

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
- Renamed `compute_notifications` to `compute_unread_counts`, because that's really what this function does. It doesn't generate any new notifications, it computes how many unread messages/notifications/messages there are for a room.
- Changed the strategy to decide whether we need to update a `RoomReadReceipt` after calling `compute_unread_counts`, to let `PartialEq` do the hard work, and not rely on the explicit, error-prone signalling of updates (which was still buggy).
- We're not taking the sync write lock when processing the sliding sync response. @timokoesters has noticed it was an issue in the past for the latest event, and I wonder if `RoomReadReceipt` may be overwritten by the concurrent e2ee sliding sync, so fixing it here now.
=> sliding sync: change read receipts update strategy + take sync lock during response processing

Cargo.lock, Cargo.toml
=> Use new crates.io release of UniFFI

bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs
We need to make sure we guard against servers downgrading the encryption settings, or breaking them with unsupported algorithms. It's not *entirely* clear what the expectation is here, but legacy crypto in matrix-js-sdk blocks any changes to the settings at all, so we'll follow suit for now.
This PR also extends the supported `RoomSettings`. Suggest reviewing each commit separately.
Signed-off-by:
=> crypto: Implement `OlmMachine::{set_,}room_settings`

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
Some clients, including the timeline code handling the *sending* of read receipts, have the notion of an implicit read receipt. Every event that you've sent yourself implies that you've read all the events prior to yours. Both parts of the code should align on when to send read receipts, since computing unread counts precisely relies on read receipts echoed back by the server otherwise. 
This patch adds a new method in the `ReceiptSelector`, to look for an implicit read receipt and use it, if found and it's the latest in sync order.
Also add lots of tracing `trace`-level logs for making remote debugging easier.
=> read receipts: handle implicit receipts for unread counts

bindings/matrix-sdk-ffi/uniffi.toml
Note that this breaks compatibility with pure JVM environments, meaning the Kotlin library can only be used in Android.
Signed-off-by:
=> ffi: Use Android Cleaner implementation if possible

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/room_member.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/member.rs, crates/matrix-sdk/src/room/mod.rs
https://github.com/matrix-org/matrix-rust-sdk/issues/3033
This PR adds the suggested mapping in the [spec](https://spec.matrix.org/v1.9/client-server-api/#permissions) for power levels to a new enum so we can share the logic to figure out who is an admin, mod or regular member within a room.
In order to do this, I've added uniffi to the SDK crate like we already did for the UI crate.
=> sdk: Add support for getting a room member's suggested role

crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
A quick performance improvement to not do the deserialization/decryption inside the transaction.
Signed-off-by:
=> indexeddb(perf): don't deserialize data while in an indexeddb transaction

testing/matrix-sdk-integration-testing/assets/docker-compose.yml
I am sorry, I actually didn't test the latest commits of #3063, and podman compose complains that the syntax is invalid.
=> integration-testing: Fix syntax of docker-compose.yml

testing/matrix-sdk-integration-testing/src/tests/reactions.rs
It's started failing with timeouts in multiple PRs, so this PR should help spot where the issues specifically are, since codecov test failures are so hard to reproduce locally.
=> integration test: make `test_toggling_reaction` fail fast

Cargo.lock, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/lib.rs, testing/matrix-sdk-test/src/sync_builder/mod.rs, testing/matrix-sdk-test/src/sync_builder/test_event.rs, testing/matrix-sdk-test/src/test_json/sync_events.rs
Handles "Expose a way to have is_favorite: bool live in the bindings" from https://github.com/matrix-org/matrix-rust-sdk/issues/3005
=> Tags: introduce RoomNotableTags

bindings/matrix-sdk-ffi/src/timeline_event_filter.rs
Added:
- PollEnd
- PollResponse
- PollStart
- UnstablePollStart
- UnstablePollResponse
- UnstablePollEnd
Signed-off-by:
=> ffi: add missing poll events to `FilterMessageLikeEventType`

.typos.toml, Cargo.lock, crates/matrix-sdk-indexeddb/src/crypto_store/indexeddb_serializer.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk-store-encryption/src/lib.rs
Fixes #3057.
Change the way we store values in Indexed DB for the crypto store, specifically in the `inbound_group_sessions` store. Reduce the size of the stored values and replace arrays of numbers with base 64 strings. The rationale and some implementation ideas are documented in #3057. (TL;DR: small values are faster, base64 is faster.)
This change:
* Introduces a `MaybeEncrypted` type in `matrix_sdk_indexeddb::crypto_store::indexeddb_serializer` that encapsulates the fact that we serialize differently if the session is encrypted with a store cipher. (Previously, we just serialized an array of numbers in both cases. This was actually quite confusing since these arrays of numbers were holding encoded versions of very different values.) This enum is `untagged` in Serde to avoid …
=> indexeddb: Shrink values in inbound_group_sessions store, improving performance all around

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
I think the reasoning behind using a RwLock for sync, and notably allowing multiple concurrent `.read()` lock taking was flawed: since there's no way to identify which subpiece of the store we're reading and writing, there could be two concurrent requests to the write to the same thing at the same time. To get rid of this possibility, this commit changes the lock to a single access only Mutex lock.
=> sdk: use a Mutex instead of a RwLock for the sync lock

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This PR must be reviewed commit-by-commit.
`matrix_sdk::sliding_sync::SlidingSyncRoom` holds information about the unread notification counts. Unfortunately, it's a duplication of the data synchronized with `Room`. Worst: it hides the new Read Receipt Notification Count API, introduced by @bnjbvr. So this is basically a bad API to use, and almost dead code now.
These patches clean the situation up by removing the `SlidingSyncRoom::has_unread_notifications` and the `::unread_notifications` methods, along with all the chain: `matrix_sdk_ui::room_list_service::Room` and `matrix_sdk_ffi::room_list_service::Room`.
---
=> feat(sdk,ui,ffi): Remove `SlidingSyncRoom::has_unread_notifications` and `::unread_notifications`

crates/matrix-sdk/src/sliding_sync/room.rs
This patch removes a useless and not used (in the Matrix Rust SDK, along with the FFI bindings) method: `SlidingSyncRoom::required_state`.
This is based on https://github.com/matrix-org/matrix-rust-sdk/pull/3080. Please see only the last commit.
---
=>  feat(sdk): Remove the `SlidingSyncRoom::required_state` method

crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This patch continues the clean up of `matrix_sdk::sliding_sync::SlidingSyncRoom`. Please read commit-by-commit. 3 methods are removed, because either they are never used, or because the data they contain are a duplication with the `matrix_sdk_base::Room`.
---
=> feat(sdk,base,ui,ffi): Continue to remove dead code in `SlidingSyncRoom`

crates/matrix-sdk-indexeddb/src/crypto_store/migrations.rs
Since my investigation found that it significantly speeds up deletion of a store on both Firefox and Chromium if you clear() it first, do that in our migration code.
Related: https://github.com/element-hq/element-web/issues/26948
=> indexeddb: Clear the object store before deleting it

crates/matrix-sdk-ui/src/timeline/sliding_sync_ext.rs, crates/matrix-sdk/src/sliding_sync/list/frozen.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This patch removes the need to store and to update the
`SlidingSyncRoom::inner` field (of type `v4::SlidingSyncRoom`). Now,
we just need to handle the `prev_batch`, which is the only data we care
about.
Bonus: it reduces the size of the frozen sliding sync room quite much.
---
=> feat(sdk): Remove `SlidingSyncRoomInner::inner`

crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/client.rs
This PR had the main goal to allow to follow ambiguity changes per-room, without relying on the `SyncResponse`. We need this because we keep the members list of the current room in memory for mention autocompletion in Fractal.
As a bonus, we use that to update profiles in the `Timeline` when there is an ambiguity change (ticks one of the boxes in https://github.com/matrix-org/matrix-rust-sdk/issues/1103).
=> sdk: Allow to track ambiguity changes per-room

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs
Requires https://github.com/ruma/ruma/pull/1721
This PR add support for manually marking rooms as unread through the means of [MSC2867](https://github.com/matrix-org/matrix-spec-proposals/pull/2867) which introduces a new room account data flag.
Rooms now have a new `mark_unread(unread: bool)` method for setting the flag as well as a `is_marked_unread` property, which is also exposed on RoomInfo
On the FFI layer the method above is used in conjucture with `send_read_receipt` to fully mark a room as read, which the client should do from the room list (outside of the timeline)
=> Add support for MSC2867 - Manually marking rooms as unread

crates/matrix-sdk-ui/src/timeline/sliding_sync_ext.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This patch inlines `SlidingSyncRoom::latest_event` into its unique call site: `SlidingSyncRoomExt::latest_timeline_item`.
`SlidingSyncRoom::latest_event` is not using any data from `SlidingSyncRoom`, except the `Client`. So it can easily live somewhere else. Our goal is to clean up `SlidingSyncRoom` as much as possible, and to remove any kind of logic from it.
---
=> feat(sdk,ui): Remove `SlidingSyncRoom::latest_event`

crates/matrix-sdk/CHANGELOG.md
=> Add a missing changelog entry for the Client::sync_token() method

Cargo.lock, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/room/power_levels.rs
Closes #3034 and closes #3035
This PR makes the following changes:
- Add a method to the FFI to update a specific user's power level.
- Adds a `RoomPowerLevelChanges` type that allows for updating the required power levels for common operations from a single place.
- Expose the power level settings to the FFI.
Note that in the first commit, I was removing any state events where their power levels matched the default, however looking at the behaviour of Element Web, I noticed that they are actually kept, presumably so that changing the state default, doesn't have a knock-on effect for all the other power-levels, potentially allowing users to perform actions that you weren't expecting. This behaviour is removed in the second commit.
=> Add RoomPowerLevelSettings.

crates/matrix-sdk/src/sliding_sync/list/request_generator.rs
While randomly reading the code, I've noticed this typo.
=> doc(sdk): Fix a typo

crates/matrix-sdk/src/encryption/recovery/mod.rs, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
Please take a look at the commit message of the first commit to understand what's going on. The second commit just adds an integration test for the backup creation using a real server.
=> Fix a race when automatically enabling room key backups

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/room/mod.rs, crates/matrix-sdk/tests/integration/room/tags.rs
Handles "Expose a way to update tags in the bindings" from https://github.com/matrix-org/matrix-rust-sdk/issues/3005
=> Tags : introduce set_is_favorite and set_is_low_priority

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/machine.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1816
Adds a new API on `Device` called `create_encrypted_to_device_request` that allows to encrypt a specific event
to a single target device. 
The caller must call `get_missing_sessions` before calling `create_encrypted_to_device_request`, or he might get an `OlmError::MissingSession`.
For now this will create missing sessions with all devices of the target users, as there is no API to get missing session for a given device, but I think it's acceptable.
Signed-off-by:
=> Simple send encrypted to device API

crates/matrix-sdk-ui/src/timeline/mod.rs
This didn't show up, and it's quite useful to know for which room we're trying to send a receipt, without having to look up the room based on the target event id.
=> read receipts: add the room id in the instrumentation of `send_single_receipt`

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-ui/src/event_graph.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sync.rs
A few renamings for things that confused me at least once in the past. Each commit can be reviewed/accepted in isolation.
=> sdk: a few renamings in the sync processing area

Cargo.lock, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/tags.rs
This PR must be reviewed commit-by-commit.
This PR entirely revisits the `RoomNotableTags` API (introduced in #3071 and #3075). The idea is to compute the notable tags as a single 8-bits unsigned integer (`u8`) and to store it inside `RoomInfo`. The benefits are numerous:
1. The type and the API is noticeably smaller that the existing `RoomNotableTags`,
2. It's part of `RoomInfo` so:
- We don't need an async API to fetch the tags from the store and to compute the notable tags,
- It can be put in the store,
- The observable/subscribe mechanism is supported by `RoomInfo` behind observable instead of introducing a new subscribe mechanism.
The PR ends up providing `Room::is_favourite` and `Room::is_low_priority` as simple non-async getters, which is needed by #3021.
---
* Address #3005
* …
=> fix(base): Rewrite `RoomNotableTags`

crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/media.rs, crates/matrix-sdk/tests/integration/client.rs
`matrix_sdk_ui::timeline::Message::msgtype` returns `&MessageType`, and variants of `MessageType` implement `MediaEventContent`, so it is allowing references here avoids cloning message content.
=> Allow references to MediaEventContent

crates/matrix-sdk/src/media.rs
Vectors grow in powers of two while reading, which is doubly wasteful:
* causes every byte to be copied in average once
* leaves the vector in average 25% larger than it needs to be, wasting memory.
For example, adding this test to
`crates/matrix-sdk-crypto/src/file_encryption/attachments.rs`:
```rust
fn encrypt_decrypt_minimize_memory() {
let data = std::iter::repeat("abcdefg").take(10000).collect::<String>();
let mut cursor = Cursor::new(data.clone());
let mut encryptor = AttachmentEncryptor::new(&mut cursor);
let mut encrypted = Vec::new();
encryptor.read_to_end(&mut encrypted).unwrap();
let key = encryptor.finish();
assert_ne!(encrypted.as_slice(), data.as_bytes());
let mut cursor = Cursor::new(encrypted);
let mut decryptor = AttachmentDecryptor::new(&mut cursor, key).unwrap();
let …
```
=> Preallocate vector storing decrypted files

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs, crates/matrix-sdk/src/encryption/secret_storage/mod.rs, crates/matrix-sdk/tests/integration/encryption/recovery.rs
The first commit makes it so that there can't be two clients living at the same time.
The second commit changes the default configuration of FFI clients, so they don't try to enable backup and cross-signing bootstrap for the first client that's used only to figure out what's the user's `user_id()`. Only the second client may do that.
This should avoid a race condition at startup at the FFI level, where multiple clients try to initialize encryption at the same time, or would send one-time-keys racily.
The third commit is me figuring out the effect of setting up backup and recovery: mostly it adds event handlers, recovers state by reading from the store. For a fresh in-memory client, it will do nothing interesting.
=> ffi: have at most one `Client` alive at any time during login and don't run e2ee tasks for the login client

crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
Critically, explain _why_ the session is being rotated. Ends up looking like:
`2024-02-07T17:41:15.683374Z DEBUG matrix_sdk_crypto::session_manager::group_sessions: collect_session_recipients should_rotate=true user_left=true visibility_changed=false algorithm_changed=false | crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs:453 | spans: send_raw{room_id="!OERZwnPnwtzHsOxJIo:hs1" transaction_id="a894c3b5214a4b6c935623b8f75ccee5" encrypted=true} > preshare_room_key{room_id="!OERZwnPnwtzHsOxJIo:hs1"} > share_room_key > share_room_key{room_id="!OERZwnPnwtzHsOxJIo:hs1" session_id="KITTxcvy/BUM+F4Htlf5zfAeoV4KXUsuYFgoGIZx9SI"}`
and
`2024-02-07T17:41:40.203132Z DEBUG matrix_sdk_crypto::session_manager::group_sessions: collect_session_recipients: rotating due to these devices being …
=> Add debug logging when sessions get rotated

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs
See commit by commit for an easier review.
TL;DR:
- FFI `mark_as_{un}read` has been changed to `set_unread_flag(bool)`
- a new method `Timeline::mark_as_read` is introduced in both the UI and FFI layers, attaching a read receipt to the latest event (not the event attached to the latest item)
- instead of `mark_as_unread_and_send_receipt`, it's expected of the callers to first call `set_unread_flag(false)` then `mark_as_read`
- instead of using `send_read_receipt` on the latest item's event id, when scrolled to the bottom in a room view, one would call `mark_as_read`
Pinging some app developers so they're aware of the new methods, cc @stefanceriu @ganfra @bmarty
Should fix with stuck unreads like https://github.com/element-hq/element-x-ios-rageshakes/issues/1409.
=> timeline: mark as read based on the latest folded/invisible event

bindings/matrix-sdk-ffi/src/client_builder.rs
This fixes #3130.
The fact that we have two places where we pass in things to the client builder is pretty annoying and I would call this a broken API. #3126 is also affected by the configure twice and more things will come.
Though let's fix the backup download strategy so we can tackle the API rework in peace.
=> ffi: Re-enable the correct backup download strategy for the bindings

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/http_client/native.rs
This PR mainly allows clients to add root certificates to the HTTP client without having to build the `reqwest::Client` manually.
We also re-expose this functionality through the bindings.
=> Re-expose the reqwest method to add additional root certificates to the HTTP client

bindings/matrix-sdk-ffi/src/error.rs, crates/matrix-sdk-ui/src/event_cache.rs, crates/matrix-sdk-ui/src/event_cache/store.rs, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/client.rs, testing/matrix-sdk-test/src/test_json/sync.rs
See changes commit by commit. Sitting on top of #3121.
Part of #3058.
=> event ~~~graph~~~ cache: listen to the updates to all rooms at once

crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
discovered during trying to use matrix-sdk-ui on wasm.
=> indexeddb: fix incorrect key used for next batch token

crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/builder.rs
Take III at #3029. This replaces #3108 with the additions to homeserver discovery being moved into the ClientBuilder instead. The new `server_name_or_homeserver_url` method on the builder will first attempt to build the client by discovering a well-known for a server name, and will then fall back to building the client based on a direct URL, but checks that a server actually exists before building, throwing if it doesn't.
These changes are unused, I'll make a follow-up PR to use this in the existing auth service after this is merged.
=> sdk: Add `ClientBuilder::server_name_or_homeserver_url`

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/filters/all.rs, crates/matrix-sdk-ui/src/room_list_service/filters/any.rs, crates/matrix-sdk-ui/src/room_list_service/filters/category.rs, crates/matrix-sdk-ui/src/room_list_service/filters/favourite.rs, crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs, crates/matrix-sdk-ui/src/room_list_service/filters/non_left.rs, crates/matrix-sdk-ui/src/room_list_service/filters/none.rs, crates/matrix-sdk-ui/src/room_list_service/filters/normalized_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/filters/not.rs, crates/matrix-sdk-ui/src/room_list_service/filters/unread.rs
This PR adds the `favourite` room list filter.
This PR should be be reviewed commit-by-commit, though the patches are rather simple.
---
* Closes https://github.com/matrix-org/matrix-rust-sdk/issues/3021
* Blocked by https://github.com/matrix-org/matrix-rust-sdk/pull/3111
=> feat(ui,ffi): Add the `favourite` room list filter

bindings/matrix-sdk-ffi/src/client.rs
This should help us understand why 2 failed requests with invalid access token didn't pass a refreshed token to the client.
I'll also add more detailed logging filters to the app so we can try to track the actual refresh so we can check where this process failed:
- When refreshing the access token: refreshing failed or no refresh happened (is this even possible?).
- When notifying the client: maybe there is no delegate, or it was destroyed.
- At the client somehow: I don't see how, but if we discard every other possibility....
Signed-off-by:
=> ffi: Add extra logs to `Client::process_session_change`

bindings/apple/Tests/MatrixRustSDKTests/ClientTests.swift, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/lib.rs
This PR builds on top of #3129 and uses the new (and tested) method in the FFI.
As part of this I've added a `ClientBuildError` to the FFI's client builder that passes up the SDK's error so we can match it.
Next part of #3029.
=> Use ClientBuilder::server_name_or_homeserver_url directly in the authentication service.

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk/src/client/mod.rs
This PR exposes 2 new methods on the FFI client that will
1) Allow fetching the current list of ignored users from the current account's data
2) Allow subscribing to changes to said list
=> Fixes #3141 - Expose ignored users on the FFI layer

bindings/matrix-sdk-ffi/src/authentication_service.rs
The ClientBuilder already exposes setting the proxy, but sadly the AuthService doesn't let you configure the ClientBuilder directly (yet).
So logging in with a proxy wasn't supported until now.
=> ffi: Let the auth service use a proxy as well

bindings/matrix-sdk-ffi/src/client_builder.rs, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_cache/mod.rs
Turns out I've been a bit too eager about removing the `Room` in the event cache; it is needed for the back-pagination, to call `Room::messages()`. This is basically reverting https://github.com/matrix-org/matrix-rust-sdk/pull/3136/commits/f022b405caf3b45d5228032c8156f9136246c59b and putting back the infrastructure for the deferred initialization in the `Client`.
=> event cache: put the `sdk::Room` back in the `RoomEventGraph`

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This test has caused timeouts lately, so adding some logs to help investigating what goes wrong.
Also identified one possible cause for it to be wrong, let's see if it helps. (It's hard to reproduce those intermittent timeouts under the code coverage task.)
=> test: timeout faster in `test_room_notification_count`

crates/matrix-sdk/src/room/futures.rs, crates/matrix-sdk/src/room/mod.rs
Fixes https://github.com/element-hq/element-x-ios/issues/2216
We were not logging the id of events we send. Make it hards to debug UISI when we want to ensure that the device was the sender.
~~I did put it as `info` level, let me know if you think it should be `debug`. I'll then have to update the filter so that it appears correctly in the app logs.~~
~~Logs will look like that~~
~~> 2024-02-23T15:29:21.915148Z  INFO matrix_sdk::room::futures: Sent event in room event_id="$sUpMhXe18_hrac6MNNZQEQllk7d_jAlpLN2FxJdjqmU" | crates/matrix-sdk/src/room/futures.rs:205 | spans: root > send_raw{room_id="!NCkAdxsQkjlTESyKQC:matrix.org" transaction_id="cee10b9ac7db429291005852e5e31e1f" encrypted=true}~~
**Edit**
As per suggestion the`event_id` is now added to the current span
Logs looks like that …
=> sdk: Add an info log with the `event_id` when a room event is succesfully sent

crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/tests/integration/event_cache.rs, crates/matrix-sdk/tests/integration/main.rs
This adds a few basic tests for the event cache, notably one for the `add_initial_events`, for something I identified while working on the code, but that could've caused bad issues:
The `test_add_initial_events` checks that even if we received updates with meaningful events for a room, the room's events are cleared before we add initial events (since we have no ways to know where to insert the events, in this case). In the future, we can keep this test as a "smoke test" for basic functionality of the event cache.
=> event cache: add a few smoke tests

bindings/matrix-sdk-ffi/src/room_member.rs
This PR exposes a method to get the suggested power level from a role. Just like using the role's constructor with a power level, the macros don't allow to `uniffi::export` a method on an enum, so this needs to be done as a global method ☹️
=> FFI: Expose getting a power level from a role.

Cargo.lock, Cargo.toml
This will pull in https://github.com/mozilla/uniffi-rs/pull/1975 and hopefuly not cause any breaking changes.
=> ffi: bump uniffi to latest to generate open swift classes

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/room_member.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk/src/config/request.rs, crates/matrix-sdk/src/room/mod.rs
See https://github.com/matrix-org/matrix-rust-sdk/pull/3074 and https://github.com/matrix-org/matrix-rust-sdk/pull/3101 for previous versions. This PR is based on !3074 with minor cleanup.
The corresponding element android PR is here: https://github.com/element-hq/element-x-android/pull/2322
=> ffi: aggregate `RoomMember` fields early instead of requiring calling getters

Cargo.lock, Cargo.toml
At the moment, the SDK can't be built for Android after https://github.com/matrix-org/matrix-rust-sdk/pull/3174 because of these 2 issues:
- https://github.com/mozilla/uniffi-rs/issues/1996
- https://github.com/mozilla/uniffi-rs/issues/1995
Those have been fixed in the new commit.
@stefanceriu: next time we decide to bump to a non-stable version please ask us to test it in every platform. Otherwise we can end up in a similar situation.
Signed-off-by:
=> ffi: bump the UniFFi referenced commit again

bindings/matrix-sdk-ffi/src/room.rs
Having noticed that we were about to queue up calls for multiple members in EX it seemed worth passing in an array. I'm honestly not sure why I didn't originally expose this method in line with the SDK method it calls, but it's fixed now!
=> FFI: Update the power levels of multiple users at once.

.github/workflows/coverage.yml
https://github.com/codecov/codecov-action/tree/v4?tab=readme-ov-file#v4-release
> Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token)
Let's see if it helps with forks.
=> ci: update codecov action to v4

bindings/matrix-sdk-ffi/src/timeline/content.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
Prompted by https://github.com/element-hq/element-x-ios/issues/1837
This PR exposes `m.call.invite` events on the Timeline and as a latest Room message. It will allow the client to render them and inform the user accordingly.
=> feat: add support for `m.call.invite` events in the timeline and as a last room message

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/event_cache.rs
By attaching the `RoomEventCache` public getter to the `Room` itself, we can make it so that it's impossible to get an error when getting the room cache for a room. The only downside is that, when receiving room updates, we now need to fetch the room in the client, and log an error if it's missing. It really shouldn't be missing at any time, so as when we're calling event handlers we're logging out an `error!` when that happens.
=> event cache: get rid of the `RoomNotFound` error

bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, testing/matrix-sdk-test/src/test_json/sync.rs
It maps user ids to users' power levels.
Also, make sure it just returns an empty map if this info is not available, instead of crashing. 
Then use it in the FFI side to output updated data for the `RoomInfo`.
Signed-off-by:
=> sdk: create new `users_with_power_levels` fn 

crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-sqlite/src/state_store.rs
A backwards compatible optimization addition to the `StateStore` allowing to set_custom_value without reading it first.
Background: we use the set_custom_value quite extensively to store our own code. At times this can be a bit larger and it adds quite a bit of delay into the processing to have a get and the corresponding mem-copies happen from the SQlite store all the way to the our App just to have it discarded at the end. 
Thus, this PR adds a `set_custom_value_no_read` which falls back to `set_custom_value` discarding the given value by default - and thus makes it backwards compatible - but allows the store implementation to provide a more efficient set-implementation if useful. This is implemented for the SQlite store implementation in this PR as well.
Signed-off-by: Benjamin …
=> Add optimization on StateStore to allow setting a custom value without read

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, testing/matrix-sdk-test/src/test_json/sync.rs
This will return the default power level for several actions based on the Matrix spec.
We can use this info to add a 'reset to defaults' option in the clients.
cc @pixlwave 
Signed-off-by:
=> sdk: add Room::default_power_levels() function

crates/matrix-sdk/src/event_cache/mod.rs
Before this patch, there could potentially be a race condition between `EventCache::handle_room_updates` and `EventCache::add_initial_events`, for instance like that:
- `add_initial_events` clears events in a room
- `handle_room_updates` adds events received from sync
- `add_initial_events` adds the initial events
And that could lead to duplicate events.
This paves the way for the crypto-store lock by making it so that access to the store is protected behind a lock, so we don't actually need another lock only dedicated to processing.
=> event cache: enforce unique access on the `EventCacheStore`

bindings/matrix-sdk-ffi/src/notification_settings.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, testing/matrix-sdk-test/src/test_json/api_responses.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3191
Allows support for fetching the unstable_features from `/_matrix/clients/versions`.
Specifically, to be used for checking the state of org.matrix.msc4028 through ffi to the clients.
P.S. ^ I can split them into two PRs if necessary.
Signed-off-by: @hanadi92
=> sdk&ffi: server unstable features support for MSC4028

bindings/matrix-sdk-ffi/src/timeline/content.rs
This is needed to be able to diff between increases and decreases of power levels ("user Alice was promoted Admin", etc.).
Signed-off-by:
=> ffi: add `previous` power levels to `OtherState::RoomPowerLevels`

Cargo.lock, Cargo.toml, crates/matrix-sdk/src/http_client/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs
=> workspace: Bump ruma crate

crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
This prepares the way for me to add a feature flag making `rotation_period_ms`'s enforced minimum be turn-off-able via a feature flag (which is needed for https://github.com/matrix-org/complement-crypto/issues/17).
=> crypto: Break up the expiration tests for clarity

Cargo.lock, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/utilities.rs
Turns out this is quite useful information when analysing decryption failures.
=> crypto: Include event timestamp in decryption failure logs

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/sync_service.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/src/sync_service.rs
The idea of this patch is to explore the possibility to unify the `all_rooms` list with the `invites` list in `RoomListService`. Since this is entirely experimental, it's behind a new feature flag. The feature itself can be configured at runtime by using the new `SyncServiceBuilder::with_unified_invites_in_room_list` builder method, or directly with `RoomListService::new_with_unified_invites` constructor.
=> feat(ui,ffi): Add a new `experimental-room-list-with-unified-invites` feature

crates/matrix-sdk-crypto/src/error.rs
Putting this up for discussion and CI checks:
As far as I can tell, whenever Vodozemac returns a `DecryptionError`, matrix-sdk-crypto then wraps it as a `SessionWedged`, so the presence of `DecryptionError` here is redundant and misleading.
=> Remove `OlmError::Decryption`

crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/README.md, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/3198
I suggest reviewing commit by commit.
As discussed IRL with @poljar, add a feature flag that will allow us to remove the minimum session rotation time, so that we can write complement-crypto tests that use very short expirations.
See https://github.com/matrix-org/complement-crypto/issues/17 for more.
=> crypto: Add a feature flag to disable the minimum session rotation time

Cargo.toml
This patch enables the `compat-tag-info` feature on Ruma, so that `TagInfo::order` can be deserialized from both a `f64` or a `string` representing a `f64`[^1].
[^1]: https://github.com/ruma/ruma/blob/f24cae17f50d140a0ff112cb3dc74a2053aa1df4/crates/ruma-events/src/tag.rs#L180-L185
=> fix(ruma): Add the `compat-tag-info` feature

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-ui/src/encryption_sync_service.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
It's a bit unclear whether the crypto-store generation counter is doing the right thing in terms of causing us to reload the OlmMachine. There is a suspicion that things might be keeping hold of references to the old OlmMachine.
This PR attempts to add the generation number to the logging for any operations that hold the cross-process lock. It's obviously not bulletproof: for example, it is possible for the `OlmMachine` to be replaced without holding the lock; but hopefully this will at least help us understand what's going on.
=> Add more logging for crypto store generation counter

crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/src/timeline/tests/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/store.rs, crates/matrix-sdk/tests/integration/event_cache.rs
This adds support for back-pagination into the event cache, supporting enough features for integrating with the timeline (which is going to happen in a separate PR).
The idea is to provide two new primitives:
- one to get (or wait, if we don't have any handy) the latest pagination token received by the sync,
- one to run a single back-pagination, given a token (or not — which will backpaginate from the end of the room's timeline)
The timeline code can then use those two primitives in a loop to replicate the current behavior it has (next PR to be open Soon™).
The representation of events in the store is changed, so that a timeline can have *entries*, which are one of two things:
- either an event, as before
- or a gap, identified by a backpagination token (at the moment)
This allows us to …
=> event cache: add support for running back-pagination

bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/sync_service.rs, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
This adds a new mechanism in the UI crate (since re-attempts to decrypt happen in the timeline, as of today — later that'll happen in the event cache) to notify whenever we run into a UTD (an event couldn't be decrypted) or a late-decryption event (after some time, a UTD could be decrypted).
This new hook will deduplicate pings for the same event (identifying events on their event id), and also implements an optional grace period. If an event was a UTD:
- if it's still a UTD after the grace period, then it's reported with a `None` `time_to_decrypt`,
- if it's not a UTD anymore (i.e. it's been decrypted in the meanwhile), then it's reported with a `time_to_decrypt` set to the time it took to decrypt the event (approximate, since it starts counting from the time the timeline receives it, …
=> ui/timeline: allow subscribing to UTDs and late-decrypt events

bindings/matrix-sdk-ffi/src/ruma.rs
Enables clients to render media captions as per the recently merged [MSC2530](https://github.com/matrix-org/matrix-spec-proposals/pull/2530).
Related ruma PR: https://github.com/ruma/ruma/pull/1732
Signed-off-by: Tobias Büttner <dev@spiritcroc.de>
=> ffi: Expose filename and formatted body fields for media captions

crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/event_cache/linked_chunk.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/store.rs
This PR is a work-in-progress. It explores an experimental data structure to store events in an efficient way.
Note: in this comment, I will use the term _store_ to mean _database_ or _storage_.
The biggest constraint is the following: events can be ordered in multiple ways, either topological order, or sync order. The problem is that, when syncing events (with `/sync`), or when fetching events (with `/messages`), we **don't know** how to order the newly received events compared to the already downloaded events. A reconciliation algorithm must be written (see #3058). However, from the “storage” point of view, events must be read, written and re-ordered efficiently.
The simplest approach would be to use an `order_index` for example. Every time a new event is inserted, it uses the position …
=> feat(sdk): Event cache experimental store

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/olm/account.rs
When we fail to decrypt an olm message, it is useful to know *why* it failed. Include the details of the failures in the warning message.
=> crypto: Log errors from Olm decryption

crates/matrix-sdk-crypto/src/verification/mod.rs
Append error msg for the missed cancel codes.
Sorry, my mistake closed [my previous PR](https://github.com/matrix-org/matrix-rust-sdk/pull/3209).
Will fix [this issue](https://github.com/matrix-org/matrix-rust-sdk/pull/3209#discussion_r1523058621).
=> crypto: Add new error messages for verification cancellation

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/src/timeline/reactions.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/edit.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs, crates/matrix-sdk/src/event_cache/mod.rs
This introduces a few refactorings to mostly the timeline. Commits can be reviewed in isolation.
Notable changes:
- by raising the size of the type holding the number of events touched in `HandleManyEventsResult`, I got rid of most overflow checks, with the reasoning that u64 should be enough for everyone, aka: we shouldn't get `u64::max_value()` events while back-paginating (even if we do it multiple times), nor should we get that many events in a single sync response. I think this heuristic is fine, and that gets rid of one fallible path. (I slightly wonder if we could even get rid of the transaction mechanism, but it seems some functions use it with early returns, so it's still used at least.)
- I got rid of a few `Deref` implementations that were surprising to me. I don't like …
=> timeline: a few drive-by refactorings

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs
The small first commit reintroduces `sanitize_server_name` in the public API. In Fractal, we use it to validate the string in the input before allowing the user to trigger the discovery.
The main commit changes a bit the discovery process: before, server names like `example.org` would only be checked for the presence of a well-known, and only URLs like `https://example.org` would be checked as a homeserver. Now, providing `example.org` will also check if `https://example.org` is the URL of a homeserver.
Sadly I don't think it's possible to add tests for it as it would require to have a homeserver accessible via HTTPS.
=> sdk: Check if server name points to homeserver during discovery

Cargo.toml
This reflects the reality of the situation at the moment: we need 1.76. to compile, and Ruma requires 1.75.
=> Update minimum supported Rust version to 1.76

crates/matrix-sdk/src/event_cache/linked_chunk.rs, crates/matrix-sdk/src/event_cache/store.rs
This patch updates `ChunkContent::Gap` to hold a content `U`. Thus, `Chunk` and LinkedChunk` both get a new generic parameter `U`. Some methods like `new_gap` or `insert_gap_at` take a new `content: U` parameter.
This type `RoomEvents` (that uses `LinkedChunk`) is also updated accordingly.
And because @bnjbvr asked me to do it with Beatbox, I delegate this task to the king of Beatbox: [Rythmind](https://www.youtube.com/watch?v=IX8p4GAfUoU).
=> feat(sdk): `LinkedChunk` can hold a value for `Gap`s

crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/tests/integration/event_cache.rs
@Hywan gently had me notice that the pagination token is optional. This is a remnant from a previous version of the patch, where the token was mandatory.
=> event cache: rename `backpaginate_with_token` to `backpaginate`

.github/workflows/msrv.yaml, crates/matrix-sdk/Cargo.toml
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3224
Based on the recommendation at https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
=> ci: Add a workflow to verify the minimum supported Rust version

Cargo.lock, Cargo.toml
Related to https://github.com/element-hq/element-x-android/issues/2346
When Element X ran on GrapheneOS, a fork of Android, with API Level 33, it crashed on startup because it tried to instantiate an `AndroidSystemCleaner`, which is not supported. A pull request, https://github.com/mozilla/uniffi-rs/pull/2036, was merged to avoid using a `SystemCleaner` on Android 13.
=> chore: upgrade uniffi-rs to latest commit

crates/matrix-sdk/src/event_handler/context.rs
so it can be moved out and converted to other types like ruma::Serde::Raw.
closes #3237.
Signed-off-by: `lilydjwg <lilydjwg@gmail.com>`
=> sdk: make content of RawEvent public

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/widget/settings/mod.rs
Also rename existing `Account::get_profile` to `Account::get_current_user_profile` and reuse the new function.
Signed-off-by:
=> sdk: move `get_profile` from `Client` to `Account`

bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs
Fallback keys until now have been rotated on the basis that the homeserver tells us that a fallback key has been used.
Now this leads to various problems if the server tells us too often that it has been used, i.e. if we receive the same sync response too often. It leaves us also open to the homeserver being dishonest and never telling us that the fallback key has been used.
Let's avoid all these problems by just rotating the fallback key in a time-based manner.
This fixes #3127.
=> crypto: Rotate fallback keys in a time-based manner

Cargo.lock, crates/matrix-sdk/Cargo.toml
We don't need the `hyper` feature as we use our own HTTP client, and the `keystore` will not be used in most cases.
We need to switch to a recent git rev because a couple of commits just landed with fixes for disabling the default features.
=> sdk: Don't enable default features of mas-oidc-client

bindings/matrix-sdk-crypto-ffi/src/responses.rs, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk/src/encryption/mod.rs
Backing up room keys isn't part of the outgoing requests processing loop, instead the user is supposed to have a separate loop calling `BackupMachine::backup()`.
This closes #3244.
=> crypto: Remove the KeysBackup variant of the OutgoingRequest enum

crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Because I am trying to get `MemoryStore` to pass the `cryptostore_integration_tests`, I need this store to hold on to the tracked users, when previously it didn't both.
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3220
Part of my work on https://github.com/element-hq/element-web/issues/26892
=> crypto: Store TrackedUsers in MemoryStore

crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3247
A source of https://github.com/matrix-org/matrix-rust-sdk/issues/3197
When downloading keys if the `forwarding_curve25519_key_chain` contains items the deserialisation would fail with `error: Json(Error("invalid type: string \"EQCtWSJclhxEU9mGlF4erDHxIacpUQz70yjYVRPODTg\", expected an array of length 32", line: 1, column: 255))`
As a consequence the key import fails silently with:
`Successfully imported room keys total_count=0 imported_count=0 room_keys={} `
That would cause unable to decrypt errors for history.
A serde attribute `deserialize_curve_key_vec`  was missing.
Signed-off-by:
=> crypto: fix BackedUpRoomKey Serialization

crates/matrix-sdk/src/event_cache/linked_chunk.rs, crates/matrix-sdk/src/event_cache/store.rs
Those patches have been cherry-picked from https://github.com/matrix-org/matrix-rust-sdk/pull/3230. It's a collection of tiny improvements or bug fixes for `LinkedChunk`. More have been added after that. It's best to review them one by one.
=> fix(sdk): Various tiny improvements for `LinkedChunk`

crates/matrix-sdk-crypto/src/store/memorystore.rs
Because I am trying to get `MemoryStore` to pass the `cryptostore_integration_tests`, I need this store to hold on to the private identity when previously it didn't both.
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3221
Part of my work on https://github.com/element-hq/element-web/issues/26892
=> crypto: Save private identity in the MemoryStore

crates/matrix-sdk/src/event_cache/linked_chunk.rs
Imagine we have this linked chunk:
```rust
assert_items_eq!(linked_chunk, ['a'] [-] ['b', 'c'] ['d', 'e', 'f']);
```
Before the patch, when we were running:
```rust
let position_of_d = linked_chunk.item_position(|item| *item == 'd').unwrap();
linked_chunk.insert_gap_at((), position_of_d)?;
```
it was taking `['d', 'e', 'f']` to split it at index 0, so `[]` + `['d', 'e', 'f']`, and then was inserting a gap in between, thus resulting into:
```rust
assert_items_eq!(linked_chunk, ['a'] [-] ['b', 'c'] [] [-] ['d', 'e', 'f']);
```
The problem is that it creates a useless empty chunk. It's a waste of space, and rapidly, of computation. When used with `EventCache`, this problem occurs every time a backpagination occurs (because it executes a `replace_gap_at` to insert the new item, and then …
=> feat(sdk): Optimise how `LinkedChunk::insert_gap_at` works when inserting at first position

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/pusher.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3096
I chose to create a new method for delete pusher because Ruma defines a delete action itself.
Signed-off-by: @hanadi92
=> sdk/ffi: ability to delete a pusher

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk-crypto/src/verification/machine.rs
`TryFrom` and `TryInto` are imported redundantly. They are already defined in `core::prelude::rust_2021` which is automatically imported. This is generating warnings on my side. This patch fixes that.
=> chore: Avoid importing types redundantly

bindings/matrix-sdk-ffi/src/room_directory_search.rs
Up until uniffi 0.26 it was not possible to send objects across the boundary unless they were wrapped in an `Arc<>`, see https://github.com/mozilla/uniffi-rs/pull/1672
The bindings generator used in complement-crypto only supports up to uniffi 0.25, meaning having a function which returns objects ends up erroring with:
```
error[E0277]: the trait bound `TaskHandle: LowerReturn<UniFfiTag>` is not satisfied
--> bindings/matrix-sdk-ffi/src/room_directory_search.rs:109:10
|
109 |     ) -> TaskHandle {
|          ^^^^^^^^^^ the trait `LowerReturn<UniFfiTag>` is not implemented for `TaskHandle`
|
= help: the following other types implement trait `LowerReturn<UT>`:
<bool as LowerReturn<UT>>
<i8 as LowerReturn<UT>>
<i16 as LowerReturn<UT>>
<i32 as LowerReturn<UT>>
<i64 as LowerReturn<UT>>
<u8 as …
```
=> uniffi: wrap TaskHandle up in an Arc<>

crates/matrix-sdk/src/event_cache/linked_chunk.rs
Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/3251#discussion_r1532103818.
1. As suggested by @poljar, it is possible that the
value of the atomic changes between the `fetch_add` and the `load` (if
and only if it is used in a concurrency model, which is not the case
right now, but anyway… better being correct now!). The idea is not
`load` but repeat the addition manually to compute the “current” value.
2. Makes `ChunkIdentifierGenerator::generate_next` to panic
if there is no more identifiers available. It was previously returning
a `Result` but we were doing nothing with this `Result` except
`unwrap`ping it. To simplify the API: let's panic.
=> feat(sdk): Improve `ChunkIdentifierGenerator`

crates/matrix-sdk-crypto/src/store/integration_tests.rs
A couple of small changes that allow us to drop locks that would otherwise persist when running the tests over the MemoryStore, and some documentation comments for assertions to make it easier to spot which assertion failed, even though we are inside a macro.
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3222
Part of my work on https://github.com/element-hq/element-web/issues/26892
=> crypto: Refactor integration tests in preparation for them running against MemoryStore

bindings/matrix-sdk-crypto-ffi/src/device.rs
This patch changes seconds to milliseconds for the description of `Device::first_time_seen_ts`.
---
* Close https://github.com/matrix-org/matrix-rust-sdk/issues/3213
=> doc(crypto-ffi): `Device::first_time_seen_ts` has an incorrect unit

.github/workflows/coverage.yml
It appears that tarpaulin complains if the symbol information is stripped from the binary, and [as of Rust 1.77](https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default), `debug=0` causes Cargo to strip all debug info, leading to errors like:
```
2024-03-21T15:30:52.521627Z ERROR cargo_tarpaulin::test_loader: Error parsing debug information from binary: An I/O error occurred while reading.
2024-03-21T15:30:52.521653Z  WARN cargo_tarpaulin::test_loader: Stripping symbol information can prevent tarpaulin from working. If you want to do this pass `--engine=llvm`
2024-03-21T15:30:52.524745Z ERROR cargo_tarpaulin: Error while parsing binary or DWARF info.
2024-03-21T15:30:52.534462Z  INFO cargo_tarpaulin::process_handling::linux: Launching test …
```
=> Enable debuginfo for tarpaulin builds.

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
The test has been failing with a timeout recently, several time. Let's see if it was a fluke caused by the low threshold (because the server might be busy handling other requests from other tests), or an actual issue.
I don't repro the failure locally with my test coverage setup, so let's see if it's just about waiting a bit longer.
=> tests: try bumping the timeout duration in `test_room_notification_count`

crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs
The previous API relied on the callers not forgetting about adjusting day dividers after handling an event.
This makes it statically impossible, by requiring that `TimelineEventHandler` takes an unused `&DayDividerToken` when operating. The only way to get a `DayDividerToken` is by creating a `DayDividerAdjuster`, so that we know there's one in scope that will be used later.
Additional checks are added to the `DayDividerAdjuster`, to make sure the adjuster is effectively called when needed.
=> day divider: make it impossible to handle an event without adjusting day dividers

crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs
Local echoes (which haven't received a remote echo yet) can have no event id, so when computing the report, don't unwrap the event id but use a sensible default instead.
Also tweaks comments from a previous version of another PR. And rename `DayDividerAdjuster::maybe_adjust_day_dividers` to `run`.
=> day divider: don't assume events have event id

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs
Closes #3265.
There is currently no way to get the URL of a homeserver's sliding sync proxy before logging in on the homeserver.
I suggest exposing the URL via the `HomeserverLoginDetail` struct after configuring the homeserver (through `configure_homeserver`).
Since the homeserver may not declare a corresponding sliding sync proxy, this value is an `Optional`. It is used later in `configure_homeserver` to check if a sliding sync proxy exists and throws an error otherwise. Previously, this check was done against the client's `discovered_sliding_sync_proxy` function.
---
Signed-off-by: Thomas Völkl <thomas@vollkorntomate.de>
=> ffi: Expose discovered sliding sync proxy URL

crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs
Make a simple wrapper for `MemoryStore` so that we can run the crypto store integration tests against it.
Also requires a little build fix to make sure the `testing` module is available when we are running in `test` mode but have not enabled the `testing` feature.
Also, now that the `cryptostore_integration_tests` and `cryptostore_integration_tests_time` macros are used in the default build, we can rustfmt them and see any warnings \o/
Part of https://github.com/element-hq/element-web/issues/26892
=> crypto: Run the crypto integration tests against MemoryStore

crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs
When removing or replacing a previous item that was a day divider, we assumed it was always at the immediate previous position (i - 1 in the loop). That's not correct, because there could be other items unrelated to the day divider algorithm in between (like a read marker), so it would fail the previous assertion.
The regression test (that fails on current main) shows the required setup:
0. event @ ts X
1. day divider @ ts X+1day
2. read marker
3. event @ ts X
When seeing the event, we decided to remove the "previous" day divider that was spurious, and assumed it was at position 2, while it was at position 1. The solution is to keep track of the actual index of the previous item, in addition to the previous item itself.
Also, I've lowered the severity of the check, from an assertion to an …
=> day dividers: don't assume a previous item is at the immediate previous position

.gitignore, Cargo.lock, crates/matrix-sdk-base/src/rooms/normal.rs, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-integration-testing/src/tests/reactions.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This PR adds logs to `test_toggling_reactions`, which fails and we don't really understand why (although we suspect some low-level tokio issue — which might just be a fallout from a timeout).
Also, this makes the `test_room_notification_count` test much more robust: instead of just waiting for `RoomInfo` updates, it now contains some assertions related to those updates. During debugging, I've used a cute hack to see how the `RoomInfo` updates were evolving over time: every time we'd receive an update, we'd store it, so the next time we can compute a (JSON) diff of the two updates. This helped understanding why sometimes an assertion was failing, or in a few places, it showed me that I thought something was happening but it was completely unrelated, and the update was about something …
=> ci: Fix flakey integration test failures

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine.rs
Turns out this is useful for https://github.com/element-hq/element-meta/issues/2313.
=> crypto: Add `OlmMachine::device_creation_time`

crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/store.rs, crates/matrix-sdk/tests/integration/event_cache.rs
`EventCache` uses a custom `EventCacheStore` trait to store all events for all rooms.
The idea of this PR is to use the newly introduced `LinkedChunk` in https://github.com/matrix-org/matrix-rust-sdk/pull/3166. Instead of having one store for all events for all rooms, now there is one `LinkedChunk`/store per room.
Of course, @bnjbvr and I are discussing a lot, which explains why the actual `EventCacheStore` was already adopting some patterns from `LinkedChunk`. The migration was easier.
Several PR were necessary to make this work possible:
Briefly, this PR removes the `EventCacheStore` and the `MemoryStore`, and replace them by `LinkedChunk`.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3058
=> feat(sdk): `EventCache` fully uses `RoomEvents`/`LinkedChunk`

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk/src/event_cache/mod.rs
This is a relatively simple change: this moves handling the fully read marker for a given room into the event cache, so listeners can react to a specific event for that, instead of handling themselves all the account data changes.
Not sure if that's a better API than just returning all the account data changes, so I would love feedback on this. At least it's sufficient for the UI timeline use case, and so it seems sufficient right now (and we could make it different later).
Part of #3058.
=> event cache: internalize handling of the account data

crates/matrix-sdk/src/event_cache/linked_chunk.rs
This patch fixes a bug when inserting items at the end of the current items of a chunk. The condition was: `if item_index >= current_items_length`, which is too restrictive. The bug was “hidden” so far because it's not possible to get the position of “after an item” with the current API. However, the bug arises if the items are empty and new items are inserted at the position index 0 (index = 0, length = 0).
The fix consists of relaxing the condition, and introducing an optimisation. If we insert at the end, we do a simple push (like an append). If we insert at another position, we split, then push the new items, and finally push the detached items (as it was the case before).
The tests have been updated accordingly.
---
* Fix https://github.com/matrix-org/complement-crypto/issues/43
=> fix(sdk): Fix `LinkedChunk::insert_items_at`

crates/matrix-sdk-base/src/client.rs
This reverts commit 99e47ed5d7750bb65e271ad2361c9dbbb46d7914, for the following reasons:
- it's easy for a sender to put arbitrary content in the `m.room.member` event content for the person they're inviting, so the previous code, while uncommented, was a measure against abuse. I've added a comment in a separate commit there.
- I've written a test in #3283 for what I thought #3278 was fixing, but it's passing even after reverting #3278, so the test isn't showing what's getting fixed, and it's not clear as a result what the PR was fixing. We should identify that first, before writing a blind fix like this.
cc @stefanceriu
=> Revert "fix: Process profiles for all room members not only state event senders (#3278)"

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs
@stefanceriu This adds a test for #3277, but it passes even if I revert your commit, so I'm not too sure what your PR fixes; would you be interested in adding commits to this PR until the test is a regression test (aka it fails before your patch, it passes after your patch)? (also we should consider reverting #3277, because it's likely wrong — see last comment I've posted there)
Anyhow, this PR contains a few cleanups that I've made while digging into code related to all of this. `MemberRoomInfo` seems super shady in terms of performance: it's computed in `member_room_info()`, which takes twice the same RW lock and does 3 DB requests; this method is called once per `get_member`; and `get_member` is sometimes called in loops. Oh well, fun for another day.
=> sdk(base): misc refactorings + a test for #3277

bindings/matrix-sdk-ffi/src/room.rs
Prompted by https://github.com/element-hq/element-x-ios/issues/2618 but also because we know the permalinks iOS creates don't include via parameters and are basically wrong.
=> ffi: expose room and event matrix.to permalink builder methods

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk/src/oidc/registrations.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, examples/image_bot/src/main.rs, examples/login/src/main.rs, examples/timeline/src/main.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
I am guessing these are new clippy lints in nightly.
I have a bunch of other warnings (27 currently) that I didn't fix because they seem a bit pedantic to me, so I'm not sure if they are wanted (but I would love to see all the warnings go away):
- https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones, in a lot of places, for example at: https://github.com/matrix-org/matrix-rust-sdk/blob/29f7f88a2c527eacae71cfbcfaeacd785a37f3c2/crates/matrix-sdk-base/src/client.rs#L422
- https://rust-lang.github.io/rust-clippy/master/index.html#mixed_attributes_style, for example at: https://github.com/matrix-org/matrix-rust-sdk/blob/29f7f88a2c527eacae71cfbcfaeacd785a37f3c2/crates/matrix-sdk-crypto/src/identities/device.rs#L980-L983
- …
=> Fix some clippy warnings

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs
See description commit by commit.
This fixes #3277.
=> base: remove previous profiles of a member when they're reinvited

crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/item.rs
When updating the send state of a message, we manually got rid of a day divider, before this patch. Now we let the algorithm run, as we do everywhere else. Also fixes an issue in the algorithm where the final item could be a day divider, and we'd never remove it (since we remove them only when we notice they're a spurious *previous* day divider) — maybe the algorithm could be changed to just do some linear logic with an iterator, but who cares, it's still O(n) with n = number of timeline items.
=> timeline: Use day divider when updating send state

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/client/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3290
This PR add support for tracking the users recently accessed rooms on device, within the state store (potentially encrypted). It does so by exposing 2 new methods on the client/account:
* `track_recently_visited_room` which takes a roomId, validates that it's a valid one, and then updates the ordered (by recency) **set** of stored rooms, capping it at a predefined **20** (inspired by element web's `im.vector.setting.breadcrumbs` which seems to work great in practice)
* `get_recently_visited_rooms` which will just return an array of room identifiers as strings
There's also a test that should properly check this whole behavior.
You can see it all in action within Element X here …
=> feat: add support for storing breadcrumbs in the state store

bindings/apple/Tests/MatrixRustSDKTests/ClientTests.swift, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs
I believe that all async methods called from AuthenticationService's API are now ported away from `RUNTIME.block_on`.
=> ffi: Use async functions in `AuthenticationService`

crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This way, we're sure that a (UI) timeline will always have access to the `m.room.create` event, and thus get the proper room version, resulting in more correct room redactions (IIUC). It will also avoid causing all the WARN logs in rageshakes, as mitigated by #3299 (which is a nice improvement in separation IMO).
Alternative implementations:
- require the caller to `matrix_ui::...::Room::subscribe()` to pass the proper creation event: this is a bit cumbersome (would require one PR against both EX apps, for my use case), but overall I find this API cumbersome because it shouldn't be the caller's responsibility to specify which events are *required*. The room list service code is opinionated, and it should be fine that the SDK requires some events that are mandatory for it to work well, and …
=> room list service: always include the `m.room.create` state event in a room subscription

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk/src/event_cache/mod.rs
There were cases in the wild of a (UI) timeline lagging behind updates sent from a `RoomEventCache`. The previous buffer size was 32, which I thought would be sufficient for anyone, but with more `RoomEventCacheUpdate` added recently (notably: the read marker update, or, the timeline update code might have gotten slower recently), it might need to get a bit bigger. Let's see if this helps, as a first measure.
Also add more logs and better handle the event cache lagging behind room updates; this would be catastrophic if it happened, so we need to get some logs, at the very least. See details in commit messages.
=> event cache: increase the buffer's size for listeners to `RoomEventCache`

crates/matrix-sdk/Cargo.toml
I noticed that we had uniffi crates in our `Cargo.lock` in Fractal, while we shouldn't.
=> sdk: Enable matrix-sdk-base uniffi feature conditionally

crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk/src/room/messages.rs, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/src/tests.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs
`Room::event_with_context` now returns a wrapper over the server response, containing all the previous data, and the next/prev batch tokens now, as well as decrypted events before/after the target event itself.
Also add an integration test for `/context` queries, with a few examples of continuing backwards/forwards pagination.
Part of #3234.
=> room: improve `event_with_context` to decrypt all prev/next events

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
As outlined in https://github.com/element-hq/element-web/issues/26892#issuecomment-1961271348 , pass in the backup version we mean when we call `inbound_group_sessions_for_backup` and `mark_inbound_group_sessions_as_backed_up`. This will allow us to switch smoothly to a new backup version when the user asks to reset it, instead of modifying lots of records in our DB when this happens.
Fixes https://github.com/element-hq/crypto-internal/issues/206
=> crypto: Add a backup_version argument to group session backup methods

crates/matrix-sdk-ui/src/timeline/read_receipts.rs
Those two issues really aren't errors we should be too scared of:
- on the one hand, they don't prevent correct usage of the timeline, but slightly decrease the UX's quality
- on the other hand, they may indicate that read receipts haven't been received yet, OR some events are unknown (can be happening if the previous read receipt refers to an event the timeline doesn't know about).
So I lowered their severity to debug instead of error, since only outstanding issues should errors or warnings in my opinion.
=> timeline: lower log severity of read receipts issues

Cargo.lock, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk/Cargo.toml
Even if they are breaking releases, the upgrade seems pretty transparent.
=> Upgrade qrcode and image dependencies

crates/matrix-sdk-ui/src/sync_service.rs
We do see lots of "broken channel" log lines for these two log statements, and since I'm unclear why they happened, I'd like to add a bit more logging to those.
Also makes the log level consistent, both are set to "warn" instead of one warn and one error. Usually it's not a big deal because the only error that may happen is that the channel is broken, indicating the task died before, so there's no need to stop it manually.
=> sync service: show the termination report debug info in the error logs

crates/matrix-sdk/src/event_cache/mod.rs
This protects against the sliding sync proxy (or synapse) sending lots of duplicate fully read marker events for the same room in case of reset. This would lead to forwarding lots and lots of `RoomEventCacheUpdate`s to the timeline, cluttering the channel, and resulting in a lag. This lag would then clear the timeline, seemingly cause missing chunks from history.
I've also lowered the size of the channel again, because we shouldn't need a buffer of 128 updates anymore.
https://github.com/matrix-org/matrix-rust-sdk/pull/3312 is likely the long term fix (after a clear(), the timeline should retrieve all the memoized events from the event cache), but this should prevent the root cause of the spamming in the first place, getting us back to a safe state.
=> event cache: forward at most one read marker update per `JoinedRoomUpdate`

bindings/matrix-sdk-ffi/src/room_member.rs, bindings/matrix-sdk-ffi/src/ruma.rs
- expose method for generating user `matrix.to` permalinks
- expose method for parsing Matrix URIs and converting them into actual Matrix entities (for both `matrix.to` links as well as actual URIs)
=> ffi: expose methods for creating user permalinks and parsing Matrix URIs

crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/test_utils.rs, crates/matrix-sdk/src/test_utils/events.rs, crates/matrix-sdk/tests/integration/event_cache.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs
This introduces a new helper object to run arbitrary pagination requests, backwards- or forward-. At the moment they're disconnected from the event cache, although I've put the files there for future convenience, since at some point we'll want to merge the retrieved events with the cache (? maybe).
This little state machine makes it possible to retrieve the initial data, given an initial event id, using the /context endpoint; then allow stateful pagination using a paginator kind of API. Paginating in the timeline indicates whether we've reached the start/end of the timeline.
The test for the state subscription is quite extensive and makes sure the basic functionality works as intended.
Some testing helpers have been (re)introduced in the SDK crate, simplifying the code, and introducing a …
=> event cache: introduce the `Paginator` API

crates/matrix-sdk-base/src/sliding_sync.rs
A kick/ban event has the sender key and the state key defined to different values. The banner/kicker is the actual sender. Sliding sync considered they had to be the same for the event to be legit, but it's not the case. Thanks @ganfra for showing me actual events sent from the sliding sync proxy, which made the bug in the SDK obvious.
Contains a regression test.
Fixes #3315.
=> sliding sync: don't exclude room membership events sent by other users

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
This fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3110
=> bugfix: ensure the SessionStore is cleared when regenerating the OlmMachine

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs
Fixes #3311.
When the timeline is lagging behind the event cache, it should not only clear what it contains (because it may be lagging some information coming from the event cache), it should also retrieve the events the cache knows about, and adds them as if they were "initial" events.
This makes sure that the event cache's events and the timeline's events are always the same, and that, in the case of a lag, there won't be any missing chunks (caused by the event cache back-pagination being further away in the past, than what's displayed in the timeline).
The lag behind a bit too hard to reproduce, I've not included a test here; but I think this should be the right move.
=> timeline: after an event cache update lag, fetch previous events back from the cache

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room_preview.rs, crates/matrix-sdk/src/http_client/native.rs, crates/matrix-sdk/src/room_preview.rs, crates/matrix-sdk/tests/integration/matrix_auth.rs, testing/matrix-sdk-integration-testing/assets/ci-start.sh, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This adds support for MSC3266 when fetching a room preview, for servers that support it. If the server doesn't support it, we resort to using the room state event endpoint.
Pretty sure the integration testing in CI will hate this, since I'm unit-testing the `from_room_summary` method, which requires an experimental feature to be enabled on the synapse service. If that's the case, I'll disable this test.
Using a fork of Ruma to cut corners, since the review of the feature there is getting complicated. Maybe https://github.com/ruma/ruma/pull/1776 will get approved some day soon :smiling_face_with_tear:
=> room preview: use the room summary MSC3266 endpoint

crates/matrix-sdk/src/event_cache/paginator.rs
Does what it says on the tin. Mostly test changes.
Supports https://github.com/matrix-org/matrix-rust-sdk/issues/3234
=> paginator: select how many events to retrieve during initial /context and pagination queries

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/traits.rs
:warning: This is preventing timelines to be built with read marker support, if there was a fully read marker event stored in the database.
The `state` lock was taken at the top level of this function, and indirectly implicitly in the `set_fully_read_event` function. This fixes it, and adds a regression test.
=> timeline: prevent deadlock in `replace_with_initial_events`

crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
In https://github.com/matrix-org/matrix-rust-sdk/pull/2691, I suppose
the way `add_mentions` is computed is… wrong. [`AddMentions`](https://docs.rs/ruma/latest/ruma/events/room/message/enum.AddMentions.html) is used to
automatically infer the [`m.mentions`](https://spec.matrix.org/v1.10/client-server-api/#definition-mmentions) of the reply event based on the
replied event. The way it was computed was based on the reply event
`mentions`, which seems wrong: if the reply contains mentions, then the
sender should be part of it? Nah. That's a bug. We want the reply event
to automatically mention the sender of the replied event if and only
if it's not the same as the current user, i.e. the sender of the reply
event.
This patch fixes the `add_mentions` calculation. This patch also updates
a test …
=> fix(ui): `Timeline::send_reply` correctly sets up `m.mentions`

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs
`Room::invite_details()` can return an error if the room member event (the invite) is missing from the store. Usually that would be a sign that the state is semi-broken, since there should always be such an event for an invited room. But if it's missing, it shouldn't break the creation of a `RoomInfo`, and just be missing from the struct.
Also, setting the `inviter` field to `None` when `Room::invite_details()` returned an error is consistent with the FFI `Room::inviter()` function which also returns `None` in that case.
=> ffi: don't abort RoomInfo creation if the room member invite event is missing

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs
Follow-up to 13cc7962. Same thing would happen when populating the initial user receipts, with the `populate_initial_user_receipt` re-attempting to take the state lock while it was already taken.
Includes a regression test.
=> timeline: prevent deadlock in `populate_initial_user_receipt`

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs
And don't assume inserting to the end means it's coming from sync — as it won't be true for forward pagination anymore.
Supports https://github.com/matrix-org/matrix-rust-sdk/issues/3234, extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3329.
=> timeline: include the remote event's origin in the timeline position/end

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/encryption/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3130
This allows providing encryption settings while constructing a client via FFI, instead of hard-coding specific values.
We do it by holding on to an `EncryptionSettings` inside `ClientBuilder` and updating it when certain methods on the builder are called. During `build_inner()` we provide those `EncryptionSettings` by calling `with_encryption_settings` on `inner_builder`.
I added an enum `BackupDownloadStrategy` to be passed as an argument to `backup_download_strategy`. Let me know if there's a better way.
=> ffi: Expose encryption settings via FFI

bindings/matrix-sdk-ffi/src/sync_service.rs, bindings/matrix-sdk-ffi/src/timeline/content.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-crypto/src/types/events/mod.rs, crates/matrix-sdk-crypto/src/types/events/utd_cause.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
We want to decorate messages we can't decrypt based on _why_ we can't decrypt them. This PR detects the `membership` info provided if the server implements [MSC4115](https://github.com/matrix-org/matrix-spec-proposals/pull/4115) and provides that feedback to the client via the `UtdCause` enum, which we expect to expand in the future.
=> crypto: UtdCause enum in reporting hooks and encryption event

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/main.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs, labs/multiverse/src/main.rs
Fixes #3234.
See the commit message of the first commit for more details. This is sufficient to implement pagination in the timeline.
=> timeline: add event focus mode for permalinks

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_member.rs
Whilst the FFI currently supports creating a matrix.to room alias link directly from a `Room`, there isn't a way to do so when you already have one as a string. This PR fixes that by adding a global `matrix_to_room_alias_permalink` method similar to the existing `matrix_to_user_permalink` method. (This is only useful against an alias, as a plain room ID doesn't provide enough info to construct the URL with the necessary via parameters).
=> FFI: Allow the creation of a matrix.to link for any room alias.

.cargo/config.toml
The clippy website explains that `Box::new(Default::default())` can be shortened to `Box::default()` and that it's more readable. That's true… when you don't have a generic parameter in the mix (which may be required if rustc can't infer the type of the boxee), in which case it just looks bad, e.g. `Box::<MyType>::default()` instead of `Box::new(MyType::default())`.
I do strongly prefer the latter, and propose to get rid of the lint, as a result.
=> clippy: disable the box_default lint

.cargo/config.toml, Cargo.toml, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/messages.rs
This makes all the requests (/context and /messages) cancellation-safe by making two changes:
- first, use sync locks instead of async locks for the prev/next batch tokens. This ensures that we can't get cancelled after receiving a response and managing internal state, i.e. we keep run-to-completion semantics until the end of the function, once we got a response.
- second, introduce a RAII guard that will reset the state to a given value when dropped. Then use this to reset the state to Initial (resp. Idle) in /context (resp. /messages) when the async call is aborted. We use `mem::forget` once the response has been returned, so as to not call the `Drop` implementation of the guard later on.
A regression test has also been introduced.
Part of …
=> paginator: reset the paginator's state if the task is cancelled

Cargo.lock, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/oidc/auth_code_builder.rs, crates/matrix-sdk/src/oidc/cross_process.rs, crates/matrix-sdk/src/oidc/data_serde.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/src/oidc/tests.rs, examples/oidc_cli/src/main.rs
The well-known method is deprecated.
This removes some tests on methods that were previously only getters but now make a request to the auth issuer.
Tested the example CLI to work with the OIDC playground. Element X should probably be tested with other deployments to confirm this. There should be no code changes needed with the FFI bindings.
=> sdk: Use the `GET /auth_issuer` endpoint for OIDC

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/platform.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/http_client/http_helpers.rs, crates/matrix-sdk/src/http_client/mod.rs, crates/matrix-sdk/src/oidc/backend/mock.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
They need to be updated together because the latters depend on the former.
matrix-authentication-service is still using http 0.2 so we need to add a conversion layer between both major versions for OIDC requests for now.
We need to update vodozemac too because of a dependency resolution issue.
=> Upgrade http, ruma, reqwest and wiremock dependencies

Cargo.lock, examples/oidc_cli/Cargo.toml, examples/oidc_cli/src/main.rs
Something went wrong while #3305 was merged. This fixes the issue introduced by the github rebase.
=>  oidc: Use the correct types to compare the status codes in the oidc example

crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs, crates/matrix-sdk/src/event_cache/paginator.rs
Repetition of https://github.com/matrix-org/matrix-rust-sdk/pull/3359 but at a different layer: the timeline has its own observable state for a back-pagination status, and we should *also* reset it when using back-pagination on a live timeline.
Instead of doing this, we should probably have the status + the pagination being handled in the event cache, using the new Paginator API, but that's a bigger change that I'm working on, and it changes many many public APIs related to the event cache, so I'm slightly postponing that and instead I propose to get this simpler fix merged.
Part of #3355.
=> timeline: reset pagination status if a live back-pagination is aborted

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-store-encryption/src/lib.rs, crates/matrix-sdk/Cargo.toml
base64 now matches the version used in ruma and vodozemac.
I saw other possible upgrades but they created duplicate entries in `Cargo.lock`, so I tried to be conservative, and ended up only upgrading ~~this one~~ these.
Edit: It turns out I missed the update of async-channel which allows to update event-listener too.
=> chore: Upgrade dependencies

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/tests/integration/room/common.rs, examples/oidc_cli/src/main.rs, examples/persist_session/src/main.rs
Reverts a few changes of https://github.com/matrix-org/matrix-rust-sdk/pull/3368, and also simplify / add more comments / etc.
One notable change: in `Room`, `RoomInfo` and `RoomListItem`, the `name()` method will now always return the computed display name only, and not alternate between the computed display name and the raw name from the room state event. Let me know if that's something we don't want.
=> ffi: revert some functions back to sync

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
The builder had only one meaningful method, `filter_by_push_rules`, which was always called by the applications — and in fact should always be true. It was designed as an extra method because it was experimental at the time, but it's stabilized sufficiently that we can enable this behavior by default now, considering that a notification that is not wanted by the user shouldn't be kept, to respect their intent. (This is in the UI crate, which is opinionated, so it's fine to assume such intents by design.)
=> notification client: get rid of builder

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs, crates/matrix-sdk/tests/integration/room/common.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/room/notification_mode.rs, crates/matrix-sdk/tests/integration/room/tags.rs
I am in `--pedantic` mode today.
=> tests: rename ev_builder to sync_builder + add test_ prefix to test functions

Cargo.lock, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk-store-encryption/src/lib.rs
This patch removes the `displaydoc` dependency. Why?
1. It creates a warning in rustc nightly:
```
warning: non-local `impl` definition, they should be avoided as they go against expectation
--> crates/matrix-sdk-store-encryption/src/lib.rs:49:17
|
49 | #[derive(Debug, Display, thiserror::Error)]
|                 ^^^^^^^
|
= help: move this `impl` block outside the of the current constant `_DERIVE_Display_FOR_Error`
= note: an `impl` definition is non-local if it is nested inside an item and may impact type checking outside of that item. This can be the case if neither the trait or the self type are at the same nesting level as the `impl`
= note: one exception to the rule are anon-const (`const _: () = { ... }`) at top-level module and anon-const at the same nesting as the trait or type …
```
=> fix(store-encryption): Remove the `displaydoc` dependency

crates/matrix-sdk/src/event_cache/linked_chunk.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/store.rs
This patch introduces `LinkedChunkUpdate` and `LinkedChunk::updates(&mut self) -> &mut Vec<LinkedChunkUpdate>`. It's a new mechanism that is used by `LinkedChunk` in order to get a list of all updates that happened in a `LinkedChunk`. This is the fundamental piece to write a persistent storage for `LinkedChunk`, and thus for `EventCache`, see #3280 to learn more.
---
=> feat(sdk): Introduce `LinkedChunkUpdate`

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/README.md, bindings/matrix-sdk-ffi/src/platform.rs
This patch removes support for OpenTelemetry in `matrix-sdk-ffi` because it's not used anymore by anybody. It also adds multiple duplicated dependencies (like `reqwest`). Anyway. Farewell.
Removing opentelemetry removes axum 0.6.20, hyper-timeout, reqwest 0.11.20, tokio-timeout, tonic and winreg.
=> chore(ffi): Remove support for opentelemetry

bindings/matrix-sdk-crypto-ffi/src/device.rs
Wanted to use dehydrated devices in our application and noticed the `dehydrated` flag is not exposed in the FFI bindings for use.
Signed-off-by:
=> ffi: Added dehydrated flag to Device

crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/types/cross_signing/master.rs, crates/matrix-sdk-crypto/src/types/cross_signing/self_signing.rs, crates/matrix-sdk-crypto/src/types/cross_signing/user_signing.rs
Since the master/self-signing/user-signing public key types are used for public user identities as well as for the private key type we have, and we'd like to sign the public key types it makes sense that the types itself aren't using an Arc.
Let's instead put the Arc inside the user identity structs.
This will allow us later on to more easily sign the public key types.
=> chore(crypto): Refactor the cross-signing key wrappers

.github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/documentation.yml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-base/build.rs, crates/matrix-sdk-common/build.rs, crates/matrix-sdk-crypto/build.rs, crates/matrix-sdk-indexeddb/build.rs, crates/matrix-sdk-sqlite/build.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/build.rs, crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/build.rs, crates/matrix-sdk/src/sliding_sync/README.md, xtask/src/main.rs
Includes fixes for:
- Warnings when using `default_features` instead of `default-features` in `Cargo.toml`: Cargo says that it will not be supported anymore in the upcoming 2024 edition
- Errors with `cfg` options: Cargo now [checks cfgs at compile-time](https://blog.rust-lang.org/2024/05/06/check-cfg.html), which means that custom options need to be declared in build scripts. It also detects cargo features used in code that do not exist in the manifest.
=> ci: Bump version of rust nightly

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
Our main use case for this in Fractal is to check if there is a intentional room mention in the message to see if we need to try to look for `@room` in the text to replace it with a visual aid.
This has another benefit for edits: the users that were mentioned in the original event are not supposed to be mentioned again when sending an edit. Ruma takes care of that, but only if the original mentions are provided, which is now the case.
I didn't add the mentions in `Message::to_content()` because in both cases where it the method is called it would be unused.
=> ui: Expose message mentions

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/test_utils/events.rs, crates/matrix-sdk/tests/integration/event_cache.rs
This should "fix" ignoring/unignoring users, which had regressed likely since the introduction of the event cache.
This is still not perfect: in theory the sliding sync room cache should *also* be emptied every time we get an ignored/unignored change, but better to wait for https://github.com/matrix-org/matrix-rust-sdk/pull/3092 to land, instead of trying to work around it somewhere else.
Part of #3058, should help with https://github.com/element-hq/element-meta/issues/2382 too.
=> event cache: handle blocking correctly

Cargo.lock, Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/encryption/futures.rs, testing/matrix-sdk-integration-testing/Cargo.toml
As the title says!
This PR updates the dependencies. It also removes `cfg_vis` from `matrix-rust-sdk` because that's pretty useless if I understand what it was supposed to do. It was also introducing more proc-macros and a duplicated dep with Ruma.
=> chore(cargo) Update dependencies

.github/workflows/ci.yml, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests.rs, testing/matrix-sdk-integration-testing/src/tests/nse.rs
Adds a test that fails before https://github.com/matrix-org/matrix-rust-sdk/pull/3338 and passes afterwards.
Tests the fix for https://github.com/matrix-org/matrix-rust-sdk/issues/3110
The test sets up a cross-process lock and 2 clients using it, then makes sure they both have Olm sessions with a 3rd client, before sending from one of them and checking that the other can still receive. This validates that it flushed and replaced its Olm session with the 3rd client.
=> crypto: Add a standalone integration test for the NSE race

crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs
This ensures the room name is deterministic, when it's computed client-side. Includes regression tests too, where the members or heroes might not be in the expected order.
=> base: sort the heroes in the computed display name alphabetically

.github/workflows/ci.yml, .github/workflows/coverage.yml, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
And re-enable the room preview test in integration testing.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3340 (although it doesn't use a standard synapse image, it makes it so that we don't need such a thing).
=> ci: use the latest synapse-service image with msc3266

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk/src/test_utils/events.rs
=> timeline: reuse internal id when adding pending replied-to details to an item

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/types/mod.rs, crates/matrix-sdk-crypto/src/types/qr_login.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk/Cargo.toml, examples/backups/Cargo.toml, examples/cross_signing_bootstrap/Cargo.toml, examples/emoji_verification/Cargo.toml, examples/get_profiles/Cargo.toml, examples/image_bot/Cargo.toml, examples/login/Cargo.toml, examples/oidc_cli/Cargo.toml, examples/secret_storage/Cargo.toml, examples/timeline/Cargo.toml, labs/multiverse/Cargo.toml
This is the first part of [MSC4108] support, it just adds the basic parsing and encoding parts for the data which will be present in QR codes for [MSC4108].
[MSC4108]: https://github.com/matrix-org/matrix-spec-proposals/pull/4108
=> Parsing of QR codes from MSC4108

.github/workflows/bindings_ci.yml, xtask/src/swift.rs
Currently `cargo xtask swift build-framework` lets us either build a single target, or all supported targets. This PR allows to pass `--target triple-1 --target triple2` to build a subset of the supported targets.
=> xtask: Allow passing multiple targets to Swift's build-framework.

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/CHANGELOG.md, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
That way the API is closer to that of `send_reply`.
=> ui: Make Timeline::edit take a RoomMessageEventContentWithoutRelation

crates/matrix-sdk-ui/CHANGELOG.md, crates/matrix-sdk-ui/src/timeline/futures.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
I found the previous API confusing. Firstly, the parameter name was "filename" when we want a file path. Secondly, we take a `String` when we want a `Path` (or `PathBuf` to get an owned value here).
=> ui: Take a `PathBuf` to send an attachment

Cargo.lock, Cargo.toml
This gives us the necessary primitives for the QR code login feature. This is being merged sooner because we have all the necessary bits for the WASM bindings EW needs.
=> chore: Bump the vodozemac version

crates/matrix-sdk-crypto/CHANGELOG.md
This is part of the `0.7` release branch but was not backported here.
=> chore(crypto): Add a missing changelog entry

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room_preview.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room_preview.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
=> room preview: allow passing through a list of servers to discover a room with MSC3266

bindings/matrix-sdk-ffi/src/timeline/content.rs
This is useful to properly format membership state events.
=> ffi: Add the user's display name to `RoomMembership` timeline content

crates/matrix-sdk-ui/src/timeline/day_dividers.rs
See individual commit messages.
Fixes #3412. Thanks again @stefanceriu for the report!
=> day divider: don't attempt to replace a day divider scheduled for removal

bindings/matrix-sdk-ffi/src/encryption.rs, crates/matrix-sdk/src/encryption/mod.rs
The Element-X rageshakes are lacking device keys info, see https://github.com/element-hq/element-x-ios/issues/2550
This change exposes these so that it can be used by the app.
The `ed25519_key()` was already present in the sdk but not exposed in bindings. I added a second one for `curve25519_key()` in both sdk and bindings.
Can be accessed via `client.encryption().curve25519Key()` in the aps
Signed-off-by:
=> FFI: Expose ed25519/curve25519 keys in bindings

bindings/matrix-sdk-ffi/src/notification.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
And don't rely on the `name` field in the response as provided by the server. The name displayed by the server was before saved as the `m.room.name` event for that room, which is not the right semantics when the name has been computed by the server. The computation of a name should happen client-side, so as to be able to translate it according to the user's language.
Instead, this PR makes it so that we ignore the `name` field from the sliding sync response, and instead request the `m.room.name` event for all the rooms in the room list service.
Conversely, the `m.room.avatar` is always set to the `avatar` field from a room sub-part of a response, and it's likely more precise than the actual content of the `m.room.avatar` (it will user the other user avatar for a DM room). We could also …
=> room list service: always request the room name event

crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs
With a regression test.
Fixes #3432.
=> memory state store: correctly save and delete a user avatar url

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/queue.rs
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3361. This is me understanding the code and starting to refactor it a bit.
=> timeline queue: refactor the code a bit

crates/matrix-sdk-ui/src/timeline/day_dividers.rs
See individual commit messages.
=> day dividers: record the insertion index for operations based on the previous item

Cargo.lock, crates/matrix-sdk-indexeddb/CHANGELOG.md, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
Part of a resolution to https://github.com/element-hq/element-web/issues/26821: allow applications to skip the PBKDF2 operation if they already have a cryptographically secure key.
In order to maintain compatibility for existing element-web sessions, if we discover that we have an existing store that was encrypted with a key derived from PBKDF2, then we reconstruct what element-web used to do: specifically, we base64-encode the key to obtain the "passphrase" that was previously passed in. If that matches, we know we've got the right key, and can update the meta store accordingly.
=> indexeddb: expose new method `IndexeddbCryptoStore::open_with_key`

.github/workflows/bindings_ci.yml, bindings/apple/build_crypto_xcframework.sh, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/uniffi-bindgen.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3310
The script to build the crypto bindings was not working anymore since the move from UDL to procedural macro.
Modified as per the following recommendations https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html#running-uniffi-bindgen-using-a-library-file-recommended
There is some changes in the generated framework, there are now two swift files and two modulemap files that have to be merged together in the final xcframework.
Previous structure was
The new one is 
Signed-off-by:
=> crypto: Apple Crypto Bindings | Fix crypto xcframework script

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/types/device_keys.rs
Fixes: https://github.com/element-hq/element-web/issues/27165.
Currently, whenever we receive a `/keys/query` response, we emit items from `identities_stream_raw` and `devices_stream` for any users listed in the response, even if there was no actual change to the devices. This PR changes behaviour so that items are only emitted if there are actual changes.
=> crypto: emit no `identities_stream` items on no-op changes

crates/matrix-sdk-ui/src/timeline/day_dividers.rs
This checks in a few tests found thanks to some local poorman's fuzzing. They were failing locally and have been fixed since, see each commit that contains one failing test and its fix. These are likely showing real-world bugs, where in the worst case, the last message could disappear because it's been incorrectly removed as if it were a duplicate day divider.
=> day dividers: resolve a few extra bugs

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/tasks.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/messages.rs, crates/matrix-sdk/src/room/mod.rs
See individual commit messages.
=> event cache: don't cause a reference cycle with `Client` because of pagination

crates/matrix-sdk-crypto/src/identities/manager.rs
The compiler has been pestering me with this, so here's a fix.
=> crypto(nit): remove unnecessary path qualifier in a test

bindings/README.md
It looks like the repo has moved. I also think it's worth calling out that the bindings use Wasm (which means they're not usable in e.g. React Native).
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
=> Update JS bindings link

bindings/matrix-sdk-ffi/src/widget.rs
-fix what permissions `get_element_call_required_permissions` returns and have them match what Element Call actually expects
- this got implemented in https://github.com/matrix-org/matrix-rust-sdk/pull/2825 but never actually worked in the app, resulting in ElementCall getting stuck on a `Loading` screen
- tweaked the permissions list by running ElementCall and comparing it to the capabilities returned in `acquireCapabilities(capabilities:)`
- check all of this with @toger5, which also tells me that `org.matrix.msc3401.call` is deprecated and should not be required although ElementCall doesn't work without it.  He will clean up the web side and then come back to remove this as well in a later PR.
=> ffi: Fix `get_element_call_required_permissions`

bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs, crates/matrix-sdk/src/event_cache/pagination.rs, crates/matrix-sdk/src/event_cache/paginator.rs
This should help with the integration of the back-pagination status, when we have automatic back-pagination in the background.
=> timeline: indicate if we've hit the start of the timeline in the live back-pagination status

Cargo.lock, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml
It appears that the patch release 0.7.1 branch has not been merged in main, causing the crypto crate changelog to be outdated, and the toml version also.
Attempt to fix that
Signed-off-by:
=> chore(crypto): Fixup version and changelog from patch release

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/sticky.rs, labs/multiverse/src/main.rs
This is #3441 but since I've added many commits while taking it over, reopening a new PR for it.
This makes it so that we prefer using the hero names if we receive those from the sliding sync, rather than retrieving the names from the room members that are hero, or retrieving the room members from the first N members.
I've also updated the very unfortunate edge case where we have 0 heroes to display "n people" instead of ", and n others.".
=> room names: better make use of the hero names for locally computing a room display name

Cargo.lock, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/event_cache/linked_chunk/as_vector.rs, crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs, crates/matrix-sdk/src/event_cache/linked_chunk/updates.rs
This patch is the result of:
* Running [`cargo mutants`](https://mutants.rs/) on `matrix_sdk::event_cache::linked_chunk`,
* Having fun with [`cargo fuzz`](https://rust-fuzz.github.io/book/cargo-fuzz.html), then replacing it with [`proptest`](https://proptest-rs.github.io/proptest/proptest/index.html).
Mutation-based testing has revealed that one test was missing, it's been addressed by https://github.com/matrix-org/matrix-rust-sdk/commit/50f9cd6b4536389d65d7b51fb6e5a940c0346eb1.
Property-based testing has revealed nothing except that the test I wrote was raising a bug, addressed by https://github.com/matrix-org/matrix-rust-sdk/pull/3460/commits/ed41d49fe14350edb746278d52a39a884debb29b.
The property-based test is present in this patch too.
=> feat(sdk): Mutation-based testing and property-based testing for `LinkedChunk`

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine.rs
Exposes the crypto store `clear_caches` method on the OlmMachine to be used by EI to invalidate cache when multiprocess is involed. (see EXI equivalent https://github.com/matrix-org/matrix-rust-sdk/pull/3338)
Signed-off-by:
=> FFI Bindings: Expose CryptoStore clear caches

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/tests/integration/event_cache.rs
This patch improves/refactors `RoomEventCacheUpdate` a little bit. That's preliminary work to support `VectorDiff` from the `EventCache` into the `Timeline`.
---
=> feat(sdk): Improve `RoomEventCacheUpdate`

.typos.toml, Cargo.lock, Cargo.toml, benchmarks/benches/room_bench.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/test_utils.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/authentication/mod.rs, crates/matrix-sdk/src/authentication/qrcode/login.rs, crates/matrix-sdk/src/authentication/qrcode/messages.rs, crates/matrix-sdk/src/authentication/qrcode/mod.rs, crates/matrix-sdk/src/authentication/qrcode/oidc_client.rs, crates/matrix-sdk/src/authentication/qrcode/rendezvous_channel.rs, crates/matrix-sdk/src/authentication/qrcode/secure_channel.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/oidc/mod.rs, examples/qr-login/Cargo.toml, examples/qr-login/src/main.rs
This implements part of [MSC4108](https://github.com/matrix-org/matrix-spec-proposals/pull/4108). We're only supporting the case where new device scans the QR code and gets logged in by the existing device.
Opening as a draft as I want to reword the commit messages a bit, add some more documentation (mainly to insert some jokes about rendezvous), and possibly one or two more tests.
Best reviewed commit by commit, although there is one giant commit. Reviewer please have mercy on me.
=> Support to log in using a QR code

crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/pagination.rs, crates/matrix-sdk/tests/integration/event_cache.rs
Reverting changes because the PR didn't pass CI at the time of merging, and it's been force-merged. We can't break `main` like this, especially when the PR author is not around to fix it thereafter.
=> Revert "feat(sdk): Add `RoomPagination::run_backwards(…, until)`"

bindings/matrix-sdk-ffi/src/client_builder.rs
We have a separate error for the QR code decoding method.
=> bindings: Remove the InvalidQrCode error variant for the QR login error type.

bindings/matrix-sdk-crypto-ffi/src/verification.rs, bindings/matrix-sdk-ffi/src/session_verification.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk/src/encryption/verification/sas.rs, examples/emoji_verification/src/main.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs
To differentiate the SAS state between the party that sent the verification start and the party that received it.
Fixes #2979.
=> crypto: Add `SasState::Created` variant

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs
Add tests to ensure that unknown properties in device keys are handled correctly.
One test was previously discussed at https://github.com/matrix-org/matrix-rust-sdk/issues/3132#issuecomment-2002060930  The other test ensures that the /keys/query response handler doesn't freak out about unknown properties.
=> Add tests for unknown properties in device keys

.github/workflows/coverage.yml, .github/workflows/upload_coverage.yml
… which runs in the context of the main repo even for PRs from forks, and can be retried individually without rerunning coverage collection.
I saw you're still suffering from codecov's problems, so I decided to take the time required to look up the most recent suggested workaround (most up-to-date upstream issue discussing this stuff is https://github.com/codecov/feedback/issues/301 and contains links to the workflows I copied here).
Hope it works. If not, maybe you can get it to work. Can't promise that I'll put more time into this.
=> ci: Split codecov uploads into a separate workflow

.github/workflows/upload_coverage.yml
Because GitHub actions has no IDs for workflows, you refer to them by name. What could possibly go wrong?
=> Fix trigger condition for new upload_coverage workflow

.github/workflows/coverage.yml, .github/workflows/upload_coverage.yml
Should start working after this merges. Second-to-last commit is the main fix, everything else is related refactorings.
=> ci: Fix coverage uploads in separate workflow

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/platform.rs
Simple as that, everything just works.
Test rageshake here https://rageshakes.element.io/api/listing/2024-05-31/064228-6IZED7GI/console.2024-05-31-06.log.gz, search for `Burn, baby! Burn! 🔥`
=> ffi: enable panic logging for all supported platforms not only android

crates/matrix-sdk-ui/CHANGELOG.md, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
If an event cannot be decrypted after a grace period, it is reported to the application (and thence Posthog) as a UTD event. Currently, if it is then successfully decrypted, the event is then re-reported as a "late decryption".
This does not match the expected behaviour in Posthog - an event is *either* a UTD, or a late decryption; it makes no sense for it to be both. This PR fixes the problem.
I've attempted to make the commits sensible, but I'm not entirely sure I've succeeded. The tests do pass after each commit, though. The interesting change itself is somewhere in the middle; there is non-functional groundwork before and cleanup afterwards.
=> utd hook: fix re-reporting of late-decrypted events

crates/matrix-sdk-ui/src/timeline/pagination.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/pagination.rs, crates/matrix-sdk/tests/integration/event_cache.rs
https://github.com/matrix-org/matrix-rust-sdk/pull/3472 has been reverted in https://github.com/matrix-org/matrix-rust-sdk/pull/3477 because the doc' was broken. This PR reverts #3477 and fixes the doc.
=> feat(sdk): Add `RoomPagination::run_backwards(…, until)`, take 2

bindings/matrix-sdk-ffi/src/timeline/content.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs
This can be equivalently retrieved using:
`get_timeline_event_by_event_id(event_id).content().as_message()?.content()`
As per the commit date, this is used in one place in both EXA and EXI, so it seems fine to change the caller's call sites.
And this avoids one explicit call site of
`Timeline::item_by_event_id()`.
=> ffi: get rid of `Timeline::get_timeline_event_content_by_event_id`

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/futures.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Most of #3361, except for storing/reloading the local echoes from the disk.
=> sdk: implement a sending queue

labs/multiverse/src/main.rs
For testing purposes only :notes: 
Helps with testing #3361.
=> multiverse: add support for sending messages and {en|dis}abling the sending queue

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
It turns out that the failure came when using the known room path in the room preview: Alice knows about the room, but for some reason the client didn't retrieve all the state events from the sliding sync proxy yet.
Before, the sync would be considered stable after 2 seconds. This is too little, considering that events come from the proxy that listens to events from synapse. Raising this threshold to 15 seconds should help getting all the room information from the proxy, and thus get all the information we expected in the client.
Fixes #3483.
=> integration test: sync longer in `test_room_preview` before considering it stable

Cargo.toml, bindings/matrix-sdk-ffi/src/timeline/content.rs, crates/matrix-sdk-base/src/media.rs
Depends on https://github.com/ruma/ruma/pull/1820
The StickerEventContent struct changed (url is gone, source was added), this change exposes the new field.
Signed-off-by: Marco Alvarez <surakin@gmail.com>
=> Expose new sticker source field (and drop url field)

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/sliding_sync.rs, xtask/src/ci.rs
This enforces the env variable to set the `--target-applies-to-host` setting when running in xtask. I'm not sure why it's required, but without it, the CI step didn't find all the issues that I could find locally. @jplatte if you have any idea about that, I'd be curious; I've mostly cargo culted the existing workaround used when building the doc. It looks like another instance of https://github.com/rust-lang/cargo/issues/10744 in a slightly different context.
The second commit fixes the issues found by clippy.
=> clippy: fix extra errors and enforce `target-applies-to-host` in xtask

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
Another attempt at fixing #3483.
=> room preview integration test: explicitly request some state events to sync

Cargo.lock, Cargo.toml, crates/matrix-sdk-base/src/rooms/normal.rs
This patch updates Ruma to [`75e8829`](https://github.com/ruma/ruma/commit/75e8829bec0b7bc5332860e1fb2df658d5c71d66) so that `RoomSummary::heroes` is now a `Vec<OwnedUserId>` instead of a `Vec<String>`. This patch updates our code accordingly by removing the parsing of heroes as `OwnedUserId`.
---
=> feat(base): Update Ruma to get `RoomSummary::heroes` as `Vec<OwnedUserId>`

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, bindings/matrix-sdk-ffi/src/encryption.rs
- Fixes a regression in the `AuthenticationService` introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/3473. See the commit message.
- FFI objects that contain (directly or transitively) a reference to a SDK `Client` may drop before the FFI `Client` has dropped. As a matter of fact, they should *also* hold a reference to the FFI `Client`, otherwise we may need to replicate the `ManuallyDrop` hack introduced for the FFI `Client` in all those structures. There's a precedent for keeping a link to the FFI `Client`, in `NotificationClient`, so I copied it in a few places.
=> ffi: fix multiple issues with the `AuthenticationService` and `deadpool`

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/oidc/registrations.rs
This PR removes the concept of a base_path from the FFI. Instead we do the following:
1. Provide a direct path to the OIDC registrations.json file instead of building it - this was weird using a base_path directly in the main SDK crate.
2. Remove all the ClientBuilder logic that creates the store path from the base_path + user_id and instead have the caller generate one (using a UUID for new logins and saving it for restoration) themselves.
3. Remove the in-memory client from the authentication service, as now we don't need to worry about the whole "we don't know the final path until the login is complete".
Have tested with password, OIDC and QR logins.
=> FFI: Replace `base_path + user_id` with a `session_path`.

crates/matrix-sdk-ui/src/timeline/day_dividers.rs
Because of the task cancellation that can happen at any place in the code base, it's really hard to predict in which situation a day-divider-adjuster should have run or not, so just demote the assert to an error. The intent is that, if we see errors with day dividers in the future, they'll be reported along rageshakes and we'll notice this in the logs.
=> day dividers: demote an assert to an error message

bindings/matrix-sdk-ffi/src/widget.rs
also add TODO comment to remove. `org.matrix.msc3401.call` once possible.
=> widget API(ffi): Add `StateEventType::RoomEncryption` to capabilities

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs, labs/multiverse/src/main.rs
What it says on the tin. Based on #3520 to avoid another conflict with myself.
=> sdk: finish renaming the sending queue to send queue :eyes: 

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs, labs/multiverse/src/main.rs
This makes it so that getting any error (network or API error) will only disable the send queue for a single room. Callers are expected to `SendQueue::subscribe_errors()` to see whenever they get an error:
- if they get an error, and network is disconnected: disable the send queue
- if they get an error, but network is still here: either re-enable the send queue, or display the error somewhere to the user. (It's also reflected live in the timeline.)
Based on top of #3522 to avoid conflicts.
=> send queue: use an enablement status per room

crates/matrix-sdk-ui/src/timeline/inner/mod.rs
This patch removes a useless clone of `TimelineInner::items`. This clone was technically cheap because it's a `Vector` behind the scene, which is cheap to clone, but still, it's not necessary at all to clone it.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512.
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3280.
=> chore(ui): Remove a useless clone

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs
This patch updates `TimelineEventHandler` to re-use the public API and avoid using `TimelineInnerMeta::next_internal_id`. The consequence is that `next_internal_id` can now be private instead of public. It's better to have isolated API in this code.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512.
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3280.
=> chore(ui): Make `TimelineInnerMetadata::next_internal_id` private

crates/matrix-sdk-ui/src/timeline/event_handler.rs
This patch renames `TimelineEventHandler::add` to `add_item`.
This patch also removes the `should_add` argument. The `add_item` is called conditionally everytime. I believe this is much cleaner. Otherwise the method should have been called `maybe_add_item` with a return type or something that indicates whether the item is added. This patch makes it clear and remove one possible state in `add_item`.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512.
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3280.
=> chore(ui): Rewrite a bit `TimelineEventHandler::add`

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/mod.rs
This PR is the first piece of the breakdown of the following PR: https://github.com/matrix-org/matrix-rust-sdk/pull/3439 where only the core functionalities of the feature are implemented, without addressing the issue of editing and replying to events that have not yet been paginated.
=> feat (bindings): added APIs to save and load composer drafts

crates/matrix-sdk/src/deduplicating_handler.rs
Solves one potential issue spotted in https://github.com/matrix-org/matrix-rust-sdk/issues/3529. If the following sequence happened:
- request A for key K starts
- request B for key K wants to start, but it's deduplicated, so it waits for request A to finish
- request A gets aborted
Then, in the previous version of the code, request B would finish and assume that A successfully completed, while this is not the case.
This new version handles that by repeating the deduplicated query. **This assumes that it's fine to repeat the entire query**, which is not a light assumption, but looking at the uses of the deduplicating handler (/members, sending a read receipt for a room, reading the encryption state for a room), this should be fine.
=> deduplicating handler: handle cancellation by repeating the query, if needs be

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline/content.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
second part of the #3439 breakdown
The context for this API, is for the composer preview an reply without the need of it being actively in the timeline.
=> feat (bindings): added an API to retrieve a loaded reply

xtask/src/swift.rs
=> fix(bindings): use the same library name for all platforms in the xcframework

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-crypto/src/types/qr_login.rs, crates/matrix-sdk/src/authentication/qrcode/login.rs, crates/matrix-sdk/src/authentication/qrcode/secure_channel.rs, examples/qr-login/src/main.rs
Using the resolved homeserver URL causes problems if we need to inspect the well-known configuration of the homeserver, for example, if the server name is matrix.org, but the homeserver URL is server.matrix.org, the well-known might be only available for the former.
This is why we also need to receive the former, i.e. the server name in the QR code data.
=> crypto: Use the server name in the QR code login data

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/room_list.rs
This patch removes `RoomInfo::latest_event`. To get the latest event,
one has to use `RoomListItem::latest_event` because it supports
local events and remote events. It was supposed to be the case of
`Room::room_info` too, but only when the method was called: Once the
`RoomInfo` was created, the latest event inside `RoomInfo`
was static, not dynamic. Also, this code wasn't tested
contrary to `RoomListItem::latest_event` which uses
`matrix_sdk_ui::room_list_service::Room::latest_event` which is itself
tested.
---
* Based on https://github.com/matrix-org/matrix-rust-sdk/pull/3540. It must be merged after #3540 is merged. Please review only the last commit.
=> chore(ffi): Remove `RoomInfo::latest_event`

crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
This patch changes the behaviour of the `Timeline` when a duplicated event is received. Prior to this patch, the old event was removed, and the one was added. With this patch, the old event is kept, and the new one is skipped.
This is important for https://github.com/matrix-org/matrix-rust-sdk/pull/3512 where events are mapped to the timeline item indices. When an event is removed, it becomes difficult to keep the mapping correct.
This patch also adds duplication detection for pagination (with `TimelineItemPosition::Start`).
---
=> fix(ui): Change the behaviour when a duplicated event is received by the `Timeline`

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, labs/multiverse/src/main.rs
This patch is twofold:
* it updates `room_list_service::Room::new` to take a `&Client` and a `&RoomId` instead of a `SlidingSyncRoom`. The `SlidingSyncRoom` is only used in `Room::default_room_timeline_builder` and is fetched there from the `SlidingSync` instance lazily. It confines the `SlidingSyncRoom` to one single method for `Room` now.
* it makes `RoomListService::room` synchronous. It no longer reads a `SlidingSyncRoom` from `SlidingSync`, then it not needs to be async anymore. This patch replaces the `RwLock` of `RoomListService::rooms` from `tokio::sync` to `std::sync`.
--- 
=> feat(ui): `RoomListService::room` is no longer async!

crates/matrix-sdk-base/src/store/mod.rs
`Store::get_rooms` worked as follows: For each room ID, call
* Take the read lock for `rooms`,
* For each entry in `rooms`, take the room ID (the key), then call `Store::get_room`, which…
* Take the read lock for `rooms`,
* Based on the room ID (the key), read the room (the value) from `rooms`.
So calling `get_rooms` calls `get_room` for each room, which takes the lock every time.
This patch modifies that by fetching the values (the rooms) directly from `rooms`, without calling `get_room`.
In my benchmark, it took 1.2ms to read 10'000 rooms. Now it takes 542µs. Performance time has improved by -55.8%.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3068
=> feat(base): Make `Store::get_rooms` wayyy faster

crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk/src/client/mod.rs
This patch renames `Store::get_rooms`, `::get_rooms_filtered` and `::get_room` to respectively `::rooms`, `::rooms_filtered` and `::room`. This `get_` prefix isn't really Rust idiomatic.
This patch also fix `Store::rooms_filtered` to not call `Store::room`, thus not locking the entire `rooms` for every item, making it everything faster.
---
* Extracted from #3068,
* Partly a follow up of #3552 with the update of `rooms_filtered`,
=> chore: Remove the `get_` of some `Store`'s methods

crates/matrix-sdk-base/src/store/mod.rs
This patch removes the public type alias `BoxedStream` which is never used in our code.
=> chore(base): Remove `BoxStream` as it's never used

crates/matrix-sdk/tests/integration/encryption/backups.rs
Some groundwork for fixing https://github.com/matrix-org/matrix-rust-sdk/issues/3446.
~~Almost all the changes are in the integration tests, but there is a tiny change to the `crypto` crate to expose `MegolmV1BackupKey::encrypt` outside the crate.~~
Edit: now exclusively updates in the integ tests.
=> sdk: Refactor key-backup integration tests

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/lib.rs
This PR makes 2 changes:
- Updates the storage of room heroes to be a single array containing the user's complete profile.
- Exposes these to the FFI so that client apps can use these for avatar colours/clusters.
I'm not 100% sure what to do about the difference between syncv2 and syncv3 returning different things, adding some thoughts inline.
Closes #2702 (again, now with avatars 🖼️)
=> ffi: Expose room heroes (adding support for avatars).

crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
Not doing this leads to an invalid ordering of events, as shown in the test: if we increase the timeline limit of a room using sliding sync, we'll receive a duplicate event, and if we ignore it, it'll be in an invalid position. The solution is to keep the most recent event (and remove the old one from event_meta).
=> timeline: when deduplicating event meta, keep the most recent instead of the oldest

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/tasks.rs, crates/matrix-sdk/src/room/mod.rs
More groundwork for fixing #3446, and a follow up to #3560 .
Currently (prior to this PR), the `BackupDownloadTask` fires off an async task for each megolm session we get a UTD for. Each task then waits for a bit to see if the key turns up, and if not, makes a backup download request.
The primary goal of this PR is to change that behaviour so that it fires off a task for each *event* and waits to see if the key for that *event* becomes available. That does necessitate a bit of extra bookkeeping to make sure that we don't end up doing multiple backup downloads for the same megolm session, but the point is that each event needs its own `sleep`.
It doesn't actually fix the bug yet, because we still just check `is_key_available` for the session as a whole. This PR is just groundwork for …
=> sdk: Rewrite key-backup download task

crates/matrix-sdk-crypto/src/backups/keys/backup.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk/src/encryption/tasks.rs, crates/matrix-sdk/tests/integration/encryption.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3446 by checking that we have the key for the event in question, not just the key for the session.
~~This PR is based on #3567.~~
=> sdk: Fix key backup download for ratcheted sessions

benchmarks/Cargo.toml
The workspace root enables some features which are required to compile the benchmarks, but if you decide to just compile the benchmarks these features won't be enabled since they aren't specified in the Cargo.toml file of the benchmarks.
Let's define all the required features so compilation works in both cases.
=> chore: Fix the compilation of the benchmarks outside of the workspace root

crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs
This patch fixes a panic in `LinkedChunk` where we substract with overflow when fetching the latest position of an item in an empty `Chunk`.
=> fix(sdk): Fix a substract with overflow in `LinkedChunk`

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk/src/room/mod.rs
Allows to potentially have a fully decrypted event.
Fixes #2976.
=> crypto: Decrypt events bundled in unsigned object of another event

crates/matrix-sdk/src/room/futures.rs, crates/matrix-sdk/src/room/mod.rs
This adjusts the control flow so we start with the simplest cases (do not encrypt) first, then the encryption path. This then properly records that a reaction is *not* sent encrypted. Also lowers the level of logging from debug to trace for those log events, since they're not particularly interesting.
=> room: rename the `encrypted` log field to `encrypted_room`

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs
This patch makes `Room::new` infallible, i.e. it no longer returns a `Result<Self, _>` but `Self` directly.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3585.
=> feat(sdk): `room_list_service::Room::new` is now infallible

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/builder.rs
This PR is a small part of #3029 that moves (and tests) the check for mandatory sliding sync from the FFI into the SDK with the use of a `ClientBuilder::requires_sliding_sync` method.
=> Client Builder: Add support for requiring Sliding Sync.

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/oidc/auth_code_builder.rs, crates/matrix-sdk/src/oidc/mod.rs, crates/matrix-sdk/src/oidc/registrations.rs, crates/matrix-sdk/src/oidc/tests.rs
This PR moves the remaining logic from the `AuthenticationService` into the SDK. For now this doesn't expose anything new in the FFI and simply calls the inner methods. I'll leave that and deleting the service for a follow-up PR.
Another part of #3029.
=> sdk: Move the OIDC helper methods from the FFI's `AuthenticationService` into `Client`

Cargo.lock
=> fix(ffi): Downgrade security-framework to 2.10.0

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/migrations/state_store/003_send_queue.sql, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk/src/media.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Ruma needs https://github.com/ruma/ruma/pull/1850. I need an Advil.
Part of #3361. The remaining bit will be to, at start, reload all the rooms' send queues that had _some_ pending event (right now, pending events will be automatically re-sent as soon as a timeline is opened for that room).
=> send queue: add state store backend for persisting pending events to disk

Cargo.lock, Cargo.toml, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk/src/room/futures.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
This requires a bit of API rejiggering, but turns out not so bad actually.
Requires a [Ruma fix](https://github.com/ruma/ruma/pull/1866) first, otherwise it'll break all message responses in threads (as a test failure will show).
Part of #3361.
Note: draft only because this is waiting for the Ruma fix, otherwise the code is ready for review.
=> send queue: allow sending raw events from the send queue

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Based on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3601.
This adds an `is_wedged` boolean to `LocalEcho`, so it's possible to know if a local echo was wedged or not, and so the timeline can update its event send state as soon as possible when it's reloading persisted local echoes.
Spotted by @stefanceriu (thanks!). Includes a regression test.
Note: draft only because this is waiting for the Ruma fix, otherwise the code is ready for review.
=> send queue: mark reloaded local echoes as wedged or not

crates/matrix-sdk/src/error.rs
This can happen if there's a load-balancer or any modification of the response by a reverse proxy (e.g. rewrite 5XX errors into 429, to not let a reverse proxy mark the upstream server as being down, as Cloudflare seems to do).
As a result, such requests will be retried in multiple places, including when sending something with the send queue. Also, the send queue will mark these errors as recoverable instead of unrecoverable.
No test, because the change really is trivial and a regression test didn't seem worth it, for once.
Part of #3361.
=> sdk: retry all requests which previous response was a plain 429 without an errcode

crates/matrix-sdk/Cargo.toml
It is only needed with the `experimental-oidc` and `e2e-encryption` features. The former is less likely to be enabled so use it to enable the dependency.
=> sdk: Mark openidconnect crate as optional

crates/matrix-sdk-ui/src/timeline/mod.rs
A few were missing in the public API like `SendEventError` and `RedactEventError` and their dependencies.
This uses a wildcard because it should be rare to not want to expose an error type.
=> ui: Make public all timeline module errors

crates/matrix-sdk-ui/src/lib.rs
A user of the library needs to add this crate as a dependency just to be able to match on `VectorDiff`.
=> ui: Reexport eyeball-im

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-common/src/tracing_timer.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/migrations/state_store/004_send_queue_with_roomid_value.sql, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/src/test_utils.rs, crates/matrix-sdk/tests/integration/send_queue.rs, labs/multiverse/src/main.rs
This changes the database scheme for the send queue: to be able to list all the rooms (room_id) which have unsent events, the `room_id`s need to be saved as *values* (i.e. encrypted/decrypted when the db is encrypted), and not just as *keys* (i.e. one-way hashed when the db is encrypted). To make this work, I've added another `room_id` field in the sqlite/indexeddb database, and introduced a sqlite migration (hoping no one used the indexeddb backend with the new feature since two days ago :sweat_smile:) that drops and recreates the table with the new format.
Then, we can implement a query to retrieve all the rooms which have unsent events. With that, we can add a new public function to the `SendQueue` object, which allows to automatically respawn the background room send queue tasks for …
=> send queue: allow to respawn tasks for send queues which had unsent events

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-common/src/deserialized_responses.rs
Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3585. Just a simple refactoring.
=> chore(base): Use constructors of `SyncTimelineEvent` to simplify code

bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/local.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Final step of #3361, as a bonus.
Fixes #3361.
=> send queue: allow editing local echoes

.typos.toml, bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk-crypto/src/types/events/room_key.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/mod.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3542
This changes the shape of `InboundGroupSession` to allow us to include a `SenderData` struct. To see how it will be populated, look at https://github.com/matrix-org/matrix-rust-sdk/issues/3543
=> crypto: Storage changes for keeping sender data with InboundGroupSessions

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/element.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/lib.rs, crates/matrix-sdk/src/client/mod.rs
Handles part of element-hq/element-meta/issues/2441
* exposes a generic method to make GET requests throgh the SDKs internal HTTP client. This avoids various configuration differences between the SDK stack and that of the client
* exposes a way to read the server name part of the current user's identifier (already built into ruma, make sense to use it across clients)
* adds an Element specific well-known struct that the FFI clients can use to deserialize a response JSON
Powers https://github.com/element-hq/element-x-ios/pull/2971
=> Element specific well-known support

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/send_queue.rs
This will still disable the room's send queue, but the embedder may then decide whether to re-enable the queue or not, based on network connectivity. Ideally, we'd implement some retry mechanism here too, but since we're at a different layer than the HTTP one, we can't get that "for free", so let the embedder decide what to do here.
---
No test because the only way to trigger this is likely by having an encrypted room, start a /member query for that room, then try to send an encrypted message into that room. Sending encrypted messages require lots of endpoints, and I'm not sure whether we have all the testing setup for that; I'll ask on the Matrix room. But since this is a tiny change in behavior (and we're likely to have other tweaks like that related to error handling, I don't think …
=> send queue: mark `ConcurrentRequestFailed` as recoverable

.github/workflows/fixup-block.yml
We tend to use fixup commits quite a bit, and in the heat of the moment we sometimes forget to squash them before the final merge.
This should prevent us from doing so.
=> ci: Add a github workflow to fail when fixup commits exist

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs
Where a string is clearly documented as a room ID, event ID or mxc URI, use `OwnedRoomId`, `OwnedEventId` and `OwnedMxcURI`, respectively.
Leave the conversion to the bindings.
=> sdk: Use strongly-typed strings where it makes sense

crates/matrix-sdk/src/send_queue.rs
These logs may help with debugging issues around editing of local echoes.
Part of #3361.
=> send queue: add useful logs when aborting/editing a local echo

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/local.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/reactions.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/reaction_group.rs
Each commit should be rather self-explanatory.
The motivation behind the second commit is for the use with `Room::restore_composer_draft`. When restoring a draft, but the edited/replied-to item is not available locally, that would result in two requests to the homeserver:
1. When restoring the composer state, the client makes a request with `Room::event()` to get the content of the edited/replied-to event to be able to display it in the UI.
2. When the user sends the message, the client must first call `Timeline::{edit/replied_to}_info_from_event_id()`, which makes a request to the homeserver, to be able to call `Timeline::edit/send_reply()` to send the event.
By exposing the content of the edit/replied-to info, the client needs only to make a single homeserver request with …
=> ui: Improvements for replies and edits

crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs, crates/matrix-sdk/src/encryption/tasks.rs, crates/matrix-sdk/src/utils.rs, crates/matrix-sdk/tests/integration/encryption/recovery.rs
A review commit by commit is the best way to go through this PR, please take a look at the commit message of the last commit for a full explanation on how the fix works.
A test for this was written in #3583, but sadly it doesn't reproduce the issue since the issue is only triggered if event handlers are run in the wrong order. This PR doesn't rely on the event handler for the backup state, so the order doesn't matter anymore.
This closes: #3445.
=> recovery: Fix the recovery state not being updated after backups are enabled via secret send

.typos.toml
As suggested by @poljar in https://github.com/matrix-org/matrix-rust-sdk/pull/3556
=> typos: Exclude specific words from typo checking instead of whole files

crates/matrix-sdk-crypto/src/olm/session.rs
Commit d41af396c implemented MSC4147, which puts the device keys into a Olm message. It failed to adhere to the unstable prefix proposed in the MSC:
> Until this MSC is accepted, the new property should be named
> org.matrix.msc4147.device_keys.
This patch fixes this.
=> fix(crypto): Rename the device keys property for Olm messages

crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
It could be that the last event in a room's send queue has been marked as wedged. In that case, the task will sleep until it's notified again. If the event is being edited, then nothing would wake up the task; a manual wakeup might be required in that case.
The new integration test shows the issue; the last `assert_update` would fail with a timeout before this patch.
Part of #3361.
=> send queue: wake up the sending task after editing an event

crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Using `SendHandle::abort()` after the event has been sent would look like a successful abort of the event, while it's not the case; this fixes this by having the state store backends return whether they've touched an entry in the database.
Found thanks to `multiverse`.
Part of #3361.
=> send queue: make `SendHandle::abort()`/`update()` more precise

bindings/matrix-sdk-ffi/src/client_builder.rs
No functional changes here, just inlining methods called by a single caller, and simplifying things that could be simplified.
=> ffi: refactor `ClientBuilder`

crates/matrix-sdk-store-encryption/src/lib.rs
One item of https://github.com/matrix-org/matrix-rust-sdk/issues/3272.
=> sdk-store-encryption: use `ZeroizeOnDrop` instead of `[zeroize(drop)]`

crates/matrix-sdk-ui/src/timeline/mod.rs
That way, users of the crate don't need to keep track of the ID separately.
=> ui: Expose identifier of `RepliedToInfo` and `EditInfo`

crates/matrix-sdk-indexeddb/src/crypto_store/indexeddb_serializer.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/mod.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-store-encryption/src/lib.rs
`StoreCipher`'s interface has grown *baroque* over the years. These four functions aren't giving a whole lot of value: they are only used in a couple of places in the codebase, and are pretty simple.
This PR is a mission to clean that up.
Review commit-by-commit.
=> Stores: Remove `StoreCipher::{en,de}crypt_value_[base64_]typed`

testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests/auth.rs, testing/matrix-sdk-integration-testing/src/tests/e2ee.rs, testing/matrix-sdk-integration-testing/src/tests/invitations.rs, testing/matrix-sdk-integration-testing/src/tests/nse.rs, testing/matrix-sdk-integration-testing/src/tests/reactions.rs, testing/matrix-sdk-integration-testing/src/tests/redaction.rs, testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs, testing/matrix-sdk-integration-testing/src/tests/room_directory_search.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
Most tests would randomize the username when creating a `TestClientBuilder`; make it the default, since it's a sensible choice, and avoids interference between different tests / test runs.
A single test required an actual non-randomized username, so a specific way to opt out from this new default behavior has been introduced.
=> integration tests: make randomize_username() the default

crates/matrix-sdk/src/account.rs, crates/matrix-sdk/tests/integration/client.rs
Fixes #3410.
I don't think there's a point in waiting for the `m.direct` data to come through sync, as 1. it would require a causality link (channel) between getting the m.direct event and this method — not impossible but tedious, and 2. marking a room as DM doesn't occur that often, so there's no need to optimize for it that much.
=> sdk: don't clobber the DM list if we failed to deserialize the previous `m.direct` event

crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
It's currently possible for integ test results to leak from one test run to the next (for example, the indexeddb stores hang around in the browser), causing bad test results.
Extend the test setup routine to clear out the store before the test starts.
=> Crypto store: clear db before integ tests

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
~~Draft because based on https://github.com/matrix-org/matrix-rust-sdk/pull/3605~~
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3563
This PR just introduce a new way to distribute room keys based on identities, by only sharing with devices signed by their owner.
This is a first PR to introduce this mode, but it will be really usable once we introduce some support for identity TOFU.
Signed-off-by:
=> feat(sdk-crypto): Add Identity based room key sharing strategy

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This patch revisits the need to trigger a room list update for all changes of `RoomInfo`. For the moment, it reduces the scope to `recency_timestamp` update.
This patch comes with a test to ensure things work as expected.
=> feat(ui): Trigger room list update only when necessary

.github/workflows/bindings_ci.yml
Added a new flow that builds the Kotlin bindings to make sure changes in a PR don't break them (uniffi updates or broken binding generation).
Of course this won't find actual issues with how the bindings work on runtime, it'll only find build time problems.
To make it faster I'm just building for `x86_64-linux-android`. While `aarch64-linux-android` is the most used architecture on our side, `x86_64` is the most prone to breaking due to issues like [Rust compiler errors](https://github.com/matrix-org/matrix-rust-sdk/blob/a957e7069842c7c8594d371c12fd8132c882077a/bindings/matrix-sdk-ffi/build.rs#L8).
Closes #2343.
Signed-off-by:
=> ci: Verify Android bindings build fine

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/session.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/types/events/olm_v1.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk-crypto/src/types/events/room_key.rs
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3542
Fixes a mistake I made in https://github.com/matrix-org/matrix-rust-sdk/pull/3556 - I included `device_keys` in the `content` and it should be outside as per [MSC4147](https://github.com/matrix-org/matrix-spec-proposals/pull/4147)
=> crypto: Move device_keys to DecryptedOlmV1Event as per MSC4147

.github/workflows/bindings_ci.yml
This patch restores Complement crypto since it's been updated to the latest version of the Rust SDK.
=> test(crypto): Restore Complement crypto since it's been updated

crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/config/request.rs, crates/matrix-sdk/src/http_client/mod.rs
Add a new `max_concurrent_requests` parameter in the `RequestConfig` limits the number of http(s) requests the internal sdk client issues concurrently (if > 0). The default behavior is the same as before: there is no limit on concurrent requests issued.
This is especially useful for resource constrained platforms (e.g. mobile platforms), and if your pattern might lead to issuing many requests at the same time (like downloading and caching all avatars at startup).
Signed-off-by: Benjamin Kampmann <ben.kampmann@gmail.com>
=> sdk: Allow to limit the number of concurrent network requests

bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
Before it would go fetch the event from the server using a network request.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3589
Signed-off-by:
=> ffi: Timeline::load_reply_details checks if the event exists locally

bindings/matrix-sdk-ffi/src/timeline/content.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs
Synapse returns a bare `{ "membership": "leave" }` as the content of a room membership event (for leave membership changes and likely others). In this case, it'd still be nice to have some kind of display name/avatar URL to show in UIs; it's possible to reuse information from the previous member event, if available.
=> timeline: use the previous content's membership info when it's missing from the current membership event

crates/matrix-sdk/src/http_client/mod.rs, crates/matrix-sdk/src/http_client/native.rs, crates/matrix-sdk/src/http_client/wasm.rs
When a request fails because of the exponential backoff, it won't be re-logged again. It would be useful, for the purposes of the send queue notably, to see when a request is re-attempted.
Since the HTTP client has two implementations, one native that does the retries and another one for wasm that doesn't, we have to duplicate the log statement; it's fine IMO, since this is code that shouldn't change much over time.
=> http_client: log each backed-off attempt at sending a request

crates/matrix-sdk-base/src/store/memory_store.rs
Now we have more information on which locks are implicated, refine the logs to identify the exact lock.
Follow up to https://github.com/matrix-org/matrix-rust-sdk/pull/3642
=> base: adjust trace logging in memory store

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/mod.rs, labs/multiverse/src/main.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This patch updates several parts of the code but it's basically just
renamings.
First off, the patch renames `RoomInfoUpdate` to
`RoomInfoNotableUpdate`. The functions, methods or variables
whose names start with `roominfo_update(.*)` are renamed
`room_info_notable_update$1`.
Second, this patch removes the
`RoomInfoNotableUpdate::trigger_room_list_update` field. It is replaced
by a `reasons: RoomInfoNotableUpdateReasons` 8-bit unsigned integer.
It addresses the following issues:
1. When a subscriber receives a `RoomInfoNotableUpdate`, they have no
idea what has triggered this update.
2. In
`matrix_sdk_base::sliding_sync::BaseClient::process_sliding_sync_e2ee`,
we were triggering an update even if the latest event wasn't
modified: it is a false-positive, it was a bug and a waste of …
=>  feat(base): Revisit the `roominfo_update` API

crates/matrix-sdk-base/src/store/memory_store.rs
I've been debugging a cause of flakey complement-crypto tests for about a month now. I was pretty convinced it was deadlocking somewhere in the memory store `save_changes` code. With additional logging, it's now clear that the there is an ABBA style deadlock when `save_changes` is called at the same time as `get_state_events`.
I've also adjusted code for `get_user_ids` as it has a very similar pattern and also acquires locks in reverse order to `save_changes`, so is potentially vulnerable to this.
=> memory-store: release locks earlier to avoid deadlocks

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/src/media.rs
This series of commits makes it possible to cache the server versions and unstable features, with a cache duration of one day (can be tweaked easily!). Caching works this way:
- if we have already filled the in-memory cache, use that
- instead, try to reload the disk caches,
- if they have expired, do a network request to get the latest server version (and cache the results in both memory and disk)
Fixes #2372.
=> sdk: cache server versions and unstable features

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Part of the fix to https://github.com/element-hq/element-web/issues/27653.
[Please ignore the branch name; I appear to have fat-fingered]
=> crypto: Expose new stream about room_key withheld messages

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Followup on #3660: I realised I didn't want to have to parse the room_id and session_id out of the messages again.
=> crypto: Pass room id and session id to `room_keys_withheld_received_stream`

crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs, crates/matrix-sdk-ui/src/timeline/tests/invalid.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk/src/test_utils/events.rs, crates/matrix-sdk/tests/integration/event_cache.rs, testing/matrix-sdk-test/src/event_builder.rs
The `TestTimeline` had lots and lots of custom methods for creating test events and handling them immediately. Since the `EventFactory` helper makes it possible to easily create events, there's no need to repeat those responsibilities in the timeline testing code itself, and we can make more use of the `EventFactory` instead.
There's much more to do there; ideally, we'd get rid of most of `TestTimeline::handle_` methods (we'd keep `handle_live_events`), as well as `EventBuilder` entirely, which API isn't flexible at all. Could be some nice and fun good-first-bugs :sunglasses:
=> tests(timeline): make use of the `EventFactory` more

crates/matrix-sdk/src/test_utils/events.rs, crates/matrix-sdk/tests/integration/event_cache.rs
It's actually simpler to not use a macro here, and the `EventFactory` "curried" parameters make this a breeze to avoid repetition.
(Only last commit applies, will rebase before review.)
=> tests: get rid of the `non_sync_events` macro

crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
This is needed to prevent the race condition where the invite request finished, the `/sync` one didn't fetch the new membership event yet and we send a message in the room. This message won't be encrypted for the newly invited user and will result in an UTD.
I added a new integration test and I can confirm this [complement-crypto test](https://github.com/matrix-org/complement-crypto/pull/98) now passes instead of being skipped.
Fixes #3622.
Signed-off-by:
=> fix(sdk): force room member reload after inviting a user

crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
As suggested in https://github.com/matrix-org/matrix-rust-sdk/pull/3590#discussion_r1671945866
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3543
=> crypto: Rename msk to master_key for consistency with the wider codebase

crates/matrix-sdk-base/src/read_receipts.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs
Please review this PR patch-by-patch.
tl;dr: this PR adds the `READ_RECEIPT` reason for the room info notable update, in order to refresh the room list for this particular reason. This PR also adds a missing test for the `LATEST_EVENT` reason (it was tested in `matrix-sdk-ui` but it's better to also unit test it in `matrix-sdk-base` directly).
=> feat(base): New `RoomInfoNotableUpdateReasons::READ_RECEIPT`

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/virt.rs
=> timeline: adjust day divider and read marker items after a local echo has been redacted/edited

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs
Since it's only used for remote events, and a local echo couldn't figure that out anyways (since it's not sent yet, and that information makes sense after sending).
=> timeline: move `TimelineEventContext::encryption_info` to the remote flow

crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/store.rs
"dude… what if the event cache… allowed to retrieve events by id… i know, it's crazy right…"
This is going to be useful for #3663, for edits we'll want to retrieve the original event by id, to see if it was a reply, and some other things like this.
Part of #3058 too.
=> event cache: add a way to get an event by ID

Cargo.toml, benchmarks/Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk/Cargo.toml, examples/autojoin/Cargo.toml, examples/backups/Cargo.toml, examples/command_bot/Cargo.toml, examples/cross_signing_bootstrap/Cargo.toml, examples/custom_events/Cargo.toml, examples/emoji_verification/Cargo.toml, examples/get_profiles/Cargo.toml, examples/getting_started/Cargo.toml, examples/image_bot/Cargo.toml, examples/login/Cargo.toml, examples/oidc_cli/Cargo.toml, examples/persist_session/Cargo.toml, examples/qr-login/Cargo.toml, examples/secret_storage/Cargo.toml, examples/timeline/Cargo.toml, labs/multiverse/Cargo.toml, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-test/Cargo.toml
These patches try to declare the dependencies by abusing `workspace`.
=> fix: Dependencies clean up

bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3667
Signed-off-by:
=> feat(timeline) - Expose shield state for EventTimelineItem

Cargo.lock
The version we were using was yanked.
Closes: https://github.com/matrix-org/matrix-rust-sdk/issues/3693
=> chore: Bump our bytes dependency

bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs
These logs were alarming for no good reasons: a transaction id may be sent with a remote event, even if the remote event doesn't match a corresponding local echo (because it's been sent much further in the past). As a result, these logs will pollute rageshakes, so let's get rid of those.
=> timeline: remove some dubious logs

bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/edit.rs, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/src/tests/timeline.rs
Part of my quest to move functionality from the `Timeline` to the SDK, this makes it possible to create a replacement event for another one (edit), for all the `m.room.message`s to start with. The timeline can now use this, instead of trying to look into its items for the data it needs for the edit to work correctly; this helps get rid of `EditInfo`, which was an oversight from yours truly.
Part of #3663 too.
=> sdk: provide a way to create edit events

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/cache.rs
This patch fixes a bug where rooms stored in the sliding sync cache aren't restored by the `SlidingSyncBuilder`.
This patch also improves a test to ensure we don't break this in the future again.
=> fix(sdk): Sliding sync rooms aren't restored from the cache

bindings/matrix-sdk-ffi/CHANGELOG.md, bindings/matrix-sdk-ffi/src/widget.rs
It is possible to remove the m.call capability because we now have merged and released a version that does not request it anymore on call.element.io
Signed-off-by:
=>  element call(ffi): add widget permissions for room create and call member state keys with device id

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs, testing/matrix-sdk-integration-testing/src/tests/timeline.rs
This reverts the removal of the test done in https://github.com/matrix-org/matrix-rust-sdk/pull/3691, since the test is actually useful (it makes sure the apps don't get spurious updates about the room list), and was indeed badly written (two syncs running at once for one client — good catch on that for the other test @Hywan!).
This rewrites it in such a way that it should fail fast; it's been pretty solid for me locally, let's see how CI likes it…
=> integration tests: reinstate no spurious room update test

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/src/media.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk/src/media.rs, crates/matrix-sdk/tests/integration/media.rs
=> sdk: Allow to request animated thumbnails

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/latest_event.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
Currently on Element X if you receive a sticker in a room, the room list will show the room as updated but it will show the latest event that is not a sticker. This change fixes that.
Signed-off-by: 
Marco Antonio Alvarez <surakin@gmail.com>
=> matrix_sdk_base: make sticker events suitable as latest_event

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/http_client/native.rs
This will mean the client only trusts the CAs provided by `add_root_certificates`.
I am not really sure how we should test this given https://github.com/LukeMathWalker/wiremock-rs/issues/58 means we can't yet use wiremock for that (and even then, that would only prove it worked with the added CA, it wouldn't prove it rejected one of the system CAs) 🤔
=> FFI: Allow a Client to be built that doesn't trust built in CAs.

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/mod.rs
Small follow-up to #3676 that makes 2 small changes:
- Ignore a `Session`'s sliding sync proxy when restoring a client in the FFI so we don't have to do it in both EXI and EXA.
- Ignore a custom sliding sync proxy when building a client with support for SSS (not tested that one specifically but seemed worth adding whilst writing the other one).
=> FFI: Allow restoring an existing session with SSS enabled.

Cargo.lock, Cargo.toml
This patch updates the `rev` of our `ruma`'s fork to match the latest commit of our `feat-sss` branch, see
https://github.com/ruma/ruma/commit/f25b3220d0c3ece7720020ed180af4955a855402. It adds `m.room.create` in the `bump_event_types` of a `v4::SyncRequestList` (equivalent of a `v5::request::List`).
=> fix(sdk): Add `m.room.create` to `bump_event_types` for sliding sync

crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
The `RoomList` provides a `Stream<Item = Vec<VectorDiff<Room>>>`. This `Stream` receives updates from 2 sources: `RoomList::entries`, and `Receiver<RoomInfoNotableUpdate>`. When a `RoomInfo` is updated, a notable update is emitted and broadcasted. The `RoomList` was filtering these notable updates by _reasons_ (namely `RoomInfoNotableUpdateReasons`).
This is great and it's a good idea since we can filter which `RoomInfoNotableUpdate` will trigger a `RoomList` update. However, too many _reasons_ were hidden/implicit, and it creates several regressions because (i) these _reasons_ were implicit, (ii) since the business rules are not defined, there is no tests for that (not in this SDK, not in apps like ElementX). It means we discover missing _reasons_ bug after bug. It's not pleasant.
The …
=> fix(ui): `RoomList` reacts to all `RoomInfoNotableUpdate`

Cargo.lock, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/user.rs
This PR merges the 0.7 release branch back into main, mainly to update our changelog accordingly and bump the version that got released.
=> Merge the 0.7 release branch back into main

crates/matrix-sdk-sqlite/Cargo.toml
Merging this into the release branch, we bumped the vodozemac version so we need to do releases of all the crates that depend on vodozemac.
A bit of a mess, there should have been a patch release of vodozemac instead.
=> sqlite: Bump the version

crates/matrix-sdk-qrcode/Cargo.toml
Same as https://github.com/matrix-org/matrix-rust-sdk/pull/3735. But for the matrix-sdk-qrcode crate.
=> qrcode: Bump the version

crates/matrix-sdk-base/src/sliding_sync/mod.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk/src/sliding_sync/client.rs
The sliding sync proxy has a bug: despite the presence of
`m.room.create` in `bump_event_types`, an invite with an `m.room.create`
event will not have a `timestamp`. Thus, such a room cannot be sorted
reliably.
This patch fixes this problem with a terrible hack, where it tries to
find an `origin_server_ts` value from within the `invite_state` state
events.
Please read the comment to learn more.
=> fix(base): Fix a bug when an invite has no timestamp

crates/matrix-sdk/src/room/edit.rs, crates/matrix-sdk/tests/integration/event_cache.rs, crates/matrix-sdk/tests/integration/room/joined.rs
If the event cache isn't enabled, we should try to use /event instead.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3722
=> `make_reply_event`: don't require the event cache to be enabled for the API to work

crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs
As it says on the tin. Needed the functions but they were missing. They are analogous to the GlobalAccountData setters.
Signed-off-by: Benjamin Kampmann <ben@acter.global>
=> Add set_account_data to room, too

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/builder.rs
Oversight on my part in #3723, this code needed to handle the discovered proxy as well as the custom one.
=> SDK: Ignore the discovered/custom sliding sync proxy when using SSS.

crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
A tiny change to this method interface to make it easier to call from different parts of the code.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3546
=> crypto: Simplify the interface of search_for_device

crates/matrix-sdk-crypto/src/machine.rs
These calls are equivalent because the old code called `self.get_user_devices` with a `timeout` of `None`, which meant the call to `wait_if_user_pending` inside was a no-op.
=> crypto: Re-use existing get_device_from_curve_key method

crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync/mod.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs
This can be used to subscribe to pinned event ids in a room.
Implements the first part of https://github.com/matrix-org/matrix-rust-sdk/issues/3726.
Signed-off-by:
=> sdk-base: add `Room::pinned_events(&self)` 

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/tests/integration/encryption.rs, crates/matrix-sdk/tests/integration/encryption/cross_signing.rs, examples/cross_signing_bootstrap/src/main.rs, examples/oidc_cli/src/main.rs
This method supports OIDC as well as the usual UIAA method of cross-signing reset, it attempts to guide the user more easily towards a successful reset.
The cross-signing bootstrap example was modified to use the new method and the functionality was exposed in the oidc-cli example as well.
=> sdk: Add a higher level method to reset the cross-signing keys

crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/migrations/state_store/005_send_queue_dependent_events.sql, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
Part of #3663.
Commit 1 introduces a way to store "dependent events", that is, events that depend upon another one being sent for their completion. Dumb CRUD code, if you ask me. One important thing to note: we don't delete an event's dependents when it's been sent by the send queue, because the dependent events live their own lives independently of the send queue event they're attached to.
Commit 2 introduces a way to "canonicalize" dependent events. If you request a thousand edits and one redaction, then only the redaction is meaningful. This function filters out useless dependent events and only keeps those that will have a final effect.
Commit 4 makes use of the dependent events in storage:
- if a send queue event is being sent, then we remember the intent to edit/redact it later, via …
=> send queue: implement dependent events

Cargo.lock, crates/matrix-sdk/Cargo.toml
There's a published 4.0.0-alpha.2 version that compiles and doesn't require the custom changes we needed.
Part of #3742.
=> dependencies: get rid of custom fork of openidconnect-rs

Cargo.toml, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs
This MR introduces basic functionality for sending and stopping live location shares, as outlined in the [Matrix Spec Proposal #3489](https://github.com/matrix-org/matrix-spec-proposals/pull/3489). This foundational support allows users to share their live location, setting the stage for further enhancements.
**Key Changes**
- Live Location Start: Saving and sending an initial `beacon_info` state event.
- Live Location Stop: Stopping a users existing `beacon_info` state event from the state store.
These changes were adapted from a previous MR discussion, available for reference [here](https://github.com/matrix-org/matrix-rust-sdk/pull/3621).
**Follow-up**
Future MRs will expand on this initial implementation, using a layered approach to fully realize the functionality described in the …
=> sdk: basic support for sending and stopping live location shares

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3754
When we are verifying who sent a session, make sure we do the "backwards" check that the device we have found is actual the owner of the session.
Review commit by commit
=> crypto: Check the device owns the session in SenderDataFinder

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk/src/room/mod.rs, testing/matrix-sdk-test/src/sync_builder/test_event.rs, testing/matrix-sdk-test/src/test_json/sync_events.rs
- Adds `fn Timeline::pin_event`, `fn Timeline::unpin_event` and exposes them through the FFI.
- Adds `fn Room::can_user_pin_unpin` to make sure the user can perform the action.
- Exposes the currently pinned event ids using `RoomInfo`.
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/3747
Signed-off-by:
=> sdk & ffi: add `pin_event` and `unpin_event` fns, as well as power level checks

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/beacon/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/room/mod.rs
This MR introduces basic functionality for sending beacons associated with a live location share, as outlined in the https://github.com/matrix-org/matrix-spec-proposals/pull/3489. This foundational support allows users to send their live location beacon.
**Key Changes**
- `send_location_beacon`: simple support for sending a `beacon` message event with related `beacon_info` event id.
These changes were adapted from a previous MR discussion, available for reference [here](https://github.com/matrix-org/matrix-rust-sdk/pull/3621).
**Follow-up**
This does not save any `beacon` message events with its associated `beacon_info`. This MR simply introduces `beacon` sending support with the intention of follow on MRs to build on this basic functionality.
Signed-off-by:
=> sdk: basic support for sending location beacons

crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
This means we have all the information inside SenderData to populate VerificationStatus and DeviceId for EncryptionInfo, so we can share the code between SenderDataFinder and get_verification_state.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3751
=> crypto: Store device_id in SenderData

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs
Make the return type of is_owner_of_session more specific, so we can use it in contexts that expect e.g. an `OlmError` instead of `MegolmError`.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3751
=> crypto: Make the return type of is_owner_of_session more specific

crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs, crates/matrix-sdk/Cargo.toml
The feature is now a no-op.
Will fix (I hope) https://github.com/element-hq/element-android/issues/8872
=> Make `message-ids` feature the default

bindings/matrix-sdk-ffi/src/encryption.rs, bindings/matrix-sdk-ffi/src/ruma.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs, crates/matrix-sdk/tests/integration/encryption/recovery.rs
This PR adds support for completely resetting the user's identity and all their secrets. It will go through the following steps:
1. Disable backing up room keys and delete the active backup
2. Disable recovery (We can't delete account data events)
3. Remove previously known secrets by creating a new store (?)
4. Go through the cross-signing key reset flow
5. Finally, re-enable key backups only if they were enabled before
=> ffi: add high level method for resetting the user's identity and deleting all associated secrets

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
Replace the implementation of `get_verification_state` with `SenderDataFinder`, since they are now equivalent.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3751
As part of developing this PR, I created (and then removed) this commit: 282320f79ed2447d2d39f4ca7f60df02dbfb5a2f which proves that for every case, converting from `SenderDataFinder`'s result into a `VerificationState` and an `Option<DeviceId>` produces the same result as the old `get_verification_state` code, so we can safely replace it.
=> crypto: Replace the implementation of get_verification_state with SenderDataFinder

Cargo.lock
=> chore: Update the bytemuck crate

crates/matrix-sdk-crypto/src/machine.rs
This is the key PR that implements the significant part of https://github.com/matrix-org/matrix-rust-sdk/issues/3751 - lazily updating SenderData inside an InboundGroupSession whenever we decrypt a message.
=> crypto: Store the updated SenderData in the store when we calculate it

crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/shields.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/profiles.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
This PR makes the following changes:
- Add a property to the timeline so that it knows whether the room is encrypted or not.
- Pass this value when building timeline items and use it inside `get_shield` to add a new ShieldState.
- Add tests for the ShieldState of an unencrypted item in both and encrypted and unencrypted timeline.
=> UI Timeline: Build a ShieldState for an unencrypted event in an encrypted room.

crates/matrix-sdk-ui/src/timeline/mod.rs
This tiny change allows one to easily name the return type of `EventTimelineItem::reactions()` such that you can use it in a function signature. Same goes for the `ReactionInfo` type.
I think this was likely just a small oversight in recent changes to the reactions API, so hopefully it's not controversial.
Without this, it's impossible to write a function that uses `ReactionsByKeyBySender` or `ReactionInfo` in the signature.
Signed-off-by: Kevin Boos <kevinaboos@gmail.com>
=> timeline: re-export `ReactionsByKeyBySender` and `ReactionInfo` types

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/shields.rs
Small fix following on from #3783 as local echoes were always showing as `SentInClear` due to the `encryption_info` not being [available](https://github.com/matrix-org/matrix-rust-sdk/blob/7c5c5a8f307a29ac03d7f6de4b1ed41e526a7e7b/crates/matrix-sdk-ui/src/timeline/event_item/mod.rs#L365).
Will need a rebase after #3786 to add the `code` field (or vice versa).
=> Timeline: Fix a bug where local echoes were showing unencrypted shields.

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
part of invisible crypto, follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/3607
Alternative fix for  https://github.com/matrix-org/matrix-rust-sdk/issues/3564
Alternative PR https://github.com/matrix-org/matrix-rust-sdk/pull/3610
Add the capability to locally pin a public MSK for a `ReadOnlyUserIdentity`. 
The first time an identity is seen for a user, the msk is pinned. Pin violation will be reported when an identity is rotated.
This PR only adds support for pinning, support for serialization/migration, persistance. 
This could be used later by other PRs to report specific errors or show pinning violation to users.
Note about verification and pinning.
As part of this PR, if a new identity is detected it will still be seen as a pinning violation even if the new identity is …
=> feature(crypto): Add support for master key local pinning

crates/matrix-sdk-crypto/src/identities/device.rs
I found some of this comment a bit hard to grok, so I've expanded it a bit. Hope it's clear to others.
=> crypto: clarify/expand comments in `Device::is_owner_of_session`

Cargo.lock, benchmarks/Cargo.toml, benchmarks/benches/room_bench.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync/mod.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/error.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/main.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs, testing/matrix-sdk-test/src/test_json/sync_events.rs
- Create a new type of `TimelineFocus`, `TimelineFocus::PinnedEvents` that will use the pinned event ids in `RoomInfo` to load the associated events, cache them and sort them chronologically.
- Create `PinnedEventsRoom` trait to be able to provide the necessary data to the new timeline type.
- Change the `is_live` parameter used in the `Timeline` code for a `LiveTimelineUpdatesAllowed` enum to distinguish between timelines that need to process every update (live timeline), those who don't need to process any (the focused one) and those which may need to process *some* items (pinned events one).
- Add tests and a benchmark for the concurrent pinned event loading.
Signed-off-by:
=> sdk-ui: Add `TimelineFocus::PinnedEvents`

crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs, crates/matrix-sdk/tests/integration/encryption/recovery.rs
This PR handles 2 different issues:
1) The normal `backups().disable` method does not delete the remote backup if the backups haven't been setup yet locally
2) and it doesn't throw an error or reset the backup state when that happens
We've introduced a new `delete_backup` method what **will** delete remote backups and that can be used from the identity reset flows to correctly setup the fresh session.
=> Identity reset backup fixes

.github/workflows/bindings_ci.yml, bindings/matrix-sdk-ffi/build.rs
This seems to fix the Kotlin bindings issues we were seeing until now. And no more workaround needed it seems!
Signed-off-by:
=> Use NDK 27 for the Kotlin bindings

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/pinned_events_cache.rs
- Moves the `PinnedEventCache` from `sdk-ui` to `sdk` so it can work in the same way as `EventCache`, attached to a `Client`.
- Remove the `PinnedEventCache` included inside `PinnedEventsLoader`, now you need to provide a cache for the loading event methods.
- Add a way to clear the cached pinned events for a room.
- Add a test to verify this change works as expected.
Loading pinned events is expensive and slow-ish for rooms with lots of them since we have no bulk `/event` or `/context` endpoint to load a set of events given their event ids, and we need to perform those requests concurrently. To avoid this, a cache was added, but it only worked for events you had already loaded in the same `Timeline` instance so if you exited the room and entered it again you'd still have to reload every …
=> sdk: add global `PinnedEventCache` instead of having a single instance per timeline

Cargo.lock, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/shields.rs
Following on from the conversation over on https://github.com/element-hq/element-x-ios/pull/3051#discussion_r1680872736 this PR adds a `code` field to the `ShieldState` so that it can be easily mapped by apps that need to provide a translated description to the user.
Note: This PR also adds uniffi to the matrix_sdk_common crate to avoid a duplicate type in the FFI for the code.
=> Shields: Add a code field for easier mapping of the state.

benchmarks/benches/room_bench.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs, crates/matrix-sdk/src/room/mod.rs
- Use reversed chronological order for the events, as the rest of the timelines do.
- Add `fn sdk::Room::clear_pinned_events_cache`, previously this was only in the FFI layer.
- Fix benchmark and tests after the changes above.
Signed-off-by:
=> Fixes for the `TimelineFocus::PinnedEvents` timeline

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
This error will be returned when the room has pinned event ids but the timeline couldn't load any of them. 
We need to make this distinction instead of just failing as soon as the first request fails because we don't want an incorrect pinned event id to break loading any other existing events, or have a single failed request with poor connectivity to invalidate the rest of them.
Also fix and add new tests.
Signed-off-by:
=> sdk-ui: add `PinnedEventsLoaderError::TimelineReloadFailed`

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
After discussion with @richvdh we realised that the policy we agreed earlier for initial creation of SenderData applies here too: if the sender is known, we stick with that and don't recalculate to find out whether they are verified.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3751
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3782
=> crypto: Don't recalculate SenderData if the sender is known but not verified

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
This PR is another step in the https://github.com/matrix-org/matrix-rust-sdk/issues/2624 epic. It moves the Olm `Session` cache from each individual cryptostore implementation to the `CryptoStoreWrapper`.
While the wrapper shouldn't be the final destination for this cache it does help with our current multi-process support which relied on the `CryptoStore::clear_caches()` method. This method is now gone and no further caches should be added to the store implementations.
Review commit by commit isn't advised as the API changed and changed back when the cache was removed and re-added.
=> Remove the Session cache from the cryptostore implementations

crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-ui/src/timeline/tests/shields.rs
The new message is more understandable in the timeline context and is consistent with current implementations (Element Web)
=> Timeline: Update the human readable description for the SentInClear shield.

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
This way it matches the rest of timelines in the SDK, I reversed it here because I didn't realise most clients just do this reversal of ordering themselves. As they do, they need the same order for this timeline too to be able to reuse their existing logic.
Signed-off-by:
=> sdk-ui: reverse (again) the order in the pinned events timeline

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk/src/room/mod.rs
This method works the same as `Room::event` but you can provide a custom `RequestConfig` to it.
It's especially useful for the pinned events timeline, since we need a max number of retries and a max number of concurrent requests. With this we can remove some unnecessary complexity.
Related but not depending on https://github.com/matrix-org/matrix-rust-sdk/pull/3807.
Signed-off-by:
=> sdk-ui: add `fn Room::event_with_config`

bindings/matrix-sdk-ffi/src/client_builder.rs
Without this, the default request config would always be used. This meant having unlimited retries for almost every request, even with no network connection.
Signed-off-by:
=> ffi: allow the clients to provide a custom `RequestConfig`

.typos.toml, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1129
Signed-off-by:
=> Crypto | Add support for verified identities change detection.

bindings/matrix-sdk-ffi/src/widget.rs
Before we set them for reading events which is not required since:
```rust
read: vec![
WidgetEventFilter::StateWithType { event_type: StateEventType::CallMember.to_string() },
]
```
already covers all keys. And an additional `@` was used resulting in:
`@@user_id:demain.org_DEVICEID` and `_@@user_id:demain.org_DEVICEID`.
This also made it obvious that we need unit tests for this ffi method!
(We currently use the tauri widget wrapper to do manual end to end tests for the widget driver. But the ffi layer is not part of the tauri app. The testing cycle for EX is cumbersome without merging the changes.
Offtopic: any ideas or recommendations how to mitigate this in the future are welcome)
Signed-off-by:
=> FFI Element Call: Fix the permission list returned by the `get_element_call_required_permissions` ffi function.

bindings/matrix-sdk-ffi/src/encryption.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/recovery/mod.rs
Works around swift issue where nil-ing the handle is not enough for it to get cancelled.
=> ffi: provide manual cancellation mechanism for identity/cross-signing reset handles

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/mod.rs, labs/multiverse/src/main.rs
This patch changes the `SlidingSync::subscribe_to_room` method to `subscribe_to_rooms`. Note the plural form. It's now mandatory to subscribe to a set of rooms. The idea is to avoid calling this method repeatedly. Why? Because each time the method is called, it sends a `SlidingSyncInternalMessage` of kind `SyncLoopSkipOverCurrentIteration`, i.e. it cancels the in-flight sliding sync request, to start over with a new one (with the new room subscription). A problem arises when the async runtime (here, Tokio) is busy: in this case, the internal message channel can be filled pretty easily because its size is 8. Messages are not consumed as fast as they are inserted. By changing this API: subscribing to multiple rooms will result in a single internal message, instead of one per room. …
=> feat(sdk): Subscribe to many rooms only via Sliding Sync

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
We should only show the spinner if the *first* sliding sync request is taking a while. If we have received some data and the second request takes a while, that is OK.
For the state transition of `Init -> SettingUp` this is handled correctly, however for `Terminated -> Recovering -> Running` we waited until the second request returned before hiding the sync spinner. This meant that if the first request returned quickly the app would show new data and *then* the sync spinner would show (if the second request took time).
This situation occurs frequently with the new SSS API, where if all the new data was returned in the first sync then the second sync would block waiting for new data, triggering the sync spinner.
--- 
Not sure if this needs a changelog entry, as it really only is noticeable …
=> Sync: Don't spuriously show spinner

benchmarks/benches/crypto_bench.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine/mod.rs, crates/matrix-sdk-crypto/src/machine/test_helpers.rs, crates/matrix-sdk-crypto/src/machine/tests/decryption_verification_state.rs, crates/matrix-sdk-crypto/src/machine/tests/mod.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, testing/matrix-sdk-test/src/lib.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
We had *two* copies of `response_from_file`, and all calls to them were always immediately followed by an operation to parse the response as a Ruma response object.
We can save a whole lot of boilerplate with a generic function that wraps the json into an HTTP response *and* parses it into a Ruma object.
=> testing: create `ruma_response_from_json`

crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/sticky_parameters.rs
This PR is a tiny collection of really small patches I've done while trying to debug bugs about the sliding sync native implementation.
=> Tiny collection of tiny small edits around Sliding Sync

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
The patch https://github.com/matrix-org/matrix-rust-sdk/pull/2395 has introduced `SlidingSyncInner::past_positions` as a mechanism to filter duplicated responses. It was a problem because the sliding sync `ops` could easily create corrupted states if they were applied more than once.
Since https://github.com/matrix-org/matrix-rust-sdk/pull/3664/, `ops` are ignored.
Now, `past_positions` create a problem with the sliding sync native implementation inside Synapse because `pos` can stay the same between multiple responses.
While `past_positions` was helpful to fix bugs in the past, it's no longer necessary today. Moreover, it breaks an invariant about `pos`: we must consider it as a blackbox. It means we must ignore if a `pos` value has been received in the past or not. This invariant has …
=> fix(sdk): Remove `SlidingSyncInner::past_positions`

crates/matrix-sdk/src/sliding_sync/mod.rs
This patch restricts the call to `compute_limited` to the sliding sync proxy implementation (aka MCS3575). It is not necessary for the sliding sync native implementation (aka Simplified MSC3575). The proxy doesn't implement the `limited` flag, contrary to Synapse. Let's not run workarounds when we don't need them.
=> feat(sdk): `compute_limited` is only useful for the SS proxy

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk/src/pinned_events_cache.rs
To make the code more idiomatic, avoid having too many concepts, rename a few things, etc.
Next I'll merge the pinned event cache into the event cache, because there's no reason to have two different event caches.
=> pinned events: a collection of small refactorings

testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
`PreviouslyVerifiedTestData` is currently an unfortunate code dump. Attempt to make it a bit less write-only with some explanation of wtf the methods do.
=> Test: improve documentation of `PreviouslyVerifiedTestData`

Cargo.lock, Cargo.toml, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs
Update Ruma dependency to expect call membership state events with state keys that are arbitrary strings, not just pure MXIDs.
When a call membership state key does not exactly match the format of an MXID, treat it as a valid state key if it starts with an MXID followed by an underscore, with that MXID designating the owner of the event.
(The state key may also be optionally prefixed with an underscore, which is permitted as a way to bypass pre-MSC3757 authorization rules against sending state events with state keys that do not exactly match the sender's MXID.)
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
=> rtc: Handle non-MXID call member event state keys

bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine/tests/mod.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3792
Suggest review commit-by-commit.
=> Crypto: Return an error when sharing a room key to a verified user, who has an unverified device (optional encryption setting)

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs
This fixes left rooms not disappearing from the room list.
Signed-off-by:
=> sdk-base: Add `RoomInfoNotableUpdateReasons::MEMBERSHIP`

bindings/matrix-sdk-ffi/src/room_info.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/notification_settings.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/migration_helpers.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sliding_sync/client.rs
This patch should be reviewed commit by commit.
In `matrix_sdk_ffi::RoomInfo`, there is a `user_defined_notification_mode` field. To compute a value for this field, it takes quite a non-negligeable amount of time because the store is hit (because the account data must be read to compute a `NotificationSettings` object). If a lot of `RoomInfo` are created (it happens in some apps that want to display a lot of rooms), it can quickly create a performance bottleneck.
This pull request solves the problem by caching the result of `Room::user_defined_notification_mode()` into `Room::cached_user_defined_notification_mode()`. This cache is updated for every sync, similarly to what we do for the room name for example.
This time, it's a bit different as this mechanism happens in `matrix-sdk` instead …
=> feat(sdk): Add `Room::cached_user_defined_notification_mode`

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs
There are a set of methods in `OwnUserIdentityData` and `OtherUserIdentityData` which return an error if a device or identity is unverified. All the callers end up calling `is_ok()` on the result, so we may as well just return a bool.
=> crypto: change `Identity::is_x_signed` methods to return bool

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/user.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
A follow-up to #3795, which extends the same principle to `OwnUserIdentity`.
Fixes #3845.
=> crypto: Remember whether our own identity has been verified

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk/src/encryption/identities/users.rs
We have a bunch of methods which are the same in both `OtherUserIdentity` and `OwnUserIdentity`, so add some convenience methods to access them.
=> Crypto: add helper methods to `UserIdentities`

bindings/matrix-sdk-ffi/src/platform.rs
This patch fixes a bug in the tracing system. It introduces one
fields formatter _per layer_ to force the fields to be recorded in
different span extensions, and thus to remove the duplicated fields in
`FormattedFields`.
The patch contains links to the bug report in `tokio-rs/tracing`. This
patch is a workaround.
---
* Fix #3494
=> fix(ffi): New fields formatter to remove duplicated span fields

crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/edit.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs, crates/matrix-sdk-ui/src/timeline/tests/invalid.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/polls.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs, crates/matrix-sdk-ui/src/timeline/tests/shields.rs, crates/matrix-sdk-ui/src/timeline/tests/virt.rs, crates/matrix-sdk/src/test_utils/events.rs
By using the `EventFactory` a bit more.
Part of #3716.
=> test: get rid of `TestTimeline::handle_live_message_event` in favor of `handle_live_event`

crates/matrix-sdk-crypto/Cargo.toml
It seems that the fact that matrix-rust-sdk contains `olm-rs` in its `Cargo.lock` sparked panic, so let's attempt to fend off future concerns by adding a comment.
=> crypto: add a note about libolm only being used in tests

crates/matrix-sdk-sqlite/src/crypto_store.rs
Most times we pulled an InboundGroupSession from the sqlite DB, we were overriding whatever value for `backed_up` was stored inside the pickled value, and using the value stored in the SQL column.
But when we pulled a single InboundGroupSession from the DB by ID, we did not override it.
I am fairly sure this was an accidental oversight, so this change corrects it, and unifies the code with other places we create these objects.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3544
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3862
=> crypto: In sqlite, use the SQL column value for backed_up everywhere

bindings/matrix-sdk-ffi/CHANGELOG.md, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/builder.rs
https://github.com/matrix-org/matrix-rust-sdk/pull/3810 added a new option to the `CollectStrategy` used when collecting recipients for encrypted room keys. We need to expose that to applications via the FFI bindings.
Part of https://github.com/element-hq/element-internal/issues/614
=> Expose `room_key_recipient_strategy` through higher-level SDK crates

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/tests/edit.rs
- this prevents issues where spoofing the sender field is enough to spoof and edit and display wrong decorations in the app
- fixes matrix-org/internal-config/issues/1549
=> timeline: use the `EncryptionInfo` provided by the replacement event when processing edits

crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This patch updates when sliding sync requests have a `timeout`.
Prior to this patch, all requests had a `timeout` query, set to the
`poll_timeout` duration value. However it means: if there is no data
to return, wait `timeout` milliseconds for new data before returning.
This definition is correct. Problem: if the current range of a list
has no data, the server will wait! It means that, in a situation where
there is no update at all, but the client is fetching all rooms batch by
batch, it will wait `poll_timeout` for each batch!
The behaviour described above is absolutely correct. Some server
implementations are less strict though, and we didn't realise our code
was doing that, because the server had some optimisations to ignore the
timeout if the range wasn't covering all the rooms. …
=>  feat(sdk): Sliding sync has a timeout if all lists require a timeout

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs
We're finding ourselves in the situation in which we can't interact with invites through normal Room APIs as `full_room`s can't be build from the RoomListItem. Full rooms require the timeline to be configured before use and the timeline can't be configured because encryption cannot be fetched for invited rooms on homeservers that have previews disabled (see #3848 and #3850)
In response we now expose the room's membership directly from the `RoomListItem` so that the final client can chose which of the 2 rooms types (invited or full) to ask for before using aforementioned APIs.
Powers https://github.com/element-hq/element-x-ios/pull/3189
=> ffi: expose room membership through the RoomListItem and allow invited rooms to be build differently than "full" ones

crates/matrix-sdk/src/sliding_sync/mod.rs
This patch clears all sliding sync room subscriptions when a session expires. Indeed, we might not want to request all room subscriptions when the session restarts. Imagine if the client has subscribed to 400 rooms and the session expires: once the session restarts, it will ask for 400 room subscriptions, which is a lot and will result in a quite slow response.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3647.
=> fix(sdk): Clear all sliding sync room subscriptions when session expires

Cargo.lock, crates/matrix-sdk-ui/tests/integration/main.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs, crates/matrix-sdk-ui/tests/integration/timeline/profiles.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs, crates/matrix-sdk-ui/tests/integration/timeline/replies.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/room/attachment/mod.rs, crates/matrix-sdk/tests/integration/room/beacon/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/send_queue.rs, crates/matrix-sdk/tests/integration/widget.rs, testing/matrix-sdk-test/Cargo.toml, testing/matrix-sdk-test/src/lib.rs, testing/matrix-sdk-test/src/mocks.rs
=> testing: add a mocks module in matrix-sdk-test to reuse mock endpoints across test suites

crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/test_utils/events.rs
- Creates a separate `AllEventsCache` struct holding both the actual all events cache map and the relationship one. This new cache wrapper also holds a single `RwLock` to both inner caches, as they are independent from each other.
- When a new event is saved either from `/sync` or another HS request, it'll be saved to both the 'all events' cache and the relationship map.
- Add tests for the relationship cache.
Signed-off-by:
=> sdk: add relationships cache to `EventCache`

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/reactions.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/src/timeline/util.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs, testing/matrix-sdk-integration-testing/src/tests/timeline.rs
Independently of #3749, we can, as of today, start using the send queue only to send reactions, instead of having the logic of sending reactions in the timeline itself
There was a mechanism to queue adding/removing a reaction, with the possibility to get observable updates for each add/remove that occurred. In some contexts, if you quickly tapped a reaction button on ElementX apps, you could observe it: the reaction would be added, then removed, then added back, etc. until it stabilized.
I don't see the user value for this: if I quickly tap the reaction button, I'd expect the sending of the reaction to be aborted, if it can, instead of delayed into a redaction event that's subsequently sent. The sending queue allows doing this for free, so making use of that.
I've also removed tests which …
=> timeline: only use the send queue mechanism to send reactions

crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/sticky_parameters.rs
This patch should ideally be reviewed commit-by-commit.
The problem the patch is trying to solve is the following: in sliding sync, for every new room subscriptions, all the previous room subscriptions are part of the request to be send. This is a waste of bandwidth. This patch adds the following feature: when a room subscription has been sent, it won't be part of the next request anymore. All room subscriptions are kept in memory though, but they are marked as `Applied` instead of `Pending` (see the new `RoomSubscriptionState` type).
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3647
=>  feat(sdk): Do not send a room subscription that has already been sent

Cargo.lock, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/pagination.rs, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/edit.rs
This series of patches, investigated using Fasterthanlime's [good advice](https://fasterthanli.me/articles/why-is-my-rust-build-so-slow#rustc-self-profiling), helped lowering the compiles times from 44 seconds to 4 on my machine, for the `matrix-sdk-ui` crate.
Compile times for the `matrix-sdk` crate have also been lowered from 33 to 12 seconds.
Overall, for a plain `cargo build`:
- before: 113 seconds
- after: 54 seconds
Each commit can be reviewed independently.
See also: https://github.com/rust-lang/rust/issues/87012
=> sdk: lower compile times

Cargo.lock, crates/matrix-sdk-base/CHANGELOG.md, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/failures_cache.rs, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-common/src/tracing_timer.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/README.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/room/beacon/mod.rs
This is a reexport of web-time.
Closes #2937.
=> chore: Use `ruma::time` instead of instant

crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine/mod.rs, crates/matrix-sdk-crypto/src/machine/tests/decryption_verification_state.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk/CHANGELOG.md
(Slightly-modified version of https://github.com/matrix-org/matrix-rust-sdk/pull/3856/)
As [previously discussed](https://github.com/matrix-org/matrix-rust-sdk/pull/3701/files#r1721932382)
=> crypto: Add variants to SenderData to represent different verification states

benchmarks/benches/room_bench.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/paginator.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/src/test_utils.rs, crates/matrix-sdk/tests/integration/room/common.rs, testing/matrix-sdk-integration-testing/src/tests/room.rs
This is a follow-up PR for https://github.com/matrix-org/matrix-rust-sdk/pull/3870.
- Make `TimelineEventBuilder` process synced events for `TimelineFocus::PinnedEvents` too.
- Use the relationship cache added in https://github.com/matrix-org/matrix-rust-sdk/pull/3870 to load pinned events and other events related to them so their final timeline event results contain the changes those would add (edits, redactions, reactions, etc.).
- Make `Room::event_with_context` also save its results to the cache.
- Add new tests for pinned events and related events.
- Fix the pinned events benchmark in `room_bench`.
The end result of this is the pinned events timeline now reacts to edits and redactions, and those values are kept even when the event list reloads.
Signed-off-by:
=> feat(sdk): Live updates for pinned events timeline with replacements and redactions

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/builder.rs
This PR is a follow-up to https://github.com/matrix-org/matrix-rust-sdk/pull/3858, exposing the ability to set a custom cache path in the FFI.
PR to fix the complement tests is [here](https://github.com/matrix-org/complement-crypto/pull/127) - will need merging after this one for CI to continue to be happy on `main`.
=> FFI: Expose the new cache store path to the bindings.

crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-sqlite/src/utils.rs
Allows the operation to be atomic, and to chunk part of a transaction.
I believe that this change makes sense on its own, but for context I will need to be able to chunk part of a transaction in an upcoming PR.
=> sqlite: Use a transaction for chunked queries

bindings/matrix-sdk-ffi/src/client.rs
Login via OIDC and username were exposed in the ffi, but login via email was seemingly not.  This adds a `login_with_email` method to the `Client` object.
Signed-off-by:
=> Expose login with email + password on the client

crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
This is part of https://github.com/matrix-org/matrix-rust-sdk/pull/3662, pulled out to into a separate PR.  Recent changes in `main` made it pretty much impossible to merge this section of code from `main` into that PR, and Rich wanted to see the refactoring bits separate from the behavioural changes.  So I've re-written the refactoring.
Pulls the `match` on `sharing_strategy` outside of the `for` loop, and moves any code that is specific to one strategy into the appropriate branch.
=> refactor collect_session_recipients in advance of some behavioural changes

crates/matrix-sdk-common/src/deserialized_responses.rs
If we're building for the wasm architecture, jump through the hoops to tell
wasm_bindgen about `ShieldStateCode`. This solves the need to declare an
identical copy of `ShieldStateCode` in the wasm bindings.
=> common: generate wasm bindings for ShieldStateCode on wasm architectures

crates/matrix-sdk/src/sliding_sync/mod.rs
On my version of clippy nightly, these lines triggered the [`filter_map_bool_then`](https://rust-lang.github.io/rust-clippy/master/index.html#/filter_map_bool_then) lint.
=> sdk: Handle a clippy nightly warning

.github/workflows/bindings_ci.yml, bindings/matrix-sdk-ffi/src/authentication.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/tests/integration/encryption/backups.rs, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs, testing/matrix-sdk-test/src/test_json/api_responses.rs
OK. So this PR should be reviewed commit-by-commit. It seems large, but most of the additions are tests.
This PR does 3 things. It's not possible to split them without breaking `main`.
1. It removes `requires_sliding_sync`, `sliding_sync_proxy`, `is_simplified_sliding_sync_enabled` and all these messy configurations that are super error-prone (and that already contain at least one bug, e.g. it's possible to define a sliding sync proxy URL with simplified sliding sync enabled at the same time; now: which one is used? no error, but simplified sliding sync is taking precedence). Everything is replaced by a single, unique, simple:
```rust
enum Version {
None,
Proxy { url: Url },
Native,
}
```
It feels much better after that:
- The “no sliding sync” state is represented by `None`.
- The …
=> feat(sdk): Welcome `sliding_sync::Version` and `sliding_sync::VersionBuilder`

crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
We are supposed to run the cryptostore integ tests twice for indexeddb: once with encryption enabled, and once without.
We are no longer running the tests without encryption. I think this was accidentally removed in [#3799](https://github.com/matrix-org/matrix-rust-sdk/pull/3799/commits/3dae56d34338086aa681e3a5a932a9f4c9d86570#diff-a6cc12d0312753050af771b6007b12f02f0997e8578eeb0a11a17df87f79817aL1804).
=> indexeddb: Reinstate crypto store integration tests

crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/event_cache_store.rs, crates/matrix-sdk-sqlite/src/lib.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-sqlite/src/utils.rs
To make it easier to understand what the types and traits do, rename:
- `SqliteConn` to `SqliteAsyncConn`,
- `SqliteObjectExt` to `SqliteAsyncConnExt`
- `SqliteConnectionExt` to `SqliteKeyValueStoreConnectionExt`
- `SqliteObjectStoreExt` to `SqliteKeyValueStoreAsyncConnExt`.
And refactor the code to put more methods in `SqliteKeyValueStoreAsyncConnExt`, to avoid free functions that take an `&SqliteAsyncConn` and reduce code duplication.
=> sqlite: Rename types and traits and refactoring

bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-ui/src/timeline/day_dividers.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/reactions.rs, crates/matrix-sdk-ui/src/timeline/util.rs, crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs, testing/matrix-sdk-integration-testing/src/tests/timeline.rs, xtask/src/ci.rs
=> send queue: allow sending reactions to local echoes

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/http_client/native.rs, crates/matrix-sdk/src/send_queue.rs
Otherwise, this would mean that logged out clients would infinitely repeat network requests failing in the background.
Without this fix, the added test will time out, endlessly reattempting network requests.
Closes #3901.
=> http client: don't infinitely retry network failures if there's no retry limit

crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/event_cache_store.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-sqlite/src/utils.rs
Setting the version number only when all migrations are done means that the version of the db will be wrong if a migration fails.
So this sets the version of the database for each migration transaction.
This includes also a related second commit that merges `init` and `run_migrations` for `SqliteEventCacheStore`, since they don't need to be separate like in `SqliteStateStore`.
=> sqlite: Make migrations atomic

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/send_queue.rs
Tiny commits, see their descriptions.
=> ffi: use the send queue for out-of-timeline edits

crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v8_to_v10.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
This PR has no functional changes -- it's just refactoring in preparation for later functional changes.
I'm soon going to be adding three more fields to `InboundGroupSessionIndexedDbObject`. Rather than keep adding more and more arguments to `InboundGroupSessionIndexedDbObject::new`, we might as well construct the object directly.
Futher, there are two copies of the same code to construct an `InboundGroupSessionIndexedDbObject` from an `InboundGroupSession`. Let's factor the common logic into a new function called `InboundGroupSessionIndexedDbObject::from_session`.
=> indexeddb: simplify construction of `InboundGroupSessionIndexedDbObject`

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
There's already the right logic to not *add* new timeline items to a non-live timeline, so adding a message etc. will not show it in a pinned / permalinked timeline. On the other hand, *updating* a timeline item (reaction/redaction/edit) will affect it, no matter the type. So we can handle local echoes of those types for those timeline items, such that they're displayed in real-time on all foci.
The added test would fail before the patch.
=> timeline: allow all foci to handle local echoes

crates/matrix-sdk-indexeddb/src/crypto_store/migrations/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v0_to_v5.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v10_to_v11.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v5_to_v7.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v7_to_v8.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v8_to_v10.rs
For some operations (notably: adding an index to an existing object store), we need access to the database transation during the upgrade operation.
This isn't used yet, but I wanted to pull it out to a separate PR to slim down https://github.com/matrix-org/matrix-rust-sdk/pull/3806 a bit.
=> indexeddb: Pass the db transaction into do_schema_upgrade closures

crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk/src/test_utils/events.rs
Might fix issues like https://github.com/element-hq/element-x-android-rageshakes/issues/2585 or items morphing into other items as in https://github.com/element-hq/element-x-ios/issues/3206.
=> timeline: don't clear the internal counter in presence of local echoes

crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
Tidying up and resolves potential bugs around handling of read receipts in theory.
=> timeline: simplify `should_add` management, and document it better

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/builder/homeserver_config.rs, crates/matrix-sdk/src/client/builder/mod.rs, crates/matrix-sdk/src/client/mod.rs
This patch adds `Client::server` as an `Option<Url>`. This should not be confused with the `homeserver`. For example, in the case of Matrix, `matrix.org` is the server, and `matrix-client.matrix.org` is the homeserver.
This patch should be reviewed commit-by-commit for the sake of simplicity. Code is moved into their own module for clarity.
=> feat(sdk): Add `Client::server`

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync/client.rs
The `.well-known` file is located on the server, not the homeserver. This patch fixes that along with the associated tests.
=> fix(sdk): Sliding sync discovers the proxy on the server, not the homeserver

crates/matrix-sdk/src/client/builder/homeserver_config.rs, crates/matrix-sdk/src/client/builder/mod.rs
This patch renames `HomeserverConfig::Url` to `HomeserverUrl`, and `HomeserverConfig::ServerNameOrUrl` to `ServerNameOrHomeserverUrl`. Funnily, the methods on `ClientBuilder` doesn't need to be renamed to match the new naming since they already use this naming!
=> chore(sdk): Rename `HomeserverConfig` variants

crates/matrix-sdk-crypto/src/machine/mod.rs, crates/matrix-sdk-crypto/src/types/events/olm_v1.rs
MSC4147 adds a `device_keys` property to the plaintext content of encrypted to-device events, and support for picking this out was added in #3556/#3633.
Turns out it's quite handy to log this information.
The output of this is something like:
```
2024-08-30T14:40:27.061681Z DEBUG receive_sync_changes:receive_to_device_event{sender="@alice:example.org" event_type="m.room.encrypted" message_id="01J6HVNZXBPF860R0TBH3H75KZ"}:handle_decrypted_to_device_event{sender_key="curve25519:CpEg1cKt2OiASokDD23L9/buqT7LAkcUEVaFXaBSCFU" event_type="m.room_key"}: matrix_sdk_crypto::machine: Received a decrypted to-device event sender_device_keys=(Some("curve25519:CpEg1cKt2OiASokDD23L9/buqT7LAkcUEVaFXaBSCFU"), Some("ed25519:aEMaB1+jf3tzIRdyNzI514m1czCra9W23JwYXho27iw"))
```
=> crypto: Log the received device keys on an encrypted olm message

crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
Turns out that most of the places we call `find_using_device_keys`, we already have a DeviceData. So we might as well pass that in directly, rather than extracting the device keys and then rebuilding a DeviceData.
=> crypto: expose `SenderDataFinder::find_using_device_data`

crates/matrix-sdk-crypto/src/machine/test_helpers.rs, crates/matrix-sdk-crypto/src/machine/tests/megolm_sender_data.rs, crates/matrix-sdk-crypto/src/machine/tests/mod.rs, crates/matrix-sdk-crypto/src/olm/session.rs
Some high-level tests to check that sender data on received group sessions works correctly.
=> crypto: Add some integration tests for sender_data functionality

crates/matrix-sdk-sqlite/src/event_cache_store.rs
Avoids errors when the read transaction tries to upgrade to a write transaction (see [SQLite docs](https://sqlite.org/lang_transaction.html#read_transactions_versus_write_transactions) for details).
=> sqlite: Update last access time first to force write transaction

Cargo.lock, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v11_to_v12.rs, crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs, crates/matrix-sdk-sqlite/migrations/crypto_store/009_inbound_group_session_sender_key_sender_data_type.sql, crates/matrix-sdk-sqlite/src/crypto_store.rs
This PR adds a new method `CryptoStore::get_inbound_group_sessions_for_device_batch`, which is required for us to be able to update the information we hold about inbound group sessions when we get a `/keys/query` response (https://github.com/matrix-org/matrix-rust-sdk/issues/3753).
Strongly suggest reviewing commit-by-commit!
Fixes #3752
=> crypto: Allow querying InboundGroupSessions using curve key

.github/workflows/bindings_ci.yml
It's been disabled in https://github.com/matrix-org/matrix-rust-sdk/pull/3889. Now that https://github.com/matrix-org/complement-crypto/pull/128 has been merged, we can re-enable Complement Crypto.
=> test: Restore Complement Crypto

crates/matrix-sdk-ui/src/room_list_service/sorters/recency.rs
This is not a timestamp but a regular stamp. Make it clear with the variable names.
=> chore(ui): Rename variables

bindings/matrix-sdk-ffi/CHANGELOG.md, bindings/matrix-sdk-ffi/src/timeline/mod.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs, testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
This is the rest of https://github.com/matrix-org/matrix-rust-sdk/pull/3662, on top of https://github.com/matrix-org/matrix-rust-sdk/pull/3884.
3662 says:
> Part of invisible crypto, follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/3639
>
> Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3565
Signed-off-by:
=> crypto: Error when sending keys to previously-verified users with identity-based strategy

crates/matrix-sdk/src/client/builder/mod.rs, crates/matrix-sdk/src/event_cache/mod.rs, crates/matrix-sdk/src/event_cache/pagination.rs, crates/matrix-sdk/src/room/mod.rs
These were found while looking at rageshakes involving missing initial local echoes, but I didn't get my head around it this time. Oh well.
=> sdk: tiny refactorings

bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/controller/mod.rs, crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/send_queue.rs, crates/matrix-sdk/tests/integration/send_queue.rs
* add a generic mechanism for unwedging and resending requests based on their transaction identifier
* expose methods for manually withdrawing certain users' verification or trusting their devices and resending failed messages
This will be used in conjunction with the send errors introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/3866 to allow the user to force resend failed messages after manually resolving trust issues.
Fixes #3839, fixes #3838, fixes #3837.
=> send queue: allow unwedging and retry after recipient trust changes

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine/mod.rs, crates/matrix-sdk-crypto/src/machine/tests/decryption_verification_state.rs, crates/matrix-sdk-crypto/src/machine/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk/src/room/mod.rs
Replaces https://github.com/matrix-org/matrix-rust-sdk/pull/3701.  Part of invisible crypto.
The room event decryption function now takes a `DecryptionSetting` which allows you to require that event senders have a certain trust level based on their cross-signing status.  Events that do not meet the required trust level will fail to decrypt with an error.
Signed-off-by:
=> crypto: Configurable sender trust checking on decrypting

crates/matrix-sdk-ui/src/timeline/controller/state.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
What it says on the tin. I was looking how poll events stash pending related events, will probably do something similar for edits later.
=> timeline: small cleanups (doc polls + use event factory more)

crates/matrix-sdk-crypto/src/machine/tests/megolm_sender_data.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
Since we now have a clear idea of the structure, and anything we create now should be usable in future.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3544
Explanation:
This whole feature (SenderData) is about allowing us to know whether a session was created by a trusted person.
Sessions that we created in the past before this feature existed need to be treated differently: we can't just consider them all untrusted.
The `legacy_session` flag is our way of knowing that this session was created before we introduced the feature, or that we have imported the session from somewhere that does not support storing this information (at time of writing, neither key storage nor import/export persist the SenderData info).
This means that we can choose to hide messages that we don't …
=> crypto: Mark all new SenderData info as non-legacy

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs, crates/matrix-sdk-crypto/src/types/cross_signing/self_signing.rs, crates/matrix-sdk-crypto/src/types/cross_signing/user_signing.rs, crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs
A collection of random logging updates, that would have made my life easier when trying to debug a verification failure this week.
=> crypto: logging updates for verification

crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs
Inspect might not be the best name for this method considering what we're doing with it, but the docs seem to be more general so I decided to follow clippy's advice instead of silencing it.
=> sdk: Fix a clippy warning

bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/controller/mod.rs, crates/matrix-sdk-ui/src/timeline/controller/state.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/remote.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/encryption_sync_service.rs
It does not make much sense to create an UI client that does not support end-to-end encryption, besides disabling the feature was broken for quite some time.
=> ui: Remove the e2e-encryption feature from the matrix-sdk-ui crate

benchmarks/benches/room_bench.rs, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/controller/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs, crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/3840.
`RequestConfig::max_concurrent_requests` won't work for requests to a same endpoint, since it's a global value that can only be passed to `HttpClient` when created.
To replace it I added a buffered stream that can run at most `MAX_PINNED_EVENTS_CONCURRENT_REQUESTS` (10) requests concurrently.
There is also a test to make sure this max concurrency mechanism works.
Signed-off-by:
=> pinned events: limit the max amount of concurrent requests to load pinned events

Cargo.lock, Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/sliding_sync/http.rs, crates/matrix-sdk-base/src/sliding_sync/mod.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/matrix-sdk-integration-testing/src/helpers.rs
Simplified sliding sync now has an MSC number: 4186. Let's use it to clarify our code. I've done the same on Ruma side, and I've updated our `matrix-org/ruma` fork with its `feat-sss` branch.
=> chore(sdk): Replace “simplified sliding sync” by “MSC4186”

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/encryption/backups/mod.rs, crates/matrix-sdk/src/encryption/tasks.rs, testing/matrix-sdk-integration-testing/src/tests/timeline.rs
This PR is an attempt to fix https://github.com/matrix-org/matrix-rust-sdk/issues/3768 and subsequently https://github.com/element-hq/element-x-ios/issues/3055. A review commit by commit is advised.
There are two issues that I have discovered:
1. Like #3768 theorized, enabling a backup doesn't trigger a decryption retry in the timeline.
2. The background task which is supposed to download the room keys upon a decryption failure happens has logic to deduplicate downloads and to stop the download if the backup does not contain the room key. This logic incorrectly marks a room key as downloaded if a backup was not yet enabled and thus no actual download attempt happened.
The first two commits add regression tests for these two issues, then we fix the actual issues, and lastly we address a …
=> Retry the decryption of events in the timeline if backups were enabled

crates/matrix-sdk-ui/src/timeline/controller/mod.rs, crates/matrix-sdk-ui/src/timeline/controller/state.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/polls.rs, crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
What it says on the tin. Built on top of #https://github.com/matrix-org/matrix-rust-sdk/pull/3947. Needs a bit extra work/thinking:
The idea is that if we receive an edit for an event we hadn't seen in the timeline, then we'll keep the edit around, in case we see the event later. The number of pending edits event is bounded, by virtue of using a `RingBuffer` for each timeline.
This PR will stash pending edits for room messages and polls, as these two kinds of edits are handled in the code base.
Part of #3905.
=> timeline: stash edits around until we see the original event
