matrix-org/matrix-rust-sdk

crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/paginator.rs
crates/matrix-sdk/tests/integration/event_cache.rs

Before this patch, we did reset the paginator state just a bit too late, that is: at the beginning of running the next back-pagination. Resetting the state would trigger an update of the paginator status, which would reflect at the timeline paginator status level too.
But we have a bit of a conundrum here. Imagine the following sequence of events:
- back-pagination => at some point the paginator from the event cache hits the start of the timeline
- it reflects that at the timeline level, setting `hit_start_of_timeline` to true
- we received a limited/gappy sync via (simplified?) sliding sync, which resets the internal back-pagination token to None in the room event cache (not the associated paginator)
- this clears the timeline
Now, calling the paginator's `run_backwards()` method (or …

event cache: reset paginator state when receiving a limited timeline

---

crates/matrix-sdk-crypto/src/identities/manager.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk/src/sliding_sync/error.rs
crates/matrix-sdk/src/sliding_sync/mod.rs

Closes https://github.com/matrix-org/matrix-rust-sdk/issues/3959.
There is a non-negligible difference [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) and [MSC4186](https://github.com/matrix-org/matrix-spec-proposals/pull/4186) in how the
`e2ee` extension works. When the client sends a request with no `pos`:
* [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) returns all device lists updates since the last request
from the device that asked for device lists (this works similarly to
to-device message handling),
* [MSC4186](https://github.com/matrix-org/matrix-spec-proposals/pull/4186) returns no device lists updates, as it only returns changes
since the provided `pos` (which is `null` in this case); this is in
line with sync v2.
Therefore, …

fix(sdk): Mark tracked users as dirty when the SS connection is reset. 

---

bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk/src/room/edit.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/test_utils/events.rs
crates/matrix-sdk/tests/integration/send_queue.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

Takes care of [this TODO](https://github.com/matrix-org/matrix-rust-sdk/blob/9df1c480795c42afcee39e4c7e553d5a927a2680/crates/matrix-sdk-ui/src/timeline/mod.rs#L520).
- sdk & sdk-ui: unify `Timeline::edit` and `Timeline::edit_polls`, the new fn takes an `EditedContent` parameter now, which includes a `PollStart` case too.
- ffi: also unify the FFI fns there,  using `PollStart` and a new `EditContent` enum that must be passed from the clients like:
```kotlin
val messageContent = MessageEventContent.from(...)
timeline.edit(event, EditedContent.RoomMessage(messageContent))
```
Since the is mainly about changing the fns signatures I've reused the existing tests, including one that used `edit_poll` that now uses the new fn.
Signed-off-by:

timeline: unify `edit` and `edit_poll` functions

---

crates/matrix-sdk/src/sliding_sync/mod.rs

Previously this was only done in `Client::sync_once`, which made `ClientInner::sync_beat` not that useful.
Signed-off-by:

sdk: notify when a sync response is received by SlidingSync

---

bindings/matrix-sdk-ffi/src/room_info.rs
crates/matrix-sdk-base/src/rooms/normal.rs

This patch adds the `matrix_sdk_ffi::RoomInfo::creator` field
as an `Option<String>`. This value comes from the new method
`matrix_sdk_base::Room::creator()`, which simply forwards the value from the
existing `matrix_sdk_base::RoomInfo::creator()`.
---
* Addresses https://github.com/element-hq/customer-success/issues/347#issuecomment-2312062942

feat(ffi): Add `RoomInfo::creator`.

---

bindings/matrix-sdk-crypto-ffi/src/lib.rs

Again a draft until we get things merged in vodozemac land.
@bmarty and @Velin92 I think this is all you need for the legacy apps. Please shout if there's more needed.

bindings: Expose the PkEncryption stuff in the crypto crate bindings

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-ui/src/room_list_service/room.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/client/mod.rs

- Add `fn sdk_base::Room::is_state_partially_or_fully_synced()`. I was planning to reuse `Room::is_state_fully_synced()`, but this apparently doesn't work with SSS.
- Add `fn Client::await_room_remote_echo(&RoomId)`, which will loop indefinitely until it finds a room with the provided room id, using `ClientInner::sync_beat` to delay the checks. This is the core of the changes, and an FFI fn has been created to access it.
- `SlidingSyncRoom` is no longer needed in `fn RoomListItem::default_room_timeline_builder()`. It was mandatory, and used only to pre-fill the timeline with initial items. After discussing this behavior we decided we can make it non-mandatory so timelines can be created for rooms that haven't been synced yet, which was a source of pain in the clients.
- Fix dumb typo in …

feat: add fn to await a synced room from `Client`

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs

This field is helpful as it tells us the sequence number of the message in the megolm session, which gives us a clue about how long it will have been since the session should have been shared with us.
[Question: an alternative would be just to attach the whole of `content` to the span, instead of separate fields for `sender_key`, `session_id`, `message_index`. The Debug defintion for `MegolmV1AesSha2Content` looks like it contains the right things, so the code might be simpler. On the other hand, I think the output would be less readable. Thoughts?]

crypto: Include megolm ratchet index in logging span fields

---

bindings/matrix-sdk-ffi/src/element.rs

There's a new field to handle in the well-known file.

ffi: Add the registration helper URL to the ElementWellKnown file.

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk/tests/integration/client.rs

When processing a sliding sync response, if no account_data for direct rooms is found in the current response, use the cached value in the store.
This fixes an issue in the EX clients where only very few DMs were visible under the `People` filter since they weren't considered DMs, until a full restart of the app.
Signed-off-by:

sdk-base: use updated account data for processing direct rooms

---

bindings/matrix-sdk-ffi/src/room_list.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs

Reverts matrix-org/matrix-rust-sdk#3999
Complement crypto was failing but CI configuration has failed to catch that, let's revert this patch quickly.

Revert "chore(ui,ffi): Remove the `RoomList::entries` method"

---

crates/matrix-sdk-ui/src/notification_client.rs

The notification client was relying on the SS proxy including the `event_id` of a stripped room membership event, to correctly match an invite. This is not the case anymore with SSS (in the spec, stripped events don't include an event_id, although I don't see any good reason why), so we have to resort to a different mechanism:
- stash an invite event for the current user, if found.
- use it, if and only if, the room was inferred by the notification client to be in the invited state, based on the sync.
With this change, `matrix-sdk-integration-testing tests::sliding_sync::notification_client::test_notification` integration test from #3983 passes correctly.

notification client: use the membership state to match an invite

---

testing/matrix-sdk-integration-testing/src/tests/timeline.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3931, or so I think: the test waits for a stable state where there aren't any new updates to the timeline, before trying to edit a timeline item, and observe a precise sequence of timeline updates after the item has been edited.
The failures showed that the stable state wasn't reached, because in some occasions, we'd receive the original text as a new timeline update — which could also be the sign of a failing server / duplicated event or other things, but I believe it is just that 1 second timeouts ain't enough for code running under CodeCov.

tests: increase timeout duration when awaiting a timeline update

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs

This broadcast channel can easily be overflowed if more than 100 updates arrive
at the time. This patch extends the capacity to 2^16 - 1.
This patch also adds more logs to detect lagged on this channel from the room
list point of view.

feat(base): Increase the `room_info_notable_update_sender` capacity

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs

This PR is best reviewed with the background from: https://github.com/matrix-org/matrix-rust-sdk/pull/3998
The main change in this PR is the transition from using a UserId as the index for call member events in the room info to using the newly introduced `CallMemberStateKey` that is a combination of UserId and device id.
This is important since otherwise the room state could only store one event per user (but a user can join with multiple devices)
It also adds tests for session membership events (which is the new state event format for call member state events we need for reliable state events)
Signed-off-by:

MatrixRTC: Fix different devices from the same user overwriting the room info state event.

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs

Follow up for https://github.com/matrix-org/matrix-rust-sdk/pull/3990.
This removes a couple of TODOs in the codebase where we were running `handle_account_data` twice to be able to update the direct rooms after the rooms had been created in the store. Now these responsibilities are split in two separate functions.
Signed-off-by:

sdk-base: split `handle_account_data` and `process_direct_rooms`

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/day_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/test_utils/events.rs

Instead of forcing the room encryption to be known when the timeline is created and failing if it's not known, take the latest room encryption info as a base value and update it when processing timeline events.
At the time of writing this PR, the encryption info is only used to decide whether shields should be calculated for timeline items or not.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/3850 (I hope).
Signed-off-by:

sdk-ui: make room encryption optional to create a timeline

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
testing/matrix-sdk-integration-testing/assets/Dockerfile
testing/matrix-sdk-integration-testing/assets/ci-start.sh
testing/matrix-sdk-integration-testing/assets/docker-compose.yml
testing/matrix-sdk-integration-testing/src/helpers.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/mod.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

This patch removes the sliding sync proxy, and makes the `matrix-sdk-integration-testing` tests to run against Synapse with MSC4186 enabled.
The following tests from `matrix-sdk-integration-testing` have been disabled because they are not working with Synapse for the moment:
* `sliding_sync::room::test_room_avatar_group_conversation`
* `sliding_sync::room::test_room_notification_count`
* `sliding_sync::room::test_delayed_decryption_latest_event`
* `sliding_sync::room::test_room_info_notable_update_deduplication`
* `sliding_sync::room::test_room_preview`
* `sliding_sync::notification_client::test_notification`
---
* Addresses https://github.com/matrix-org/matrix-rust-sdk/issues/3698

test: Bye bye SS proxy, hello Synapse \o/

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/read_receipts.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs

This is to fix a bug caused by a race condition in Fractal. We used an event handler to detect changes in our own read receipts, then we called methods like [`Timeline::latest_user_read_receipt_timeline_event_id()`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.Timeline.html#method.latest_user_read_receipt_timeline_event_id). The problem is that there is no guarantee that the metadata of the timeline has already been updated when we call the method since they happen in separate threads. So instead we use this stream to react when the metadata is updated.

ui: Allow to subscribe to read receipt changes in timeline metadata

---

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs

We need this for pinned events where we want reactions, edits and redactions, but we don't want replies or threaded replies.
Signed-off-by:

sdk-ui & sdk: add a relationship type filter to `load_event_with_relations`

---

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs

This test was failing since the migration from the sliding sync proxy
to Synapse.
This patch fixes the test. The failing part was:
```rust
assert_eq!(notification.joined_members_count, 1);
```
This patch removes this assertion for the moment. In Synapse 1.115,
Synapse doesn't share this data for the sake of privacy because the
room is not joined. But the CI runs 1.114 and it seems to be different.
I'm investigating that. Edit: https://github.com/matrix-org/matrix-rust-sdk/pull/4030
fixes the CI to use 1.115, and the test now passes correctly \o/.
A comment has been made on MSC4186 to precise this behaviour:
https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1774775560.
Moreover, this test was asserting a bug (which is alright), <del>but now
a bug report has been …

test(integration): Enable `test_notification`

---

crates/matrix-sdk/src/sliding_sync/list/builder.rs
crates/matrix-sdk/src/sliding_sync/list/mod.rs
crates/matrix-sdk/src/sliding_sync/list/sticky.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

This test was failing since the migration from the sliding sync proxy
to Synapse.
This patch fixes the test. The failing parts were:
1. The `timeline_limit` wasn't set, so Synapse was returning an error,
2. The `unread_notifications` was set to 0 and could not be set to 1
because that's an encrypted room.
The fact `timeline_limit` is now mandatory has been mentioned in the MSC:
https://github.com/matrix-org/matrix-spec-proposals/pull/4186/files#r1775138458
A patch in Ruma has been created. The previous patch in this repository
also contains the fix for the SDK side.
The assertions around `unread_notifications` have been removed. We no
longer use this API anymore (and it should be deprecated by the way).

test(integration): Enable `test_room_notification_count`

---

testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

These tests were failing since the migration from the sliding sync proxy to Synapse.
Since the previous fixes to re-enable other tests, these 2 passes for free.

test(integration): Enable `test_room_preview` and `test_room_avatar_group_conversation`

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

Change the withheld code for the `IdentityBasedStrategy` from `WithheldCode::Unauthorised`
to `WithheldCode::Unverified`.
Signed-off-by:

crypto: change withheld code for IdentityBased share strategy

---

bindings/matrix-sdk-ffi/Cargo.toml

The `tracing` library has [an issue](https://github.com/tokio-rs/tracing/issues/2937) that prevents the configured log rotation from working on Android. While there has been [a proposed fix](https://github.com/tokio-rs/tracing/pull/3000) for some time, it hasn't been merged yet.
We recently discovered some cases of users who had hundreds of log files, several times our current max limit, and today I confirmed old logs weren't being deleted.
My proposed solution is to use [a forked tracing library](https://github.com/element-hq/tracing) in the meantime, along with [a forked paranoid-android one](https://github.com/element-hq/paranoid-android), which needs to use this former fork.
I tested this on an Android client and I saw the old logs being removed, as expected.
Signed-off-by:

ffi: use fork of `tracing` crate with a fix for Android logs rotation

---

bindings/matrix-sdk-ffi/src/encryption.rs

Some people might want to use the recovery module using a passphrase, please note EX should just pass `None` as the `passphrase` argument.

ffi: Allow recovery to be enabled using a passphrase

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/Cargo.toml

This seems to be the only way to make the log rotation fix work and avoid build warnings like:
```
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   matrix-rust-sdk/bindings/matrix-sdk-ffi/Cargo.toml
workspace: = matrix-rust-sdk/Cargo.toml
Finished `dev` profile [unoptimized] target(s) in 0.30s
```
I can confirm log rotation was working fine on an Android client after these changes, while it's not working with the current code on `main`.
Fixes the implementation in https://github.com/matrix-org/matrix-rust-sdk/pull/4038.
Signed-off-by:

ffi: move the dependency override from `ffi/Cargo.toml` to the root one

---

crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk/tests/integration/room/common.rs

In Fractal, we try to optimize our image requests according to the image info that was provided, e.g. we don't request thumbnails but the original image for SVGs or if the original is small. Currently it means we need to request the `m.room.avatar` event from the store to get this info although it is already available in the `RoomInfo` for `/v3/sync`. This exposes that data from `RoomInfo`.

base: Expose room avatar info from RoomInfo

---

crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/room/mod.rs

The APIs have been deprecated for a year and a half, and the deprecations were released in 0.7.0.

misc: Remove deprecated apis

---

crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/mod.rs

This old method was checking invariants that were
spooky-action-at-a-distance: these invariants have changed since then,
so this would panic instead of returning a proper error to the caller.
Signed-off-by: oliverw@element.io

client builder: return a `ClientBuildError` when failing to build, instead of filtering out unexpected errors

---

bindings/matrix-sdk-ffi/src/client.rs

Expose a kotlin method for logging in with JWT. 
example usage : This will help users to login to synapse using third party libraries
Tested on the local element app
Signed-off-by: 
Pratik Deshpande <prattspective@gmail.com>

FFI : Add a method in the client to log in using JWT

---

crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs

This if a first attempt at addressing #3703. This isn't a full fix, but should address the most common case where the same room keys are received but contain different authenticity properties due to being received from different sources.
A more complete solution will need to utilize the [`InboundGroupSession::merge()`](https://docs.rs/vodozemac/latest/vodozemac/megolm/struct.InboundGroupSession.html#method.merge) method.

feat: Prefer room keys with better SenderData when comparing duplicate room keys

---

.github/dependabot.yml

This was tested out in vodozemac, works nicely: https://github.com/matrix-org/vodozemac/pull/188 and https://github.com/matrix-org/vodozemac/pull/190.

chore: Configure dependabot to notify us about outdated github actions

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/response_processors.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk/src/sliding_sync/client.rs

This tidies up the code by making the data dependencies very explicit, instead of stashing data into `StateChanges` and then relying on it later on during computation. It reduces the amount of duplicated code, streamlines the processing of global account data events, and makes it easier to reason. Also would make it easier to test in isolation, would we need to. Overall, I think this is an improvement, and generalizing this would help commonize more code between sync-v2 and SSS processing.

base: tidy up processing of global events in sync responses

---

crates/matrix-sdk/src/encryption/recovery/mod.rs

Noticed this while looking at the logs, where I saw a log line of ~1.26MB

Do not log full keys query response which can be very large

---

bindings/matrix-sdk-ffi/src/identity_status_change.rs
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-crypto/src/identities/mod.rs
crates/matrix-sdk-crypto/src/identities/room_identity_state.rs
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk/src/encryption/identities/users.rs
crates/matrix-sdk/src/room/identity_status_changes.rs
crates/matrix-sdk/src/room/mod.rs

Part of https://github.com/element-hq/element-meta/issues/2526
If you follow the stream returned from `matrix_sdk::room::Room::subscribe_to_identity_status_changes` you will receive an update every time someone in the room changes identity status e.g. becomes "Unpinned", meaning the UI should display a warning.

crypto: Notify when the identity status of a user changes

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/identities/manager.rs
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk/CHANGELOG.md
testing/matrix-sdk-test/src/test_json/keys_query_sets.rs

Part of https://github.com/element-hq/element-meta/issues/2526
For consistency with other places, we have now settled on `VerificationViolation` as the best way to express this situation.

crypto: Rename PreviouslyVerified to VerificationViolation

---

bindings/matrix-sdk-crypto-ffi/src/users.rs
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk/src/encryption/identities/users.rs

The main enum was renamed to `UserIdentity` and some aliases and comments had not kept up.

crypto: Rename some straggling 'Identities' to 'Identity'

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs

The `handle_reaction_redaction` method is called by `handle_redaction` for every single redaction event that we receive as a first step to check if the redaction matches a reaction.
It means that not finding a reaction to redact is perfectly fine and is not worthy of a warning.

ui: Do not warn when no reaction to redact was found

---

crates/matrix-sdk-base/src/response_processors.rs

It can occur that the data is partly outdated and contains rooms that were forgotten. Given that we now update that data after every sync, that creates a lot of noise in the logs for something that is not really a problem.
I demoted it to the DEBUG level, in case someone needs it for debugging purposes, but it would also be fine not to log anything, imo.

base: Do not warn when room in m.direct account data is missing

---

crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/polls.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/echo.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/src/timeline/tests/polls.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk/src/test_utils/events.rs

When adding a new event, we might also receive a bundled edit as part of `m.relations`; this is guaranteed to be the most up-to-date (if received from sync), so we should prefer this bundled edit over any pending edit we might have found.
Consider the following scenario:
- received pending edit $2 for event $1
- another edit $3 happens to $1
- when receiving $1, we may receive $3 as a bundled edit, but might have seen $2 before. In that case, it's preferable to use $3 rather than $2.
It's not clear it's the absolute fix, since we don't know the relative ordering of $2 and $3: if getting the event from cache, it might have bundled relations that are now outdated. I wonder if we should get rid of the bundled relations when storing them in the event cache :eyes: A question for another day. …

timeline: prefer a bundled edit over a pending one

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/ruma.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/sliding_sync/list/sticky.rs
labs/multiverse/src/main.rs

This PR makes 2 changes:
- Update Ruma to include https://github.com/ruma/ruma/pull/1919 and https://github.com/ruma/ruma/pull/1921 so that computed filenames/captions are available for audio, file, image and video messages.
- Update the FFI mappings to include captions and use the computed filename.

Media: Add support for media captions.

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/encryption.rs
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/encryption/identities/users.rs
crates/matrix-sdk/src/room/identity_status_changes.rs

Part of https://github.com/element-hq/element-meta/issues/2526

crypto: Expose a method to pin a user's identity

---

.github/workflows/bindings_ci.yml

- speed regression introduced when switching the default bindings profile to `reldbg` in #4020

ci: speed up iOS bindings tests by building them on the `dev` profile

---

.github/workflows/bindings_ci.yml
.github/workflows/xtask.yml

macos-12 runners are going [to be deprecated](https://github.com/actions/runner-images/issues/10721), so we should try to upgrade any time soon.
cc @stefanceriu @pixlwave

ci: use macos-14 runners for the swift related tasks

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/sliding_sync/list/builder.rs
crates/matrix-sdk/src/sliding_sync/list/mod.rs
crates/matrix-sdk/src/sliding_sync/list/sticky.rs

This patch updates `ruma` to include:
* https://github.com/ruma/ruma/pull/1913
* https://github.com/ruma/ruma/pull/1914

chore(cargo): Update `ruma`

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/tests/integration/room/left.rs

- Add `Client::knock` to both the binding and the SDK.
- Add `Client::room_knocked` to mark a room as knocked. I more or less copied the implementation from `room_joined`, so I'm not sure if some of the internal operations are not needed.
- Added `RoomState::Knocked` and `RoomStateFilter::KNOCKED` enum cases.
Signed-off-by:

ffi & sdk: add room knocking to `Client`

---

crates/matrix-sdk/src/config/request.rs
crates/matrix-sdk/src/http_client/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/tests/integration/media.rs

Was added post-merge to the MSC in https://github.com/matrix-org/matrix-spec-proposals/pull/4180 for servers that support authenticated media but do not support all of Matrix 1.11 yet.
Requires a kind of hack to force Ruma to select the stable endpoint by ignoring the real versions advertised by the homeserver for this particular endpoint.

sdk: Add support for authenticated media stable feature

---

crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs

This is useful for the knocking feature since we'll be able to differentiate between rooms that you were just invited from rooms that you knocked and then were granted access, or rooms that you left and rooms where your knocking attempt was rejected.
The `mark_room_as_*` functions have been updated so they reuse the same `set_state` function underneath, which only updates the previous state if the new one doesn't match.
Needs https://github.com/matrix-org/matrix-rust-sdk/pull/4080.
Signed-off-by:

sdk-base: add `RoomInfo::prev_room_state` property

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/src/room_list_service/state.rs

Fixes #3935.
Untested in the apps for now, but integration test is included and working.
Signed-off-by: Mathieu Velten <mathieu.velten@beta.gouv.fr>

Get back to Recovering syncing when we haven't sync for a while

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/media.rs

In https://github.com/element-hq/element-x-ios/pull/3375 I noticed that we request a file using the event's `body` which doesn't seem to make sense to me now that #4081 (and https://github.com/ruma/ruma/pull/1921) is available.
This PR updates the `get_media_file` methods in the SDK and FFI to both take the filename instead.

SDK: Pass the filename to get_media_file instead of the body.

---

.github/workflows/detect-unused-dependencies.yml
Cargo.lock
bindings/matrix-sdk-ffi/Cargo.toml
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-store-encryption/Cargo.toml
examples/qr-login/Cargo.toml

I've noticed there were a few unused dependencies; this removes them, and introduces a new check that will fail if there are any unused dependencies detected with `cargo-machete`. Also marks one false positive that the tool can't detect.

ci: detect unused dependencies

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

Sliding sync expects all state events to be in `required_state`. State
events in `timeline` **must be ignored**. However, in sync v2, state
events in `timeline` **must be handled**.
Two patches:
* From sliding sync response handler, we don't gather state events
from `timeline` anymore,
* In the same handler, both sliding sync and sync v2 uses the same
`handle_timeline` method. I add an argument to ignore state
events. This is not ideal, but it's a temporary solution as a first
step. The next step is to refactor this code, but let's start easy.
Other patches updates the tests.
Next step: clean this flow/handler just like https://github.com/matrix-org/matrix-rust-sdk/pull/4061 did.

fix(base): Fix state events handling in sliding sync

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs

This will help investigating edit issues, in case we run into more in the future.
Part of #3905.

chore(timeline): add extra logs to investigate edit issues

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs

- `is_local` is the opposite of `is_remote`. I hope all foreign languages have a `!` operator :clown_face: 
- the two lazy providers can be unified into a single one, avoiding a bit of boilerplate.
Split from #4100.

refactor(ffi): remove two fields in `EventTimelineItem`

---

bindings/matrix-sdk-ffi-macros/src/lib.rs
bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/encryption.rs
bindings/matrix-sdk-ffi/src/notification.rs
bindings/matrix-sdk-ffi/src/notification_settings.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_directory_search.rs
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/session_verification.rs
bindings/matrix-sdk-ffi/src/sync_service.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/widget.rs

I decided to make this forwards-compatible with `async fn` in callback interfaces / traits, bc. why not?

chore(ffi): Merge export and export_async attribute macros

---

.cargo/config.toml
.github/workflows/documentation.yml
Cargo.toml
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk/src/lib.rs
xtask/src/ci.rs
xtask/src/main.rs

This allows removing a lot of hacks to avoid spurious rebuilds.

chore: Move lint configuration out of .cargo/config.toml

---

Cargo.toml

We depend on the `futures_util::steam_select` macro since 9b36a04b. This macro requires the async-await-macros and std feature of futures-util.
These features are the default features so let's just stop disabling the default features for futures-util.

chore: Enable the default features for futures-util

---

crates/matrix-sdk-crypto/src/identities/room_identity_state.rs
crates/matrix-sdk/src/room/identity_status_changes.rs

A specific test for this case will need quite involved changes to `IdentityChangeDataSet` so I am working on that as a separate change.
Fixes https://github.com/element-hq/element-meta/issues/2566

crypto: Sort IdentityStatusChanges when providing them via subscribe_to_identity_status_changes

---

crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/paginator.rs
crates/matrix-sdk/tests/integration/event_cache.rs

This simplifies the locking situation, in particular it would've made the bug fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3501 impossible to happen in the first place (or at least, way more obvious).
Fixes #3502. Thanks @Hywan for the technical discussion we had about it.

refactor(event cache): simplify the locking situation

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/observable_map.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/left.rs

When forgetting rooms:
- Remove direct rooms from the `m.direct` account data,
- Remove rooms from the in-memory list.
Fixes #4078.\
Fixes #4079.

sdk: Fixes to `Room::forget`

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/src/oidc/mod.rs
crates/matrix-sdk/src/oidc/tests.rs

This allows clients to directly open the web page they want: the login one, the registration one, consent, etc. It should improve the UX in the registration flow since we can now skip the login one.
Requested in https://github.com/element-hq/element-x-android/pull/3635.
Signed-off-by:

refactor(oidc): allow passing a `Prompt` to get an OIDC url

---

CONTRIBUTING.md

Older versions of Git require --interactive when we supply --autosquash, and it's also probably a good idea generally.
See https://stackoverflow.com/a/77663575/22610 for more info.

doc(contributing): Recommend --interactive for git rebase --autosquash

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/echo.rs

This would have avoided a few hours of debugging where we thought there was an issue with multiple timelines spawned at the same time, and then realized it was expected because of the existence of the pinned timeline in EX apps.

chore(timeline): instrument timeline tasks with their focus and internal id prefix

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/src/timeline/util.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

New preamble to https://github.com/matrix-org/matrix-rust-sdk/pull/4111.

timeline: use a `TimelineEventItemId` for reacting to something

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/debug.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-base/src/sync.rs
crates/matrix-sdk/src/sync.rs
crates/matrix-sdk/tests/integration/client.rs
testing/matrix-sdk-test/src/test_json/sync.rs

This PR contains 2 commits:
1. The first one processes the membership state events in `process_sliding_sync_room_membership`, deserializes them and decides whether the resulting room should be a knock or invite one default to invite if not sure. Then it propagates the changes up the flow.
2. Since we already have `handle_stripped_state` to parse the contents of the `invite_state` stripped state events it seemed better to reuse this and deserialize the events only once, then mark the room as invited or knocked in this method. Ideally this should be part of the inner `fn BaseRoomInfo::handle_stripped_state_event`, but that doesn't have access to the `Room::state` property.
Both solutions work AFAICT, the 1st one centralises the membership processing in a single point but it's more …

feat(knocking): process knocked rooms separately during sync

---

CONTRIBUTING.md

The convention is for changelog entries to be in the imperative, not the past
tense.

doc: fix typo in contributing guide

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs

... which returns an enum which encodes decryption failure information, rather than returning `MegolmError`
To make this work, we also extend the existing `UnableToDecryptInfo` to include a reason code for the failure.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4048

crypto: expose new method `OlmMachine::try_decrypt_room_event`

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

fix(ffi): don't panic when joining after having cancelled a media upload

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/error.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This PR sits on top of #4111 and #4127, and allows us to get rid of the `edit_by_id` / `redact_by_id` variants.
I've added changelog entries \o/
Fixes #4093.

refactor(timeline): fuse `edit_by_id` (resp `redact_by_id`) into their ID-less counterparts

---

bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_info.rs
bindings/matrix-sdk-ffi/src/room_member.rs

Fixes #1254. This adds a bandaid in the form of converting `Into` impl to `TryInto`, and then will happily ignore errors in multiple places; unknown states are logged in warnings, so we can still get some information about it, would they become an issue in the future.

fix(ffi): don't panic when running into an unknown membership state

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk/src/encryption/futures.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/futures.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/encryption/backups.rs
crates/matrix-sdk/tests/integration/room/joined.rs

aka "Benjamin tries to make sense of the media code. Oh, nice: it makes sense."

refactor(media): some preparatory refactorings

---

crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

I'd really like some help on how to name the function, the internal variables and what the comments should say, please!

crypto: Extract a test helper function for simulating verification

---

bindings/matrix-sdk-ffi/src/client.rs

We need this value to provide a room alias for public rooms.
Signed-off-by:

chore(ffi): Add optional `canonical_alias` field to `CreateRoomParameters`

---

crates/matrix-sdk/src/event_cache/linked_chunk/updates.rs

The event cache stores its events in a linked chunk. The linked chunk
supports updates (`ObservableUpdates`) via `LinkedChunk::updates()`.
This `ObservableUpdates` receives all updates that are happening inside
the `LinkedChunk`. An `ObservableUpdates` wraps `UpdatesInner`, which
is the real logic to handle multiple update readers. Each reader has a
unique `ReaderToken`. `UpdatesInner` has a garbage collector that drops
all updates that are read by all readers. And here comes the problem.
A category of readers are `UpdatesSubscriber`, returned by
`ObservableUpdates::subscribe()`. When an `UpdatesSubscriber` is
dropped, its reader token was still alive, thus preventing the garbage
collector to clear all its pending updates: they were kept in memory
for the eternity.
This patch implements …

feat(sdk): Dropping an `UpdatesSubscriber` release its reader token for the garbage collector

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
crates/matrix-sdk-ui/src/timeline/tests/invalid.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/polls.rs
crates/matrix-sdk-ui/src/timeline/tests/shields.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/sliding_sync/mod.rs

I feel like the ability to convert straight from a `Raw<AnySyncTimelineEvent>>` into a `SyncTimelineEvent` is somewhat over-simplified: the two are only occasionally equivalent, and it's better to be explicit.

refactor(base): Remove `impl From` for `SyncTimelineEvent`

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs

This PR would be the cherry on cake on top of https://github.com/matrix-org/matrix-rust-sdk/pull/4100. Drafting for now, to let a bit of time for other PRs to be reviewed and merged first.

refactor(ffi): get rid of the `get_event_timeline_item` by id methods

---

crates/matrix-sdk-crypto/src/gossiping/machine.rs

This fixes the build
Before this change:
```
$ cargo check --features=experimental-algorithms
error[E0061]: this method takes 4 arguments but 3 arguments were supplied
--> crates/matrix-sdk-crypto/src/gossiping/machine.rs:513:30
|
513 |                         self.handle_supported_key_request(event, &i.room_id, &i.session_id).await
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ----- argument #1 of type `&StoreCache` is missing
```

fix(experimental-algorithms) Add missing argument to handle_supported_key_request

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/tests/shields.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/events.rs

This PR takes the `TimelineEventKind` that was added in https://github.com/matrix-org/matrix-rust-sdk/pull/4082, and adds a third enum variant which is specific to unable-to-decrypt events. We update the two methods which are responsible for decrypting encrypted events that have been received from the network (`decrypt_sync_room_event` and `decrypt_room_event`), and make them return a `[Sync]TimelineEvent` of the relevant kind instead of a megolm error.
Since pretty much everything downstream accesses UTD events via `TimelineEventKind::raw()`, we don't have to change much else to keep things working. 
Part of #4048.

Support for UTD error codes in `[Sync]TimelineEvent`

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/futures.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs

This adds an optional way to cache a media's content after uploading it successfully. In a followup PR, I'll also add caching of the thumbnail, in a slightly smarter way than we do right now (always return a cache hit independently of the requested thumbnail features).
Part of #1732.

media: cache media's content after uploading it

---

bindings/matrix-sdk-ffi/src/room_list.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
labs/multiverse/src/main.rs

This patch updates `matrix_sdk_ui::room_list_service`, and is twofold:
First off, it adds `m.call.member`, `m.room.topic` and `m.room.pinned_events` to
`required_state` of the `all_rooms` sliding sync list.
Second, this `required_state` sliding sync list value is easily out-of-sync with
the `required_state` sliding sync room subscription value. Thus, this patch
removes the `settings` argument of `RoomListService::subscribe_to_rooms` and
computes its own `RoomSubscription` instance. For `required_state`, it uses the
same `required_state` used by the `all_rooms` list, plus the `m.room.create`
state event. For `timeline_limit`, it uses 20 by default (this is not the
default value we were using in our tests, but that's the default value most
Matrix clients use).

feat(ui): Revisit `required_state` for `RoomListService`

---

crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs

The FFI will request a scaled version of the thumbnail by default; let's use the same cache key when caching the thumbnail after an upload.
Thanks @zecakeh for flagging the issue.
Part of #1732.

chore(media): use the same media method when caching a thumbnail as the FFI

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

chore(ffi): move the `store_in_cache` timeline media upload parameter before the `progress_watcher` closure

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/tests/integration/room/left.rs

These are needed parts of the API 😬 .
Signed-off-by:

chore(knocking): Add `reason` and `server_names` to `Client::knock`

---

crates/matrix-sdk-crypto/src/error.rs
crates/matrix-sdk-crypto/src/types/events/utd_cause.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs

This PR is the final part of the epic of making unable-to-decrypt information available in the timeline. As of #4070, the UTD info is now available in the `[Sync]TimelineEvent` created by the network code: now, we just need to copy that information into the items that are added to the timeline itself.
To do this, we add a new variant to `matrix_sdk_ui::event_handler::TimelineEventKind` (not to be confused with `matrix_sdk_common::deserialized_responses::TimelineEventKind` which was recently added in #4082) to hold the relevant data, and then add a bunch of new reason codes to the `UtdCause` which is derived from the decryption failure.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4048.
~~Based on https://github.com/matrix-org/matrix-rust-sdk/pull/4070.~~

Timeline: Extend UtdCause with new reason codes

---

crates/matrix-sdk/src/error.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/media.rs

This adds support for preallocated a MXC ID and using it to upload content later.
Part of #1732.

feat(media): support async upload

---

crates/matrix-sdk-crypto/src/identities/room_identity_state.rs
crates/matrix-sdk/src/room/identity_status_changes.rs

This is the Rust part of https://github.com/element-hq/element-meta/issues/2492

crypto: Support Verified and VerificationViolation updates in IdentityStatusChanges streams

---

bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs

This allows clients to decide whether or not passing `Create` to `url_for_oidc` is allowed.

FFI: Expose support for registration through OIDC in the login details.

---

crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/store.rs

This patch should be reviewed commit-by-commit. The idea is to improve the test suite of `RoomEvents`.

test(sdk): Improve the test suite of `RoomEvents`

---

bindings/matrix-sdk-crypto-ffi/src/verification.rs
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/session_verification.rs
crates/matrix-sdk-crypto/src/verification/machine.rs
crates/matrix-sdk-crypto/src/verification/mod.rs
crates/matrix-sdk-crypto/src/verification/requests.rs
crates/matrix-sdk-crypto/src/verification/sas/mod.rs
crates/matrix-sdk/src/encryption/verification/requests.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee.rs

This PR introduced FFI level API support for interacting with incoming session verification requests. Best reviewed commit by commit
- it exposes a new `did_receive_verification_request` `SessionVerificationController` delegate method that includes information about the incoming request/device/sender
- the client can `acknowledge_verification_request` to get informed about it getting accepted somewhere else or cancelled
- the client can also `accept_verification_request` to start interacting with it
This PR also internally switches to the `VerificationRequest::changes` publisher, fixes a couple of invalid VerificationMachine tests and starts storing requesting `DeviceData` directly in `VerificationRequestState. Requested`
Relates to element-hq/element-meta/issues/2464, fixes #3595.

Session verification incoming request support

---

crates/matrix-sdk/src/event_cache/linked_chunk/as_vector.rs
crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/linked_chunk/updates.rs

This patch should be reviewed commit-by-commit.
The idea is to implement `LinkedChunk::remove_item_at`, which removes an item at a specific position. This new feature propagates to `Update` with `Update::RemoveItem` and to `UpdateToVectorDiff` which can emit a `VectorDiff::Remove`.
One bug has been found and fixed in `UpdateToVectorDiff`, which no impact on the SDK so far since this API is not yet used.
---

feat(sdk): Add `LinkedChunk::remove_item_at`

---

CONTRIBUTING.md

Git trailers have a funny format.

doc: Deal with paragraphes in trailers

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
testing/matrix-sdk-integration-testing/assets/Dockerfile

This patch updates Synapse in our CI infrastructure and in the `matrix-sdk-integration-testing` crate.

test: Update Synapse from 1.115 to 1.117

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk/src/client/mod.rs

While working on something else, couldn't resist.

chore: Add an empty line between struct fields

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/migrations/state_store/005_send_queue_dependent_events.sql
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This refactors the send queue so that it can apply sending more abstract requests, instead of only sending plain events. This will generalize to media uploads soon, but in the future might also generalize to [sending redactions](https://github.com/matrix-org/matrix-rust-sdk/issues/4162), etc. So we now queue requests, update requests, and so on; which leads to some fun renaming in a massive patch, but no changes in functionality. Those would come in subsequent pull requests.
Indexeddb has a database format change, that is gently handled the same way we did for is_wedged vs wedged errors, that is: the migration applies at the reading boundary (we can't use the `#[serde(untagged)]` enum trick because we're storing a raw JSON value, and this is known to be …

refactor(send queue): refactor in preparation for media local echoes

---

crates/matrix-sdk-base/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache_store/memory_store.rs
crates/matrix-sdk-base/src/event_cache_store/traits.rs
crates/matrix-sdk-common/src/ring_buffer.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs

What it says on the tin. Will allow caching medias before they're sent to a remote, when used with the send queue.
Part of #1732.

feat(event cache store): add ability to rename a media cache key

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-crypto-ffi/src/machine.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-crypto/src/backups/mod.rs
crates/matrix-sdk-crypto/src/gossiping/machine.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/test_helpers.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/olm/account.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/session_manager/sessions.rs
crates/matrix-sdk-crypto/src/types/one_time_keys.rs
crates/matrix-sdk/src/notification_settings/command.rs
crates/matrix-sdk/src/notification_settings/mod.rs
crates/matrix-sdk/src/notification_settings/rule_commands.rs
crates/matrix-sdk/src/notification_settings/rules.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/tests/integration/encryption/verification.rs

The version that was just published on crates.io.

refactor!: Upgrade Ruma to 0.11.0

---

crates/matrix-sdk-crypto/src/error.rs
crates/matrix-sdk-crypto/src/olm/account.rs
crates/matrix-sdk-crypto/src/types/one_time_keys.rs

As discussed in https://github.com/matrix-org/matrix-rust-sdk/pull/4171#discussion_r1820767666.

refactor(crypto)!: Remove unused `OneTimeKey::Key` and `SessionCreationError::OneTimeKeyUnknown` variants

---

bindings/matrix-sdk-crypto-ffi/src/users.rs

Quick change to expose `has_verification_violation` in the crypto ffi layer for legacy mobile apps.
Signed-off-by:

crypto-ffi: Expose `has_verification_violation` for `UserIdentity`

---

bindings/matrix-sdk-ffi/src/client.rs

This avoids one spammy error log for sessions not using oidc.

chore(ffi): in `Client::account_url` return early when we're not an OIDC session

---

Cargo.lock
Cargo.toml

Brings in an important bug fix for `KeyId::key_name`.

fix: Upgrade Ruma to 0.11.1

---

bindings/matrix-sdk-ffi/src/room_directory_search.rs
crates/matrix-sdk/src/room_directory_search.rs
testing/matrix-sdk-integration-testing/src/tests/room_directory_search.rs

What the title says. This was previously missing.
Signed-off-by:

task(room_directory_search): add 'server' parameter to the room directory search

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/room_preview.rs
bindings/matrix-sdk-ffi/src/utils.rs

This avoids proliferation of `ManuallyDrop` in the code base, by having
a single type that's used for dropping under an async runtime.
---
I actually saw three uses of `ManuallyDrop` on the FFI layer, but failed to notice that two of them were in the crypto FFI crate. Should I introduce a new FFI helper crate just for sharing this code across the two other crates?

chore(ffi): introduce `AsyncRuntimeDropped` helper

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs

This patch displays the wrapped error.

chore(ui): Display the real error of `Error::EventCache`

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs

This patch removes `RoomListService::new_with_encryption`. This feature is not used, not useful since it's best to use `EncryptionSyncService`, and it can be racy depending on how it's used. To avoid potential errors and bugs, it's preferable to remove this code.

feat(ui): Remove `RoomListService::new_with_encryption`

---

benchmarks/benches/room_bench.rs
bindings/matrix-sdk-ffi/src/room_info.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/client.rs

When the required state of a room doesn't contain pinned events info for some reason, try using the `/state` endpoint from the HS to get this data instead.
This should take care of a bug that caused pinned events to be incorrectly removed when the new pinned event ids list was based on an empty one if the required state of the room didn't contain any pinned events info
Signed-off-by:

fix(pinned_events): get pinned event ids from the HS as fallback

---

bindings/matrix-sdk-ffi/src/client.rs

This uses the underlying `sdk::Client::resolve_room_alias` fn to check if a room alias is available for room creation.
Signed-off-by:

feat(ffi): add `Client::is_room_alias_available` function

---

crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/migrations/state_store/008_send_queue.sql
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/send_queue.rs

See the first commit message, which explains the whole point.
Because of this PR, the send queue events and dependent events tables are both cleared, because there's a change in the format of serde-serialized data, and I didn't bother to write a migration for those. Events stuck in there would only be wedged events, or events that were still in the queue before closing the app; worst case scenario is some users lose some messages they tried to send before an update of an app. Is that OK? otherwise, can look into a sane migration, if needs be.
Part of #1732, blocks #4195.

refactor(send queue): generalize stored send queue data

---

crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/mod.rs

Notably, make it super clear what parameters are required to create the attachment type, since the function doesn't consume the whole `AttachmentConfig` for realz.
Part of #1732, blocks #4195.

chore(base): refactor internal helpers related to media

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs

fix(timeline): update responses after a UTD has been decrypted

---

bindings/matrix-sdk-ffi/src/room_list.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

The parameter `room_info_notable_update_receiver` was removed
from `RoomList::entries_with_dynamic_adapters`, since it could be
inferred internally instead.
Alternative to #4212, which I think avoids the problem altogether by providing a better API.

refactor!(room list): remove unneeded argument from `RoomList::entries_with_dynamic_adapters`

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk-ui/tests/integration/sliding_sync.rs

Fixes #3936.
Signed-off-by: Mathieu Velten <mathieu.velten@beta.gouv.fr>

Activate share_pos on the room-list sliding sync instance

---

crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs

What it says on the tin. There were ideas to also rename `TimelineItemPosition`, but we're fine with the status quo, until we get more progress on the event cache.

chore(timeline): rename `TimelineItemPosition::Update` to `UpdateDecrypted`

---

crates/matrix-sdk/src/event_cache/linked_chunk/as_vector.rs
crates/matrix-sdk/src/event_cache/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/room/events.rs

This patch introduces `EmptyChunk`, a new enum used to represent whether empty chunks must be removed/unlink or kept from the `LinkedChunk`. It is used by `LinkedChunk::remove_item_at`.
Why is it important? For example, imagine the following situation:
- one inserts a single event in a new chunk (possible if a (sliding) sync is done with `timeline_limit=1`),
- one inserts many events at the position of the previous event, with one of the new events being a duplicate of the first event (possible if a (sliding) sync is done with `timeline_limit=10` this time),
- prior to this patch, the older event was removed, resulting in an empty chunk, which was removed from the `LinkedChunk`, invalidating the insertion position!
So, with this patch:
- `RoomEvents::remove_events` does remove empty …

fix(sdk): Do not always remove empty chunks from `LinkedChunk`

---

Cargo.lock
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/room_alias.rs
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/rooms/mod.rs

Add two FFI functions:
`is_room_alias_format_valid`: to check if a passed string has a valid room alias format in Ruma.
`room_alias_from_room_display_name`: to get a suggestion of a room alias to use given a room name.
Signed-off-by:

feat(ffi): add room alias format validation & room name to alias

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache_store/memory_store.rs
crates/matrix-sdk-base/src/event_cache_store/traits.rs
crates/matrix-sdk-base/src/media.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/member.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/media.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

As a separate PR to help with review.
It's better to change the structure of the fields before landing the other PR, otherwise we'd need a migration (or at least, to clear the send queue tables) when changing this code.
Part of #1732.

refactor!(media): flatten and rename `MediaRequest` and fields

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache_store/memory_store.rs
crates/matrix-sdk-base/src/event_cache_store/mod.rs
crates/matrix-sdk-base/src/event_cache_store/traits.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-common/src/store_locks.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/002_lease_locks.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/mod.rs

This PR must be reviewed commit-by-commit.
It introduces the `LockableEventCacheStore` type, which wraps `DynEventCacheStore`, and that implements `BackingStore` so that it can be used inside the `CrossProcessStoreLock`.
It then introduces the `EventCacheStoreLock` type, which glue all pieces together: the `CrossProcessStoreLock` and the `LockableEventCacheStore`. It exposes a single method: `lock(&'a self) -> Result<EventCacheStoreLockGuard<'a>, _>`, which allows to take the lock. The guard derefs to `DynEventCacheStore`. The resulting API is straightforward to use according to me: `client.event_cache_store().lock().await?`, pretty Rust idiomatic.
Finally, the PR replaces all uses of `DynEventCacheStore` by `EventCacheStoreLock`. There is no more public `DynEventCacheStore`, expect via …

feat: Implement cross-process lock for the `EventCache`

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-base/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache_store/memory_store.rs
crates/matrix-sdk-base/src/event_cache_store/traits.rs
crates/matrix-sdk-base/src/media.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/member.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/media.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Fixes #1732. This adds support for sending medias via the send queue, which gives us local echoes for free.
The process looks like this:
- put the medias (thumbnail and file) into the media cache (with temporary MXC IDs)
- send a local echo for the media event that references the local media cache
- if thumbnail
- create a request to upload the thumbnail
- create a dependent request to upload the file, depending on the thumbnail being uploaded
- create a dependent request to send the media event, depending on the file upload
- otherwise
- create a request to upload the file
- create a dependent request to send the media event
- once the medias have been uploaded, send a local echo edit for the media event, that fixes the MXC IDs to the final ones
The send queue dependency system is made …

feat(send queue): send attachments with the send queue

---

bindings/matrix-sdk-ffi/src/encryption.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/test_utils.rs

With this, we get notified of the current verification state almost immediately.
Without it, you may either call it too soon and receive an `Unknown` state or you might have to call `Encryption::wait_for_e2ee_initialization_tasks()` and wait until it's finished to request a valid state value.
Also, make sure we get an updated verification value before any network request runs so it can't get deadlocked/time out and we end up not receiving the updated value.
Signed-off-by:

feat(ffi): allow `VerificationStateListener` to emit the current state

---

bindings/matrix-sdk-ffi/src/widget.rs

This is the same work as done in:
https://github.com/element-hq/element-web/pull/28401
It also refactors the ffi `get_element_call_required_permissions` function to use a `read_send` array that gets copied both (read and send) capability lists.
Signed-off-by:

feat(ffi): Auto approve the required widget capabilities for element call raise hand and reaction feature.

---

crates/matrix-sdk/src/event_cache/deduplicator.rs

The previous values would lead to super large memory allocations, as observed with `valgrind --tool=massive` on the tiny test added in this commit:
- for 400 rooms each having 100 events, this led to 540MB of allocations.
- for 1000 rooms each having 100 events, this led to 1.5GB of allocations.
This is not acceptable for any kind of devices, especially for mobile devices which may be more constrained on memory. The bloom filter is an optimisation to avoid going through events in the room's event list, so it shouldn't cause a big toll like that; instead, we can reduce the parameters values given when creating the filters.
With the given parameters, 1000 rooms each having 100 events leads to 1.2MB of allocations.

fix(event cache): give looser parameters for the deduplicator's bloom filters

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-base/src/media.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/media.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This new ctor is used when caching a thumbnail everywhere, and when
attempting to retrieve it; it gives us a single place where to
coordinate the default `MediaThumbnailSettings` parameters.

feat(media): replace `MediaThumbnailSettings` default ctor with reasonable defaults

---

bindings/matrix-sdk-ffi/src/room_alias.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/ambiguity_map.rs
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/tests/integration/room/common.rs

This is in preparation of some higher level user display name handling, thus the rename of our `DisplayName` type as well.
No functional changes here.

Refactor and clean up our ambiguity handling

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk/src/test_utils.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/main.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This introduces new test utilities, starting with `MatrixMockServer`. This is a pair of a `MockServer` and a `Client` (one can retrieve them respectively with `.server()` and `.client()`).
It implements a few mock endpoints, expanding and limited the shared code as much as possible, so the mocks are still flexible to use as scoped/unscoped mounts, named, and so on.
It works like this:
- start with telling which endpoint you'd like to mock, e.g. `mock_room_send()`. This returns a specialized `MockSomething` data structure, with its own impl. For this example, it's `MockRoomSend`.
- configure the response on the endpoint-specific mock data structure. For instance, if you want the sending to result in a transient failure, call `MockRoomSend::error500()`; if you want it to succeed and return …

task(tests): introduce prebuilt mocks and mocking helpers

---

bindings/matrix-sdk-ffi/src/room_alias.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk/src/utils.rs

Previously this only used the Ruma checks, which only handled the initial `#` char and the domain part. With these changes, the name part is also validated, checking it's lowercase, with no whitespaces and containing only allowed chars, similar to what `DisplayName::to_room_alias_name` does.
Signed-off-by:

refactor(ffi): Make `is_room_alias_format_valid` stricter

---

ARCHITECTURE.md

Based on reading the https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html blog post, @andybalaam and I started an architecture document explaining at a high-level what the different crates are. We hope to also include the most important high-level components in the mix, as a vague map of where things are implemented. (e.g. Timeline, SyncService, RoomListService, etc.). Very WIP-y, etc.

doc: start an architecture document with a high-level description of the crates

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs

Previously I was matching a different error state, so it turns out the code was failing 🫠 .
Signed-off-by:

fix(ffi): match the right status code in `Client::is_room_alias_available`

---

crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/machine/tests/error.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/tests/integration/widget.rs

WidgetDriver: Handle widget send action that is a redact.

---

bindings/matrix-sdk-ffi/src/timeline/content.rs

What the title says.
Signed-off-by:

feat(ffi): add `reason` field to `TimelineItemContent::RoomMembership`

---

.github/workflows/bindings_ci.yml

- Complement Crypto has been disabled in https://github.com/matrix-org/matrix-rust-sdk/pull/4224 because the public FFI API has changed.
- https://github.com/matrix-org/complement-crypto/pull/153 fixes Complement Crypto.
- Now we can re-enable Complement Crypto.

test(ci): Re-enable Complement Crypto

---

bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This better encapsulates the transaction id of the send handle. Also introduced a FFI method to retrieve the `SendHandle` of a timeline local echo.
Let's see how hard it becomes in practice for EX apps, cc @jmartinesp @stefanceriu.

refactor!(send queue): move `RoomSendQueue::unwedge` to the `SendHandle` type

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/encryption/futures.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/send_queue.rs

A small foresight from the initial PR: 
- make it possible to define a `RequestConfig` for upload, plain or encrypted
- use that to request a short retry of uploads, in the send queue
Part of #1732.

feat(send queue): retry uploads

---

bindings/matrix-sdk-ffi/src/ruma.rs
crates/matrix-sdk/src/room/mod.rs

The caption and filenames were weirdly duplicated in each media content, when the expected behavior is well defined:
- if there's both a caption and a filename, body := caption, filename is its own field.
- if there's only a filename, body := filename.
We can remove all duplicated fields, knowing this, and reconstruct the body based on that information. This should make it clearer to FFI users which is what, and provide a clearer API when creating the caption and so on.

refactor(ffi): remove duplicated fields in media event contents

---

ARCHITECTURE.md

task(architecture): address typo in architecture.md file about `EncryptionSyncService`

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs

This patch disables the call to `share_pos()` inside the `RoomListService` because it creates slowness we need to investigate.
---
- Fix https://github.com/matrix-org/matrix-rust-sdk/issues/4244
- Address https://github.com/matrix-org/matrix-rust-sdk/pull/4035
- Reopen https://github.com/matrix-org/matrix-rust-sdk/issues/3936

fix(ui): Disable `share_pos()` inside `RoomListService`

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/observable_map.rs

This patch updates `eyeball-im` and `eyeball-im-util` to integrate https://github.com/jplatte/eyeball/pull/63/. With this new feature, we can have a single implementation of `ObservableMap` (instead of 2: one for all targets, one for `wasm32-u-u`). It makes it possible to get `Client::rooms_stream` available on all targets now.
This was required to get `matrix-sdk-ui` usable on `wasm32-u-u`, esp. the `RoomListService`.

feat(base): Make `ObservableMap::stream` works on `wasm32-unknown-unknown`

---

crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/send_queue.rs

A media upload can fail forever (i.e. get wedged) at step 1 (thumbnail upload failed) or 2 (media upload failed), for instance because the media's too large and the server's refusing it. This implements unwedging for such cases, with a naive yet effective solution: since only at most one `QueuedRequest` with one of the three transaction IDs used during a upload may be active, we can unwedge all 3 in the database; at most one will have an effect, and the other two will be spurious :nerd_face: 
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4201

send queue: implement full unwedging of media uploads

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk/src/utils.rs

At the moment we could only pass existing `caption` and `formatted_caption` parameters, assuming they were either plain text for `caption` or already parsed for `formatted_caption`. With these changes, the `caption` parameter is now treated as MD and transformed to HTML which will be used as `formatted_caption` if none is provided.
Bonus screenshot:
Signed-off-by:

feat(ffi): generate formatted captions for `send_*` media fns

---

crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/migrations/state_store/009_send_queue_priority.sql
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Prior to this patch, the send queue would not maintain the ordering of
sending a media *then* a text, because it would push back a dependent
request graduating into a queued request.
The solution implemented here consists in adding a new priority column
to the send queue, defaulting to 0 for existing events, and use higher
priorities for the media uploads, so they're considered before other
requests.
A high priority is also used for aggregation events that are sent late,
so they're sent as soon as possible, before other subsequent events.
Let's say it's part of #4201.

feat(send queue): maintain ordering of sending

---

crates/matrix-sdk/src/widget/matrix.rs

This PR changes the source of messages send to the widget. Instead of using: 
`let handle = self.room.add_event_handler(move |raw: Raw<AnySyncTimelineEvent>| {})`
which listens to all events form the timeline section of the sync, we use two listeners for state and message like:
`let handle = self.room.add_event_handler(move |raw: Raw<AnySyncStateEvent>| {})`
And
`let handle = self.room.add_event_handler(move |raw: Raw<AnySyncMessageLikeEvent>| {})`
`AnySyncStateEvent` should only get events from the state block of the SSS response.
and `AnySyncMessageLikeEvent` all the message like events from the timeline block.
This makes the behaviour equivalent to: https://github.com/element-hq/element-web/pull/28422
Signed-off-by:

feat(WidgetDriver): Send state from state sync and not from timeline to widget

---

crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This is a bit tricky, because we need to care about all possible states of the sending state machine, and do something different in each case:
- has the thumbnail upload started yet? y/n
- has the file upload staretd yet? y/n
- has the media event been sent yet? y/n
Fortunately, it's pretty easy to test all the cases, so I've done just that. Many LOCs are just tests, so don't be too afraid by it.
Part of #4201.

feat(send queue): allow aborting a media upload

---

crates/matrix-sdk/src/attachment.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/send_queue.rs

When we don't know the dimensions of a thumbnail, we still need *some* dimensions to cache it locally in the cache store, because it's required to send the thumbnail with the send queue. As a result, we default to using 0 for the unknown dimensions.
However, as soon as the thumbnail and file have been uploaded, there's no need to keep the 0-sized thumbnail in the cache; it's more likely the callers will try to retrieve it with actual, realistic sizes later. As a result, remove those locally-cached thumbnails from the cache store after a successful upload, if one of their dimensions was unknown.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4201

test(send queue): cached thumbnails of unknown dimensions are removed after upload

---

.github/workflows/upload_coverage.yml

task(CI): rename the upload code coverage task to make its name clearer

---

bindings/matrix-sdk-ffi/src/room_preview.rs
crates/matrix-sdk/src/room_preview.rs

Changes:
- Add `is_direct` field and `invited` fn.
- Add optional `num_active_members`, available for rooms you're invited to or have requested to join.
- Add `RoomType` enum to map the `Option<ruma::RoomType>`, instead of using a plain String.
Signed-off-by:

feat(ffi): add more info to `RoomPreview`

---

crates/matrix-sdk/src/send_queue.rs

Better safe than panicky. I don't want a bad surprise when coming back from my weekend.

task(send queue): demote some assertions back to logged errors

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

All the other media types include support for captions but for some reason file uploads didn't.

feat(ffi): Add support for including captions with file uploads.

---

crates/matrix-sdk-crypto/src/identities/user.rs

Withdrawing verification implicitly acknowledges that the identity changed, so we also pin the identity.
fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4206
Signed-off-by:

feat(crypto): pin identity when we withdraw verification

---

crates/matrix-sdk/src/room_preview.rs
crates/matrix-sdk/src/test_utils/mocks.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

For getting a `RoomPreview` we have the following paths, unfolding from `Client::get_room_preview`.
- If the room is known, get the preview from its `RoomInfo`.
- If it's not known:
- Try using [MSC3266](https://github.com/deepbluev7/matrix-doc/blob/room-summaries/proposals/3266-room-summary.md) to get a preview.
- If MSC3266 is not enabled, try asking your homeserver for some state and room member data.
The 'not known' part may fail oftentimes if the MSC is not enabled, so we're trying to complement it with the room directory search for public rooms, which will be added as another possible fallback.
The way this works is:
- If we have a room alias, use it for the search, take the first 20 results and look for a room with the expected room id.
- If we don't have it, request 100 rooms and …

feat(room_preview): Use room directory as another data source

---

crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs

There was an implicit relationship that the `being_sent` lock needed to be taken in order to do non-atomic state store operations. With the change from this commit, the relationship is now more explicit: to get a handle to the state store, or being_sent, you have to obtain a `StoreLockGuard` by locking against the store itself. The `WeakClient` isn't stored in the QueueStorage data structure itself, so it's the only way to get a `dyn StateStore` from the `QueueStorage`.

refactor(send queue): use a specialized mutex for locking access to the state store and `being_sent`

---

crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs
testing/matrix-sdk-test/src/test_json/sync_events.rs

feat(Room): Check if the user is allowed to do a room mention before trying to send a call notify event.

---

crates/matrix-sdk/src/sliding_sync/mod.rs

This is to make it easier to see which sync requests are for which connection when debugging.

Add 'conn_id' field to `sync_once` span

---

crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-sqlite/src/state_store.rs

Since this wasn't properly done for the dependent send queue for rooms, technically we should run a migration to look for the entries in the dependent send queue table, and remove all those that don't correspond to known room ids. I didn't bother here because the value seems quite low (this shouldn't affect many lines), but if the reviewer strongly feels about it, we could clean it up.

fix(base): clear a room's send queue and dependent event queue after removing it from the state store

---

crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/room/mod.rs

An oversight in `make_attachment_type`, where the creation of file and audio events would lead to losing both the filename (if set, that is, if there was a caption — resulting in the caption being considered as the file name) and the formatted caption, if provided.
Thanks @bmarty for catching this on EX.
Part of #4201.

media: include the caption and filename for file and audio events too

---

crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk/src/send_queue.rs

This allows reacting to a local media upload.
Adding a reaction to a local echo would check that the target of the reaction (identified by its transaction id) is part of the *requests*, but not part of the *dependent requests*. For a media upload, it's more likely the media event will be alive as a dependent request of kind `FinishUpload`, so we need to check there too. With that fix, it's then possible to react to a local media upload.
Part of #4201.

fix(send queue): when adding a local reaction, look for media events in dependent requests too

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/error.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk/src/room/edit.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/src/test_utils/events.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This allows editing media captions:
- for remote echo'd events, adding support in `make_edit_event` is sufficient,
- for local events (that are in the send queue), a bit more work is necessary:
- either the media event is a dependent request, and we need to update it
- or the media event is a request, and we need to update it
- or the media event is being sent, and we'll record a dependent request for an edit
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4201

feat(send queue): allow editing media captions

---

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs

This PR makes audio, file, image and video messages be editable so that the timeline signals when it is possible to use #4277/#4300 for editing captions.

feat(timeline): mark media events as editable

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

It has the same semantics used when creating a caption (if no formatted caption is provided, assume a provided caption is markdown and use that as the formatted caption).

feat(ffi): add a new function helper to create a caption edit

---

crates/matrix-sdk-base/src/rooms/normal.rs

This method has grown organically into a bit of a beast. Let's try to make it a bit easier to understand in preparation for [MSC4171](https://github.com/matrix-org/matrix-spec-proposals/pull/4171) :saluting_face:.

refactor: Clean up the Room::compute_display_name() method

---

bindings/apple/Debug-Package.swift

On the latest Xcode versions this is required to make the app run when building the SDK locally

build (apple): add dynamic type to debug package

---

crates/matrix-sdk/src/oidc/mod.rs

To help with OIDC token refresh issues we've observed in the wild with EX apps.

task(oidc): add logs when refreshing an OIDC token

---

crates/matrix-sdk-base/src/event_cache/store/mod.rs
crates/matrix-sdk-ui/src/timeline/error.rs
crates/matrix-sdk/src/lib.rs
labs/multiverse/src/main.rs

This contains a few commits that are useful in isolation from the large event cache storage PR (#4308).

refactor(event cache): some preparatory refactorings

---

crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-common/src/store_locks.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs

<p align="center"><img src="https://github.com/user-attachments/assets/dd188a36-7459-4025-adb9-2567f8e9570b" alt="A flask of poison" width="80%" /></p>
<figcaption><p align="center">A book floating in space in front of a black hole.</p></figcaption>
</figure>
---
A `RelationalLinkedChunk` is like a `LinkedChunk` but with a relational
layout, similar to what we would have in a database.
This is used by memory stores. The idea is to have a data layout that
is similar for memory stores and for relational database stores, to
represent a `LinkedChunk`.
This type is also designed to receive `Update`. Applying `Update`s
directly on a `LinkedChunk` is not ideal and particularly not trivial
as the `Update`s do _not_ match the internal data layout of the
`LinkedChunk`, …

feat(base) Implement `RelationalLinkedChunk`

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/updates.rs

This patch implements `LinkedChunk::clear`. The code from `impl Drop for LinkedChunk` has been moved inside `Ends::clear`, and replaced by a simple `self.links.clear()`. In addition, `LinkedChunk::clear` indeed calls `self.links.clear()` but also resets all fields.
This patch adds the `Clear` variant to `Update`.
This patch updates `AsVector` to emit a `VectorDiff::Clear` on `Update::Clear`.
Finally, this patch adds the necessary tests.
---

feat(common): Implement `LinkedChunk::clear`

---

crates/matrix-sdk-common/src/linked_chunk/relational.rs

fix: `RelationalLinkedChunk` handles `Update::Clear`

---

bindings/matrix-sdk-ffi/src/api.udl
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/timeline/content.rs

Ruma doesn't currently validate mxuri's and as such `MediaSource`s passed over FFI can contain invalid/empty URLs. 
This change introduces a wrapper type around Ruma's and failable transformations so that appropiate actions can be taken beforehand e.g. returning a `TimelineItemContent::FailedToParseMessageLike` or nil-ing out the thumbnail info.

feat(ffi): wrap Ruma MediaSources and run validations before passing them over FFI

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/room/events.rs

This PR is twofold:
1. It fixes a bug in `AsVector`: when an `Update::Clear` was received, the internal state of `AsVector` wasn't cleared,
2. It updates `RoomEvents::reset` to use `LinkedChunk::clear` so that events are correctly cleared and not dropped silently, i.e. the `Update`s and `VectorDiff`s are correctly reflecting that. That's important to clear the stores (implementations of `EventCacheStore`, like `MemoryStore` or `SqliteStore`). A new `RoomEvents::updates_as_vector_diffs()` method is added, it's going to be used later and it's useful to test the new behaviour now.
---
* Partly address https://github.com/matrix-org/matrix-rust-sdk/issues/4314

refactor: `RoomEvents::reset` really clears the linked chunk

---

bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk/src/attachment.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

`Thumbnail` is used to provide the data and information when uploading a thumbnail along an attachment. It seems sensible to assume that if a client is able to generate a thumbnail, it should be able to get all this information for it too.
A thumbnail with no information is not really useful, as we don't know when it could be used instead of the original image.
It allows to simplify the send queue to not have to handle the case where the dimensions of the thumbnail are missing.
Removes `BaseThumbnailInfo` in the process by merging its fields in `Thumbnail` directly.
There are also 2 pre-commits to refactor part of the code to simplify the changes.
cc @bnjbvr.

feat(media)!: Make all fields of `Thumbnail` required

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

chore(ffi): Fix thumbnail size info

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs

(Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512/)
This patch renames `TimelineEnd` into `TimelineNewItemPosition` for 2 reasons:
1. In the following patches, we will introduce a new variant to insert at a specific index, so the suffix `End` would no longer make sense.
2. It's exactly like `TimelineItemPosition` except that it's used only and strictly only to add **new** items, which is why we can't use `TimelineItemPosition` because it contains the `UpdateDecrypted` variant. This renaming reflects it's only about **new** items.
This patch takes the opportunity to move the `RemoteEventOrigin` inside `TimelineNewItemPosition` to simplify method signatures. They always go together.
---

chore(ui): Rename `TimelineEnd` to `TimelineNewItemPosition`

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/room/events.rs

It's unused so it's mostly cosmetic, and it's trivial to reimplement using `linked_chunk.items().count()`, as shown in tests.
Fixes #4332.

refactor(linked chunk): replace `LinkedChunk::len()` with a simpler impl

---

crates/matrix-sdk-common/src/linked_chunk/builder.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs

What it says on the tin. Extracted from #4308, with extra testing and better error handling.
In particular, we must be careful that the passed set of chunks form a linked list, and not a looser kind of a graph.
Two things I'm not very sure about:
- should we have a dedicated pass only to check the internal links are consistent? I *think* what I've done is equivalent and correct (i.e.: manually check the previous, remove from `self.chunks` while constructing, ensure `self.chunks` is empty after iterating), but an explicit pass might be more straightforward and clearer in its intent. 
- is it fine that `Ends::last` is always set? It's not clear to me why it should be optional, since its users will either take it, or take `first` when it's not set.
Part of …

feat(linked chunk): add a way to reconstruct a linked chunk from its raw representation

---

crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs

(Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512/)
This patch tries to clear confusion around
`TimelineItemPosition::UpdateDecrypted(usize)`: it does contains a timeline item index. This patch changes to
`TimelineItemPosition::UpdateDecrypted { timeline_item_index: usize }`
---

chore(ui): Clarifies what `TimelineItemPosition::UpdateDecrypted` holds

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/updates.rs

This patch updates `LinkedChunk::new_with_update_history` to emit an `Update::NewItemsChunk` because the first chunk is created and it must emit an update accordingly.
The fix is 9 lines changes, the rest is only test updates.
---
* Fix https://github.com/matrix-org/matrix-rust-sdk/issues/4314

fix(common): `LinkedChunk` emits an `Update::NewItemsChunk` when constructed

---

crates/matrix-sdk-crypto/src/types/events/mod.rs
crates/matrix-sdk-crypto/src/types/events/utd_cause.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk/src/room/mod.rs

Fixes https://github.com/element-hq/element-meta/issues/2581 
Detect and report expected historical UTDs as such. Must be integrated by clients and reported with [this code](https://github.com/matrix-org/matrix-analytics-events/blob/564a8b1386f2f46eee65f429b2a07940916d8257/schemas/Error.json#L23) in Analytics.
To determine if an event is device historical (i.e sent before the current login existed) we use an heuristic based on the event `origin_server_ts` and the device creation local timestamp.
Signed-off-by:

feat(utd_hook): Report historical expected UTD with new reason

---

crates/matrix-sdk-base/src/event_cache/store/mod.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/003_events.sql
crates/matrix-sdk-sqlite/src/error.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs

So, it's a bit of a chatty PR:
- because of the tests,
- because the tests required reading out from the store, I've implemented the full linked chunk reloading; it's using the intermediary raw format at this point, and later we can use the `LinkedChunkBuilder` to recreate the full thing.
Apart from that, the changes here are somewhat boring, and just running SQL requests.
I've taken the liberty to add a (clear) event id as a column for the events table, so we can add fetch_by_id easily in the future; this avoids a trivial migration.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3280
Split from #4308.

feat(event cache): handle linked chunk updates and reload in the sqlite backend

---

Cargo.lock
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk-sqlite/src/lib.rs
crates/matrix-sdk-ui/src/lib.rs
crates/matrix-sdk-ui/tests/integration/main.rs
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/tests/integration/main.rs
testing/matrix-sdk-integration-testing/src/lib.rs
testing/matrix-sdk-test/Cargo.toml

Fixes the `unexpected_cfgs` warning so it doesn't need to be disabled anymore.
We are also looking at the one triggered by `EventContent` in https://github.com/ruma/ruma/issues/1956, if anyone has an opinion.

chore(test): Upgrade ctor

---

crates/matrix-sdk/src/client/builder/mod.rs

Clippy only shows the warning when the `indexeddb` is active but we are not under WASM.

chore(sdk): Disable `unused_async` clippy lint for unimplemented method

---

Cargo.lock
xtask/Cargo.toml
xtask/src/ci.rs
xtask/src/fixup.rs
xtask/src/kotlin.rs
xtask/src/main.rs
xtask/src/release.rs
xtask/src/swift.rs
xtask/src/workspace.rs

Gets rid of an `unexpected_cfgs` warning. Alternative to #4352.
Because most subcommands are functions, this uses a thread-local static shared shell API. If they were methods, we could just use a shared shell API for a given command.

chore(xtask): Upgrade xshell

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/echo.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs

(Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/3512/)
This patch changes `TimelineStateTransaction::add_remote_events_at` to take an `IntoIterator<Item = Into<SyncTimelineEvent>>` for `events`. In the current code, it saves one
`iter().map(Into::into).collect::<Vec<_>>()`, but it will save another one when we will support `VectorDiff`s coming from the `EventCache`.
It also avoids to allocate a vector to pass new events (this mostly happens in the tests, but it can happen in real life).
---

refactor(ui): Use an iterator instead of `Vec` to represent events

---

.github/workflows/bindings_ci.yml

This brings our CI times for the `Build framework` step down to 13 minutes after they have risen to 40+ minutes because of https://github.com/matrix-org/matrix-rust-sdk/pull/4354/commits/191d00871f3b50ef90fde2fbef1c92d7036aec22.

ci: Build the Mac framework using the reldbg profile

---

crates/matrix-sdk-common/src/linked_chunk/updates.rs
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/event_cache/deduplicator.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This implements both directions for interacting between the event cache and the storage backend. I think this is fine design… as long as we don't have any other process writing into the cache, in which case we'll need to reset at different places.
The main idea in this PR is to use `RoomEventCacheState::with_events_mut(func: impl FnMut(&mut RoomEvents))` to perform any write to the underlying `RoomEvent` data structure. The function takes care of maintaining the storage, after updates have been performed.
Additionally: this behavior isn't enabled by default; callers have to call `EventCache::enable_storage()` when they start using the event cache.
I've put the `RoomEventCacheState` data structure in a private module, so that even the same module can't access its private fields, and we …

feat(event cache): connect the room event cache and persistent storage

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/read_receipts.rs

This patch renames the `all_events` field to `all_remote_events` in `TimelineMetada` for the sake of clarity.

refactor: Rename `TimelineMetadata::all_events` to `all_remote_events`

---

crates/matrix-sdk-base/src/store/observable_map.rs

The client we're building is panicking on startups in some random cases with the following error message `Value should be present or has just been inserted, but it's missing`. There seems to be a pretty serious bug in `observable_map.rs` which I initially demonstrated with an extension of the existing unit tests in 6d6f8e4dada2ec43f89d1aa07118efb608a0a60a.
Any `.remove` operation called on a `ObservableMap` will not re-index `values` _after_ the removed position, which means any later operation on elements inserted after the previously removed key will either be fetched wrongly, or panic when using `.get_or_create`.
This PR fixes these two related bugs and adds extra test cases.

Fix indexing issue in `ObservableMap`

---

crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk/src/oidc/cross_process.rs
crates/matrix-sdk/src/widget/settings/url_params.rs

- For global variables which don't need to be mutable, prefer const to static.
Signed-off-by: Integral <integral@member.fsf.org>

refactor: replace static with const for global constants

---

crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/event_cache.rs
crates/matrix-sdk/tests/integration/widget.rs

This is a follow up PR on: https://github.com/matrix-org/matrix-rust-sdk/pull/3987
And tries to use the `MockMatrixServer` wherever reasonable in the widget integration tests.
Signed-off-by:

tests: Refactor the widget tests to use `MockMatrixServer`

---

.deny.toml

This reverts commit f256fe4b24d9d180b6dcf3dc7ead4b06d2ef87ee.
As discussed, we want to prioritize the testing of new Ruma features over stability.

Revert "chore: Remove Ruma from the cargo-deny git dep allow list"

---

crates/matrix-sdk-ui/src/timeline/controller/state.rs

The `add_or_update_remote_event` method always returns `true`. This
patch updates the method to return nothing, and cleans up the call sites
accordingly. This patch also adds comments to clarify the code flow.
The bool value returned by `add_or_update_remote_event` was supposed
to be `false` if the event was duplicated. First off, as soon as the
`Timeline` receives its events from the `EventCache` via `VectorDiff`,
the `event_cache::Deduplicator` will take care of deduplication,
so the `Timeline` won't have to handle that itself. Second,
`add_or_update_remote_event` was sometimes removing an event, but it
was re-inserting a new one immediately without returning `false`: it was
never returning `false` because a new event was always added.

refactor: `TimelineStateTransaction::add_or_update_remote_event` always return `true`

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/read_receipts.rs

<p align="center"><img src="https://github.com/user-attachments/assets/fdbe72c4-c82a-441e-8307-c218cd7eac76" width="80%" /></p>
<figcaption><p align="center">A shepherdess gathering a herd of sheep.</p></figcaption>
</figure>
---
Build on top of https://github.com/matrix-org/matrix-rust-sdk/pull/4369.
The first patch replaces `VecDeque<EventMeta>` by `AllRemoteEvents` which
is a wrapper type around `VecDeque<EventMeta>`, but this new type aims
at adding semantics API rather than a generic API. It also helps to
isolate the use of these values and to know precisely when and how they
are used.
As a first step, `AllRemoteEvents` implements a generic API to not break
the existing code. Next patches are revisiting that a little bit step
by step:
* …

refactor(ui): Introduce the `AllRemoteEvents` type

---

bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/room.rs

Instances of these timelines will be used to power the 2 different tabs shown on the new media browser. The client will be responsible for interacting with it similar to a normal timeline and transforming its data into something renderable e.g. section by date separators (which will be made configurable in a follow up PR)

feat(ffi): expose a custom timeline builder that can be configured to show only media, images and videos or files and audios

---

Cargo.lock
xtask/Cargo.toml

Since xshell 0.2.3 the behavior of the run() function has changed in a incompatible manner. Namely the stdin for the run() function no longer inherits stdin from the shell. This makes it impossible for commands that are executed by the run() function to accept input from the shell.
We don't use this functionality in many places but the `xtask release prepare` command is now broken.
Let's just pin xshell to a working version while we wait for this to be resolved upstream.
Upstream-issue: https://github.com/matklad/xshell/issues/63

chore: Downgrade xshell due to broken stdin interactions

---

crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

`EventCache::add_initial_events()` was supposed to be temporary, until the event cache has its own storage. It's been used in multiple tests, as a way to prefill the event cache. It's used in other place, when constructing a timeline, to prefill the room event cache with the (soon-to-be-deprecated) cached timeline we stored in the sliding sync storage (aka `timeline_queue()`).
This patch gets rids of all uses in tests, so that there remains only a single use (when creating the timeline). We can later remove this function, once the storage has been enabled unconditionally.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3280
Split from #4308.

test(event cache): rely less on `EventCache::add_initial_events()`

---

crates/matrix-sdk/src/event_cache/room/mod.rs

A bit of serde foo to remove the `unsigned`.`m_relations` of an event, if it contained any, before storing the persisted event to disk. Otherwise, we might end up duplicating events with different contents in the database, and it creates complications for consumers. For instance, the consumer of a reloaded event wouldn't know how to order a bundled edit with respect to other edits (i.e. figure which edit is the most recent one), since there's no generalized notion of ordering across events.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3280.

feat(event cache): strip bundled relations before persisting events

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs

This seems to cause incorrect ordering under some more complex insertion scenarios which are not fully understood yet.
This is the likely culprit for: https://github.com/element-hq/element-x-ios/issues/3583.
A second commit, containing doc updates, was reverted as well as the culprit wouldn't revert cleanly on its own.

Revert "chore(ui): Unify the logic for timeline item insertions"

---

Cargo.lock
bindings/matrix-sdk-crypto-ffi/src/error.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/error.rs
crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-crypto/src/types/events/room_key_withheld.rs
crates/matrix-sdk-crypto/src/types/events/utd_cause.rs
crates/matrix-sdk-crypto/src/types/mod.rs
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk/src/authentication/qrcode/messages.rs
testing/matrix-sdk-test/src/event_factory.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4270
Signed-off-by:

feat(crypto): Add optional withheld reason to `UnableToDecryptReason`

---

crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/event_cache.rs
crates/matrix-sdk/tests/integration/widget.rs
labs/multiverse/src/main.rs

This is one of the last steps for integrating the persistent storage: if a timeline is gappy, then we *don't* need to reset it, either internally or for observers. That's the whole point of persisting the event cache, after all: we should be able to paginate again from any holes we encounter later.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3280

feat(event cache): don't clear a timeline if storage's enabled

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/src/response_processors.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/client.rs
crates/matrix-sdk/tests/integration/room/common.rs
crates/matrix-sdk/tests/integration/room/joined.rs
crates/matrix-sdk/tests/integration/room/left.rs

This is the follow up of this [Ruma PR](https://github.com/ruma/ruma/pull/1946) for the SDK.
Ruma PR needs to be merged first.

Accept any string as a key for `m.direct` account data

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/rooms/normal.rs
testing/matrix-sdk-test/src/event_factory.rs

Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/4228, only the second commit here is relevant.
This adds support for service members to be excluded from the room display name calculation logic as described in [MSC4717](https://github.com/matrix-org/matrix-spec-proposals/blob/tulir/service-members/proposals/4171-service-members.md).

Add support for MSC4717: service members 🫡

---

crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/event_cache/mod.rs

The test requires subtle conditions to trigger:
- initialize a timeline from a room-list-service's room
- start a backpagination with that timeline (so the room event cache's paginator is busy)
- try to initialize another timeline with the same room-list-service's room (e.g. because the first room has been closed, and the app using it doesn't have a room cache)
This would fail, because initializing a timeline calls `EventCache::add_initial_events()` all the time, which tries to reset the paginator's state, which assumes the paginator's not paginating at this point. In a soon future, we'll get rid of the `add_initial_events()` function because the event cache will handle its own persistent storage; in the meantime, a correct fix is to skip `add_initial_events()` if there was already …

fix(event cache): don't fill initial items if the room already had events

---

xtask/src/main.rs
xtask/src/release.rs

See the commit messages for details.
Since it was not noticed before, it seems that CI does not lint xtask with clippy. Maybe it should?

chore(xtask): Fix clippy lints

---

crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/src/live_location_share.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/beacon/mod.rs

Conversation related to this issue can be [found here](https://github.com/matrix-org/matrix-rust-sdk/issues/3945)
This merge request adds `subscribe_to_live_location_shares` to the `matrix_sdk::Room` that allows clients to listen for beacon updates using a background task. The method provides an easy way to subscribe to live location sharing events within a room, handling event processing internally.
Follow-up tasks will include adding support for the event cache.

sdk: add support for listening to stream of live location updates

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/src/utils.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Extracted from #4329. This does not change the `MediaFormat` of the request used in the media cache by the send queue.

fix(media): Make sure that local MXC URIs only try to get media from the cache and ignore requested dimensions

---

README.md
bindings/matrix-sdk-crypto-ffi/README.md

To match the version in `Cargo.toml`.

chore: Bump MSRV in READMEs

---

crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs

Part of #3280. See the first commit message's description to get the reasoning.
Split from #4308.

feat(event cache): start paginations from the most recent token, not the oldest token

---

bindings/matrix-sdk-ffi/src/encryption.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/encryption/backups/mod.rs
crates/matrix-sdk/src/encryption/backups/types.rs
crates/matrix-sdk/src/encryption/recovery/futures.rs
crates/matrix-sdk/src/encryption/recovery/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs

Part of https://github.com/element-hq/element-meta/issues/2638
Provide `fast_exists_on_server` so we can call it when figuring out whether a UTD is expected.
If you have suggestions for better ways to implement this, I am interested. I wish we didn't need to have a lock on the cached value but I couldn't see a better way.
This method does not always provide a fully-correct answer, but it is a best effort that is much cheaper than the full `exists_on_server` which always makes a request to the server. Since we only plan to call the new method when reporting UTDs, for now, the negative consequence of an incorrect answer is only to report the wrong kind of UTD.

feat(crypto) Provide a method to check whether server backup exists without hitting the server every time

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room.rs

This PR adds the send_raw methods to the bindings, making it usable from e.g. Swift.
Signed-off-by: Jonas Richard Richter <jonas-richard.richter@telekom.de>

feat(ffi): Add method to send custom events with JSON content

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs

Instead of one transaction per update. This ensures that if a single update fails, then none is taken into account.
The test triggers a unique constraint violation. Before the patch, it would still contain a single chunk (the first one), while after the patch, it contains none.
Part of #3280.

refactor(event cache store): use a single transaction to handle all linked chunk updates at once

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/day_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/item.rs
crates/matrix-sdk-ui/src/timeline/read_receipts.rs

<p align="center"><img src="https://github.com/user-attachments/assets/ea94db30-494e-44d3-8479-24451ff2cb67" width="80%" /></p>
<figcaption><p align="center">A messenger trying to find its path in an unknown land</p></figcaption>
</figure>
---
Don't be fooled by the number of new lines in this PR, patches are small and relatively easy to read. Most of the new lines are documentation or tests (around 1300).
The idea of this PR is to create a mapping between events to timeline items. More precisely, a mapping between event indexes and timeline item indexes. Why is this needed? We want `Timeline` to receive its updates via `VectorDiff`. Those `VectorDiff` are generated by the `EventCache` (via `linked_chunk::AsVector`). The indexes from these `VectorDiff` —like …

refactor(ui): Create a mapping between remote events to timeline items

---

bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This adds a way to:
- clear all the rooms' linked chunk, all at once: this will be useful when disabling the feature flag
- clear a single room's event cache persistent storage: this should be useful for testing purposes, and in case storage is completely borked
- enable a feature flag on an FFI `ClientBuilder` to enable or disable persistent storage. Note: after persistent storage has been enabled, if the embedder decides to disable it, they must explicitly set it to `false` the next time; otherwise the on-disk storage isn't cleared.
The last item isn't very satisfying, but I don't see how to do it otherwise without more involved refactorings. The way persistent storage works right now, is by checking the presence of an event cache store reference in the `RoomEventCacheState` data …

feat(event cache): add a way to clear all chunks, clear a room's chunks + FFI feature flag

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/mod.rs

Adds a number of new properties to the `UnableToDecryptInfo` that is passed to the application-level `UnableToDecryptHook`.
Part of https://github.com/element-hq/element-meta/issues/2582

feat(ui): Add new properties to `UnableToDecryptInfo`

---

crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Fix extracted from #4329. 
The `MediaFormat` reflects only the request that would be made to the homeserver. There is no link between the format of the files stored in the media cache and their purpose in an event. `MediaFormat::Thumbnail` means that we request a server-generated thumbnail of a file in the media repository. Since the thumbnail is its own file in the media repository, it makes more sense to use `MediaFormat::File`. See https://github.com/matrix-org/matrix-rust-sdk/pull/4329#discussion_r1873122697 for even more details why this change makes sense.
The fix was simplified a lot here. Instead of requiring a migration, we just minimize the changes in the format of the send queue request in the state store and keep handling the previous case.
This also documents the caching of …

fix(send_queue): Use `MediaFormat::File` when caching attachment thumbnail

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/builder.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

- commit 1: refactor in preparation for commit 3; instead of rebuilding the linked chunk in the event cache store impl, do it one layer above. It's similar code all the cache store impls had to copy/paste themselves + it will allow us to inspect the chunks whenever something goes wrong.
- commit 2: display a debug string showing the raw state of a linked chunk, which allows to display invalid states, in particular. Use that display whenever rebuilding the linked chunk fails, in the event cache.
- commit 3: when rebuilding a linked chunk fails, clear the storage, and start afresh.
- commit 4: spawn a task when handling updates to storage, so that it can't be interrupted.
- question for reviewer: this relies on the fact that getting the store lock requires holding onto a real mutex. I'm …

feat(event cache): improve event cache storage a bit (debug, resilience,…)

---

bindings/matrix-sdk-ffi/src/sync_service.rs

Followup to https://github.com/matrix-org/matrix-rust-sdk/pull/4360: expose the new properties via FFI
Part of element-hq/element-meta#2582

feat(ffi): Add new properties to `UnableToDecryptInfo`

---

crates/matrix-sdk-base/src/store/memory_store.rs

The `MemoryStore` implementation of the `StateStore` has grown into a monster, with one lock per field. It's probably overkill, as individual fields don't need fine-grained locks like this; after all, accesses to the store shouldn't be reentrant in general.
Also allows us to get rid of some annoying trace logs, which is the reason why I was reminded of this problem.
Fixes #3720.
Let's see how Complement Crypto likes it…

refactor(state store): use a single lock for all memory store accesses

---

bindings/matrix-sdk-crypto-ffi/build.rs
bindings/matrix-sdk-ffi/build.rs

Update the workaround for https://github.com/rust-lang/rust/issues/109717 to avoid hardcoding the clang version; instead, run `clang -dumpversion` to figure it out.
While we're there, use the `CC_x86_64-linux-android` env var, which should point to clang, rather than relying on `ANDROID_NDK_HOME` to be set.

chore(ffi): avoid hardcoding clang version

---

crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs

We forgot that under sliding sync we won't have access to all state events, which meant that #4335 never got working.
The first commit adds the relevant event to the required state for the UI crate.
The second commit fixes another edge case in the case where we homeserver does provide a room summary containing service members in the heroes and thus in the joined members count.

Ensure that we request the correct state event for the service members to work correctly

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs

This is unfortunate, but we're hitting a bad case of a read transaction upgrading to a write transaction, and that can plain fail if there's any other write transaction already happening in the background.
To work around this, we need to start the transaction in write mode, so start with the update statements themselves. This means some work is duplicated (fetching a linked chunk), but this should be fine since there's an index on the pair (chunk id, room id).

fix(event cache store): use immediate transactions in `handle_linked_chunk_updates`

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/types/events/utd_cause.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk/src/room/mod.rs

Part of https://github.com/element-hq/element-meta/issues/2638
Distinguish between 3 cases where we can't find keys for an old message:
- There is no backup -> `HistoricalMessageAndBackupIsDisabled`
- Backup is not working and we have not verified our device -> `HistoricalMessageAndDeviceIsUnverified`
- Something else -> `Unknown`

Provide the reason why an event was an expected UTD

---

bindings/matrix-sdk-crypto-ffi/src/dehydrated_devices.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/dehydrated_devices.rs
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-crypto/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/utils.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4186
No need for migration, the pickle key is stored in the generic Key/Value store.
Signed-off-by:

feat(crypto): Support storing the dehydrated device pickle key

---

crates/matrix-sdk/build.rs

The cargo feature was removed in #4132, but the build script was forgotten.

chore(sdk): Remove image-rayon cargo feature check from build.rs

---

crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/tests/integration/event_cache.rs

This started as a refactoring of the event cache's logic for back-paginations, for other purposes, but turns out there was a bug if you were in the following conditions:
- a room has some events
- the room doesn't have a prev-batch token / a gap
In this case, if we ran a back-pagination, the next prev-batch token would be in the wrong position, compared to the events that we just back-paginated. Which means that the next back-pagination would insert events in the wrong place. The integration test I added acts as a regression test, which failed on main.

fix(event cache): fix back-pagination ordering in one specific case

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/identities/user.rs

Add some extra logging in these two methods, to try to narrow down a bug report
we received.

crypto: extra logging in `OtherUserIdentity`

---

Cargo.lock
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/deserialized_responses.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/room/knock_requests.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/request_to_join.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/room/joined.rs

This PR adds support for listening to changes in requests to join a room (aka: knock memberships): to do this, we listen to new room member events to trigger the emission of a new list of join requests, as well as to the `RoomInfo::members_synced` flag to understand if we need to reload the room members because a gappy sync happened
Since having too many/old requests to join to display can be an UX problem, I added the concept of a 'seen' join request, and an internal set of join request ids (these referencing the knock membership event), so we can mark some of these join requests as seen and filter them out in the clients at will. Also, when a join request is marked as seen, a new list of join requests is emitted with the updated value.
When a user of a knockable room has the power level …

feat(room): add `JoinRequest` subscriptions

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
labs/multiverse/src/main.rs

I think that this debug representation may show useful to understand issues. Just from using it a few minutes, I've identified a few issues related to storage:
- we shouldn't have empty items chunks; they should be removed, or even better, reused.
- we may have multiple prev-batch token that represent the same events, e.g. if we sync'd a room with timeline_limit=1, then with timeline_limit=20. Not sure if there's anything obvious to do about that.
- edit: yes there is! do not store a prev-batch token when all the events (at least 1) returned from the backpagination are known. Should be a sufficiently good heuristic 🧠

feat(event cache): have a debug representation of a linked chunk and use it in multiverse

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs

This is needed to tell apart rooms in left and banned state in places like `RoomInfo` or `RoomPreview`.
The banned rooms will still count as left rooms in the sync processes.
Signed-off-by:

feat(room): Separate `RoomState::Ban` from `RoomState::Left`.

---

bindings/matrix-sdk-crypto-ffi/src/dehydrated_devices.rs
bindings/matrix-sdk-crypto-ffi/src/error.rs
bindings/matrix-sdk-crypto-ffi/src/lib.rs
crates/matrix-sdk-crypto/src/dehydrated_devices.rs
crates/matrix-sdk-crypto/src/store/mod.rs

Draft because depends on https://github.com/matrix-org/matrix-rust-sdk/pull/4383
Signed-off-by:

feat(crypto-ffi-bindings): Save/Load dehydrated pickle key

---

crates/matrix-sdk-crypto/src/machine/tests/megolm_sender_data.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk/src/encryption/mod.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This is a partial fix for https://github.com/matrix-org/matrix-rust-sdk/issues/4189.
The fix works if you don't use the cross-process lock, otherwise the stream gets destroyed and updates don't come in anymore.
Opening as a draft, still needs a test.

Retry decryptions based on the room key stream of the OlmMachine

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs

The previous code would skip based on the position's index, but not the position's chunk. It could be that the position's chunk is different from the first items chunk, as shown in the example, where the linked chunk ends with a gap; in this case, the position's index would be 0, while the first chunk found while iterating backwards had 3 items. As a result, items 'd' and 'e' would be skipped incorrectly.
The fix is to take into account the chunk id when skipping over items.

fix(linked chunk): in LinkedChunk::ritems_from, skip as long as we're on the right chunk

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/tests/integration/event_cache.rs

It was simpler to add a new function rather than trying to fiddle with `replace_gap_at`, especially in terms of the return type of this function. After a few back-and-forth, they're close enough that we could probably merge them together, if you have strong opinions about it.
This was the only place where we'd create an empty chunk, so with this, the storage doesn't keep empty chunks anymore \o/
Part of #3280.

feat(event cache): don't replace a gap chunk by an empty items chunks

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4424 in the release-for-crypto-wasm-11 branch
Rebased version of https://github.com/matrix-org/matrix-rust-sdk/pull/4425 on top of the newly-created `release-for-crypto-wasm-11` branch.

Fix error loading older sender data from storage

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs

This patch updates the documentation of `AsVector`.

doc(common): Update documentation of `AsVector`

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs

The code would use a chunk iterator that moves forward, but call `push_front()` repetitively on each chunk, semantically storing the lengths in *reverse* order.
This could result in subsequent panics, when a new chunk was added, because the links would not match what's expected (e.g. the last chunk must have no successor, etc.).

fix(linked chunk): fix order handling of initial chunks in `UpdateToVectorDiff::new`

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/identities/user.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs

Port the fix for https://github.com/matrix-org/matrix-rust-sdk/issues/4424 onto the version that was used in matrix-rust-sdk-crypto-wasm v12.0.0

Cherry-pick fix for #4424 onto release-for-crypto-wasm-12

---

crates/matrix-sdk/src/event_handler/mod.rs

The code in `Client::handle_sync_events` and `Client::handle_sync_state_events` call `Client::call_event_handlers`, which takes a single event and it gives the impression of the underlying event handler notifying the subscribers once per each event fed to it, which is the opposite behaviour to what `Room::observe_events` docs state:
> Be careful that only the most recent value can be observed. Subscribers are notified when a new value is sent, but there is no guarantee that they will see all values.
It turns out it works like that because the sender will be fed items way faster than the receiver can handle them if I'm not mistaken.
This behaviour wasn't tested before AFAICT, so I added a test to make sure the described behaviour doesn't regress at some point.
Signed-off-by:

test(room): add test to verify `Room::observe_events` with several events

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

In a previous PR (https://github.com/matrix-org/matrix-rust-sdk/pull/4338) we introduced the concept of a 'seen' knock request id, that is, a member event with knock membership that the current user has seen and decided to explicitly ignore so it can be filtered out in the future in the clients and won't clutter the UI. However, if left alone this list will only grow indefinitely, so we need a way to observe the changes in knock room members in the room and remove outdated seen request ids.
Take this PR as a follow-up of the one mentioned above.
A new `matrix_sdk_base::room_member_updates_sender` field was added too, which will broadcast when a room members update is received, both when loading the room members from the HS and when new member state events are received in a sync.
On `fn …

feat(room): add `Room::remove_outdated_seen_knock_requests_ids` method

---

crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/paginator.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

We have a problem right now, with the event cache storage: as soon as you receive a previous-batch token, either from the sync or from a previous back-pagination, we consider that we may have more events to retrieve in the past. Later, after running back-paginations, we may realize those events are duplicated. But since a back-pagination will return another previous-batch token, until we hit the start of the timeline, then we're getting stuck in back-pagination mode, until we've reached the start of the timeline again.
That's bad, because it makes the event cache store basically useless: every time you restore a session, you may receive a previous-batch token from sync (even more so with sliding sync, which will give one previous-batch token when timeline_limit=1, then another one when …

feat(event cache): avoid storing useless prev-batch tokens

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs
crates/matrix-sdk-crypto/src/olm/session.rs
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-crypto/src/types/events/olm_v1.rs

Part of https://github.com/element-hq/element-meta/issues/2665
On the receiving side, allow `sender_device_keys` as well as `org.matrix.msc4147.device_keys` for the sender's device keys in to-device event. Once this has time to bed in, we will change the sending side to use this stable identifier since the MSC has been merged.

task(crypto): Support receiving stable identifier for MSC4147

---

crates/matrix-sdk-crypto/src/identities/room_identity_state.rs
crates/matrix-sdk/src/room/mod.rs

This is an 8 seconds (out of 22) decrease of the matrix-sdk compile times. `BoxFuture` ftw.

refactor: avoid use of `async_trait` for `RoomIdentityProvider`

---

.github/workflows/ci.yml
CONTRIBUTING.md
Cargo.lock
Cargo.toml
crates/matrix-sdk-common/Cargo.toml
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_algorithm_info.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_encryption_info.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes-2.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes-3.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes-4.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes-5.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes-6.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_codes.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_states-2.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_states-3.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_shield_states.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_sync_timeline_event.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_level-2.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_level-3.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_level-4.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_level-5.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_level.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_states-2.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_states-3.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_states-4.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_states-5.snap
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__snapshot_test_verification_states.snap

Tentative to introduce snapshot testing using [insta.rs](https://insta.rs/).
Added some initial doc on the Contributing.md file
As a draft now, because I have some open questions on how to do things.
I need also to see what to do for CI
> Insta behaves differently in CI environments. For instance it will not write new snapshot files. This behavior is enabled by the CI environment variable. Please ensure that your CI system sets it.
`export CI=true`
Signed-off-by:

test(snapshot): Use snapshot testing in sdk-common

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/client/futures.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/encryption/backups/mod.rs
crates/matrix-sdk/src/encryption/identities/devices.rs
crates/matrix-sdk/src/encryption/identities/users.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/encryption/verification/sas.rs
crates/matrix-sdk/src/matrix_auth/login_builder.rs
crates/matrix-sdk/src/matrix_auth/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/notification_settings/mod.rs
crates/matrix-sdk/src/oidc/mod.rs
crates/matrix-sdk/src/pusher.rs
crates/matrix-sdk/src/room/futures.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room_preview.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/src/widget/matrix.rs
examples/get_profiles/src/main.rs

Instead of `Client::send(request, request_config)`, consumers can now do `Client::send(request).with_request_config(request_config)`. The parameter is still `Option`al to avoid messy patterns, when the `request_config` is an `Option` passed from the caller.
The messy pattern would look like this, if `with_request_config` took a `RequestConfig` and not an `Option<RequestConfig>`:
```
let mut send_req = client.send(req);
if let Some(request_config) = request_config {
send_req = send_req.with_request_config(request_config);
}
```

refactor!(client): replace the optional `RequestConfig` arg to `Client::send()` with a `with_request_config()` builder method

---

bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/session_verification.rs
bindings/matrix-sdk-ffi/src/timeline/content.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/utils.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/polls.rs

This PR adds a new type alias to the matrix-sdk-ffi crate called Date64.  This is aliased to u64 for backwards compatibility (so no change to Swift/Kotlin as is), but as a distinct type it will allow uniffi integrations to customize the unpacking of the type automatically: https://mozilla.github.io/uniffi-rs/latest/udl/custom_types.html
Using this, it is possible to make the uniffi layer automatically convert these from u64 -> an appropriate system Date class in the generated code layer.  
Today a `u64` type can mean either a count or a date, so without an alias implementing a customType would not be possible.  At the very least, the type helps improve the documentation, even if individual bindings choose not to adopt this in their UDL configs.

Use a type alias to allow bindings to take advantage of custom types

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/room_list_service/filters/non_left.rs

Recently we started to differentiate between rooms we've been banned from from rooms we have left on our own.
Sadly the non-left rooms matcher only checked if the room state is not equal to the Left state. This then accidentally moved all the banned rooms to be considered as non-left.
We replace the single if expression with a match and list all the states, this way we're going to be notified by the compiler that we need to consider any new states we add in the future.
This closes: #4447.

fix(ui): Consider banned rooms as rooms we left in the non-left rooms matcher

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/attachment.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

`AttachmentConfig::with_thumbnail()` is replaced by `AttachmentConfig::new().thumbnail()`.
Simplifies the use of `AttachmentConfig`, by avoiding code like:
```rust
let config = if let Some(thumbnail) = thumbnail {
AttachmentConfig::with_thumbnail(thumbnail)
} else {
AttachmentConfig::new()
};
```

refactor!(sdk): Set thumbnail in `AttachmentConfig` with builder method instead of constructor

---

crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

Every caller to `with_events_mut` must propagate the vector diff updates, otherwise updates would be missing to the room event cache's observers. This slightly tweaks the signature to make this a bit clearer, and adjusts the code comment as well.

refactor(event cache): make it clearer that vecdiff updates must be handled in `with_events_mut`

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/futures.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs

Sometimes we can get the bytes directly, e.g. in Fractal we can get an image from the clipboard. It avoids to have to write the data to a temporary file only to have the data loaded back in memory by the SDK right after.
The first commit to accept any type that implements `Into<String>` for the filename is grouped here because it simplifies slightly the second commit.
Note that we could also use `AttachmentSource` in the other `send_attachment` APIs, on `Room` and `RoomSendQueue`, for consistency.

feat!(timeline): Allow to send attachments from bytes

---

crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-common/src/store_locks.rs
crates/matrix-sdk-common/src/tracing_timer.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs
crates/matrix-sdk-ui/src/room_list_service/state.rs
crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/widget/machine/pending.rs

web-time's Instant type is already used elsewhere in the project. It is an alias for std's Instant type on most targets, but tries to call into JavaScript on wasm32-unknown-unknown (assuming that the wasm blob is used in from a browser context). Its Duration type is a plain re-export of std's Duration, even on wasm32-unknown-unknown. (it is only used to avoid splitting the `time::` import in two)

Use Instant from web-time in more places (via ruma re-export)

---

crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk/src/send_queue.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Instead of keeping on handling unwedged events from the sending queue, it's now required to re-enable the send queue manually for the room that encountered the sending error, all the time. This is more consistent, and avoids weird behavior when a user would 1. send an event for which sending fails, in an unrecoverable manner, 2. send an event that's actually sendable.
Fixes #4389.

feat!(send queue): make unrecoverable errors stop the sending queue

---

crates/matrix-sdk-base/src/rooms/normal.rs

It claimed that it would immediately return when the cached display name value was computed, but that's absolutely not the case.
Spotted while reviewing a PR updating `iamb` to the latest version of the SDK.

doc(base): update lying doc comment of `compute_display_name`

---

crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs

With experimental-sliding-sync enabled and e2e-encryption disabled, there were a bunch of warnings about unused imports. This fixes them (but a few warnings about other unused items remain).

Clean up some imports

---

crates/matrix-sdk-common/src/linked_chunk/builder.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/updates.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
crates/matrix-sdk-indexeddb/src/safe_encode.rs
crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/sliding_sync/list/mod.rs
testing/matrix-sdk-test/src/test_json/keys_query_sets.rs

We have quite a few `allow(dead_code)` annotations. While it's OK to use in situations where the Cargo-feature combination explodes and makes it hard to reason about when something is actually used or not, in other situations it can be avoided, and show actual, dead code.

chore: remove some `allow(dead_code)` annotations

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

Since 8205da898e11c34b77b13fe4794d0b2e1bcdd2a8 it has been possible to attach (intentional) mentions to _edited_ media captions, but the `send_${mediatype}()` timeline APIs provided no way to send them with the initial event. This fixes that.
If I missed something, or completely got the wrong end of the stick, feel free to decline this or point me in the right direction. I'm not familiar with Rust, but this at least compiles and doesn't crash EXA on my phone.

feat(timeline): allow sending mentions along with media

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs

This patch adds the `Pagination` variant to the `EventsOrigin` enum. Not something really mandatory and that is likely to fix a bug, but it's now correct.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4462

feat(sdk,ui): Add `EventsOrigin::Pagination`

---

crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs

What's on the tin. Add one level of indentation.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4462

chore: Re-indent a macro

---

crates/matrix-sdk/src/event_cache/room/events.rs

This patch renames `RoomEvents::filter_duplicated_events` to `collect_valid_and_duplicated_events` as I believe it improves the understanding of the code. The variables named `unique_events` are renamed `events` as all (valid) events are returned, not only the unique ones.
---
* Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4462

refactor(sdk): Rename `RoomEvents::filter_duplicated_events`

---

crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/snapshots/matrix_sdk_crypto__olm__group_sessions__sender_data__tests__snapshot_sender_data-4.snap
crates/matrix-sdk-crypto/src/olm/group_sessions/snapshots/matrix_sdk_crypto__olm__group_sessions__sender_data__tests__snapshot_sender_data-5.snap
crates/matrix-sdk-crypto/src/olm/group_sessions/snapshots/matrix_sdk_crypto__olm__group_sessions__sender_data__tests__snapshot_sender_data-6.snap

Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/4449
While adding snapshot test, I detected that sender's data `KnownSenderData` was serializing the cross-signing master key as an array of number. This PR changes that and now serialize the key as a base64 string, adding migration for the old format.
Signed-off-by:

fix(crypto): Serialize sender data msk in base64 instead of numbers

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

Number of parameters and code duplication has gone a bit too wild lately.

refactor(ffi): clean up functions to send medias

---

bindings/matrix-sdk-ffi/src/platform.rs

If it's present, we just let it untouched. Otherwise, we set it to `error` if it's missing. See code comment explaining why we need this.
This makes sure we log panics at the FFI layer, since the log_panics crate will use an error level, with a target that's likely unknown to the user providing the log filter configuration.

fix(ffi): ensure there's always a global directive for logs

---

bindings/matrix-sdk-ffi/Cargo.toml
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync/mod.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/futures.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/error.rs
crates/matrix-sdk/src/http_client/mod.rs
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/src/sliding_sync/cache.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sliding_sync/error.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/sliding_sync/room.rs
crates/matrix-sdk/src/sliding_sync/utils.rs
crates/matrix-sdk/tests/integration/encryption/backups.rs
crates/matrix-sdk/tests/integration/room_preview.rs
xtask/src/ci.rs

Sliding sync is no longer experimental. It has a solid MSC4186, along with a solid implementation inside Synapse. It's time to consider it mature.
The SDK continues to support the old MSC3575 in addition to MSC4186. This patch only removes the `experimental-sliding-sync` feature flag.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3647

feat: Remove the `experimental-sliding-sync` feature flag

---

crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk/src/client/mod.rs

Not sufficient for compiling the UI crate on WASM, but smaller PRs = better.

Some WASM-related refactors

---

crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

It's nice to have some logs when background tasks are shutting down, and also about other kinds of changes related to the event cache.

chore(event cache): add more logs here and there

---

crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs

This fixes the deserialization of the SenderData since it switched to the base64 encoding for serialization of the master key in one of its variants.
The issue was introduced in 5ff556f6c3026ab53b21ba0b0a24749ffa715e17 (#4450).

fix: Implement visit_bytes for the Ed25519PublicKey deserialization

---

crates/matrix-sdk-store-encryption/CHANGELOG.md
crates/matrix-sdk-store-encryption/src/lib.rs

Found during my crusade against unwraps in the codebase.

fix(store-encryption): Remove an unwrap that snuck in

---

bindings/matrix-sdk-ffi/src/ruma.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/attachment.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

Using MSC4230.
While I was in the area I added a second commit to implement `Default` for the `Base*Info` types since they only have optional fields and it is easier to construct them that way when we don't want to set all fields.

feat(sdk): Allow to set and check whether an image is animated

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs

We have one specific use case at the moment for this in Fractal, to build the [UIAA fallback URL](https://spec.matrix.org/v1.13/client-server-api/#fallback) depending on the Matrix version.  Currently we always use the r0 version that is hardcoded in our code.
But I also don't see why it should not be public.

feat(sdk): Expose Client::server_versions publicly

---

xtask/src/release.rs

As an outsider, I am mostly interested in features and new developments that have happened, not those that *may* happen. An open-but-not-merged PR may not get merged in the end, or it may not get merged any time soon, creating false expectations. Merged PRs, on the other hand, have definitely happened (even if they get undone, that happens via other PRs that will get merged later). As such, I think it brings more value to outsiders.

chore(xtask): tweak the TWiM report to include only merged PRs, not created PRs

---

Cargo.lock
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_info.rs
bindings/matrix-sdk-ffi/src/room_list.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/privacy_settings.rs
crates/matrix-sdk/src/test_utils/mocks.rs
testing/matrix-sdk-integration-testing/src/tests.rs
testing/matrix-sdk-integration-testing/src/tests/room_privacy.rs

These include:
- Updating the canonical alias.
- Creating and removing a room alias from the room directory.
- Enabling encryption in a room.
- Updating the join rule of a room.
- Updating the room history visiblity.
- Updating the room visibility in the room directory.
Also, expose the room history visibility through the FFI RoomInfo.
Signed-off-by:

feat(room): add methods to customise a Room's privacy settings

---

bindings/matrix-sdk-ffi/src/encryption.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/encryption/recovery/mod.rs

While the former name is arguably more fun, the latter is more descriptive of what the function does.

chore!(encryption): rename `are_we_the_last_man_standing` to `is_last_device`

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/error.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk/tests/integration/room/left.rs

Does what it says on the tin, and fixes a bug where clearing a room in the in-memory linked chunk would clear *all* rooms at once.
Part of #3280.

feat(event cache): remove events when forgetting a room

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs

Should fix https://github.com/element-hq/element-x-ios/issues/3669.
Take into account the `should_add` parameter for including UTDs in the timeline, as is done for other types of events.
Signed-off-by:

fix(timeline): Add UTDs to the timeline conditionally

---

bindings/matrix-sdk-ffi/src/room_member.rs
bindings/matrix-sdk-ffi/src/room_preview.rs
crates/matrix-sdk/src/room/mod.rs

This will retrieve the room member info of both the current user and the info for the sender of the current user's room member event and make it accessible in the FFI layer.
This is needed for `RoomPreview` to display messages such as 'you were banned from this room by Foo'.
Signed-off-by:

feat(room): Add fn Room::own_membership_details

---

Cargo.lock
testing/matrix-sdk-test/Cargo.toml
testing/matrix-sdk-test/src/lib.rs
testing/matrix-sdk-test/src/test_json/keys_query_sets.rs
testing/matrix-sdk-test/src/test_json/snapshots/matrix_sdk_test__test_json__keys_query_sets__KeyDistributionTestData::dan_keys_query_response.snap
testing/matrix-sdk-test/src/test_json/snapshots/matrix_sdk_test__test_json__keys_query_sets__KeyDistributionTestData::dan_keys_query_response_device_loggedout.snap
testing/matrix-sdk-test/src/test_json/snapshots/matrix_sdk_test__test_json__keys_query_sets__KeyDistributionTestData::me_keys_query_response.snap
testing/matrix-sdk-test/src/test_json/snapshots/matrix_sdk_test__test_json__keys_query_sets__VerificationViolationTestData::own_keys_query_response_1.snap

Currently it's very hard to extend our test data because it has been generated manually with real users and devices. I'd like to change that so that the data is created more dynamically, so that it is easier to extend.
This PR introduces a builder type which can be used to help construct such test data, and rebuilds some of the existing test data using it. Unfortunately we're lacking some private keys, so I've had to replace a couple of keys.
The PR also introduces some snapshots, so we can keep an eye on how the data is changing.
Recommend reviewing commit-by-commit.

Implement test helpers for constructing user device data

---

crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk/src/room/identity_status_changes.rs

This is intended to prevent the test
`test_when_user_in_verification_violation_becomes_verified_we_report_it` flaking. I found that sometimes when it called `Room::members` the result was empty due to it trying to fetch the answer from the server. This change prevents that behaviour. I don't know why the behaviour was inconsistent before.

fix(tests): Fix a flaky test by marking a room's members as synced.

---

crates/matrix-sdk/src/event_cache/mod.rs

This is unlikely that it will affect us, so not worth adding a test IMO, but for the sake of completeness: this handles redacted redactions in the `AllEventsCache` too.

feat(event cache): handle redacted redactions in the `AllEventsCache`

---

crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/linked_chunk/as_vector.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-common/src/linked_chunk/updates.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

This makes it possible to:
- replace one item in a linked chunk, and have all the consumers handle the update. This will be useful for the second part of the PR (applying redactions to the linked chunk), and in the future to replace decrypted events ([when decryption happens in the event cache](https://github.com/matrix-org/matrix-rust-sdk/issues/3872)).
- redact, in memory and in storage, an event by its redacted form, so that it's not possible to read it on disk.
We _could_ add a migration to apply redactions for existing users of the nightly cache. I'd rather do this as a followup, since this PR is growing a bit large already (and another possibility is also to clear all events stored in the event cache, as a dirty yet safe migration — we might need this because I spotted an …

feat(event cache): redact previously-seen events in the linked chunk too

---

testing/matrix-sdk-test/src/test_json/keys_query_sets.rs

#4476 added some test helpers to generate `/keys/query` responses. We're going to need to test dehydrated devices, so this PR adds support for that.

test: add support for dehydrated devices to `KeyQueryResponseTemplate`

---

bindings/matrix-sdk-ffi/src/platform.rs

Setting the default log level to `debug` results in logs like:
```
log: log_event
log: latest_event
log: log_event
log: log_event
log: room_info
log: latest_event
log: log_event
log: room_info
```
Presumably they're coming out of the custom tracing configuration and we definitely don't need them

chore(ffi): silence useless logs coming out of the ffi crate

---

testing/matrix-sdk-test/src/test_json/keys_query_sets.rs

Generating keys from slices rather than base64 is easier.
Also, s/builder/template/.

test: simplify examples for `KeyQueryResponseTemplate`

---

crates/matrix-sdk-crypto/src/types/device_keys.rs

This confused me for a while, so I thought more documentation might help.

crypto: add some more documentation to `DeviceKeys`

---

crates/matrix-sdk/src/http_client/mod.rs

The dependencies required for the `experimental-oidc` feature don't currently compile on WASM, but once they do this is another thing inside this repo that's required for the feature to work on WASM.

Use Send-less BoxFuture for HttpClient Service impl on wasm

---

crates/matrix-sdk/src/event_cache/room/mod.rs

This patch removes a `XXX` (which I believe is a TODO) in the documentation of `RoomEventCache::subscribe`. We are not going to change this API anytime soon.

doc(sdk): Simplify documentation of `RoomEventCache::subscribe`

---

.github/workflows/ci.yml
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/lib.rs
xtask/src/ci.rs

Check matrix-sdk-ui compilation on wasm in CI

---

crates/matrix-sdk/src/live_location_share.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/beacon/mod.rs

This change ensures that the user's own live location events are excluded from the location sharing stream. Since the user's location is already represented on the map by the blue dot, processing their own events is redundant and unnecessary.

refactor(live_location_share): exclude live location events of own user

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/remote.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs

This was a regression introduced in f0d98602a9e65cf26a607cf10a0715b92da12d4a.
`latest_edit_json` was first set by the call to `EventTimelineItem::with_content()`. It was overwritten in the next section because of the `if let EventTimelineItemKind::Remote(remote_event)` that uses `item` instead of `new_item`.
It means that the updated `RemoteEventTimelineItem` inside`new_item` was replaced by the outdated one inside `item`, so `latest_edit_json` went back to its previous value.
I believe that part of why that went unnoticed is that the code looks more complicated due to the need to set an inner field dependant on an enum variant, so I decided to change the API and move `with_encryption_info` to `EventTimelineItem`, which makes the code look cleaner.
The changes in the tests fail without …

fix(ui): Fix `latest_edit_json` for live edits

---

Cargo.lock
Cargo.toml

Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4531.
This patch updates ruma to the latest commit at the time of writing.
I'm really not sure about what I'm doing, so please be careful during the review 😛.

chore: Update to latest Ruma version

---

crates/matrix-sdk/src/room/knock_requests.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/common.rs
crates/matrix-sdk/tests/integration/room/joined.rs
testing/matrix-sdk-test/src/event_factory.rs

It was used in places where we could make use of other helpers, in some cases. Also introduces the `room_avatar` helper to create the room avatar state event.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3716

test: minimize usage of `EventFactory::state_key`

---

crates/matrix-sdk-ui/tests/integration/main.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk/src/test_utils/mocks.rs

Changes:
- Make sure the `pinned_event` integration tests use `MatrixMockServer` behind the scenes.
- Fix a bug in the `RoomEventEndpoint` that caused the `match_event_id` option to not actually work because the event id has a `$local-part:server-name` format and the `path_regex` function of WireMock would parse the whole `^/_matrix/client/v3/rooms/.*/event/$local-part:server-name` as just `^/_matrix/client/v3/rooms/.*/event/$` because it'll take the `$` char as the 'end of regex' one.
- Remove unused `mock_event` legacy mocking method.
- Remove redundant `TestHelper`.
Signed-off-by:

test: Update the `pinned_event` integration tests code

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_handler/mod.rs
testing/matrix-sdk-test/src/event_factory.rs

test: remove some uses of `sync_timeline_event!` in the base and sdk crates

---

Cargo.lock
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml

It became an optional default feature in reqwest 0.12, and we disable the default features, so I don't think it was meant to be disabled when the crate was upgraded in https://github.com/matrix-org/matrix-rust-sdk/pull/3362.

feat(sdk): (re)Enable HTTP/2 support

---

benchmarks/benches/room_bench.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
examples/timeline/src/main.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This patch removes `Timeline::subscribe` and keeps `::subscribe_batched`, which is the only method that is really used.
Edit: I agree that's a non-negligible amount of work, but we want to clean up this API. The more API, the more maintenance and documentation. Also, `subscribe_batched` is more performant from the caller's perspective. Finally, we want the test to use the same API as more users are using, which is the case now with this PR.

chore(ui): Remove `Timeline::subscribe`

---

bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/timeline/configuration.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs

What it says on the tin. Fixes #4554

chore(ffi): add a message focused timeline variant that allows focusing on a particular event

---

crates/matrix-sdk/src/authentication/mod.rs

Noticed, this when looking at #4575. It was done in #3587/#3594.

Chore: Remove an old todo item.

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-ui/src/room_list_service/room_list.rs

A bounds check was recently relaxed in `imbl`'s `Focus::narrow()` function: https://github.com/jneem/imbl/pull/89, which fixed a bug that would cause a panic if the downstream user of `matrix-sdk-ui` attempted to narrow a focus of Timeline items using a `Range` that included the last item in the Timeline. Example: https://github.com/project-robius/robrix/issues/330
This fix has been incorporated in `eyeball-im` and `eyeball-im-util` and has been tested by me in Robrix to no longer trigger upon the aforementioned conditions.
Signed-off-by: Kevin Boos kevinaboos@gmail.com

Upgrade `imbl`, `eyeball-im`, `eyeball-im-util` to fix bounds check

---

bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/live_location_share.rs
bindings/matrix-sdk-ffi/src/room.rs

FFI functions for starting ,stopping and subscribing to Live Location Shares. 
Signed-off-by: 
Torry Brelsford

feat(beacons): expose ffi functions to start, stop and subscribe to live location shares

---

Cargo.lock
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs

- supports only text room message types
- enumerates through their body's grapheme clusters and check that every single one of them is an emoji
- part of the `LazyTimelineItemProvider` so that it can be opt in

feat(ui): expose a method for checking whether a message contains only emojis and should be boosted (use a bigger font size)

---

bindings/matrix-sdk-crypto-ffi/src/lib.rs
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/error.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/matrix_sdk_crypto__session_manager__group_sessions__share_strategy__tests__serialize_device_based_strategy.snap

Currently, we have two `CollectStrategy` settings, of which one (`DeviceBasedStrategy`) is a bit of a confusing mess of options. Let's split things up so that each option has its own strategy; I find this makes the behaviour much clearer.
It takes quite a bit of refactoring to get there in a way which doesn't end up duplicating a lot of code. Suggest review commit-by-commit.

crypto: refactor the room key sharing strategies

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
labs/multiverse/src/main.rs

This patch simplifies the `Timeline` pagination API as follows:
- a unique `paginate_backwards` method (no more
`focused_paginate_backwards` and `live_paginate_backwards`),
- a unique `paginate_forwards` method (no more
`focused_paginate_forwards`, the `live` variant was absent).
The idea is to unify pagination by hiding the `live` and `focused` mode.
It was already partially the case with `paginate_backards`, but the
`live` and `focused` variants were also present. I believe it creates
an unnecessary confusion.

refactor(ui): Unify the Timeline pagination API

---

benchmarks/benches/room_bench.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
examples/timeline/src/main.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This patch renames `Timeline::subscribe_batched` to
`Timeline::subscribe`. Since the `Timeline::subscribe` method has been
removed because unused, it no longer makes sense to have a “batched”
variant here. Let's simplify things!
---
* Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/4567/.
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/3280.

chore(ui): Rename `Timeline::subscribe_batched` to `Timeline::subscribe`

---

Cargo.lock
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/sync_service.rs
crates/matrix-sdk-ui/tests/integration/sync_service.rs

These are mostly internal changes and don't contain any behavioral change, except for some edge cases that are now a bit better handled.
A review commit by commit should ease the task a bit, but reading the whole file shouldn't be too terrible either, it's not that big.

Refactor and clean up the SyncService

---

crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/test_helpers.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4466

Ignore to-device messages from dehydrated devices

---

crates/matrix-sdk-crypto/src/gossiping/machine.rs
crates/matrix-sdk-crypto/src/store/caches.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs

Attempt to make the memory store behave more like other stores. 
This is following reports of [Playwright flaky tests](https://github.com/element-hq/crypto-internal/issues/414) that are showing some panics of the memory store (used by the bots not the tested app).
The idea is to make the memory store works more like other stores by removing `unwrap()`s, serializing/deserialising structures instead of keep them around to be mutated by everyone. Add a global save_changes lock
Will behave more like other stores (might help and make the tests less flaky)
Might be slower
Best reviewed commit per commit (will squash at the end):
- Replace unwrap with expect https://github.com/matrix-org/matrix-rust-sdk/commit/17fa2c791dbdea0212f37117c4aa477ae8dac2a7
- Serialize account and cache static account …

refactor(crypto): Make memory store behave more like other stores

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs

The `Timeline` contained 2 _input API_: `add_events_at` and `handle_remote_events_with_diffs`.
Refactoring after refactoring, the former was only used by tests and by some internal API. The first patches replace uses of `add_events_at` by `handle_remote_events_with_diff` until we can remove this method.
After that, I've noticed that `add_remote_events_at` may be in a similar position. The next patches replace uses of `add_remote_events_at` by `handle_remote_events_with_diff` until we can remove this method.
Finally, the `HandleManyEventsResult` and `TimelineNewItemPosition` types are unused, and can be removed.
Everything looks simpler and a single API is used: `handle_remote_events_with_diffs`.

chore(ui): Move to a single input API for the `Timeline`, and remove many types and methods

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/matrix_sdk_crypto__session_manager__group_sessions__share_strategy__tests__dehydrated_device__prepare_machine_with_dehydrated_device_of_verification_violation_user.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/matrix_sdk_crypto__session_manager__group_sessions__share_strategy__tests__dehydrated_device__should_not_share_with_unverified_dehydrated_device.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/matrix_sdk_crypto__session_manager__group_sessions__share_strategy__tests__dehydrated_device__should_share_with_verified_dehydrated_device.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/matrix_sdk_crypto__session_manager__group_sessions__share_strategy__tests__dehydrated_device__should_share_with_verified_device_of_pin_violation_user.snap

Per https://github.com/matrix-org/matrix-rust-sdk/issues/4313, we should not send outgoing messages to dehydrated devices that are not signed by the user's identity
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4313

crypto: withhold outgoing messages to unsigned dehydrated devices

---

bindings/matrix-sdk-ffi/src/sync_service.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/sync_service.rs
crates/matrix-sdk-ui/tests/integration/sync_service.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/src/test_utils/mod.rs
examples/oidc_cli/src/main.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/nse.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

There are a couple of preparation commits before we come to the meat of this PR, due to this a review commit by commit is advised.
The offline mode attempts to allow users of the UI crate to delegate the restarting of the `SyncService` to the SDK itself. While in offline mode, we're attempting to see if the server is back online using the `/_matrix/client/versions` endpoint. Once we can find the homeserver using the `/versions` endpoint we attempt to sync again.

Introduce an offline mode for the SyncService

---

crates/matrix-sdk/src/room/identity_status_changes.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/src/test_utils/mod.rs

While trying to figure out why #4596 fails, I noticed that some tests reimplement the `assert_next_with_timeout` macro using a function.
While I'm doing this I expanded the macro to make the timeout parameter optional and added some doc examples to the macro.
Additionally I noticed that one of our examples seems to contain a bug because of a misplaced `#`.
A review commit by commit makes the most sense.

Simplify some tests with the assert_next_with_timeout macro

---

Cargo.lock

See this note https://rustsec.org/advisories/RUSTSEC-2025-0004.
This patch updates OpenSSL to 0.10.70.

fix(security): Update OpenSSL

---

Cargo.toml
crates/matrix-sdk-ui/src/timeline/event_handler.rs

This patch drastically improves the performance of `TimelineEventHandler::deduplicate_local_timeline_item`.
Before this patch, `rfind_event_item` was used to iterate over all timeline items: for each item in reverse order, if it was an event timeline item, and if it was a local event timeline item, and if it was matching the event ID or transaction ID, then a duplicate was found.
The problem is the following: all items are traversed.
However, local event timeline items are always at the back of the items. Even virtual timeline items are before local event timeline items. Thus, it is not necessary to traverse all items. It is possible to stop the iteration as soon as (i) a non event timeline item is met, or (ii) a non local event timeline item is met.
This patch updates …

fix(ui): Fix performance of `TimelineEventHandler::deduplicate_local_timeline_item`

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs

Fixes #4517.
It turns out that the bugs found in that test were due to 2 causes:
- First commit: `TestRoomDataProvider` didn't use `initial_user_receipts` but returned hardcoded values.
- Second commit: Our own read receipts were ignored in `TimelineStateTransaction::load_read_receipts_for_event`, although we need to process all read receipts via `ReadReceipts::maybe_update_read_receipt` because it knows how to filter out our own read receipts were needed.

fix(ui): Do not filter out own receipts in load_read_receipts_for_event

---

crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-sqlite/src/utils.rs

- First commit: run `VACUUM` on the `SqliteStateStore`. We should have done this when we moved the media cache to `SqlitEventCacheStore`, to defragment the file and reduce its size on the filesystem. Because of that there are databases from that time that still take much more space than they need.
- Second commit: run `PRAGMA optimize` after running the eventual migrations. The [SQLite docs](https://www.sqlite.org/pragma.html#pragma_optimize) recommend to do this regularly, especially after a schema change. Doing this consistently during construction seems to be the easiest solution.
- Third commit: limit the size of the WAL file. While the DB connections of the databases are open, [the size of the WAL file can keep increasing](https://www.sqlite.org/wal.html#avoiding_excessively_large_wal …

sqlite: Optimize the DB and the files sizes

---

crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs

This patch fixes the performance of
`AllRemoteEvents::increment_all_timeline_item_index_after` and
`decrment_all_timeline_item_index_after`.
It appears that the code was previously iterating over all items. This
is a waste of time. This patch updates the code to iterate over all
items in reverse order:
- if `new_timeline_item_index` is 0, we need to shift all items anyways,
so all items must be traversed, the iterator direction doesn't matter,
- otherwise, it's unlikely we want to traverse all items: the item has
been either inserted or pushed back, so there is no need to traverse
the first items; we can also break the iteration as soon as all
timeline item index after `new_timeline_item_index` has been updated.
I'm testing this patch with the `test_lazy_back_pagination` test in …

fix(ui): Fix performance of `AllRemoteEvents::(in|de)crement_all_timeline_item_index_after`

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/left.rs

This PR adds bindings for `Room::forget` and makes sure you can also forget rooms with `Banned` state.
Signed-off-by:

feat(ffi): Add FFI bindings to `Room::forget`

---

crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room_preview.rs
crates/matrix-sdk/src/test_utils/mocks.rs

What the tin says.
We weren't trusting the local room info for rooms that weren't in joined state because for invites and knocks that might mean  displaying outdated info about the room, and left rooms would also return the same info than we had locally. 
However, this missed the `Banned` room state, and the different endpoints would just return a `M_FORBIDDEN` 403 error when trying to get info about a room the user was banned from. So the fix is to trust the local info we have about the room instead of asking the HS about it.
Signed-off-by:

fix(room_preview): Return room preview info based on local data for banned rooms

---

crates/matrix-sdk/src/event_cache/room/events.rs

This patch improves the performance of
`RoomEvents::maybe_apply_new_redaction`. This method deserialises all the events it receives, entirely. If the event is not an `m.room.redaction`, then the method returns early. Most of the time, the event is deserialised for nothing because most events aren't of kind `m.room.redaction`!
This patch first uses `Raw::get_field("type")` to detect the type of the event. If it's a `m.room.redaction`, then the event is entirely deserialised, otherwise the method returns.
When running the `test_lazy_back_pagination` from
https://github.com/matrix-org/matrix-rust-sdk/pull/4594 with 10'000 events, prior to this patch, this method takes 11% of the execution time. With this patch, this method takes 2.5%.
Call tree before this patch:
After this patch:
---
* …

fix(sdk): Improve performance of `RoomEvents::maybe_apply_new_redaction`

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/api.udl
bindings/matrix-sdk-ffi/src/error.rs
crates/matrix-sdk/src/client/mod.rs

Map Matrix client API errors to `ClientError::MatrixApi { error_code, msg }` instead of `ClientError::Generic { msg }` so we can check for special cases like access to a resource being forbidden, the account being deactivated, etc.
Signed-off-by:

refactor(ffi): Add `ClientError::MatrixApi` errors with error codes

---

crates/matrix-sdk/src/authentication/oidc/mod.rs

While running `cargo test --doc --features docsrs` with the OIDC feature enabled, I noticed that the tests in the OIDC module were failing due to outdated module resolution in the documentation examples.
This MR updates the module resolution to reflect the current structure.

fix[oidc]: fix docstring in oidc module

---

crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs

This patch improves the performance of
`ReadReceiptTimelineUpdate::apply`, which does 2 things: it calls `remove_old_receipt` and `add_new_receipt`. Both of them need a timeline item position. Until this patch, `rfind_event_by_id` was used and was the bottleneck. The improvement is twofold and is as follows.
First off, when collecting data to create `ReadReceiptTimelineUpdate`, the timeline item position can be known ahead of time by using `EventMeta::timeline_item_index`. This data is not always available though, for example if the timeline item isn't created yet. But let's try to collect these data if there are some.
Second, inside `ReadReceiptTimelineUpdate::remove_old_receipt`, we use the timeline item position collected from `EventMeta` if it exists. Otherwise, let's fallback to a …

fix(ui): Fix performance of `ReadReceiptTimelineUpdate::apply`

---

bindings/matrix-sdk-ffi/src/room_preview.rs

This was previously added to `ffi::Room`, but the problem is in the clients we'd get the room from `RoomList::full_room`, which has a 'return only if joined' rule, so you would not be able to use this API unless you used `Client::rooms`  and looked for the room in the list instead, which is not ideal. So the forget function binding needs to live somewhere a non-joined room can be retrieved, that being `RoomPreview`.
At this point I'm even wondering if the `ffi::Room::forget` function makes sense or it should be removed, because that room is supposed to be a joined one (and if we should just rename that FFI 'Room' into 'JoinedRoom', sigh...), although I think this distinction is only done at the `RoomList::full_room` function.
Signed-off-by:

feat(ffi): Add `RoomPreview::forget` action in the FFI layer

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi-macros/Cargo.toml
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-common/CHANGELOG.md
crates/matrix-sdk-common/Cargo.toml
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-indexeddb/CHANGELOG.md
crates/matrix-sdk-indexeddb/Cargo.toml
crates/matrix-sdk-qrcode/CHANGELOG.md
crates/matrix-sdk-qrcode/Cargo.toml
crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk-store-encryption/CHANGELOG.md
crates/matrix-sdk-store-encryption/Cargo.toml
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
testing/matrix-sdk-test-macros/CHANGELOG.md
testing/matrix-sdk-test-macros/Cargo.toml
testing/matrix-sdk-test/CHANGELOG.md
testing/matrix-sdk-test/Cargo.toml
xtask/src/release.rs

Another month, another release.
This will be the last release that contains the Sliding Sync Proxy ([MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575)) support.
We're also fixing one part of #4292, the testing crates are now part of the release.

Release 0.10.0

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk/CHANGELOG.md

This patch adds #4601, #4608, #4612 and #4616 in their respective `CHANGELOG.md`s.

doc(changelog): Add entries for the performance improvement patches

---

crates/matrix-sdk-ui/tests/integration/timeline/echo.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs

Removal of test helpers will continue until morale improves.

test(timeline): use the `MatrixMockServer` in a few more places

---

.deny.toml
Cargo.lock
Cargo.toml
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/src/timeline/subscriber.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
testing/matrix-sdk-test/src/sync_builder/joined_room.rs

<p align="center"><img src="https://github.com/user-attachments/assets/8a2045a3-f938-4830-9c05-36435b38ca91" width="80%" /></p>
<figcaption><p align="center">A red fox, relaxing under the snow (credits <a href="https://www.roeselienraimond.com/red_foxes/">roeselienraimond.com</a>)</p></figcaption>
</figure>
---
These patches implement lazy pagination for a live `Timeline`. The idea is that `Timeline::subscribe()` keeps returning a `Stream` but [the `Skip` higher-order stream](https://github.com/jplatte/eyeball/pull/72) is applied to skip the first items, exactly the `count` first items:
- When new items are added in the `Timeline`, they will appear in the subscriber's stream (if they are not part of the skipped items, see `Skip`'s documentation to learn more). …

feat(ui): Implement `Timeline` lazy pagination

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

This patch removes the `Clear` variant of the `RoomEventCacheUpdate` enum. This one is not needed anymore since we have `UpdateTimelineEvents` which contains updates as `Vec<VectorDiff<_>>`. `VectorDiff` _has_ a `Clear` variant. It resulted in a double clear every time.
This patch updates `RoomEventCacheInner::reset` and `RoomEventCacheInner::with_events_mut` to annotate them with a `#[must_use]`. Since they return the updates as `VectorDiff`s, they **must** be broadcasted/propagated somewhere, likely with `RoomEventCacheUpdate`. This mechanism ensures to not miss updates.
---
* Address #3280

chore(sdk): Remove `RoomEventCacheUpdate::Clear`

---

bindings/matrix-sdk-ffi/src/room_list.rs

This removes the restriction applied in the FFI layer that made only invited and knocked rooms return room previews in this function.
Signed-off-by:

fix(ffi): Align `RoomList::preview_room` with `Client::get_room_preview_*` functions.

---

bindings/matrix-sdk-ffi/src/platform.rs

They produce hundreds of logs like
```
2025-02-05T12:25:02.584637Z  INFO matrix_sdk_base::store::ambiguity_map: return=false | crates/matrix-sdk-base/src/store/ambiguity_map.rs:89 | spans: live_update_handler{room_id="!XBZZPIcqcoInXjgKdL:matrix.org" focus="live"} > is_display_name_ambiguous{display_name=DisplayName { raw: "Doug", decancered: Some("doug") } users_with_display_name={"@douge:matrix.org"}}
```
and
```
2025-02-05T12:23:21.894300Z  INFO matrix_sdk_common::store_locks: aborting the previous renew task | crates/matrix-sdk-common/src/store_locks.rs:219 | spans: root > spin_lock{max_backoff=None self.lock_key="default" self.lock_holder="io.element.elementx"} > try_lock_once{self.lock_key="default" self.lock_holder="io.element.elementx"}
```

chore(ffi): reduce the verbosity of the store locks and ambiguity map

---

.github/workflows/ci.yml
xtask/src/ci.rs

This would help find test failures specific to experimental-oidc, as well as doctests failing (which would have prevented the failures fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/4614 to happen in the first place).
---
Let me know if it is preferred to reuse an existing feature set, rather than introduce one; I don't have any strong opinion there.

ci: add a new feature set to test experimental-oidc too

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/session_verification.rs
crates/matrix-sdk-base/src/latest_event.rs

This patch expands on the existing device verification flows to add support for verifying users as well. 
It does so by:
- moving incoming request detection to the Client level so that it works for both to-device events as well as timeline ones. The client then forwards the data through the generic `process_incoming_verification_request` method
- exposing a new `request_user_verification` method next to the (renamed) `request_device_verification` one on the `SessionVerificationController`
- consolidating subscription logic within `set_ongoing_verification_request`
- overall the mecanisms are very similar which should make it easy to adopt in the final clients

feat(ffi): add support for starting and responding to user verification requests

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/date_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/echo.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/tests/shields.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/test_utils/mocks.rs
testing/matrix-sdk-test/src/event_factory.rs

Oh, and make more use of the `MatrixMockServer` and `EventFactory` btw.

refactor(timeline): simplify transition from unencrypted to encrypted

---

crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-sqlite/src/utils.rs

A room can be associated to a lot of data, depending on the number of members in the room.
So freeing space on the filesystem should be worth it in some cases.
An (extreme) example: I have a test account that is in ~60 rooms, a few of those big public rooms, including Matrix HQ. The size of the `matrix-sdk-state.sqlite3` file is 542 MB. Using this PR and leaving, then forgetting Matrix HQ brings the DB down to 255 MB.

feat(sqlite): Run VACUUM operation after removing a room 

---

crates/matrix-sdk-ui/src/timeline/controller/aggregations.rs

We encountered this warning a lot in the logs after upgrading the SDK today. This comes from https://github.com/matrix-org/matrix-rust-sdk/pull/4576.
My understanding is that this path is expected if the target event is not yet in the timeline, which can happen often when paginating backwards, so it's nothing to warn about.
cc @bnjbvr

fix(ui): Demote aggregation target not found log to TRACE level

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs

This patch removes the invariant stating that a `LinkedChunk` must start by a chunk of type items. This has never been really useful but it's now annoying to have this (with iterative loading of a `LinkedChunk` via the `EventCache`, it's now possible to get a gap as the first chunk). Let's remove this invariant.
---
* Address #3280 
* Extracted from #4632

refactor(common): `LinkedChunk` can start by a gap

---

crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

Instead of having the `RoomEvents` own the `Deduplicator` instance, we put the `Deduplicator` outside of `RoomEvents`; the flow changes from "when doing an operation on the room events, first check for duplicates and do things based on that" to "deduplicate events first, then do operations on the room events".
This is a more orthogonal design, that makes adding future changes to the `Deduplicator` easier; for instance, if deduplication became asynchroneous, that means we won't have to change every single method of `RoomEvents` to make it async, as a result.
It also means that `RoomEvents` is "dumber", in the sense that it exposes simpler primitives to the caller. The caller now has more responsibilities (must check for duplicates *before* doing any operations on the room events), but we …

refactor(event cache): extract deduplication out of `RoomEvents`

---

crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs

Right now, the replied-to details can only contain information about a room message, while we can have other timeline item contents for an item. In particular, the replied-to event could be still encrypted (UTD), and that shouldn't be considered an "unsupported kind", as in https://github.com/element-hq/element-x-ios/issues/3774. Instead, consumers can display the replied-to event was a UTD, and perform manual retries in the background later on (after a backup key has been downloaded, for instance).
Remaining tasks:
- ~~[ ] Since the code getting a `TimelineItemContent` from a Ruma event is so similar to the code used when handling an event, I'm planning to attempt to merge the two.~~
- will be a followup

feat(timeline): handle more timeline item content kinds in replied-to details

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs

This patch removes a useless indentation.
---
* Extracted from #4632

chore(sqlite): Remove a useless indentation

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs
labs/multiverse/src/main.rs

This patch updates `RoomEventCache::subscribe` to be infallible. This method wasn't able to return something else than an `Ok`. The return type has been updated from `Result<T>` to `T`.
---
* Extracted from #4632

fix: `RoomEventCache::subscribe` is now infallible

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs

This patch adds and implements the
`EventCacheStore::filter_duplicated_events` method. It is implemented on the `MemoryStore` and the `SqliteEventCacheStore`.
This method remove the unique events and return the duplicated events.
On the `MemoryStore`, it iterates over events only once.
On the `SqliteEventCacheStore`, it runs a single query (modulo the size of events to check, see
`chunk_large_query_over`).
---
* Address #3280
* Unblock #4632

feat(base): Add `EventCacheStore::filter_duplicated_events`

---

crates/matrix-sdk/src/event_cache/deduplicator.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

Based on the glorious work of #4659 and #4656, this introduces a new way to deduplicate events, whether we have enabled storage or not, using a plain old sum type :nerd_face: When storage is enabled by default for everyone, we can get rid of the `BloomFilterDeduplicator` and replace `Deduplicator` with the store-based one.
Part of #3280.

feat(event cache): deduplicate using a store when available

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-common/CHANGELOG.md
crates/matrix-sdk-common/src/lib.rs
crates/matrix-sdk-common/src/ttl_cache.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/backend/mock.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/client/caches.rs
crates/matrix-sdk/src/client/mod.rs
examples/oidc_cli/src/main.rs

This will hopefully fix #4460.

Memoize the `Oidc::account_management_url()` method

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs

Otherwise this causes a panic when repeating the events variable, when generating the SQL query below.

fix(event cache store): shortcut when there's no duplicate events to check at all

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/http_client/native.rs

As recommended by [BCP 195](https://datatracker.ietf.org/doc/bcp195/).
It think it's better if the SDK enforces best current security practices by default.
It shouldn't be a problem with rustls that only supports TLS 1.2 and 1.3, but with native-tls it depends on the implementation.

feat(sdk): Only allow TLS 1.2 or newer

---

crates/matrix-sdk/src/oidc/cross_process.rs
crates/matrix-sdk/src/oidc/mod.rs

I noticed that the crate won't build without the  `e2e-encryption` feature enabled. This does not make it build rather it is a step towards it. 
There is still https://github.com/neodyme-labs/matrix-rust-sdk/blob/oidc_e2e/crates/matrix-sdk/src/oidc/mod.rs#L319 missing.
Signed-off-by: Daniel Kilimnik daniel@neoydme.io

fix(oidc): remove unnecessary e2e-encryption imports

---

.github/workflows/ci.yml
benchmarks/Cargo.toml
benchmarks/benches/room_bench.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/media/integration_tests.rs
crates/matrix-sdk-base/src/store/integration_tests.rs

This makes the `room_bench` benchmark compile, simplifies it a bit by reusing our test helpers, and adds a CI task to compile (without running) benchmarks on CI.

ci: Fix benchmark compilation and compile them in CI

---

crates/matrix-sdk-ui/tests/integration/sync_service.rs

Might fix #4639.
I don't think there's anything else we can do.

chore(test): Increase the timeout for the sync service offline mode test

---

crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/identities/manager.rs
crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs

Add more logs for when device keys changes.
- Promotes an existing `trace!` log to debug
- Logs when a user device keys are updated (typically new signatures)
- Add a log when the current own identity verification status has changed
The new logs
```
2025-02-04T14:11:12.433085Z DEBUG matrix_sdk_crypto::identities::device: Updated a device user_id="@valere_test_reg:matrix.org" device_id="PCWFHVSKZM" keys={"curve25519:PCWFHVSKZM": Curve25519("curve25519:b3m+XIBCH+rMUcYeEcmAwm2JWH21lFPAkN3jazSVQm0"), "ed25519:PCWFHVSKZM": Ed25519("ed25519:iOt4FV1u10SQuCdInO1HwGyQCe+iSiFWKXL61Sn2TRs")} | crates/matrix-sdk-crypto/src/identities/device.rs:872 | spans: root
```
```
2025-02-04T14:11:12.433952Z DEBUG matrix_sdk_crypto::identities::manager: Updated a user identity identity=Own(OwnUserIdentityData { …
```

logging(crypto): Add more logs when identity or devices change

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
examples/oidc_cli/src/main.rs

Only the scopes necessary during login are specified in MSC2967 now.

refactor(oidc): Remove method to authorize arbitrary scope

---

crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs

`TimelineEventHandler::maybe_update_responses` was used after a message has been edited or redacted, so as to update replies to it. To find replies to a message, it would iterate over every single timeline item, find if it's an event item that's a message that's a reply, and look if the replied-to id matched the event that was redacted or edited.
This is super inefficient, because it may be doing work for nothing, if there's no such replies.
The alternative implemented in this patch is a classical memory / runtime speed tradeoff: every time we receive a new message that's a reply, we do insert it in a reverse mapping from `reply-target` to `set of replies`. Then, finding the replies to a message after it's edited/redacted becomes instant, because we can use this reverse mapping.
The …

perf(timeline): make replacing replies much faster by indexing replies

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs

This patch introduces `Chunk::lazy_previous` which is a key feature to support lazy-loading of a `LinkedChunk`. When a chunk is loaded, if it is the first, it keeps in memory whether it has a previous chunk or not. Thus, it is possible to insert new chunk in front of the `LinkedChunk`, and `Update`s will correctly continue to link chunks between them (with `NewItemsChunk` and `NewGapChunk`).
Example, imagine the following chunks: [0] <-> [1] <-> [2]. If [2] is the only one being loaded. Then its previous chunk, [1], is loaded from the store (because [2]'s previous is [1] in the store). Then [1] is replaced by [3] and [4]. We get this: [4] <-> [3] <-> [1] <-> [2]. If the `Update::New*Chunk` for [4] doesn't contain a `previous`, the store is out of sync: in the store, [4] has no previous, …

feat(common): Introduce `Chunk::lazy_previous` in the `LinkedChunk`

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/data_serde.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs

The format changed 10 months ago and since it contains the tokens, it should have been re-serialized already in that time.
Afaict EX clients do not serialize that type, the bindings have their own `Session` type for that.

refactor(oidc): Remove support for deserializing previous `UserSession` format

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/room/left.rs

Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4632 for the sake of easy review.

task(base): Update `EventCacheStore` to add `load_last_chunk` and `load_previous_chunk`

---

bindings/matrix-sdk-ffi/src/client.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4631.
Signed-off-by:

feat(ffi): add `history_visibility_override` param to the create room fn

---

benchmarks/benches/room_bench.rs
benchmarks/benches/timeline.rs

This should help with compiling the benchmarks on platforms that aren't linux.

fix(compilation): fix benchmark compilation on non-linux platforms

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/backend/mock.rs
crates/matrix-sdk/src/authentication/oidc/backend/mod.rs
crates/matrix-sdk/src/authentication/oidc/backend/server.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/authentication/qrcode/login.rs
crates/matrix-sdk/src/authentication/qrcode/mod.rs
examples/oidc_cli/src/main.rs

This is the method to get the server metadata in the latest draft of [MSC2965](https://github.com/matrix-org/matrix-spec-proposals/pull/2965).
We still keep the old behavior with `GET /auth_issuer` as fallback for now because it has wider server support.
There are some pre-main commit cleanups to simplify the main commit. This can be reviewed commit by commit.
The changes were tested with the oidc_cli example on beta.matrix.org.
Closes #4550.

refactor(oidc): Use the `GET /auth_metadata` Matrix endpoint

---

crates/matrix-sdk-sqlite/migrations/event_cache_store/005_events_index_on_event_id.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs

This patch adds an index on `events.event_id` and on `events.room_id` so that queries on this column are faster. It mostly happens in the `Deduplicator`, which runs for every backwards pagination or sync.
This patch also updates the query in `filter_duplicated_events` to sort event by their `chunk_id` and `position` so that the results are constant, it helps when testing.
---
* Follow up of #4632

feat(sqlite) Add an index on `events.event_id` and `.room_id`

---

crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/prepare_machine_with_dehydrated_device_of_verification_violation_user.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/serialize_device_based_strategy.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/should_not_share_with_unverified_dehydrated_device.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/should_share_with_verified_dehydrated_device.snap
crates/matrix-sdk-crypto/src/session_manager/group_sessions/snapshots/should_share_with_verified_device_of_pin_violation_user.snap

Most core developers don't work in windows and they are creating snapshot files that file path is too long or contains the exceptional character.
Windows doesn't allow these issues.
I am working on windows, so I am suffering by file path issue on `git pull` when this repo contains long path issues.
Will fix them here.
And from @richvdh 's proposal, will implement file path checker in github actions CI, so that developer can find long path issue on every PR.

Rename snapshots to reduce filename length

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/src/linked_chunk/lazy_loader.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This patch renames the `builder` module to `lazy_loader`. The `LinkedChunkBuilder`'s methods are now functions. The `LinkedChunkBuilder` struct is removed. Finally, `LinkedChunkBuilderError` is renamed `LazyLoaderError`.
The `LinkedChunkBuilderTest` struct is kept for the moment. It's going to be replaced soon.
Easier to review without whitespace in the diffs.
---
* Follow up of #4632

refactor(common): `builder::LinkedChunkBuilder::*` becomes `lazy_loader::*`

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs

Extracted from #4677. Some good came out of that pull request, after all.

doc(timeline): fix a broken link to all_remote_events

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs

This patch updates `Update::RemoveChunk` to emit `VectorDiff::Remove`. Until now, `RemoveChunk` was expecting the chunk to be empty, because it is how it is used so far. However, with https://github.com/matrix-org/matrix-rust-sdk/pull/4694, it can change rapidly. It's better to be robust whatever the future will look like.
---

feat(common): `Update::RemoveChunk` emits `VectorDiff::Remove`

---

crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs

As part of https://github.com/element-hq/element-meta/issues/2720 we're going to add a new fields to the `InboundGroupSession` struct.
A new constructor will be helpful to initialize the new field when we receive a room key as an `m.room_key` event.

Add a new constructor to the InboundGroupSession struct

---

crates/matrix-sdk-common/src/linked_chunk/mod.rs

This is generally a good practice, as it makes some APIs less awkward to call (in particular, callers don't have to pass `&mut None` when they're not interested in the optional value).
There are a few other instances of this in the code base, but after spending a few minutes trying to move them to `Option<&mut>`, turns out I couldn't:
- in matrix-sdk/src/sync.rs, the option is overridden at the end of the function with a new value.
- in matrix-sdk-crypto/src/identities/manager, we're actually overriding the passed `&mut Option` with a new `Option` value.
- in matrix-sdk-common/src/linked_chunk/mod.rs, the two remaining functions using `&mut Option` pass it multiple times, and strangely i can't clone a `Option<&mut T>`; I suspect the mutability makes it impossible, because it would be …

refactor: use `Option<&mut T>` instead of `&mut Option<T>`in a few places

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/src/linked_chunk/lazy_loader.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This patch adds the new `from_all_chunks` function in the
`linked_chunk::lazy_loader` module. It is only used for testing
purposes. It aims at replacing `LinkedChunkBuilderTest`.
Why? Because `from_all_chunks` uses `from_last_chunk` and
`insert_new_first_chunk`: if `from_all_chunks` is able to find all
errors that `LinkedChunkBuilderTest` finds, it's a bingo. Transitively,
it proves that `from_last_chunk` and `insert_new_first_chunk` are
correct!
The other patches replaces `LinkedChunkBuilderTest` and remove it.
---
* Follow up of #4632

chore(common): Remove `LinkedChunkBuilderTest`

---

crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/tests/integration/event_cache.rs
crates/matrix-sdk/tests/integration/widget.rs

The `.from()`, `.with_delay()` and `.limit()` functions are not very explicit about what they did, and the `with_delay` one in particular led me to think that it would introduce a delay *in the response*, while it indicated a delay was expected as part of the matched URL.
Instead, this patch proposes to prefix all matchers with `match_`, to make it clearer that… they will match the incoming query: match_from, match_delay, match_limit.
Thanks to this change, the `RoomMessagesResponseTemplate` can be renamed from `delayed` to `with_delay`, which was my original intent, before I noticed another `with_delay` with totally different semantics.

test: rename some MatrixMockServer matcher functions

---

crates/matrix-sdk-common/src/linked_chunk/as_vector.rs
crates/matrix-sdk-common/src/linked_chunk/lazy_loader.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

This implements unloading the linked chunk, so as to free memory on the one hand, and avoid some weird corner cases like #4684 on the other hand.
Unloading a linked chunk happens in two steps:
- first, load the last chunk from storage,
- then, replace the current linked chunk with that last chunk.
Then, we make use of that functionality whenever we receive a gap via sync. This resolves the situation where we start with a hot cache store, that has one old event E1; the room's state is actually [E1, E2, E3], and the last sync returns [Gap, E3]. In this case, since we don't render gaps yet in the timeline, the timeline would show [E1, E3], making it look like we missed event E2; although the next pagination would make it appear. Instead, we here unload the linked chunk to its last chunk …

feat(event cache): unload a linked chunk whenever we get a limited sync

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This patch fixes a bug in `RoomEventCache::event` since https://github.com/matrix-org/matrix-rust-sdk/pull/4632 has landed. `RoomEvents` now likely contains a partial view of the events, i.e. they are not all loaded from the store to memory.
A new `EventCacheStore::find_event` is added to look for an event in the store. `RoomEventCache::event` uses it to use the store, with a fallback to `AllEventsCache` because we can't get rid of it right now (see https://github.com/matrix-org/matrix-rust-sdk/issues/3886).

fix(sdk): `RoomEventCache::event` looks inside the store

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oidc/backend/mock.rs
crates/matrix-sdk/src/authentication/oidc/backend/mod.rs
crates/matrix-sdk/src/authentication/oidc/backend/server.rs

The first commit removes support for Pushed Authorization Requests. PAR is a small optimization that sends the parameters via a request first, and returns an ID that we used in the authorization URL instead of the parameters, so it only makes the authorization URL smaller by reducing the size of the query part. It is no mentioned in the next-gen auth MSCs and it is not supported by the oauth2 crate so let's remove it already.
The second commit removes most of the optional parameters of the authorization URL. All those parameters are specified in OpenID Connect, but the next-gen auth MSCs were downgraded to OAuth 2.0 which doesn't have those parameters.
Only the following parameters are defined in the MSCs:
- `prompt=create` is defined in …

refactor(oidc): Align `OidcAuthCodeUrlBuilder` behavior with next-gen auth MSCs

---

crates/matrix-sdk-crypto/src/gossiping/machine.rs
crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/olm/session.rs
crates/matrix-sdk-crypto/src/session_manager/sessions.rs
crates/matrix-sdk-crypto/src/types/events/mod.rs
crates/matrix-sdk-crypto/src/types/events/olm_v1.rs

This requires a bit of a hack, but I think the stronger typing and having the fields defined in a single place make this worth it.

Use the `DecryptedOlmV1Event` when encrypting to-device events

---

bindings/matrix-sdk-ffi/src/client.rs

There was a small regression introduced into the FFI layer in #4673 where an error that returned `false` was updated to return `true`. This PR fixes it.

FFI: Correctly indicate OIDC support when fetching metadata fails.

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

The important part of this refactor is that we avoid holding onto a `Paginator` instance in the `RoomEventCacheInner` data structure. Instead, we create it on the fly when we need it, and drop it after the fact.
It makes for a tidier state: we don't need to manually remember to reset the `Paginator` state in multiple places. Now, instead, we have to maintain the pagination status by ourselves (since there's no way to subscribe to a `Paginator` that's transient, remember?). This is fine, because 1) the timeline already wanted to simplified pagination status that included whether we've hit the start of the timeline or not, and 2) we couldn't reach two of the states of `PaginatorStatus` anyways, theoretically.
And even better: in the future, the timeline might have a start-of-timeline item, …

refactor(event cache): don't keep an instance of `Paginator` in `RoomEventCache`

---

crates/matrix-sdk/src/authentication/oidc/backend/mock.rs
crates/matrix-sdk/src/authentication/oidc/cross_process.rs
crates/matrix-sdk/src/authentication/oidc/qrcode/login.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/test_utils/client.rs
crates/matrix-sdk/src/test_utils/mocks.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
crates/matrix-sdk/tests/integration/encryption/cross_signing.rs

As discussed in https://github.com/matrix-org/matrix-rust-sdk/pull/4687#discussion_r1967556139, we want to get rid of the `OidcBackend` trait to mock a real authorization server instead.
This implements an `OauthMockServer` to handle the OAuth 2.0-related endpoints and uses it as much as possible.
We keep the mock backend for now because mocking the server would require generating ID tokens on the fly (which involves encryption with private keys). Since ID tokens are only part of OpenID Connect, and not OAuth 2.0, we will remove support for them, so it doesn't seem worth it to add temporary code for this. We can remove support for them easily and get rid of the backend trait when this and #4699 are merged.

test(oidc): Use MatrixMockServer and MockClientBuilder where possible

---

xtask/src/ci.rs

There is one test that I know of :stuck_out_tongue:.

test(sdk): Run integration tests for experimental-oidc feature too

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

solves this https://github.com/matrix-org/matrix-rust-sdk/issues/4681
- add room report_room api from https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3roomsroomidreport
- expose report_room on room ffi
Signed-off-by: @hanadi92 <hanadi.tamimi@gmail.com>

feat(sdk&ffi): report room api

---

crates/matrix-sdk/src/event_cache/mod.rs

Wish we had a way to detect those.

chore(event cache): remove unused errors

---

crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

If during back-pagination, we lazy-load a chunk from storage and realize there's no previous chunk, we might think we've reached the start of the timeline and that we're done. This is not true, if this was the first default chunk, and we never waited long enough to get the initial gap from sync. This patch fixes that, and includes a regression test showing the error.
Part of #3280.

fix(event cache): wait for the initial previous-batch token, when storage's enabled

---

crates/matrix-sdk/src/event_cache/room/mod.rs

This patch helps to trace updates that are sent from the event cache to its store. It is central to sync or pagination.

chore(sdk): Increase log level and log all updates

---

crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs

Part of https://github.com/element-hq/element-meta/issues/2697
In response to a [comment on #4644](https://github.com/matrix-org/matrix-rust-sdk/pull/4644/files#r1963599148) - avoid spawning a detached async task every time we have some things to decrypt because some Megolm sessions updated.
Instead, we create one async task and hold it inside a new struct called `RetryDecryptionTask`. This struct holds one end of channel, and sends retry requests to the async task, which stops when the channel is closed, which will happen when the `RetryDecryptionTask` struct is dropped.
So we keep the feature that retrying decryption does not block the main processing, but we lose the spawning of lots of async tasks that are not kept track of.
As written, the task is not cancellable, but this could be …

Retry decryption from a long-lived async task, instead of lots of detached ones

---

crates/matrix-sdk/src/http_client/native.rs

`http::Request` implements `Clone` since http 1.0.0.

refactor(sdk): Remove `clone_request` method

---

crates/matrix-sdk-common/src/linked_chunk/lazy_loader.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/updates.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

I wanted to look at what it'd take to implement the `TODO`s about clearing, and I think I got them right, in the first commit; the only thing to pay attention to was the `last_index_per_reader` that needed an update when clearing updates.
But this wasn't sufficient to actually get rid of the spurious updates I've introduced in a previous test, because we're _extending the previous updates with the ones caused by the shrink/reset_. Instead, I've tried passing the updates diff vector as a `&mut` parameter to reset/shrink etc., but it makes the APIs a bit uglier, but eventually it behaves as I expected. What do you think @Hywan?

feat(event cache): leaner updates when clearing/shrinking to the last chunk

---

.github/workflows/detect-long-path.yml

Will implement file path checker in github actions CI, so that developer can find long path issue on every PR.
This proposal was from @richvdh .
This PR is a sequel to https://github.com/matrix-org/matrix-rust-sdk/pull/4625.

Implement CI to detect long path in pushed commit

---

Cargo.toml
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/event_cache/store/media/media_retention_policy.rs
crates/matrix-sdk-base/src/event_cache/store/media/media_service.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/CHANGELOG.md

What it says on the tin.
Part of #3280.

feat(ffi): allow clearing all the non-critical caches + set a media retention policy

---

crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

Repeating the logic of the fix here: before the patch, when receiving a partially overlapping backpagination result, we would:
1. keep the duplicated events in their locations
2. replace the gap with only the non-duplicated events
This leads to incorrect orderings. Consider the following example:
- sync returns [D, E, F]
- then sync returns [] with a previous batch token PB1, so the internal linked chunk state is [D, E, F, PB1].
- back-paginating with PB1 may return [A, B, C, D, E, F], so we replace PB1 with those events.
- since DEF were duplicated, we replace PB1 with ABC
- we end up with [DEFABC], which is incorrect :exploding_head: 
The solution is thus to remove the duplicates (in-memory or from the store), and reinsert them in their rightful locations. Only one test's (the one for …

fix(timeline): deduplicate events when they're received from a back-pagination too

---

Cargo.toml

I have to disable LTO every time I'm building any final binary using the SDK, because otherwise, the builds can take easily more than 10 minutes to complete, killing iteration times, and making it almost impractical to use the programs (benchmarks, or multiverse).
I think it should be the decision of the final embedder to enable or disable LTO, and that for the purpose of our own binaries hosted in the SDK repository, we don't need the absolute best performance (or, for the sake of benchmarking, we can tweak the profiling profile).

chore: disable LTO on release builds

---

crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

This is the last known task required after the event cache lazy-loading feature.
This is unblocked by https://github.com/matrix-org/matrix-rust-sdk/pull/4708.
`maybe_apply_new_redaction` was looking for events only from `RoomEvents`, so only in-memory. And the redaction was only happening in-memory too. With this patch, `maybe_apply_new_redaction` handles in memory and in store.
This pull request should be reviewed patch by patch for the sake of clarity.
A clean up in the `Deduplicator` is possible by using the new `EventLocation` enum, but it's not part of this set of patches.
---

fix(sdk): `maybe_apply_new_redaction` updates in-store events

---

benchmarks/Cargo.toml
benchmarks/benches/linked_chunk.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/006_events.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/event_cache/deduplicator.rs

This patch adds a benchmark for the `LinkedChunk` with the following matrix:
* Handling 10, 100, 1_000, 10_000 and 100_000 events,
* With no store, with the `MemoryStore`, with the `SqliteEventCacheStore`.
Before this patch, the case with no store and `MemoryStore` were not a blocker. I was surprisingly delighted to see that the `LinkedChunk` is able to handle a throughput of 9.3 millions events per second. With the `MemoryStore`, it drops at 4.5 millions events per second, not bad for a test-tailored store. However, for `SqliteEventCacheStore`, the story was clearly different… **7_300 events per second**, only. And it got worst with more events.
I dug into this for 2 days, and found several things.
In the future we can improve the benchmark to test more operations, but I wanted to solve …

fix(sqlite): `SqliteEventCacheStore` is 35 times faster

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee.rs

<del>This can be used to ignore verification requests in this sliding sync instance, preventing issues found where several sliding sync instances with the same client process events simultaneously and re-process the same verification request events during their initial syncs.</del> We went with a solution based on `BaseClient` instead.
This is a blocker for user verification on Android clients, since both the normal sync and the one initiated to get the event for a notification will process the same verification request events and end up with conflicts, making the verification flow fail most of the time.
Signed-off-by:

fix(client): Add `handle_verification_events` to `BaseClient`

---

bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/authentication/oidc/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oidc/error.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/qrcode/login.rs
crates/matrix-sdk/src/authentication/oidc/registrations.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/test_utils/client.rs
examples/oidc_cli/src/main.rs

This makes use of the oauth2 crate for the authorization code grant and the refresh token grant.
There is still the token revocation that can use oauth2, but it requires changes in the HTTP client so it will be done separately. And the remaining parts (account management URL, fallback discovery, registration) will need to be included in the SDK to get rid of mas-oidc-client.

refactor(oidc): Start replacing mas-oidc-client with oauth2

---

labs/multiverse/src/main.rs

The `SyncService::stop()` method guarantees that the sync service will be stopped after it has completed so there's no need to wait for state changes.
The state change might not even come, if you pressed `S` to stop the sync service manually.

fix(multiverse): Don't wait for sync service state changes when shutting down

---

Cargo.lock
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/authentication/oidc/cross_process.rs
crates/matrix-sdk/src/authentication/oidc/error.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs

With a dirty hack to pass tests.

refactor(oidc): Use oauth2 for token revocation

---

crates/matrix-sdk/src/authentication/oidc/cross_process.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/client/futures.rs
crates/matrix-sdk/src/test_utils/client.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
crates/matrix-sdk/tests/integration/refresh_token.rs

This was forgotten in #4761. Since we do not use mas-oidc-client anymore, the error to match has changed.
The second commit adds tests that would have catched the regression.

fix(oidc): Match the proper error type for invalid refresh token

---

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

Adds a little utility method. I didn't add tests because the nearby similar methods don't have them, but happy to add them if we want.
See https://github.com/matrix-org/matrix-rust-sdk/pull/4644#discussion_r1984968706 for a context where this is useful.

feat(timeline): Provide is_utd on EventTimelineItem

---

benchmarks/benches/store_bench.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/encryption_sync_service.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/matrix/mod.rs
crates/matrix-sdk/src/authentication/mod.rs
crates/matrix-sdk/src/authentication/oidc/cross_process.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/client.rs
crates/matrix-sdk/src/test_utils/mod.rs
crates/matrix-sdk/tests/integration/client.rs
crates/matrix-sdk/tests/integration/encryption/backups.rs
crates/matrix-sdk/tests/integration/encryption/cross_signing.rs
crates/matrix-sdk/tests/integration/encryption/recovery.rs
crates/matrix-sdk/tests/integration/encryption/secret_storage.rs
crates/matrix-sdk/tests/integration/encryption/verification.rs
crates/matrix-sdk/tests/integration/matrix_auth.rs
crates/matrix-sdk/tests/integration/media.rs
crates/matrix-sdk/tests/integration/refresh_token.rs
examples/secret_storage/src/main.rs

Since both authentication APIs now have identical session tokens type, we can merge them an put the data in `AuthCtx`.
I decided to not reuse a `SharedObservable` because the `session_tokens_stream` behavior can be done by subscribing to `Client::subscribe_to_session_changes()` and then calling `Client::session_tokens()`.

refactor(sdk): Merge session tokens

---

crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
crates/matrix-sdk/tests/integration/refresh_token.rs

Generalizes the behavior introduced in #4767 for the `/whoami` mock endpoint.
It requires creators of `MockEndpoint`s to use the built-in methods instead of custom methods on `MockBuilder` and sadly there is no way to enforce this programmatically.

test(sdk): Allow any MockEndpoint to override the expected access token

---

crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

It's unusual to have the method on the parent type when the field type could also hold the method. In fact, this was the only bool getter inspecting the timeline's content, so let's move the method next to as its siblings, for consistency, and let's spell it out fully for clarity.

refactor(timeline): move `is_utd()` to `TimelineItemContent`

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/room_preview.rs
crates/matrix-sdk/src/room_preview.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room_preview.rs

This PR introduces a fallback mechanism for dealing with invites when the room summary API [MSC3266](https://github.com/matrix-org/matrix-spec-proposals/pull/3266) isn't enabled on the homeserver. 
It does so by trying to use whatever data the client has cached about the room, and even though it won't contain a lot of information, it will still provide an usable instance which can be used to accept/decline the invite and partially populate the join room screen (in EX).
It also deals away with the now unnecessary `invited_room` and `inviter` and expose a new client one for fetching arbitrary rooms based on their identifier.

Invites room summary fallback

---

bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oidc/error.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/registrations.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/test_utils/client.rs

This can be reviewed commit by commit:
1. Don't require the client metadata as an argument: we already hold it in `OidcRegistrations`, so we can lazily clone it when needed.
2. Require the redirect URI as an argument: the previous behavior, which used the first redirect URI in the client metadata doesn't fit every client. For example clients that need to bind a port on localhost need to provide a custom redirect URI each time. So we ask for the redirect URI, and keep the previous behavior only for the bindings.
3. (bonus) Refactor the way that types are constructed from `OidcConfiguration` in the FFI crate by moving them to methods on the type. This makes the login code easier to read in my opinion, and avoids the necessity to specify the type in some cases.

refactor(oidc): Improvements to url_for_oidc

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/observable_map.rs

This patch reduces the memory usage of the broadcast channel used by
`BaseClient::room_info_notable_update_sender`. So far, its size was
`u16::MAX`. Considering `RoomInfoNotableUpdate` is 24 bytes, the channel
was allocating 1.5Mb of memory, which is way too much. It is creating
problems on systems where the process has limited resources, like the
[Notification Service Extension][NSE] on iOS.
For a regular users with 200 rooms, the memory usage becomes 24Kb, which
is 65'536 times less.
[NSE]: https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension
---
* Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/4013

feat(base): Reduce memory usage of `BaseClient::room_info_notable_update_sender` by 65'536 times for a regular user

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/events.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

See the commit messages for more explanations. This makes the event cache much more stable for `multiverse`, by addressing three issues:
- if a gap was the only chunk loaded in a linked chunk, don't try to remove it after resolving it to an empty set of events
- #4785: enable the foreign keys pragma for each sqlite connection, to make sure cascading works
- #4784 (perf): now we'll only wake the subscribers if the ignored user list has changed, when compared to the previous version we knew about
Bugs found with `multiverse`.
Fixes #4785.
Fixes #4784.
Part of #3280.

fix(event cache): don't remove a gap when it's the only chunk in memory

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room_info.rs

This patch adds the `EncryptionState` onto the new `RoomInfo::encryption_state` field.

feat(ffi): Add `RoomInfo::encryption_state`

---

.deny.toml
Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/Cargo.toml
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/encryption.rs
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/platform.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_directory_search.rs
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/session_verification.rs
bindings/matrix-sdk-ffi/src/sync_service.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/utils.rs
bindings/matrix-sdk-ffi/src/widget.rs

Creating many threads may use a bit of memory: on a machine with N
devices, exactly N*2 MB of memory may be consumed.
That might be a lot for a NSE process on iOS, which can only have up to
16 MB of RAM allocated for it. For this case, we introduce a new FFI
method `setup_lightweight_tokio_runtime` which will spawn at most 4
worker threads and 2 blocking threads. This should be sufficient for most
use cases.
---
* Address https://github.com/element-hq/element-x-ios/issues/3785

feat(ffi): new way to provide a lightweight tokio runtime for memory-constrained apps

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_list.rs

This patch removes the last `block_on` calls in `matrix-sdk-ffi`.
By reducing the number of blocking contexts, we are reducing the number of blocking threads, which is good performance wide. See https://github.com/matrix-org/matrix-rust-sdk/pull/4766 and https://github.com/matrix-org/matrix-rust-sdk/pull/4786.
---
* Address https://github.com/element-hq/element-x-ios/issues/3785

chore(ffi): Remove useless `block_on`

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/platform.rs

And make it take a boolean indicating whether we want to set up a lightweight tokio runtime or not, instead of having `setup_lightweight_tokio_runtime` as a public function + another function, both of which would have to be called anyways.
cc @stefanceriu @jmartinesp

feat!(ffi): rename `setup_tracing` into `init_platform`

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs

Restores recently removed but needed OIDC prompts.
Signed-off-by:

fix(ffi): Restore some needed OIDC prompts in the FFI layer

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/tests/integration/room_preview.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs

<p align="center"><img src="https://github.com/user-attachments/assets/dbd5bffc-181b-4a7d-8e22-8bffc591056a" width="60%" /></p>
<figcaption><p align="center"><a href="https://commons.wikimedia.org/wiki/File:John_Collier_-_Priestess_of_Delphi_-_Google_Art_Project.jpg">Priestess of Delphi (John Collier)</a></p></figcaption>
</figure>
---
So, we have a problem with encryption state.
First off, a patch has clarified the different states for encryption, see https://github.com/matrix-org/matrix-rust-sdk/pull/4777.
Second, the problem is pretty basic to understand:
- the _presence_ of a `m.room.encryption` state event for a room in a sync response means the encryption state for this room is `Encrypted`,
- the _absence_ of a `m.room.encryption` state event means two …

feat: Always know when a room is encrypted or not (with sliding sync)

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4794/.
These patches update the `EventsOrigin` and `RemoteEventOrigin` to `Cache` when necessary. Better to review patch by patch.

fix: Adjust the event origins in the `Timeline` and the `EventCache`

---

labs/multiverse/src/main.rs

Allow use of a server url (eg `http://localhost:8008`), enabling connection to a local server rather than one which supports well-known, TLS, and the rest.

multiverse: support passing a server URL

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/observable_map.rs

When `BaseClient` is created, the rooms aren't loaded yet. Then, calculating the size of the channel for `RoomInfoNotableUpdate` is useless, as it will always be zero, and we will fallback to 500 every time. By the way, 500 is a nice default. This patch uses this value as the only channel's size.

fix(base): Do not define the `RoomInfoNotableUpdate`'s channel based on number of rooms

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk/src/event_cache/mod.rs

Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/4794.
This patch rewrites the `TimelineBuilder::build()` method by extracting all the spawned task code block into their own function. The resulting code is simpler to read, and we can reference each task by its function name. Moreover, each task is isolated, it's a bit easier to reason about.

chore(ui): Extract `TimelineBuilder` tasks into their own functions

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/to_device.rs
crates/matrix-sdk-ui/tests/integration/timeline/decryption.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs

The fix is 3 LOC, the test is 345 LOC, oh yeah.
So, currently, it is possible to store an `TimelineEventKind::UnableToDecrypt` (UTD) event inside the event cache. When received by the `Timeline`, prior this patch, such event wasn't decrypted. The fix is actually quite small: everything that comes from the cache (`EventsOrigin::Cache`) and that contains a UTD, triggers a redecryption. Hoping that the keys are in the `OlmMachine` of course.
This patch tests two situations where it can happen: when the UTD is part of the initial items, and when the UTD is part of a pagination. The former was already working, but not tested via the event cache as far as I know, and the latter wasn't tested at all (because it wasn't implemented).
---
* Fix …

fix(ui): Decrypt `TimelineEventKind::UnableToDecrypt` coming from the event cache

---

Cargo.lock
bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/authentication/oidc/account_management_url.rs
crates/matrix-sdk/src/authentication/oidc/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oidc/cross_process.rs
crates/matrix-sdk/src/authentication/oidc/error.rs
crates/matrix-sdk/src/authentication/oidc/http_client.rs
crates/matrix-sdk/src/authentication/oidc/mod.rs
crates/matrix-sdk/src/authentication/oidc/oidc_discovery.rs
crates/matrix-sdk/src/authentication/oidc/qrcode/login.rs
crates/matrix-sdk/src/authentication/oidc/registration.rs
crates/matrix-sdk/src/authentication/oidc/registrations.rs
crates/matrix-sdk/src/authentication/oidc/tests.rs
crates/matrix-sdk/src/client/caches.rs
crates/matrix-sdk/src/http_client/mod.rs
crates/matrix-sdk/src/test_utils/client.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
examples/oidc_cli/src/main.rs
examples/qr-login/src/main.rs

To get rid of mas-oidc-client, we need to import a few methods and types, but nothing very complex.
I decided to create a more opinionated `ClientMetadata` type so that it is easy to construct and we don't need to validate it.

refactor(oidc): Remove dependency on mas-oidc-client 

---

xtask/src/release.rs

Because yes, some weeks, we are very productive!
This patch adds `--limit 100` to `gh pr list` so that we are sure to not miss pull requests if there are many.

fix(xtask): Add `--limit 100` to `gh pr list`

---

crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-crypto/src/store/snapshots/matrix_sdk_crypto__store__tests__build_room_key_bundle.snap
crates/matrix-sdk-crypto/src/types/events/forwarded_room_key.rs
crates/matrix-sdk-crypto/src/types/events/room_key.rs
crates/matrix-sdk-crypto/src/types/mod.rs
crates/matrix-sdk-crypto/src/types/room_history.rs
crates/matrix-sdk-crypto/src/types/snapshots/matrix_sdk_crypto__types__room_history__tests__historic_room_key_debug.snap

Add a method to CryptoStore which will construct a key bundle, ready for encrypting and sharing with invited users.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4504.

crypto: support for building key bundles

---

Cargo.lock
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/authentication/matrix/login_builder.rs
crates/matrix-sdk/src/utils/local_server.rs
crates/matrix-sdk/src/utils/mod.rs
examples/oidc_cli/Cargo.toml
examples/oidc_cli/src/main.rs

This exposes the server builder code that was used behind the `sso-login` feature so that it can be reused in other places, like during OAuth 2.0 login. It's called `LocalServerBuilder` and is behind the `local-server` feature.
I added types around the channels to make the API easier to use and harder to misuse (if the shutdown signal is not sent, the server will keep running). They are inspired by tokio's `JoinHandle` and `AbortHandle`.

feat(sdk): Expose a local server builder

---

crates/matrix-sdk/src/event_cache/room/mod.rs

doc(sdk): Precise in which context a variable can or cannot be used

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/src/linked_chunk/lazy_loader.rs

This patch adds a `debug_assert_eq` to ensure the new first chunk is the one that matches the `lazy_previous` of the current first chunk.
---

test(common): Ensure inserting a new first chunk is as expected

---

crates/matrix-sdk/src/event_cache/room/mod.rs

This patch updates `RoomEventCacheState::remove_events` to check whether
the set of events are not empty before removing them. When removing
`in_memory_events`, it avoids taking a write lock on the `RoomEvents`
for nothing for example.

refactor(sdk): `RoomEventCacheState::remove_events` checks if events to remove aren't empty

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk/src/event_cache/pagination.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

And add more logs to the event cache computation of the `reached_start` value.
Might be a reason why we ran into https://github.com/element-hq/element-x-ios/issues/3768: spawning the task can be deferred a bit, so EXI doesn't receive the initial value until much later, causing it to be confused as its initial value was `timelineEndReached` (it's been changed [here](https://github.com/element-hq/element-x-ios/pull/3924), which should also be sufficient to fix the issue).
Part of #3280.

fix(ffi): propagate the back-pagination status immediately after a subscriber asked for it

---

bindings/matrix-sdk-ffi/src/widget.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/widget/mod.rs
crates/matrix-sdk/src/widget/settings/element_call.rs
crates/matrix-sdk/src/widget/settings/mod.rs

Fixes: #4793
The was a previous PR https://github.com/matrix-org/matrix-rust-sdk/pull/4802 which attempted to implement this, but missed some backwards compatibility needs.
This updated PR has the original commit and then additional commits to add the compatibility (along with tests for the new intent param generally).
Signed-off-by:

feat(widgets, element-call) Update the widget url generation

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oauth/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oauth/cross_process.rs
crates/matrix-sdk/src/authentication/oauth/error.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
examples/oidc_cli/src/main.rs

This can be reviewed commit by commit:
1. Merge `finish_authorization()` and `finish_login()`: now the user only needs to call `finish_login()`, since currently the only way to use the authorization code flow is for logging in it makes more sense.
2. Allow to log into the same session several times: useful for soft logouts, we just check that we are indeed logged into the same session.
3. Get rid of `OAuthError::MissingDeviceId`: since we are the ones providing the device ID to the server, there is clearly a way to work around the ID missing in the response.

refactor(oauth): Simplify behavior to finish login

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/platform.rs
bindings/matrix-sdk-ffi/src/tracing.rs

This is a new convenient way to enable the TRACE log levels for multiple targets at the same time, when they relate to the same feature. For instance, there's a log pack for the event cache, that will enable the trace level for `matrix_sdk::event_cache`, `matrix_sdk_base::event_cache` and `matrix_sdk_sqlite::event_cache_store` at the same time.
I haven't made it possible to configure the log *level* (instead of TRACE) for those targets, because I think we won't need it; the only interesting case is debugging purposes, which usually requires trace logs.
Also, log the env filter string, so we know when looking at rageshakes what logs are enabled.

feat(ffi): trace log bundles + log the log levels

---

bindings/matrix-sdk-ffi/src/authentication.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oauth/error.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/registration_store.rs
crates/matrix-sdk/src/authentication/oauth/registrations.rs
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/test_utils/client.rs
examples/oidc_cli/src/main.rs

We rename the types to use the same prefix as the other types in the OAuth 2.0 API, and we use the
same suffix as other data-persisting APIs for consistency. It also avoids to have two modules with very similar names, the only difference being a trailing `s`.
We also refactor the error types to have more precise variants, we don't ignore errors when reading from the file, and we make the methods async because they perform blocking I/O.

refactor(oauth): Rename `OidcRegistrations` to `OAuthRegistrationStore` and other improvements

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oauth/auth_code_builder.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/qrcode/login.rs
crates/matrix-sdk/src/authentication/oauth/registration.rs
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/test_utils/mocks/oauth.rs
examples/oidc_cli/src/main.rs
examples/qr-login/src/main.rs

This creates a `ClientRegistrationMethod` enum and use it for `OAuth::login` and `OAuth::login_with_qr_code`, allowing notable to use the `OAuthRegistrationStore` every time.
We can get rid of `url_for_oidc` since everything can be done with `OAuth::login` now, and we also merge `OAuth::finish_login` and `OAuth::login_with_oidc_callback()` to use the simplest API.
Finally there are some optimizations to reduce the number of requests by reusing the `AuthorizationServerMetadata`.

refactor(oauth): Allow to use any registration method with any login function

---

Cargo.lock
crates/matrix-sdk/src/authentication/oauth/mod.rs
examples/oauth_cli/Cargo.toml
examples/oauth_cli/src/main.rs
examples/qr-login/src/main.rs

To mention OAuth 2.0 instead of OpenID Connect.
Also use `OAuthRegistrationStore` in the oauth_cli example, since it's probably the recommended way to manage registrations.

refactor(examples): Update OAuth examples

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs

`send_reply` is geared towards clients that don't render threads themselves. It sends a reply and optionally forwards it onto any existing thread.
This PR adds `send_thread_reply` for clients that do render threads themselves. This sends a message onto a thread, regardless of whether a thread existed before, and includes the fallback for non-threaded clients only if the message is not itself a reply on the thread.

feat(timeline): add functions for sending messages in threads

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/edit.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/common.rs

Small refactoring which should help with https://github.com/matrix-org/matrix-rust-sdk/issues/4835.
Also introduces a new way to retrieve an event from the event cache, or if it's missing, from the network.

refactor!(timeline): simplify getting the `RepliedToInfo` + introduce `Room::load_or_fetch_event()`

---

Cargo.lock
crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/lib.rs
crates/matrix-sdk-sqlite/src/state_store.rs

This patch adds a new `StoreOpenConfig` type to configure the store when opening it and when creating the pool of connections to SQLite via `deadpool_sqlite`.
This patch also adds a new `open_with_config` constructor on all stores, namely `SqliteCryptoStore`, `SqliteEventCacheStore` and `SqliteStateStore`.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/4801

feat(sqlite): Add `StoreOpenConfig` and `open_with_config` for all stores

---

bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_directory_search.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs

Same spirit as #4818; doing work after the `async move` "moves" the code inside the future, and it will be executed only when a tokio runtime is available, instead of doing it right away. We can improve and do it right away in a few cases:
- when getting the initial timeline items
- when looking at the room directory search results
I've audited all the `spawn`s at the FFI layer, so we should be in a good shape now.

fix(ffi): propagate initial values before the future is picked by a runtime

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/date_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/item.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/src/timeline/virtual_item.rs
crates/matrix-sdk-ui/tests/integration/timeline/decryption.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
labs/multiverse/src/main.rs

Might be better than letting the apps figure out whether they need to put one or not.
The next step would be to add a virtuel item for gaps as well, `Gap { loading: bool }`:
1. this would pave the way for inserting gaps at random positions in the timeline,
2. when the timeline is back-paginating, we'd have a gap with `loading: true`
3. when the timeline is idle and we suspect there *might* be an history we haven't loaded, we'd have a gap with `loading: false`. The next call to `Timeline::paginate_backwards()` would resolve it into a `TimelineStart` or another `Gap { loading: false }`.
Part of #4821.

feat(timeline): add a virtual start of timeline item

---

benchmarks/benches/room_bench.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/test_utils.rs
crates/matrix-sdk/src/client/builder/mod.rs

This is a small set of patches that improve the documentation of `BaseClient` but also renames the `with_store_config` constructor to `new`:
1. there is no alternative constructor, it's the only one,
2. the `with_` prefix is usually reserved to (i) builders or (ii) alternative constructors,
3. I believe it clarifies the code.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/4801

refactor(client): Improve documentation and rename `BaseClient::with_store_config` to `new`

---

crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/machine/tests/olm_encryption.rs
crates/matrix-sdk-crypto/src/olm/mod.rs

If we have a device whose Curve25519 key we don't know, then self-evidently we can't have any active Olm sessions with that device. Currently, we return an `EventError::MissingSenderKey` in this case, but (a) the definition of that error doesn't match this situation, and (b) it complicates handling in methods that call `DeviceData::encrypt` (currently only `DeviceData::maybe_encrypt_room_key`, but I want to add a second).
Other than `DeviceData::encrypt`, the only place where `get_most_recent_session` is called is `mark_device_as_wedged`. In that case, we have just looked up the device by its Curve25519 key, so we know it must have one.
We can therefore be reasonably certain that this change is a no-op.

crypto: `get_most_recent_session`: return `None` for unknown device

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/sync.rs
crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/src/sliding_sync/cache.rs
crates/matrix-sdk/src/sliding_sync/list/builder.rs
testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs

This set of patches rename the `Store` struture to `BaseStateStore` (`StateStore` was already taken by `traits::StateStore`, let's avoid confusions). It also renames `BaseClient::store()` and `Client::store()` to `state_store()` for the sake of consistency.
---
* Part of the https://github.com/matrix-org/matrix-rust-sdk/issues/4801 journey

refactor(base): `Store` is renamed `BaseStateStore`, and `store()` methods are renamed `state_store()`.

---

crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/lib.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-sqlite/src/utils.rs

This patch updates `StoreOpenConfig` to hold a new type: `RuntimeConfig`.
This `RuntimeConfig` type is passed to a new `SqliteAsyncConnExt`
method, named `apply_runtime_config`. Depending on the values passed
here, the `optimize`, `cache_size` (new!) and `journal_size_limit`
methods will be called automatically.
The goal of this type is to automate a flow we keep repeating in
all the stores. This is error-prone. This type brings uniformity and
consistency.
This patch also makes all `open_with_pool` methods on the stores private
(they were public before):
1. they were never used as far as I know because getting a `SqlitePool`
isn't possible since the `pool` attribute is private…
2. it's better to keep control of this flow.
---
* Address …

feat(sqlite): Introduce `RuntimeConfig` which includes `cache_size`

---

bindings/matrix-sdk-ffi/src/timeline/content.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/date_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/msg_like.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs
labs/multiverse/src/main.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This patch moves `RedactedMessage` and `UnableToDecrypt` to the newly introduced `TimelineItemContent::MsgLike` variant to bring consistency with Ruma and have them provide aggregations if necessary (e.g. UTD on a thread).

chore: move `RedactedMessage` and `UnableToDecrypt` to `MsgLike`

---

crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/encryption/cross_signing.rs

Seems that we don't handle an error here correctly which ends up creating an infinite loop.
Opening as a draft since we need a test.

fix(encryption): Return the uiaa error if we have one in the identity reset loop

---

benchmarks/benches/room_bench.rs
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/test_utils.rs
crates/matrix-sdk/src/authentication/matrix/mod.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/qrcode/login.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/tests/integration/matrix_auth.rs
crates/matrix-sdk/tests/integration/refresh_token.rs

This set of patches is twofold:
1. it renames `set_session_meta` to `set_or_reload_session` to clarify that the state _can be reloaded_, which is not obvious for a setter,
2. a new `Store::set_or_reload_session_from_other` method is added, to derive a state store from another one.
Finally, this patch adds missing unit tests and adds one for the `…from_other` method.
See https://github.com/matrix-org/matrix-rust-sdk/pull/4850#issuecomment-2761547063 to see the next step we went for: `BaseClient::activate` and `BaseStateStore::set_session_meta` + `::load_rooms` + `::load_sync_token` + `::derive_from_other`.
This refactoring is necessary regarding https://github.com/matrix-org/matrix-rust-sdk/issues/4801 because I'm about to add another data in `Store`. Having this …

refactor(base): Introduce `BaseClient::activate` and split `BaseStateStore::set_session_meta` to 3 methods

---

.deny.toml

Since we don't depend on mas anymore, we don't depend on RSA either.
Let's remove the exception, lest we reintroduce the dependency and security issue.

chore: Remove the RSA security advisory from our deny config

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
testing/matrix-sdk-integration-testing/README.md
testing/matrix-sdk-integration-testing/assets/docker-compose.yml

Followup on https://github.com/matrix-org/matrix-rust-sdk/pull/3983: now that we don't have a sliding sync proxy, we don't need a postgres container.

integration-test: Remove postgres container

---

crates/matrix-sdk/src/encryption/mod.rs

Now that OAuth isn't behind a feature flag a bunch of things can be simplified.
This was also tested with a  real server.

refactor(encryption): Simplify the parsing of OAuthCrossSigningResetInfo

---

benchmarks/benches/room_bench.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-base/src/test_utils.rs
crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/authentication/matrix/mod.rs
crates/matrix-sdk/src/authentication/oauth/cross_process.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/qrcode/login.rs
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/client.rs
crates/matrix-sdk/src/test_utils/mod.rs
crates/matrix-sdk/tests/integration/client.rs
crates/matrix-sdk/tests/integration/media.rs
crates/matrix-sdk/tests/integration/refresh_token.rs

This set of patches introduces the `RoomLoadSettings` enum. It is helpful to load either all rooms or one room when activating a `BaseClient`, i.e. when a session is initialized or restored.
It addresses a broader problem where, for large accounts with large caches, creating a `BaseClient` takes many resources. In a resource constrained context, like a push notification process, it can eat all resources up to the point the process is killed (then notifications can be missed).
The idea is then to force the `BaseClient` to load a single room.
It's better to review this PR patch by patch. Don't be fooled by the number of new lines: they are mostly tests.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/4801
* Address https://github.com/element-hq/customer-success/issues/457

feat(base): Expose `RoomLoadSettings` when loading rooms in `BaseStateStore`

---

bindings/matrix-sdk-ffi/src/client.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4867.
This patch adds `Client::restore_session_with` along with the
`RoomLoadSettings` enum.
---
* ~Build on top of https://github.com/matrix-org/matrix-rust-sdk/pull/4867. Only the last 2 commits are new.~
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/4801
* Address https://github.com/element-hq/customer-success/issues/457

feat(ffi): Add `Client::restore_session_with` and `RoomLoadSettings`

---

testing/matrix-sdk-integration-testing/src/tests/timeline.rs

Fixes #4871 (hopefully).
I can't reproduce the test flake in `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure` locally, but I hope that by syncing after alice cross-signs, then bob has time for the information to arrive before fetching alice's identity.

test(timeline): In redecryption tests, sync after other user cross-signs

---

benchmarks/benches/room_bench.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/mod.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/007_event_chunks.sql
crates/matrix-sdk-sqlite/migrations/event_cache_store/007_events_chunks.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/common.rs

This rejiggers the event cache's store schema so that events can be saved independently of their position in a linked chunk. Also, it makes it possible to extract an event's relation metadata, so we can get rid of the `AllEventsCache` along the way.
Fixes #4841.
Fixes #3886.
Part of #3280.
Remaining steps:
Kind of depending on https://github.com/ruma/ruma/pull/2052, although we don't really have to.

feat(event cache): rework the SQL schema

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs

- First commit makes it so that we use the `EventCache::clear_all_rooms()` methods when clearing the rooms, from the FFI. Doing otherwise would be incorrect, because if there's a live room in the background, then its in-memory linked chunk would have been desynchronized from the store, leading to confusion all over the place (and potentially some weird constraint violations in the sqlite backend).
- Second commit fixes `clear_all_rooms()` so that it also removes rooms from the store, that haven't ever been loaded in the app. This wasn't the case before, where we'd only clear rooms that have been loaded at least once (either because their room event cache was explicitly requested, or because a sync caused changes to the room). Clearing sleeping rooms causes complications, but hopefully the …

fix(ffi+event cache): properly clear all rooms

---

bindings/matrix-sdk-ffi/src/ruma.rs

This patch fixes forwarding audio and voice messages that would previously show up as files because of missing fields.
Props go out to @jmartinesp for finding what the actual problem was 🍻

fix(ffi): correctly populate all audio content fields when converting from FFI types to Ruma

---

.deny.toml
Cargo.lock
Cargo.toml

This patch updates `eyeball`, `eyeball-im` and `eyeball-im-util` from `main` branch to latest releases.
This patch also updates `imbl` to 5.0.

chore(cargo): Update `eyeball` and `imbl`

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/client.rs
examples/oauth_cli/src/main.rs

It simplifies code for users, and avoids to have to match on `AuthApi`, which is a non-exhaustive enum.

feat(sdk): Add `Client::logout()` to log out regardless of the auth API

---

bindings/matrix-sdk-ffi/src/authentication.rs
crates/matrix-sdk-base/src/deserialized_responses.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/echo.rs
crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
crates/matrix-sdk/src/authentication/oauth/mod.rs
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/error.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/reply.rs
crates/matrix-sdk/src/send_queue/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/src/sliding_sync/builder.rs
crates/matrix-sdk/src/widget/machine/from_widget.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/tests/integration/room/beacon_info/mod.rs

This PR is a collection of small patches that reduce the sizes of various types. A particular focus has been made on `matrix_sdk::Error` where its size has been reduced by 6.5x (from 160 bytes to 24 bytes). This is important as it impacts all the methods and functions that return a `Result`.

Reduce the sizes of various types and mostly `matrix_sdk::Error`

---

crates/matrix-sdk/tests/integration/client.rs

Introduced by merging #4886 and #4887 around the same time.

test(sdk): Fix compilation error

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oauth/mod.rs

There are two commits here:
1. Make sure that the docs of the `oauth` module are up-to-date and mention all the login APIs.
2. Try to clean up the changelog: there were a lot of changes around the Oidc/OAuth API this cycle, and it was hard to follow, especially with methods and types that changed and were then removed.
This groups everything under a single entry, with a short summary of the changes, followed by a list of per-PR changes.
The detailed list is reorganized to put the biggest changes first, like the renaming, and a few entries were cleaned up or removed, because they mention a method or type that is removed in another entry.

Clean up OAuth docs

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/src/lib.rs

This PR is twofold:
1. One patch adds a new constructor for `SqliteStoreConfig`, namely `with_low_memory_config`, which sets some defaults tailored for low memory usage,
2. Another patch adds `ClientBuilder::system_is_memory_constrained` so that the client can be built with that in mind. Behind the scene, for the moment, it only calls `SqliteStoreConfig::with_low_memory_config` instead of `SqliteStoreConfig::new`, but this flag can be used for other use cases.

feat(sqlite): Add `SqliteStoreConfig::with_low_memory_config`

---

crates/matrix-sdk-common/src/executor.rs

makes behavior similar to tokio::spawn otherwise spawned tasks immediately die if join handles are not saved somewhere

fix(wasm): don't kill task on drop

---

bindings/matrix-sdk-ffi/src/timeline/content.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/timeline/msg_like.rs
bindings/matrix-sdk-ffi/src/timeline/reply.rs

This patch introduces an intermediary MsgLike Content and Type on the FFI layer and brings the timeline items in line with the ones from the UI crate.
This is the last step in the timeline item structure factoring, following https://github.com/matrix-org/matrix-rust-sdk/pull/4839, https://github.com/matrix-org/matrix-rust-sdk/pull/4853 and https://github.com/matrix-org/matrix-rust-sdk/pull/4860
Best reviewed commit by commit.

Introduce MsgLike on the FFI layer

---

crates/matrix-sdk-crypto/src/identities/device.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

A set of non-functional changes in `matrix-sdk-crypto` which may not make a whole lot of sense on their own, but are enablers for the actual sharing of room key history bundles (#4864). I decided to separate the refactoring work from the functional changes for easeier review.

crypto: prep work for sharing room key history bundles

---

labs/multiverse/src/widgets/settings/mod.rs

Currently, `h` and `l` are intercepted by the parent view to change tab,
meaning it's impossible to enter a recovery key which contains those
characters.
The fix here is very blunt: it just disables `h` and `l` for tab-changing. I
considered making it dependent on which tab is open, or what's going on in the
'Encryption' tab, but given you need to know about the alternatives (tab/cursor
keys) to switch away from the Encryption tab, I don't think that makes sense.

multiverse: allow recovery keys with `h` or `l` in them

---

labs/multiverse/src/main.rs

This reduces the framerate from ~62fps to 10fps.
This is a workaround for a problem in my terminal, so apologies for inflicting
it on everyone else, but here we are, and 10fps seems like it should be enough
for anyone.
The problem in question is specifically when I try to select some text by
dragging the mouse (eg, to copy a generated recovery key). If I start a drag,
but a redraw happens before the mouse has moved [a certain distance?], then the
drag doesn't work, and nothing gets selected. By reducing the framerate, I have
a much better chance of successfully starting a drag.

multiverse: reduce redraw rate

---

.deny.toml
Cargo.lock
bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/config/request.rs
crates/matrix-sdk/src/http_client/native.rs

Since backon also has WASM support, this should mean that we can get rid of the WASM specific HTTP client implementation.
This closes #4243.

refactor(sdk): Migrate away from the backoff crate to the backon crate

---

bindings/matrix-sdk-ffi/src/notification.rs
crates/matrix-sdk-ui/src/notification_client.rs

Would be useful to tell from a notification if the room that generated it, is public or not, or if has some specific join rule, since a client may want to hide or show the media based on the join rule of the room for safety reasons

feat(bindings): expose `is_public` and `join_rule` in notifications

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/e2ee/decrypt.rs
crates/matrix-sdk-base/src/response_processors/e2ee/mod.rs
crates/matrix-sdk-base/src/response_processors/e2ee/to_device.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/response_processors/mod.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/response_processors/verification.rs
crates/matrix-sdk-base/src/sliding_sync.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4901.
This PR continues to refactor and clean up the response workflow as so-called response processors.
Each patch should be reviewed individually. There is nothing fancy, it's mostly code moves.
This time, it's a bit more interesting as we are clearly reusing existing processors. Even some processors are re-using other processors.
I've cleaned up the `BaseClient::handle_timeline` quite a lot, to finally be able to move it as the new `timeline::build` processor. It is still a bit too broad from my point of view as the commit description says, but at least `BaseClient` is cleaner.
The detection and processing of the verification events is also now unified: previously it was more or less copy-pasted in three different locations.

refactor(base): Continue to extract response processors, take 3

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/element.rs
bindings/matrix-sdk-ffi/src/encryption.rs
bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/session_verification.rs

Also split `ClientError::new` into `ClientError::from_str` and `ClientError::from_err` so we can automatically get the details from the 2nd one.
Signed-off-by:

feat(ffi): Add extra details to `ClientError`.

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/ephemeral_events.rs
crates/matrix-sdk-base/src/response_processors/mod.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/sliding_sync.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4914.
This PR continues to refactor and clean up the response workflow as so-called response processors.
Each patch should be reviewed individually. There is nothing fancy, it's mostly code moves.
This time, we remove the last `handle_` method on `BaseClient`! And we create another set of response processors, `ephemeral_events`, which remove duplicated code.

refactor(base): Continue to extract response processors, take 4

---

crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/sliding_sync/list/builder.rs
crates/matrix-sdk/src/sliding_sync/list/sticky.rs

This patch removes all mentions of `include_heroes`. This field isn't part of the MSC4186. We have the `test_compute_heroes_from_sliding_sync` which continues to pass, everything fine on that side. There is no mention of `include_heroes` in Synapse at the time of writing. It seems to be an artifact from the sliding sync proxy experiment.
---
* Related to https://github.com/ruma/ruma/pull/2058

fix(sdk): Remove `include_heroes` in sliding sync requests

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/deserialized_responses.rs
crates/matrix-sdk-base/src/response_processors/e2ee/decrypt.rs
crates/matrix-sdk-base/src/response_processors/e2ee/mod.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/response_processors/mod.rs
crates/matrix-sdk-base/src/response_processors/notification.rs
crates/matrix-sdk-base/src/response_processors/room/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/response_processors/verification.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/sync.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4925.
This PR continues to refactor and clean up the response workflow as so-called response processors.
Each patch should be reviewed individually. There is nothing fancy, it's mostly code moves.
This time, the sync v2 (`BaseClient::receive_sync_response`) is now fully using response processors. This PR introduces the new `rooms::sync_v2::update_(joined|left|invited|knocked)_room` processors! It also removes duplicated code around push notifications by improving the `notification::Notification` type.

refactor(base): Continue to extract response processors, take 5

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/ephemeral_events.rs
crates/matrix-sdk-base/src/response_processors/room/mod.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/extensions.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/sync.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/sync.rs
crates/matrix-sdk/tests/integration/client.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/notification_client.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4928.
This PR continues to refactor and clean up the response workflow as so-called response processors.
Each patch should be reviewed individually. There is nothing fancy, it's mostly code moves.
This time, the sliding sync (`BaseClient::process_sliding_sync`) is now fully using response processors. This PR introduces the new `rooms::msc4186` processors! It does several things, but the most notable is: a nice clean up around 4 `Option`s being returned by a method, and the removal of a large `clone` of room account data.

refactor(base): Continue to extract response processors, take 6

---

labs/multiverse/src/widgets/room_view/timeline.rs

This is useful to observe the virtyual start of timeline item in manual testing.

multiverse: prefer rendering back-paginated events instead of timeline's tail

---

crates/matrix-sdk-crypto/CHANGELOG.md

PR #4670 didn't land until 0.11.0.

crypto: fix changelog for 0.10.0 and 0.11.0

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/types/events/mod.rs
crates/matrix-sdk-crypto/src/types/events/room_key_bundle.rs
crates/matrix-sdk-crypto/src/types/room_history.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/shared_room_history.rs
testing/matrix-sdk-integration-testing/src/helpers.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee.rs

The next step of our plan to share room history (https://github.com/element-hq/element-meta/issues/39). This PR adds the functionality to:
* Build a blob of room keys
* Upload it as an encrypted media file
* Send the keys to the encrypted media file to a user's devices
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/4505

crypto: encrypt, upload and share keys for room history

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/changes.rs
crates/matrix-sdk-base/src/response_processors/mod.rs
crates/matrix-sdk-base/src/response_processors/room/display_name.rs
crates/matrix-sdk-base/src/response_processors/room/mod.rs
crates/matrix-sdk-base/src/rooms/mod.rs
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/sync.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs

Sequel of https://github.com/matrix-org/matrix-rust-sdk/pull/4934.
This PR should be reviewed patch-by-patch.
The room display name is computed during the sync (for both sync v2 and sliding sync), and is kept in memory. To do that, the `StateChanges` needs to be saved in the state store, because computing the display name requires data from the state store. Problem is: the display name isn't saved after that. One needs to wait on another sync to happen for this particular room to persist/save the computed display name.
This PR fixes that by using the recently added response processors. A test confirms the problem is fixed.
---
Combo.
* Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4051
* Fixes https://github.com/element-hq/element-x-ios/issues/3365
* Fixes …

fix(base): The room computed display name is persisted

---

labs/multiverse/src/widgets/room_view/input.rs
labs/multiverse/src/widgets/room_view/mod.rs
labs/multiverse/src/widgets/room_view/timeline.rs

multiverse: Add a command to invite users to a room

---

testing/matrix-sdk-integration-testing/src/tests/timeline.rs

Fixes #4871 (hopefully). In `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure`, we think we might need to sync twice to persuade the client or server to notice the update to alice's idenitity.

fix(integration-tests): Fixes #4871 (hopefully). Repeatedly sync in a test after other user cross-signs

---

crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/shared_room_history.rs
labs/multiverse/Cargo.toml
testing/matrix-sdk-integration-testing/Cargo.toml
testing/matrix-sdk-integration-testing/src/tests/e2ee.rs

... subject to an experimental feature flag.
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/4511

sdk: share room history when we send an invite

---

crates/matrix-sdk-common/src/timeout.rs
crates/matrix-sdk/src/room/futures.rs
crates/matrix-sdk/src/room/mod.rs
testing/matrix-sdk-integration-testing/src/helpers.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee.rs

Rather than attempting to trigger Alice's encryption sync loop with an incoming message from Bob, instead have Alice send a message once Bob has joined the room.
Hopefully, fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4945.

test: attempt to deflake history-sharing integ test

---

crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/widget/mod.rs

This PR is a revived version of: https://github.com/matrix-org/matrix-rust-sdk/pull/4707 since it is now possible to easily add wasm support thanks to: https://github.com/matrix-org/matrix-rust-sdk/pull/4572
Using the `executer::spawn` will select `tokio::spawn` or `wasm_bindgen_futures::spawn_local` based on what platform we are on.
~~They behave differently in that `tokio` actually starts the async block inside the spawn but the wasm `spawn` wrapper will only start the part that is not inside the `async` block and the join handle needs to be awaited for it to work.~~
This has now changed with: https://github.com/matrix-org/matrix-rust-sdk/pull/4572.
Now they behave the same and this PR becomes a very simple change.
Signed-off-by:

WidgetDriver: Use `matrix_sdk_common::executor::spawn` instead of `tokio::spawn` to make it wasm compatible.

---

crates/matrix-sdk-base/src/response_processors/notification.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/client.rs
testing/matrix-sdk-integration-testing/src/tests/nse.rs

This has three benefits:
- we don't need to recompute the full push context (which requires a few database accesses each time) when we're calling `try_decrypt_event()` for lots of events (which can happen when doing `/context` queries).
- this makes the workflow very explicit: you may get (or not) a `PushContext`, and use that to compute the push actions after decrypting
- we will properly fill the push actions for non-encrypted messages received with `/messages` at the right time (in `self.try_decrypt_event`), so we don't need to do it in an extra processing step
This is a preparatory refactoring for threads, since we'll want to use similar logic when fetching the thread roots, or when back-paginating inside a thread.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4869.

refactor(sdk): compute a push context only once when computing push actions for a bunch of events

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/machine/tests/send_encrypted_to_device.rs
crates/matrix-sdk-crypto/src/machine/tests/snapshots/processed_to_device_variants.snap
crates/matrix-sdk-crypto/src/olm/session.rs
crates/matrix-sdk-crypto/src/types/events/olm_v1.rs
crates/matrix-sdk-crypto/src/types/events/snapshots/decrypted_to_device_event_snapshot.snap
crates/matrix-sdk-crypto/src/types/events/snapshots/sender_device_keys_are_deserialized.snap

This patch updates the sending side of the `sender_device_keys` field introduced in MSC4147.
Since the MSC got merged, we're switching from the unstable identifier to the stable one.
A couple of snapshot tests were added modified to make this happen.

feat(crypto): Start using the stable identifier for the sender device keys

---

CONTRIBUTING.md

Following our internal discussion, here's a small text summarizing our position with respect to intermittent test failures in the project. TLDR:
- we open issues with the label `intermittent-failure`
- we comment there whenever there's a testing failure
- we disable tests if they've been intermittently failing for two weeks, and no one's actively trying to fix them

docs: add an intermittent test failure policy

---

crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-crypto/src/store/memorystore.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-crypto/src/store/traits.rs
crates/matrix-sdk-crypto/src/types/events/olm_v1.rs
crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs
crates/matrix-sdk-sqlite/migrations/crypto_store/010_received_room_key_bundles.sql
crates/matrix-sdk-sqlite/src/crypto_store.rs

Add hooks to the memory store and sqlite store to stash the information about room key data.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4512

crypto: store received room key bundle data information

---

crates/matrix-sdk-base/src/response_processors/state_events.rs

Fixes #4952 .
Signed-off-by: Benjamin Kampmann <ben@acter.global>

fix(sdk): Don't overwrite previously added state events for this room in state_event sync processing

---

crates/matrix-sdk/src/widget/machine/driver_req.rs
crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/machine/to_widget.rs

I didn't know we had implemented promises in the widget machine/driver/thingy. Anyhow, this includes a few tiny refactorings caused by "wtfs" emitted during previous reviews of the widget code, and which in my opinion make the code easier to read, etc.

refactor(widget): simplify a few things

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

Previously, `is_session_overshared_for_user` did not take into account that `shared_with_set` also contains withheld device IDs who explicitly have never received the session keys. This would lead to it mistakenly determining oversharing for those devices for every event being sent in the presence of blacklisted/withheld devices in the room, and rotating the group session accordingly.
The fix is to correctly exclude devices with `ShareInfo::Withheld` from the enumeration.
Signed-off-by: Niklas Baumstark niklas.baumstark@gmail.com

Crypto: Fixed a bug where room keys would be rotated unecessarily in the presence of blacklisted/withheld devices

---

testing/matrix-sdk-integration-testing/src/tests/timeline.rs

Ignores a test that is flaking, tracked here: https://github.com/matrix-org/matrix-rust-sdk/issues/4871

task(tests): Ignore test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure because it is flaky

---

crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/unable_to_decrypt_hook.rs

Tentative fix for https://github.com/matrix-org/matrix-rust-sdk/issues/4832
Tweaked a bit the timings and added more logging in the UTD manager to see what is happening exactly in case it is still flaky.
Signed-off-by:

fix(tests): tweak a flaky test to make it more stable + logs

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

Attempted fix for #2729 based on previous discussion in https://github.com/matrix-org/matrix-rust-sdk/pull/4954.
To summarize, the situation of pending room key sharing requests prior to calls to `GroupSessionManager::share_room_key` can indeed occur if `matrix-sdk-crypto` is used directly. In the case where `matrix-sdk` wraps it, [`Room::share_room_key`](https://github.com/matrix-org/matrix-rust-sdk/blob/a60e336f8572252e26f8dacb42e096f0f6d1fce3/crates/matrix-sdk/src/room/mod.rs#L1799) makes sure to send pending requests right after, as well as mark them as sent which will cause the corresponding entry in `to_share_with_set` to be moved to `shared_with_set`. If there is a failure, the room key [is discarded](https://github.com/matrix-org/matrix-rust-sdk/blob/a60e336f8572252e26f8dacb42e096f …

Crypto: Take into account pending to-device room key sharing requests when collecting devices

---

crates/matrix-sdk-crypto/src/machine/mod.rs

This method had a confusing name: it didn't receive a key bundle, but rather the data *about* a key bundle.
Remove the unused `sender_key` parameter while we are at it: we use the embedded (and already-checked) `event.sender_device_keys` here.

crypto: clean up confusing method

---

bindings/matrix-sdk-ffi/src/client.rs

Since only homeservers that support matrix v1.13 are able to use this API, clients might need to know if the report room API is available or not, to display an action to the user

feat(bindings): check if report room api is supported

---

bindings/matrix-sdk-crypto-ffi/src/machine.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/snapshots/matrix_sdk_common__deserialized_responses__tests__encryption_info_migration.snap
crates/matrix-sdk-common/src/snapshots/snapshot_test_sync_timeline_event.snap
crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs

Moves the `session_id` field from EncryptionInfo to AlgorithmInfo::MegolmV1AesSha2 as it is specific to megolm. Provides transparent migration of serialized data.
In the future we plan to reuse `EncryptionInfo` for to_device decryption (using olm not megolm). So megolm session_id should move to algorithm specific data.
This is a follow-up of https://github.com/matrix-org/matrix-rust-sdk/pull/4935 and also ground work for future changes.
As discussed here https://github.com/matrix-org/matrix-rust-sdk/pull/4935#discussion_r2049153547
This PR also provides migration for old serialized `EncryptionInfo` (serialized in the event cache).
I only provide specific migration for `EncryptionInfo`.
I don't think more migration it is needed for `AlgorithmInfo::MegolmV1AesSha2` as the added `session_id` …

refactor(crypto): Move `session_id` from `EncryptionInfo` to `AlgorithmInfo` as it is megolm specific

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs

`matrix_sdk_ffi` exposes functions for sending attachments through the [`Timeline`](https://github.com/matrix-org/matrix-rust-sdk/blob/bc50cae35fd32b902eac4d86d61ebe2ee7e11df2/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L93). These functions, however, only allow the foreign language to provide the name of a file (see [UploadParameters](https://github.com/matrix-org/matrix-rust-sdk/blob/bc50cae35fd32b902eac4d86d61ebe2ee7e11df2/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L203)) and require that the linked Rust library actually handle reading the files.
Add functionality to make it possible for a foreign language to read in a file's contents natively and then upload those contents through the `Timeline`.  
Currently, `UploadParameters.filename` is eventually transformed into an …

FFI: Allow file data to be passed through bindings when sending attachment

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/messages.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs

The tests show how to use them for listing threads (`Room::list_threads()`), and the events within a thread (`Room::relations()`).
This should be sufficient to implement an in-memory (viz. not persisted on disk) `RoomThreadEventCache` :eyes: according to the plan described in #4869.
Part of #4869.

feat(threads): add methods to list a room's threads + list all related events

---

crates/matrix-sdk-crypto/src/gossiping/machine.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/share_strategy.rs

As discussed in #4975. Previously, the `share_strategy` was breaking the abstraction provided by `OutboundGroupSession` by accessing its internal fields in an inconsistent and adhoc way. Now all fields are private and a proper abstraction was added to access the required state in a consistent API.
NOTE: Mostly used this to practice my Rust, I'm not heavily invested in it

refactor(crypto): Properly encapsulate internal `OutboundGroupSession` state

---

bindings/matrix-sdk-ffi/src/widget.rs
crates/matrix-sdk/src/widget/capabilities.rs
crates/matrix-sdk/src/widget/filter.rs
crates/matrix-sdk/src/widget/machine/driver_req.rs
crates/matrix-sdk/src/widget/machine/from_widget.rs
crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/machine/tests/send_event.rs
crates/matrix-sdk/src/widget/mod.rs

This is a split out of: https://github.com/matrix-org/matrix-rust-sdk/pull/4856
It is the first step to introduce to-device events to the widget api.
With this PR we only focus on the current filter implementation and change improve it so that adding to-device
filters can be done in a cleaner way. The refactor is a result of what worked well when doing the full implementation in https://github.com/matrix-org/matrix-rust-sdk/pull/4856
(This PR does not yet include any to-device changes. It will make the introduction of the filtering for to-device events much cleaner and simpler to read)
The API for the filters was a bit confusing since it had a lot of special cases.
This commit also simplifies the filter public api.
Rethinking the public api we only need:
- to know if events can be sent …

WidgetDriver: to-device support, refactor `Filter`

---

bindings/matrix-sdk-ffi/src/notification.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs

This PR tweaks the NotificationClient so that it also requests the `org.matrix.msc3401.call.member` state and exposes a method for fetching rooms from its internal in-memory store backed client.
These will be used to check whether a room still has an ongoing call before showing the ringing screen.

Notification client call members

---

bindings/matrix-sdk-crypto-ffi/src/error.rs

This error does not necessarily mean that the session was *withheld*.

crypto-ffi: fix error message for `MissingRoomKey`

---

crates/matrix-sdk-crypto/src/verification/machine.rs

Validation errors on the timestamp of the device verification request are now logged on a visible level.
In element-hq/element-web#29625 it was found to be useful to give more visibility to this kind of verification error.
Signed-off-by: mpeter50 <83356418+mpeter50@users.noreply.github.com>

Update logging of device verification request timestamp valdiation

---

crates/matrix-sdk-sqlite/CHANGELOG.md
crates/matrix-sdk-sqlite/src/event_cache_store.rs

Imagine we have the following events:
| event_id | room_id | chunk_id | position |
|----------|---------|----------|----------|
| $ev0     | !r0     | 42       | 0        |
| $ev1     | !r0     | 42       | 1        |
| $ev2     | !r0     | 42       | 2        |
| $ev3     | !r0     | 42       | 3        |
| $ev4     | !r0     | 42       | 4        |
`$ev2` has been removed, then we end up in this state:
| event_id | room_id | chunk_id | position |
|----------|---------|----------|----------|
| $ev0     | !r0     | 42       | 0        |
| $ev1     | !r0     | 42       | 1        |
| $ev3     | !r0     | 42       | 3        |
| $ev4     | !r0     | 42       | 4        |
We need to shift the `position` of `$ev3` and `$ev4` to `position - 1`, like so:
| event_id | room_id | chunk_id | …

fix(sqlite): Fix a `UNIQUE` constraint violation with `Update::RemoveItem`

---

crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-sqlite/src/crypto_store.rs
crates/matrix-sdk-sqlite/src/error.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/client/builder/mod.rs

- Doc comment for the SQLite-based state store incorrectly referred to
it as a "cryptostore".
- Consistent capitalisation of SQLite.
- Consistent use of indefinite article "an" before SQLite.
- Fix line length.

Tweak some store-related comments

---

bindings/matrix-sdk-ffi/src/client_builder.rs

Small PR to expose the scanned `server_name` in QR code data so that clients with e.g. MDM can choose not to continue with the authorisation for particular servers.

FFI: Expose the QrCodeData server name.

---

crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/test_helpers.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data_finder.rs

If we already have cross-signing details for the owner of the device at the point we receive the to-device message, we should store that rather than just the device info.
To enable this, we have a couple of preparatory commits which factor out some code from `SenderDataFinder` so that we can reuse the same logic when we receive the key bundle data.
Suggest review commit-by-commit
Part of https://github.com/element-hq/element-meta/issues/2685

crypto: improve SenderData stored with room key bundle data

---

crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-common/Cargo.toml
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-indexeddb/Cargo.toml
crates/matrix-sdk-qrcode/Cargo.toml
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk-store-encryption/Cargo.toml
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk/Cargo.toml

This patch adds the `--generate-link-to-definition` argument to `rustdoc` for `docs.rs`. This is using https://github.com/rust-lang/rust/pull/84176 to add links in the source code page.

doc: Generate doc with `--generate-link-to-definition`

---

crates/matrix-sdk/tests/integration/room/common.rs
testing/matrix-sdk-test/src/event_factory.rs

Part of #3716
I was working on replacing all uses of `sync_timeline_event!` in this test file, but after seeing that it probably requires adding more than one new method on `EventFactory`, I thought I'd make a PR for a subset of the changes I've done so far which I think are still useful in isolation and self-contained, to keep the diff smaller.
On the other hand, if these code changes alone are too small to warrant a PR then I'm happy to keep adding the rest of the changes to get rid of `sync_timeline_event!` from that file :slightly_smiling_face: 

Test: Replace `sync_timeline_event!` with `EventFactory` for room create and room member events in room integration test

---

crates/matrix-sdk-ui/src/timeline/tests/virt.rs

This test fails when run in the Americas, because over here the Unix epoch took place in 1969 =D

fix(tests): Avoid depending on the local time zone in tests

---

crates/matrix-sdk/tests/integration/room/common.rs
testing/matrix-sdk-test/src/event_factory.rs

Part of #3716
I went with a `BTreeMap` for the parameter type on the new helper method on `EventFactory` purely because that's the type of the `RoomPowerLevelsEventContent.users` field, there was no other reason for that choice of map type.

Test: Replace `sync_timeline_event!` with `EventFactory` for room power level events in room integration test

---

crates/matrix-sdk/tests/integration/room/common.rs
testing/matrix-sdk-test/src/event_factory.rs

Part of #3716
The added method to `EventFactory` could be thought of as redundant, since its args are simply being passed through to the `RoomServerAclEventContent` constructor.
I thought one reason to have it is so then `event_factory.rs` could be the single place where the `RoomServerAclEventContent` struct is imported, so that no test modules wanting to create this particular event would need to do the import themselves.
So I could understand both wanting it or not wanting it, I'm happy to go with whatever is preferred.

Test: Replace `sync_timeline_event!` with `EventFactory` for room server ACL event in room integration test

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/notification_settings.rs
bindings/matrix-sdk-ffi/src/ruma.rs

feat(ffi): Add methods for observing account data changes

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs
crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/date_dividers.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs

This patch is twofold.
This patch fixes the insertion of a new `TimelineItem` in the presence of a `TimelineStart` that shifts/offsets the timeline index of 1. It fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4976. It also contains a regression test.
Based on https://github.com/matrix-org/matrix-rust-sdk/pull/4816#pullrequestreview-2705148141, I'm proposing a new concept in `timeline::controller::ObservableItems`: **regions**.
The `ObservableItems` holds all the invariants about the _position_ of the items. It defines three regions where items can live:
1. the _start_ region, which can only contain a single `TimelineStart`,
2. the _remotes_ region, which can only contain many `Remote` timeline items with their decorations (only `DateDivider`s and `ReadMarker`s),
3. the …

fix(ui): Introduce `Timeline` regions

---

crates/matrix-sdk/tests/integration/room/common.rs
testing/matrix-sdk-test/src/event_factory.rs

Part of #3716
I inlined the creation of the `EventFactory` in the second test since it's only used once and I thought it was a tad neater than having a separate binding. Hopefully the extra level of indentation is tolerable, but I'm happy to define the `EventFactory` instance separately if it's too unsightly :slightly_smiling_face: 

Test: Replace `sync_timeline_event!` with `EventFactory` for room canonical alias events in room integration test

---

bindings/matrix-sdk-ffi/src/notification.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs

Add `NotificationClient::get_notifications` method to be able to retrieve several push notification events in the same sliding sync pass.
Also add several helper structs for this, and try to make error handling per-notification request when possible.
Signed-off-by:

feat(ui): allow retrieving push notification events in batches

---

Cargo.lock
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs

This centralizes (and simplifies, IMO) the creation of new timeline items vs handling of aggregations. Before, this was done partly when creating the (type previously known as) `TimelineEventKind` and handling it later in the `TimelineEventHandler`. Now, the event is analyzed once, and analyzing the event results in three outcomes:
- either the event type is not supported: we do nothing
- or it would result in a new timeline item: the item is created and wrapped in `TimelineAction::AddItem`
- or it would result in a new aggregation: the aggregation is created and wrapped in `TimelineAction::HandleAggregation`
That way, it should be much simpler to handle aggregation-only events in non-live timelines, which will be handy for thread timelines.
Part of #4869.

refactor(timeline): replace `TimelineEventKind` with `TimelineAction`

---

Cargo.lock

I'm not sure why I am the first one to get this error in CI, they are supposed to have been issued a month ago…

chore: Get rid of cargo-deny errors due to new advisories

---

bindings/matrix-sdk-ffi/src/timeline/configuration.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/error.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/threaded_events_loader.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs

… that allows building a timeline instance specific to a particular thread root.
Creating a timeline in this mode will start by backpaginating root event relations with `num_events` and automatically insert the thread root event when reaching the end. It will include `RelationsOfType(RelationType::Thread)` but also recurse over the retrieved events to fetch reactions. 
It will not however react to new events received over sync or that the user sends (for now).
This patch will also help incrementally deliver the upstream client support for creating such a timeline.
Part of #4833 (meta #4869).

feat(ui): add new `Thread` timeline focus mode and associated events loader

---

crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/widget/machine/driver_req.rs
crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/machine/to_widget.rs

The then() function can be used with booleans and futures to execute a piece of code if the boolean is true or once the future is completed.
In contrast, the then() function in the widget driver is not executed immediately. Instead it only adds a callback that is later on executed by the widget driver.

refactor(widgets): Rename the then() function into add_response_handler()

---

crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-crypto/src/types/mod.rs

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4513 and necessary for https://github.com/matrix-org/matrix-rust-sdk/pull/4989.
Making this generic right now is a bit of a no-op, but eventually we'll also import the `HistoricRoomKey` type which requires this to be generic.

refactor(crypto): Make the room key importing logic more generic

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room/mod.rs

This moves the logic from `Room::join()` to these two methods. This is isofunctional, because `Room::join()` does call into `Client::join_room_by_id()` internally.
Fix #4730.

fix(sdk): mark invited DM rooms joined with `Client::join_room_by_id` or `Client::join_room_by_id_or_alias` as DMs

---

crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/tests/basic.rs
crates/matrix-sdk-ui/src/timeline/tests/polls.rs
testing/matrix-sdk-test/src/event_factory.rs

They have never been set and there was no way of telling if stickers and polls belong on a thread or come in reply of any other message.
This patch also exposes methods for setting these relations on the event factory level for polls.

fix(ui): populate the `thread_root` and `in_reply_to` fields for stickers and polls

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk-base/src/response_processors/e2ee/decrypt.rs
crates/matrix-sdk-base/src/response_processors/e2ee/to_device.rs
crates/matrix-sdk-base/src/response_processors/e2ee/tracked_users.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/extensions.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/response_processors/verification.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/src/sliding_sync/cache.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/sliding_sync/room.rs
crates/matrix-sdk/tests/integration/event_cache.rs
labs/multiverse/src/widgets/room_view/details/events.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

These patch removes `SlidingSyncRoom::timeline_queue`, `SlidingSyncRoom::prev_batch`, `FrozenSlidingSyncRoom::timeline` and `FrozenSlidingSyncRoom::prev_batch`.
The removal of `timeline_queue` has escalated to updating `read_receipts::compute_unread_counts` to be called with events from the Event Cache instead of `timeline_queue`. The code has been revisited a little bit around the sliding sync workflow, but nothing fancy or deep.
---

feat(sdk): Remove `SlidingSyncRoom::timeline_queue` and `prev_batch`

---

bindings/matrix-sdk-ffi/src/widget.rs
crates/matrix-sdk/src/widget/settings/element_call.rs

This is used to configure EC on devices that need to control media outputs on their own (android, ios).
If set, EC will display a list of devices provided by the app.
Signed-off-by:

feat(widgets): Add the `controlledMediaOutput` url parameter to the `VirtualElementCallWidgetOptions`.

---

Cargo.lock
examples/oauth_cli/Cargo.toml
examples/persist_session/Cargo.toml

chore: Upgrade dirs to 6.0 in examples

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/rooms/normal.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs

This patch removes the `RoomInfo::prev_room_state` field, along with the `RoomInfo::prev_state` method.
This data was introduced during the knocking project but was never used, and is not used nowadays. Let's remove it.

chore(base): Remove `RoomInfo::prev_room_state`

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/ruma.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs

This PR
- Updates Ruma to use the improved MediaPreviewConfig event type that also supports a `Default` for the content type
- Implemented a way to observe the stable and unstable values of the event and return the used one accordingly, if no one is present the default will be used
- Set the value (will only use unstable type for now)

feat: implement and observe MSC4278 config value

---

crates/matrix-sdk-crypto/src/machine/mod.rs

There are two reasons for this.
Firstly. we've already done a bunch of work to map `SenderData` into a `VerificationState`, and the decision tree from `VerificationState` to allow/reject is simpler than going from `SenderData`, even if we have to fudge it a bit to get the "legacy" flag. (Note that it allows us to get rid of an `unreachable!` panic.)
Secondly, `VerficationState` represents the state of an *event*, whereas `SenderData` is about the session as a whole. A session can be fine, whilst events (claiming to be) encrypted with it can be suspect. What we want here is to check a specific message. Currently, this doesn't make any functional difference, but conceptually it's cleaner to check the `VerificationState`.
Note that there are a bunch of tests for this method in …

crypto: rewrite `check_sender_trust_requirement` to use `VerificationState`

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs

This avoids a few spurious pinned event timeline resets, as shown by the test changes.

feat(timeline): don't reset the pinned events timeline when underlying events haven't changed

---

crates/matrix-sdk/tests/integration/room/beacon/mod.rs
testing/matrix-sdk-test/src/event_factory.rs

Part of #3716
I _think_ I've done something sensible for adding the ability to put age into the unsigned data of an event, but it's possible I've misunderstood how the fields on `Unsigned` are being used.
It seemed like fields from different `*Unsigned` types from `ruma` were all put onto the single `Unsigned` struct (ie, `transaction_id` and `relations` from `RoomMemberUnsigned`, and `redacted_because` from `RedactedUnsigned`), and that some but not all fields on an `Unsigned` instance within an `EventBuilder` would be made a `Some` value depending on what event type was being created.
So, I just stuck another field onto `Unsigned` to allow `age` to be in the unsigned data, even though it's not a field that's available on every `*Unsigned` type, imagining it'd be used only for events …

Test: Replace `sync_timeline_event!` with `EventFactory` for beacon events in room integration test

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/controller/aggregations.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/observable_items.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/message.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/polls.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
crates/matrix-sdk-ui/src/timeline/tests/reactions.rs
crates/matrix-sdk-ui/src/timeline/tests/redaction.rs
crates/matrix-sdk-ui/tests/integration/timeline/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/reactions.rs
testing/matrix-sdk-integration-testing/src/tests/timeline.rs

This uses the `Aggregations` manager to take care of redactions and edits, allowing us to get rid of the `pending_edits` in the `TimelineMetadata` \o/ Aggregations are now handled in a single manner, which is nice for consistency.
For redactions, this means we now stash a redaction even if we've seen it before the event it redacts, making sure we won't display something that should've been redacted.
For edits, we now do "the right thing", and will look at the position of each edit event we know about, and use the most "recent" one, if we've found any. This will help handling edits within threads as well (as such, helps with #4869), instead of having us implement some more complicated logic for those.
Part of #4823.

refactor(timeline): finish the aggregations refactoring

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs

The reason behind this PR, is to extend https://github.com/matrix-org/matrix-rust-sdk/pull/5040 
While the observable value is very useful in the context of the main app, it may be problematic in the context of parallel processes that aim to aid the main app process, like for example the Notification Service Extension on iOS, which is treated as a different process, and has some very harsh memory contraints, and a limited lifetime, which would make the observable values not quite useful.
Also while we do have a [`get_media_preview_config_event_content`](https://github.com/matrix-org/matrix-rust-sdk/blob/0cfb4b1c55dd2ff8e90a6bb804944592ea819222/crates/matrix-sdk/src/account.rs#L1067) that is used by the observable API, this sends a request to the server to check for the current account …

feat(bindings): added APIs to get the media preview config from the store

---

crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs
testing/matrix-sdk-test/src/sync_builder/test_event.rs
testing/matrix-sdk-test/src/test_json/sync_events.rs

This allows to follow [these recommendations from the spec](https://spec.matrix.org/v1.14/client-server-api/#client-behaviour-6) automatically:
> Clients SHOULD reset the unread marker by setting unread to false when opening a room to display its timeline.
>
> Clients that offer functionality to mark a room as read by sending a read receipt for the last event, SHOULD reset the unread marker simultaneously.
Note that there was a function in the bindings doing a similar thing that was removed in https://github.com/matrix-org/matrix-rust-sdk/pull/3119, but it doesn't seem that it was necessary to fix the bug that it was trying to fix.

feat(sdk,ui): Unset the unread flag when sending unthreaded receipts

---

Cargo.lock
benchmarks/benches/room_bench.rs
benchmarks/benches/timeline.rs
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/notification.rs
bindings/matrix-sdk-ffi/src/room.rs
bindings/matrix-sdk-ffi/src/room_list.rs
bindings/matrix-sdk-ffi/src/sync_service.rs
bindings/matrix-sdk-ffi/src/timeline/configuration.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/utd.rs
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/src/room_list_service/room.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs
labs/multiverse/src/main.rs
labs/multiverse/src/widgets/room_view/mod.rs

This PR implements the plan laid out in #4718: it removes long living timeline instances from the room list service and its items in favor of directly creating a timeline through its parent room and the `timeline_with_configuration` method.
In order to do so it also moves the previously internally configured UTD hook to the FFI client and exposes an option to use it on the aforementioned timeline configuration method.
NB: the event filter is already exposed in the configuration and the event cache is now enabled by default.

ffi: Refactor timeline creation and lifetimes

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs

One more bullet item of #4823. The reply preview will now support all the types that are supported by the timeline, by default, and the UTD hook will also be called when creating a `RepliedToEvent` when the replied-to event is a UTD.
On top of #5046, so draft. Only the latest commit has been added on top of the aforementioned PR.

refactor(timeline): use `TimelineAction::from_event` to create a `RepliedToEvent` struct

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs

This is a direct follow up to #4823, because it was deemed a bit too big for that PR. Also nicely groups all the parameters of `TimelineAction::from_content` when the event is a remote echo.
(I get more and more ideas to refactor this part of the timeline, please send help, in the form of contributor time or financial support to Element :D)

feat(timeline): pass the encryption info for a bundled edit

---

bindings/matrix-sdk-ffi/src/room_preview.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

This behaviour was added only at the `RoomPreview::leave` method, but since we're slowly moving away from it we should move the forget action to the `Room::leave` method instead.
Signed-off-by:

refactor: when leaving an `Invited` room also forget it

---

crates/matrix-sdk-ui/src/timeline/tests/shields.rs

Part of #3716
A pretty simple change, nothing specific to say about this one :slightly_smiling_face: 

Test: Replace `sync_timeline_event!` with `EventFactory` for plain text room message event in timeline shield test

---

bindings/matrix-sdk-ffi/src/room_info.rs
crates/matrix-sdk-base/src/room/mod.rs
crates/matrix-sdk-base/src/room/tombstone.rs
testing/matrix-sdk-test/src/event_factory.rs
testing/matrix-sdk-test/src/test_json/sync_events.rs

This patch adds 2 methods on `Room`:
1. `predecessor_room()`,
2. `successor_room()`.
If a room A is tombstoned, it is replaced by a room B. Room A is the predecessor, and room B is the successor. Having this clear semantics is helpful, and will help to solve https://github.com/matrix-org/matrix-rust-sdk/issues/5050.
Documentation has been improved, along with adding missing tests, and writing new tests.
---
* Address https://github.com/matrix-org/matrix-rust-sdk/issues/5050

feat(base): Create `Room::predecessor_room()` and `Room::successor_room()`

---

crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

This patch updates `Room::leave` to not early return when the server returns a 403 error code on `/leave`. Indeed, if the user doesn't have the permissions to leave a room, it's impossible for they to leave it. Let's consider it's fine to ignore this particular error and continue the process of leaving the room.

fix(sdk): Continue leaving a room if server replies with 403

---

crates/matrix-sdk-ui/src/timeline/date_dividers.rs

fix(test): make the `test_monthly_divider_mode` test pass all on timezones

---

crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs

Okay, that's a small clean up, but a nice one. The `dispatch_and_get_new_users` response processor is renamed `dispatch`. Less allocations, one less clone, and clear code, please review each patch individually, it's rather simple and straightforward.
---
- Address https://github.com/matrix-org/matrix-rust-sdk/issues/5050

refactor(base): Improve the `dispatch_and_get_new_users` response processor

---

crates/matrix-sdk-crypto/src/store/integration_tests.rs

The test was ignored since the functionality was only implemented for the memory and SQLite store. This caused a bug in the SQLite implementation to go unnoticed.
Let's just disable it for Wasm since this is the only place where we didn't yet implement the necessary methods.
Based on top of #5071 since the fix for a bug this test should have catched is on that branch.

test: Enable the historic room key bundle storage test, except on Wasm

---

bindings/matrix-sdk-ffi/src/event.rs

At the moment, the error just says `Unsupported Event Type`, which is not that helpful.
Signed-off-by:

refactor: When mapping FFI event contents, log unsupported event types

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/detect-long-path.yml
.github/workflows/documentation.yml
.github/workflows/msrv.yaml

This only makes sense to do for workflows that branch off of github.event.pull_request.draft, which only bindings_ci.yml does at this point in time.

refactor(ci): Don't rerun most CI jobs when un-drafting a PR

---

Cargo.lock
crates/matrix-sdk-base/Cargo.toml

This removes the paste dependency decancer had. We still need to have a denyc exception for paste because of rmp-serde and ratatui.

chore: Bump our decancer version

---

Cargo.toml
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/aggregations.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/remote.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk/src/event_handler/mod.rs
crates/matrix-sdk/src/room/mod.rs

It's >100 bytes large and often optional, so it makes sense to put it on the heap to reduce the size of structs with such optional fields, and the stack size of functions with such optional parameters. It's also cloned in a couple places in the UI crate, so it probably makes sense to just always refcount it.
This started as a clippy suggestion to box `PendingEdit` inside `AggregationKind::Edit`.

refactor: Wrap EncryptionInfo in Arc

---

crates/matrix-sdk/src/widget/filter.rs
crates/matrix-sdk/src/widget/machine/driver_req.rs
crates/matrix-sdk/src/widget/machine/from_widget.rs
crates/matrix-sdk/src/widget/machine/incoming.rs
crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/machine/tests/api_versions.rs
crates/matrix-sdk/src/widget/machine/tests/capabilities.rs
crates/matrix-sdk/src/widget/machine/tests/error.rs
crates/matrix-sdk/src/widget/machine/to_widget.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/src/widget/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs
crates/matrix-sdk/tests/integration/widget.rs
testing/matrix-sdk-test/src/event_factory.rs
testing/matrix-sdk-test/src/sync_builder/invited_room.rs
testing/matrix-sdk-test/src/sync_builder/joined_room.rs
testing/matrix-sdk-test/src/sync_builder/knocked_room.rs
testing/matrix-sdk-test/src/sync_builder/left_room.rs
testing/matrix-sdk-test/src/sync_builder/test_event.rs

This is an implementation of [an update to MSC2762](https://github.com/matrix-org/matrix-spec-proposals/pull/4237). It changes the widget driver to split state updates out into an `update_state` action and use the `send_event` action exclusively for forwarding timeline events. Accordingly, `read_events` now always reads from /messages, never the state store.
For https://github.com/element-hq/voip-internal/issues/289

Widget driver: Distinguish room state and timeline events

---

crates/matrix-sdk-crypto/src/olm/account.rs
crates/matrix-sdk/src/room/shared_room_history.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee/shared_history.rs

These two patches ensure that we:
1. Have all the devices of the recipient of the room key bundle before we send it out.
2. Accept a room key bundle from a device even if the device which has sent us the bundle isn't found in our local store.
The second point depends on [MSC4147](https://github.com/matrix-org/matrix-spec-proposals/pull/4147).

Make the sharing and accepting of historic room key bundles more robust

---

crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs

Part of #3716
For the tests which were modified, this additionally:
- removes server timestamp information on events that weren't necessary for the associated test to pass
- for places where multiple events were added at the same time, the code was very slightly tidied by adding them in bulk rather than adding them individually
If it's preferred to do those changes separate to the removal of the `sync_timeline_event!` macro, I'm happy to split them off into a separate PR :slightly_smiling_face:

Test: Replace `sync_timeline_event!` with `EventFactory` for events in timeline subscribe tests

---

labs/multiverse/src/main.rs

Rather than always writing the logs to `/tmp`, write them to the session
directory. The session directory defaults to `/tmp` so by default this will do
the same as before, but if you override the session path on the commandline,
the logs will get stored alongside the stores and caches.
This is particularly useful when running two instances of multiverse, and you
want them to put their logs in different places.

multiverse: write logs to session dir

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/lib.rs
crates/matrix-sdk-common/src/serde_helpers.rs
crates/matrix-sdk-common/src/snapshots/snapshot_test_sync_timeline_event.snap
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
testing/matrix-sdk-test/src/event_factory.rs

This adds the following functionality:
- we add a new `ThreadSummary` data structure (empty at the moment; it will be filled later), and add it as a field of `TimelineEvent`
- when a thread root event contains a bundled thread summary, we translate it into a `ThreadSummary` on the carrying event.
- event cache: when an event is a threaded reply, we identify the thread root and attach a `ThreadSummary` to it
- we forward this new `ThreadSummary` into the timeline's `ThreadSummary`
This allows a main timeline to identify which events are thread roots, by querying whether they have a (timeline) `ThreadSummary` with `event_item.content().thread_summary().is_some()`. If that's the case, then it means the item can lead to the opening of a thread.
Subsequent PRs will introduce Interesting …

feat(threads): add a `ThreadSummary` to `TimelineEvent` and maintain it over time

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/futures.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/media.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs

- Add `ClientInner::server_max_upload_size` field to hold the max upload size coming from the media config endpoint response.
- Add `Client::load_or_fetch_max_upload_size()` fn that will either load the value from the cached `OnceCell` or fetch it from the homeserver using the media config endpoint, then set it in the cell. This means the value is only valid for the current Client and will have to be re-fetched when the client is restarted.
- Create `SendMediaUploadRequest` wrapper for media upload requests, which will check the size of the file to upload and cancel the upload with an error if the file is larger than the allowed size.
- Expose `ffi::Client::get_max_upload_size()` fn to get this value so we can use it when compressing media in the platform side to check if further …

fix(sdk): check max_upload_size before attempting to upload any media

---

bindings/matrix-sdk-ffi-macros/src/lib.rs

Change the uniffi export to not use tokio on Wasm platforms.

feat(wasm): Add Wasm platform aware test to export proc-macro

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/Cargo.toml
bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs

Addendum to https://github.com/matrix-org/matrix-rust-sdk/pull/5125 to allow sending galleries from the FFI crate. This is the final PR for galleries (apart from possible enhancements to report the upload status in https://github.com/matrix-org/matrix-rust-sdk/pull/5008).
This is somewhat lengthy again, apologies. Most of the changes are just wrappers and type mapping, however. So I was hoping that it's relatively straightforward to review in bulk. Happy to try and elaborate on the changes or break them up into smaller commits if that helps, however.

feat(ffi): Expose method for sending galleries

---

crates/matrix-sdk-ui/src/timeline/futures.rs

Similar to https://github.com/matrix-org/matrix-rust-sdk/pull/5169, subscriptions now support wasm making this cfg carve out unnecessary. 

feat(wasm): Enable subscribe_to_send_progress on wasm platforms

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs

Looks like I forgot adding this in https://github.com/matrix-org/matrix-rust-sdk/pull/5163, sorry. Everything below the FFI layer was already prepared for replies.
Signed-off-by:

feat(ffi): Add reply_params to GalleryUploadParameters

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/ruma.rs

This helps in the case we want to observe the membership state changes - or some other info - for a room that's still not known so we can't just use `Client::get_room` to fetch it.
Signed-off-by:

feat(ffi): Subscribe to a room's `RoomInfo` through `Client`

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
tarpaulin.toml

This particular crate is running into segfaults as part of the code coverage job in #5165. I've opened https://github.com/xd009642/tarpaulin/issues/1749 to track the status of this failure upstream, or know if there are workarounds/other solutions we could try. In the meantime, @poljar agreed with me that we ought to disable it.
This will lose us a few points of coverage, but hopefully we can get it back when the upstream issue has been fixed.

chore(ci): exclude `matrix-sdk-base` from code coverage testing :(

---

crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk-base/src/response_processors/e2ee/decrypt.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/response_processors/verification.rs
crates/matrix-sdk-base/src/room/latest_event.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-common/src/serde_helpers.rs
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/edit.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/event_filter.rs
crates/matrix-sdk-ui/src/timeline/tests/invalid.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs
crates/matrix-sdk/src/event_cache/deduplicator.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/src/event_handler/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/room/reply.rs
crates/matrix-sdk/tests/integration/room/common.rs
testing/matrix-sdk-test/src/event_factory.rs

A few refactorings first around the `TimelineEvent` creation, which was a bit scattered and messy. Then, this patch makes it possible to extract a bundled thread's latest event as a `TimelineEvent`, and store it temporarily in the `TimelineEvent`; it's not persisted, since it's information that could in theory be recovered, and our only use case right now is saving it (the first time we observe it via sync/pagination) in the event cache, so it's sufficient and efficient to do it like this.
This is a followup to #5153, so part of #4869 and #5036.

refactor(sdk): extract a bundled thread's latest event as a `TimelineEvent`

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

Also make it return `Result<bool>` instead of `Result<()>` so we can check if the event was sent.
Add new test for the 'active call' case and adapt the rest to the new return type.
Signed-off-by:

refactor: Add extra logs to Client::send_call_notifications_if_needed

---

benchmarks/benches/linked_chunk.rs
benchmarks/benches/room_bench.rs
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-base/src/event_cache/store/memory_store.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk-common/src/linked_chunk/mod.rs
crates/matrix-sdk-common/src/linked_chunk/relational.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/008_linked_chunk_id.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/tests/integration/timeline/decryption.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
crates/matrix-sdk/src/event_cache/deduplicator.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs
crates/matrix-sdk/tests/integration/room/left.rs

In a "soon" future, threads have their own linked chunk. All our code has been written with the fact that a linked chunk belong to *a room* in mind, so it needs some biggish update. Fortunately, most of the changes are mechanical, so they should be rather easy to review.
Part of #4869, namely #5122.

refactor!(event cache): introduce `LinkedChunkId` in the backends

---

bindings/matrix-sdk-ffi/src/timeline/configuration.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/subscriber.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/threaded_events_loader.rs
crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs

This set of patches introduces options for filtering out threaded messages from the main timelines. In order to do so it:
* moves relation processing from `TimelineAction` to `TimelineMetadata` so that they're available beforehand and can be used in `TimelineStateTransaction::handle_remote_event` and `TimelineState::handle_local_event`
* uses the thread root in the `TimelineStateTransaction::should_add_event_item` and the newly introduced `TimelineState::should_add_event_item`
* adds new `hide_threaded_events` associated values to the `Live` and `Event` focuses so that the old behavior can be kept until clients migrate 
Relates to https://github.com/element-hq/element-meta/issues/2771 and https://github.com/matrix-org/matrix-rust-sdk/issues/4833

timeline: Thread filtering

---

crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs
testing/matrix-sdk-test/src/event_factory.rs

This correctly handles the reply fallback behavior:
- the behavior isn't changed for a live timeline,
- when a timeline is thread-focused, we will extract the `replied_to` field if and only if the thread relation is *not* marked as behaving in a fallback manner.
This makes it possible to distinguish actual in-thread replies.
Part of #4833.

feat(ui): don't mark each thread reply as an actual reply to the previous message, in threaded timelines

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/state_store.rs

Internal Sentry reports tell us that enabling the busy_timeout seems to have *increased* the number of "database is busy" errors, instead of lowering those. As a result, we're going to disable the pragmas in all the places where we enabled it before, and observe how the number of "database is busy" errors evolves.

chore(sqlite): revert the busy_timeout pragmas

---

crates/matrix-sdk/tests/integration/room/joined.rs

They were exceedingly low, especially in the context of code coverage which can be quite slow.
Fixes #5195.

fix(ci): bump the timeout values for `test_subscribe_to_knock_requests`

---

bindings/matrix-sdk-ffi/src/runtime.rs

When file was [moved](https://github.com/matrix-org/matrix-rust-sdk/commit/2a140770a02cbeeaedc8c4dec90de9135aebc679) it looks like an update was missed, since wasm is not in the CI yet.

feat(wasm): Fix cargo runtime on Wasm platforms

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs

This PR makes 2 changes:
1) exposes `ReplyParameters` on `send_location` on the FFI layer so that locations can be sent as replies, or, more importantly, within threads.
2) Updates the definition of what a "live" timeline is on the builder level so that events coming down from /sync are forwarded to threaded timelines.

feat(ffi): pass live events to threaded timelines and allow sending locations in them

---

labs/multiverse/src/main.rs
labs/multiverse/src/widgets/help.rs
labs/multiverse/src/widgets/room_list.rs
labs/multiverse/src/widgets/room_view/mod.rs
labs/multiverse/src/widgets/room_view/timeline.rs

This adds supports for threaded timelines to multiverse, by pressing `Ctrl+T` on a given thread root event. This will be useful for debugging, and understanding how one would use the APIs, for sure. Already noticed #5216 because of this.
Part of #4869.

feat(multiverse): add support for threaded timelines

---

bindings/matrix-sdk-ffi/src/room.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/room/mod.rs

This patch adds optional thread root event id parameters to the drafting functions exposed on the room level allowing unfinished messages to be managed for the main room as well as any inner thread.
Fixes #5223

feat: add thread support to the room message draft facilities

---

crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/room/room_info.rs

This patch changes the strategy of `check_room_upgrades`. Instead of checking all state events in `StateChanges` and throwing an error in case of an invalid state, this patch updates `state_events::sync::dispatch` to filter out invalid state events (specifically `m.room.create` and `m.room.tombstone`), and log the error. That way, the sync doesn't stop and the app can continue working smoothly.
So `check_room_upgrades` is splited into two functions: `is_create_event_valid` and `is_tombstone_event_valid`. It's no longer necessary to detect mergers or splitters because those are _soft errors_, however loops are still critical errors (hence the fact the state events aren't stored nor saved nor applied, and that a log is emitted).
Note: `check_room_upgrades` has been reverted in a previous …

fix(base): Ignore invalid state events instead of throwing an error

---

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs

Looks like a tracing log that I've added during development, that should've been removed at review.

fix(timeline): remove development tracing log in the pinned events loader

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs

Address use of anyhow's error context + use of panic::resume_unwind on wasm targets.

feat(wasm): Address use of errors and panic::resume_unwind for wasm targets

---

crates/matrix-sdk-crypto/src/machine/mod.rs

This is a cut-and-paste of the logic from within a match branch into a separate method: the diff doesn't necessarily make that easy to see but I promise I didn't change anything.
This is purely because I found the existing method too long for me to understand easily, and because I may possibly want to unit test the new method as part of my work.
Preparation for https://github.com/matrix-org/matrix-rust-sdk/issues/4147

refactor(crypto): Extract a method for handling encrypted to-device events

---

crates/matrix-sdk-base/src/event_cache/store/mod.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk/src/authentication/mod.rs

Some of these Box<dyn Error + Send + Sync> are okay, but a few are problematic.
Confirmed this still compiles fine on the fully working wasm tree.

refactor(wasm) Remove some unnecessary wasm32 differentiations

---

crates/matrix-sdk-indexeddb/src/event_cache_store/migrations.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/traits.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/types.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/types.rs

This pull request is part of a series of pull requests to add an IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138). This particular pull request provides (de)serialization functionality for the types defined in #5138.
This change add a few traits to aid in (de)serialization and implements those traits on a relevant types. Furthermore, there is a `struct` for conveniently calling into those (de)serialization traits - i.e., `IndexeddbEventCacheStoreSerializer`.
- `Indexed` - converts high-level types to/from indexed types
- `impl`s:
- `Chunk` ↔ `IndexedChunk`
- `Event` ↔ `IndexedEvent`
- `Gap` ↔ `IndexedGap`
- `IndexedKey` - encodes a key for an indexed type
- `impl`s:
- `Chunk`
- `IndexedChunkIdKey`
- `IndexedNextChunkIdKey`
- `Event`
- `IndexedEventIdKey` …

IndexedDB: Add (de)serialization functionality for `EventCacheStore` backend

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-ui/src/sync_service.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/authentication/oauth/tests.rs
crates/matrix-sdk/src/client/builder/homeserver_config.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/caches.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/tests/integration/media.rs
testing/matrix-sdk-test/src/test_json/api_responses.rs

This PR makes the following changes:
- Refactor `ServerCapabilities` into `ServerInfo`
- It had nothing to do with `/capabilities` and was confusing.
- Include the `/.well-known/matrix/client` response in the `ServerInfo` cache.
- Add `Client::rtc_foci` which uses the cached well-known.
- Add `Client::is_livekit_rtc_supported` to the FFI using the cache RTC foci.
Requires https://github.com/ruma/ruma/pull/2091 before merging

SDK: Cache the RTC foci from the well-known file.

---

bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/lib.rs
bindings/matrix-sdk-ffi/src/qr_code.rs

We have a working implementation of the additional forms of QR Code login of MSC4108. This commit moves the existing code into its own file to make future updates easier to follow.
The additional functionality will eventually see support for:
1) producing a QR code that can be scanned by the existing mechanism.
2) Producing a QR code on a logged out device that can be scanned (for uses on platforms without cameras)
3) Scanning the QR code produced by a logged out device to log it in.
These changes will be fairly substantial, regrouping the existing functionality first seemed like a good pre-step.

Reorganize matrix-sdk-ffi qr_code related functionality into its own file

---

crates/matrix-sdk-crypto/src/store/error.rs

refactor(wasm): Remove special Send/Sync behavior for Wasm on a crypto-store error

---

Cargo.lock
bindings/matrix-sdk-ffi/Cargo.toml
bindings/matrix-sdk-ffi/src/platform.rs

The multi-threaded tokio environment does not work in Wasm, nor does Logging.
`console_error_panic_hook` turns rust panics into JS console statements.

feat(wasm): Adjust platform init on Wasm to avoid tokio environment

---

bindings/matrix-sdk-ffi/src/lib.rs
crates/matrix-sdk-base/src/room/mod.rs
crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs
crates/matrix-sdk/src/widget/machine/driver_req.rs

In response to the review feedback from #5255.
Signed-off-by: Jonas Platte

Some cleanup

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs

Extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/5247.
This patch removes a name ambiguity around _listener_ vs. _subscriber_.
Both terms are used to talk about `RoomEventCacheListener`. We usually
use the term _subscriber_ for the type being returned by a `subscribe`
method. The code refers to this sometimes as listener, sometimes
as subscriber, sometimes both in the same sentence, which can be very
confusing! This patch solves this by using the _subscriber_ term only.
Moreover, the term _listener_ refers to a callback (usually a function) that is
passed to an event-based or reactive system, like we have in `matrix_sdk_ffi`
for example. It's not appropriate here.

chore(sdk): Rename `RoomEventCacheListener` to `RoomEventCacheSubscriber`

---

bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/e2ee/decrypt.rs
crates/matrix-sdk-base/src/response_processors/e2ee/mod.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room/mod.rs

Previously, we held a `TrustRequirement` inside `Client`, and had to wrap it in a `DecryptionSettings` manually a couple of times.
It feels more right to hold on to a `DecryptionSettings` directly. If there were ever some additional settings, most likely we would need them all here.
If I haven't screwed it up, this should not affect behaviour in any way.
Prep for https://github.com/matrix-org/matrix-rust-sdk/issues/4147

refactor(crypto): Hold a DecryptionSettings in base Client

---

bindings/matrix-sdk-ffi/src/client_builder.rs

Features to configure UserAgent, Proxy, Disabling SSL, and additional certificates are not available on Wasm platforms. We remove these configuration options from the FFI layer, while preserving them on non-Wasm platforms.

feat(wasm): Remove network config features from ffi ClientBuilder for Wasm

---

crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs

fix(notification client): request join rules in `required_state` so as to be able to compute them

---

crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/tests/integration/widget.rs

Alternative for https://github.com/matrix-org/matrix-rust-sdk/pull/5201
Ensure that only sender/type/content are exposed to the widgets, and not the crypto-related fields.
Before:
```
{
"type": "my.custom.to.device",
"content": {
"call_id": ""
},
"keys": {
"ed25519": "hk5X9uSb0OwhdAFrlcdtzNkE+AmL/85XdPO5v1Ocgg"
},
"recipient": "@alice:example.org",
"recipient_keys": {
"ed25519": "WgEu0w6T511+R03R4dUQP53d9OQTVJr6F/cYmF3Civs"
},
"sender": "@bob:example.org",
"sender_device_keys": {
"algorithms": [
"m.olm.v1.curve25519-aes-sha2",
"m.megolm.v1.aes-sha2"
],
"device_id": "B0B0B0B0B",
"keys": {
"curve25519:B0B0B0B0B": "Bwl3kZjTnxxKNufqMiG1XoJg1VxGQko5asIy6aq4pUk",
"ed25519:B0B0B0B0B": "hk5X9uSb0OwhdAFrlcdtzNkE+AmLT/85XdPO5v1Ocgg"
},
"signatures": {
"@bob:example.org": {
"ed25519:B0B0B0B0B": …
```

widgets: Throw away crypto related fields of raw decrypted to-device

---

crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-indexeddb/CHANGELOG.md
crates/matrix-sdk-indexeddb/src/crypto_store/migrations/mod.rs
crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v11_to_v12.rs
crates/matrix-sdk-indexeddb/src/crypto_store/migrations/v12_to_v13.rs
crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs

Add a new store to keep track of the information we have received about room key bundles for MSC4268.
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/5107

Indexeddb: support for received room key bundles

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/notification.rs
bindings/matrix-sdk-ffi/src/room/mod.rs
bindings/matrix-sdk-ffi/src/room/room_info.rs
bindings/matrix-sdk-ffi/src/room_preview.rs
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/room/mod.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room_preview.rs
testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs

Returning a default value when the state event is missing is an API footgun. Instead, we should return `None` in this case, and let the caller decide what to do with that.
This would've avoided #5275 in the first place. Likely more changelog lines than code lines here…

refactor(sdk): make methods and fields related to `join_rules` `Option`al

---

bindings/matrix-sdk-ffi/src/room/room_info.rs

The `m.room.power_levels` state event is not part of the room list required state and computing the RoomInfo would fail in that case.

fix(ffi): make `RoomInfo` power levels optional as they can be missing depending on the required state

---

crates/matrix-sdk-indexeddb/src/event_cache_store/error.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/traits.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/types.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/transaction.rs

This pull request is part of a series of pull requests to add an IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226). This particular pull request primarily focuses on providing functionality for easily issuing IndexedDB transaction.
The primary change is the addition of `IndexeddbEventCacheStoreTransaction`, which wraps `IdbTransaction` and `IndexedbEventCacheStoreSerializer`. It provides a convenient interface for composing atomic IndexedDB operations. For the sake of brevity, I have only added the generic versions of the functions for these operations, but as we add implementations of the functions in `EventCacheStore`, I will bring in their typed versions where relevant.
Additionally, in order to support some of the generic functions in …

IndexedDB: Add transaction functionality for `EventCacheStore` backend

---

crates/matrix-sdk/src/sliding_sync/client.rs

Tiny sliding sync cleanup observed while investigating a rageshake.

refactor(sliding sync): avoid an unwrap by inlining a function into its own caller

---

crates/matrix-sdk-crypto/src/store/crypto_store_wrapper.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk-crypto/src/store/types.rs
crates/matrix-sdk-crypto/src/types/events/room_key_bundle.rs
crates/matrix-sdk/src/encryption/mod.rs
crates/matrix-sdk/src/room/shared_room_history.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee/shared_history.rs

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4926.
This PR doesn't yet handle room key bundles received out of order. It is rather the building block which will notify us that we need to consider that a bundle might have arrived out of order.

Add a stream that notifies us about received room key bundles

---

bindings/matrix-sdk-ffi/src/widget.rs

The latest mobile designs for Element Call have it displaying the room name in an "app bar". So the Element Call widget will soon start requesting the capability to learn the room name, and the SDK should auto-approve this capability.

feat(widget): Allow Element Call to learn the room name

---

crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-common/CHANGELOG.md
crates/matrix-sdk-common/src/lib.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/event_cache/mod.rs

It avoids using different versions in several places for consistency. It also allows to be able to change it in a single place when needed.
This also bumps the fallback to v11 everywhere, since it is the default version for new rooms since Matrix 1.14 and it has the sanest redaction rules.

refactor(common): Use a constant for the room version to use as a fallback

---

crates/matrix-sdk/src/event_cache/room/events.rs

What it says on the tin. I'll never learn the rules around `if cfg!`.

fix(sdk): use a cfg guard instead of `if cfg!` to avoid build failures on !test && !debug_assertions builds

---

crates/matrix-sdk-ui/src/timeline/builder.rs
crates/matrix-sdk-ui/src/timeline/controller/decryption_retry_task.rs
crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/src/timeline/subscriber.rs
crates/matrix-sdk-ui/src/timeline/tasks.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs

There were three different APIs for a `TimelineFocus`, before this PR:
- `TimelineFocus`, which is the public API to be used when building a `Timeline`
- `TimelineFocusKind`, which is a simplified view of the focus of a timeline, used in misc places to make some lightweight decisions
- `TimelineFocusData`, which includes some (inner) mutable data to make useful changes to a timeline: pagination, etc.
This PR unifies the latter two into a single type, that's eventually renamed `TimelineFocusKind`. I find it makes it simpler to understand the different choices, and I even think this might lead to more simplifications later.

refactor(timeline): simplify the concept of "focus" and refactor building

---

crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks/encryption.rs
crates/matrix-sdk/src/widget/machine/driver_req.rs
crates/matrix-sdk/src/widget/machine/from_widget.rs
crates/matrix-sdk/src/widget/machine/incoming.rs
crates/matrix-sdk/src/widget/machine/mod.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/src/widget/mod.rs
crates/matrix-sdk/tests/integration/widget.rs

Adds the capability for widgets to send encrytped to-device messages properly.
It is getting rid of the old encrypted boolean that was used by widget to request encryption. As said by the base MSC
for widget send/receive messages: Widgets should not be aware of encryption.
If the widget is in an encrytped room then to-device traffic will be encrypted.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/4859
Signed-off-by:

feat(widget): Send custom to-device messages in widgets in e2ee rooms

---

crates/matrix-sdk/src/encryption/tasks.rs

The whole module is behind a e2e-encryption feature guard, so those individual ones in the module are not useful.

refactor: Remove some useless cfg guards

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs
bindings/matrix-sdk-ffi/src/timeline/reply.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/event_item/content/reply.rs
crates/matrix-sdk-ui/tests/integration/timeline/replies.rs

These are available in normal timeline items. Having them on embedded items, too, allows clients to render them (timestamp) or use them for further operations (event ID).

feat(timeline): expose timestamp & identifier on embedded events

---

crates/matrix-sdk-ui/src/timeline/pinned_events_loader.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache.rs
crates/matrix-sdk/tests/integration/room/common.rs

This patch introduces a new method named `RoomEventCache::rfind_event_in_memory_by` to look for an in-memory event, starting from the most recent event, by applying a predicate closure on each event.
Because this method's name has the pattern `find_event*_by`, this patch is also renaming `event` to `find_event_by_id` and `event_with_relations` to `find_event_by_id_with_relations`. I think it is mandatory and it's more Rust idiomatic as it follows the standard library namings. Those methods are no more getters, but methods going over an iterator. Proof is: `RoomEventCache::event` was entirely using `RoomEventCacheState::find_event` (this last naming was correct!).

feat(sdk): `Add RoomEventCache::rfind_event_in_memory_by`

---

benchmarks/benches/room_bench.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk-base/src/room/latest_event.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/room/tags.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/test_utils.rs
crates/matrix-sdk-ui/CHANGELOG.md
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/read_receipts.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs

This series of patches introduce proper threading support for sending read receipts and computing room unread counts.
They add a new, client wide, `threads_enabled` feature flag which overtake the old `TimelineFocus:: hide_threaded_events`.
If this feature flag is turned on then the timelines will automatically send [the correct read receipt](https://spec.matrix.org/latest/client-server-api/#threaded-read-receipts) when invoked through the existing `send_read_receipt`/`send_single_receipt`/ method.
The base SDK's read receipts handler will also start ignoring threaded messages when computing room unread counts. A room will be unread only if there are new messages in its main timeline.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3123

feat(sdk): send threaded read receipts

---

Cargo.lock
Cargo.toml

It seems that some `m.room.topic` events in the wild have the wrong format for the `m.topic` field (https://github.com/matrix-org/matrix-js-sdk/issues/4902). Since this field was stabilized recently in Ruma, deserializing these events now fails. We added a feature to ignore this field if its deserialization fails.
Thanks to @stefanceriu for reporting this to me.

Upgrade Ruma (again)

---

README.md

This patch fixes the markup in the `README.md` file. Links were broken because of the mix of HTML and Markdown. Plus, the HTML markup was kind of incorrect (`<i>` instead of `<em>`). Plus, too much `<br />`, most of them were “collapsed” automatically.

doc: Fix markup in `README.md`

---

Cargo.lock
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs

I think that this is necessary to make #5322 somewhat secure.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/4926.

feat(base): Remember when a user accepts an invite

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs

Another test that I was pretty sure would fail. I was *not* wrong.

fix(timeline): reload the related events for the initial thread events

---

crates/matrix-sdk-crypto/src/machine/mod.rs

When using this function, whether encryption keys are dropped depends on the crypto store implementation used.
Signed-off-by: Tobias Fella <tobias.fella@kde.org>

docs(crypto): Remove wrong statement about encryption keys for OlmMachine::with_store

---

crates/matrix-sdk/src/sliding_sync/mod.rs

doc(sdk): Fix a typo in `SlidingSyncInner::network_timeout`

---

crates/matrix-sdk-indexeddb/src/event_cache_store/builder.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/error.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/transaction.rs
crates/matrix-sdk-indexeddb/src/serializer.rs

This pull request is part of a series of pull requests to add a full IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226, #5274). This particular pull request focuses on providing implementations of a few `EventCacheStore` functions.
The primary change is the addition of a top-level type, `IndexeddbEventCacheStore`, as well as a way of constructing this type through `IndexeddbEventCacheStoreBuilder`. Additionally, `IndexeddbEventCacheStore` also provides an implementation of `EventCacheStore`.
In order to limit the size of this pull request, the implementation of `EventCacheStore` is almost entirely delegated to a nested `MemoryStore` except for the following two functions, which have a genuine IndexedDB implementation.
- …

IndexedDB: Add initial implementation of `EventCacheStore`

---

crates/matrix-sdk-sqlite/src/event_cache_store.rs

No functional changes, only a code move. Makes rustfmt kick in as it seemed to have trouble with the deeply nested structure.

refactor(sqlite): Move the transaction in find_event_relations into a function

---

crates/matrix-sdk/CHANGELOG.md

A bunch of methods were removed in #5250, sadly this wasn't documented in the changelog.

chore: Add a missing changelog entry for PR #5250

---

crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/refresh_token.rs

Change test_login_username_refresh_token to use MatrixMockServer.
Add builders for configurable reesponses for mock login endpoint.
Signed-off-by: 
Shrey Patel <shreyp@element.io>

Fix issue #5366

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs

With this PR the FFI's API now matches the SDK and as such allows for checks to be made on the built `Client` before proceeding to log in.
Hopefully the docs make sense, please make any suggestions if they are unclear.

FFI: Refactor ClientBuilder::build_with_qr_code into Client::login_with_qr_code

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/room/mod.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs
crates/matrix-sdk/src/client/mod.rs

Another PR that is a prerequisite of #5322.
Par of https://github.com/matrix-org/matrix-rust-sdk/issues/4926.

feat(base): Remember the inviter if we accept an invite

---

crates/matrix-sdk-common/src/tracing_timer.rs
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-sqlite/src/lib.rs

Until now, `SqliteEventCacheStore` manages a pool of connections. A connection is fetched from this pool and operations are executed on it, regardless whether these are read operations or write operations.
We are seeing more and more _database is busy_ errors. We believe this is because too many write operations are executed concurrently.
The solution to solve this is to use multiple connections for read operations, and a single connection for write operations. That way, concurrent writings are no longer a thing, and we hope it will reduce the number of _database is busy_ errors to zero. That's our guess.
This patch does that. When the pool of connections is created, a connection is elected as the `write_connection`. To get a connection for read operations, one has to use the new …

feat(sqlite): `SqliteEventCacheStore` has 1 write connection

---

crates/matrix-sdk/src/sliding_sync/mod.rs

What it says on the tin, again.

feat(sdk): Add more logs around `pos` lock in sliding sync

---

crates/matrix-sdk-indexeddb/src/event_cache_store/error.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/transaction.rs

This pull request is part of a series of pull requests to add a full IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226, #5274, #5343). This particular pull request focuses on providing an implementation of `EventCacheStore::load_last_chunk`.
The primary change is the addition of `EventCacheStore::load_last_chunk`, as well as tests for ensuring this is functioning correctly.
There are also a number of additions to `IndexeddbEventCacheStoreTransaction` which support the implementation of `EventCacheStore::load_last_chunk`.
- `get_chunk_by_next_chunk_id`
- `get_chunks_count_in_room`
- `get_max_chunk_id`
These are simply typed wrappers around the generic functions in `IndexeddbEventCacheStoreTransaction`.
- Add remaining implementations of …

IndexedDB: Add IndexedDB implementation of `EventCacheStore::load_last_chunk`

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs

Currently, each time `Client.url_for_oidc` is called, a new device ID is generated as `OAuth.login` is passed `None` as the `device_id` parameter.
This closes #5392.
Signed-off-by: fl0lli <github@fl0lli.de>

FFI: Pass existing device ID to url_for_oidc

---

crates/matrix-sdk/src/sliding_sync/mod.rs

As discussed in the [dev room](https://matrix.to/#/#matrix-rust-sdk-dev:flipdot.org), don't log so much data at DEBUG level.
I left in a small `debug` message since it seems like it might be helpful, but made the response dump be TRACE.

task(sliding_sync): Avoid logging the entire sliding sync response at the DEBUG level

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-crypto/src/types/events/room_key_withheld.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/pinned_event.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/account.rs
crates/matrix-sdk/src/encryption/recovery/mod.rs
crates/matrix-sdk/src/encryption/recovery/types.rs
crates/matrix-sdk/src/encryption/secret_storage/mod.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/tests/integration/event_cache/threads.rs

This will allow to have a slightly smaller diff when bumping Ruma.
It also adds `Account::fetch_account_data_static()` to allow to fetch account data using a statically-known type.
This can be reviewed commit by commit. The commit messages have more details about what is happening.

refactor: Clean up some uses of `Raw`.

---

benchmarks/benches/linked_chunk.rs
crates/matrix-sdk-sqlite/migrations/event_cache_store/008_linked_chunk_id.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs

This patch changes the query used by `SqliteEventCacheStore::load_all_chunks_metadata`. It was the cause of severe slowness (see https://github.com/matrix-org/matrix-rust-sdk/pull/5407). The new query improves the throughput by +1140% and the time by -91.916%.
This query will visit all chunks of a linked chunk with ID `hashed_linked_chunk_id`. For each chunk, it collects its ID (`ChunkIdentifier`), previous chunk, next chunk, and number of events (`num_events`). If it's a gap, `num_events` is equal to 0, otherwise it counts the number of events in `event_chunks` where `event_chunks.chunk_id = linked_chunks.id`.
Why not using a `(LEFT) JOIN` + `COUNT`? Because for gaps, the entire `event_chunks` will be traversed every time to always count zero events (a gap has no event). It's extremely …

feat(sqlite): Improve throughput of `SqliteEventCacheStore::load_all_chunks_metadata` by 1140%

---

contrib/ide/vscode/settings.json

Clippy is a bit too heavy to be used as the check on save command in this repo.
Let's set a better default.

contrib: Set our check command to check instead of clippy

---

benchmarks/Cargo.toml
benchmarks/benches/event_cache.rs
crates/matrix-sdk-base/src/event_cache/store/traits.rs
crates/matrix-sdk/src/event_cache/mod.rs

Each sync update contains N rooms (for N in 1, 10, 100), each gets 1000 new room message (text) events. We might want to do something more representative, as we've done in other benchmarks (throw a few aggregated events in the mix), but for now that'll be sufficient, and it's already teaching us things, notably that the supposed performance improvement in #5426 isn't the obvious improvement I thought it would be. More investigation is needed there, so in the meantime I'll just add a comment that it's not as good as it was supposed to be.

bench(event cache): add a benchmark for measuring how long it takes to handle a sync update

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/client.rs

`Client::get_url` is there for SDK consumers to be able to use the existing HTTP stack (configuration and all) however in practice it was a bit weird:
- Responses came back as strings limiting the types of resource that could be fetched (as well as requiring the string to be converted back to data before handed to a JSON decoder).
- HTTP errors weren't being raised and instead you would find the (e.g. 404) error response in the `Ok` case.
This PR fixes both of these issues.

FFI: Update `Client::get_url` to return raw data and to throw on HTTP errors.

---

bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/config/request.rs
crates/matrix-sdk/src/http_client/native.rs
crates/matrix-sdk/src/media.rs

Having the `read_timeout` value set allows us to have long network requests that will get cancelled automatically when no data is received for a certain amount of time.
If we combine it with being able to remove the existing default `timeout` value for some requests, it would fix the issue with downloading large files in poor network connectivity scenarios where the download would just cancel automatically after the timeout (30s) was reached.
Signed-off-by:

refactor: Add `read_timeout` for HTTP requests, make `timeout` optional

---

crates/matrix-sdk-indexeddb/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/types.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/transaction.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/types.rs

This pull request is part of a series of pull requests to add a full IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226, #5274, #5343, #5384, #5406). This particular pull request focuses on providing implementations for the `Event`-related functions in `EventCacheStore`.
The changes include implementations of the following functions, as well as tests for each of them.
- `EventCacheStore::filter_duplicated_events`
- `EventCacheStore::find_event`
- `EventCacheStore::find_event_relations`
- `EventCacheStore::save_event`
I have also added a few other functions which support the implementation of the functions above.
- `IndexedEventRelationKey::set_related_event`
- `IndexeddbEventCacheStoreTransaction::get_event_by_id`
- …

feat(indexeddb): implement `Event`-related functions in `EventCacheStore`

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/error.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/joined.rs

Made the ```Room.leave``` function recursive to leave predecessor rooms. Also added an integration test to check this.  
Signed-off-by: Shrey Patel shreyp@element.io

Fix for issue #5381: Leaving room leaves predecessors 

---

bindings/matrix-sdk-ffi/src/widget.rs

For clients which integrate Element Call: Currently matrix-rust-sdk is responsible for sending the call notification event when joining MatrixRTC sessions, but this is planned to be changed soon. As of the upcoming Element Call 0.14.0 release, it will request the capability to send call notifications itself, and we should auto-approve this capability.

Allow Element Call to send call notifications

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room/mod.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/mod.rs
crates/matrix-sdk/tests/integration/room/thread.rs
labs/multiverse/src/widgets/room_view/input.rs
labs/multiverse/src/widgets/room_view/mod.rs
labs/multiverse/src/widgets/status.rs

This implements the three new endpoints introduced by [MSC4306](https://github.com/matrix-org/matrix-spec-proposals/pull/4306), with tests and support in multiverse.
Depends on https://github.com/ruma/ruma/pull/2169 and https://github.com/element-hq/synapse/pull/18722.
Part of #4869.

feat(sdk): add support for thread subscription endpoints (MSC4306)

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room/room_info.rs
crates/matrix-sdk-base/src/room/mod.rs

- Exposes the room version in the FFI RoomInfo.
- Exposes the `privileged_creators_role` boolean in the FFI RoomInfo, to understand how the retrieved creators ids should be treated.
This is needed on the clients so we can understand whether `RoomInfo.creators` are the ids of the room creators (with no special privileges) or they're users with infinite power level and should be treated differently.
Signed-off-by:

refactor(ffi): expose room_version in the FFI RoomInfo

---

.github/workflows/benchmarks.yml
Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
benchmarks/benches/crypto_bench.rs
benchmarks/benches/event_cache.rs
benchmarks/benches/linked_chunk.rs
benchmarks/benches/room_bench.rs
benchmarks/benches/store_bench.rs
benchmarks/benches/timeline.rs

This sadly removes our ability to create flamegraphs locally due to the usage of a fork of criterion.
Codspeed by default generates those for us, so it might not be that bad. But if needs be we might investigate how to get them back locally as well.
Some of our benchmarks seem to panic when run, so I'm only enabling a couple of benchmarks for now.
Closes: https://github.com/matrix-org/matrix-rust-sdk/issues/5417.

Enable benchmarks on the CI

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/room/mod.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/widget/settings/element_call.rs
crates/matrix-sdk/tests/integration/room/joined.rs

See the commits for details. Element Call now provides a `sendNotificationType` URL parameter which we can use to tell it to send a call notification, so we no longer need the `Room::send_call_notification_if_needed` method provided by this SDK.

Expose Element Call's new mechanism for sending call notifications

---

bindings/matrix-sdk-ffi/src/room/mod.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/migrations.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/migrations/state_store/011_thread_subscriptions.sql
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/tests/integration/room/thread.rs
labs/multiverse/src/widgets/room_view/mod.rs

Some implementation notes:
- instead of using kvdata (`StateStoreDataKey` et al.), I've added a new table for the thread subscriptions, so we can later do queries like "where status is subscribed".
- I've made it so that unsubscribing is remembered on the local device, so the next attempt to fetch a thread subscription may return unsubscribed. The MSC should soon evolve in that direction, in such a way that a thread status can be unsubscribed on the server as well, so I'm just being a bit early here.

feat: store the thread subscription status in the database

---

crates/matrix-sdk-sqlite/src/state_store.rs

In this [commit](https://github.com/matrix-org/matrix-rust-sdk/commit/339b220488b7c3bc387b9c89fef064bd4bb6fab7#diff-7f0f467e2238b53105e2ce5eadf1e7eff8ac3f635ae6bf16dc93a8b1f36d4d2dL121) `open_with_pool` was changed from public to private.
I'm using this part in my project to share one sql database between my application and the matrix sdk.
If that change from public to private was intentional and you have suggestions how i should solve this i'd love to hear it.
Signed-off-by: Jakob Lachermeier jakob.lachermeier@posteo.de

fix(sqlite): made `open_with_pool` public again.

---

bindings/matrix-sdk-ffi/src/client.rs
crates/matrix-sdk-base/src/store/send_queue.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk/src/http_client/mod.rs
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/src/send_queue/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This contains the send queue changes broken out from #5008.

feat(send_queue): report progress for media uploads

---

crates/matrix-sdk-base/src/response_processors/state_events.rs

The `m.room.create` event contains at lot of important information for a room, like its type (i.e. whether it is a space), its version and its creator(s) (which are important in room version 12). So ignoring the event completely might break a room.
Instead what we do here is simply ignore the `predecessor` field if it is considered invalid, allowing us to access the other fields.
In the process, this also adds a bug fix, where the content of a redacted create event was not validated, although it still contains the same fields.

refactor(base): Don't drop whole `m.room.create` if `predecessor` is invalid

---

xtask/src/kotlin.rs

We use `cargo ndk -p {package_name}`, where `-p` is short for `--package`. However, `cargo ndk` has introduced the `-p` option (see https://github.com/bbqsrc/cargo-ndk/commit/c6b93a89a2723ff0fac99b5ac86ae6636a6cf54a), short for `--platform`. It creates a confusion and the command line doesn't execute properly. Let's use the long option `--package` to clarify everything.

fix(xtask): Use `--package` instead of `-p` on `cargo ndk`

---

crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs
crates/matrix-sdk/src/room/mod.rs

With this missing in the `SlidingSync` instance created for the notification client, power levels couldn't be computed, and some push rules didn't take effect for notifications.
Should fix https://github.com/matrix-org/matrix-rust-sdk/issues/5485 (https://github.com/element-hq/element-x-android/issues/5113 being the original report on the EXA repo) and the equivalent issue on iOS of `@room` and call notifications being filtered out because they didn't match any push rules.
Kudos to @zecakeh for his help on debugging the issue.
Signed-off-by:

fix(notification_client): Add `m.room.create` to the required sliding sync state

---

Cargo.toml
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/sync.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/event_handler/mod.rs
crates/matrix-sdk/src/widget/matrix.rs
crates/matrix-sdk/tests/integration/client.rs
testing/matrix-sdk-test/src/sync_builder/joined_room.rs
testing/matrix-sdk-test/src/sync_builder/mod.rs

It is supposed to be an improvement over `state`, since it allows the
server to send updates to the state that might not be reflected in the
timeline.
This is also the same behavior as in Simplified Sliding Sync.
This is MSC4222 that was accepted and is about to get merged in the spec.

feat(sdk): Use `state_after` in sync v2 

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/src/client_builder.rs
bindings/matrix-sdk-ffi/src/room/mod.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk-base/src/response_processors/notification.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/thread.rs
labs/multiverse/src/widgets/room_view/mod.rs
testing/matrix-sdk-test/src/event_factory.rs

- Updates to the new subscription request, that includes the ID of the event that triggered an automatic subscription.
- Get rid of the "unsubscribed" thread status. Technically a breaking change, but since this is all very experimental and shouldn't have shipped yet, I will likely not do a DB migration for it.
- Updates to Ruma's async evaluation of push rules, that's going to be needed to evaluate the thread subscription push rule
- Fetch the thread subscription status when evaluating thread-related event push conditions.
Part of #4869. Depends on https://github.com/ruma/ruma/pull/2180

refactor(threads): add support for MSC4306 latest changes and push rules

---

crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk/src/notification_settings/mod.rs
crates/matrix-sdk/tests/integration/encryption/backups.rs
testing/matrix-sdk-test/src/lib.rs

Let's you use `?` in tests (only on `Result`s, not `Option`s unfortunately). Error backtrace will point to the (first line of the) expression being `?`ed. Pretty close to `.unwrap()`!
Signed-off-by: Jonas Platte

Introduce TestResult and use it in a couple random places

---

crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/encryption/futures.rs
crates/matrix-sdk/src/send_queue/mod.rs

Signed-off-by: multi multiestunhappydev@gmail.com
Fixes #5465

refactor(client): have `upload_encrypted_file` own the `Client` instance

---

crates/matrix-sdk-base/src/response_processors/notification.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs

It is already in the `PushConditionRoomCtx`, so we don't need an extra argument for it.

refactor(base): Don't take room ID in `Notification::push_notification_from_event_if`

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/sender_data.rs
crates/matrix-sdk-crypto/src/store/mod.rs
crates/matrix-sdk/src/room/shared_room_history.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee/shared_history.rs

This closes: https://github.com/matrix-org/matrix-rust-sdk/issues/5139.
The solution is a bit different from what #5139 describes, here we do the check before we accept the bundle, not before we download it.
This is done to avoid the duplication the Rust implementation and js-sdk implementation of shared historic bundles would need to do in case the check is done before the download. Furthermore it makes for a simpler API, implementers can't accidentally forgot to do this check.

Check the sender data before we accept historic room key bundles

---

crates/matrix-sdk/CHANGELOG.md

The link for an entry was wrong. It's #5439, not #5442.

doc(sdk): Fix `CHANGELOG.md` entry

---

crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/encryption.rs
crates/matrix-sdk-ui/src/timeline/tests/mod.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/traits.rs

Part of the work on https://github.com/matrix-org/matrix-rust-sdk/issues/5474
This should help us (in future changes) to call into the decryptor thread from code that adds events to the timeline.

refactor(timeline): Make RoomDataProvider provide Decryptor to simplify redecryption

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs

Now that the we media upload progress in the timeline, thanks to @Johennes, we can remove the legacy support, so as to make the API less confusing (before, one could use a `progress_watcher` *and* enable the send queue media upload progress at the same time, and it wasn't clear how these two API would interact / which would be enabled).
Also always use the send queue for media uploads, as it's generally better, stable (after months in production in the EX apps).

refactor!(ffi): always use the send queue and remove legacy media upload progress

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs

This switches from `filename: String` to `source: UploadSource` for gallery uploads which enables using bytes directly (which is already possible for normal media uploads).
See also https://github.com/matrix-org/matrix-rust-sdk/pull/5530.

feat(ffi): allow specifying gallery items using UploadSource

---

bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/timeline/mod.rs

This partially relates to #5529 and allows using bytes for thumbnails through the use of `UploadSource` which is already used for the main file.

feat(ffi): allow specifying thumbnails using UploadSource

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-common/Cargo.toml
crates/matrix-sdk-common/src/executor.rs
crates/matrix-sdk-common/src/lib.rs
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-crypto/src/lib.rs
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk-sqlite/src/lib.rs
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/lib.rs
crates/matrix-sdk-ui/tests/integration/main.rs
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/lib.rs
crates/matrix-sdk/tests/integration/main.rs
testing/matrix-sdk-integration-testing/Cargo.toml
testing/matrix-sdk-integration-testing/src/lib.rs
testing/matrix-sdk-test-utils/Cargo.toml
testing/matrix-sdk-test-utils/README.md
testing/matrix-sdk-test-utils/src/lib.rs
testing/matrix-sdk-test/src/lib.rs

This PR allows `init_tracing_for_test` to be called by any other crate in the sdk
Signed-off-by: multi [multiestunhappydev@gmail.com](mailto:multiestunhappydev@gmail.com)
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/5292

feat(test): add a test utils crate to make log initialization possible everywhere

---

crates/matrix-sdk-ui/src/timeline/controller/read_receipts.rs
crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs

This patch updates the Timeline Controller's `handle_explicit_read_receipts` method to also consider unthreaded read receipts on **threaded** **main** timelines when calculating timeline items states and adds a test for it.
This picks up from #5442 and fixes https://github.com/matrix-org/matrix-rust-sdk/issues/5440

feat(timeline): consider unthreaded read receipts for `ReceiptThread::Main` timelines when computing timeline items states.

---

bindings/matrix-sdk-crypto-ffi/src/machine.rs
crates/matrix-sdk-base/src/event_cache/store/integration_tests.rs
crates/matrix-sdk-common/CHANGELOG.md
crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk/src/test_utils/mod.rs

feat: Change type of `DecryptedRoomEvent::event` to `Raw<AnyTimelineEvent>`

---

Cargo.lock
crates/matrix-sdk/src/client/mod.rs

Likely a fallout of a race merging two PRs (a ruma bump + the introduction of the ruma-signatures usage).

chore: check in the updated compatible ruma version

---

crates/matrix-sdk-ui/tests/integration/timeline/focus_event.rs
crates/matrix-sdk-ui/tests/integration/timeline/pagination.rs
crates/matrix-sdk-ui/tests/integration/timeline/profiles.rs
crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
crates/matrix-sdk-ui/tests/integration/timeline/subscribe.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/config/mod.rs
crates/matrix-sdk/src/config/sync.rs
crates/matrix-sdk/src/sync.rs
crates/matrix-sdk/tests/integration/client.rs
crates/matrix-sdk/tests/integration/notification.rs
crates/matrix-sdk/tests/integration/room/beacon/mod.rs
crates/matrix-sdk/tests/integration/room/beacon_info/mod.rs
crates/matrix-sdk/tests/integration/room/common.rs
crates/matrix-sdk/tests/integration/room/tags.rs

Fixes #1835.
Introduces a new `SyncToken` enum for the `SyncSettings::token` field.
The enum has 3 variants: ReusePrevious (default), NoToken, Specific(String).
Some tests were changed to use the old default (NoToken).
Signed-off-by: Shrey Patel shreyp@element.io

fix(sdk): `Client::sync_once` defaults to reuse previous token

---

crates/matrix-sdk-crypto/CHANGELOG.md
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-crypto/src/machine/tests/room_settings.rs
crates/matrix-sdk-crypto/src/store/types.rs

feat(crypto): Add RoomSettings::encrypt_state_events

---

.github/workflows/ci.yml
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-common/Cargo.toml
crates/matrix-sdk-crypto/Cargo.toml
crates/matrix-sdk-crypto/src/store/integration_tests.rs
crates/matrix-sdk-sqlite/Cargo.toml
crates/matrix-sdk/Cargo.toml
xtask/src/ci.rs

This PR makes some non-domain-specific changes across multiple crates that are required for proper testing of features implemented for #5397.
* Adds a `experimental-encrypted-state-events` feature flag across the SDK.
* Introduces a feature set into xtask to ensure feature-gated tests are run during CI.
* Minor fix to a test that would otherwise fail with the newly introduced CI.

feat: Experimental encrypted state feature flag with CI support

---

crates/matrix-sdk-common/src/deserialized_responses.rs
crates/matrix-sdk-crypto/src/error.rs
crates/matrix-sdk-crypto/src/gossiping/machine.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk-crypto/src/machine/tests/mod.rs
crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
crates/matrix-sdk-crypto/src/session_manager/group_sessions/mod.rs
crates/matrix-sdk-crypto/src/types/events/room/mod.rs

Depends on #5511, #5512 and #5523.

feat(crypto): Add support for encrypted state events to `matrix-sdk-crypto`

---

.github/workflows/coverage.yml

This frees 13 GB of disk space in the Codecov image runner, by getting rid of tools, binaries and libs we're not interested in.
These tools have been identified thanks to the new lines added to detect large files, e.g. `du -hsc /usr/local/bin/* | sort -h`:
- `du -hsc /usr/local/bin/*` will output a summary of the size, in human size format, of every top-level entry in `/usr/local/bin`
- `sort -h` will sort from smallest to largest, in the human size format too
[Example](https://github.com/matrix-org/matrix-rust-sdk/actions/runs/17067856858/job/48389222421#step:4:89).
This idea courtesy of apache/arrow, which has a [script](https://github.com/apache/arrow/blob/main/ci/scripts/util_free_space.sh) to remove such unused space (but many binaries seem to not be present in our image at start, so …

fix(ci): free more space in the CI runner for the `codecov` task

---

crates/matrix-sdk/src/notification_settings/mod.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/room/thread.rs

This adds a large integration test, that will exhaustively check all our notification modes, and how they relate to thread subscriptions:
- for each interesting global notification behavior (all messages / mentions only),
- for each interesting room notification behavior (all messages / mentions only / mute),
Look if a subscribed thread will trigger a mention or not.
There are a few false-negatives, which motivated https://github.com/matrix-org/matrix-spec-proposals/pull/4306/commits/bd9e842fee4de0e97c35f3958c3386757af0a57e in the spec. This PR will make it possible to check that these cases have been fixed, after implementing the new behavior from that spec update.
Part of #5038.

test(threads): add tests for checking the push rule behavior with respect to threads subscriptions

---

crates/matrix-sdk/src/media.rs

Using `Option::None` will just make `reqwest` use the default `Client`'s timeout value, instead of setting an infinite timeout value. Using `Some(Duration::MAX)` should achieve the desired behaviour instead.
Fixes https://github.com/element-hq/element-x-ios/issues/4437.
Signed-off-by:

fix(media): Use the right value to get no timeouts when downloading media

---

benchmarks/benches/event_cache.rs

Does what it says on the tin. Split from the performance fix, so we can get some initial numbers on the CI bench runs too. 
Part of investigating https://github.com/matrix-org/matrix-rust-sdk/issues/5572

bench: add a benchmark for finding related events

---

crates/matrix-sdk-sqlite/migrations/event_cache_store/009_related_event_index.sql
crates/matrix-sdk-sqlite/src/event_cache_store.rs
crates/matrix-sdk-ui/tests/integration/timeline/thread.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/event_cache/room/mod.rs
crates/matrix-sdk/tests/integration/event_cache/threads.rs

This adds indexes to make finding related events faster, on top of #5578.
The speedup factor is a function of the number of events in the DB, so with the updated benchmark from #5578, at this very precise moment, this gives me the following numbers:
```
Gnuplot not found, using plotters backend
Event cache room updates/Event cache find_event_relations[SQLite]/10 events, #no filter
time:   [338.94 µs 352.31 µs 375.31 µs]
thrpt:  [26.645 Kelem/s 28.384 Kelem/s 29.504 Kelem/s]
change:
time:   [-78.035% -75.984% -73.825%] (p = 0.00 < 0.05)
thrpt:  [+282.04% +316.39% +355.28%]
Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
Event cache room updates/Event cache find_event_relations[SQLite]/10 events, edits filter
time:   [350.26 µs 361.38 µs 373.78 …
```

feat(event cache): find related events faster

---

crates/matrix-sdk-indexeddb/src/event_cache_store/builder.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/integration_tests.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/migrations.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/types.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/transaction.rs
crates/matrix-sdk-indexeddb/src/serializer.rs

This pull request is part of a series of pull requests to add a full IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226, #5274, #5343, #5384, #5406, #5414, #5497, #5506, #5540). This particular pull request adds a `MemoryStore`-backed implementation of `EventCacheStoreMedia`, as well as, IndexedDB-backed implementations for `MediaRetentionPolicy`-related functions.
The overarching change adds a `MemoryStore`-backed implementation of `EventCacheStoreMedia` for `IndexeddbEventCacheStore`. Furthermore, the implementation of `EventCacheStore` now delegates to the implementation of `EventCacheStoreMedia` via a `MediaService` nested in `IndexeddbEventCacheStore`.
Additionally, there are now implementations and tests for the following `EventCacheStoreMedia` …

IndexedDB: Add implementation of `MediaRetentionPolicy`-related functions in `EventCacheStoreMedia`

---

crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/room/sync_v2.rs
crates/matrix-sdk-base/src/response_processors/state_events.rs
crates/matrix-sdk-ui/Cargo.toml
crates/matrix-sdk-ui/src/notification_client.rs
crates/matrix-sdk-ui/src/timeline/traits.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/test_utils/mod.rs
crates/matrix-sdk/tests/integration/client.rs
testing/matrix-sdk-integration-testing/Cargo.toml
testing/matrix-sdk-integration-testing/src/tests/e2ee/mod.rs
testing/matrix-sdk-integration-testing/src/tests/e2ee/state_events.rs

Implements support for decryption of state events. Needs #5545.

feat: Add top-level support for decrypting state events

---

crates/matrix-sdk-base/src/store/integration_tests.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk/src/encryption/mod.rs

Since the server will reject any duplicate one-time keys forever, clients which encounter such an error will spam sentry with such reports.
This patch ensures that we only send the sentry report once.

fix: Only report duplicate one-time key errors once

---

crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/room/latest_event.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-base/src/store/migration_helpers.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/latest_events/latest_event.rs
crates/matrix-sdk/src/latest_events/mod.rs

This set of patches make the `LatestEventValue` persistent by:
- setting it in `RoomInfo`,
- persisting the `RoomInfo` in the `StateStore`,
- emitting a `RoomInfoNotableUpdateReasons::LATEST_EVENT`.
---

feat(sdk,base): Introduce the new `LatestEvents` API, part 5: Make it persistent

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/src/room/call.rs
crates/matrix-sdk-ui/tests/integration/notification_client.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/client.rs
crates/matrix-sdk/tests/integration/event_cache/threads.rs
crates/matrix-sdk/tests/integration/room/thread.rs
crates/matrix-sdk/tests/integration/send_queue.rs

This bumps Ruma (to an unstable branch, because we need https://github.com/ruma/ruma/pull/2200 for tests, duh), which brings us a few documented test fixes.
In addition to this, this implements the support for the companion endpoint of MSC4308, which allows to back-paginate thread subscriptions, if the sync response contained only a small subset of the entire change set.
Part of #5038.

feat(threads): implement msc4308 companion endpoint

---

labs/README.md

Document `--proxy` option in the `multiverse` client to be able to inspect network requests flying around as you interact.
Spawning from https://github.com/matrix-org/matrix-rust-sdk/issues/5600#issuecomment-3238128112 as pointed out by @poljar 
Signed-off-by: erice@element.io

Document `--proxy` option in the `multiverse` client to inspect network requests

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/store/memory_store.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk-base/src/store/traits.rs
crates/matrix-sdk-indexeddb/src/state_store/mod.rs
crates/matrix-sdk-sqlite/src/state_store.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk/src/client/builder/mod.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/src/client/thread_subscriptions.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/sliding_sync/builder.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sliding_sync/mod.rs
crates/matrix-sdk/src/test_utils/mocks/mod.rs
crates/matrix-sdk/tests/integration/client.rs
labs/multiverse/src/widgets/room_view/mod.rs

This adds support for:
- msc4308 sliding sync extension: receiving new changes to thread subscriptions over sync, as well as the `prev_batch` token that indicates if there are more subscriptions to catch up with the companion endpoint.
- saving such catchup tokens in the state store
- automatically catch up for extra thread subscriptions in a background task
- in `Room::load_or_fetch_thread_subscriptions()`, use network if we haven't caught up yet, or the local store only, if we have.
I've tested this in isolation, with a few sliding sync tests (using the `MatrixMockServer`; this adds quite a bit of code to it, expanding the PR's size), as well as against the Synapse impl from https://github.com/element-hq/synapse/pull/18695, and it works great in both cases.
Fixes #5038.

feat: implement msc4308 + automatic background catchup of thread subscriptions

---

Cargo.lock
crates/matrix-sdk-indexeddb/Cargo.toml
crates/matrix-sdk-indexeddb/src/event_cache_store/migrations.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/foreign.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/mod.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/serializer/types.rs
crates/matrix-sdk-indexeddb/src/event_cache_store/types.rs

This pull request is part of a series of pull requests to add a full IndexedDB implementation of the `EventCacheStore` (see #4617, #4996, #5090, #5138, #5226, #5274, #5343, #5384, #5406, #5414, #5497, #5506, #5540, #5574). This particular pull request adds types and migrations that will support storing media in IndexedDB via `EventCacheStoreMedia`.
Based on the SQLite-backed implementation of `EventCacheStoreMedia`, the following queries for interacting with stored media should be supported.
1. Operate on media by [`MediaRequestParameters`](https://docs.rs/matrix-sdk/latest/matrix_sdk/media/struct.MediaRequestParameters.html)
2. Operate on media by [`MediaSource`](https://docs.rs/matrix-sdk/latest/matrix_sdk/ruma/events/room/enum.MediaSource.html#)
3. Operate on media by last time it was …

IndexedDB: Add initial types and database migrations for `EventCacheStoreMedia` backend

---

.github/workflows/ci.yml
Cargo.lock
bindings/matrix-sdk-ffi/Cargo.toml
bindings/matrix-sdk-ffi/src/platform.rs
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/response_processors/account_data/global.rs
crates/matrix-sdk-base/src/response_processors/changes.rs
crates/matrix-sdk-base/src/response_processors/e2ee/tracked_users.rs
crates/matrix-sdk-base/src/response_processors/room/display_name.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/response_processors/timeline.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-crypto/src/machine/mod.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sync.rs
xtask/src/ci.rs

Not for the fainted of heart.
This would help pinpoint what is taking so long during some sync processing.

feat(sdk): add more timers to sync processing

---

bindings/matrix-sdk-ffi/src/client.rs
bindings/matrix-sdk-ffi/src/client_builder.rs
crates/matrix-sdk/src/client/mod.rs
crates/matrix-sdk/tests/integration/client.rs

If no custom request config is passed to `ClientBuilder`, it'll use the default one with no retry limit.
On Element X Android, this caused the `Client` to never be built and the logs to get stuck like this:
```
...
09-03 10:55:12.059 26932 27032 D org.matrix.rust.sdk: matrix_sdk::http_client::native: Sending request num_attempt=7 | crates/matrix-sdk/src/http_client/native.rs:78 | spans: send{request_id="REQ-0" method=GET uri="https://matrix-client.matrix.org/_matrix/federation/v1/version" status=429 response_size="56B" request_duration=4.144895311s status=429 response_size="56B" request_duration=3.6975288s status=429 response_size="56B" request_duration=3.40915854s status=429 response_size="56B" request_duration=3.254537239s status=429 response_size="56B" request_duration=3.750466093s …
```

fix: Stop `ClientBuilder::build` from requesting the server info indefinitely

---

labs/multiverse/src/widgets/room_view/input.rs

This ensures that we're using the same color despite what your color scheme of your terminal is. Some color schemes might produce unreadable combinations of foreground color and background color.
Reported by @dkasak.

fix(multiverse): Define the color of the placeholder text of the input line

---

crates/matrix-sdk-base/src/response_processors/room/msc4186/extensions.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk/src/sliding_sync/client.rs

By slightly changing the shape of the function used to process read receipts, we can make it so that it's trivial to run concurrently, which gives some nice speedups locally.
While not a benchmark (and so not super accurate), I've got the distribution of the 6 worst case processing time, for an initial response of my personal account, in multiverse:
Before:
0.172524963s
0.216173016s
0.252289760s
0.257619156s
0.275838632s
0.280295891s
After:
0.083094692s
0.117074046s
0.130246646s
0.132577343s
0.138685246s
0.170287945s
---
I think we could even do better:  finally move the read receipt processing to the event cache, since it can know about the order of events, it won't have to rebuild it from scratch on every new event/read receipt, for every room. I could look into this later.
Found thanks …

perf: process read receipts concurrently

---

bindings/matrix-sdk-ffi/src/sync_service.rs
crates/matrix-sdk-ui/src/sync_service.rs
crates/matrix-sdk-ui/tests/integration/sync_service.rs
crates/matrix-sdk/src/test_utils/mod.rs
examples/oauth_cli/src/main.rs
labs/multiverse/src/widgets/settings/developer.rs

This set of patches makes `TerminationReport` and `State::Error` to contain the error leading to this state.
So far, this is not yet mapped to new error type in FFI land because it's unclear what we want for the moment. However, things are here, ready to be used, for any other Rust consumers.
It's best to review this set patch after patch.
---
* Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2822#issuecomment-3248280281

feat(ui): `sync_service::TerminationReport` and `State` contain the error

---

Cargo.toml
bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/error.rs
bindings/matrix-sdk-ffi/src/room/mod.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/Cargo.toml
crates/matrix-sdk/src/room/calls.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/widget/settings/element_call.rs
crates/matrix-sdk/tests/integration/room/calls.rs
crates/matrix-sdk/tests/integration/room/mod.rs
testing/matrix-sdk-test/src/event_factory.rs

Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/5580 
Signed-off-by:

bindings: MSC4310 call decline and subscribe to decline events

---

crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/lib.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-base/src/room/mod.rs
crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-base/src/sliding_sync.rs
crates/matrix-sdk-ui/src/room_list_service/filters/category.rs
crates/matrix-sdk-ui/src/room_list_service/filters/deduplicate_versions.rs
crates/matrix-sdk-ui/src/room_list_service/filters/favourite.rs
crates/matrix-sdk-ui/src/room_list_service/filters/invite.rs
crates/matrix-sdk-ui/src/room_list_service/filters/joined.rs
crates/matrix-sdk-ui/src/room_list_service/filters/low_priority.rs
crates/matrix-sdk-ui/src/room_list_service/filters/non_left.rs
crates/matrix-sdk-ui/src/room_list_service/filters/space.rs
crates/matrix-sdk-ui/src/room_list_service/filters/unread.rs
crates/matrix-sdk-ui/src/room_list_service/room_list.rs
crates/matrix-sdk-ui/src/room_list_service/sorters/latest_event.rs
crates/matrix-sdk-ui/src/room_list_service/sorters/lexicographic.rs
crates/matrix-sdk-ui/src/room_list_service/sorters/mod.rs
crates/matrix-sdk-ui/src/room_list_service/sorters/name.rs
crates/matrix-sdk-ui/src/room_list_service/sorters/recency.rs
crates/matrix-sdk/src/lib.rs

This set of patches updates the room list to sort rooms by their “latest event”. What does it mean?
- We want a room with a **local** latest event to be at the top of the room list,
- We want a room to have an accurate position in the room list, which means we want to rely on the latest event instead of the room `recency_stamp` (also known as the `bump_stamp` in sliding sync terminology):
- Why was `recency_stamp` inaccurate? Because the server might _bump_ a room based on certain events, so the room will _bump_ in the room list, but the latest event won't change because the event causing the bump is **not** a latest event candidate. Because the latest event is used by som apps to display the room “last updated time” in the room, the user might see unordered rooms!
- One may argue that we …

feat(ui): Add the new `latest_event` room list sorter, and update the `recency` sorter

---

bindings/matrix-sdk-ffi/src/widget.rs

Add capabilities for widgets to read/send rtc decline events.
Signed-off-by:

widget-driver: Add read/send capabilities for rtc decline event

---

.deny.toml
Cargo.lock
Cargo.toml
crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/Cargo.toml
crates/matrix-sdk-base/src/room/members.rs
crates/matrix-sdk/CHANGELOG.md

This PR cherry picks a fix for a panic and prepares the 0.14.1 release of the matrix-sdk-base crate.
I forgot to develop the fix on the release branch, so we're doing cherry picks.

Release prep for matrix-sdk-base 0.14.1

---

bindings/matrix-sdk-ffi/src/widget.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/widget/mod.rs
crates/matrix-sdk/src/widget/settings/element_call.rs
crates/matrix-sdk/src/widget/settings/mod.rs

This PR is part of an onging effort to move responsiblity to the EC app and out of the EX apps.
4 intends (f.ex `join_existing` `start_new_dm`... ) (as url paramters) are introduced in recent element call versions. Those intends behave like defaults. If an intend is set a set of url parameters are predefined.
Not all params can be covered by the intend (for insteance the `widget_id` or the `host_url`).
This PR splits the url parameters into configuration (things that can be configured by the intent) and properties (things that still need to be passed one by one)
The goal with this change is that EX only needs to configre the intent once and the EC codebase can update the behavior in those 4 specific scenarios in case new features come along (auto hangup when other participants leave, send …

feat(element-call url params): split url params into configuration and properties

---

bindings/matrix-sdk-ffi/src/widget.rs

Disable adding both final `m.rtc.notification` and dev id `org.matrix.mscxxx.rtc.notification` as it is not working as expected with the ser/deser and serde alias. (They both are turned into RtcDecline at the end so ends up with duplicating the same cap)
Signed-off-by:

Fix adding both final and dev id doesn't work with ruma alias

---

crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs
crates/matrix-sdk/src/test_utils/client.rs

Otherwise, when running against a server that doesn't support thread subscriptions, the client may falsely think that its thread subscriptions are *not* outdated (when receiving an empty, defaulted `ThreadSubscriptions` section in the SSS response). As a result, it would always use the store, not find most thread subscriptions, and conclude "nope, you haven't subscribed to any thread", which is wrong.
(Looking for support of MSC4306 is _close_ to what we want, which would be support of MSC4308 itself, coming as part of https://github.com/element-hq/synapse/pull/18695, and that will land despite MSC4306 being already advertised, but that's good enough, since it's unlikely many servers have enabled it by default yet.)

fix(room service): enable the thread subscriptions extension based on server support

---

crates/matrix-sdk-common/src/deserialized_responses.rs

This patch adds a log in `TimelineEvent::timestamp` when the `timestamp` has to be extracted. It can be a performance problem depending on when it's called.
---

chore(common): Add log in `TimelineEvent::timestamp`

---

crates/matrix-sdk-ui/src/timeline/controller/metadata.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/state.rs
crates/matrix-sdk-ui/src/timeline/controller/state_transaction.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/mod.rs

In support of https://github.com/matrix-org/matrix-rust-sdk/issues/5535, this changes two things:
- centralize the decision whether a timeline is thread-focused or not, by using a `match` with fields explicitly named (so that when adding/changing a field, we have to consider those `match` statements).
- add a new `Timeline::is_threaded()` function that will return whether a timeline is on a thread or not. This will be useful in the `Events` case, to know if the permalinked message belonged to a thread or to the main timeline.

refactor(timeline): some preparatory refactorings for in-thread permalinks

---

Cargo.lock
Cargo.toml
bindings/matrix-sdk-ffi/CHANGELOG.md
bindings/matrix-sdk-ffi/src/event.rs
bindings/matrix-sdk-ffi/src/room/mod.rs
bindings/matrix-sdk-ffi/src/ruma.rs
bindings/matrix-sdk-ffi/src/timeline/content.rs
bindings/matrix-sdk-ffi/src/widget.rs
crates/matrix-sdk-base/src/latest_event.rs
crates/matrix-sdk-base/src/read_receipts.rs
crates/matrix-sdk-base/src/response_processors/latest_event.rs
crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs
crates/matrix-sdk-ui/src/timeline/controller/mod.rs
crates/matrix-sdk-ui/src/timeline/event_handler.rs
crates/matrix-sdk-ui/src/timeline/event_item/content/mod.rs
crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
crates/matrix-sdk/src/latest_events/latest_event.rs
crates/matrix-sdk/src/room/calls.rs
crates/matrix-sdk/src/widget/settings/element_call.rs
crates/matrix-sdk/tests/integration/room/calls.rs
labs/multiverse/src/widgets/room_view/timeline.rs
testing/matrix-sdk-test/src/event_factory.rs

`CallNotify` event has been deprecated in favour of `RtcNotification` event https://github.com/ruma/ruma/pull/2199
Needs an update on ruma dependency
Signed-off-by:

feat(rtc): Remove deprecated CallNotify in favour of RtcNotification

---

bindings/matrix-sdk-ffi/src/platform.rs
crates/matrix-sdk-common/src/deserialized_responses.rs

This patch defines a new log target, `MatrixSdkCommonDeserializedResponses`. It is enabled by the `SyncProfiling`, `EventCache` or `Timeline` log packs.
This patch also changes the level of the log in `TimelineEvent::timestamp` from `trace` to `warn`.
---

chore(ffi): Define new log target for `deserialized_responses`

---

crates/matrix-sdk-ui/src/room_list_service/sorters/recency.rs

This patch updates the `recency` room list sorter to no longer use the `LatestEventValue::timestamp` method. It keeps using the `Room::recency_stamp` for the moment, as it was the case before. This patch is a test to try finding the problem in some Matrix clients where the room list becomes unusable. We suspect it's because of this patch sorter.
---

fix(ui): The `recency` room list sorter stops using the latest event's timestamp

---

crates/matrix-sdk-base/src/room/room_info.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk/src/notification_settings/mod.rs
crates/matrix-sdk/src/sliding_sync/client.rs
labs/multiverse/src/main.rs

The room notification modes will only change when the push rules have changed; otherwise, recomputing them is a no-op, and only wastes time.
Here's a distribution of the worst processing times under this method, as measured in `multiverse` with some big test account running (fresh, i.e. after an initial response) for a few minutes:
Before:
0.036192141s
0.037368775s
0.039177686s
0.039883797s
0.041679405s
After:
0.000000249s
0.000000397s
0.000000899s
0.001080307s
0.001340611s
The new distribution makes sense: the push rules event comes only once, in the initial response, so they're processed only once. Then, there's no need to process it ever again (in my session I've never changed the processing times), so it's almost instantaneous the subsequent times.
Found thanks to …

perf: make room notification caching up to 4000% faster

---

Cargo.lock
Cargo.toml
crates/matrix-sdk-ui/src/room_list_service/sorters/recency.rs
crates/matrix-sdk-ui/tests/integration/room_list_service.rs

This patch updates `eyeball-im` to 0.8.0, `eyeball-im-util` to 0.10.0 and `imbl` to 6.1.0.
The idea is to fix this bug https://github.com/jplatte/eyeball/pull/80.
---

chore: Update `eyeball-im`, `eyeball-im-util` and `imbl`

---

bindings/matrix-sdk-ffi/src/client.rs

For some reason, running `cargo xtask ci clippy` locally would now fail, complaining that the recent emoji functions didn't exist, in the FFI layer. I suspect it's because some of the uniffi derive macro to export functions incorrectly propagates the `cfg` guards; so a solution is to move all this code under a new mod, that's enabled if and only if the feature's enabled.
@jmartinesp can you try it around and confirm the emoji functions are still available for you, when the experimental feature's enabled, please?

chore(ffi): rejigger recent emoji code around so as to work with defaut features disabled

---

crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-ui/src/room_list_service/mod.rs
crates/matrix-sdk/src/event_cache/mod.rs
crates/matrix-sdk/src/latest_events/mod.rs
crates/matrix-sdk/src/latest_events/room_latest_events.rs
crates/matrix-sdk/src/sliding_sync/client.rs
crates/matrix-sdk/src/sync.rs

This patch updates `SlidingSyncResponseProcessor::handle_room_response` to automatically call `LatestEvents::listen_to_room` based on `http::Response`'s `rooms`.
Why? Because when a sync is received, we want its `LatestEventValue` to be computed, so that it can trigger a `RoomInfoNotableUpdate`, which will update the `RoomList`, which will re-sort the rooms. So far, `LatestEvents::listen_to_room` was called by `RoomListService::subscribe_to_rooms`, but it's possible to receive a room update via the sync for a room that is not subscribed, i.e. out of the viewport of the room list in Matrix clients (it's recommended to subscribe to rooms that “enter” the viewport). Without this patch, rooms are receiving updates but the room list is not entirely refreshed/recalculated.
Other patches also …

feat(sdk): `LatestEvents` auto-listens from the sync

---

crates/matrix-sdk-base/CHANGELOG.md
crates/matrix-sdk-base/src/client.rs
crates/matrix-sdk-base/src/store/mod.rs
crates/matrix-sdk/src/latest_events/latest_event.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/sliding_sync/mod.rs

This patch renames the `sync_lock` to `state_store_lock` because it is what it is. It's not about the sync, it's about the state store.

refactor(base): Rename `sync_lock` to `state_store_lock`

---

bindings/matrix-sdk-ffi/src/room/mod.rs

The raw event was being deserialized in a wrong way and it could have a missing room id in some cases, returning an error even when the event was found.
Signed-off-by:

fix(ffi): `ffi::Room::load_or_fetch_event` fails with missing room_id

---

crates/matrix-sdk-ui/src/spaces/room_list.rs

… when known to the client and forward updates through the existing `subscribe_to_space_updates` mechanisms.
This allows clients to listen to updates without having to resort to a separate room info subscription on their side.

feat(spaces): automatically subscribe to `SpaceRoomList` "parent" space room info updates 

---

bindings/matrix-sdk-ffi/src/timeline/mod.rs
crates/matrix-sdk-ui/src/timeline/futures.rs
crates/matrix-sdk-ui/src/timeline/mod.rs
crates/matrix-sdk-ui/tests/integration/timeline/media.rs
crates/matrix-sdk/CHANGELOG.md
crates/matrix-sdk/src/attachment.rs
crates/matrix-sdk/src/room/mod.rs
crates/matrix-sdk/src/send_queue/upload.rs
crates/matrix-sdk/tests/integration/room/attachment/mod.rs
crates/matrix-sdk/tests/integration/send_queue.rs
examples/image_bot/src/main.rs

It doesn't make sense to send a formatted caption without a plain text caption so using TextMessageEventContent forces the latter to be present.
This also allows to use the helpful constructors of TextMessageEventContent.

refactor(sdk): Use TextMessageEventContent to send a caption

---

crates/matrix-sdk-ui/src/room_list_service/room_list.rs

The `RoomListItem` caches some data. It's been introduced in #5684. When the cached data are refreshed, the `Room::is_space()` value wasn't refreshed because I thought it wasn't possible to change the type of a room. However, if the state is not fully loaded (because the `m.room.create` event isn't present), the result of `Room::is_space()`… can change. So this patch refreshes the `cached_is_space` value unconditionally.
---
* Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/5721

fix(ui): `RoomListItem` refreshes its `cache_is_space`
