Cargo.toml, examples/login.rs, src/async_client.rs, src/base_client.rs, src/event_emitter/mod.rs, src/lib.rs, src/models/mod.rs, src/models/room.rs, src/models/room_member.rs, src/models/user.rs, tests/async_client_tests.rs
Sorry I didn't break the PR up more.
This works in an async `spawn` environment now, you were right no references and we have to use `Arc<tokio::Mutex<...` in order for it to be `Future` safe.
=> EventEmitter trait implementation

.travis.yml, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs
Travis doesn't fail by default when any script before the last fails: https://github.com/travis-ci/travis-ci/issues/1066
This change fixes that (and the build).
=> travis: fail-fast for wasm target

matrix_sdk/Cargo.toml, matrix_sdk/src/client.rs
Use futures-timer's `wasm-bindgen` feature for the WASM target and re-enable (the no longer panic'ing) sleep.
=> matrix-sdk: Use futures-timer's wasm-bindgen feature

matrix_sdk/src/client.rs
This was briefly discussed in the Matrix room, but I believe that exposing the `Client::send` at least until the 1.0 release may be beneficial, as the ruma api is extensive and fairly easy to use, thus greatly extending the functionality of this library until more wrapper methods are complete.  The doccomment used for this method indicates that it is not recommended to use this method while a wrapper method exists for the same purpose, and warns that this method will not update client state.
=> Expose the Client::send method, adding a brief doccomment

matrix_sdk_base/src/client.rs, matrix_sdk_base/src/event_emitter/mod.rs, matrix_sdk_test/src/lib.rs, matrix_sdk_test/test_data/more_sync.json, test_data/events/message_edit.json, test_data/events/reaction.json, test_data/more_sync.json
We had everything already implemented to do this just wasn't actually hooked up.
Would a PR to remove one of the `test_data` folders be wanted?
=> base_client: emit typing events and test using EventEmitter

matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs
Allows for more specific error types when the `BaseClient` Errors.
=> matrix-sdk: Export matrix-sdk-base Error type as BaseError

Cargo.toml, matrix_sdk/Cargo.toml, matrix_sdk/examples/command_bot.rs, matrix_sdk/examples/login.rs, matrix_sdk_base/Cargo.toml, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/event_emitter/mod.rs, matrix_sdk_base/src/models/room.rs, matrix_sdk_base/src/models/room_member.rs, matrix_sdk_base/src/state/mod.rs, matrix_sdk_common_macros/Cargo.toml, matrix_sdk_common_macros/src/lib.rs, matrix_sdk_crypto/Cargo.toml, matrix_sdk_crypto/src/store/mod.rs
- Only use send+sync when not using wasm
- Use wasm capable async_trait wrapper macro
- Make room and room_member specific structs always clonable
The first two are discussed in the wasm tracking issue (#35) the third was from a discussion in the matrix room. 
All changes were tested in Daydream.
=> Do wasm sepcific changes

matrix_sdk_base/src/models/message.rs
I have not benchmarked this, but I would expect the first commit to be irrelevant perf-wise for release builds, while the second one should reduce (re)allocations a lot when lots of messages pass through `MessageQueue` deserialization (as is the case for Daydream).
cc @MTRNord
=> Some simple optimizations

matrix_sdk_base/src/lib.rs
Mark `AllRooms` and `ClientState` as `pub` in `matrix-sdk-basd` so that the `StateStore` trait can be implemented in a local crate.
The trait `StateStore` has
```rust
async fn load_client_state(&self, _: &Session) -> Result<Option<ClientState>>;
async fn load_all_rooms(&self) -> Result<AllRooms>;
```
which reference the currently private `ClientState` and `AllRooms`. Implementing this trait is not possible currently (afaik), since it references those types. This PR marks them as `pub` so they can be used in the trait impl.
=> mark state::AllRooms and state::ClientState as public

matrix_sdk/src/client.rs
Added an HTTP timeout, which will allow the client to automatically reconnect instead of hanging indefinitely.
Note: I have not tested this locally (Need to rewrite my bot for it to work with the latest changes) but it compiles. Someone else will need to test this.
=> HTTP timeout

.pre-commit-config.yaml, matrix_sdk/examples/autojoin.rs, matrix_sdk/examples/command_bot.rs, matrix_sdk/examples/login.rs, matrix_sdk/examples/wasm_command_bot/src/lib.rs, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs, matrix_sdk/src/request_builder.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/event_emitter/mod.rs, matrix_sdk_base/src/lib.rs, matrix_sdk_base/src/models/message.rs, matrix_sdk_base/src/models/mod.rs, matrix_sdk_base/src/models/room.rs, matrix_sdk_base/src/models/room_member.rs, matrix_sdk_common/Cargo.toml, matrix_sdk_crypto/src/device.rs, matrix_sdk_crypto/src/error.rs, matrix_sdk_crypto/src/lib.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/memory_stores.rs, matrix_sdk_crypto/src/olm.rs, matrix_sdk_crypto/src/store/sqlite.rs, matrix_sdk_test/src/lib.rs
This also bumps the rev of ruma to the commit that adds redacted event support.
=> matrix-sdk-base: MessageQueue properly handles redacted events

matrix_sdk/src/client.rs, matrix_sdk/src/request_builder.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/models/room.rs, matrix_sdk_base/src/models/room_member.rs, matrix_sdk_common/Cargo.toml, matrix_sdk_common/src/lib.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/olm/group_sessions.rs
By the way, you've got a weird mix of one use statement per crate and one use statement per module. And also a mix of matrix_sdk_common imports and crate imports in matrix_sdk_base. You may want to fix that.
=> Upgrade ruma

matrix_sdk_base/src/models/message.rs
There's already a SyncMessageEvent in Ruma which is something else.
Let's prefer the full, unambiguous type.
=> Remove confusing type alias for AnyPossiblyRedactedSyncMessageEvent.

matrix_sdk/src/lib.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/lib.rs, matrix_sdk_base/src/models/message.rs, matrix_sdk_base/src/models/mod.rs, matrix_sdk_base/src/models/room.rs
As discussed on matrix in the rust-sdk room we should not be sorting the messages and a simpler duplicate checking only the `event_id`.
=> sdk-base: Remove MessageWrapper and do not order messages in queue

.gitignore, matrix_sdk/examples/wasm_command_bot/src/lib.rs, matrix_sdk/src/lib.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/event_emitter/mod.rs, matrix_sdk_base/src/lib.rs, matrix_sdk_base/src/models/room.rs, matrix_sdk_crypto/src/verification/sas/mod.rs, matrix_sdk_test/src/test_json/events.rs, matrix_sdk_test/src/test_json/sync.rs
~~I don't think it is possible for a valid event to fail deserialization, all the cases I can think of become custom events. The message edit event was failing because of an invalid `EventId` value in the JSON. I wonder if we should remove the `EventEmitter::on_unrecognized_event` trait method? Or is the just incase still useful?~~
The `CustomOrRawEvent::RawJson` variant is what could possibly be removed and the `EventEmitter::on_unrecognized_event` trait method renamed to `on_custom_event` maybe?
=> Update ruma and fix failing message edit test

matrix_sdk_base/src/models/room.rs, matrix_sdk_crypto/src/machine.rs
This was overflowing in DayDream for @MTRNord. This should guarantee that won't happen.
I wonder if this method should return a `Result` in the case of problems with the power level. This would cause a number of methods to go from `bool` -> `Result<bool>` but I would imagine this is somewhat important info for a client?
=> Power ev overflow

matrix_sdk/src/client.rs, matrix_sdk/src/device.rs, matrix_sdk/src/sas.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/lib.rs, matrix_sdk_crypto/src/device.rs, matrix_sdk_crypto/src/lib.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/requests.rs, matrix_sdk_crypto/src/verification/machine.rs, matrix_sdk_crypto/src/verification/mod.rs, matrix_sdk_crypto/src/verification/sas/helpers.rs, matrix_sdk_crypto/src/verification/sas/mod.rs
I was planning to also bump ruma, but that's a bit more involved than I had hoped. You will probably need your own copies of `IncomingKeysUploadRequest` and `IncomingKeysQueryRequest` too for the next bump.
I wasn't too sure where to put the `ToDeviceRequest` type. Let me know if there is a better place.
=> Replace IncomingToDeviceRequest with customized request type

matrix_sdk_common/Cargo.toml
=> matrix-sdk-common: Switch futures-locks to crates.io version

matrix_sdk/Cargo.toml, matrix_sdk/examples/autojoin.rs, matrix_sdk/examples/command_bot.rs, matrix_sdk/examples/emoji_verification.rs, matrix_sdk/examples/image_bot.rs, matrix_sdk/examples/login.rs, matrix_sdk/examples/wasm_command_bot/src/lib.rs, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs
This attempts to fix a bunch of issues presented in https://github.com/matrix-org/matrix-rust-sdk/issues/98.
Mainly the sync loop can be aborted by providing a boolean value in the callback, the login method has an example and we link restore_login from login and vice versa.
=> Improve our sync methods and the docs for the login.

matrix_sdk_common/Cargo.toml
I noticed some oddities in the ruma dependency, so went and fixed them.
The upgrade doesn't include a lot, but noticably it includes (under `unstable-pre-spec`) the URL in `m.room.avatar` being optional, such that it can be unset.
=> Clean up ruma dependency

contrib/mitmproxy/failures.py, matrix_sdk/Cargo.toml, matrix_sdk/examples/get_profiles.rs, matrix_sdk/src/client.rs, matrix_sdk/src/error.rs, matrix_sdk/src/http_client.rs, matrix_sdk/src/lib.rs, matrix_sdk/src/sas.rs
This PR adds logic to the client to retry requests in a smart way depending on the status code.
Stuff that needs to be done before this can be merged:
=> Request retrying

matrix_sdk/src/lib.rs, matrix_sdk_base/src/lib.rs, matrix_sdk_base/src/store/mod.rs
Not sure if `StateChanges` should be exported but everything was pub so :shrug:. In order to impl all the `EventEmitter` trait methods the `CustomEvent` needed to be exported.
=> Export CustomEvent and StateChanges add docs to StateChanges

design.md, matrix_sdk/examples/autojoin.rs, matrix_sdk/examples/command_bot.rs, matrix_sdk/examples/image_bot.rs, matrix_sdk/examples/login.rs, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/event_emitter/mod.rs, matrix_sdk_base/src/event_handler/mod.rs, matrix_sdk_base/src/lib.rs
Quite a breaking change, but the SDK breaks quite often anyways so we might as well do it now.
=> Rename `EventEmitter` to `EventHandler`

.github/workflows/docs.yml
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/154
This requires also that github pages are enabled in the repo settings. The docs are build for commits to `master` and pull requests but only for new commits to `master` the new version is published to the `gh-pages` branch.
=> CI: Publish docs via github pages

matrix_sdk/src/http_client.rs
Ruma will for some requests already set the content-type for us to application/json, but for some it still seems to miss the header, since the headers are kept in a map add the header only if it isn't already there.
=> matrix-sdk: Don't set two content-type headers for json contents

matrix_sdk_base/src/client.rs, matrix_sdk_base/src/rooms/mod.rs, matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_base/src/rooms/stripped.rs, matrix_sdk_crypto/src/olm/account.rs, matrix_sdk_crypto/src/olm/group_sessions/inbound.rs, matrix_sdk_crypto/src/olm/group_sessions/outbound.rs, matrix_sdk_crypto/src/session_manager/group_sessions.rs
This is meant to come after #130.
This fixes some typos and refactors the group session sharing code to increase readability.
=> Group session sharing code refactoring

matrix_sdk/src/sas.rs, matrix_sdk_crypto/src/lib.rs, matrix_sdk_crypto/src/verification/mod.rs, matrix_sdk_crypto/src/verification/sas/mod.rs
Offer callers to modify the SAS accept() request before being sent by
passing in a function which allows arbitrary modifications to the
request.
=> crypto: Expose a function to customize SAS accepting

matrix_sdk/examples/autojoin.rs, matrix_sdk/examples/command_bot.rs, matrix_sdk/examples/image_bot.rs, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs, matrix_sdk/src/room/common.rs, matrix_sdk/src/room/invited.rs, matrix_sdk/src/room/joined.rs, matrix_sdk/src/room/left.rs, matrix_sdk/src/room/mod.rs, matrix_sdk/src/verification_request.rs, matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs, matrix_sdk_test/src/test_json/members.rs, matrix_sdk_test/src/test_json/mod.rs
This adds four new structs: `room::{Common, Joined, Left, Invited}`
- Common: Contains methods that are shared between the different Room states and is the base for other room types. This struct contains a clone of `matrix_sdk::Client` and derefs to the `matrix_sdk_base::Room` so that the user can access the underlying data directly.  
- Joined, Left, Invited: Contains methods that are available for each room state respectively rooms, they all deref to `room::Common`
Fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/165, https://github.com/matrix-org/matrix-rust-sdk/issues/144
=> matrix-sdk: High-level room api

matrix_sdk/src/client.rs, matrix_sdk/src/room/joined.rs
Implement redaction for client [`PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}`](https://matrix.org/docs/spec/client_server/r0.6.1#id276).
=> client: PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}

matrix_sdk/src/room/joined.rs
Make accidentally hidden lines in examples show up again.
=> matrix-sdk: fix accidentally hidden lines in examples

.github/workflows/ci.yml, matrix_sdk/src/client.rs, matrix_sdk/src/room/common.rs, matrix_sdk/src/room/mod.rs, matrix_sdk/src/sas.rs
CI still fails because the `room_send()` method was removed from the `Client`. I'm inclined to just reintroduce it since it seems to be generally useful for it to exists since not everybody will care about room state, e.g. bots that send messages to a hard-coded room.
=> Reintroduce CI for WASM

matrix_sdk_base/src/error.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs, matrix_sdk_crypto/src/store/mod.rs, matrix_sdk_crypto/src/store/sled.rs
I left out the public-facing rust-sdk `Result` type since it's not used internally and I don't imagine consumer `use`ing it, but if you prefer I can update that one too.
=> Allow Result aliases to be used with two type parameters

matrix_sdk/examples/get_profiles.rs, matrix_sdk/src/client.rs, matrix_sdk/src/lib.rs, matrix_sdk/src/room/common.rs, matrix_sdk/src/room/joined.rs, matrix_sdk_base/src/rooms/members.rs, matrix_sdk_base/src/rooms/mod.rs, matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_common/Cargo.toml, matrix_sdk_crypto/src/error.rs, matrix_sdk_crypto/src/olm/account.rs, matrix_sdk_crypto/src/olm/mod.rs, matrix_sdk_crypto/src/olm/signing/pk_signing.rs, matrix_sdk_crypto/src/store/sled.rs, matrix_sdk_test/src/test_json/events.rs, matrix_sdk_test/src/test_json/sync.rs
I need it to work on push rules but there are quite a few changes so I think it's better to do this separately:
- Use `MxcUri` instead of `String` for media URLs.
- Fix wrong MXC URIs in tests.
- Remove method `parse_mxc` no longer useful.
- Apply new non-exhaustive types: `CrossSigningKey`, `OneTimeKey` and `SignedKey`.
- Apply endpoint name change: `send_state_event_for_key` to `send_state_event`
=> Bump ruma to 2f1b9f097930bf7908ca539f2ab7bb0ccf5d8b25

matrix_sdk/src/client.rs, matrix_sdk/src/http_client.rs, matrix_sdk/src/lib.rs
This exposes the retry behavior to the developer. This way the user can
set if a request should be retried or failed immidiatly.
This also make sure that the timeout set by the user is used for all
requests. Of-course it can't be used for uploaded and syncs with
timeout, but this doesn't change the behavior for those requests.
=> matrix-sdk: Add RequestConfig that replaces timeout for requests

matrix_sdk/src/client.rs, matrix_sdk/src/error.rs, matrix_sdk/src/room/common.rs, matrix_sdk/src/room_member.rs, matrix_sdk_common/Cargo.toml, matrix_sdk_crypto/src/olm/group_sessions/mod.rs
Yet another version bumping… This is to have the more flexible `MxcUri`.
- Added an error variant to handle `identifiers::Error` because of request constructors that return that error.
- Fixed a new non-exhaustive type.
=> Bump ruma to e2728a70812412aade9322f6ad832731978a4240

matrix_sdk/Cargo.toml, matrix_sdk/src/client.rs, matrix_sdk_base/Cargo.toml
`cargo build --no-default-features --features native-tls` currently fails on `master`
=> matrix-sdk: fix building without encryption feature

matrix_sdk_base/src/client.rs, matrix_sdk_common/Cargo.toml
Unfortunately I had to duplicate the entire destructuring statement for `sync_events::Response` since attributes on field patterns or `..` rest-field patterns are not supported. (cc https://github.com/rust-lang/rust/issues/81282#issuecomment-822376089)
From here it should be easy to add `EncryptionInfo` as discussed without further changes to Ruma, right? If so, this closes ruma/ruma#35.
=> Exhaustive sync_events::Response conversion

matrix_sdk/src/client.rs, matrix_sdk_base/src/client.rs, matrix_sdk_crypto/benches/crypto_bench.rs, matrix_sdk_crypto/src/identities/device.rs, matrix_sdk_crypto/src/key_request.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/session_manager/group_sessions.rs, matrix_sdk_crypto/src/session_manager/mod.rs, matrix_sdk_crypto/src/session_manager/sessions.rs, matrix_sdk_crypto/src/store/memorystore.rs, matrix_sdk_crypto/src/store/mod.rs, matrix_sdk_crypto/src/store/sled.rs
This PR improves key sharing and key requesting in a couple of ways:
1. Correctly honor requests if we have an outbound group session and the list of recipients
2. Add a public method so users can request and re-request room keys manually
3. Add specialized cryptostore methods to handle key requests
4. Only request room keys if we have a verified device to avoid room key request spam on initial sync
=> Key share improvements

.github/workflows/ci.yml, matrix_sdk/src/client.rs, matrix_sdk/src/room/joined.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/store/mod.rs
Those warnings currently pop up with `cargo clippy --no-default-features --features native-tls`
Also adds a CI task that executes clippy without default features (just native-tls) and without `--all-targets` (because properly cleaning up examples is hard)
=> chore: cleanup clippy warnings

matrix_sdk/src/event_handler/mod.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs, matrix_sdk_common/src/deserialized_responses.rs, matrix_sdk_test/src/test_json/sync.rs
This matches all events received in room timelines during sync against push rules. You can use the new `EventHandler` method `on_room_notification` to get the notifications.
There are small issues to handle before merging:
Fixes #184.
**Improvements to be added later:**
- It does not handle yet the `read` field of the notification because we need to be able to know if an event is before or after the user's `m.read` receipt.
- The "highlight" tweak should be passed with the event for display.
=> matrix-sdk: Get notifications locally on sync

matrix_sdk/examples/emoji_verification.rs, matrix_sdk/examples/wasm_command_bot/src/lib.rs, matrix_sdk/src/event_handler/mod.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs, matrix_sdk_common/src/deserialized_responses.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/olm/group_sessions/inbound.rs
This should supersede #136, we now have much less custom response and event types so this is nice, though the trade off is that the API has become a serialized form.
This was discussed in the Matrix room and is necessary due to the lossy nature of the deserialization/serialization cycle of Ruma events.
=> Support for encryption info, take two.

matrix_sdk/src/sas.rs, matrix_sdk_crypto/src/verification/sas/helpers.rs, matrix_sdk_crypto/src/verification/sas/inner_sas.rs, matrix_sdk_crypto/src/verification/sas/mod.rs, matrix_sdk_crypto/src/verification/sas/sas_state.rs
Most notably this adds the ability to get the index of the SAS emoji instead of the emoji/decryption tuple, if you already have the emoji list defined and translated like Element Android has.
=> Some small Sas changes

.github/workflows/ci.yml, Cargo.toml, matrix_sdk/Cargo.toml, matrix_sdk/src/client.rs, matrix_sdk/src/error.rs, matrix_sdk/src/http_client.rs, matrix_sdk/src/lib.rs, matrix_sdk_appservice/Cargo.toml, matrix_sdk_appservice/examples/actix_autojoin.rs, matrix_sdk_appservice/src/actix.rs, matrix_sdk_appservice/src/error.rs, matrix_sdk_appservice/src/lib.rs, matrix_sdk_appservice/tests/actix.rs, matrix_sdk_appservice/tests/registration.yaml, matrix_sdk_appservice/tests/tests.rs, matrix_sdk_common/Cargo.toml, matrix_sdk_common/src/lib.rs
---
The general idea is that [incoming appservice transactions](https://matrix.org/docs/spec/application_service/r0.1.2#put-matrix-app-v1-transactions-txnid) from the homeserver are translated into an `api::client::r0::sync::sync_events::Response` and then passed into `receive_sync_response`.
The user associated with the client `Session` is the "main appservice user" (`sender_localpart` in the [registration](https://matrix.org/docs/spec/application_service/r0.1.2#registration)). This allows for the state store to properly propagated and an API surface similar to a regular client while still handling most events coming in over transactions:
```rust
let config = AppserviceConfig::new(homeserver_url, server_name, appservice_registration)?;
let appservice = Appservice::new(config).await?; …
```
=> feat: appservice

matrix_sdk_appservice/examples/actix_autojoin.rs, matrix_sdk_appservice/src/actix.rs, matrix_sdk_appservice/src/lib.rs, matrix_sdk_appservice/tests/tests.rs
Refactors APIs and improves documentation
- Merged `client` and `client_with_localpart`
- `client` no longer implicitly calls `register`
- Renamed `hs_token_matches` to `compare_hs_token`
- Exposed `ensure_registered` as `register`
- Moved `get_host_and_port_from_registration` to `AppserviceRegistration::get_host_and_port`
- Added `set_event_handler` convenience wrapper
Tracking issue: https://github.com/matrix-org/matrix-rust-sdk/issues/228
=> appservice: Refactor API

matrix_sdk/src/room/common.rs
This fixes a problem where asking for joined members in a room will attempt to deserialize user IDs from the `members` Sled tree, but entries in that tree are serialized member event JSON values, and thus an "identifier too long" error is returned.
=> Return joined members in a room from the correct Sled tree.

matrix_sdk_base/src/rooms/mod.rs
This pull request addresses implementation errors in step 3 of the room naming algorithm[0]. They are: 
1. Empty room naming
2. Bound check in step 3.ii
3. Room member count in step 3.ii
To do this, this PR contains a small refactor of the step 3 logic into a low-level function using simple Rust data types. This changes improves testing as the Matrix data types are more cumbersome to initialize. Now the implementation has unit tests verifying expected behavior.
Fixes #133 
[0] https://matrix.org/docs/spec/client_server/latest#calculating-the-display-name-for-a-room
=> Fix step 3 of room naming algorithm

matrix_sdk/src/client.rs, matrix_sdk/src/error.rs, matrix_sdk/src/http_client.rs, matrix_sdk_test/src/test_json/mod.rs
Was supposed to fix #219, but apparently that was about something else.
=> Make client use .well-known redirects

matrix_sdk/src/client.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_test/src/test_json/sync.rs
Once upon a time we had different types for the stripped room infos and for the non-stripped ones. The different types were removed since we could handle all the infos the same way, though we still keep them in different buckets in the store since they per spec need to be stored separately.
The removal of the types didn't account for those different buckets and invited (or stripped) room infos we're never updated in its respective bucket.
This PR fixes this, and possibly #133.
=> base: Correctly update the room info for invited rooms

matrix_sdk/src/client.rs, matrix_sdk/src/error.rs, matrix_sdk/src/lib.rs, matrix_sdk_base/Cargo.toml, matrix_sdk_base/src/lib.rs, matrix_sdk_base/src/media.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs, matrix_sdk_crypto/src/file_encryption/attachments.rs
As discussed in the matrix room, when the memory store is used, we use an LRU Cache. Otherwise it's stored in the sled store.
I added methods to the client, maybe it's useful to forward them to the rooms because that's usually what you work with from the `EventHandler`. The `get_media_content` method decrypts the content if encryption is on.
I implemented a helper trait `MediaEventContent` to be able to get the files directly with the event content.
I tested it locally with a command line client and it works, both with the memory store and the sled store, and encrypted content.
=> Add Media store

matrix_sdk/Cargo.toml, matrix_sdk/src/client.rs, matrix_sdk/src/http_client.rs, matrix_sdk/src/lib.rs, matrix_sdk_appservice/Cargo.toml, matrix_sdk_appservice/examples/actix_autojoin.rs, matrix_sdk_appservice/src/actix.rs, matrix_sdk_appservice/src/error.rs, matrix_sdk_appservice/src/lib.rs, matrix_sdk_appservice/tests/actix.rs, matrix_sdk_appservice/tests/tests.rs
- Adds `new_with_client_config` to allow configuring main appservice user client
- Adds `client_with_config` to allow configuring virtual user clients
- Exposes `get_request_config` on the `Client`
- Refactors `Appservice`'s `client` method to be a singleton that caches clients internally
- Puts `AppserviceRegistration` into an `Arc`
- Some cleanup
- What's probably missing is a way to drop or re-initialize cached clients, added to the tracking issue
- Reasoning for `client` method singleton: Since in an appservice context clients get often constructed on demand it could lead to easy footguns in terms of having multiple clients trying to sync, which is especially problematic in terms of E2EE
Part of #228
=> appservice: Add client_with_config singleton

matrix_sdk_appservice/examples/actix_autojoin.rs, matrix_sdk_appservice/src/lib.rs, matrix_sdk_appservice/tests/tests.rs
Having both `new_with_client_config` and `client_with_config` was confusing. This refactoring tries to make the difference between "main user" and "virtual user" more obvious.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/228
=> appservice: Improve API

matrix_sdk_base/src/rooms/normal.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_crypto/src/identities/device.rs, matrix_sdk_crypto/src/identities/manager.rs, matrix_sdk_crypto/src/identities/user.rs, matrix_sdk_crypto/src/key_request.rs, matrix_sdk_crypto/src/machine.rs, matrix_sdk_crypto/src/olm/account.rs, matrix_sdk_crypto/src/olm/group_sessions/outbound.rs, matrix_sdk_crypto/src/olm/session.rs, matrix_sdk_crypto/src/session_manager/sessions.rs, matrix_sdk_crypto/src/store/mod.rs, matrix_sdk_crypto/src/store/sled.rs, matrix_sdk_crypto/src/verification/machine.rs, matrix_sdk_crypto/src/verification/mod.rs, matrix_sdk_crypto/src/verification/requests.rs, matrix_sdk_crypto/src/verification/sas/mod.rs
I also saw lots of `Arc<Box<dyn CryptoStore>>` but didn't bother with that. Maybe there's a good reason for it?
This change will introduce an extra string copy whereever `Box<DeviceId>` is converted to `Arc<DeviceId>` (and in two places where `&DeviceId` is converted to `Arc<DeviceId>`, but that [is fixable](https://github.com/ruma/ruma/issues/615)), but remove the double indirection and also remove a few (tiny) allocations.
=> Remove a bunch of double indirections

.github/workflows/ci.yml, matrix_sdk_appservice/Cargo.toml
Let's enable `warp` by default for now until I figure out a non-breaking choosing mechanism
=> appservice: Enable warp by default

matrix_sdk/src/client.rs, matrix_sdk/src/room/common.rs, matrix_sdk/src/room_member.rs
fixes: https://github.com/matrix-org/matrix-rust-sdk/issues/150
=> matrix-sdk: use media cache for avatar requests

matrix_sdk/src/event_handler/mod.rs, matrix_sdk_base/src/client.rs, matrix_sdk_base/src/lib.rs
This is a continuation of #293, it just adds the missing doc that makes CI fail.
=> Use hoist-and-deserialize when deserializing events for the event emitter

matrix_sdk/src/room/common.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs
This PR closes #270 and adds getters for state events to `Store` and `room::Common`
Added to store:
- `get_state_events(&room_id, event_type) -> Result<Vec<Raw<AnySyncStateEvent>>>`
Added to `room::Common`:
- `get_state_event(type, state_key) -> Result<Option<Raw<AnySyncStateEvent>>>`
- `get_state_events(event_type) -> Result<Vec<Raw<AnySyncStateEvent>>>`
Questions (Answered):
1. These function names feel pretty verbose, suggestions for better ones?
2. Should the getters in `room::Common` return fully deserialized events converted to [AnyStateEvent](https://docs.ruma.io/ruma/events/enum.AnyStateEvent.html) through [into_full_event](https://docs.ruma.io/ruma/events/enum.AnySyncStateEvent.html#method.into_full_event)?
- I like having the cleaner `AnyStateEvent` output, but letting the user …
=> WIP: State Event Getters

matrix_sdk/src/client.rs, matrix_sdk/src/room/common.rs, matrix_sdk_common/src/deserialized_responses.rs
It seems there's currently no way to retrieve a event by using the event id. 
This PR adds a `event` method to `matrix_sdk::room::Common`, which makes use of `GET /_matrix/client/r0/rooms/{roomId}/event/{eventId}`
https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-event-eventid
=> room: Add event() method to retrieve a room event

matrix_sdk_appservice/Cargo.toml
So consumers directly importing the appservice crate or relying on resolver 2 can toggle sdk features.
Part of #228
=> appservice: Re-export sdk features

matrix_sdk/src/client.rs, matrix_sdk_base/src/store/memory_store.rs, matrix_sdk_base/src/store/mod.rs, matrix_sdk_base/src/store/sled_store/mod.rs
Closes #271.
Add an additional tree to the Store where custom api consumer data may
be stored.
I'm not sure exactly what types are the smartest to use for the keys and values here. While it would be nice to be able to use sled-types as suggested by the issue, it would make the custom store implementation dependent. I'm also not sure if the method on `Client` is necessary when the custom store can be interacted with via getting a reference to the `Store`.
=> Add custom storage

matrix_sdk/src/client.rs, matrix_sdk/src/event_handler.rs
InviteState contains stripped state events, and initial state events are not used anywhere in the sync response.
More complete (and simpler) fix for the autojoin bot being broken, supersedes #332.
=> Fix confusion between initial / stripped state events

matrix_sdk_common/Cargo.toml
instant doesn't need wasm_bindgen on non wasm targets, avoids building some stuff I suppose
=> fix(common): wasm_bindgen dependency feature

crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/event_handler.rs
=> Run event / notification handler callbacks in order

.rustfmt.toml
Explicitly specify the rust edition in `rustfmt.toml`. This makes makes the autoformatting in certain editors - like vim - more reliable.
=> Specifiy edition in rustfmt.toml

crates/matrix-sdk-crypto/src/verification/requests.rs
We can't keep a lock on the `inner` therefore clone it. It's not pretty
but we do the same in `start_sas()`.
=> crypto: Fix VerificationRequest::generate_qr_code()

crates/matrix-qrcode/Cargo.toml, crates/matrix-qrcode/src/types.rs, crates/matrix-qrcode/src/utils.rs
This changes `QrVerificationData::from_luma()` to accept any struct that
implements GenericImage and GenericImageView.
This way we don't force a specific container for the ImageBufffer, hence
the developer doesn't necessarily need to copy the image data into a
Vec<u8>.
=> matrix-qrcode: Use GenericImage and GenericImageView trait

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs
This PR makes sure we don't generate too many one-time keys if the caller didn't successfully upload the previous call.
=> Make sure we don't generate too many one-time keys

.typos.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/backups/keys/backup.rs, crates/matrix-sdk-crypto/src/backups/keys/mod.rs, crates/matrix-sdk-crypto/src/backups/keys/recovery.rs, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/sled.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk/src/encryption/mod.rs
This is mostly just here to get backups working in Element Android, the backup functionality is missing from the top level sdk crate.
The top level crate will first need 4S support and we'll likely only enable backups once [symmetric backups](https://github.com/uhoreg/matrix-doc/blob/symmetric-backups/proposals/3270-symmetric-megolm-backup.md) have been implemented.
I'm not completely happy with the API, but it's what EA expects  and the backups being so heavily tied to making requests to check the current state makes it a bit hard to model nicely.
=> Support for server-side backups of room keys

crates/matrix-sdk/examples/wasm_command_bot/package.json, crates/matrix-sdk/examples/wasm_command_bot/webpack.config.js
This PR updates the wasm-example to use webpack5, fixing the unexpected-section-bug described in #353 . The env-bug however is coming from libolm 2.3.3, for which a PR has been sent upstream but isn't integrated yet.
=> Update to webpack5

crates/matrix-sdk-crypto/src/file_encryption/key_export.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs
Clients might want to retry decryption after they import room keys, for this to be efficient they'll need to know which room keys got imported.
This patch extends the return value of the room key import result to include the map of room keys that got imported.
=> Return the list of room keys we imported

crates/matrix-sdk-common/Cargo.toml
This fixes a minor thing that did prevent compiling wasm for me. (Note this likely doesnt fix the runtime wasm issues but I just saw that it caused rust to not compile as uuid was missing the serialize and deserialize traits because of this)
=> Make sure to also include the uuid crate's serde feature with wasm

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk/src/config/client.rs, crates/matrix-sdk/src/config/request.rs, crates/matrix-sdk/src/config/sync.rs
Got nerd-sniped into looking for & fixing a huge type name by https://github.com/matrix-org/matrix-rust-sdk/pull/414#issuecomment-1001554043.
=> Avoid enormous type name + related refactoring

crates/matrix-sdk/src/config/request.rs
This is needed for some endpoints where authentication is marqued as None in Ruma, but the homeserver might require it.
For example: [GET /_matrix/client/r0/profile/{userId}](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-profile-userid) is marked as not authenticated [in Ruma](https://github.com/ruma/ruma/blob/main/crates/ruma-client-api/src/r0/profile/get_profile.rs#L13) but authentication may be required in Synapse if `require_auth_for_profile_requests` is set to `true`.
=> feat(RequestConfig): expose force_auth setting

crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/mod.rs
This fixes #189. Even though there is #288 already, there are still a number of open issues with it and I think it is worth it to implement merge these changes at least as an intermediate solution.
=> Decrypt messages from room::Common::messages()

crates/matrix-sdk-crypto/Cargo.toml
Turn on alloc feature that is required for `future::join_all`.
Fixes #451.
=> Fix futures-util dependency

crates/matrix-sdk/src/room/common.rs
Since it's a method called on a Room, it doesn't make sense to have to specify the `RoomId` manually. Also the request has only a simple constructor, unlike `messages` so it doesn't make sense that users must it create manually for a high-level API.
There's also a small commit that fixes the doc of `Common::active_members_no_sync`.
=> feat(sdk): Simplify the API of Common::event

crates/matrix-sdk/src/client.rs
Since it's the recommended endpoint to call to validate that a URL matches a Matrix homeserver, it makes sense to make it public for users when they don't use auto-discovery with the `Client::new_from_user_id` methods.
Alternatively, we could have a `validate_homeserver` method that returns a `HttpResult<()>`.
=> feat(sdk): Make get_supported_versions public

crates/matrix-sdk/README.md
=> docs(sdk): Fix a typo

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/common.rs
Without this change, a batch with a message that cannot be deserialized
(for whatever reason) means that the batch cannot be processed at all by
the caller. Now, those messages are returned unchanged in the batch so
that the caller can handle them.
=> Return broken messages unchanged from messages() (followup to #448)

crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This is the first part of #449 as a separate PR as requested:
It fixes the verification getting stuck if both parties send a `start` message (which is allowed according to [this guide](https://matrix.org/docs/guides/implementing-more-advanced-e-2-ee-features-such-as-cross-signing/#recap-1)).
Since the test of the full request-initiated verification also requires the other part of #449, it is included in the second PR.
=> Fix verification getting stuck when both parties send start

crates/matrix-sdk-appservice/src/lib.rs
Add examples for functions for registering handlers for room and user
queries. Also remove a needless mut requirement for these functions.
=> appservice: Examples for query handler registry fns

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs
**1. Move set/remove tag methods to room::Common**
In the spec, it doesn't say that a room has to be joined before setting or removing room tags. In the SDK, the corresponding methods are only implemented on `Joined rooms.
In practice, it works on matrix.org in the three states we have: invite, joined, left.
My use case is that the user can join an invite and put it in favorites at the same time with drag and drop. Changing the tag before joining the room will make it have the proper tag right away.
**2. Use TagName in set/remove tag methods**
This provides the default values and string validity check for user-defined tags. It's always possible to use `TagName::_Custom` for custom strings.
=> sdk: Move tag methods to room::Common and use TagName

crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/mod.rs
With the previous API, one would have to supply the room's ID manually, despite the method already being called on a room.
I thought there was a previous issue or PR regarding this, but couldn't find one.
=> Use a custom options type for room::Common::messages

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk/src/encryption/verification/sas.rs
This is the second part of #449 as a separate PR as requested:
The `done` message should be sent when a participant has verified the emojis and received a mac from the other party, and in particular not only when the get a done from the other side. Otherwise both parties get stuck waiting to receive a `done` from the respective other.
As this PR includes the test of the full request-initiated verification, should be merged after #459 (which is also why the test will fail until then).
=> Fix both parties getting stuck in a "waiting for done" state in verification

crates/matrix-sdk/src/config/client.rs
If default features `sled_state_store` and `sled_cryptostore` aren't enabled, then passing a store path to the Client does nothing.
This change follows a discussion in the matrix-rust-sdk room on Matrix, where I was confused about my program's behaviour because it never saved anything to the `store_path` I passed it. It turned out that I had disabled default features, including `sled_state_store`.
Now other users should be warned, *if* they read the documentation.
=> docs(sdk): document features needed for store_path

crates/matrix-sdk/src/encryption/verification/sas.rs
The method sets the proper CancelCode for the case when SAS doesn't
match on both devices.
=> Add method to mismatch SAS verifications

crates/matrix-sdk-crypto/src/file_encryption/attachments.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/README.md, crates/matrix-sdk/examples/image_bot.rs, crates/matrix-sdk/src/attachment.rs, crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/joined.rs
- Allow to send info and thumbnail for attachments
- Method to generate thumbnails behind `image_proc` feature flag. It seems like the only thing preventing to use `image` in wasm is the rayon dependency so I also added the `image_rayon` feature.
- Method to send attachment with generated thumbnail
I tested it locally with a modified `image_bot` example and it works fine both in encrypted and normal rooms. I'm not sure how to add tests for the image generation feature.
=> feat(sdk): Generate thumbnails for image attachments

crates/matrix-sdk-test/src/appservice.rs, crates/matrix-sdk-test/src/lib.rs
In the latest version of Ruma, the event enums no longer implement `Serialize` because it was somewhat of a footgun when custom / unrecognized events were involved.
=> Stop relying on event enum `Serialize` impls

crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/config/request.rs
This PR fixes the issue #483 
Only open points from my side:
- Is there anywhere I should document the new behavior?
- are the tests enough, or should there be one for each changed method?
=> Short retry for intial client methods to prevent long retry cycles

crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/sled_store.rs, crates/matrix-sdk/src/client.rs
This changeset addresses the deadlock in the timeline tests when running with the memory store. The problem comes about because the implementation of the memory store uses locks around the timeline cache and under the circumstance of figuring out the timelines does not match up, tries to delete the cache for the entry for which it attempts to acquire the lock that it still holds.
This PR refactors that code base to not run into that problem but only remove the timeline cache when the lock has been released.
That, however, surfaced a problem in the tests and the API design itself: what to do when the timeline cache is removed while a stream is still handed out to the outside. The API is unclear what should happen and sled- and memory store actually have different behaviors. This problem …
=> fix(MemoryStore): undeadlock timeline saving

crates/matrix-sdk/src/client.rs
This removes the `info!()` log because of
https://github.com/rust-lang/rust/issues/93274
=> Ensure Client::login_with_sso() to be send

crates/matrix-sdk/src/http_client.rs
I would have liked to integrate ruma-client but it seems like due to wasm and request retrying¹ that's more involved.
¹ serializing the request once per retry would be a solution, but not a nice one
=> Refactor request sending

.github/workflows/ci.yml, crates/matrix-sdk-crypto/src/backups/keys/backup.rs, crates/matrix-sdk-crypto/src/backups/keys/mod.rs, crates/matrix-sdk-crypto/src/backups/keys/recovery.rs, crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-sled/src/cryptostore.rs, xtask/src/ci.rs
This PR fixes backup support in the crypto crate.  It's only used by Element Android and is not exposed through the main crate, so it was skipped by CI and accidentally broken by a couple of innocently looking PRs.
The `RecoverKey` struct is now available without the feature flag, so stores don't have to juggle the feature around.
This also adds a CI job to check that we don't rebreak it, an xtask is also provided for your convenience.
=> Fix the room key backup support in the crypto crate

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk-indexeddb/src/safe_encode.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/bin/state_inspector.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/common.rs
I'd like to remove the `EventType` enum from Ruma in the future, and we've had these more fine-grained types for a while, the right people just weren't aware of them it seems 😄
=> Use fine-grained *EventType types

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/lib.rs, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-sled/src/lib.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/examples/autojoin.rs, crates/matrix-sdk/examples/command_bot.rs, crates/matrix-sdk/examples/wasm_command_bot/Cargo.toml, crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/config/client.rs, crates/matrix-sdk/src/config/mod.rs, crates/matrix-sdk/src/docs/encryption.md, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/store.rs, xtask/src/ci.rs
context: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$yh6vVuOVhR_RWgdtHY6_HiFBgv_R-46TK-E-B3HwQlw?via=matrix.org&via=kde.org&via=one.ems.host
The main goal of this work is to remove the default magic that happens to create the stores and have something more explicit.
I ended up creating a mix of what was discussed as it made more sense to me looking at how the code is organized. By default I could have reused `BaseClientConfig` but it doesn't make sense to expose it in the main crate as the `BaseClient` doesn't mean anything there, so I created `StoreConfig`.
By default a `MemoryStore` is always used now. The stores have to be explicitely opened and provided to the `ClientConfig`. There are two helper functions to do that in the store crates `open_stores_with_*` and `make_config`.
=> Change store initialization

crates/matrix-sdk/examples/cross_signing_bootstrap.rs, crates/matrix-sdk/examples/emoji_verification.rs, crates/matrix-sdk/src/client.rs, crates/matrix-sdk/src/docs/encryption.md, crates/matrix-sdk/src/encryption/identities/devices.rs, crates/matrix-sdk/src/encryption/identities/mod.rs, crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/encryption/verification/sas.rs, crates/matrix-sdk/src/room/common.rs
Lowers the API surface of Client.
I'm wondering if I should rename it to `EncryptionManager` to make its use more obvious (and then `Account` would be renamed to `AccountManager` too).
=> sdk: Create Encryption struct

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/types/cross_signing_key.rs, crates/matrix-sdk-crypto/src/types/device_keys.rs, crates/matrix-sdk-crypto/src/types/mod.rs, crates/matrix-sdk/src/encryption/mod.rs
This is a continuation from https://github.com/matrix-org/matrix-rust-sdk/commit/f4010b597f289e10481f4333a4ed9003833f0fc9. We're still not using vodozemac types in these types, this is a bit of a far reaching change and will come in a separate PR.
=> Use customized device and cross signing key types.

crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs
This fixes the breaking gap in the timeline when reading the events from
store.
=> store: Make sure that event position in store is contiguous

crates/matrix-sdk/src/room/common.rs
My goal is to retrieve the `m.fully_read` account data, but I'm thinking generic methods are more useful for custom/new account data types.
=> feat(sdk): Retrieve account data from room::Common

crates/matrix-crypto-ffi/src/lib.rs, crates/matrix-crypto-ffi/src/olm.udl
The field is called message which clashes with the field of the same name in the Kotlin Exception class.
=> fix(crypto-ffi): Rename the error message field for MigrationError

crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/examples/timeline.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/common.rs
Feature-gated with `experimental-timeline` for base, sled, indexeddb and the main SDK-crates.
Note: this has to use weak dependencies in order to allow proper switching it on from the main crate.
=> Put timeline behind a feature-flag

crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-sled/src/lib.rs, xtask/src/ci.rs
`make_store_config()` is enabled for both of the features we have in the sled crate, but `StoreConfig` was only imported if the `state-store` feature was enabled.
We're also building the `crypto-ffi` crate separately in the`xtask ci` target, which uses the sled store with the `crypto-store` feature, which makes sure we don't regress. Not sure if we want to add a separate `sled` target to `xtask`.
=> fix(sled): Fix the compilation if only the cryptostore is enabled

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This patch moves all the important identities that we need for verification into the already existing IdentitiesBeingVerified struct.
It adds a method to get those identities to the store, and streamlines our to-device and in-room verification constructors.
This is the first part of #399 and incidentally fixes a bug where the `started_from_request` flag wouldn't be set correctly for in-room verifications. The buggy constructor has been removed.
=> refactor(crypto): Simplify the verification object constructors

crates/matrix-sdk-base/README.md
I've recently opened https://github.com/matrix-org/matrix-rust-sdk/pull/645. I may update this PR if I find other typos instead of opening a new PR everytime.
=> docs(sdk-base) Fix a typo in the `README.md`

crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/http_client.rs
Since the server versions isn't modified we can use a OnceCell and
get rid of the Mutex.
=> Use OnceCell to store server versions

crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk/src/lib.rs
- Fix a typo in its docs
- Reexport it from the sdk crate so it can be used.
=> DisplayName fixes

crates/matrix-crypto-ffi/src/machine.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-indexeddb/src/cryptostore.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-sled/src/cryptostore.rs, crates/matrix-sdk-sled/src/state_store.rs
Downstream applications may wish to implement their own StateStore/CryptoStore and may not use anyhow.
This commit switches the Database backend error from `anyhow::Error` to `Box<Error>`, which is more compatible with other rust error libraries.
If you are using anyhow or eyre, you need to map the error like this:
```rust
expr.map_err(|e| StoreError::Backend(e.into())
```
If your error types implement std::error::Error, you need to map the error like this:
```rust
expr.map_err(|e| StoreError::Backend(Box::new(e)))
```
Special thanks to @jplatte for the idea.
Replaces/Closes #643
=> [Breaking Change] Use boxed errors in StoreError

crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/utils.rs, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/src/encryption/mod.rs
=> More redaction improvements

crates/matrix-sdk-base/src/client.rs
I'm currently implementing notifications for fractal.
If I had e.g. element concurrently open and sent a message into a room, I would get a notification from fractal.
This fix avoids creating notifications originating from the userId of the client
=> fix(sdk): Don't send notifications for your own user

crates/matrix-sdk-indexeddb/src/cryptostore.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/cryptostore.rs
Prevent metadata leaking by using the store-cipher (if given) to encrypt the indexeddb keys, too.
=> fix(indexeddb): encrypt crypto-store key

crates/matrix-sdk-base/src/client.rs
Minor bugfix that otherwise would have exploded, I'm so sorry
Blocks #665
=> fix(sdk): Fix regression

crates/matrix-sdk-crypto/src/machine.rs
This PR removes the mention of the `OlmMachine::should_share_group_session` method in the documentation. It also removes manual links, so that `rustdoc` can detect whether a function is missing or not.
=> docs(crypto): Remove outdated documentation and use auto-link

crates/matrix-sdk-test/src/test_json/sync.rs, crates/matrix-sdk/src/client/mod.rs
The test json used for mocking a sync response contained an ill-formed
event with a room_id key present in the event. Since the deserialization
ignores the room_id key, this resulted in the client's membership state
evaluating to left going by the contents of the state events, despite
the room being in the "joined" section of the sync response. This is a
violation of the spec.
I chose to remove the event rather than correct it and move it to the "left" section of the responses, as the one test that failed after I removed the event assumed the event applied to `!SVkFJHzfwvuaIEawgC:localhost` rather than `!roomid:room.com` specified in the event itself.
See also #507.
=> test(base): Remove invalid sync event from test json

crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs
I [asked](https://github.com/danieldg/async-once-cell/issues/1) for a `new_with` so we don't need different initialization of tokio's and async_once_cell's `OnceCell` types, the author wrote it and published it super fast! 🥳
=> Upgrade async-once-cell to 0.3.1

crates/matrix-sdk-base/src/rooms/mod.rs
… instead of taking into account an older maximum as well.
I'm pretty sure this is the desired behavior for normalized power levels. For example, if a room uses standard power levels of 0, 50 and 100 for most users but one person has 200, it makes sense for only them to show up as an admin. However, if they downgrade themselves to 100, all users with that power level should then be shown as admins rather than none of them.
=> fix(base): Make max_power_level reflect the current maximum only

codecov.yaml
=> Improve CI coverage reporting

.github/workflows/docs.yml
This should drastically reduce the repository size. ([docs](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-force-orphan-force_orphan))
Fixes #676.
=> fix(docs): Remove history gh-pages branch

crates/matrix-sdk-appservice/examples/appservice_autojoin.rs
The already registered user check could probably also happen inside `register_virtual_user` - but not sure if there are scenarios where consumers might want to know that the error happened.
Context: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$8QgFf_IBjMBGojAri_aZeGBLuC1rU-O0Ni7Fy3s3G1c?via=matrix.org&via=famedly.de&via=gnome.org
=> feat(appservice): Improve autojoin example

crates/matrix-sdk-test/src/test_json/mod.rs, crates/matrix-sdk/src/client/mod.rs
Let me try to fix my own issue https://github.com/matrix-org/matrix-rust-sdk/issues/673.
The method is named after ruma. I don't know if it should be kept the same but if not, I can give it a better name.
=> feat: add .get_alias() method to the client

crates/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-crypto-ffi/src/olm.udl, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/types/cross_signing_key.rs, crates/matrix-sdk-crypto/src/types/device_keys.rs, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-qrcode/src/types.rs
This is mainly so we switch from the `&str` libolm pickle key to a `&[u8]` one in the `matrix-sdk-crypto-ffi` crate.
=> chore(crypto): Bump vodozemac

crates/matrix-sdk-crypto-ffi/Cargo.toml
Updates `crypto-ffi` to output a static library to wrap in a Swift Package, which is the same approach being taken with`matrix-sdk-ffi` and [`matrix-rust-components-swift`](https://github.com/matrix-org/matrix-rust-components-swift).
=> fix(crypto-ffi): generate static crypto-ffi library for iOS clients

crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs, crates/matrix-sdk-crypto/src/olm/utility.rs, crates/matrix-sdk-crypto/src/types/cross_signing_key.rs, crates/matrix-sdk-crypto/src/types/device_keys.rs, crates/matrix-sdk-crypto/src/types/mod.rs, crates/matrix-sdk-crypto/src/types/one_time_keys.rs, crates/matrix-sdk-crypto/src/verification/mod.rs
The main purpose of this PR is to have stronger typing for our signatures, we directly deserialize into a vodozemac type for the known signature types.
This isn't directly useful right now, but hopefully we'll be able to make our signature checking a bit less reliant on `serde_json::Value`.
=> Convert the `Signatures` type alias into a struct

crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-store-encryption/Cargo.toml
- add `all-features` for docs.rs build on sled and indexeddb-store
- add docsrs feature on store-encryption (but not all features, to not enable the `js` features)
fixes #694
=> docs: configure docs.rs build to contain more features

benchmarks/benches/crypto_bench.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto-js/src/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk/src/room/joined.rs
As discussed with @poljar, the Matrix event we are creating is
`m.room.key`, so it's preferable to rename the function
`share_room_key`. Note: Olm calls the things an inbound group session,
that's where the name comes from, but it's not aligned with the
specification.
Thoughts?
=> feat: Rename `OlmMachine.share_group_session` to `OlmMachine.share_room_key`

crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/mod.rs
The whole machine is nowadays exposed through the base Client, so no need to re-expose individual methods that don't add more functionality.
=> Remove a bunch of OlmMachine wrapper methods

crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/encode_key.rs, crates/matrix-sdk-sled/src/state_store.rs
... if a cipher is provided.
Effected:
every other instance of `insert` (in `sled`) and `set_key_val` (in `indexeddb`) has a proper key and value serialization as far as I could see.
fixes #609 and brings some more integration tests to cover these functions (though whether they en- & decrypt is black boxed and thus not something we can tests for :( )
=> Ensure all data state stores save is encrypted 

.github/workflows/ffi.yml, bindings/apple/debug_build_xcframework.sh
Use the nightly toolchain together with the newly introduced `target-applies-to-host` on the sdk-ffi crate debug builds to avoid cache corruption issues. This happens because the `rustflags` aren't being respected when using a cargo --target.
Also switch back to debug mode as the internal tokio crashes went away.
=> Nightly ffi crate debug builds

crates/matrix-sdk-appservice/src/lib.rs
Whoops.
Correct the inconsistency between the keys used for reading and writing the membership of a virtual user in the appservice's namespace. The separator was not placed correctly writes, and reads used the full mxid, while writes used only the localpart.
=> fix(appservice): Make membership keys consistent

README.md
Works around https://github.com/rust-lang/rust/issues/97881
=> chore: Fix `main` docs link in readme

crates/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto-ffi/src/olm.udl, crates/matrix-sdk-crypto-js/src/requests.rs, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/mod.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk/src/encryption/mod.rs
This PR adds a mechanism to wait for a `/keys/query` response to be received by the `OlmMachine`.
Namely, the sync response will contain only a notification that a user has changed their devices in some way. We need to send out a `/keys/query` request to actually know what devices were added/changed/removed.
The time between the received notification from the sync response and sending/receiving/processing the matching `/keys/query` response is a race where we have an outdated device list. When encrypting a room event we need to know the accurate list of devices a user possesses, so each and one of their devices gets a copy of the room key.
Users might also want to verify a device while this race is going on. Not finding the correct device.
This PR solves the first problem by waiting for a …
=> Add ways to wait for a `/keys/query` request to be done

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/http_client.rs
Reduces unnecessary sharing of interor-mutable types, simplifies an `Arc` to `Box` and adds a little bit more logging (from #743).
Fixes #746.
=> Various code structure improvements

crates/matrix-sdk-appservice/examples/appservice_autojoin.rs, crates/matrix-sdk-appservice/src/lib.rs
I wasn't entirely sure where the best place to put the cached regexes were.
=> perf(appservice): Cache namespace regexes

crates/matrix-sdk-crypto/src/backups/mod.rs, crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/pk_signing.rs, crates/matrix-sdk-crypto/src/olm/utility.rs
This should mostly remove the wild west of signature verification. We define a trait that tells us which objects can contain signatures and thus can be passed on to signature verification methods.
It also should be slightly more efficient, since we removed a bunch of duplicate canonicalization steps.
This requires #725 and #724.
=> Introduce a SignedJsonObject trait

crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/requests.rs
The spec claims that we should cancel verifications if multiple verifications are attempted at once[[1]]:
> When the same device attempts to initiate multiple verification
attempts, the recipient should cancel all attempts with that device.
This patch adds support for this.
[1]: https://spec.matrix.org/v1.2/client-server-api/#error-and-exception-handling
=> Cancel the verification flow if we have multiple verifications

.github/workflows/coverage.yml, codecov.yaml, tarpaulin.toml
This patch fixes https://github.com/matrix-org/matrix-rust-sdk/issues/748 and https://github.com/matrix-org/matrix-rust-sdk/issues/749.
The first patch uses [the Ignoring Paths feature](https://docs.codecov.com/docs/ignoring-paths) of codecov.io. I hope it will exclude entirely the `crates/matrix-sdk-crypto-(js|nodejs)/` paths from their UI and code coverage score.
The second patch updates the `tarpaulin` configuration file to:
1. fix the `exclude-files` paths (because they were invalid),
2. `exclude` crates entirely
3. be used in the CI directly, so that we don't have different configurations.
=> chore(test):  Code Coverage must ignore some `matrix-sdk-crypto-(js|nodejs)`

.cargo/config.toml, .github/workflows/docs.yml, xtask/src/main.rs
… which partially broke our docs.
I decided not to change back the link in README.md because most people are likely going to look for the main crates' docs and that's what what we link to on docs.rs as well. (although there we have no choice anyways)
=> chore: Work around a cargo bug

labs/sled-state-inspector/Cargo.toml, xtask/Cargo.toml
https://github.com/clap-rs/clap/issues/3822
=> Prevent clap upgrades beyond 3.2

crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-appservice/tests/tests.rs
commit 1: Don't assume virtual client membership is join if none is stored, since that leads to a client being told it's joined in rooms it has no membership of. The main appservice client still assumes it's joined every room it receives transaction events about.
commit 2: Test that virtual clients get assigned the correct membership to rooms when processing received transactions.
=> Appservice virt member test

codecov.yaml
First patch remove `labs` from the projects list. It's already part of the `ignore` section.
Second patch exclude `matrix-sdk-indexeddb` from the code coverage report. It's already excluded from Tarpaulin, but not for codecov.io.
It's a sequel of #748.
=> chore(test): Remove `labs` from the projects + exclude `matrix-sdk-indexeddb` from code coverage report

.github/workflows/ci.yml, crates/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-crypto-nodejs/README.md, crates/matrix-sdk-crypto-nodejs/package.json, crates/matrix-sdk-crypto-nodejs/src/machine.rs, crates/matrix-sdk-crypto-nodejs/tests/machine.test.js
This patch fixes https://github.com/matrix-org/matrix-rust-sdk/issues/755.
This patch adds the `store_path` and the `store_passphrase` arguments to the `OlmMachine` constructor to use a `CryptoStore` instead of having an in-memory Olm machine.
=> feat(crypto-nodejs): Add `store_path` and `store_passphrase` to the `OlmMachine` constructor

labs/sled-state-inspector/Cargo.toml, xtask/Cargo.toml
Deprecations are now opt-in behind a feature.
=> Undo pinning of clap

bindings/apple/MatrixSDKCrypto.podspec, bindings/apple/README.md, bindings/apple/build_crypto_xcframework.sh, crates/matrix-sdk-crypto-ffi/src/olm.udl, crates/matrix-sdk-crypto-ffi/uniffi.toml
Provide scripts and tooling to compile and package matrix-sdk-crypto-ffi project, to be used with existing [Matrix iOS SDK](https://github.com/matrix-org/matrix-ios-sdk). Changes in this PR are only the first step to get a precompiled library up and running and do not yet include further automation of publishing these artifacts in [GitHub releases](https://github.com/matrix-org/matrix-rust-sdk/releases/tag/matrix-sdk-crypto-ffi-0.1.0).
This PR contains the following changes:
1. Duplicate and tweak an existing `build_xcframework.sh` script, which chooses `matrix-sdk-crypto-ffi` crate to compile, only compiles for iOS targets, and produces a zip file ready to be uploaded to GitHub releases
2. Define `MatrixSDKCrypto.podspec` which can be pushed directly to public CocoaPods repo, see …
=> Build Crypto iOS framework

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/mod.rs
I'm skeptical about the separate `Store` type, but it's not that easy to just remove it, so this is the smallest change I could find to move in that direction. `AmbiguityCache` was using a `Store`, but only ever calling `StateStore` methods on it so I replaced its usage of `Store` with using the underlying `Arc<dyn StateStore>` directly.
=> chore: Replace usage of Store with Arc<dyn StateStore>

.github/workflows/appservice.yml, .github/workflows/ci.yml, .github/workflows/wasm.yml, xtask/src/ci.rs
> [`cargo-nextest`](https://nexte.st/index.html) is a next-generation
> test runner for Rust projects.
This patch installs and uses `nextest` to run our own tests.
Comparing `cargo test` and `cargo nextest` with hyperfine provides the
following results:
```
$ hyperfine 'cargo test --workspace' 'cargo nextest run --workspace && cargo test --doc'
Benchmark 1: cargo test --workspace
Time (mean ± σ):     51.785 s ±  2.066 s    [User: 183.471 s, System: 10.563 s]
Range (min … max):   49.151 s … 56.641 s    10 runs
Benchmark 2: cargo nextest run --workspace && cargo test --doc
Time (mean ± σ):     44.556 s ±  0.894 s    [User: 192.213 s, System: 11.441 s]
Range (min … max):   43.170 s … 45.762 s    10 runs
```
Benchmark 2 is 1.16 times faster than Benchmark 1
=> test: Run tests faster with `nextest`

bindings/matrix-sdk-crypto-nodejs/package.json
For some unknown reasons, sometimes, randomly, one test (initializing
an `OlmMachine` with a local store with a passphrase) can take more
than 5s, only on Github Actions. Let's increase the test timeout value
so that the entire test suite doesn't fail.
=> test(crypto-nodejs): Increase timeout

bindings/matrix-sdk-crypto-nodejs/src/identifiers.rs, bindings/matrix-sdk-crypto-nodejs/src/machine.rs
In async functions, the Node.js GC may or may not (that's a random
behavior) collect the arguments passed to the function as soon as it
returns. The function may not be executed yet, since it's async. Thus,
it leads to memory corruption: The function tries to read later on the
value inside an argument and… it crashes at best.
To avoid this bug, there is no other choice than cloning the values
before the function returns, in its “sync path” (so before any
transformation of an `.await` point into an “async block”).
The performance impact is not “massive”, I'm not sure it could be
noticeable easily since it is most of the time related to identifiers
(e.g. `UserId`), which are cheap to clone. I have to find the balance
here, and cloning offers the best trade off from my point of view.
=> fix(bindings/cryto-nodejs): Fix memory corruption in async functions

bindings/apple/build_crypto_xcframework.sh
This PR fixes build errors in the `build_crypto_xcframework.sh` script.  Fixes issue #823
=> Fix build errors

crates/matrix-sdk/src/http_client.rs
Without this fix a potentially provided per-request config gets ignored.
=> fix(sdk): Use the local config variable to decide identity assertion

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/types/events/mod.rs, crates/matrix-sdk-crypto/src/types/events/room_key.rs, crates/matrix-sdk-crypto/src/types/events/secret_send.rs, crates/matrix-sdk-crypto/src/types/events/to_device.rs, crates/matrix-sdk-crypto/src/types/mod.rs, crates/matrix-sdk-crypto/src/verification/event_enums.rs, crates/matrix-sdk-crypto/src/verification/mod.rs
This patch adds customized event types, currently only for the m.room_key and m.secret.send to-device events.
This allows us to:
a) Deserialize the session_key field into a vodozemac type
b) Control when we zeroize secrets better
=> feat(crypto): Customized event types

.gitignore, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/lib.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs
This PR adds a basic authentication service to the FFI that abstracts away the client until a login has been completed successfully. Additionally it adds
- An `authentication_issuer` property to the SDK client for OIDC detection.
Always happy to learn of any changes that would make this into more idiomatic Rust :)
=> Add an authentication service to the FFI

bindings/matrix-sdk-crypto-nodejs/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/src/attachment.rs, bindings/matrix-sdk-crypto-nodejs/src/lib.rs, bindings/matrix-sdk-crypto-nodejs/tests/attachment.test.js, bindings/matrix-sdk-crypto-nodejs/tests/machine.test.js, crates/matrix-sdk-crypto/src/file_encryption/attachments.rs, crates/matrix-sdk/src/encryption/mod.rs
This patch fixes https://github.com/matrix-org/matrix-rust-sdk/issues/796.
This patch provides a new API to encrypt and decrypt attachment, i.e. big buffer of type `Uint8Array`.
This patch also fixes a bug in `matrix_sdk_crypto::MediaEncryptedInfo` where its `web_key` field should serialize to and deserialize from `key` to respect [the specification](https://spec.matrix.org/v1.2/client-server-api/#extensions-to-mroommessage-msgtypes).
It's based on `matrix_sdk_crypto::AttachmentEncryptor` and `AttachmentDecryptor`.
~~Note: I'm really not happy with the fact `EncryptedAttachment.encryptedData` returns a **copy**. But we cannot return a `&T` with `napi-rs`. I tried to create a new buffer that references data from elsewhere, like with …
=> feat(bindings/crypto-nodejs): Implement an `Attachment` API.

crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-appservice/tests/tests.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/event_handler.rs, crates/matrix-sdk/tests/integration/client.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/room/common.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/room/left.rs
The issue with mockito is that it uses only one server so all the tests must be run sequentially. Wiremock uses a pool of servers so the tests can be run in parallel.
On my machine, the matrix-sdk integration tests took ~3.3s with mockito. With wiremock they now take ~1s, which is almost 70% quicker and the difference should grow with the number of tests.
It also avoids an issue I encountered at some point where all the tests hang if a single test hangs. It's then easier to find out which test is the culprit.
=> test: Replace mockito with wiremock

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/http_client.rs
=> fix(sdk): Can't assert identity without session

crates/matrix-sdk-appservice/examples/appservice_autojoin.rs, crates/matrix-sdk-appservice/src/event_handler.rs, crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-appservice/src/registration.rs, crates/matrix-sdk-appservice/src/virtual_user.rs, crates/matrix-sdk-appservice/tests/tests.rs
Since the `lib.rs` was slowly growing a bit too large and covering multiple contexts it was about time to refactor a bit. Also clarified the implicit behavior which special-cases the ` sender_localpart` user.
- Clarify why we create a virtual user for the `sender_localpart` on `AppService` construction
- Drop the methods `register_event_handler` and `register_event_handler_context`, so the consumer has to be explicit
- Drop the method `get_cached_client` as it's already covered by the method `virtual_user`
- Move `create_session` into the `VirtualUserBuilder`, as it's only used there
- Rename `virtual_user_client*` to `virtual_user*` to make it more concise 
- Make `NamespaceCache` private since there's no reason to expose it
- Split out `AppServiceRegistration` and `VirtualUserBuilder` …
=> refactor(appservice)!: Improve API and cleanup docs

bindings/matrix-sdk-crypto-js/package.json
Fix #843.
Windows doesn't support `KEY=value` in its shell to define an environment variable. We must use `set KEY=value` but, in this case, it no longer works on Unix-like OS properly inside NPM.
A common solution, sadly, is to use another NPM package, called [`cross-env`](https://www.npmjs.com/package/cross-env). That's what this patch does.
I wonder whether it is sensible to run the CI on Windows for this project. Wasm is portable so we don't really care about that usually; in this case it would only be useful to test the build system. I'm embarassed by the time and the energy (i.e. electricity) it will take “just” to see if `npm run build` runs correctly on Windows. Let's assume for now we will have issues raised by contributors (not by users, they won't have to build the Wasm module) …
=> fix(bindings/crypto-js): Use `cross-env` to pass envvar on Windows

crates/matrix-sdk-appservice/src/lib.rs
Allows doing things like
- Check all constructed virtual users for something specific, such as whether they joined a room
- Check which virtual user was already constructed
- Drop virtual user clients
=> feat(appservice): Add method to get virtual user map

.github/workflows/bindings_ci.yml, bindings/apple/MatrixRustSDK.xcodeproj/project.pbxproj, bindings/apple/MatrixRustSDK/MatrixRustSDK-Bridging-Header.h
CI builds are now failing because the biding tests are looking for iOS 15.4 and the runner has been updated to 15.5. 
This PR will allow the tests to run on **any** iPhone 13 simulator no matter the OS version.
=> Fix Apple binding tests

crates/matrix-sdk-crypto/src/verification/requests.rs
Fixing a [new clippy-lint that appeared on our CI after merging to main](https://github.com/matrix-org/matrix-rust-sdk/runs/7406421293?check_suite_focus=true#step:5:711)
=> style(crypto): use matches for legibility

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs
This PR removes the separate calls for `homeserver()`, `authentication_issuer()` and `supports_password_login()`, instead wrapping them up in a value that can be requested via `homeserver_details()` with a single call.
`use_server` has also been renamed to `configure_homeserver` for a bit more clarity.
=> Add a `HomeserverLoginDetails` to the FFI's auth service.

benchmarks/Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-test/Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/joined.rs, labs/sled-state-inspector/Cargo.toml
This gets rid of the need to have a separate `ruma-client-api` dependency to enable the `unstable-msc2965` feature.
=> chore: Update Ruma

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sync.rs
If the last sync was less then a 1s ago we wait for a 1s, it doesn't
make sense to wait an additional second on an error. Also the stream
sync api returns the error after a delay of 1s, which doesn't make
sense.
=> client: Remove redudant delay after sync error

crates/matrix-sdk/src/event_handler.rs
It wasn't actually testing typing and power-levels event handlers before.
Thanks @docweirdo for finding this.
=> chore(sdk): Fix event handler test

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs
This PR is likely a temporary addition until #859 is implemented to allow for https://github.com/vector-im/element-x-ios/issues/137 to be completed with the proof of concept implementation.
The new method first creates an in-memory client to perform a `/whoami` and get the user ID and device ID. Then it creates a second client with a store path set and sets this one up for real.
Forked from #860 so would need to wait for that to be merged first.
=> Add restore_with_access_token to the FFI auth service.

crates/matrix-sdk-appservice/examples/appservice_autojoin.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_handler.rs
This PR implements the ability to remove a previously registered event handler.
To remove the event handler, the struct `EventHandlerWrapper` containing the actual handler and an `EventHandlerHandle` is saved in the HashMap for all event handlers instead of event handlers directly. Client.register_event_handler was amended to return an instance of `EventHandlerHandle` associated with the registered handler, which can later be used to remove the event handler with `Client.remove_event_handler`. The Handle contains a uniquely generated ID and the event ID which the event handler is interested in, so the event handler can be removed only with the handle.
This is a breaking change since it removes the method chaining functionality of `Client.register_event_handler`, which is a conscious …
=> feat(sdk): Implement remove_event_handler

bindings/apple/build_xcframework.sh, crates/matrix-sdk/src/client/builder.rs
Entering a bad URL would leave discovery hanging.
Additionally adds a small tweak to the XCFramework script to indicate progress through the task.
=> Fix discovery of HS with invalid URL.

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/file_encryption/attachments.rs, crates/matrix-sdk-crypto/src/file_encryption/key_export.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk/tests/integration/client.rs, crates/matrix-sdk/tests/integration/room/joined.rs
The main new warning was uses of `assert!(x.is_ok())` or `assert!(x.is_err())` while unwrapping gives better error messages.
=> chore(ci): Fix new clippy warnings

.editorconfig, .github/workflows/documentation.yml
Adding an `.editorconfig` in the root to ensure the editors do all the line-endings as we want them to.
=> build: Adding .editorconfig

.github/workflows/documentation.yml
We see moving bindings docs into the exising directory fails often on CI. This creates a new folder and moves all the different docs into that before publishing this folder instead of the previous one.
=> Fix documentation generation

crates/matrix-sdk-sled/build.rs, crates/matrix-sdk/build.rs, crates/matrix-sdk/src/client/login_builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs
… instead of through `compile_error!` invocations. This helps avoid unhelpful errors from the unsupported feature configuration by aborting compilation earlier.
=> refactor(sdk): Check permissible feature configuration in build script

bindings/matrix-sdk-crypto-js/package.json, bindings/matrix-sdk-crypto-nodejs/package.json
We are effected by https://github.com/yargs/yargs-parser/issues/452
through the transient dependency of jest on yargs
=> build(crypto-js): Pin yarg-parser to 21.0.1 to prevent upgrade bug

.github/workflows/benchmarks.yml, .github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/documentation.yml, .github/workflows/style.yml, tarpaulin.toml
Hopefully this is going to fix wrong reports like the one on #921.
Docs: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
=> ci: Checkout head ref instead of merge commit for coverage

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/tests/integration/client.rs
A user shouldn't need to change the homeserver manually after creating the client.
=> fix(sdk)!: Make set_homeserver private

examples/autojoin/Cargo.toml, examples/command_bot/Cargo.toml, examples/cross_signing_bootstrap/Cargo.toml, examples/custom_events/Cargo.toml, examples/emoji_verification/Cargo.toml, examples/get_profiles/Cargo.toml, examples/getting_started/Cargo.toml, examples/image_bot/Cargo.toml, examples/login/Cargo.toml, examples/timeline/Cargo.toml, examples/wasm_command_bot/Cargo.toml, labs/sled-state-inspector/Cargo.toml, testing/matrix-sdk-test-macros/Cargo.toml, testing/matrix-sdk-test/Cargo.toml, xtask/Cargo.toml
This reduces the amount of "running 0 tests" spam when testing the whole workspace and makes testing a little faster overall.
I've left out the crates that *currently* don't have tests but might get some in the future (this includes all the binding crates where I wasn't entirely certain, since one of them actually does have a test).
=> chore: Disable testing of crates without tests

crates/matrix-sdk-appservice/examples/appservice_autojoin.rs, crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk/README.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_handler.rs, crates/matrix-sdk/src/room/common.rs, examples/autojoin/src/main.rs, examples/command_bot/src/main.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs, examples/image_bot/src/main.rs, examples/login/src/main.rs
Creating such a guard basically makes the event handler temporary, it will be removed again once the guard is dropped – e.g. because of a surrounding future being cancelled, or an error being propagated out of a function that stored the guard on the stack.
cc @docweirdo
=> Add EventHandlerDropGuard

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/http_client.rs
Allow to send authed requests when only the access token is available, it's a prerequisite for #859, to be able to call `/whoami` to get the user ID.
Remove the unreachable `UserIdRequired` error. Looking at the code, the errors in `.ok_or()` were never reached because, if the session was `None`, the other branch was used. I refactored the code to avoid unwrapping instead.
=> refactor(sdk): Don't require the whole `Session` for sending

.typos.toml, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, examples/emoji_verification/src/main.rs
A couple of errors slipped in when switching to our own customized event types with regards to relations.
Added some tests so we don't regress and manually checked that the example now works. 
This PR should fix the first part of #928.
=> Fix relations when encrypting and decrypting

crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_handler.rs
This allows capturing non-`Send` / -`Sync` values in handler closures.
I didn't add a test because this is going to be exercised by #868 anyways.
cc @docweirdo
=> fix(sdk): Further relax event / notification handler bounds on WASM

crates/matrix-sdk-common/src/timeout.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/types/events/mod.rs, crates/matrix-sdk-crypto/src/types/events/olm_v1.rs
This patch adds some more stronger guarantees that received room key events and other similarly security critical event types are only handled if they have been received over a secure Olm channel.
=> refactor(crypto): Utilize the decrypted Olm event type more

crates/matrix-sdk/src/event_handler.rs
Initial state events aren't actually received through sync, they're sent from the client to the server when creating a room.
This change makes it impossible to register event handlers for initial state events. Previously, this was allowed, but the event handler was never called.
=> fix(sdk)!: Remove SyncEvent implementation for InitialStateEvent

examples/wasm_command_bot/README.md
Updates the instructions for the `wasm_command_bot` example as outlined in [this issue](https://github.com/matrix-org/matrix-rust-sdk/issues/938#issuecomment-1214720184).
=> update instructions for wasm_command_bot example

crates/matrix-sdk-sled/src/encode_key.rs
The function is not used and Github Actions rightously complains about it.
=> fix(sled): Remove unused `from` on EncodeUnchecked

bindings/matrix-sdk-crypto-js/src/attachment.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-crypto-js/tests/attachment.test.js, bindings/matrix-sdk-crypto-nodejs/src/attachment.rs
Implement the `Attachment.encrypt` and `Attachment.decrypt` methods,
along with its `EncryptedAttachment` companion.
The trick is to avoid copies as much as possible. Instead of dealing
with `Uint8Array` as I've initially done, `&[u8]` and `Vec<u8>` is
passed instead. `wasm-bindgen` is smart enough to do as few copies as
possible (from JavaScript to Wasm's memory is required, and we don't
want to do more), while typing everything as `Uint8Array`.
`EncryptedAttachment.encryptedData` returns a copy of the data
everytime it is called, and that's the last copy I'm not happy with.
=> feat(crypto-js): Implement the Attachment API

Cargo.lock, benchmarks/Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/tests/integration/refresh_token.rs, crates/matrix-sdk/tests/integration/room/joined.rs, labs/sled-state-inspector/Cargo.toml, testing/matrix-sdk-test/Cargo.toml
Another on of those refactorings I've been thinking about for a while. @Hywan just reminded me of this possibility.
I'm not too sure about the upgrade path here. It should be simple enough for people who read the changelog, but I think we have experienced many people *not* doing that..
Looking for feedback on
* Is this a good idea?
* Naming
* Upgrade path
I also posted a very small related Ruma PR: https://github.com/ruma/ruma/pull/1259
=> refactor(sdk)!: Split strongly-typed state event functions into two

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/invited.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/left.rs
… and avoid unnecessary clones before calling them.
These constructors were never called from any other crate in the workspace, and I don't see why one would want to use them directly rather than use the other existing means to obtain a room object.
=> refactor(sdk)!: Make room type constructors private

.github/workflows/release_crypto_js.yml, bindings/matrix-sdk-crypto-js/package.json
This patch adds a new `npm run publish` script that:
1. Run `npm run prepublish` (which runs the `build` and `test` scripts),
2. Run `wasm-pack publish`.
Note 1: The `prepublish` script is using the `$npm_execpath`
environment variable instead of just “`npm`”, so that if someone is
using `yarn` or another JavaScript package manager, it _should_ work
(not tested yet).
Note 2: `wasm-pack publish` is run without running `wasm-pack login`
before that. _But_ we are updating the registry URL in the NPM
configuration file in the Github Action workflow, see below.
This patch then creates a new Github Action workflow that is triggered
when a new tag of the form `matrix-sdk-crypto-js-v[0_9]+.*` is
pushed. This workflow runs `npm run publish` basically, but before
that, it updates the NPM …
=> chore(crypto-js): Add a release workflow for `crypto-js`

Cargo.lock, benchmarks/Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/common.rs, labs/sled-state-inspector/Cargo.toml, testing/matrix-sdk-test/Cargo.toml
Required for one of the examples in #940 to not need an extra dev-dependency.
=> chore: Upgrade ruma

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/session_verification.rs, examples/autojoin/Cargo.toml, examples/command_bot/Cargo.toml, examples/cross_signing_bootstrap/Cargo.toml, examples/custom_events/Cargo.toml, examples/emoji_verification/Cargo.toml, examples/get_profiles/Cargo.toml, examples/getting_started/Cargo.toml, examples/image_bot/Cargo.toml, examples/login/Cargo.toml, examples/timeline/Cargo.toml
Unfortunately we still always pull in parking_lot 0.11 (sled, wasm-timer) which I suspect is not really needed, plus parking_lot 0.12 (but only on `target_os = "linux"` when checking / building `benchmarks`). That is, the overall reduction in dependencies is very small, but at least the parking_lot 0.12 dependency for wasm and macos through the examples is gone, so it should speed up those CI jobs a little bit.
=> Remove a few parking_lot dependencies for faster builds

bindings/matrix-sdk-crypto-js/src/identifiers.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/olm.rs, bindings/matrix-sdk-crypto-js/src/types.rs, bindings/matrix-sdk-crypto-js/src/vodozemac.rs, bindings/matrix-sdk-crypto-js/tests/identifiers.test.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js
This PR implements 2 new methods on `OlmMachine`: `sign` and `cross_signing_status`. It's basically a port from `crypto-nodejs` adapted for Wasm+JS.
=> feat(crypto-js): Implement `OlmMachine.sign` and `.cross_signing_status`

Cargo.lock, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-js/package.json, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-indexeddb/Cargo.toml
The `OlmMachine` constructor now has 2 more optional arguments:
`store_name` and `store_passphrase`, to use Indexed DB as the backend
to store the Olm machine keys, rather than having an in-memory Olm
machine.
Node.js is used to test our binding. Indexed DB is absent of
Node.js. So, firstly, we are using the [`fake-indexeddb`](https://www.npmjs.com/package/fake-indexeddb) JavaScript
library to mimic the same API inside Node.js. And, secondly, we use
our own fork of [the `indexed_db_futures` Rust crate](https://github.com/Alorel/rust-indexed-db) to provide add
support for Node.js too ([PR is
here](https://github.com/Alorel/rust-indexed-db/pull/11)). It
basically looks in the Node.js global environment if the `indexedDB`
getter is present, just like it is already done for `Window` on any …
=> feat(crypto-js): Add store configuration to the `OlmMachine` constructor

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/event_handler.rs, crates/matrix-sdk/src/event_handler/context.rs, crates/matrix-sdk/src/event_handler/maps.rs, crates/matrix-sdk/src/event_handler/mod.rs, crates/matrix-sdk/src/event_handler/static_events.rs
Plus a few refactorings to make the actual change easier, and the code more readable.
Motivation: We want to handle all timeline events in the event handler registered for the timeline API. If we just register event handlers for all known event types we'll miss custom ones, that we want to support for a "show hidden events" mode found in some Matrix clients (including Element).
=> feat(sdk): Allow event enums to be used as the first event handler argument

bindings/matrix-sdk-crypto-js/package.json
This patch introduces a new `pack` NPM script, which runs `wasm-pack
pack` behind the scene.
This patch modifies the `publish` NPM script to run the `pack` script
as a pre-script (so… in the `prepublish` script).
Finally, this patch no longer uses `$npm_execpath` as it doesn't work
on Windows. It should be `%npm_execpath%`. It's not obvious to make
scripts interoperable, so we will stick with `npm` for now.
Address #980.
=> chore(crypto-js): Add `npm run pack`

crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/mod.rs
Inbound group sessions would fail to be deserialized if there was a forwarding curve chain, this patch fixes it so we go through base64 when we deserialize this field.
=> fix(crypto): Fix the deserialization of inbound group group_sessions

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs
Exposes the account data from #964 through the FFI.
=> feat(bindings/ffi): Add account data.

examples/get_profiles/src/main.rs
Not sure why this isn't bothering the CI and if I'm the only poor sod running `xtask ci` locally but an error springs out:
This patch fixes this.
=> chore(examples): Use automatic links for some URLs

.typos.toml
Typos now ignores .lock files automatically without any configuration.
=> ci: Stop ignoring .lock files in typos config explicitly

crates/matrix-sdk/src/room/common.rs
Adds a getter for retrieving the client of rooms. This allows to create extension traits and such on rooms. For example, one could make methods to send custom events or join/leave without waiting for the sync.
=> feat: Expose client of rooms for extensions

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/gossiping/mod.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/types/events/mod.rs, crates/matrix-sdk-crypto/src/types/events/olm_v1.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk-crypto/src/types/events/room/mod.rs, crates/matrix-sdk-crypto/src/types/events/room_key_request.rs, crates/matrix-sdk-crypto/src/types/events/to_device.rs, crates/matrix-sdk-sled/src/crypto_store.rs, crates/matrix-sdk-sled/src/encode_key.rs
This prepares us for a brave new world where the `sender_key` gets removed from some events.
It is a prerequisite to resurrect #481.
=> Customized event types for room key request

examples/autojoin/src/main.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs
Spawn a task for accepting the invite otherwise the call never returns and sync stops.
As far as I can tell other examples are unaffected.
=> fix(examples): Fix examples that accept invites

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk/src/encryption/mod.rs
Also documents some errors to avoid clippy warnings.
=> feat(sdk): Re-export matrix-sdk-crypto errors

crates/matrix-sdk/src/event_handler/maps.rs, crates/matrix-sdk/src/event_handler/mod.rs, crates/matrix-sdk/src/event_handler/static_events.rs, crates/matrix-sdk/src/sync.rs
The change from the second commit was suggested by @gnunicorn a while ago. It doesn't add a lot of parallelism since it's probably not even common to have multiple event handlers that react to the same event at all, but it's the most we can do since we need distinct events to be handled sequentially in the general case (people can still parallelize themselves if they don't care about the order).
=> feat(sdk): Add support for AnySyncTimelineEvent in event handlers

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs
I originally wanted to post this PR months ago, but it got lost. The reason this function is deprecated is that it's kind of confusing to have client code pass the user ID twice when logging in (once for the builder, then the login API), and the alternative of `.server_name(user_id.server_name())` makes it more obvious what is going on.
=> refactor(sdk): Deprecate ClientBuilder::user_id

crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk/src/encryption/verification/mod.rs, crates/matrix-sdk/src/encryption/verification/sas.rs, examples/emoji_verification/src/main.rs
We now print a neater output in the emoji example:
Individual commits contain more detailed explanations.
=> Improve the emoji example a bit

crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/crypto_store.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk-store-encryption/src/lib.rs
This speeds up the crypto-store tests a lot.
I benchmarked the sled `crypto_store::tests` and `crypto_store::encrypted_tests` with this, it makes a huge difference:
```
tests before:  2.08s
tests after:   0.17s
encrypted_tests before:  11.69s
encrypted_tests after:   0.29s
```
=> test: Use a weak password hash for crypto-store testing

Cargo.lock, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs
Without the first commit, things break on `Cargo.lock` upgrade:
```
error: Only features sync,macros,io-util,rt,time are supported on wasm.
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.0/src/lib.rs:462:1
|
462 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Update Cargo.lock and fix wasm + tokio issue

crates/matrix-sdk-crypto/src/types/events/olm_v1.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-qrcode/src/error.rs, crates/matrix-sdk-qrcode/src/lib.rs, crates/matrix-sdk-qrcode/src/types.rs
This PR happens in 2 acts.
Allow `VerificationData` to receive a flow ID.
[This first patch](https://github.com/matrix-org/matrix-rust-sdk/commit/cc5034f4b990430036d23adad5baf9439e53c872) updates `VerificationData` to receive a flow ID,
represented as an owned `String`, instead of an `OwnedEventId`. Why?
Because QR code verification can happen outside a room. In such
scenario, there is no event ID, but a transaction ID, unified behind
the `matrix_sdk_crypto::FlowId` enum. `VerificationData` doesn't
really care about that details. Proof is that `QrVerificationData`
receives an owned `String`, which is then casted into an
`OwnedEventId` to match this API properly; but at the top, it just
receives a string.
This patch brings also a little bit of clean up while editing code
around.
[This …
=> feat(qrcode): Allow `VerificationData` to receive a flow ID

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-js/src/responses.rs, bindings/matrix-sdk-crypto-nodejs/src/responses.rs, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-crypto/src/backups/keys/backup.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs
These aren't really useful since they can be easily spoofed by any room key forwarder.
=> refactor(crypto): Remove the forwarding chains

crates/matrix-sdk/src/encryption/verification/mod.rs
To match errors from `QrVerificationData`.
=> fix(sdk): Re-export qrcode encoding and decoding error types

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs
I think the plan is to eventually add a higher level API here along with the react/unreact and edits, but for now here's a PR that adds the existing redact method to the FFI.
=> feat(bindings): Expose redact method to FFI.

Cargo.lock, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-js/package.json, bindings/matrix-sdk-crypto-js/src/device.rs, bindings/matrix-sdk-crypto-js/src/identifiers.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/requests.rs, bindings/matrix-sdk-crypto-js/src/store.rs, bindings/matrix-sdk-crypto-js/src/types.rs, bindings/matrix-sdk-crypto-js/src/verification.rs, bindings/matrix-sdk-crypto-js/src/vodozemac.rs, bindings/matrix-sdk-crypto-js/tests/device.test.js, bindings/matrix-sdk-crypto-js/tests/helper.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-crypto/src/verification/mod.rs
Related to https://github.com/matrix-org/matrix-rust-sdk/issues/1016.
This PR is quite important. It brings the Key Verification API to `crypto-js`, aka SAS, Emoji, QR Code and bootstraping cross stuff.
=> feat(crypto-js): Implement key verification

Cargo.lock, labs/jack-in/Cargo.toml, labs/jack-in/src/main.rs
Removes a vulnerable dependency (`traitobject`) from our dependency tree.
=> fix(jack-in): limit log4rs features to minimum

bindings/matrix-sdk-ffi/src/lib.rs
The swift side uses stderr as the default log destination and redirects that to a log file when no debugger is attached. This is important for getting rageshake log files from client devices. Rust on the other hand uses stdout by default. This PR switches the FFI layer to stderr as well.
I think there's also a discussion to be had on whether stderr should the default throughout the rust sdk or whether the destination should be configurable on the FFI layer.
=> Switch ffi layer logs output to stderr instead of stdout

bindings/matrix-sdk-crypto-js/src/device.rs, bindings/matrix-sdk-crypto-js/src/identifiers.rs, bindings/matrix-sdk-crypto-js/src/identities.rs, bindings/matrix-sdk-crypto-js/src/js.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/macros.rs, bindings/matrix-sdk-crypto-js/src/olm.rs, bindings/matrix-sdk-crypto-js/src/store.rs, bindings/matrix-sdk-crypto-js/src/sync_events.rs, bindings/matrix-sdk-crypto-js/src/types.rs, bindings/matrix-sdk-crypto-js/src/verification.rs, bindings/matrix-sdk-crypto-js/src/vodozemac.rs, bindings/matrix-sdk-crypto-js/tests/identifiers.test.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-crypto/src/identities/user.rs
Related to https://github.com/matrix-org/matrix-rust-sdk/issues/1016.
This PR does the following::
* Implement `EventId` (with tests for version 1 to 4),
* Simplify a little bit the code with one `impl_from_to_inner!` simple macro,
* Simplify a little bit the code with a small helper `try_array_to_vec`, it will probably be revamped later with a more general approach,
* Implement `OlmMachine.get_identity` with `OwnUserIdentity` and `UserIdentity`.
=> feat(crypto-js): Implement `OlmMachine.get_identity`

crates/matrix-sdk-appservice/src/lib.rs
Adds an optional default RequestConfig to the appservice struct, which when present is used for any virtual clients created.
Closes #925
=> feat(appservice): Add default request config

bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/olm.rs, bindings/matrix-sdk-crypto-js/tests/device.test.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js
=> feat(crypto-js): Implement `OlmMachine.export_room_keys` and `.import_room_keys`

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/types/events/room_key_request.rs, crates/matrix-sdk-crypto/src/types/events/to_device.rs
The crypto crate consumes to-device events, if needed decrypts them, and in the end reserializes while zeroizing secrets.
It needs to do this reserialization cycle as loslessly as possible, this is why we have a bunch of BTreeMaps lying in events and contents that capture unknown fields.
The Deserialize implementation of ToDeviceEvent<C> put the event type into this BTreeMap but the Serialize implementation figures it out from the EventType trait of the content.
This patch simplifies things by putting the event type into ToDeviceEvent<C>, this also means that we can just derive the Serialize implementation for ToDeviceEvent<C>.
=> fix(crypto) Fix the zeroizing serialization of to-device events

Cargo.lock, bindings/matrix-sdk-crypto-js/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-indexeddb/src/lib.rs, crates/matrix-sdk-indexeddb/src/state_store.rs
By default, the new `experimental-nodejs` feature is disabled. However, when enabled, it uses our own fork of `indexed_db_futures` that make it work on Node.js, and so this entire `matrix-sdk-indexebdb` crate.
=> feat(indexeddb): Introduce the `experimental-nodejs` feature

.github/workflows/release-crypto-nodejs.yml
We hope that adding this to the workflow will make `NPM_TOKEN` available from within the script.
=> fix(crypto-nodejs): Hopefully it will make `NPM_TOKEN` available in the script

crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/README.md, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/docs/encryption.md, crates/matrix-sdk/src/room/common.rs, xtask/src/main.rs
Now that 0.6.0 is out, we can remove all the stuff we previously deprecated!
@poljar there is one more deprecated function that I didn't remove because I don't really know whether there's still a potential use case for it:
```rust
// In crates/matrix-sdk/src/encryption/identities/devices.rs
// impl Device {
#[deprecated(
since = "0.4.0",
note = "directly starting a verification is deprecated in the spec. \
Users should instead use request_verification()"
)]
pub async fn start_verification(&self) -> Result<SasVerification> {
```
Should I remove that one as well?
=> Remove deprecated functions

.gitignore
This folder is created when building or testing the Swift package in `bindings/apple`.
=> chore: Ignore Swift's .build folder

crates/matrix-sdk-crypto/src/verification/machine.rs
The `decrypt_room_event` method will automatically handle any verification events it decrypts, incl. inserting new verification requests. The existing code ensures that only one request per user exists, but does not check for strict duplicates (i.e. matching flow_id). If the client decrypts the same message multiple times (e.g. via sync + pagination), the cancellation branch will always be triggered.
To solve this add a simple check to ignore verification requests with matching flow_id
=> Ignore duplicate verification requests

.github/workflows/ci.yml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-ffi/uniffi.toml
Do we want to merge this now? Or should we stay with just the one crate using the proc-macro frontend while it's still as incomplete as it is now?
=> Start using #[uniffi::export] for matrix-sdk-crypto-ffi

benchmarks/benches/crypto_bench.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-nodejs/src/machine.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sled/src/crypto_store.rs, crates/matrix-sdk-sled/src/lib.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/src/client/builder.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs, examples/timeline/src/main.rs, testing/matrix-sdk-integration-testing/src/helpers.rs
This implements [MSC 3700](https://github.com/matrix-org/matrix-doc/pull/3700), which is nowadays part of the spec.
=> Don't use the Curve25519 sender key to store room keys

.github/workflows/bindings_ci.yml, Cargo.lock, bindings/apple/MatrixSDKCrypto.podspec, bindings/apple/README.md, bindings/apple/build_crypto_xcframework.sh, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/uniffi_api.rs, bindings/matrix-sdk-ffi/Cargo.toml
- Add steps to compile Crypto FFI for macOS
- Upgrade uniff-rs to include swift [codegen bug fix](https://github.com/mozilla/uniffi-rs/pull/1365)
- Update Podspec version to release new CocoaPods version
=> Compile Crypto FFI for MacOS

Cargo.lock, Cargo.toml, README.md, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-ffi/Cargo.toml, xtask/Cargo.toml, xtask/src/swift.rs
=> Unifiy UniFFI version workspace-wide, use same for xtask job

Cargo.lock, crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-appservice/src/webserver.rs
We could just return `axum::Router<B>` directly as `axum`(`-core`) is part of our public API anyways, but it seems like with 0.6, we won't have to have it as public API anymore while retaining the same functionality, so this seems better.
=> feat(appservice): Return a concrete type from AppService::service

crates/matrix-sdk/src/http_client.rs
=> fix(sdk): Don't log the access token in HttpClient::send

crates/matrix-sdk/src/account.rs
=> fix(sdk): Always send an access token for `get_display_name`

crates/matrix-sdk/src/account.rs
=> fix(sdk): Always send an access token for `get_profile`

Cargo.toml, benchmarks/Cargo.toml, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk/Cargo.toml, labs/sled-state-inspector/Cargo.toml, testing/matrix-sdk-test/Cargo.toml
… where we can't use different versions anyways (ruma) or we want to consistently use the latest version we can for security reasons (vodozemac, zeroize).
=> Use workspace dependencies for a few more packages

Cargo.lock, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/requests.rs
Two valid user flows currently lead to the insertion of duplicate verifications and thus the cancellation of both:
1. Two QR-capable devices both generate a QR code (and start qr_verification in the process), but only one of them will scan the other code. Once scanned, this will create a new `QrVerification` and clash with the existing one.
2. A device starts qr_verification and displays QR code, but then "Can't scan" (or similar) button is tapped, which will transition into SAS verification flow. Once again we will have a clashing previous verification.
To avoid the cancellation of these flows, we need to detect when this transition occurs, and explictly replace an existing verification with a new one.
An alternative solution would be to expose new `cancel_verification_flow` and call …
=> Replace QR with SAS verification

.github/workflows/cancel_others.yml, .github/workflows/ci.yml
(not just jobs from the ci workflow file)
=> ci: Cancel all CI jobs for old commits when pushing to a PR branch

bindings/apple/build_crypto_xcframework.sh, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/logger.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl
Deprecate unused `mark_device_as_trusted` (one should instead use `verify_device` which will create and upload new signatures) and expose the internal `set_local_trust` instead, which can be used to (un)blacklist a user.
=> Set local trust

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-ffi/src/responses.rs, bindings/matrix-sdk-crypto-ffi/src/verification.rs
This reverts commit 6b9075aa42dbd30253468a6c41c84cce2a67d06c.
I have a partial fix for UniFFI locally, but am not managing to make it work fully.
=> Revert "refactor(bindings): Use new uniffi::Enum derive macro in crypto-ffi"

Cargo.lock, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs, crates/matrix-sdk/src/encryption/verification/mod.rs, crates/matrix-sdk/src/encryption/verification/sas.rs, examples/emoji_verification/Cargo.toml, examples/emoji_verification/src/main.rs, examples/timeline/Cargo.toml
This patch adds a way for users to listen to changes in the state of a SAS verification.
This makes it much more pleasant to go through the verification flow and incidentally easier to document it.
=> feat(crypto): Add signalling to the SAS verification

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl
@BillCarsonFr as requested, the settings can be now passed to the E2EE layer. @Anderas this probably interests you as well as it's a breaking change.
=> Allow passing the E2EE settings when sharing a room key

crates/matrix-sdk/src/config/sync.rs
This one was named just `token`, not `access_token`, so I didn't find it on initial review.
Fixes one of the two log-leaks of the token from #1110, the other one was previously fixed in #1117.
=> fix(sdk): Remove token field from SyncSettings Debug output

Cargo.lock, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk/Cargo.toml
… to bring them up to the released ones from the v0.6.x branch. All changes from those versions are already present on main.
cc #1141 (let's see whether the bot closes that one automatically after this is merged)
=> chore: Bump versions of matrix-sdk, matrix-sdk-base

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/session_verification.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Smaller version of #1133 that doesn't break binding generation. Through reduction of the initial PR, I now have a pretty clear understanding of what circumstances triggered the previous issue.
=> refactor(bindings): Use uniffi proc-macros a little more in sdk-ffi

bindings/matrix-sdk-ffi/src/sliding_sync.rs
=> fix(ffi): Remove duplicate RequireState definition, left over after #1151

bindings/matrix-sdk-crypto-js/package.json
By asking `wasm-bindgen` to generate JS glue code for `WeakRef` support, it removes the need to call `free` manually to free objects, thus we reduce potential memory leaks inside Rust. See https:// rustwasm.github.io/docs/wasm- bindgen/reference/weak-references.html to learn more.
It uses [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) under the hood, I reckon it's quite common and fits into Matrix's clients needs in terms of browser support.
=> feat(crypto-js): Use `WeakRef` to avoid calling `free` manually

bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/device.test.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js, bindings/matrix-sdk-crypto-js/tests/tracing.test.js
While technically a type constructor can return a `Promise`, it's not considered as idiomatic JavaScript to do that. We are changing `new OlmMachine` to `OlmMachine.initialize`. The rest of the code is strictly the same.
=> feat(crypto-js): `OlmMachine.initialize` is the new constructor

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/session_verification.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Apparently the enum derive is broken. It was merged upstream in https://github.com/mozilla/uniffi-rs/pull/1371 w/o tests because I am not familiar with the code generated for enums in any of the binding languages, and maintainers had nothing to say about that. I have now asked about examples that I can turn into a test in their Matrix channel.
=> Revert #1151

.github/workflows/bindings_ci.yml, bindings/matrix-sdk-crypto-nodejs/download-lib.js
Fixes #1160 
This is fixed more formally in https://github.com/hgouveia/node-downloader-helper/pull/92, but since it's easy to do without an upstream change I've added the config in here too. Once this gets merged and released, Node.JS 19 users should be able to download the latest binary.
=> Disable keepAlive in download-lib.js, allowing node bindings to work on Node.JS 19

Cargo.lock, labs/jack-in/Cargo.toml, xtask/Cargo.toml
We were still using a version of ruma-client-api that includes secrets in `Debug` formatting!
=> Upgrade dependencies

crates/matrix-sdk-appservice/src/webserver.rs
cc @Yoric, when this is merged you no longer need to do this hack in your own code.
=> fix(appservice): Fix nesting of AppServiceRouter in axum::Router

.github/workflows/bindings_ci.yml, Cargo.lock, Cargo.toml
Now includes a working `Enum` derive.
=> chore: Upgrade UniFFI

.github/workflows/prep-crypto-nodejs-release.yml
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecrets.
=> fix(crypto-nodejs): Pass secrets to the release workflow

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/lib.rs
This makes the FFI API a little less opaque and allows users to pull out the homeserver URL for supplying it to `ClientBuilder` while using the rest of the `Session` to restore the client's state after creation.
=> ffi: Replace RestoreToken string with Session dictionary

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/sliding_sync.rs
- sliding sync printing out info logs on every successfully processed response
- the session verification controller not being ready for to_device messages processing (identity not available): expected and part of the flow
=> chore(ffi): reduce the log level for some not so useful logs

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/verification/cache.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This prevents users from confirming that the short auth string matches before the public keys have been exchanged.
=> Add a new state to the SAS state machine

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/tests/integration/room/timeline.rs, examples/timeline/src/main.rs
Tested on a local branch on Fractal.
The current limitation is that since not all events are in the timeline, sometimes the event of the read marker is not found.
This makes the `Timeline` constructor `async` to be able to initialize the read marker from the store.
=> feat(sdk): Add read marker logic to the timeline API

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_item.rs
Exposes two things:
- `is_editable` on `EventTimelineItem` object: currently only outgoing text messages are editable.
- `edit(...)` method on `Room` object.
=> Edit messages

bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-indexeddb/src/crypto_store.rs
@richvdh has raised an important issue. When initializing a new `OlmMachine` with a store name and a store passphrase, 2 databases (IndexedDB databases) are created. At some point, one may want to delete them. But it's impossible. The sky is crying. The undeads are dancing under a bloody moon. And an exception is thrown saying the databases are _blocked_.
This PR fixes the problem in 3 acts.
Surprisingly, `indexed_db_futures::IdbDatabase` is not closed when dropped.
Hopefully, there is a [`IdbDatabase::close(&self)`][close] method, which calls
`web_sys::IdbDatabase.close`, aka [`IDBDatabase.close`][websys-close], so let's
use it!
`IDBDatabase.close` returns immediately and closes the connection in a separate
thread. The connection isn't actually closed until all transactions created
using …
=> fix(indexeddb) + feat(crypto-js): Releasing `IDBDatabase` so that we can delete them

crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-appservice/src/user.rs, examples/appservice_autojoin/src/main.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1109
=> refactor(appservice)!: Rename virtual user to appservice user

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/http_client.rs
Makes the changes from #1179 actually take effect. Previously, we never actually constructed the error variants we were checking for.
=> refactor(sdk)!: Move retrying out of HttpSend trait

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync.rs, crates/matrix-sdk/src/sync.rs, crates/matrix-sdk/tests/integration/client.rs, crates/matrix-sdk/tests/integration/room/common.rs, examples/command_bot/src/main.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs, examples/image_bot/src/main.rs, examples/wasm_command_bot/src/lib.rs, testing/matrix-sdk-integration-testing/src/tests/redaction.rs
It's not removed here because that would mean people have to manage it externally for clients that keep non-crypto state across app runs. However, to make use cases with multiple concurrent syncs possible, we could do so in a follow-up and require people to manage the sync token themselves. Many of the examples seem to suggest that it has to be passed manually anyways..
Supersedes #1211.
=> Make sync_token accessor private

crates/matrix-sdk/src/room/timeline/event_handler.rs
On building `retry-decrypt` that jplate submitted, I got this error.
```
note: future is not `Send` as this value is used across an await
--> F:\rust-workspace\.cargo\git\checkouts\matrix-rust-sdk-1f4927f82a3d27bb\fa71122\crates\matrix-sdk\src\room\timeline\event_handler.rs:105:38
|
104 |             &mut self.items.lock_mut(),
|                  --------------------- has type `MutableVecLockMut<'_, Arc<TimelineItem>>` which is not `Send`
105 |             &mut self.metadata.lock().await,
|                                      ^^^^^^ await occurs here, with `self.items.lock_mut()` maybe used later
|          - `self.items.lock_mut()` is later dropped here
note: required by a bound in `Runtime::spawn`
--> F:\rust-workspace\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\run …
```
=> Call await prior to handle_remote_event

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync.rs, labs/jack-in/Cargo.toml, labs/jack-in/src/client/state.rs, labs/jack-in/src/components/details.rs, labs/jack-in/src/main.rs
When the experimental-timeline feature is activated, sliding-sync room's `.timeline()` now hand over the cached `AliveTimeline` to `Timeline`, which they expose through it. Thus enabling a fast start for the new `Timeline`-API, which should give a visibly faster room-opening impression.
This also updates jack-in to use that new feature to build the timeline as a test-case.
=> feat: experimental-timeline API support for sliding sync

xtask/src/swift.rs
Moves missing module map to the headers directory so that it's picked up by `xcodebuild` when creating the .xcframework
=> fix(ffi): Fix xcframework release script, add missing module map

crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/tests.rs, xtask/src/swift.rs
Ping @zecakeh, can you have a look? I think the `move_from_to` call was previously wrong in that it placed the read marker one position behind where it should be, running out of bounds if it was meant to be moved to the end.
=> fix(sdk): Fix logic for updating an existing read marker

crates/matrix-sdk/src/events.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/tests.rs
When a timeline event comes in but we fail to deserialize it, previously we would just ignore it. Now, if we can still parse everything except the content, we add an `EventTimelineItem` with a new kind of content so the fact an event arrived isn't just silently discarded. The raw event and error can be reflected in the UI somehow. If something outside `content` fails to parse, that is either a bug in the server or in our code and we just log an error.
The first case can easily happen by having a buggy or malicious client, so I think it's important we preserve as much information as possible. In the latter case, just logging an error should be fine as it's much less likely (requires a bug in the server, ruma or the SDK).
=> Add FailedToParse timeline items

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/tests.rs
Follow up to #1229.
Since we don't remove the read marker when the fully read event wasn't found, we also need to update `fully_read_event_in_timeline` when both `from` and `to` are `Some`. Otherwise we will call the method for every event, even if we already have the fully read event.
Ping @jplatte.
=> fix(sdk): Fix logic if read marker event was not in the timeline

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs
I'm not sure it can be called a bug, because I don't think it could happen in the flow, but I believe it's something worth guarding against.
Without this fix, the line added in the test triggers a move of the read marker from index 2 to index 1.
=> fix(sdk): Make sure read marker can't go backwards

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/http_client.rs, crates/matrix-sdk/tests/integration/client.rs
We're currently retrying too many requests internally, which is especially problematic when the server is clearly telling us that the request is wrong and we still retry (often until the program is killed because we don't have a retry limit by default).
=> Only retry requests on M_LIMIT_EXCEEDED or HTTP 5xx

crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/verification/machine.rs
Conditional compilation erased use of some imported types on macos, which has led to clippy errors and failed `cargo xtask ci` run (unused imports)
- expiration test seems to be safe to run on macos, added it to targets
- timeout test compiles fine now (M1 Pro, macOS 13.0.1 Ventura)
=> fix(ci): Fix clippy unused imports on macos

README.md, testing/matrix-sdk-integration-testing/README.md
I would like to also add a list of dependencies that are needed to run the `xtask ci`, but I don't know which anymore. Do you happen to have a list somewhere?
=> doc: Hint towards test execution

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync.rs
… at least for the simple case where we just want the latest event item. For fetching the current fully-read marker, which a "full" timeline generally wants, we still need async because of the store.
Also contains lots of small refactorings like breaking the ever-growing `timeline::event_handler` module into two.
=> Make Timeline construction sync again

Cargo.lock, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-ffi/src/verification.rs
This is the continuation of #1124 and #1145. This now exposes the `changes()` method of our `Sas` object over FFI.
@Anderas and @BillCarsonFr this should interest you. If the `changes()` method is workable for you we can continue introducing it to the rest of the verification support.
This closes #708.
=> Update the verification support in the Uniffi based bindings

Cargo.lock, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/tests/integration/client.rs
The in-memory state store is always compiled but rarely used. It's mostly useful for bots, which don't interact with avatars and likely don't have a reason to cache other media (certainly not in memory). So this PR removes a feature that was likely never used since it was added, and that was pulling in an extra dependency.
=> refactor(sdk): Remove media caching from in-memory state store

crates/matrix-sdk/src/sliding_sync.rs
Not super happy about still having an `unwrap()` in there (which caused the earlier crashes), but we need to refactor that timeline creation for async support again anyways.
=> fix(sliding-sync): fallback to invite-room if regular room can't be found

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk/src/client/mod.rs
Tokens are not necessary for the crypto/store restoration, only the meta.
This is required for (experimental) OpenID Connect support where we need to use the tokens to get the meta.
=> refactor(sdk): Split restore_session into two parts at the Client level

.github/pull_request_template.md, CONTRIBUTING.md, README.md
GitHub will automatically let people know about the contributing instructions given the right file name, so I moved them into a separate document (and added sign-off).
=> Add more contributing instructions, and a PR template

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs
Adds basic reaction sending to `matrix-sdk-ffi`. Later we will want to add a similar function to the `Timeline` that also does local echoing, but this is a helpful stopgap until we have implemented reaction echoes.
cc @stefanceriu
=> feat(bindings): Add sending of reactions to matrix-sdk-ffi

crates/matrix-sdk/src/client/mod.rs
The SDK used to have builder types for these request types, but they were removed long ago.
=> refactor(sdk)!: Remove impl Into<_> around Ruma request types

bindings/matrix-sdk-crypto-nodejs/README.md
Clarify that the JSON-encoded `toDeviceEvents` passed to `OlmMachine.receiveSyncChanges` must be the list of events themselves, instead of a wrapper object that contains the event list.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
As found in https://github.com/turt2live/matrix-bot-sdk/pull/283, a recent change in the Rust SDK changed the expected format of the event list string accepted by `OlmMachine.receiveSyncChanges`.  Since it's a subtle yet consequential change, it's helpful to update the docs to reflect the new format.  There are probably better places/ways to document it, but this PR can be a first step.
=> Revise example of `machine.receiveSyncChanges`

crates/matrix-sdk/src/client/login_builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/tests/integration/client.rs, crates/matrix-sdk/tests/integration/refresh_token.rs, examples/autojoin/src/main.rs, examples/command_bot/src/main.rs, examples/cross_signing_bootstrap/src/main.rs, examples/custom_events/src/main.rs, examples/emoji_verification/src/main.rs, examples/get_profiles/src/main.rs, examples/getting_started/src/main.rs, examples/image_bot/src/main.rs, examples/login/src/main.rs, examples/timeline/src/main.rs, examples/wasm_command_bot/src/lib.rs, labs/jack-in/src/main.rs, testing/matrix-sdk-integration-testing/src/helpers.rs
This allows `.await`ing the builder directly, rather than first having to call `.send()`.
=> feat(sdk): Implement IntoFuture for LoginBuilder and SsoLoginBuilder

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs
Adds `upload_media` to `Client` in order to allow uploading media. And `set_display_name` to `Client` to allow for changing display name
=> Add uploading media and setting display name to FFI

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs
Previously, we were only checking whether remote events were duplicated, now we're also checking whether an event might be a remote echo and thus redundant with a local event, even when it doesn't have a transaction ID. Works around https://github.com/matrix-org/sliding-sync/issues/24.
=> Work around remote echoes that are missing a transaction ID

crates/matrix-sdk/src/sliding_sync.rs, labs/jack-in/src/client/mod.rs, labs/jack-in/src/client/state.rs, labs/jack-in/src/components/statusbar.rs
Sliding sync recovered from cold cache never turned into `live` mode, the reason being that the count was existing and it wasn't considered to be updated yet. This sets the state into `preload` to ensure we are in sync again for further updates.
=> fix(sliding-sync): set views to preload if we've recovered from frozen

bindings/matrix-sdk-crypto-nodejs/download-lib.js, bindings/matrix-sdk-crypto-nodejs/package.json
When downloading in `download-lib.js`, first look for an HTTP proxy configured in the `https_proxy` environment variable, and use this proxy when calling `DownloadHelper`. Requires the `https-proxy-agent` library.
Fix #1263
Signed-off-by: Erwan Bousse <erwan.bousse@univ-nantes.fr>
=> download-lib.js: use HTTP proxy to download when provided as environment variable (fix #1263)

crates/matrix-sdk-crypto/src/machine.rs
UnknownMessageIndex decryption errors were just bubbled up, and no room key request was sent in this case.
Added special handling for this case.
Signed-off-by:  valeref@matrix.org
=> fix: Query room key for ratcheted session

.gitignore, bindings/apple/Debug-Package.swift, xtask/src/swift.rs
This PR tweaks the Swift xtask to create a Package.swift in the repo's root when building an XCFramework. This allows the repo to be used as a Swift package directly which provides the advantage of all the source files being available to the debugger compared to using a copy located in the matrix-rust-components-swift repo.
=> Generate a Package.swift in XCFramework xtask

crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/mod.rs
I'm pretty sure it was moved there by accident, it doesn't really belong there.
=> Move PaginationOutcome out of event_item module

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-ffi/src/verification.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs
This change is a continuation of adding signalling to [SAS verification](https://github.com/matrix-org/matrix-rust-sdk/pull/1184), adding `changes` stream to `VerificationRequest` and `QrCode`
=> Verification request and QR signalling

bindings/matrix-sdk-crypto-ffi/src/verification.rs
Fixed link in documentation referring to structure that isn't used in that context with a string description 
- fixes complaining documentation build
Signed-off-by: Kateřina Churanová <k.churanova@famedly.com>
=> fix(doc): Fix unresolved link in documentation

labs/setup-pattern.md
Here I introduce some unstructured thoughts I got inspired with after seeing [Gavel](https://gitlab.com/xiretza/gavel), a mjolnir RIIR.
After having seen the readme of that project, with an explicit separation of `setup` and the main executable, I realised this pattern might be beneficial to other matrix projects, as it could alleviate onboarding issues naturally, as it builds in the invariant into bot applications that it will not run without state, and the only way to initialise state is through a dedicated `setup` command that bootstraps it.
That follows a lot of implicit consequences, some important ones are listed in the document, but the most important one of this is; E2EE state is less likely to be wedged.
The problems that this pattern seeks to address are some of the same that …
=> Lab: The Setup Pattern

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/utils.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs, testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
… so custom or not-yet-known fields are not discarded.
=> refactor: Don't reserialize member events before storing them

bindings/matrix-sdk-crypto-js/src/future.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js
It's not a hard-and-fast-rule that Javascript exceptions should be `Error` instances, but it's certainly a convention, and one that is going to reduce surprises if we follow, rather than throwing strings.
=> matrix-sdk-crypto-js: Make our promises reject with `Error`

crates/matrix-sdk/src/room/timeline/event_handler.rs
Due to https://github.com/matrix-org/sliding-sync/issues/3, this tracing event is currently emitted rather often. Until that is fixed, lower the log level to trace.
=> chore(sdk): Lower log level of event ID duplication event

.github/workflows/ci.yml
Otherwise the action uses the GitHub API to determine the latest release and falls back on v0.9.1. I suspect it was recently failing because of rate limits, because I saw it hit the fallback a lot.
=> Specify which version of wasm-pack we want

Cargo.lock, Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-appservice/src/webserver.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/utils.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/login_builder.rs, crates/matrix-sdk/src/event_handler/static_events.rs, crates/matrix-sdk/src/events.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/sliding_sync.rs
When SS sessions expire, we need to reset the SS extension to the original config used to set up the SS session in the first place. Instead, we were resetting it to a cache of the SS extension config at the point that a given SS view was created - which could well be 'None' given we clear the SS extension config whenever we send it to the server, given it's sticky. This would then entirely disasble the to-device extension after a session expires, dropping all to-device traffic and breaking E2EE.
It also looks like the since parameter in the sync loop requests was not correctly being updated with the next_batch parameter from the SS responses - it was being applied to the SS's copy of the extension config rather than the one used within the view's loop.  This would cause duplicate …
=> handle the to-device sliding sync extension correctly

bindings/matrix-sdk-ffi/src/api.udl, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
Since timeline updates are received asynchronously, this number can be used to determine whether all updates have been observed, and whether another back pagination request should be made.
=> Add num_updates to timeline PaginationOutcome

Cargo.lock, labs/jack-in/Cargo.toml, labs/jack-in/README.md, labs/jack-in/src/config.rs, labs/jack-in/src/main.rs
Updated jack-in to use `clap` instead of `structopt` and changed the README.md of jack-in with the new help output.
Fixes #1274
=> Update to clap v4 in jack-in

crates/matrix-sdk/src/http_client.rs
Apparently this is what Element clients do, so probably a better default than the much lower value we have now.
=> Increase default request timeout to 30s

bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs
We have support for placeholders for events that failed to deserialize, as well as stickers now. With this, FFI users can also use those.
I decided to go for a hybrid enum / accessor approach instead of getting just the variant as an enum and having one accessor for each variant, which is a lot of boilerplate. Maybe we should do the same thing for `TimelineDiff`.
=> Expose all TimelineItemContent variants

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/virtual_item.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
This will be especially useful once we expose a backpagination function that does multiple requests in a loop to fetch a certain minimum number of extra items.
=> Add pagination loading indicator as a virtual timeline item

crates/matrix-sdk/src/sliding_sync.rs
Index ranges are inclusive, but our loop would stop one short. This particularly
tricky when the selective view is moved, as we didn't properly invalidate all items.
Likely cause and fix for https://github.com/vector-im/element-x-ios/issues/396 .
=> fix(sliding-sync): ensure last index is also invalidated

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/pagination.rs, crates/matrix-sdk/src/room/timeline/virtual_item.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
- Add `TimelineStart` virtual timeline item
- Don't actually fire off a request when the top of the timeline has already been reached
- Allow making multiple requests without removing the loading indicator in between
=> Make timeline pagination more flexible and smarter

crates/matrix-sdk/src/sliding_sync.rs
following #1321 :
Previously, when we found a since-token in the frozen state, we'd always activate the to-device extensions regardless of whether the user had activated it in their builder or didn't. With this change we are only setting the since parameter from cache if the user actually activated the to-device extension.
=> fix(sliding-sync): Do not implictly activate to-device extension upon unfreeze

crates/matrix-sdk-crypto/src/machine.rs
This is mainly done so we create a span with the name of the function, since we can filter logs by the name of the span we're now able to enable logs for this method only.
=> chore(crypto): Instrument the receive_sync_changes method

bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, labs/jack-in/Cargo.toml, xtask/src/ci.rs
Without this, a `cargo test --features sliding-sync` fails to compile.
=> chore(sdk): Make the timeline feature a dependency of the sliding sync one

crates/matrix-sdk/src/room/timeline/event_handler.rs
=> chore(sdk): Add logging for when timeline events are not handled

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/utilities.rs
=> Handle the `failures` field in the `/keys/query` and `/keys/claim` responses

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/types/device_keys.rs
When updating a device after we receive new device keys from a /keys/query call we implicitly check that the user and device id match since we need to fetch the device using the mentioned ids.
This moves the check into the update method as well to make it more explicit. We also prevent upgrades of the Ed25519 key since we don't support any different key type anyways.
=> fix(crypto): Make the device update logic a bit more strict and obvious

crates/matrix-sdk/src/lib.rs
This was forgotten to be re-exposed after it was moved to the base crate.
=> chore(sdk): Re-export the AmbiguityChange type

crates/matrix-sdk/src/room/timeline/pagination.rs
Required when `PaginationOptions` must implement `Send`, e.g. with `tokio::runtime::Runtime::spawn`.
=> fix(sdk): Make pagination strategy implement `Send`

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs
As requested by the element-x team, this adds a helper fn to the sliding-sync-room FFI interface, that automatically subscribes in the sliding-sync-api for that room and unsubscribes on drop.
=> feat(ffi): add subscribe_and_add_timeline_listener helper fn

.github/workflows/ci.yml, .github/workflows/coverage.yml, Cargo.lock, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync.rs, testing/matrix-sdk-integration-testing/Cargo.toml, testing/matrix-sdk-integration-testing/src/helpers.rs, testing/matrix-sdk-integration-testing/src/lib.rs, testing/sliding-sync-integration-test/Cargo.toml, testing/sliding-sync-integration-test/README.md, testing/sliding-sync-integration-test/assets/Dockerfile, testing/sliding-sync-integration-test/assets/ci-start.sh, testing/sliding-sync-integration-test/assets/docker-compose.yml, testing/sliding-sync-integration-test/src/lib.rs
- 🚫 removing views is not yet supported (but we have a test we can enable when we do)
- 🚫 CI job to run the integration-tests (fails on setting up docker)
- 🚫 coverage reporting over ci-test
=> Various smaller fixes on sliding-sync for elem-x

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs
This PR exposes `read_receipt` and `read_marker` on the FFI's room. Similar to sending reactions, this is likely a method that should be moved elsewhere in order to create local echoes, although I'm not sure on what layer that would be as presumably sliding sync would need to know about that 😕
=> Expose sending read receipts to FFI.

crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk/src/sync.rs
We probably shouldn't be deriving `Deserialize` and `Serialize` on these types if we don't need to serialize it ourselves, as any breaking changes to the serialized format (for example adding a new field) would be very easy to miss.
Also make `AmbigutityChange`(`s`) non-exhaustive, they aren't meant to be constructible outside of `matrix-sdk-base`.
=> Remove unused Deserialize, Serialize implementations

bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/src/room/timeline/to_device.rs, crates/matrix-sdk/src/sliding_sync.rs
It seems very likely that this is going to trigger tokio runtime panics in EX again. If so, we need to either hack around it and intentionally disable profile fetching for fetching the latest message of a room in the sliding sync API, or wait for uniffi-async.
=> Attach profile information to timeline items

bindings/matrix-sdk-crypto-ffi/src/error.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-js/src/machine.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-crypto/src/machine.rs
=> refactor!(crypto): Don't process in-room verification implicitly

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs
During migration we only convert private keys but not devices / identities. When we eventually query our own user and recieve current device, we will not consider it verified.
To solve this we mark current device as verified if just inserting it and we have master key stored locally.
=> Mark as verified if our own device matches keys

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs
This PR exposes the ability to set the sled passphrase both on the `AuthenticationService` for login and then on the `ClientBuilder` for restoration.
=> feat(bindings): Expose sled passphrase to the FFI.

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs
Reintroduces #1346 but refactor the stoppable spawn from the old replacing token to a user-has-token-control model. This fixes the problem of sync randomly stopping after introducing the drop cancellation on stoppable spawns.
=> Cancel stoppable spawn on drop, add helper fn subscribe_and_add_timeline_listener

bindings/matrix-sdk-crypto-js/src/identities.rs, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/requests.rs, bindings/matrix-sdk-crypto-js/tests/attachment.test.js, bindings/matrix-sdk-crypto-js/tests/device.test.js, bindings/matrix-sdk-crypto-js/tests/helper.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js, bindings/matrix-sdk-crypto-js/tests/requests.test.js
It's kind of intuitive to understand with an example.
Before:
```rust
pub struct ToDeviceRequest {
pub id: Option<JsString>,
pub body: JsString,
}
```
After:
```rust
pub struct ToDeviceRequest {
pub id: Option<JsString>,
pub event_type: JsString,
pub txn_id: JsString,
pub body: JsString,
}
```
Previously, `body` was containing a JSON map containing `event_type`, `txn_id` and `messages`. Now it's part of the struct itself.
Some types have been _extracted_ as individual fields, and the others are _grouped_ inside `extra`.
The documentation explains which fields is a regular JS string, or a JSON-encoded string. In this case, `event_type` and `txn_id` are regular ID, while `messages` is part a JSON encoded string inside `body`. Supported “field types” are:
* `json` to JSON-encode the field's …
=> feat(crypto-js): Request types have fields extracted from their “body” directly

CONVENTIONAL_COMMITS.md
The conventional commit specification recommends the "docs" type for documentation related changes. This also matches the initial usage of this type in our commit history.
While the default git-cliff config does specify a regex "^doc", where I suspect our types have been taken from, this regex actually allows "doc" as well as "docs" for the type.
Nevertheless, let's specify that we're using the one recommended in the spec.
=> chore: Fix the conventional commit type for documentation

crates/matrix-sdk-crypto/src/error.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/machine.rs
A mismatch between the recorded Ed25519 and Curve25519 keys of the room key and the identity keys of a Device used to be just a warning.
Considering that many clients will aggressively try to hide E2EE related warnings let's upgrade this clear error into a full blown decryption failure.
=> crypto(fix): Fail to decrypt if there's a key mismatch

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync.rs, testing/sliding-sync-integration-test/src/lib.rs
Various sliding sync fixes, providing tests where possible. ref #1359
=> Various smaller sliding sync fixes

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/src/room/timeline/virtual_item.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
As discussed in the Dev room on Matrix ([start of discussion](https://matrix.to/#/!qSsPTKDfMGYqhgiLPJ:flipdot.org/$EufjrkHosf_6ZVCrLEEh1TIlp0vIdffSZBim-WNang8?via=flipdot.org&via=matrix.org&via=famedly.de)).
I was hesitating to change the timestamp to a significant time in the day (like midnight for example), but I'm not sure it would be useful.
=> refactor(sdk): Provide day divider as a timestamp

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
Fixes https://github.com/vector-im/element-x-ios/issues/479
=> fix(sdk): Respect server ordering for remote echoes

bindings/matrix-sdk-ffi/src/room.rs
Exposes `canonical_alias` and `alt_aliases` to the FFI.
=> feat(bindings): Expose aliases to the FFI.

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sled/src/crypto_store.rs
This moves the caches we have for tracked users out of the Sled, and IndexedDB, CryptoStore into the Store struct. The Store struct is a wrapper for the CryptoStore trait, so this is the natural place where these caches should live.
=> refactor!(crypto): Move some caches out of the CryptoStore implementations

bindings/matrix-sdk-crypto-ffi/src/error.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl
Clients may need to know when we fail to decrypt due to a missing room key (for example to trigger custom analytics event). The existing `MissingRoomKey` is however nested within `MegolmError` and only exposed as string value. It was possible to match against this string value, but any change in that string literal (e.g. [here](https://github.com/matrix-org/matrix-rust-sdk/pull/1391/files#diff-8b7ad755130258ef1d1d8a1ee8c571e33f8a2a83d6c06251c88c609126539fa4R88)) will break the behaviour without warning.
To solve this extract out the `MissingRoomKey` as another enum variant of the FFI `DecryptionError` enum
=> Expose MissingRoomKey decryption error

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, labs/jack-in/src/components/details.rs
As asked in https://github.com/matrix-org/matrix-rust-sdk/pull/1347#discussion_r1071073841.
=> refactor(sdk): Split room member events between membership and profile change

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
To create an event next to the server, the event must be accompanied by a transaction ID. When the server receives the event creation request, it responds with a new event ID (which we will name `event_id_1`). Later on, when a sync is done to the server, the server may respond with the transaction ID and a new event ID (which we will name `event_id_2`).
The transaction ID is used to update the state of the local event. The event ID received from the sync may ideally be the same as the one received by the creation request's response.
Knowing that…
`EventTimelineItem` had a field: `event_id: Option<OwnedEventId>`. It was `Some(event_id)` where `event_id` is the event ID responded by the server when an event was created, i.e. it's `event_id_1`; otherwise it was `None`. This is never …
=> feat(sdk): Move `EventTimelineItem.event_id` into `TimelineKey::TransactionId`

crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/src/room/timeline/to_device.rs
The sliding sync logic has another room type called `SlidingSyncRoom`.
This room type stores a limited amount of events in something called `AliveRoomTimeline` in a in-memory cache. This room also gets persisted to the store via another room type called `FrozenSyncRoom`.
These types are used when clients restore their view of the room, i.e. when the user enters the room to look at messages.
When the client enters a room, a `Timeline` object will be created, but it will be initially populated with events coming from `AliveRoomTimeline`.
In a hot potato contest of who should be responsible to decrypt injected events, everybody claims to be allergic to potatoes.
This patch modifies the `Timeline` constructor that populates the timeline with events from the `AliveTimeline` to retry decryption …
=> fix(sdk): Retry decryption if you initialize a Timeline with some events

CONVENTIONAL_COMMITS.md, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
`EventTimelineItem` represents an event item that can be either _local_ or _remote_. _Local_ means that the event has been sent to the server, but not acknowledged, and _remote_ means that the server has acknowledged the event.
Before this patch, to differentiate between the _local_ and _remote_ states, one has to use the `key: TimelineKey` field, which has 2 variants: `TransactionId` and `EventId`, resp. for _local_ and _remote_ states. It's not ideal, but on top of that, `EventTimelineItem` has useless fields depending of the state. For instance, `is_own` is useless in the _local_ state, or `reactions` that is useless for the moment in the _local_ state, or even `transaction_id` that is useless in the _remote_ state, or even `raw` that is always `None` in _local_ state and always `Some` …
=> feat(sdk): `EventTimelineItem` is now an `enum … { Local(…), Remote(…) }`

bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs
Address https://github.com/matrix-org/matrix-rust-sdk/issues/1103.
This patch is trying to resolve the following issue:
When a local event is sent to the server, in case of an error, the `Timeline::send` method just returned the error but it wasn't reflected inside the `LocalEventTimelineItem` type itself. It's easy to loss this information.
So now, there is a new enum: `LocalEventTimelineItemSendState` with 3 states:
1. `NotSentYet`, when the local event has not been sent yet, it's theorically the initial state,
2. `SendingFailed`, when the local event has been sent but it's failed!
3. `Sent`, when the local event has been sent successfully.
Therefore, the `LocalEventTimelineItem` struct has a new field: `send_state`. The send state is managed by its `with_event_id` method which now …
=> feat(sdk): `LocalEventTimelineItem` has a new `send_state` field

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs
We were previously not checking for event duplication when the event had a txn-id. With this refactoring, our event-handling code should be more robust against duplicate events from sync (but we will likely need to tweak things more in the long run to account for the potential of duplicate events from pagination, especially forwards-pagination which we haven't implemented yet).
=> Work around duplicate events from sync

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
The bundled reactions don't have enough data to be usable without extra requests, although we likely have all the necessary data available locally (for now at least as we always start from the end of the timeline).
Tested locally in Fractal.
Fixes #1310.\
Fixes #1311.\
Fixes #1312.
=> fix(sdk): Aggregate reactions locally

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/sliding_sync.rs, labs/jack-in/src/client/mod.rs, testing/sliding-sync-integration-test/.gitignore, testing/sliding-sync-integration-test/README.md, testing/sliding-sync-integration-test/assets/docker-compose.yml, testing/sliding-sync-integration-test/src/lib.rs
Upgrades the sliding sync from index-based views to named views. Additionally provides support for delta-tokens (once they are implemented) and exposes the new additional extensions to be enabled over ffi. Last but not least, it enabled `gzip` on `reqwest` for on-the-wire-compression whenever the sliding-sync feature is enabled.
Built against https://github.com/ruma/ruma/pull/1460
=> Upgrade Sliding Sync to named-lists JSON upgrade

crates/matrix-sdk-indexeddb/src/crypto_store.rs
When we store an Olm session in the database, we encode the sender key and
session ID using the store cipher. That means that we also need to encode them
when we look them up, otherwise we won't find them.
=> fix(indexeddb): correctly encode Olm session keys

.cargo/config.toml, .github/workflows/bindings_ci.yml, Cargo.lock, Cargo.toml, bindings/apple/build_crypto_xcframework.sh, bindings/kotlin/README.md, bindings/kotlin/scripts/build_crypto.sh, bindings/kotlin/scripts/build_sdk.sh, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/build.rs, bindings/matrix-sdk-crypto-ffi/src/uniffi_api.rs, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/build.rs, bindings/matrix-sdk-ffi/src/uniffi_api.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, uniffi-bindgen/Cargo.toml, uniffi-bindgen/src/main.rs, xtask/Cargo.toml, xtask/src/ci.rs
UniFFI made some breaking changes recently, the upside is now there is no longer a need to separately install the `uniffi-bindgen` binary! :)
=> Upgrade UniFFI to 0.23

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
This is a simple implementation of fetching replies for messages in the timeline. I thought it would be better to have this basic implementation first and add complexity later.
`fetch_in_reply_to_details` returns the updated item to be able to fetch other details with the updated item, even if it is unused now.
One thing I was wondering is whether we want to automatically remove the reply fallback (there's a method for that in Ruma).
Things that can be added in other PRs:
- Populate the `InReplyToDetails` as soon as the event is received, if the `RepliedToEvent` is in the timeline.
- Update the `RepliedToEvent` in the current event item when the content of a replied to event item in the timeline is updated.
- Allow to fetch nested `RepliedToEvent`s, to be able to display chain of replies, …
=> feat(sdk): Allow to fetch replied to messages

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync.rs
Before this patch, `SlidingSync::get_room` was taking ownership of an `OwnedRoomId`, to only use it as a reference. Thus, calling this method was creating useless clones.
This patch updates `SlidingSync::get_room` to receive a reference to `RoomId`.
=> feat(sdk): `SlidingSync::get_room` now takes a ref to `RoomId`.

bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests.rs
… as it's not available when members for the room aren't synced.
Ready for testing.
=> Update timeline when members are synced

crates/matrix-sdk/src/sliding_sync.rs, labs/jack-in/src/client/mod.rs, labs/jack-in/src/client/state.rs, labs/jack-in/src/components/details.rs, labs/jack-in/src/components/rooms.rs
`SlidingSyncView` exposes a `room` field. Problem: It's not updated correctly and leads to error. The canonical way to get a room is by using `SlidingSync::get_room`. This patch thus removes `SlidingSyncView.rooms` entirely.
=> feat(sdk): Remove `SlidingSyncView.rooms`

bindings/matrix-sdk-crypto-js/package.json
Nothing much has changed in matrix-sdk-crypto-js, but I need to publish a new artifact to NPM to include https://github.com/matrix-org/matrix-rust-sdk/pull/1429.
Is there a better way to do this?
=> Prepare matrix-sdk-crypto-js v0.1.0-alpha.4

crates/matrix-sdk-sqlite/Cargo.toml, crates/matrix-sdk-sqlite/src/crypto_store.rs
Debug string was referencing `sled`, and we seem to have accidentally pulled in some unusual auto-formatting.
=> Post-merge sqlite crypto store cleanup

crates/matrix-sdk/src/sliding_sync.rs
Tested with the sliding sync integrations tests, so hopefully nothing broke.
=> Refactor the sliding sync stream method

bindings/matrix-sdk-crypto-js/src/machine.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/error.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs
Again some splitting things up into smaller modules, plus moving some code out of `cfg(target_arch = "wasm32")` (good for rust-analyzer IDE functionality).
=> More matrix-sdk-crypto refactoring

crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync.rs
`Timeline::with_fully_read_tracking` was public although all public Timeline constructors enable it by default, so we make the builder type private for now.
It is also meant to be called when constructing the timeline so using a builder pattern makes sense.
=> refactor(sdk): Use a builder pattern to construct Timeline

crates/matrix-sdk-crypto/src/store/error.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/pagination.rs, crates/matrix-sdk/src/room/timeline/to_device.rs
I added a few modules recently, and as always I forgot to add copyright headers.
=> chore: Add missing copyright headers

.github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/documentation.yml, .github/workflows/release-crypto-nodejs.yml, .github/workflows/release_crypto_js.yml
It was affected by some deprecations of GitHub actions functionality.
=> chore: Upgrade rust-cache GitHub action

tarpaulin.toml
I noticed on codecov that the sqlite `crypto_store.rs` is one of the files with the most uncovered lines, none are counted as covered. I think I've identified why, and fixed it.
=> ci: Improve coverage checks

crates/matrix-sdk-base/src/session.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/config/sync.rs, crates/matrix-sdk/src/room/timeline/event_item.rs
We don't really want to check for exact representations, and otherwise they are really just invoked in tests that fail.
=> ci: Exclude Debug implementations from coverage reports

.github/workflows/benchmarks.yml, .github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/documentation.yml, .github/workflows/release-crypto-nodejs.yml, .github/workflows/release_crypto_js.yml
… except for `actions-rs/audit-check`, which we should probably replace with cargo-deny, but that's a little more involved.
=> ci: Replace unmaintained actions-rs actions

crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs
A fix for (de)serialization of redacted state events in Ruma made
old events undeserializable.
Bump the DB version.
Tested locally in fractal with the sled store and seems to fix the issue. I tried to test it for the IndexedDB store too but it seems I can't get the wasm_command_bot example to start when I enable the store.
=> fix(stores): Fix broken raw redacted state events

crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-indexeddb/src/safe_encode.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/encode_key.rs, crates/matrix-sdk-sled/src/state_store.rs
Read receipts should only overwrite receipts with the same `thread_id` (or lack thereof).
The key encoding in key-value stores is backwards-compatible so old receipts are counted as unthreaded receipts.
=> fix(stores): Separate receipts by thread

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-ffi/src/lib.rs, crates/matrix-sdk-indexeddb/src/safe_encode.rs
Regression introduced by merging commit 9707d73 after efdeba7.
Fixes #1489.
=> fix(indexeddb): Fix implementation of SafeEncode for tuple of 5 elements

Cargo.lock, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/error.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sled/src/crypto_store.rs, crates/matrix-sdk-sqlite/Cargo.toml, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/error.rs
This makes store implementations cleaner at the expense of some boilerplate code in matrix-sdk-crypto.
=> Add an error type to the CryptoStore trait

crates/matrix-sdk/src/room/joined.rs
It was unclear what the relationship between the read receipt and read marker was, so I copied a bit from https://spec.matrix.org/latest/client-server-api/#fully-read-markers and added hyperlinks between the functions.
Signed-off-by: Enterprisey <apersonwiki@gmail.com>
See private accepted DCO signoff at https://github.com/matrix-org/synapse/pull/13818#issuecomment-1257991591
=> docs(sdk): Improve read receipt/marker explanation

Cargo.lock, crates/matrix-sdk-common/Cargo.toml, crates/matrix-sdk-common/src/timeout.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/sync.rs
`wasm_timer` doesn't work outside the browser, which prevents it being used in tests.
We can replace it with `gloo-timers` wich uses the standard Javascript `setTimeout`.
Fixes: #896
Fixes: #1443.
=> fix: remove dependency on broken wasm_timer crate

crates/matrix-sdk-sled/src/state_store.rs
Contrary to other tables that use their own name to encode their keys, the `ROOM_INFO` table uses the `ROOM` table name to encode its keys.
=> fix(sled): Use proper table name for encoding key when redacting

bindings/matrix-sdk-crypto-js/src/requests.rs, bindings/matrix-sdk-crypto-nodejs/src/requests.rs
Follow up of #1303, but applied to `crypto-nodejs`.
Instead of putting all request fields inside a single `body` JSON-encoded string  field, there is now more types. There is less need to call `JSON.parse`, and the type system will be able to catch more things.
For example, `ToDeviceRequest` now has 2 more fields: `event_type` and `txn_id`.
=> feat(crypto-nodejs): Request types have more fields

Cargo.lock, crates/matrix-sdk-store-encryption/Cargo.toml, crates/matrix-sdk-store-encryption/src/lib.rs
This is useful for platforms which might want to avoid the cost of password based key-derivation and have the ability to securely store an encryption key.
=> feat(store-encryption): Add support to export/import the cipher using a key

Cargo.lock, testing/sliding-sync-integration-test/Cargo.toml
We activate logging through a ctor function in `matrix-sdk-test`, so no need to copy-paste it into this crate (maybe we can actually do this in other places).
=> test: Remove unused dependency

crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
Seems like these were the only two uses of `items.lock_mut()` where the metadata wasn't also locked. Let's hope this fixes the crash.
Obviously being careful about when / how we write to the items is not viable in the long term, so we will need to find a better solution soon (possibly just forking futures-signals so we don't have to deal with sync locks).
=> fix(sdk): Attempt to EX-android crash with more hacks

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests/echo.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
Fixes a bug that was (knowingly) introduced in #1393
EX issue: https://github.com/vector-im/element-x-ios/issues/540
Depends on #1499
=> Handle remote echo on the first message of the day correctly

bindings/matrix-sdk-crypto-nodejs/src/machine.rs, bindings/matrix-sdk-crypto-nodejs/tests/machine.test.js
* This patch fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1379/.
* This is similar to https://github.com/matrix-org/matrix-rust-sdk/pull/1197/.
---
We need to close the `OlmMachine`. Problem, `napi-rs` doesn't allow methods to take ownership of `self`, so the following code:
```rs
fn close(self) {}
````
isn't allowed. There an [`ObjectFinalize`](https://docs.rs/napi/latest/napi/bindgen_prelude/trait.ObjectFinalize.html) trait, but it's only called when the JS value is being collected by the GC. It's not possible to force call `finalize` here.
This patch then introduces a new type:
```rs
enum OlmMachineInner {
Opened(matrix_sdk_crypto::OlmMachine),
Closed
}
```
that derefs to `matrix_sdk_crypto::OlmMachine` when its variant is `Opened`, otherwise it panics. Calling the new …
=> feat(crypto-nodejs) Implement `OlmMachine.close`

Cargo.lock, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
… if the Timeline object itself is dropped, but something is still subscribed to its changes.
=> feat(sdk): Keep Timeline event handlers around longer

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/room/timeline/tests/echo.rs, crates/matrix-sdk/src/room/timeline/tests/mod.rs
Previously, the server ordering was only respected for remote echoes, now events newly received from syncing are always added at the back and if they already exist at an earlier position in the timeline, they're removed from there.
Also fixes an off-by-one index error when removing the day divider for an item that is removed to be re-inserted somewhere else.
=> Respect new server ordering when receiving duplicate events

testing/sliding-sync-integration-test/assets/docker-compose.yml
This prevents the proxy starting before postgres is ready, which causes the proxy to panic.
=> tests: add depends_on block for the sliding sync proxy

bindings/matrix-sdk-crypto-js/src/tracing.rs
Javascript's `console.trace` is not a good equivalent for Rust's `Level::TRACE`.
In particular:
* `console.trace` causes a stacktrace to be written with each message
* Under nodejs, `console.trace` writes the message to `stderr`, while `console.debug` writes to `stdout`
`console.trace` is therefore somewhat analogous to `console.error`.
Since we already include the log level in the message, we might as well just send trace messages to `console.debug` rather than `console.trace`.
=> crypto-js: log trace messages at debug

Cargo.lock, crates/matrix-sdk-base/Cargo.toml
Not sure when it was last used, but it doesn't seem to be anymore.
=> chore(base): Remove unused futures-channel dependency

bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js
We already have support for proper `ToDeviceRequest` objects in `outgoing_requests`, so let's use it in `share_room_key` as well. It's much easier for the application to work with the proper object than an untyped json blob.
=> crypto-js: have `share_room_key` return `ToDeviceRequest`s

crates/matrix-sdk-base/src/sliding_sync.rs
This patch contains few corrections I've noticed when reading the sliding sync code.
=> chore(sdk): Small cleans up when reading the Sliding Sync code

crates/matrix-sdk/README.md
This patch does 2 things:
1. It adds a missing link for `matrix_sdk_base`,
2. It fixes the links to the examples.
---
* Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1517
=> doc(sdk): Fix links to examples and to `matrix_sdk_base`

crates/matrix-sdk/src/room/timeline/mod.rs
Since `PaginationOptions` has its own documentation, I don't think we need the `Arguments` section on the function where it's being passed, hence I just removed it altogether.
=> Remove outdated documentation

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/room/joined.rs
This includes breaking changes beyond adding parameters, as the methods for sending receipts/markers where renamed for the following reasons:
- With the old names one could assume at first glance that they are getters, due to the Rust naming conventions, but they are not.
- The primary use cases of the receipts/read marker endpoints have been lost a bit since they now both allow to set any receipt/marker. The new names reflect more why someone would call one method instead of the other.
This is a big change so maybe we should just deprecate the old methods for now.
=> feat: Allow to get or send any type of receipt

crates/matrix-sdk/src/sliding_sync.rs
In https://github.com/matrix-org/matrix-rust-sdk/pull/1478, I've introduced a regression. The `FrozenSlidingSyncRoom.timeline` field has been renamed to `timeline_queue`.
I didn't notice that this type can be serialized and deserialized. That's actually a breaking change because this type is stored somewhere once serialized. So with #1478, it was impossible to deserialize them!
This patch fixes that. It also adds a test to ensure the serialization form of `FrozenSlidingSyncRoom` doesn't change.
=> fix(sdk): `FrozenSlidingSyncRoom.timeline_queue` must serialize to `timeline`

crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
There wasn't a clear reason why part of the logic was inside `Timeline` an the rest in `TimelineInner`. Also we should honor parallel updates (for example redaction coming in via sync) to an item that we fetch details for.
cc @zecakeh
=> Refactor event detail fetching

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs
It's an error if the room was not found, so it should be surfaced as such.
=> refactor(bindings): Fix SlidingSyncRoom timeline listener return type

crates/matrix-sdk/src/sliding_sync/mod.rs
This patch updates the sliding sync module's documentation after a complete quick reading of it.
=> doc(sdk): Fix Sliding Sync module documentation.

crates/matrix-sdk/src/sliding_sync/config.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/view.rs
Try to minimize `futures-signals` usage / at least make it more obvious (the type aliases made things a bit opaque, especially now after they were partially in a different module from their usage).
=> Some sliding sync refactoring

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs
I was saying so far that I don't think that a race condition is what we're getting but it actually seems very likely – this is the one obvious way we can get mismatched indices here.
=> Lock timeline state once for decryption retrying

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/types/events/dummy.rs, crates/matrix-sdk-crypto/src/types/events/mod.rs, crates/matrix-sdk-crypto/src/types/events/olm_v1.rs, crates/matrix-sdk-crypto/src/types/events/to_device.rs
This mostly just silences an incorrect log warning that we received an unsupported event.
This supersedes https://github.com/matrix-org/matrix-rust-sdk/pull/1330.
This closes https://github.com/matrix-org/matrix-rust-sdk/issues/1230.
=> chore(crypto): Add support for encrypted m.dummy events

crates/matrix-sdk-crypto/src/lib.rs
Resolves #1227 by exposing the `VERSION` from the vodozemac crate.
Signed-off-by: Archit Bhonsle <abhonsle2000@gmail.com>
=> feat(crypto): exposing the version of vodozemac

crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk/src/encryption/mod.rs
Resolves #1227
Exporting the version of `matrix-sdk-crypto` and `matrix-sdk/encryption`.
Signed-off-by: Archit Bhonsle <abhonsle2000@gmail.com>
=> feat(crypto): exposing the version of sdk-crypto

.typos.toml, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/tests/encryption.rs
Previously, it was possible for us to use invalid indices when:
- We retried decrypting multiple events at once
- One of them (not the last) was an edit or reaction
This lead to a situation where we would remove the UTD item once decryption for it was successfully retried, but not account for the resulting index shift for all later timeline items.
=> Rewrite decryption retrying to fix invalid index bug

testing/sliding-sync-integration-test/src/lib.rs
Otherwise it will time out after 30s and then continue executing, causing a slow test.
=> fix(tests): look for the right list when waiting for updates

crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/test_utils.rs, testing/sliding-sync-integration-test/src/lib.rs
So far, the `SlidingSync.pos` field was public to the crate. In order to avoid
breaking the internal state of this type, its visibility is now private.
However, we need to be able to change the value when testing the
`SlidingSync` type itself. To achieve that, this patch removes the old
`force_sliding_sync_pos` function, and implements 2 new functions: `set_pos`
and `pos` directly on `SlidingSync` only when `#[cfg(any(test, feature = "testing"))]`.
=> feat(sdk): Make SlidingSync.pos already private

crates/matrix-sdk/src/client/login_builder.rs, crates/matrix-sdk/src/client/mod.rs
The `Client::login_custom` allows to login by using a custom login method. In particular, it is possible to login to Synapse which supports JWT authentication.
Signed-off-by: boxdot <d@zerovolt.org>
=> Add custom login method

bindings/matrix-sdk-ffi/src/authentication_service.rs, crates/matrix-sdk/src/lib.rs
Passing a URL directly to the AuthenticationService would always fail as the well-known discovery doesn't take place. But it also doesn't report back to the user whether or not there is a valid homeserver at that URL, merely saying sliding sync isn't available which isn't helpful. This PR fixes https://github.com/vector-im/element-x-ios/issues/591 in 2 ways:
- When a URL is entered attempt discovery with a server name first before falling back to the URL directly.
- Check for homeserver details before the proxy so that entering "https://idontexist.com/" fails with the correct error.
=> Verify entered homeserver before proxy availability.

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs, crates/matrix-sdk/src/sliding_sync/view.rs, examples/timeline/Cargo.toml, labs/jack-in/Cargo.toml, labs/jack-in/src/app/model.rs, labs/jack-in/src/client/mod.rs, labs/jack-in/src/client/state.rs, labs/jack-in/src/components/details.rs, labs/jack-in/src/main.rs, testing/sliding-sync-integration-test/Cargo.toml, testing/sliding-sync-integration-test/src/lib.rs
Doesn't look great in places because `Observable` has associated functions / no methods, that is fixable with a new wrapper type but I didn't want to block this PR on that.
=> Replace remaining usage of futures-signal with eyeball(-im)

crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/room/joined.rs
Two small helper functions on Room and RoomMember around power_levels:
- `RoomMember.can_do` exposes the `ruma::PowerLevel::user_can_do`-helper function to check whether a user has the permissions to perform certain actions in the given room.
- `Joined.update_power_levels` is a handy function to update user power levels 
Signed-off-by: Benjamin Kampmann <ben.kampmann@gmail.com>
=> Add powerlevel updates

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
I admit this patch is quite tricky. Please try to follow me.
So, first off, in `SlidingSyncRoom::new`, we were clearing the timeline, because somehow it exists twice in memory at this step.
Which led me to understand how `SlidingSync::handle_response` was working. I've clarified how this part of the code works. We are dealing with 2 kind of responses for a specific reason: `SyncResponse` and `v4::Response`, now it's documented and I hope it's clearer.
Then, I notice that we were passing a clone of the entire sliding sync response (`v4::Response`) to `Client::process_sliding_sync`. I thought it was suboptimal, so I've updated the code to take a reference. It led me to update `BaseClient::process_sliding_sync`. It was a little bit tricky, but I reckon we have less clones now than before. …
=> feat(sdk): Remove clones of large responses in Sliding Sync

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml
Fixes #1580 by enabling the Ruma `unstable-sanitize` feature.
=> fix(bindings): Fix double quotes when replying to a reply.

Cargo.lock, examples/autojoin/src/main.rs, examples/command_bot/src/main.rs, examples/custom_events/src/main.rs, examples/getting_started/src/main.rs, examples/persist_session/Cargo.toml, examples/persist_session/src/main.rs, examples/timeline/src/main.rs
According to the discussion in the Matrix room a few weeks ago, starting here: https://matrix.to/#/!iYnZafYUoXkeVPOSQh:matrix.org/$gWfZEJ0Sh_kKntwRXtT0pvcC8h_TUw3gmCQNAhcBg6Y?via=matrix.org&via=element.io&via=envs.net.
Also don't use the stores in examples if the session is not persisted. Running the same example twice
borks encryption. Instead point to the new example that shows how to do it.
=> feat(examples): Add example to persist a session

crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/read_receipts.rs, crates/matrix-sdk/src/room/timeline/tests/mod.rs, crates/matrix-sdk/src/room/timeline/tests/read_receipts.rs, crates/matrix-sdk/src/sliding_sync/room.rs, crates/matrix-sdk/tests/integration/room/timeline.rs
This adds a list of read receipts for each event in the timeline and keeps it updated.
It also adds a map to allow to keep track of implicit read receipts (a read receipt because a member sent an event).
This is limited because we can't keep track of read receipts on events that don't create `TimelineEventItem`s. We would need to have an ordered list of all events in the timeline to have more reliable tracking.
=> feat(sdk): Keep track of events read receipts in the timeline API

bindings/apple/Package.swift
In order to hopefuly fix the CI for https://github.com/matrix-org/matrix-rust-sdk/pull/1587
=> Add platform versions for swift CI tests

crates/matrix-sdk-indexeddb/Cargo.toml
This patch updates the version of `uuid`. It doesn't bring any significant new features, just something I've found (I'm going to use `uuid` in another crate, that's why I was looking at `uuid` usage in our codebase already).
=> chore(indexeddb): Update version of `uuid`

crates/matrix-sdk/src/sliding_sync/room.rs
The Sliding Sync server might not send some parts of the response, because they were sent before and the server wants to save bandwidth. So let's update values only when they exist.
=> fix(sdk): Deal with missing data in Sliding Sync's responses

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store.rs, crates/matrix-sdk-sled/src/state_store.rs, crates/matrix-sdk/src/client/mod.rs
Same as for the crypto store, this makes store implementations easier. We might also be able to merge the error types of the indexeddb crypto and state store based on this, haven't tried that yet.
=> refactor(base): Add an Error type to StateStore trait

.github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/xtask.yml
Currently, the cache of the `xtask` binary isn't working terribly well:
- we seem to build it on each run anyway, presumably because we don't cache any of the intermediate build artifacts. Running the binary directly rather than indirecting via "cargo" prevents this.
- There is no sharing of the cache between the "rust" and "bindings" CI, because we use different cache keys.
This PR addresses both problems, and hopefully speeds up CI a bit as a result.
=> Clean up the way we build `xtask` in CI

.github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/xtask.yml
This seems to have been cargo-culted to lots of places where it is redundant.
=> Skip installing `protoc` where it is unneeded

crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/mod.rs
To declare the tests, the macro is still used but the content of the tests is moved in the `StateStoreIntegrationTests` trait.
Allows to get the proper line reported when a panic occurs, and have linting, formatting and IDE suggestions.
=> Split `StateStore` integration tests into a trait

crates/matrix-sdk/src/encryption/mod.rs
Exposed a function for uploading encrypted files and preparing an `EncryptedFile`, this would be useful for people who are creating custom events (like me!) and want to leverage the existing `EncryptedFile` definition.
I'm not sure if this is the most sensible place for this function, feel free to suggest somewhere else more suitable if so
=> feat(sdk): Expose `prepare_encrypted_file` function

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs
Fixes vector-im/element-x-ios/issues/297 - Broadcast all UnknownToken errors, handle them on the FFI client side and send a `did_receive_auth_error` delegate call. 
The second step of this PR will be to get rid of the `is_soft_logout` flag from the Session and ClientState, I see no reason why we need to persist those anymore
=> Broadcast UnknownToken errors

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, bindings/matrix-sdk-ffi/src/lib.rs
* remove now unused FFI Client `start_sync` method and related properties
* remove the `is_soft_logout` flag from the session, remove the `did_update_restore_token` ClientDelegate method and now empty `ClientState`. With the `UnkownToken` broadcast in place the `did_receive_auth_error(is_soft_logout)` delegate method will be invoked at all times. There's no need to store it in the session anymore and, if necessary, the final client can decide to store it next to the session instead of inside it
=> FFI client cleanup

crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/tests/integration/main.rs, crates/matrix-sdk/tests/integration/room/joined.rs
The first patch is the meat of the PR, i suggest this to be reviewed commit by commit.
The second patch makes it easier to ensure that some fields, i.e. the `members_synced` field, are only modified in one place of the codebase.
The third patch makes sure that syncing members only happens if it isn't already done so.
=> Fix a race condition around some methods that get deduplicated

Cargo.lock, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/lib.rs
Add a crate constructor, somewhat cargo-culted from the other crates, to enable tracing output from the tests.
=> matrix-sdk-crypto: enable tracing for in-crate tests

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This commit simplifies the logic for handling sliding sync extensions. These extensions are sticky, meaning that once enabled in one request, they do not need to be repeatedly enabled for subsequent requests.
However, the previous logic tried to accommodate the case where the extensions were initially disabled to reduce the size and processing time of the initial response. This resulted in complex and error-prone code.
With this patch, we have removed support for disabling to-device events and streamlined the handling of sync extensions.
=> Simplify handling of sliding sync extensions

Cargo.lock, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs
The IndexedDB API expects an unsigned integer for the version but the web-sys bindings expose it as a `f64` so versions like `1.1` and `1.2` were used. The version was converted back to a "uint" in JS which means the version was always `1` and no real upgrade was processed on the JS side (the migrations in the Rust code were processed, but the second `onupgradeneeded` callback was never called).
It is also not possible to open the DB with a version lower than the current DB version, that would throw an error, so instead we just open the DB as-is first and it gives us the current version, then we can prepare the whole upgrade.
I opened [an issue](https://github.com/Alorel/rust-indexed-db/issues/20) upstream. If it is fixed we should be able to process the whole upgrade in the …
=> Fix indexeddb migrations

.github/workflows/coverage.yml
Specify a token for codecov. According to codecov, this should fix the upload issues, which are related to rate limiting in GitHub's API. They might still happen for external contributors, but maybe if we just reduce our API usage this way, rate limiting isn't going to be a problem anymore.
=> ci: Work around frequent codecov upload errors

crates/matrix-sdk-base/src/deserialized_responses.rs, xtask/src/kotlin.rs
This is an event type that was deserializing from serde's weird default `{ "Tag": { /* enum fields */ } }` enum representation. Hopefully nobody is using this impl, but since `Serialize` was already not implemented either, chances are very low this was used.
=> A little bit of cleanup

Cargo.lock, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sled/src/state_store/migrations.rs, crates/matrix-sdk-sled/src/state_store/mod.rs
See discussion: https://github.com/matrix-org/matrix-rust-sdk/pull/1571#pullrequestreview-1315464275.
Avoids to make the API bigger when we want to add a new kind of data in the key-value stores.
Based on #1614.
=> state-store: Replace methods to get and set key-value data

examples/login/Cargo.toml, examples/login/src/main.rs
The login example didn't seem very useful because it used the same login method used in every other examples. I believe this is more useful because it shows how a regular client login flow would look like.
=> feat(examples): Also handle SSO login in the login example

Cargo.lock, Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/sliding_sync/mod.rs
This patch adds a new feature.
Each call to `SlidingSync::stream` generates a unique `stream_id`. This `stream_id` is passed to requests as a `txn_id` field. Returned responses must hold the same `txn_id`, otherwise it means `stream` has received unexpected responses from another `stream` or something else.
So far, when the `txn_id` field of the response and the `stream_id` don't match, a log with the `ERROR` level is raised. Should we do more, like ignoring the response entirely? Not sure yet.
=> feat(sdk): `SlidingSync::stream` can match expected responses

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs, bindings/matrix-sdk-crypto-ffi/src/error.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-crypto-ffi/src/responses.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs
Taking the upgrade commit from #1587, and converting a fallible functions to prove it's possible and reduce UDL file size.
The `&str` to `String` change can be undone once the proc-macros support `&str`. AFAIK it doesn't make a difference for the generated bindings, right?
=> Upgrade UniFFI, use proc-macros more

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Before this patch, `SlidingSync::sync` was returning a callback-based `TaskHandle`. It was waiting on the “stream loop” to finish (since it's a long- poll, it means waiting 2*30s, cf. our code), before checking an atomic flag has some value to decide whether it was time to leave the loop or not. So when the user is cancelling this `TaskHandle`, a response (if any) was always handled. But in the meantime, it was possible to start a new `sync`, and it seems like it creates bugs. It's not easy to reproduce but it's kind of easy to understand: **Responses are applied on the same `SlidingSync` instance in no particular order concurrently**.
After this patch, `SlidingSync::sync` now returns a handle-based `TaskHandle`. It means that cancelling it will cancel the “stream loop” immediately. If no …
=> fix(bindings): `SlidingSync.sync` returns an immediately cancellable `TaskHandle`

crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/mod.rs
This PR attempts to fix https://github.com/matrix-org/matrix-rust-sdk/issues/1386.
The comments in the code should explain the general approach, but to give an overview:
We assign a unique sequence number to each device-list-invalidation notice, and keep track of the sequence number at which each user was most recently invalidated. Then, when we build a `/keys/query` request, we take note of the current sequence number. Finally, when we get the response from that `/keys/query` request, we compare that sequence number with the most-recent-invalidation of each user that is now supposedly up-to-date. All of that means that we can see if the user has been invalidated *since* we built the `/keys/query` request, in which case our request may have raced against the new device, so we do not mark …
=> Fix races between `/sync` and `/keys/queries`

crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/login_builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
This patch moves `Client.root_span` inside `ClientInner`. That way, when cloning `Client`, we don't clone the `root_span: Span` everytime.
Try to fix https://github.com/matrix-org/matrix-rust-sdk/pull/1587 one commit at a time.
=> feat(sdk): Move `Client.root_span` inside `ClientInner`

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This patch updates `SlidingSync.pos` and `.delta_token`. Each field has their own lock. It's annoying because they must be updated at the same time to not be out-of-sync. #1601 adds a mechanism to supposedly avoid this out-of-sync problem, but still, we can have a single lock instead of two.
So a new field `SlidingSync.position` of type `SlidingSyncPositionMarkers` is created. It holds `pos` and `delta_token`. This new field is behind a single `RwLock`.
=> fix(sdk): `SlidingSync` has a lock for both `pos` _and_ `delta_token`

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs, crates/matrix-sdk/tests/integration/room/joined.rs, crates/matrix-sdk/tests/integration/room/timeline.rs, labs/jack-in/src/app/model.rs, labs/jack-in/src/client/state.rs, testing/sliding-sync-integration-test/src/lib.rs
Hope the reduction in `*`s is appreciated 😄
I think we should use the `Subscriber` type in more places. We probably don't need three distinct session token accessors in the client if we just return a `Subscriber`.
=> Upgrade to eyeball 0.4.0

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs
This PR adds the [createRoom](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-createroom) UniFFI binding.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1615
=> Add createRoom UniFFI binding

crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/read_receipts.rs, crates/matrix-sdk/tests/integration/room/timeline/mod.rs, crates/matrix-sdk/tests/integration/room/timeline/read_receipts.rs
This is to avoid unnecessary requests for clients. They can just call this method every time without having to check where they are in the timeline compared to the read receipts.
If we don't know where the receipts are in the timeline, we just make the request and let the server handle it.
Based on #1530.
=> feat(sdk): Add methods to only send receipts newer than the current ones in the timeline

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/room/joined.rs
Created the functions in the title, and exposed a binding for `upload_avatar` and `set_topic` in FFI
=> feat(room): `set_avatar_url` `remove_avatar_url` `upload_avatar` `set_topic`

Cargo.lock, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/mod.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Fixes #1618.
We replace the existing `KeysQueryListener` with new functionality tied into the `users_for_key_query` logic in the Store.
~~Based on #1619.~~
=> Fix races in `wait_if_user_pending`

bindings/CONTRIBUTING.md, bindings/README.md
This PR adds a guide for people that don't know Rust well, but they still want to contributed to UniFFI bindings.
=> Add a guide for contributing to UniFFI bindings

.gitignore, bindings/apple/Tests/MatrixRustSDKTests/AuthenticationServiceTests.swift, bindings/matrix-sdk-ffi/src/authentication_service.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/tests/integration/client.rs
Entering `https://matrix-client.matrix.org/` failed with an error about being an invalid domain or IP address. This PR fixes that by
- Trimming any trailing slashes (and whitespace whilst we're here) when sanitising.
- Trying to build the client with a URL instead of throwing when server name fails (e.g. `https://company.com/matrix`).
Additionally it adds tests to both the sanitising (Rust) and the service (Swift).
=> fix(bindings): More authentication service server name fixes.

Cargo.lock, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/media.rs
This PR adds a `get_media_file` that writes the decrypted media to disk and returns a `MediaFileHandle`. This handle maintains ownership of the file on disk and will delete it (via use of tempfile) when dropped.
What this PR doesn't do:
- De-duplicate requests of the same file (either for the potential HTTP requests or with shared handles over the same file).
- Expose a way for the app to tidy up the folder on launch if the app crashed with a file handle open. I'm unsure what would make most sense here e.g.
- The app specifies the temp directory and tidies it up itself.
- The app asks the SDK to tidy it up.
- The SDK automatically tidies it up when creating a client.
=> Add get_media_file function.

.github/workflows/ci.yml, crates/matrix-sdk/src/attachment.rs
Noticed that it wasn't compiling when running `cargo test` instead of `cargo nextest`.
Also adds a commit to make sure that all examples shown in the docs compile. 
=> sdk: Fix generate_image_thumbnail example in docs

crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/tests/integration/room/joined.rs
To go with the recent methods added to change the topic and avatar.
=> sdk: Add a method to change the room name

bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-js/src/lib.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js, bindings/matrix-sdk-crypto-nodejs/src/lib.rs, bindings/matrix-sdk-crypto-nodejs/tests/machine.test.js
Edit from @Hywan:
This PR adds a `Versions` class in JS and NodeJS that expose the `matrix-sdk-crypto` and `vodozemac`'s versions.
It also adds a `version()` and `vodozemac_version()` functions in FFI.
=> Re-expose the vodozemac and matrix-sdk-crypto versions in the bindings

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs
The url crate normalizes the string, but during OIDC verification steps, the issuer verification must be made against the exact string that was provided.
See https://github.com/matrix-org/matrix-authentication-service/pull/616.
=> sdk: Store OIDC issuer as a `String` rather than a `Url`

.github/workflows/bindings_ci.yml, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, labs/jack-in/src/client/mod.rs, labs/jack-in/src/client/state.rs, testing/sliding-sync-integration-test/src/lib.rs
This patch should ideally be split into multiple smaller ones, but life
is life.
The main purpose of this patch is to fix and to test
`SlidingSyncListRequestGenerator`. This quest has led me to rename
mutiple fields in `SlidingSyncList` and `SlidingSyncListBuilder`, like:
* `rooms_count` becomes `maximum_number_of_rooms`, it's not something
the _client_ counts, but it's a maximum number given by the server,
* `batch_size` becomes `full_sync_batch_size`, so that now, it
emphasizes that it's about full-sync only,
* `limit` becomes `full_sync_maximum_number_of_rooms_to_fetch`, so that
now, it also emphasizes that it's about full-sync only _and_ what the
limit is about!
This quest has continued with the renaming of the `SlidingSyncMode`
variants. After a discussion with the ElementX team, …
=>  fix(sdk): Fix, test, and clean up `SlidingSyncListRequestGenerator`

bindings/matrix-sdk-crypto-js/package.json
I'd like to cut a new release of the crypto-js bindings, in particular to include #1619 and #1633.
=> matrix-sdk-crypto-js: prepare v0.1.0-alpha.5

bindings/matrix-sdk-crypto-js/.yarnrc
Currently, the tags used for releases of this binding have the format: "matrix-sdk-crypto-js-v0.1.0-alpha.5". This is inconsistent with tags used for other parts of the project, which omit the `v` prefix.
=> matrix-sdk-crypto-js: drop `v` from release tags

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk/src/account.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs
This PR put some logic in the Client type to update the `m.direct` account_data when creating a new dm room.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1674
=> Update account_data when creating a new dm room

Cargo.lock, Cargo.toml, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
… and adopt its change from `im` to `imbl`. We still need to pull that in explicitly because we use its `vector!` macro which is not re-exported, and because we want to enable its `serde` feature.
=> Upgrade eyeball-im

crates/matrix-sdk/src/sliding_sync/mod.rs
With https://github.com/matrix-org/matrix-rust-sdk/pull/1601, it's safer to cancel a stream at any time, as any `Future` cancellation. This documentation section of `SlidingSync` is no longer relevant as is, and can be rephrased.
Thoughts?
=> doc(sdk): Rephrase the Quick refreshing Section

crates/matrix-sdk/src/sliding_sync/room.rs
Event deduplication is supposed to be handled by the `Timeline`. Sliding
Sync is not responsible to de-duplicate the events, in our model. Having
two different de-duplication logics (one in Sliding Sync, and one in the
Timeline) could create weird situations, and hard to debug issues.
We give it a try by removing the deduplication from Sliding Sync.
=> feat(sdk): Remove deduplication logic from Sliding Sync

examples/persist_session/src/main.rs
=> sdk: Use new filter constructor to enable room members lazy-loading

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/client_builder.rs
Since we have no migration from Sled to SQLite we'll have to log our EX users out. cc @stefanceriu.
=> Switch the FFI bindings to use the SQLite cryptostore

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs
This PR adds `report_content_and_ignore` that is like `report_content` but with an additional step to ignore the user. I considered adding `sender_id` as an optional string to `report_content` but decided it wasn't clear enough that supplying this would ignore the user, hence the specific method.
=> feat(bindings): Add report_content_and_ignore.

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk/src/client/mod.rs
This will require also a restart of SS and the cache to be cleaned, which @Hywan is working on separately, otherwise in offline cases the cold cache could restore the old messages.
=> feat: resetting the timeline when an ignore user list event is received

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/tests/virt.rs, crates/matrix-sdk/tests/integration/room/timeline/mod.rs
=> sdk: Never insert read marker in last position in timeline

crates/matrix-sdk/src/client/mod.rs
Workaround for [this](https://github.com/matrix-org/matrix-ansible-private/issues/6902) causing a loop of retries on the get profile
=> Add "short retry" strategy on the get profile

crates/matrix-sdk/src/sliding_sync/builder.rs
Prior to this patch, when `SlidingSync` was built with a storage key,
the storage was read to find a previous `SlidingSync` version that
was in a cache. To put a `SlidingSync` instance in the cache, it
was serialized to JSON. When one reads from the cache, the value is
deserialized. A problem happens when the internal representation of
`SlidingSync` and other types (e.g. `SlidingSyncList`) have changed (due
to an SDK update for example): Loading a previous state from the cache
results in an error.
After discussion with the teams, clients don't want to deal with
obsolete cache values. In such a scenario, (i) they cannot interact
with the cache to remove the obsolete entry, and (ii) their only
possibility is to log out and log in the user again. What an unfriendly
user experience!
This …
=> feat(sdk): When a `SlidingSync` cache is obsolete, let's remove it

crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/machine.rs
In some cases, restoring client state from backups may cause Olm sessions to become corrupted, resulting in a backward ratchet. As a consequence, the receiving side is unable to decrypt messages. To address this issue, the failed side initiates a new Olm session and sends a dummy encrypted message.
However, this dummy message also creates a new Olm session on the sender's side. To ensure that both sides use the same new session, we must sort sessions by their creation timestamp before encrypting new messages.
Although the session list was sorted correctly previously, we selected the wrong side of the list, resulting in an outdated session being selected instead of the newest one. This patch resolves the issue by selecting the newest Olm session and adds a test to the session getter logic …
=> Ensure correct Olm session selection for encrypted messages

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room.rs
This PR is self explanatory and fixes #1623 
Exposes said function to the FFI. Defined in the .adl file, and defined to throw `ClientError`
Signed-off-by: Simon Farre <simon.farre.cx@gmail.com>
=> Fix #1623 - Expose `invite_user_by_id`

crates/matrix-sdk/src/room/timeline/event_item/content.rs
I'm currently debugging problems with editing replies, and having this logged would be very helpful in that.
=> sdk: Log in_reply_to field in timeline::Message Debug impl

bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/mod.rs, crates/matrix-sdk/src/room/timeline/event_item/remote.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/tests/integration/room/timeline/mod.rs
Yesterday, I was debugging reply edits with Stefan, this would have been very useful.
=> Add more debug info for event timeline items

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
In https://github.com/matrix-org/matrix-rust-sdk/pull/1736, I've introduced a bug. We use a different keys when restoring than when storing `SlidingSync` in the client's store. It then breaks the “cold start”, the cache is always empty.
This patch does the following:
1. It creates a new `sliding_sync::cache` module,
2. It moves the existing “cache functions” into this new module (resp. `format_storage_key*`, `clean_storage` and `restore_sliding_sync_state`),
3. It creates a new `store_sliding_sync_state` function (it's just moved from `SlidingSync::cache_to_storage` + the bug fix),
4. It updates `SlidingSync::cache_to_storage` to use this new function,
5. It adds a test.
We should refactor this a little bit more, but let's keep the refactoring for later.
=> fix(sdk): `SlidingSync` uses the same storage keys for storing *and* restoring

crates/matrix-sdk-base/src/store/memory_store.rs
It doesn't seem very interesting since a memory store will be fast anyway. In practice, this fills the console quickly.
Signed-off-by: Olivier 'reivilibre' <oliverw@matrix.org>
=> Downgrade memory store 'Saved changes in <time>' log line to debug

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
Those methods are public, but never used by our current users.
Moreover, there is some big overlaps. For example, `storage_key`, `cold_cache` and `no_cache` do the same thing: They update the `storage_key` field. Or `add_fullsync_list` is just a helper that is never used except in the tests etc.
=> chore(sdk): Remove unused methods in `sliding_sync`

crates/matrix-sdk/src/encryption/mod.rs
It's the output type of `Encryption::cross_signing_status()` but it's not re-exported in the main crate. 
=> sdk: Re-export `CrossSigningStatus`

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-base/src/rooms/normal.rs
Fixes #1751 
This PR also adds `avatar_url_string` on Room in normal.rs.
The reason for doing this, is because the regular `avatar_url` on Room (the non-sliding sync FFI-exposed version) calls `avatar_url` on Room in normal.rs, which first clones the `OwnedMcxUri`.
`avatar_url_string` instead of doing an (unnecessary) deep copy, creates a string directly from the underlying data type as this is to be returned across the FFI boundary anyhow.
Signed-off-by:  Simon Farre <simon.farre.cx@gmail.com>
=> Fix #1751 - Adds & exposes `avatar_url` for SlidingSyncRoom

crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
I talked to Kévin who added this function, the `Ok()` return value was supposed to be used later but it's no longer clear that we actually need it for anything.
=> sdk: Simplify return type of fetch_in_reply_to_details

crates/matrix-sdk/src/sync.rs
While refactoring some read receipt code I was wondering if it was possible for the read receipt of a local echo to be handled before the event itself. I think it was, but only due to the weird order we handled events in. This should fix that.
=> sdk: Handle ephemeral events after timeline events

crates/matrix-sdk-sqlite/migrations/006_drop_outbound_group_sessions.sql, crates/matrix-sdk-sqlite/src/crypto_store.rs
This was forgotten as part of https://github.com/matrix-org/matrix-rust-sdk/pull/1483. The PR changed the format of the `OutboundGroupSession`, so any old sessions can't be restored anymore.
=> Drop outbound group sessions because of the withheld support

bindings/matrix-sdk-ffi/build.rs
Adds a temporary workaround to `bindings/matrix-sdk-ffi/build.rs` where we replace a linked library with a version that works fine in Android devices with x86_64 arch. This should let us release working versions of the Rust SDK for Android even while [this bug](https://github.com/rust-lang/rust/issues/109717) still exists.
=> Add workaround for building Android bindings with supported NDK versions (r23+)

Cargo.lock, Cargo.toml, crates/matrix-sdk/src/events.rs, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/inner.rs
As of [Synapse v1.79.0](https://github.com/matrix-org/synapse/releases/tag/v1.79.0) (earlier if a homeserver admin opted in), Synapse no longer replaces the content of edited messages with the edit in the client-server API, as per MSC3925. This updates the timeline implementation to be able to handle both edited-message representations. (the heavy lifting is done in Ruma, of course)
I don't think this will work for encrypted rooms yet – we'd have to decrypt the edit inside the bundled edit relation, which I don't think we do.
=> Implement MSC3925 for the timeline

crates/matrix-sdk/src/room/common.rs
For direct rooms a client is interested to store for each user, the set of direct room it has with him.
It doesn't make much sense to store the same information for its own user id.
Doing so the account data would collect duplicate information without apparently any benefit.
**Example**
If `U1` is marking direct a room `R1` with `U2` and `U3`:
_Before this PR the result would be_
```json
{
"U1": [ "R1" ],
"U2": [ "R1" ],
"U3": [ "R1" ]
}
```
_After this PR_
```json
{
"U2": [ "R1" ],
"U3": [ "R1" ]
}
```
=> Remove its own user id when updating the account data

crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sled/src/state_store/migrations.rs, crates/matrix-sdk-sled/src/state_store/mod.rs
Currently the member events are not stored with the other state events. This has the pitfall of room member events not being available via methods like `Common::get_state_event()` (the example of [`Common::get_state_events_static()`](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk/room/struct.Common.html#method.get_state_events_static) would even always return an empty `Vec`). I also don't see any benefit in putting them in a separate list because accessing them among other state events is quite easy (although slightly more verbose in places).
Sadly this is one big commit because changing one thing requires changing a lot of other things.
=> base-sdk: Don't separate member events from other state events

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/local.rs, crates/matrix-sdk/src/room/timeline/event_item/mod.rs, crates/matrix-sdk/src/room/timeline/event_item/remote.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/read_receipts.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/room/timeline/tests/echo.rs, crates/matrix-sdk/src/room/timeline/tests/encryption.rs, crates/matrix-sdk/src/room/timeline/tests/invalid.rs, crates/matrix-sdk/src/room/timeline/tests/read_receipts.rs, crates/matrix-sdk/tests/integration/room/timeline/mod.rs, crates/matrix-sdk/tests/integration/room/timeline/read_receipts.rs, testing/sliding-sync-integration-test/src/lib.rs
Remove `LocalTimelineItem` and `RemoteTimelineItem` from public API since it isn't really needed and we have more flexibility with how to lay out the types without that.
Also make fields of `EventTimelineItem`, `LocalTimelineItem` and `RemoteTimelineItem` public within the `timeline` module so we don't need as many one-line functions.
=> Remove LocalEventTimelineItem, RemoteEventTimelineItem from public API

bindings/apple/MatrixSDKCrypto-Local.podspec, bindings/apple/MatrixSDKCrypto.podspec, bindings/apple/README.md, bindings/apple/build_crypto_xcframework.sh, bindings/matrix-sdk-crypto-ffi/README.md
Update a few details about the building / publishing of the iOS artifact for the crypto SDK. Note that this quite quite a manual process with several steps and a lot to be desired, the changes in this PR only make those steps as explicit as possible (thus providing a recipe for future automation).
Add also add second podspec file for local development that poinst to local source files
=> Update iOS Crypto SDK docs

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/mod.rs, crates/matrix-sdk/src/room/timeline/event_item/remote.rs
It would have been useful to know where a remote event came from in previous debugging sessions.
=> sdk: Add more data to RemoteEventTimelineItem Debug string

crates/matrix-sdk/src/room/timeline/event_item/content.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/list/room_list_entry.rs, crates/matrix-sdk/src/sliding_sync/room.rs
We don't seem to be running the same checks in CI that `cargo xtask ci` does, since it fails while CI passes. We seem to have accumulated a number of broken intra-doc links, but for most (in sliding sync) I don't actually know how to rewrite them. This fixes the obvious ones.
=> Fix some rustdoc warnings

bindings/matrix-sdk-crypto-js/src/device.rs, bindings/matrix-sdk-crypto-js/src/encryption.rs, bindings/matrix-sdk-crypto-js/tests/device.test.js
Implement `Device.algorithms` and `Device.isSignedByOwner` for the js bindings.
=> crypto-js: Expose more data on `Device`

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/lib.rs
… and get rid of `uniffi_types` modules! 🎉 
We're also getting closer to proper error handling in FFI, removing `anyhow::Result<_>` in favor of more specific signatures although we don't yet have specific error variants in place (I wanted the diff to be small and only did what was necessary for the UniFFI upgrade in terms of error changes).
=> Upgrade UniFFI

bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/error.rs
Fixes #1806
Withheld error binding was exposing human readable error instead of withheld vcode
=> fix(bindings) Withheld code mapping

bindings/matrix-sdk-ffi/src/platform.rs
We may want our own formatter entirely at some point, but this is an easy improvement in the meantime.
=> ffi: Print location for tracing events

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-appservice/src/lib.rs, crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sled/src/state_store/migrations.rs, crates/matrix-sdk-sled/src/state_store/mod.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/encryption/identities/users.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs, crates/matrix-sdk/src/room/member.rs, crates/matrix-sdk/tests/integration/room/common.rs, testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
Introduce flags to filter results at the store level, which should allow to benefit from optimizations in the backend (in the future SQLite state store for example).
Reduces also the number of methods in the API by exposing only one method for all memberships. Other methods are deprecated.
Based on #1794.\
Fixes #930.
=> sdk: Allow to filter members and user IDs store results by membership

.github/workflows/bindings_ci.yml, .github/workflows/documentation.yml, .github/workflows/release_crypto_js.yml, bindings/matrix-sdk-crypto-nodejs/README.md, bindings/matrix-sdk-crypto-nodejs/package.json
This updates the supported Node.js versions to cover the current/active/maintenance release states as of the end of April 2023.
=> Update supported Node.js versions

crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sled/src/state_store/migrations.rs, crates/matrix-sdk-sled/src/state_store/mod.rs
Storing as bitset is not future-proof: the `UNKNOWN` bit will always be unsupported while a string can become supported in a future version.
This also removes the `UNKNOWN` filter as it can be complicated to match against strings and should not be very used.
=> sled & indexeddb: Store memberships as strings

.github/workflows/bindings_ci.yml, .github/workflows/prep-crypto-nodejs-release.yml, .github/workflows/release-crypto-nodejs.yml
Should fix #1808
Signed-off-by: Andrew Ferrazzutti [andrewf@element.io](mailto:andrewf@element.io)
=> Build Node bindings against Ubuntu 20.04

crates/matrix-sdk-crypto/src/utilities.rs
The [spec](https://spec.matrix.org/v1.6/appendices/#unpadded-base64) says:
> When decoding Base64, implementations SHOULD accept input with or without padding characters wherever possible, to ensure maximum interoperability.
cc @jplatte @poljar 
=> crypto: Enable decoding padded base64

.github/workflows/ci.yml, crates/matrix-sdk/src/sliding_sync/list/mod.rs, testing/sliding-sync-integration-test/assets/docker-compose.yml
Now that https://github.com/matrix-org/sliding-sync/issues/52 is fixed, we can remove the hacks introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/1699 to handle bad ranges.
It may fix some bugs we have now. The hacks were intended to work with a buggy proxy, not with a valid one (the behaviors were very different).
Let's try this.
=> feat(sdk): Remove hacks for Sliding Sync ranges

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs, bindings/matrix-sdk-crypto-ffi/src/error.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-ffi/src/olm.udl, bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/notification_service.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs, bindings/matrix-sdk-ffi/src/tracing.rs
Supported now with https://github.com/mozilla/uniffi-rs/pull/1518 + https://github.com/mozilla/uniffi-rs/pull/1520 :)
=> Use UniFFI proc-macros for constructors

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/machine.test.js
Needed in https://github.com/vector-im/element-web/issues/25215
=> JS Bindings: make `unused_fallback_keys` as optional in `machine.rs/receive_sync_changes`

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/notification_service.rs, bindings/matrix-sdk-ffi/src/tracing.rs
Using the `#[derive(uniffi::Object)]` on certain types make them not show up in the `.aar` file when building for Android. Could not determine why that is, but removing the derive macro, and adding the empty interface declarations inside the UDL, makes them turn back up again in the final `.aar`
we can still use `#[uniffi::export]` and `#[uniffi::constructor]` as expected. Further research will have to be done to determine why the object derive macro is causing this issue, but the documentation on uniffi does say it's experimental, so maybe the opaque interface declarations should be the preferred approach, going forward?
=> Add "opaque interface declarations"

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/notification_service.rs
This is to allow clients to decide if they want to discard notifications that are already read or not.
=> feat(bindings): Add is_read field on NotificationItem

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/notification_service.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
An useful field that could be used by client to discard or show notifications based on their sent timestamp
=> feat(binding): added the timestamp field to NotificationItem

bindings/matrix-sdk-crypto-js/scripts/build.sh
When running:
`yarn build`
This error is happening: 
```
Usage:  base64 [-hDd] [-b num] [-i in_file] [-o out_file]
-h, --help     display this message
-Dd, --decode   decodes input
-b, --break    break encoded string into num character lines
-i, --input    input file (default: "-" for stdin)
-o, --output   output file (default: "-" for stdout)
````
[Room discussion](https://matrix.to/#/!lKmPiFsblczTEuHjWH:matrix.org/$Pcz75mtp3bv0SuINM0twMO2xAV9aJwaQiKD8K6lH_rQ?via=matrix.org&via=element.io&via=t2l.io)
=> Fix Wasm conversion into base64

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/machine.rs
Currently this takes a `CrossSigningKeyExport`, but that's not a class you can construct from the JS side. Instead, let's just pass in the individual keys.
=> crypto-js: Make `importCrossSigningKeys` take strings

Cargo.lock, bindings/matrix-sdk-crypto-ffi/Cargo.toml, crates/matrix-sdk-appservice/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-indexeddb/Cargo.toml, crates/matrix-sdk-qrcode/Cargo.toml, crates/matrix-sdk-sled/Cargo.toml, crates/matrix-sdk-sqlite/Cargo.toml, examples/command_bot/Cargo.toml, examples/custom_events/Cargo.toml, examples/getting_started/Cargo.toml, testing/matrix-sdk-test-macros/Cargo.toml, xtask/Cargo.toml
Removes some unused dependencies, automatically detected by [cargo-machete](https://github.com/bnjbvr/cargo-machete). There weren't any unused dependencies overall across the workspace, but a few dependencies might have moved from one crate to another during the course of development, so this could help with reducing compile times by shuffling the cargo build pipeline.
I'm a bit dubious about some of the dependencies flagged as unused, so there might be a few false positives (I could at least build all the native tests with those changes); let's see what CI says.
=> Remove unused dependencies

Cargo.lock, bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/media.rs
Fixes https://github.com/vector-im/element-x-ios/issues/843
As the issue above describes, simple text files (and surely others) aren't currently renderable iOS side. This happens because we use `mime_guess` to infer an extension from the content type and that results in a list of extensions sorted in no particular order. In this case `text/plain` results in `asm` because it just happens to be the first match from [this list](https://github.com/abonander/mime_guess/blob/master/src/mime_types.rs#L92) which iOS doesn't know what to do with.
To fix that this PR switches over to [mime2ext](https://github.com/blyxxyz/mime2ext#see-also) (like [this comment](https://github.com/abonander/mime_guess/issues/59#issuecomment-1110023679) from `mime_guess` suggests) which does return more commonly used …
=> fix(ffi): Generate correct temporary file names for media attachments

crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/content.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/room/timeline/tests/edit.rs, crates/matrix-sdk/src/room/timeline/tests/mod.rs
=> sdk: Sanitize timeline HTML input and remove reply fallbacks 

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/requests.rs, bindings/matrix-sdk-crypto-js/src/responses.rs, crates/matrix-sdk-crypto/src/machine.rs
Currently, we can't pass the response to a `SigningKeysUploadRequest` into `mark_request_as_sent`, which apparently we should be able to do.
So, we need to make `SigningKeysUploadRequest` have a `type` like the other `OutgoingRequest`s, and  add support for `SigningKeysUploadResponse` to `OwnedResponse`.
=> crypto-js: extend `mark_request_as_sent` to accept SigningKeysUploadResponses

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/content.rs
If the redaction already happened server-side, it is a bug for the server to even still have access to the non-redacted form.
We don't accept the server data in this case, and also log a warning.
=> sdk: Don't add original form of redacted events to the timeline

crates/matrix-sdk/src/room/timeline/event_handler.rs, crates/matrix-sdk/src/room/timeline/event_item/remote.rs, crates/matrix-sdk/src/room/timeline/tests/basic.rs, crates/matrix-sdk/src/room/timeline/tests/echo.rs, crates/matrix-sdk/src/room/timeline/tests/edit.rs, crates/matrix-sdk/src/room/timeline/tests/encryption.rs, crates/matrix-sdk/src/room/timeline/tests/invalid.rs, crates/matrix-sdk/src/room/timeline/tests/mod.rs, crates/matrix-sdk/src/room/timeline/tests/redaction.rs, crates/matrix-sdk/src/room/timeline/tests/virt.rs
Regression almost certainly introduced in #1791. I'm a bit puzzled that we only had a redaction test for reactions, not for the main content. I thought I had written one way back. Should be the proper fix for #1864.
=> Fix redaction regression

bindings/matrix-sdk-crypto-js/scripts/epilogue.js
The `const` is needed for the module to be loaded in browser if you use ESModules. It seems like in commonjs this works fine, but ESM is stricter on variable declaration. Without this, it fails with `Uncaught ReferenceError: __initSync is not defined ` when it tries to import the package. This should have no impact on commonjs.
=> Add missing const to make epilogue.js work in ECMAScript Module compatibility mode

crates/matrix-sdk/src/room/timeline/event_handler.rs
Logs I got from EX are puzzling, add another log for a thing where I'm not sure if we're hitting it (redacting an event we already consider redacted), and avoid some unnecessary work for that same thing.
=> sdk: Log redactions of already-redacted events

bindings/matrix-sdk-crypto-ffi/src/lib.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/session.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sled/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs
=> Consistently use Ruma's Owned*Id types

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk/src/room/common.rs
This PR adds `invited_members_count` and `joined_members_count` for the room type.
=> Add invited and joined members counts

crates/matrix-sdk/src/room/timeline/event_handler.rs
It's a shame we need that branch at all, this reduces its specialness to fix a regression where it was interfering with timeline item ordering.
=> Fix timeline ordering regression

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/sync.rs, crates/matrix-sdk-common/src/debug.rs, crates/matrix-sdk-common/src/deserialized_responses.rs, crates/matrix-sdk-common/src/executor.rs, crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-common/src/timeout.rs, crates/matrix-sdk/src/sync.rs
Regarding the last commit, I want to note that my main goal there was consistency, which we didn't have between the room event lists (state, account data, ephemeral events). The solution I chose also shrinks the `Debug` output and makes customizing it a little easier, which is why I did it this way rather than updating account data to be like the other fields. I'm happy to revert that and change the account data field instead though.
=> Some refactoring around the sync response types

.github/workflows/documentation.yml, bindings/matrix-sdk-crypto-ffi/src/machine.rs, bindings/matrix-sdk-crypto-js/README.md, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync/README.md
This fixes the documentation so running `cargo xtask doc` locally keeps on working. Second commit also adds a CI task to make sure we don't regress this in the future, and that we can keep on using `cargo xtask ci` on local machines.
=> chore: Fix cargo xtask doc

crates/matrix-sdk-common/src/debug.rs
It was looking for an "event_type" field rather than just "type". The code was also more complex than necessary.
=> Fix debug output for raw events

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/notification.rs
the `get_room_member function` used for Common was always giving me a 403 for rooms where the user is invited.
So I used instead the `invite_details()` available on `Room::Invited`
Also there is an issue with the `is_encrypted()` call failing for Invited rooms:
https://github.com/matrix-org/matrix-rust-sdk/issues/1901
So for now I made the `is_encrypted` `bool `an `Option`
If this issue is likely going to be fixed soon, we can wait for the fix before approving and merging this PR, to keep the `is_encrypted` bool not optional, which is for sure more consistent
=> fix(bindings): Fix for notification item to get sender in invited rooms

crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk/src/encryption/identities/devices.rs
The commit adds a method that allows to check first if any device is cross-signed.
cc @poljar.
=> Only send verifications requests to devices that are cross-signed

Cargo.lock, benchmarks/Cargo.toml, benchmarks/benches/crypto_bench.rs
- This fixes the crypto bench by ensuring a tokio runtime is active whenever a `OlmMachine` built with a `SqliteCryptoStore` is dropped. That's necessary because `deadpool` makes use of `block_on` in the `Drop` implementation of one of its managers.
- This also adds back sled to the crypto benchmarks, so we can compare the performance of the two backends.
Turns out that sled was faster than sqlite: full report temporarily hosted on https://benj.me/pub/criterion/report/
| Benchmark | Mem | Sled | Sqlite |
| -- | -- | -- | -- |
| devices missing session collecting | 8.59 ms | 16.23 ms | 133.36 ms |
| keys quering |3.5 ms | 6.69 ms | 8.01 ms |
| olm session creation | 35.24 ms | 38.07 ms | 46.74 ms |
| room key sharing | 2 ms | 5.18 ms | 9.27 ms |
=> bench: fix running the crypto bench + add back sled to compare sled with sqlite

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Useful for EX-Android until UniFFI gets GC integration for Kotlin.
=> ffi: Add MediaSource::{from_json, to_json}

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, testing/sliding-sync-integration-test/src/lib.rs
Replaces usage of `UInt` in the internal code and public interfaces with `RangeInclusive`, which clarify that the end value is included in the range, and is generally more idiomatic in Rust.
I've gone ahead and also replaced the one other use of `UInt` for `timeline_limit` with a `u32`. Requesting 2**31-1 last events should be enough for anyone!
Fixes #1739.
=> sliding sync: Use `RangeInclusive<u32>` instead of raw start/end `UInt` values

crates/matrix-sdk/src/room/timeline/builder.rs, crates/matrix-sdk/src/room/timeline/inner.rs, crates/matrix-sdk/src/room/timeline/mod.rs
I've added a few tracing spans here and there so we can know how long it took to build the `TimelineBuilder`: one on the `build()` method itself, and two extras on functions called in `build()` and that I suspect to be the slowest there.
=> chore: add tracing spans for Timeline builder code suspected slow

crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync/room.rs
- Fix the options tracing span field for the high-level timeline pagination (looks like it was never working on `main` since it was using a wrong name that was used in a previous iteration)
- Add a tracing span that includes options for individual pagination requests (which can also be triggered from outside the timeline)
=> Improve logs for pagination

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/requests.rs
Currently, the `body` of a `SignatureUploadRequest` includes a spurious `signed_keys: {...}` property in which the actual content is wrapped.
I don't really understand how the `request` macro is supposed to work, but via a combination of cargo-culting and randomly perturbing the code I have made something that emits the right value.
=> crypto-js: fix body of `SignatureUploadRequest`

crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
GroupSessions#get_or_load() was changed to catch CryptoStore errors and return None, but the `fn` was still returning a Result
Signed-off-by:
=> refactor(crypto): get_or_load never returns crypto error

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1926, https://github.com/matrix-org/matrix-rust-sdk/pull/1936.
`SlidingSync::add_list` now sends `SlidingSyncInternalMessage::ContinueSyncLoop` once the list is added.
To make this work correctly, `add_list`, along with `subscribe_to_room` and `unsubscribe_to_room` become async.
New tests are added to ensure Tokio doesn't emit a panic.
On the FFI side:
* `SlidingSync::add_list` now returns an `Arc<TaskHandle>`
* `SlidingSync::subscribe` is renamed to `::subscribe_to_room`, and returns an `Arc<TaskHandle>`
* `SlidingSync::unsubscribe` is renamed to `::unsubscribe_to_room`, and returns an `Arc<TaskHandle>`
* `SlidingSyncRoom::subscribe_and_add_timeline_listener` is replaced by new methods: `SlidingSyncRoom::subscribe_to_room` and …
=> feat(sdk): `SlidingSync::add_list` has an immediate effect

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Address https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
`SlidingSyncMode` was previously declared as:
```rust
enum SlidingSyncMode {
Selective,
Paging,
Growing,
}
```
Now, the new declaration is:
```rust
enum SlidingSyncMode {
Selective,
Paging {
batch_size: u32,
maximum_number_of_rooms_to_fetch: Option<u32>,
},
Growing {
batch_size: u32,
maximum_number_of_rooms_to_fetch: Option<u32>,
}
}
```
First off, it helps to remove the `full_sync_batch_size` and
`full_sync_maximum_number_of_rooms_to_fetch` methods and fields from
`SlidingSyncListBuilder`. It was containing default values in case of.
That was useless and needed to be fixed. Also, calling a `full_sync_*`
method with the `Selective` mode had no effect, which could disturb
the user. Well, now everything is clean on that …
=> feat(sdk): `SlidingSyncMode` has richer variants

crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
The comment and the check in the code were contradicting each other; the comment was wrong, and the code was right, so there's that.
=> chore(comment): fix the comment for `Error::CannotModifyRanges`

crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
The `SlidingSyncListInner::timeline_limit` and `::ranges` fields were observable (behind `eyeball::Observable`). It was actually useless as those fields were never exposed to the public API, thus it was impossible to subscribe to them.
This patch cleans up that. `timeline_limit` and `ranges` are no longer observable.
=> fix(sdk): `SlidingSyncListInner::timeline_limit` and `ranges` are no longer observable

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
- Increase the size of the internal message receiver buffer, in case it's full before it can handle all the things. That's a blind attempt to fix a deadlock we've observed in ElementX iOS, when the app goes in the background.
- Also add log when exiting the stream loop, just to make sure it's properly exiting.
=> Bump sliding sync receiver size

crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Address #1911.
Changing the sync-mode of a list on-the-fly is necessary to optimise the
new `RoomList` API. For example, we can start with a list in a selective
mode, a range of `0..=50` and a `timeline_limit=0` to fetch the
beginning of the room list, and then _change_ the sync-mode to growing
to continue to sync the room list in the background.
Today, this is done with 2 lists and a merge of the lists, but
(i) this is error-prone, (ii) this is not optimal. Thanks to
`SlidingSyncList::set_sync_mode`, merging lists is no more necessary,
thus removing a class of bugs in client's code.
This patch then implements `SlidingSyncList::set_sync_mode` and adds
the necessary test. `set_sync_mode` will skip over the current iteration
of the sync loop automatically, but it won't reset the list.
=> feat(sdk): Implement `SlidingSyncList::set_sync_mode`

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/backup_recovery_key.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/backups/keys/backup.rs, crates/matrix-sdk-crypto/src/backups/keys/compat.rs, crates/matrix-sdk-crypto/src/backups/keys/mod.rs, crates/matrix-sdk-crypto/src/backups/keys/recovery.rs, crates/matrix-sdk-crypto/src/backups/mod.rs
This patch removes our dependency to libolm completely. This should allow WASM targets to use the backups_v1 feature of the matrix-sdk-crypto crate as well.
=> Replace the libolm backup encryption code with a native Rust version

bindings/matrix-sdk-ffi/src/room.rs
Exposed `set_name` function for changing the name of a room
Note: I didn't test this change because I fail to build the rust sdk...
=> feat(bindings): exposed `set_name` in `Room`

bindings/matrix-sdk-crypto-ffi/src/verification.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/encryption/verification/mod.rs, crates/matrix-sdk/src/encryption/verification/requests.rs, examples/emoji_verification/src/main.rs
The meat of this PR is the first patch. While the first patch is not particularly pretty, it works and makes the public API much nicer.
The second patch exposes things in the main crate, while the third one just updates our emoji verification example.
This PR closes: https://github.com/matrix-org/matrix-rust-sdk/issues/1894
=> Add a state for the VerificationRequest for when a request transitions

bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk/Cargo.toml
Not completely sure why disabling this didn't work the first time. The feature is now disabled by default in the matrix-sdk-crypto crate.
=> Disable automatic-key-forwarding for the matrix-sdk-ffi bindings

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
In case it's not obvious to drop the `Stream` returned by
`SlidingSync::sync` immediately to “stop” the sync-loop, one can use the
new `stop_sync` method to achieve the same result.
This patch also renames `SlidingSync::stream` to `::sync`.
This patch takes the liberty to log when an internal message is received, and
when internal messages are sent.
This patch also restores the internal channel size to 8, as it just postpones
the problem, making it harder to debug, without fixing anything.
Finally, this patch adds the `SlidingSync::stop_sync` method at the FFI layer.
=> feat(sdk): Implement `SlidingSync::stop_sync`

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
The `Client::sliding_sync` method was declared as async. However, it's not necessary as everything happening here is sync.
=> fix(sdk): `Client::sliding_sync` doesn't need to be `async`

Cargo.lock, bindings/matrix-sdk-crypto-ffi/Cargo.toml, bindings/matrix-sdk-crypto-js/Cargo.toml, bindings/matrix-sdk-crypto-nodejs/Cargo.toml, crates/matrix-sdk-base/Cargo.toml, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/session.rs, crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk-crypto/src/types/events/room/encrypted.rs, crates/matrix-sdk/Cargo.toml
This closes: https://github.com/matrix-org/matrix-rust-sdk/issues/1266
The first patch cleans some logs up, secondly we add optional support to send
message IDs for our `m.room.encrypted` to-device events, and finally we log the
message ID when we encrypt room keys.
=> Message ID support: The sending side

bindings/matrix-sdk-ffi/src/sliding_sync.rs
This reverts commit 2660e7bcf1661f6f26f686ba45af03701dab52f9.
=> Revert "bindings: Use native async support for latest_room_message"

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This is extracted from #1955: this removes unused public APIs (at least unused by ElementX iOS and Android), and replaces some internal methods with other existing functions that do more or less the same thing.
=> sliding sync: reduce `Range` surface API

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
This gets rid of many Range API methods that were unused, and reworks how ranges work internally. Also, this removes the weird duplication of `sync_mode` and `ranges` in both the request generator and the list. Now, the data is only stored once in the request generator.
Overall, this reduces the whole API surface, and gets rid of entire category of bugs (settings ranges for non-selective lists).
```rust
sliding_sync
.add_list(
SlidingSyncList::builder("bar")
.sync_mode(SlidingSyncMode::Selective)
.set_range(50..=60),
)
```
```rust
sliding_sync
.add_list(
SlidingSyncList::builder("bar")
.sync_mode(SlidingSyncMode::new_selective().add_range(50..=60)),
)
```
There's no more a `set_range` method in the FFI; we could actually add it back, as an helper, if needs be.
```rust …
```
=> sliding sync: Rejigger the range API

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs
Add builder patterns for the `Growing` and `Paging` sync modes too. As they're quite common, I've used the same builder struct with a sub enum for both.
=> feat(sdk): use the builder pattern for the other sliding sync mode too

crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
I've made `SlidingSync::ExtensionsConfig` read-only in a previous PR, but forgot to remove the mutex around it, which isn't needed anymore. Also moved the default-ing behavior of `ExtensionsConfig` closer to where configuration happens (in the builder's `build` method) instead of deep within the code, elsewhere.
=> chore(sliding sync): remove useless mutex around ExtensionsConfig

bindings/matrix-sdk-ffi/src/sliding_sync.rs
This adds a new method `set_sync_mode` on the FFI object `SlidingSyncList`, as @stefanceriu noticed it wasn't exposed and so one couldn't (notably) update ranges anymore, because of that.
=> feat(ffi): expose `set_sync_mode` on the sliding sync list

crates/matrix-sdk/src/sliding_sync/mod.rs
Everything is in the title :-).
=> test(sdk): Ensure `SlidingSync` starts after it has been stopped manually

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/sliding_sync.rs
As discussed many times, we are over-using `Deref`. I found two that were very easy to remove.
=> ffi: Remove unnecessary Deref implementations

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Something weird is happening with ElementX iOS when the app moves from foreground to background and vice versa. When `SlidingSync::stop_sync` is called, the internal message `SyncLoopStop` has time to be sent in the internal channel, but iOS decides to suspend the code before the sync-loop processes it. When ElementX decides to start the sync-loop again, it immediately processes the `SyncLoopStop` message, and… stops the sync-loop.
~~This patch ensures that `SlidingSync::sync` drains the internal channel before starting the sync-loop for real. `tokio::sync::mpsc::Receiver` type has no `drain` method, so this patch implements its own logic by calling `try_recv` in a loop, until it returns `Err(TryRecvError::Empty)`.~~
This patch changes the internal channel from a MPSC (Multiple Producer, …
=> feat(sdk): Ensure `SlidingSync::sync` “drains” its internal channel

crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
This patch uses `FutureExt::now_or_never` so that we don't wait on the future to be resolved to get a result. If we have a bug in our code and the test expects a value, the test will hang forever, which is not a desired behavior. With `now_or_never`, this situation cannot happen.
=> test(ui): Use `FutureExt::now_or_never` instead of `.await`

crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sled/src/state_store/migrations.rs, crates/matrix-sdk-sled/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/tests/integration/room/common.rs, testing/matrix-sdk-integration-testing/src/tests/redaction.rs
Previously it was not possible to get state events for invited rooms.
This is a pre-requisite for #1979, to be able to use `get_state_events` in `get_members`.
Should we deprecate `StateStore::get_member_event`? It doesn't do anything more than `StateStoreExt::get_state_event_static_for_key` now.
=> sdk: Allow to get stripped state events from the store

Cargo.lock, crates/matrix-sdk-crypto/src/backups/keys/recovery.rs
After updating my rust toolchains this morning, I stumbled upon this issue with the nightly toolchain: https://github.com/sval-rs/value-bag/issues/64. I ran `cargo update` to fix the compilation.
The second commit is a new error raised by clippy nightly.
=> chore: Update Cargo dependencies

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/list/builder.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Moves the `bump_event_types` from the main request to the list sub-request; ditto for all the builders, etc., according to the change in https://github.com/matrix-org/sliding-sync/pull/129.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2001.
=> sliding sync: move the `bump_event_types` to be per-list

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/client.rs, crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
This replaces the `storage_key` public API with another one `enable_caching` that doesn't take a string argument. Instead, sliding sync constructors are expected to receive a `loop_id` argument, that will be used to 1. be part of the storage key for this sliding sync instance, 2. be used as the `conn_id` (connection id) in the request to the proxy (paving the way for #1928).
The storage key is also inferred from the user id, such that a single app may be used for multiple users.
Fixes #2007.
=> sliding sync: infer the storage key from the loop id and user id

bindings/matrix-sdk-ffi/src/error.rs
> To print causes as well using anyhow’s default formatting of causes, use the alternate selector “{:#}”.
https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations
=> ffi: Include causes when stringifying anyhow::Error

crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/store/ambiguity_map.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk/src/lib.rs, testing/matrix-sdk-integration-testing/src/tests/repeated_join.rs
In the store implementations, it is a wrapper around `StateStore::get_state_event` since #1991.
We could keep it for convenience instead but it should probably be moved to `StateStoreExt` in that case. However given that these are low-level traits it doesn't seem necessary.
=> base: Move `StateStore::get_member_event` to `StateStoreExt` 

bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/src/media.rs
By default, `get_media_file` will attempt to use a default directory for temporary files and directories. Unfortunately, there might not be such a thing on some older Android devices, which use per-application directories.
For this specific case, an optional temporary directory parameter is added to the `get_media_file` parameters, so one can provide their own temporary directory path.
This new parameter is expected to be set at least on Android; other platforms should work just fine without it.
=> feat(sdk): add an optional temporary directory to `get_media_file`

crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
Users of the RoomList API have previously used `with_common_extensions` on the sliding sync builders to enable three extensions:
- `account_data`
- `e2ee`
- `to_device`
Considering that the last two will be handled by the `NotificationApi` in the future, they may still want to enable the `account_data` extension. There are two ways to do that:
- expose setters for each extension,
- or enable it for them
Since RoomList has an opiniated design, I think it should enable it by default, on behalf of the users; that's up to discussion.
The second commit replaces the `add_cached_list` with `add_list`, as I am 95% sure we will run into the slow reloading perf issue that we've ran into, in the past, if we keep it and put it in production before the perf issue with reloading from the cache has been …
=> `RoomList` API: enable `account_data` extension by default

crates/matrix-sdk/src/sliding_sync/builder.rs
Enable read receipts by default in the common extensions; that's the only `*extension*` method used by ElementX clients, at the very least. I expect that the importance of this will be lowered when we have the `RoomList`/`NotificationApi` in place, but in the meanwhile it's useful to have.
=> sliding sync: enable read-receipts in the common extensions

Cargo.lock, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
This PR iterates over #2024 by first, disabling Sliding Sync caching in `RoomList`. Second, it makes `Room::timeline` and `Room::sneaky_timeline` lazy by using `async-once-cell`.
=> feat(ui): Disable caching and make `Timeline`s lazy

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/inner.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
Previously a pretty obvious hole in the timeline API: When sending failed, there was no way to deal with the failed local echo. This adds one way to do that, we should also add the ability to cancel a failed local echo (in a separate PR).
=> Add Timeline::retry_send

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
Using `homeserver` to designate the sliding sync proxy has been a bit confusing in my experience, since I thought that was a real, alternate home server that was used, while it's only really used for the sliding sync request. This PR attempts to improve this by just renaming the field in a few places.
=> chore: rename `homeserver` to `sliding_sync_proxy` in sliding sync

crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/timeline/inner.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/edit.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/timeline/tests/invalid.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs, crates/matrix-sdk-ui/src/timeline/tests/virt.rs
- A little more concise and thus easier to read
- The stream not yielding an item immediately will cause failure, instead of making the test hang
=> Clean up timeline unit tests

README.md, bindings/matrix-sdk-ffi/src/lib.rs
1.70 is now the minimum required version to compile the workspace
=> docs: updated readme - rust version

crates/matrix-sdk-base/src/sliding_sync.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1771
I suggest reviewing commit by commit. Includes a refactor to extract the relevant code into a (slightly) shorter method.
In the previous code, if we were dealing with an invited room we never called `self.handle_state` to process the `required_state` that was included with this room. Now, we do.
The code could still do with some refactoring, which I will do in a later PR.
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/2032
=> In sliding sync, handle required state in invited rooms as well as joined

crates/matrix-sdk-base/src/sliding_sync.rs
Supply JSON similar to what is found in MSC3575 for `invite_state`
Added some comments based on my understanding of MSC3575. Previously we
had a FIXME about how we were setting the room state to invite or join
based on the presence or absence of the invite_state property. I think
this behaviour is correct, so I added some comments explaining why.
The functional change here is to note that we call
store.get_or_create_stripped_room to find/create the stripped room, and
this actually deletes any room of this ID that is in the store, so our
later call to store.get_room would always fall back to getting the
stripped room, which we already have, so there was no need to do the
get_room call at all.
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/2039
=> Tidy sliding sync processing code

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml
Just noticed that there's a new release, and seems like this reduces our dependencies a bit :)
=> Upgrade opentelemetry dependencies

crates/matrix-sdk-base/src/sliding_sync.rs
Extract a couple of functions to shorten the `process_sliding_sync_room` method
Applies on top of https://github.com/matrix-org/matrix-rust-sdk/pull/2043
=> Extract functions to shorten the `process_sliding_sync_room` method

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/requests.rs, crates/matrix-sdk-crypto/src/verification/sas/inner_sas.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
Closes: https://github.com/matrix-org/matrix-rust-sdk/issues/2060.
=> Use the short auth strings from the start content when accepting a verification

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/src/room_list/room.rs, crates/matrix-sdk-ui/src/room_list/state.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
Address https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
This PR must be reviewed commit by commit.
=> feat(ui+ffi): Add various features to `RoomList`

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Don't expect the `SlidingSyncBuilder` to retrieve the proxy URL from the Client, but do it for them automatically. This removes a bit of duplication, as it's done in both the FFI and the Room API (and soon, the Notification API too). And it actually makes reality match with the comment (I wrote, but at the time misunderstood) of `SlidingSyncBuilder::sliding_sync_proxy`.
=> sliding sync: always fall back to the auto-discovered proxy URL, if any

bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This closes: https://github.com/matrix-org/matrix-rust-sdk/issues/2045.
=> Properly support the hkdf-hmac-sha256.v2 MAC method for the SAS verification

benchmarks/benches/store_bench.rs, crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/lib.rs, crates/matrix-sdk-base/src/rooms/mod.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/migrations.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/migrations/state_store/002_a_create_new_room_info.sql, crates/matrix-sdk-sqlite/migrations/state_store/002_b_replace_room_info.sql, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/error.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-sqlite/src/utils.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/tests/integration/room/common.rs
Since they use the same type, it is not necessary to separate them. It is not even visible on public APIs that they are separated.
Based on #2038.
=> Do not separate stripped and non-stripped room info 

crates/matrix-sdk-base/Changelog.md, crates/matrix-sdk-base/src/deserialized_responses.rs, crates/matrix-sdk-base/src/rooms/members.rs, crates/matrix-sdk-base/src/rooms/normal.rs, crates/matrix-sdk-base/src/store/integration_tests.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-base/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/state_store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs, crates/matrix-sdk-sqlite/src/utils.rs, crates/matrix-sdk/src/room/common.rs
Each commit can be viewed separately. The first commits add the methods to retrieve events in batch to the `StateStore` trait and the last one uses the new methods for `Room::get_members`.
Should fix part of #1979. What is left is to be able to paginate to not request all the results at once.
=> base: Make store requests in batch for `Room::get_members`

bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/src/room_list/room.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
Address #1911.
This PR does 4 things:
1. It implements the `matrix_sdk_ui::room_list::Room::subscribe` and `::unsubscribe` methods, with the appropriate tests. The FFI bindings are implemented too.
2. It implements `matrix_sdk_ui::room_list::Room::id()` as a shortcut to `room.inner_room().room_id()`. It's especially useful for FFI users where creating such a “full room” (`inner_room`) may be expensive.
3. It removes `matrix_sdk_ffi::RoomListItem::timeline()` in favor of `matrix_sdk_ffi::Room::add_timeline_listener()`. It also updates the latter to return a `RoomTimelineListenerResult { items: Vec<Arc<TimelineEvent>>, items_stream: TaskHandle }`, so that now, it's finally possible to stop a timeline listener stream. Previously, it was impossible.
4. It implements …
=> feat(ui): Implement room subscriptions in `RoomList` + notification counts

bindings/matrix-sdk-ffi/src/timeline.rs
With this, the `MessageType` contained in `m.room.message` timeline items can be converted back to `RoomMessageEventContent`, which allows re-sending (forwarding) that message.
=> ffi: Add message_event_content_new

crates/matrix-sdk-base/src/store/mod.rs, crates/matrix-sdk-sqlite/src/state_store.rs
=> base: Remove the session field from StateChanges

crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/sticky_parameters.rs
The `txn_id` (transaction id) was always being generated, and this confused the sliding sync proxy server. As per the spec, it's useful to [include it only when the request parameters have changed](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#sticky-request-parameters). As a matter of fact, we were slightly deviating from the spec by always generating one, and even then it would cost us bandwidth we could avoid.
With this patch, the transaction id is now lazily generated by any `StickyManager` that would make use of it, and included in the request only if it was generated and used by any set of sticky parameters.
=> sliding sync: lazily generate and include the transaction id, only if it's useful

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
Address #1911.
This patch implements `RoomList::apply_input`. Usage example:
```rust
room_list.apply_input(RoomListInput::Viewport { ranges: vec![RoomListRange { start: 10, end_inclusive: 20 }]}).await?;
```
=> feat(fii): Implement `RoomList::apply_input`

crates/matrix-sdk-ui/src/room_list/state.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
The MSC3575 says that if no `ranges` for a list is provided, it defaults to all rooms. We don't want that! This patch sets the default value to `0..=19` for the `visible_rooms`.
=> fix(ui): Set `visible_rooms` with a default range

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/src/verification.rs, bindings/matrix-sdk-crypto-js/tests/device.test.js
... so that applications know when something happens.
=> crypto-js: Add `register_changes_callback` methods to the verification classes

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/src/room_list/state.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs
Address https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
This patch creates a new `invites` list. This list is created once `RoomList` transitions from `FirstRooms` to `AllRooms`.
It's possible to subscribe to the invites with `RoomList::invites`.
=> feat(ffi): Implement `RoomList::invites`

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/common.rs, crates/matrix-sdk/src/room/joined.rs
`OlmMachine` was a `OnceCell`, which is not a good fit for our current plan to allow resetting the `OlmMachine` in the #1928. I made it an `Arc<tokio::RwLock>`, based on the assumption that it should be mostly read, and rarely written to. Fortunately, most callers are already async, so this change went relatively smoothly.
=> feat: make `OlmMachine` resettable

Cargo.lock, crates/matrix-sdk-crypto/src/store/error.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/locks.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs, labs/sqlite-lock/Cargo.toml, labs/sqlite-lock/src/main.rs
This implements a value-based lock in the crypto stores. The intent is to use that for multiple processes to be able to make writes into the store concurrently, while still cooperating on who does them. In particular, we need this for #1928, since we may have up to two different processes trying to write into the crypto store at the same time.
The idea is to introduce two new methods touching **custom values** in the crypto store:
- one to atomically insert a value, only if it was missing (so, not following the semantics of `upsert` used in the `set_custom_value`) 
- one to atomically remove a custom value
Those two operations match the semantics we want:
- take the lock only if it ain't taken already == insert an entry only if it was missing
- release the lock = remove the entry
By …
=> Add a value-based lock in the `CryptoStore`s

crates/matrix-sdk/src/client/mod.rs
Fix a minor typo (mismatched backticks) in documentation.
Signed-off-by:
=> Add a missing backtick in sync_with_result_callback() documentation.

crates/matrix-sdk-crypto/src/error.rs
Everything is in the title :-).
=> doc(crypto): Fix a typo

crates/matrix-sdk-ui/tests/integration/notification.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
`SlidingSync::sync` had a legacy behaviour when a `M_UNKNOWN_POS`
error was received from the server: It was resetting `pos` and sticky
parameters before re-running a sync-loop iteration, hoping to get a
valid response from the server after that. This retrying
mechanism was running up to 3 times in row (represented by the
`MAXIMUM_SLIDING_SYNC_SESSION_EXPIRATION` constant) before stopping the
`sync` for real.
While it seemed a good idea, it actually brings numerous problems:
1. Each iteration in the sync-loop generates a new request, thus making
the `ranges` of the requests to move forwards. For `SlidingSyncList`
that are in `Selective` sync-mode, there is no problem, but for
`Growing` or `Paging` sync-modes, the `ranges` increased. Thus,
when a `SlidingSync` session expires, instead of …
=> fix(sdk): Remove the Sliding Sync retry mechanism on `M_UNKNOWN_POS`

crates/matrix-sdk/src/room/mod.rs
It's the type returned from Invited::invite_details() but it is not available publicly.
=> sdk: Export Invite

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client.rs, crates/matrix-sdk/CHANGELOG.md, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs
It has an `account` field besides the `issuer` field.
Also store it as immutable, the data used for authentication will be stored in another variable.
=> sdk: Keep all the discovered `AuthenticationServerInfo`

crates/matrix-sdk-ui/src/room_list/mod.rs
Just another tiny piece of cleanup :)
=> ui: Use method syntax for shared::Observable methods

crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This PR prepares the implementation of https://github.com/matrix-org/matrix-rust-sdk/issues/1959 
In order expose the notification settings later, a new `Rules` struct has been added in a new `mod notification_settings`.
This `Rules` struct encapsulates a `Ruleset` for getting, adding and deleting rules.
The `Rules` struct only updates its local `Ruleset`, and some methods return a vector of `Command` describing which API calls need to be made in order to update the owner's account push rules.
The following MSC were considered:
[MSC3987: Push actions clean-up](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3987-push-actions-clean-up.md?rgh-link-date=2023-05-24T12%3A24%3A57Z#msc3987-push-actions-clean-up)
[MSC3952: Intentional …
=> feat(sdk): Add a Rules utility struct to manipulate a Ruleset.

bindings/matrix-sdk-ffi/src/timeline.rs
This PR adds the support for location events inside a `m.room.message`. 
Aka: `"msgtype": "m.location"`
=> Add location message type to UniFFI

crates/matrix-sdk-ui/src/timeline/builder.rs
This patch updates `tracing::instrument` on `TimelineBuilder::build` so that we can detect the circumstance of slow cases.
=> feat(ui): `TimelineBuilder::build` logs more data

bindings/matrix-sdk-crypto-ffi/src/device.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-js/src/device.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/device.rs, crates/matrix-sdk-crypto/src/olm/account.rs
Added a new `first_time_seen_ts` fn to `Device`. This is used by clients to show "New login, was this you" or "You have unverified logins" banners.
Simply added as a ~~SystemTime~~ u64 wrapper in the structs, exposed in ffi binding as an `u64` seconds since epoch.
Value is populated with serde default for migration of existing persisted data.
Signed-off-by:
=> Add first_time_seen timestamp to devices

bindings/matrix-sdk-crypto-js/src/device.rs, crates/matrix-sdk-crypto/src/identities/device.rs
Follow up on #2055 updated a bad copy paste of comment in js binding 
Signed-off-by:
=> Fix js binding bad comment

Cargo.toml
… and enable incremental compilation for it.
Replaces #2072.
@stefanceriu, @Hywan: I think this should fix the iOS crashes if I understood the test results, and the profile names / descriptions still make sense this way.
=> Update reldbg profile to optimize our own packages too

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification.rs
The `NotificationItem` will be returned as an `Option` of value `None` when no action that `should_notify` is found
=> feat(bindings): `get_notification_item` filters out notifications given the push context

bindings/matrix-sdk-crypto-ffi/src/lib.rs
Currently when doing migration from EA, if a userId is malformed the whole migration will fail (and lock users out).
Notice that the validation has been relaxed in [ruma](https://github.com/ruma/ruma/commit/6ad007995c122561f8de7135195273ed91a9737c). 
Anyhow I think it's good to be more lax on the migration process, and it's also consistent as the `update_tracked_users()` function is already ignoring malformed userIds silently
=> bindings: Ignore silently malformed userId in migration of tracked users

bindings/matrix-sdk-ffi/src/timeline.rs
This PR exposes the reaction sender userIds in `matrix-sdk-ffi`. This allows clients highlight a users own reactions and also provide detail on who else added a particular reaction.
=> ffi: Expose the senders of reactions

bindings/matrix-sdk-ffi/src/room.rs
This PR adds the `send_location` API to UniFFI
=> Add send_location api to FFI

crates/matrix-sdk-ui/tests/integration/room_list.rs
Eh, removing `sleep` from the tests is always a pleasure right?
=> test(ui): Replace `sleep` by `yield_now`

bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/notification.rs
this is a workaround until we find a way to fix the issue described here:
https://github.com/vector-im/element-x-ios/issues/1155
=> feat(binding): boolean to decide whether filter by push rules or not

crates/matrix-sdk-ui/src/room_list/room.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/queue.rs, crates/matrix-sdk-ui/src/timeline/sliding_sync_ext.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
Currently, we get way too many logs from the message-sending queue because we create it for all the "sneaky" timelines in the room list API. This fixes that by adding an internal read-only mode where we don't spawn the message-sending task (also more efficient), and using it for those "sneaky" timelines.
=> ui: Improve logging for message-sending queue

crates/matrix-sdk/src/sliding_sync/list/builder.rs
Address #1911.
This patch changes the capacity of the internal buffer of `ObservableVector` for `SlidingSyncList::room_list` from 16 to 4096. With an increased capacity, we reduce the probability to send a `VectorDiff::Reset` to subscribers. `Reset` are happening quite often for apps using `matrix-sdk`, and it impacts their performance. This patch tries to improve this situation. This `room_list` contains `RoomListEntry`, which is quite cheap in terms of memory, compared to the impact of sending `Reset`s too often. That's a tradeoff.
=> fix(sdk): Change `SlidingSyncList::room_list`'s capacity

crates/matrix-sdk-common/src/lib.rs, crates/matrix-sdk-common/src/ring_buffer.rs
This patch proposes a very simple `RingBuffer` implementation based on `std::collections::VecDeque`.
=> feat(common): Propose a simple `RingBuffer` implementation

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/mod.rs
Not sure what to do about this now being an async method and having the stack
size increased again.
=> Emit room keys after they have been persisted, not before.

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/queue.rs
… such that it gets the timeline builder's tracing span.
=> ui: Move message-sending loop start log event

crates/matrix-sdk/src/sliding_sync/list/mod.rs
Address #1911.
Sometimes, ElementX sees a duplicated ID in the `RoomList` entries. How is it possible? Well, it's impossible except if the server sends unexpected sync operations:
* If the server sends an `INSERT` for a room ID has already been inserted,
* If the server tries to move a room, but instead of sending `DELETE` + `INSERT` (because there is no `MOVE` operation), it sends `INSERT` + `DELETE` (then, it's similar to the previous use case).
This patch logs the `SyncOp`s we receive from the server, so that we can dig into this deeper and confirm where the problem comes from.
=> chore(sdk): Log the `SyncOp`s

crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/src/room_list/room.rs
That avoids recreating a timeline object every time a user calls `RoomListService::room()` with the same room id, so that should speed up operations like fetching the latest event for rooms we've already entered before.
Note: I haven't added explicit tests for the caching, because there are already some tests which make use of the same room id, so they would hit the caching paths.
Part of https://github.com/matrix-org/matrix-rust-sdk/issues/2161
=> feat: Cache the `RoomListService`'s rooms

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/machine.rs
We previously did something similar for `getUserDevices` in #1790. Turns out it's useful for `getIdentity` too.
=> crypto-js: wait for device updates in `getIdentity`

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/requests.rs
According to the [spec](https://spec.matrix.org/v1.7/client-server-api/#device-verification), when a device receives a verification request and wants to refuse it, it should send the `m.key.verification.cancel` to the originating device, rather than broadcasting it:
> When Bob accepts or declines the verification on one of his devices (sending either an `m.key.verification.ready` or `m.key.verification.cancel` event), **Alice** will send an` m.key.verification.cancel` event to Bob’s other devices...
=> When refusing a verification, send cancel to the originating device

bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs
Address #1911.
Imagine the room list has the viewport set to the range `0..=19`. The
user scrolls quickly to `50..=69` to see something below and immediately
scrolls back to its initial position, without stopping the scroll
at any moment in between. The app using this API might update the
viewport from `0..=19` to… `0..=19`. Updating the viewport, updates the
`visible_rooms` sliding sync list. Since a list is modified, the current
sync-loop iteration is skipped over and a new one restarts, i.e. the
current in-flight request is cancelled… for nothing.
This patch prevents this situation. The current viewport ranges is
stored in `RoomListService`. `RoomListService::apply_input` used to
return `Result<(), Error>`, now it returns `Result<InputResult, Error>`.
The `InputResult` enum is a new …
=>  feat(ui): Do not update the viewport of the room list if it hasn't changed

crates/matrix-sdk/src/sliding_sync/list/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This patch removes an old log and adds a better one with more context.
=> chore(sdk): Log SlidingSync list updates

crates/matrix-sdk-crypto/src/store/locks.rs
This adds a few unit tests for the `CryptoStoreLock`. I was sure I wrote this before, but apparently it hasn't been the case :upside_down_face:
=> tests: add unit tests for the `CryptoStoreLock`

crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/locks.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/migrations/crypto_store/007_lock_leases.sql, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/room/joined/mod.rs, testing/matrix-sdk-test/src/lib.rs
This implements a new time lease based lock for the `CryptoStore`, that doesn't require explicit unlocking, so that's more robust in the context of #1928, where any process may die because the device is running out of battery, or unexpected flows cause a lock to not be released properly in one or the other process.
```
//! This is a per-process lock that may be used only for very specific use
//! cases, where multiple processes might concurrently write to the same
//! database at the same time; this would invalidate crypto store caches, so
//! that should be done mindfully. Such a lock can be acquired multiple times by
//! the same process, and it remains active as long as there's at least one user
//! in a given process.
//!
//! The lock is implemented using time-based leases to values …
```
=> feat: implement time lease based locks for the `CryptoStore`

bindings/matrix-sdk-ffi/src/room_list.rs
Address #1911.
Calling `RoomListItem::full_room` creates its associated `Timeline`.
ElementX calls `full_room` to get the `is_direct`, `avatar_url` and `canonical_alias` values for _all_ rooms in the room list. Instead of doing so, let's add those methods directly in `RoomListItem` so that the `Timeline` isn't created for _all_ rooms.
=> feat(ffi): Add methods on `RoomListItem` so that `full_room` isn't necessary

bindings/matrix-sdk-ffi/src/sliding_sync.rs, crates/matrix-sdk-ui/src/room_list/mod.rs, crates/matrix-sdk/src/sliding_sync/README.md, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/sliding-sync-integration-test/src/lib.rs
Common extensions are confusing, and they've included `e2ee` and `to-device` by default. This is not a sane default anymore, now that there's the concept of `EncryptionSync`: it's either we have the encryption sync that enables e2ee and to-device + a room list sync that doesn't, OR we have a single room list that has both.
Room List was misconfigured to always use `e2ee` and `to-device`, which was incorrect when it's running with the `EncryptionSync` in the background. This is now removed, and properly tested that we get the extensions only if we explicitly ask for them.
=> feat: Get rid of "common extensions"

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/verification/sas/helpers.rs
For verification-by-emoji, the spec uses the word "Aeroplane" rather than
"Airplane". Element-web expects us to use the specced words (and will otherwise
complain about the lack of i18n data).
It seems like following the spec will help maintain consistency.
=> Airplane -> Aeroplane

bindings/matrix-sdk-ffi/src/encryption_sync.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/store/locks.rs, crates/matrix-sdk-sqlite/Cargo.toml, crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk/Cargo.toml, crates/matrix-sdk/src/encryption/mod.rs, xtask/src/ci.rs
This implements a generation counter for the CryptoStore lock, aiming at solving the following problem. Consider ElementX iOS:
- the main app goes in the background, releasing the crypto store lock
- a push notification shows up, NSE process is created, acquires the crypto store lock, does its thing, then releases lock
- the main app goes back in the foreground, acquires the crypto store lock
Then it's possible that the crypto store caches in the main app are now _stale_, but the main app won't realize, because trying to acquire the lock may succeed on the first attempt.
The solution is to introduce a "generation" counter, maintained in both a process embedding the SDK, and the store. It is updated any time we acquire a lock and we observed a different value in the store.
Now observe what …
=> feat: implement a generation counter for the CryptoStore lock

bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/http_client/native.rs
- Expose network proxy setting over FFI
- Expose insecure SSL setting over FFI
Enables apps to configure a network proxy for debugging.
=> ffi: Expose proxy and insecure SSL settings

crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
Address #1911.
This patch configures the same `bump_event_types` for the `visible_rooms` list than for the `all_rooms` list, so that we may be sure that the sorting/ordering is the same between the two lists.
=> fix(ui): Add `bump_event_types` onto `visible_rooms`

.github/workflows/ci.yml, .github/workflows/coverage.yml
There is a bug in Synapse and changing the installer seems to fix the problem.
Trying to apply https://github.com/michaelkaye/setup-matrix-synapse/issues/94#issuecomment-1617680123 :-).
=> test: Change the installer for `setup-matrix-synapse`

crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
This patch ensures that we know exactly what's happening here. Tests are still
valid without any changes in the expected data, but it prevents a
potential breaking.
=> test(ui): Do strict assert comparison in some tests of `RoomList`

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/lib.rs, crates/matrix-sdk/src/notification_settings/command.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rule_commands.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This PR is the second step of the https://github.com/matrix-org/matrix-rust-sdk/issues/1959 implementation. 
It adds a new `notification_settings` crate in matrix-sdk to get and define notification settings for a room and enable/disable push rules.
The `pub` functions will be used by the ffi layer in a future PR.
=> sdk: Allow to update notification settings

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
Similar to the internal field we have already, but accounting for local events and papering over things we probably shouldn't be exposing in their current form.
Requested by @ganfra.
=> Add EventTimelineItem::origin

crates/matrix-sdk-ui/src/timeline/event_handler.rs
No tests because I'm working on replacing these virtual items entirely anyways.
=> ui: Keep loading indicator at the top when processing timeline events

crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
When the sync has been terminated and restarts (e.g. an app is going from the background to the foreground), then the sliding sync is always restarting in growing mode, independently of the previous state of the sync (error or normal termination). This is something the current sliding sync proxy can't handle nicely, because it prioritizes a change in parameters over the delivery of live data. As a matter of fact, to get a quicker response from the proxy, we can try to only restart in growing mode if we ran into an error (and not if we had a normal termination).
=> feat: Only restart growing the allRooms list in case of errors

crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
Address #1911.
`RoomListServer` defines an `all_room` sliding sync list. This list starts in selective sync-mode, then it switches to growing sync-mode. The previous batch size of the growing sync-mode was 50. This patch updates it to 200, because empirically it seems a better value for perceived performance.
This patch also rewrites how `State::next` is written. No change in the code, just comestic.
=> feat(ui): Change `all_rooms` batch size to 200

crates/matrix-sdk/src/sliding_sync/mod.rs
The assign macro is for returning a modified instance of something. Here we don't return, so just using assigns directly makes more sense. Fixes a rust-analyzer warning.
=> sdk: Remove questionable use of assign! macro

crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/list/request_generator.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/utils.rs
Closes #2209.
Fixes #2206.
This patch is a follow-up of #2209. It implements `AbortOnDrop` and `JoinHandleExt` (thanks @jplatte) to ensure that the task sending E2EE requests cannot be detached.
Also, this patch moves the error log (about E2EE requests failure) inside the task.
=> feat: Immediately fail if a sliding sync request failed (follow up of #2209)

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/src/device.rs
Add `verify` method to Device bindings. I used the same implementation than `OwnUserIdentity` 
Signed-off-by:
=> Add `verify` method to `device` bindings

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
For consistency with the UI crate.
An earlier iteration of the PR called it state and I failed to change it everywhere.
=> bindings: Rename subscribe_to_back_pagination_{status => state}

Cargo.lock, crates/matrix-sdk-sqlite/Cargo.toml, crates/matrix-sdk-sqlite/src/error.rs, crates/matrix-sdk-sqlite/src/state_store.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2224.
This patch introduces a new `chunk_large_query_over` function. Imagine there is a _dynamic_ query that runs potentially large number of parameters, so much that the maximum of parameters can be hit. Then, this function is for you. It will execute the query on chunks of parameters.
`chunk_large_query_over` uses `Vec::split_off` to avoid cloning `Key`s as much as possible. It's difficult to use references here because of the async nature of `SqliteObjectExt::prepare`.
This patch updates `get_kv_blobs`, `get_room_infos`, `get_maybe_stripped_state_events_for_keys`, `get_profiles`, `get_user_ids`, and `get_display_names` to use this new function.
This patch finally adds the `repeat_vars` function to replace in a more efficient …
=> fix(sqlite): Prevent reaching the maximum number of parameters in an SQL statement

crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/inner.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/queue.rs, crates/matrix-sdk-ui/src/timeline/tests/encryption.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/to_device.rs, crates/matrix-sdk-ui/src/timeline/traits.rs
… except for unit tests (for convenience).
Took a while to get this right, since we were borrowing a lot of things, which of course doesn't fly when you want to spawn a task.
The two removed `get_mut`s that were changed to locks could potentially be refactored away, by adding the initial events / setting the initial user receipt before wrapping `TimelineInnerState` in `Arc<Mutex<_>>>`.
Replaces #2107.
=> ui: Spawn a background task for decryption retrying

crates/matrix-sdk-crypto/src/store/locks.rs, crates/matrix-sdk/src/encryption/mod.rs
Shouldn't happen in the current code, but better safe than sorry.
=> feat: don't recreate the cross-process lock if it already existed

bindings/matrix-sdk-ffi/src/api.udl, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/notification_settings.rs
This PR is the last step of the https://github.com/matrix-org/matrix-rust-sdk/issues/1959 implementation.
It exposes the `notification_settings` crate to update notification settings for a room, and to define whether certain predefined push rules are enabled.
A `NotificationSettingsDelegate` can be defined to notify the client application each time push rules are updated.
=> ffi: expose the notification settings

bindings/matrix-sdk-ffi/src/room.rs
… right as the subscriber is registered. Previously it wasn't possible to get the current state without waiting for an update. Buf reported by @ganfra.
=> ffi: Send initial back-pagination status to subscriber immediately

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/lib.rs
Part of #2179.
This allows a Frankenstein-monster-mode where we have an in-memory state store but use the actual sqlite crypto store, for the plan mentioned in https://github.com/matrix-org/matrix-rust-sdk/issues/2179#issuecomment-1625176865.
=> feat: make it possible to configure the state store as an in-memory store in FFI

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs
f36a5b8cd71fc2185d55f098b4b62307431db506 introduced `deserialize_events`, moving the deserialization out of `handle_state`. However, the new code in `deserialize_events` used `filter_map`, which caused a deserialization failure to lead to the indices of the serialized and deserialized events to no longer match up.
This was not caught because `iter::zip` also does not require that its arguments have matching lengths, causing the mismatch to cascade for that batch of events, and persist in the store.  An application affected by this form of corruption can, for example, call `room.get_state_events` requesting events of a certain type, and getting back events of a different type.
Fix the bug by using `Option` to preserve the length of `deserialize_events`' return value, and add an assertion …
=> base: Fix deserialization failure leading to database corruption

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/encryption_sync.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/notification.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/notification_client.rs, crates/matrix-sdk-ui/tests/integration/encryption_sync.rs, crates/matrix-sdk-ui/tests/integration/main.rs, crates/matrix-sdk-ui/tests/integration/notification_client.rs
This is extracted from https://github.com/matrix-org/matrix-rust-sdk/pull/2204, and this implements a proper `NotificationClient`, that will take care of handling event decryption for notification events. It's also more logical to have something like this in the UI crate, instead of having custom code at the FFI layer.
For now, the FFI code has been moved, and the encryption sync usage for the notification decryption has been included there. In the future, I'm planning to add more, like properly handling invites, and more goodness to address https://github.com/matrix-org/matrix-rust-sdk/issues/2179.
I'd like to include tests too, but might be nice to do as a follow-up to not inflate this PR too much.
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/1962.
=> feat: add a new `NotificationClient` API :mailbox_with_mail: 

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner.rs, crates/matrix-sdk-ui/src/timeline/item.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/src/timeline/read_receipts.rs, crates/matrix-sdk-ui/src/timeline/tests/basic.rs, crates/matrix-sdk-ui/src/timeline/tests/echo.rs, crates/matrix-sdk-ui/src/timeline/tests/virt.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk-ui/tests/integration/timeline/echo.rs, crates/matrix-sdk-ui/tests/integration/timeline/sliding_sync.rs
Adding an interna unique id that we can use to identify any timeline item. This will allow for clients to understand when a timeline item has actually just changed its internal state/event, or has been just moved around, or if a new one has been inserted or a new one been deleted
=> feat: `internal_id` for TimelineItem

crates/matrix-sdk-ui/src/room_list_service/mod.rs
This will limit the memory used by the cache entries (while it was unbounded before). It's now possible to do this, since we have the `latest_room_event` handy for all the rooms; using the unbounded cache before was papering over the lack of that feature.
We can bikeshed on the number of entries in this cache. It has to be small enough to not blow up memory (and keep the linear search over room id fast, but it's secondary), and high enough that we don't hit the full timeline re-build path that often.
Address a bullet point in https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
=> feat: use a ring buffer for the `RoomListService` cache

bindings/matrix-sdk-crypto-js/tests/device.test.js, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/mod.rs
Previously we would generate one-time keys, if needed, whenever we tried to upload them. This code-path is critically missing a `save_account()` call and we would only persist the account once we uploaded the one-time keys.
This patch changes things up to generate one-time keys whenever we receive new one-time key counts from the sync response. This aligns with the way we generate fallback keys and removes the need to introduce a new place where we persist the `Account`.
It's still possible to re-upload the same one-time keys, in the case where the upload process succeeds on the server side but we fail to receive the response.
=> Generate one-time keys when we receive new one-time key counts

bindings/matrix-sdk-ffi/src/room_list.rs
Fixes `there is no reactor running, must be called from the context of a tokio runtime` errors.
=> ffi: Provide tokio context for async exported method

bindings/matrix-sdk-crypto-js/CHANGELOG.md, bindings/matrix-sdk-crypto-js/package.json, bindings/matrix-sdk-crypto-js/src/machine.rs, bindings/matrix-sdk-crypto-js/tests/helper.js, bindings/matrix-sdk-crypto-js/tests/machine.test.js, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/machine.rs
https://github.com/matrix-org/matrix-rust-sdk/pull/2142 introduced an  unintended change such that `receiveSyncChanges` returned an array of arrays.
Fix it up and release a hasty v0.1.3.
=> Fix `receiveSyncChanges` js bindings, and release 0.1.3

.github/workflows/documentation.yml
I discovered this option when setting up the matrix-rust-sdk-crypto-nodejs repo. Have also converted Ruma to it, and it's working great.
This will decrease the repo size since we'll no longer have to commit the built docs to be able to host them on GitHub pages.
=> ci: Switch to branch-less GitHub pages workflow

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/app.rs, bindings/matrix-sdk-ffi/src/notification_settings.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/session_verification.rs
The app API has caused the dreaded `Cannot start a runtime from within a runtime.` panic from tokio. Let's use async-uniffi instead of `block_on` here. (and in all new code)
=> Use async-uniffi more

crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/mod.rs
It was used when getting the latest message was done through the timeline, which is no longer the case.
=> ui: Remove read-only mode for timeline

.github/workflows/audit.yml
Updates the `actions/checkout` action used in the GitHub Actions workflow to its newest major version.
_(Other workflows in this repository are already using v3, so leaving this one at v1 was probably just a minor lapse.)_
=> ci: Update actions/checkout in GitHub Actions workflows to v3

crates/matrix-sdk-ui/src/encryption_sync/mod.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Following a comment from Jonas in another PR.
=> feat: split the `SlidingSyncBuilder` `with_timeouts` method into two

.github/workflows/coverage.yml
We're getting warnings because this is not a supported parameter (it was when we were using a fork of that action).
=> ci: Remove serverName from setup-matrix-synapse arguments

crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs
Using the crate in Fractal, where we don't use any of the sliding-sync features, we got a few compile-time errors for imports that are not available without the `experimental-sliding-sync` feature enabled.
This makes sure that no warning is reported when running `cargo check` with the features depending on sliding-sync disabled.
=> ui: Fix imports behind sliding-sync feature flag

crates/matrix-sdk-ui/src/timeline/item.rs
It is more practical to use
```rust
match item.kind() {
…
}
```
than
```rust
if let Some(event) = item.as_event() {
…
} else if let Some(virtual) = item.as_virtual() {
…
}
```
=> ui: Expose the kind of a TimelineItem

bindings/matrix-sdk-ffi/src/room.rs, crates/matrix-sdk/src/room/joined/mod.rs
This allows to actually check for permissions (like canRedact, canBan, canSendState...) at room level by just specifying the userID.
=> feat(bindings): PowerLevels permission checks all exposed also at the room level

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This implements an approximate computation of the `limited` flag, given a sliding sync response. For each room, mark the room's part of the response as limited, if and only if:
- it's an `initial` response,
- and the `timeline` in the response contains no events common with the known, locally stored `timeline`.
The general assumption seems to be that it's ok to have false positives there, i.e. we're marking a room as being limited while it's not. The worst that will happen is that the client will do more calls to fill gaps that don't exist, and the timeline should be able to handle duplicates already.
Fixes #2261.
=> feat: emulate `limited` flag in sliding sync responses

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/client.rs, bindings/matrix-sdk-ffi/src/error.rs, bindings/matrix-sdk-ffi/src/lib.rs, bindings/matrix-sdk-ffi/src/sync_service.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/sync_service/mod.rs
Just renames `App` to `SyncService`. Hesitated with `SyncLoopService`, but already too much paint has been thrown at the bike shed, and _any_ name is better than `App` :upside_down_face:
=> chore: rename `App` to `SyncService`

bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/sync_service.rs, crates/matrix-sdk-ui/src/sync_service/mod.rs
- get rid of `RoomListService::is_syncing`; on the one hand it's slightly confusing in itself (because it considers that it's not syncing while in init state, which is eyebrow-raising worthy at the bare minimum), but now it's also incorrect to look at this state if used with the `App` API. The encryption sync may be stopped and cause a stop of the `App` stream, but the room list service's SS would only be interrupted slightly later, causing some confusing race conditions. Fixes #2247.
- don't automatically start the `App` upon creation. After feedback from both @ganfra and @stefanceriu this is more confusing than helpful.
- add `App::current_state` to provide the current application's state, in addition to the state subscriber. Both are useful at different times, and having both makes it …
=> Small improvements to `App` API

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml
Uses a forked and improved version for `tracing-android` as a temporary measure to have readable logs in Android. Ideally, we should move to [paranoid-android](https://crates.io/crates/paranoid-android) in the near future, but we're in a bit of a hurry to have proper logs in Android.
=> Use forked `tracing-android` to have readable logs in Android

benchmarks/benches/store_bench.rs, crates/matrix-sdk-base/src/store/memory_store.rs, crates/matrix-sdk-crypto/src/store/caches.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs
There's a few more changes possible in this direction, but this gets rid of most of the unnecessary reference counting in the stores.
=> Remove redundant fine-grained reference counting for memory stores

Cargo.lock, Cargo.toml
… so we get log events whenever an `ObservableVector` is updated, with affected indices.
=> Bump eyeball-im, enable its tracing feature

.github/workflows/bindings_ci.yml, .github/workflows/ci.yml, .github/workflows/documentation.yml
This is what tonic, the dependency that needs `protoc`, does in its CI.
The action previously used was generating warnings.
=> ci: Use taiki-e/install-action to install protoc

bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/platform.rs
Wanted to switch from tracing-android to paranoid-android, ran out of time for today.
=> ffi: Simplify regular (non-OTLP) tracing initialization

crates/matrix-sdk-ui/src/room_list_service/mod.rs
In `RoomListService`, there is a cache over the `Room`s to avoid re- computing them every time the user calls `RoomListService::room`. It also allows async operations to have time to finish while the user jumps back to the room list and so on.
When reading this cache, which is `matrix_sdk_common::RingBuffer`, `RingBuffer::iter` is used with `Iter::find` to find if the `Room` exists in the cache. The cache has a size of 128 (given by `ROOM_OBJECT_CACHE_SIZE`), which is quite large.
`Iter::find` will iterate from the oldest to the newest room in the cache, but realistically, I reckon we need to iterate from the newest to the oldest room. Indeed, the app user is more likely to jump between recently opened rooms more frequently, thus saving quite a lot of iterations for usual cases.
One may …
=> feat(ui): Look for `Room` in the ring buffer from the newest instead of the oldest

bindings/matrix-sdk-ffi/src/room.rs
Since we seem to have a problem with futures being leaked in Kotlin, which can otherwise lead to deadlocks.
=> ffi: Spawn tokio tasks for async code that locks async mutexes

crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/store/mod.rs
=> Mark our public part of the user identity as verified if we import the private part

bindings/matrix-sdk-ffi/src/notification_settings.rs, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/room_list.rs, bindings/matrix-sdk-ffi/src/session_verification.rs
… as a workaround for cancellation being broken in UniFFI.
Specifically:
- Before this change, cancelling a future from the foreign code would (apparently) **leak** it, meaning that it would no longer be polled but it wouldn't be dropped either, so any shared resources held by that future would never be released.
- After this change, cancelling a future from the foreign code will only leak a join handle and possibly some UniFFI state, but the main Rust future will just continue running. This is not ideal, but avoids deadlocks.
=> ffi: Spawn tokio tasks for the remaining async fns

bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/src/timeline/event_handler.rs, crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner.rs, crates/matrix-sdk-ui/src/timeline/tests/mod.rs, crates/matrix-sdk-ui/src/timeline/tests/redaction.rs, crates/matrix-sdk-ui/src/timeline/traits.rs, crates/matrix-sdk-ui/tests/integration/encryption_sync.rs
… and more in-reply-to / redaction improvements.
Ready for testing in EX, needs one or two tests before merging.
=> ui: Redact replied-to event inside in_reply_to in timeline

bindings/matrix-sdk-ffi/src/authentication_service.rs, bindings/matrix-sdk-ffi/src/client_builder.rs, crates/matrix-sdk/src/client/builder.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/lib.rs
This slightly changes the public API of `ClientBuilder` to introduce a new method `server_name_with_protocol`, that allows specifying the protocol along the server name.
As a reminder: `homeserver_url` will use the URL as is, while `server_name` does the well-known fetching and discover the actual underlying homeserver based on that. The server name didn't include the protocol, and it was assumed that the server would be reachable via HTTPS all the time... except for testing purposes, where we assumed we always tested with Wiremock which only does HTTP.
This makes the whole setup more explicit by allowing (optionally) to set the protocol along the server name. This is also wired in FFI, and as such should fix #2312.
=> feat(FFI): allow specifying a protocol along a server name

crates/matrix-sdk/src/sliding_sync/mod.rs
Due to popular request, we're adding this; it would also make debugging sliding sync requests likely easier for everyone.
=> feat(sliding sync): include the connection id in the tracing context

bindings/matrix-sdk-ffi/Cargo.toml, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/lib.rs, crates/matrix-sdk-ui/src/timeline/builder.rs, crates/matrix-sdk-ui/src/timeline/event_item/content.rs, crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk-ui/tests/integration/main.rs, crates/matrix-sdk-ui/tests/integration/timeline/mod.rs
As discussed, we think the entire UI crate should be considered experimental. We've also observed a proliferation of feature flags there (many of those are my wrong doings, sorry). Since the one internal user (FFI) of that crate enabled all experimental features, it seems fine to make them all default, while not providing any extra stability guarantee based on that action.
=> chore: remove all experimental features on the UI crate

bindings/matrix-sdk-ffi/src/event.rs, bindings/matrix-sdk-ffi/src/timeline.rs
Simply adds FFI message types and their associated structs for poll events
---
We already have a working implementation based on this, but it needs the [ruma PR](https://github.com/ruma/ruma/pull/1589) landed etc. Committing just these binding stubs will unblock the client-side development that is relying on this functionality.
=> Define FFI API for `m.poll.start` and `m.poll.end`

crates/matrix-sdk/src/encryption/mod.rs
Even if the two issues are likely caused by the same root cause (the user not being authenticated), they should be used in different contexts, in my understanding:
- the authentication required error should happen only during HTTP requests
- the absence of olm machine should be signalled when we try to get one and it's not been initialized yet
This has caused a bit of confusion when looking at debug traces today, so this patches fixes it.
=> chore(encryption): replace some `AuthenticationRequired` errors with `NoOlmMachine`

crates/matrix-sdk/src/sliding_sync/list/builder.rs
Address #1911.
The batch subscriber exists in `matrix_sdk_ui::RoomList` (https://github.com/matrix-org/matrix-rust-sdk/pull/2322) instead of being added here.
We must keep the observable capacity to 4096, but the `TODO` is no longer relevant.
Why keeping the capacity to 4096? Because if the batch subscriber (in `RoomList`) isn't “listened” quickly, we don't want to get a `Reset`.
=> chore(sdk): Remove one `TODO` in Sliding Sync

.typos.toml, Cargo.lock, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
Address #1911.
This patch implements a new pre-defined filter for room list entries: `room_list_service::filters::fuzzy_match_room_name`.
The idea is that all filters can be build via a `new_filter` function, which produces a closure `Fn(&RoomListEntry) -> bool + Send + Sync + 'static`.
For `fuzzy_match_room_name`, I'm using [`fuzzy_matcher`](https://github.com/lotabout/fuzzy-matcher) from the [`skim`](https://github.com/lotabout/skim) project. It's battle-tested and widely used via `skim`. However, it works on `char`, and no Unicode transformations are applied. So, looking for _stf_ won't match _Ștefan_ —even with smart case/ignore case— for instance, because _S_ is different from _Ș_.
So before matching the pattern over the subject, we apply some transformations. I wanted to do some …
=> feat(ui): Implement the “fuzzy match room name” filter

Cargo.lock, Cargo.toml, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/room.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2306.
Blocked by:
* https://github.com/ruma/ruma/pull/1607.
This patch can be reviewed commit-by-commit.
This patch implements `matrix_sdk::SlidingSyncRoom::avatar_url`. Then it implements `matrix_sdk_ui::room_list_service::Room::avatar_url`. Finally, it updates `matrix_sdk_ffi::RoomListItem::avatar_url`.
This avatar URL comes from a Sliding Sync room response.
=> feat(sdk+ui+ffi): Implement `(SlidingSyncRoom|Room|RoomListItem)::avatar_url`

crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs, crates/matrix-sdk/src/room/mod.rs
Because of another bug, we could have a race condition where the `OlmMachine` would get invalidated between presharing room keys and encrypting a message. This would cause the `OlmMachine` cache to be invalidated, and in particular the outgoing sessions caches, making it impossible to send messages thereafter.
This includes a regression test showing the suite of events that would lead to this, and that fails on `main` right now, with `thread 'tokio-runtime-worker' panicked at 'Session wasn't created nor shared', /Users/alfogrillo/element-projects/matrix-rust-sdk/crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs:205:50`.
The fix has been contributed by @poljar, thanks!
=> fix(crypto): don't rely on outgoing sessions being in cache when encrypting a message

crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/encryption/mod.rs
In multiprocess scenarios, to know whether another process wrote in the crypto store while we were inactive/sleeping, we look at a generation counter stored in the database, comparing it against the latest value we knew about. If the latest value we knew about and the value stored in the crypto store aren't the same, we consider it a mismatch and will regenerate the entire OlmMachine (until we get finer-grained caches in the OlmMachine).
Of course, this works fine only if the generation counter lives *outside* the OlmMachine, otherwise any attempt at taking the lock will result in a mismatch, blowing up the olm machine and its generation counter, and the next time we try to lock we'll incorrectly conclude that there was a mismatch again. The only consequence should be purely about …
=> fix(crypto): store the generation counter in the `Client`, not the `OlmMachine`

crates/matrix-sdk/src/room/mod.rs
This should make the test less flaky.
=> chore(test): don't use the same database name in multiple tests

crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
This reduces log levels in the sdk-base crate when processing a sliding sync, and also changes a bit the sliding sync logs:
- include the `conn_id` at the stream level, not the `sync_once` level (that's a child scope of the stream)
- also include whether e2ee is enabled at the stream level
- shorten most static logs
- remove duplicate "sending request" logs
=> chore(sliding sync): Tweak tracing logs and context

crates/matrix-sdk-ui/src/timeline/event_item/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/state.rs, crates/matrix-sdk-ui/src/timeline/item.rs, crates/matrix-sdk-ui/tests/integration/timeline/queue.rs
This is especially important for ones that failed to send (or ones that fail post timeline clearing), since there is no way to retry them otherwise.
Closes #2334.
=> ui: Keep local echoes when clearing timeline

bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk-crypto/README.md, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/requests.rs, crates/matrix-sdk-crypto/src/store/memorystore.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/store/traits.rs, crates/matrix-sdk-indexeddb/src/crypto_store.rs, crates/matrix-sdk-sqlite/src/crypto_store.rs, crates/matrix-sdk-ui/tests/integration/encryption_sync.rs, crates/matrix-sdk/src/encryption/mod.rs, crates/matrix-sdk/src/sliding_sync/cache.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
Before this, it was saved in the state store. Because Element iOS can read and write to it from different processes (b/o the notification process), we did write it into the state store and reload it *on every single request*. With the sliding sync happening in notifications in https://github.com/matrix-org/matrix-rust-sdk/pull/2252, an in-memory state store will be used in place of the on-disk one; that means we'd lose access to the previous delta tokens, if we kept the current scheme.
This PR makes it so that the delta-token is now stored in the crypto store. As an "in-app" migration path, if we find it was missing from the crypto-store, we try to read it from the state-store. Later writes will put it into the crypto-store anyways, where it's preferably read from.
=> feat(sliding sync): store the to-device `next_batch` token in the crypto store

crates/matrix-sdk-ui/src/timeline/inner/mod.rs
Currently EX-ios is a bit over-eager with calling this, this is a quick fix so we don't do pointless extra work (though ideally the app would also make sure not to call this function too often).
=> ui: Deduplicate in-reply-to fetching

crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rules.rs, testing/matrix-sdk-test/src/lib.rs, testing/matrix-sdk-test/src/notification_settings/mod.rs
With this PR:
- `is_user_mention_enabled()` now returns the value of the new push rule `.m.rule.is_user_mention` if the rule exists. Previously, the value of the new push rule was only returned if it was enabled.
- `is_room_mention_enabled()` now returns the value of the new push rule `.m.rule.is_room_mention` if the rule exists. Previously, the value of the new push rule was only returned if it was enabled.
The previous implementation was problematic because setting `is_room_mention_enabled()` to `false` actually makes 2 API calls:
- One disabling the new push rule `.m.rule.is_room_mention`
- One disabling the deprecated rule `.m.rule.roomnotif` 
And the client app was seeing the room mention enabled after the first call because the previous implementation was returning the state of the …
=> Fix `is_user_mention_enabled` and `is_room_mention_enabled`

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/matrix_auth/mod.rs
It does the same as `restore_session` now. Thanks @zecakeh for finding this out!
=> chore: get rid of `Client::inherit_session`

Cargo.lock, Cargo.toml
Because we are fixing a subtle bug with Kotlin and async code.
=> chore: Update UniFFI fork

crates/matrix-sdk/src/authentication.rs, examples/persist_session/src/main.rs
It turns out not all authentication API sessions (i.e. OIDC) are fully (de)serializable. So this removes the derive ahead of #1019.
=> sdk: Don't derive (De)serialize for AuthSession

crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/timeline/inner/mod.rs, crates/matrix-sdk-ui/src/timeline/mod.rs, crates/matrix-sdk/src/sliding_sync/mod.rs, testing/matrix-sdk-integration-testing/Cargo.toml
I wanted to do more than this, but it's really not clear how to proceed.
This allows running matrix-sdk-ui integration tests with just `cargo test -p matrix-sdk-ui`, instead of `cargo test -p matrix-sdk-ui --features testing`.
An alternative to just making these functions public would be to make them public and `#[doc(hidden)]`.
=> Remove the 'testing' feature from matrix-sdk-ui

crates/matrix-sdk-ui/src/room_list_service/mod.rs
Address #1911.
Now is a good time to re-enable the cache :-).
=> feat(ui): Turn on cached list for `SlidingSync` in `RoomListService`

crates/matrix-sdk/src/client/futures.rs, crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/error.rs, crates/matrix-sdk/src/matrix_auth/mod.rs, crates/matrix-sdk/tests/integration/refresh_token.rs
Since other authentication APIs won't interact with the Matrix API in `Client::refresh_access_token()`, it makes more sense to change the variants and use it as the return type than `HttpError`.
The second commit is just a small fix in the area.
=> sdk: Make RefreshTokenError authentication API-agnostic 

bindings/matrix-sdk-ffi/src/notification_settings.rs, crates/matrix-sdk/src/notification_settings/command.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rule_commands.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This PR is part of https://github.com/matrix-org/matrix-rust-sdk/issues/1959 implementation.
It exposes, in the `notification_settings` crate, a function to define the default notification mode for a given room type (the type is defined by whether the room is encrypted or a direct discussion).
=> Allow to define the default notification mode for a given room type

Cargo.lock, Cargo.toml, bindings/matrix-sdk-crypto-ffi/src/dehydrated_devices.rs, bindings/matrix-sdk-crypto-ffi/src/lib.rs, bindings/matrix-sdk-crypto-ffi/src/machine.rs, crates/matrix-sdk-crypto/CHANGELOG.md, crates/matrix-sdk-crypto/Cargo.toml, crates/matrix-sdk-crypto/src/dehydrated_devices.rs, crates/matrix-sdk-crypto/src/gossiping/machine.rs, crates/matrix-sdk-crypto/src/identities/manager.rs, crates/matrix-sdk-crypto/src/identities/user.rs, crates/matrix-sdk-crypto/src/lib.rs, crates/matrix-sdk-crypto/src/machine.rs, crates/matrix-sdk-crypto/src/olm/account.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/inbound.rs, crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs, crates/matrix-sdk-crypto/src/olm/mod.rs, crates/matrix-sdk-crypto/src/olm/signing/mod.rs, crates/matrix-sdk-crypto/src/session_manager/sessions.rs, crates/matrix-sdk-crypto/src/store/integration_tests.rs, crates/matrix-sdk-crypto/src/store/mod.rs, crates/matrix-sdk-crypto/src/verification/machine.rs, crates/matrix-sdk-crypto/src/verification/mod.rs, crates/matrix-sdk-crypto/src/verification/qrcode.rs, crates/matrix-sdk-crypto/src/verification/sas/mod.rs, crates/matrix-sdk-crypto/src/verification/sas/sas_state.rs
This PR adds initial support for [MSC3814]. This is best reviewed commit by
commit.
It's best to get an overview of the MSC first, the docs in the
`dehydrated_devices` submodule attempt to explain dehydrated devices as well.
This closes: #401.
[MSC3814]: https://github.com/uhoreg/matrix-doc/blob/shrivelled_sessions/proposals/3814-dehydrated-devices-with-ssss.md
=> Support for MSC3814 - Dehydrated devices v2

Cargo.lock, bindings/matrix-sdk-ffi/src/room_list.rs, crates/matrix-sdk-ui/Cargo.toml, crates/matrix-sdk-ui/src/room_list_service/filters/all.rs, crates/matrix-sdk-ui/src/room_list_service/filters/fuzzy_match_room_name.rs, crates/matrix-sdk-ui/src/room_list_service/filters/mod.rs, crates/matrix-sdk-ui/src/room_list_service/mod.rs, crates/matrix-sdk-ui/src/room_list_service/room_list.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/list/mod.rs
Address #1911.
Thanks for @jplatte for his collaboration on this patch.
This patch can be reviewed commit-by-commit, but a one-diff review is also doable I guess.
On FFI side:
* `RoomList::entries` is now infallible,
* `RoomList::entries_with_dynamic_filter` has been implemented. It returns a stream + a `RoomListDynamicFilter` object, which has a single method: `set`. It accepts `RoomListDynamicFilterKind` value, which is an enum with `All` or `FuzzyMatchRoomName` variants.
Why this design? Because it allows the client-app to use `entries` if it provides a single “static” room list, or `entries_with_dynamic_filter` if it considers to filter the list with various filters. The client-app doesn't have to call `entries` or `entries_with_dynamic_filter` alternatively, it can just switch …
=> feat(ui): Implement `RoomList::entries_with_dynamic_filter`

crates/matrix-sdk/src/sliding_sync/room.rs
@stefanceriu said we could have a problem with `avatar` inside `FrozenSlidingSyncRoom`.
This patch tests this part specifically. This patch also updates some `tokio::test` to `async_test`.
Spoiler: there is no problem in this part specifically.
=> test(sdk): Ensure that `avatar` is serialized as expected in `FrozenSlidingSyncRoom`

crates/matrix-sdk-ui/tests/integration/room_list_service.rs, crates/matrix-sdk/src/sliding_sync/builder.rs, crates/matrix-sdk/src/sliding_sync/error.rs, crates/matrix-sdk/src/sliding_sync/mod.rs
A Sliding Sync `v4::Response` contains a `pos` value. It helps to identify progress during several requests/responses. If two requests with the same `pos` are sent, the server **must** reply with the same response, as defined in the specification.
The corollary is: If a response contains a `pos` that has already been received, the client **must** ignore it, otherwise it can create duplications. For example, let a response containing sync operations, like `DELETE` or `INSERT`, with indexes: if this pair of operations are repeated twice with the same index, it creates a broken state.
To avoid this behaviour, this patch stores the last 20 position markers received from the server. If a response contains a `pos` that has already been received, a (new) error is returned. As with all the other …
=> feat(sdk): Skip Sliding Sync `Response` if it's been received already

bindings/matrix-sdk-ffi/src/notification_settings.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This PR adds the following features on notification settings:
**sdk+ffi: Get all room IDs for which a user-defined rule exists.**
This allows the client app to list all rooms for which a user-defined notification mode exists.
**ffi: Get the user-defined notification mode for a room.**
This allows to get the user-defined notification mode (if any) with just the `room_id` (without needing to know the encryption status or the members count).
This will allow the client app to display the user-defined mode in the list above.
=> sdk+ffi: Get the user-defined notification mode for a room and all rooms for which a user-defined rule exists.

bindings/matrix-sdk-ffi/src/notification_settings.rs, crates/matrix-sdk/src/notification_settings/mod.rs, crates/matrix-sdk/src/notification_settings/rules.rs
This PR removes the need to pass the active members count to the ffi layer of the notification parameters. 
The active members count was used to hide the fact that, from a push rule perspective, a `one-to-one` room is a room with exactly two members, but ultimately this adds unnecessary complexity.
=> sdk+ffi: in notification settings, replace `members_count` by `is_one_to_one` for more clarity

crates/matrix-sdk-ui/src/room_list_service/state.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
This patch tries to fix https://github.com/vector-im/element-x-ios/issues/1204 by adding the following required states in the `visible_rooms` sliding sync list: `m.room.member: $LAZY`.
=> fix(ui): Add `m.room.member: $LAZY` in the require states of `visible_rooms`

crates/matrix-sdk-ui/tests/integration/notification_client.rs
The types used here are not implementing `Clone`, so calling `clone` on them` copies the reference, which does not do anything and can be removed.
=> chore: Remove unnecessary clones

crates/matrix-sdk-ui/src/notification_client.rs
The timeouts were a bit too agressive, according to some user logs, resulting in failing to load the event mentioned in the notification.
Here's the rationale for the new timeouts: we're only limited by the iOS process which has *at most* 30 seconds to process a notification.
- We're running at most 3 requests of the notification sliding sync, so that will be (1+3)*3 = 12 seconds allocated for that.
- If we've found an event but it required decryption, we're running the encryption sync up to 2 times, (3+4) seconds each => 14 seconds.
At most we're eating up 26 seconds of the entire time, leaving some ballast for the rest of the program.
=> feat(notification client): bump sliding sync timeouts

Cargo.lock, bindings/matrix-sdk-ffi/Cargo.toml, bindings/matrix-sdk-ffi/src/room.rs, bindings/matrix-sdk-ffi/src/timeline.rs, crates/matrix-sdk-ui/Cargo.toml
Fix https://github.com/matrix-org/matrix-rust-sdk/issues/2388
Body example for`PUT _matrix/client/v3/rooms/{room-id}/send/org.matrix.msc3381.poll.start`
```json
{
"org.matrix.msc1767.text": "Do you like polls?\n1. Yes\n2. No\n3. Maybe",
"org.matrix.msc3381.poll.start": {
"answers": [
{
"id": "0",
"org.matrix.msc1767.text": "Yes"
},
{
"id": "1",
"org.matrix.msc1767.text": "No"
},
{
"id": "2",
"org.matrix.msc1767.text": "Maybe"
}
],
"kind": "org.matrix.msc3381.poll.disclosed",
"max_selections": 2,
"question": {
"org.matrix.msc1767.text": "Do you like polls?"
}
}
}
```
=> feat(ffi) Add create poll API

crates/matrix-sdk/src/client/mod.rs, crates/matrix-sdk/src/room/mod.rs, crates/matrix-sdk/tests/integration/client.rs
This PR tackles some issues we had in our `Room::is_encrypted` method.
This PR closes: https://github.com/vector-im/crypto-internal/issues/135
Commit 1: Fixing `Room::is_encrypted` bug
We fix a bug in `Room::is_encrypted` that was messing up result. This result is
crucial to avoid the sending of unencrypted events in encrypted rooms.
Commit 2: Race-Free `Room::request_encryption_state`
We remove a minor race condition in Room::request_encryption_state. DashMap
caused issues when multiple calls stepped on each other. We switched things up
with a mutex and BTreeMap to keep things consistent.
Commit 3: Testing `Room::is_encrypted` behavior
We add a test to double-check `Room::is_encrypted` behaves now as expected.
Commit 4: Instrumenting `Room::send_raw`
The PR should be reviewed commit by …
=> Fix the `Room::is_encrypted` method

crates/matrix-sdk-ui/src/timeline/tests/echo.rs
This patch improves the `remote_echo_full_trip` `Timeline` test to ensure that until the event reaches the `Sent` state, it is indeed a local echo.
=> test(ui): Improve the `remote_echo_full_trip` test

crates/matrix-sdk-ui/src/room_list_service/room.rs, crates/matrix-sdk-ui/tests/integration/room_list_service.rs
Fixes https://github.com/matrix-org/matrix-rust-sdk/issues/2303.
Closes https://github.com/vector-im/element-x-ios/issues/1294.
This patch updates `Room::latest_event` to return the `Timeline` local event if any.
First off, it starts by checking if a `Timeline` exists. It won't create it if it doesn't exist! Second, it checks whether a latest event exists.
This patch also updates the tests accordingly.
=> feat(ui): `Room::latest_event` returns the `Timeline` local event if any

crates/matrix-sdk-ui/src/timeline/event_handler.rs
This patch removes a `TODO`.
The issue https://github.com/matrix-org/sliding-sync/issues/3 has been fixed. It's safe to raise the `trace!` into an `error!` now.
=> chore(ui): Raise a `trace` log into an `error`

crates/matrix-sdk-ui/src/room_list_service/mod.rs
`matrix_sdk_ui::room_list_service::Error` has a `SlidingSync` variant to report errors from `matrix_sdk::sliding_sync::Error` (to be more exact, from `matrix_sdk::Error::SlidingSync`).
This patch updates the error message from `SlidingSync failed` to `SlidingSync failed: <explanation>`, where `<explanation>` is the `Display` representation of the inner error.
It will help to provide more details to the end-user when looking at logs.
=> chore(ui): Improve error description for `Error::SlidingSync`

crates/matrix-sdk-base/src/client.rs, crates/matrix-sdk-base/src/sliding_sync.rs, crates/matrix-sdk/tests/integration/room/joined.rs
OK so here is the story.
In `matrix_sdk_base`, we extend the `BaseClient` to add `SlidingSync` feature. Among many things, we map a `SlidingSyncResponse` into a `SyncResponse`, and we update all the inner types like `Room` etc.
In #2300, @poljar [has noticed that we have a `FIXME` in our code](https://github.com/matrix-org/matrix-rust-sdk/issues/2300#issuecomment-1661836252) saying that any room that isn't in an `Invite` state is considered `Join`. It misses one case: `Left`. Technically, what the code does is: either the room is in `Invite` state, and we do our stuff, or we create a new room in a `Join` state, and update the room's state based on the `required_state` provided in the `SlidingSyncResponse`.
From here, I've started to investigate with @pixlwave (thanks!). We have noticed …
=> fix(base): Detect left room in `SlidingSyncResponse`

crates/matrix-sdk/src/sliding_sync/mod.rs
This patch can be reviewed commit-by-commit.
All errors inside `SlidingSync` are stopping the sync-loop, and errors
are returned to the caller. However, in some situation, some errors
should be ignored, i.e. they should not stop the sync-loop and they
should not be returned to the caller: the sync-loop just continues to
run. The first commit does that for `Error::ResponseAlreadyReceived`.
The second commit does that for `Error::Http` where it's a timeout.
Why is it annoying? When `matrix_sdk_ui::SyncService` sees an error,
it stops all the sync-loops (`RoomListService`, `EncryptionSync`…) and
restarts them properly. In the case of `Error::ResponseAlreadyReceived`,
this is a waste of time and resources. This error is an error from the
`SlidingSync` point of view, but _not_ from the caller …
=> feat(sdk): `SlidingSync` is able to “ignore” some errors
